### ISSUE TITLE
[EKS]: Kubernetes v1.14 End of Support (Dec 8, 2020)

### ISSUE THREAD

**Issue by endrec** [aws/containers-roadmap#1001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
At the time of writing [Amazon EKS version deprecation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation) does not say that 1.14 is deprecated, however I get a warning on my exeisting cluster to update now:
![image](https://user-images.githubusercontent.com/101801/88925409-6457d480-d26c-11ea-9784-f3439469c1f2.png)

I would like to now when does the support end for 1.14, so I can plan my upgrades.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to now when does the support end for 1.14, so I can plan my upgrades.

**Are you currently working around this issue?**
No, there is no workaround for this issue. Currently I'm sitting in fear, and checking the website multiple times a day...

**Comment by mikestef9** [comment]
We are working on a date for this, as well some other updates to our version strategy based on feedback we've been hearing. We will give at least 60 days notice from the date we announce, to the end of support date.

**Comment by endrec** [comment]
Thanks @mikestef9 for the correct answer, the only problem is that I (and probably thousand of fellow OPS people) got a heart attack seeing that message on our current clusters, and had a panic attack after we did not find a date anywhere. In my opinion that message should not be shown till there is no end of support date set. Maybe a different wording would work better, to tell us that we don't need to worry just yet, we will have enough time to worry later. :smiley:

**Comment by TiloGit** [comment]
also what is the best way to subscribe to the EOS announcements? GitHub filter/search? on https://aws.amazon.com/blogs/aws/?

**Comment by TiloGit** [comment]
here my quick query of Git: 

`https://github.com/aws/containers-roadmap/issues?q=is%3Aissue++Kubernetes++End+of+Support+in%3Atitle++label%3AEKS+`

**Comment by TiloGit** [comment]
maybe we can have something like this: 
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar

**Comment by trueskawka** [comment]
Thanks @endrec for bringing up the issue!

Glad to hear you're working towards clearer communication @mikestef9. If you're changing the way you're communicating, could you also make it clear what exactly happens on deprecation? 

It's been ~6 weeks since the announcement of `1.17` and the only reliable info my team could work off was the previous announcement for `1.16` - https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-eks-now-supports-kubernetes-version-1-16/.

Based on that we assumed the worst-case scenario:
- deprecation would happen after 60 days from the announcement
- if we do not update our clusters, AWS will do it for us - which was the more stressful part of the deprecation process

**Comment by mikestef9** [comment]
We have updated our documentation, please take a look

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by TiloGit** [comment]
that is great. thanks @mikestef9 . 
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

Looks like AWS will support 6 to 7 version until 1.15 is out of support. (assume you pump out 1 or 2 two more between Dec 2020 and May 2021. 


Kubernetes version | Upstream release | Amazon EKS release | Amazon EKS end of support
-- | -- | -- | --
1.14 | 3/25/2019 | 9/4/2019 | 11/2020
1.15 | 6/19/2019 | 3/10/2020 | 5/2021
1.16 | 9/8/2019 | 4/30/2020 | 7/2021
1.17 | 12/9/2019 | 7/10/2020 | 9/2021
1.18 | 3/23/2020 | 10/2020 | 11/2021
1.19 | 8/26/2020 | 12/2020 | 1/2022
