### ISSUE TITLE
New EKS region: London

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#101]
support EKS in eu-west-2

**Comment by abby-fuller** [comment]
this also resolves https://github.com/aws/containers-roadmap/issues/41

**Comment by jsamuel1** [comment]
@abby-fuller is there an unofficial timeline you are aiming for with London deployment?   (Keenly awaiting, as we are working around lack of London at the moment :)    )

**Comment by BenCoughlan15** [comment]
AFAIK, from our business contact at Amazon, EKS will be launched in a number of regions in the next week including London, Paris, Montreal, Mumbai, Sao Paolo and San Francisco.

Really hope this is true :)

**Comment by tabern** [comment]
Shipped! https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-eks-available-in-mumbai--london--and-paris-aws-regions/

**Comment by xinshang-iai** [comment]
Any chance EKS will be available in Montreal (ca-central-1) soon?
