### ISSUE TITLE
[Fargate] [Bug] ECS Fargate Platform 1.4: Empty Env Variable Regression

### ISSUE THREAD

**Issue by thenadz** [aws/containers-roadmap#1010]
### Summary
When we revved the underlying fargate platform for our previously functional clusters, we ran into issues where code relying on env variables being present stopped working if the env variable was being set to empty value. This is a behavior change since 1.3, where empty environment variables were initialized for the cluster containers.

### Description
See summary.

### Expected Behavior
All environment variables, regardless of being empty or not, are initialized in container's environment.

### Observed Behavior
All non-empty variables are initialized in container's environment.

**Comment by SaloniSonpal** [comment]
@thenadz - A fix for this was recently deployed, so closing this issue. Let us know if you still continue to see the issue and we'd be happy to look into it.
