### ISSUE TITLE
[EKS] [Windows]: Connect to Cluster Windows nodes

### ISSUE THREAD

**Issue by iusergii** [aws/containers-roadmap#1015]
**Tell us about your request**
For debugging purpose I'd like to be able to connect to Windows Nodes ( RDP, WinRM )

**Additional context**
Please correct me if I'm wrong but I haven't found any documentation for AMI description except the list of [IDs](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html).

**Comment by casey-robertson** [comment]
You can use SSM for this?  that's what we've been doing for Windows nodes.

**Comment by goyalpurvi** [comment]
@iusergii Have you tried using this to connect to Windows nodes: https://docs.aws.amazon.com/systems-manager/latest/userguide/fleet-rdp.html? Please feel free to reopen if this doesnt meet your needs.
