### ISSUE TITLE
[EKS] Track application pods costs through AWS Cost Explorer

### ISSUE THREAD

**Issue by rakesh-nd** [aws/containers-roadmap#1021]
I want to track the application pods costs through cost explorer. Is there a way to connect the pods directly to aws cost explorer ?

**Comment by nwsparks** [comment]
Also interested in this. Its particularly problematic for EKS Fargate as there's absolutely no simple way to identify what's driving costs.

There is this, https://aws.amazon.com/blogs/containers/track-costs-with-detailed-billing-reports-for-amazon-eks-on-aws-fargate/ but it's slow, clunky, and definitely not simple.

**Comment by barryib** [comment]
For info pod costs are now shipped to AWS CUR https://aws.amazon.com/fr/blogs/aws-cloud-financial-management/improve-cost-visibility-of-amazon-eks-with-aws-split-cost-allocation-data/

**Comment by vipin-mohan** [comment]
Granular cost visibility for EKS in the AWS Cost and Usage Reports (CUR) is now available. Customers can aggregate costs by cluster, namespace, and other Kubernetes primitives, and allocate costs to individual business units or teams for chargeback purposes.

What's New Post: https://aws.amazon.com/about-aws/whats-new/2024/04/aws-split-cost-allocation-data-amazon-eks/
Launch blog: https://aws.amazon.com/blogs/aws-cloud-financial-management/improve-cost-visibility-of-amazon-eks-with-aws-split-cost-allocation-data/

**Comment by vipin-mohan** [comment]
Granular cost visibility for EKS in the AWS Cost and Usage Reports (CUR) is now available. Customers can aggregate costs by cluster, namespace, and other Kubernetes primitives, and allocate costs to individual business units or teams for chargeback purposes.

What's New Post: https://aws.amazon.com/about-aws/whats-new/2024/04/aws-split-cost-allocation-data-amazon-eks/
Launch blog: https://aws.amazon.com/blogs/aws-cloud-financial-management/improve-cost-visibility-of-amazon-eks-with-aws-split-cost-allocation-data/
