### ISSUE TITLE
[ECR] [request]: `aws ecr get-login-password` should allow passing `--registry-id` or `--registry-ids`

### ISSUE THREAD

**Issue by mkielar** [aws/containers-roadmap#1024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
In https://github.com/aws/containers-roadmap/issues/717 you've added `get-login-password` command to ECR, however it only allows for generating passwords for "current" AWS Account (i.e. the one current `AWS_PROFILE` points to). This does not allow multi-account logins using `get-login-password`.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In my scenario I need ot be logged in to two registries at the same time, as my base image is in one registry, whereas I'm pushing my image to another. 

**Are you currently working around this issue?**
Currently I still need to use `aws ecr get-login --registry-ids <ACCOUNT1> <ACCOUNT2>` instead of `aws ecr get-login-password`.

**Comment by rpnguyen** [comment]
@mkielar Thanks for the request! Is it possible to replace the `--registry-ids` command with this sequence of commands?

```
# Deprecated command
$(aws ecr get-login --region <region> --no-include-email --registry-ids 111111111111 222222222222)

# New command
aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin 111111111111.dkr.ecr.<region>.amazonaws.com
aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin 222222222222.dkr.ecr.<region>.amazonaws.com
```
