### ISSUE TITLE
[EKS]: single-zone node group

### ISSUE THREAD

**Issue by aviau** [aws/containers-roadmap#1029]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please allow us to deploy single-zone node groups.

I have a database that uses static disk provisioning. It requires a node that is on us-east-1a because that is where the volume is.

**Comment by thundergolfer** [comment]
I might be wrong, but isn't this already possible?

We run multiple node groups scoped to single availability zones. It is discussed a bit here under _"Create an Amazon EKS Cluster"_ https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

**Comment by mikestef9** [comment]
Yes this is possible today, and a common use case for batch and ML workload. Closing
