### ISSUE TITLE
[EKS] [request]: Live zone update for EKS cluster

### ISSUE THREAD

**Issue by GwonsooLee** [aws/containers-roadmap#1032]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
When a new zone opens in the region, we tend to use it for many reasons(fault-tolerant, more options for instances etc..)
But currently, if I want to add subnet of new zone, I should destroy the cluster and create new one. I am not sure if this is possible or not, but it would be better if I could update our eks cluster to use new zone without destroying itself. 

If I am wrong with this, then please correct me~! Thanks in advance

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to use ap-northeast-2d zone without recreating the existing cluster.

**Are you currently working around this issue?**
No current solution known to us.

**Additional context**
Anything else we should know?
I tried to update eks cluster with terraform and I will update this 
```
 # module.eks-cluster.aws_eks_cluster.eks_master must be replaced
-/+ resource "aws_eks_cluster" "eks_master" {
      ~ arn                       = "arn:aws:eks:ap-northeast-2:xxxxxxxx:cluster/eks-dev-apne2" -> (known after apply)
      ~ created_at                = "2020-07-23 09:47:53 +0000 UTC" -> (known after apply)
      - enabled_cluster_log_types = [] -> null
      ~ id                        = "eks-wed-apne2" -> (known after apply)
        name                      = "eks-dev-apne2"
      ~ platform_version          = "eks.2" -> (known after apply)
        role_arn                  = "arn:aws:iam::xxxxxxxx:role/eks-dev-apne2"
      ~ status                    = "ACTIVE" -> (known after apply)
      - tags                      = {} -> null
      ~ version                   = "1.16" -> (known after apply)

      ~ vpc_config {
          ~ cluster_security_group_id = "sg-XXXXXX" -> (known after apply)
            endpoint_private_access   = true
            endpoint_public_access    = true
          ~ subnet_ids                = [ # forces replacement
                "subnet-XXXXXX",
              + "subnet-~~~", # new one
                "subnet-YYYYYY",
            ]
          ~ vpc_id                    = "vpc-xxxxxxxxx" -> (known after apply)
        }
    }

```
**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
@GwonsooLee the subnets associated with the EKS cluster are only used for the cross account ENIs. For an existing cluster, you can add new subnets in other AZs for worker nodes simply by adding the required tags https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-subnet-tagging

**Comment by GwonsooLee** [comment]
@mikestef9 Thanks for explaining!
By the way, what do mean by ` only used for the cross account ENIs`...?

**Comment by mreferre** [comment]
@GwonsooLee the control plane (which runs in AWS accounts) manifests itself to the user via the cross account ENI (that's your worker nodes can talk to it). Given all communications in the VPC across subnets is allowed (routing and SG wise) it doesn't matter which subnets the cross account ENIs are plugged in and which subnets the worker nodes are deployed on. They can all talk to each others regardless.

**Comment by mikestef9** [comment]
This blog helps explain the EKS cluster networking setup as well https://aws.amazon.com/blogs/containers/de-mystifying-cluster-networking-for-amazon-eks-worker-nodes/

**Comment by GwonsooLee** [comment]
@mreferre @mikestef9  Thanks for your explanation! I understood it wrong... I will close this issue :)
