### ISSUE TITLE
[EKS] [FARGATE]: Support in Seoul region

### ISSUE THREAD

**Issue by channy** [aws/containers-roadmap#1042]
at Seoul ( ap-northeast-2 ) region has lots of kubernetes users also. 
please support Seoul region.
And fargate solution always good and cool feature.  I love it

_Originally posted by @JoosungJin in https://github.com/aws/containers-roadmap/issues/620#issuecomment-666147912_

**Comment by seapy** [comment]
This is very important for our business. 

We can't migration to EKS, if EKS Farget seoul region support is not available.

**Comment by tabern** [comment]
EKS/Fargate is now available in Seoul (ap-northeast-2)

[Documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html)
