### ISSUE TITLE
[ECR] [request]: Custom domain

### ISSUE THREAD

**Issue by mg98** [aws/containers-roadmap#1065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Getting able to have a domain pointing to the ECR repository url or endpoint. For example as an ALIAS or CNAME DNS record in Route53.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In case your environment changes, for example you change AWS accounts or you re-apply your infrastructure, the endpoint to ECR changes. This means I have to update my CI files to the new one. If I was able to just create a subdomain, like registry.mycompany.com on-the-go, when I'm applying my infrastructure over TerraForm for example, it would be a lot more convenient.

**Are you currently working around this issue?**
I update the ECR endpoint in my CI or Readme files, when it changes.

**Comment by RichiCoder1** [comment]
This is a duplicate of https://github.com/aws/containers-roadmap/issues/299 no?

**Comment by mg98** [comment]
Right.
