### ISSUE TITLE
[EKS] [request]: windows VPC resource controller does not support C5a instance types

### ISSUE THREAD

**Issue by jjjms** [aws/containers-roadmap#1066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

 
**Tell us about your request**
At present while launching workernode of family c5a, it results in newly created node having vpc.amazonaws.com/PrivateIPv4Addres set to "0".

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
windows VPC resource controller to  support C5a instance types

**Are you currently working around this issue?**
no workarounds on this

**Additional context**
A sample eksctl config file to replicate the issue: 
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-2
  version: '1.17'
managedNodeGroups:
  - name: linux-ng
    instanceType: t2.large
    minSize: 2

nodeGroups:
  - name: windows-ng
    instanceType: c5a.large
    minSize: 2
    volumeSize: 100
    amiFamily: WindowsServer2019FullContainer

**Comment by dschunack** [comment]
Any News Here?
