### ISSUE TITLE
[Fargate] [request]: Compute Optimizer support

### ISSUE THREAD

**Issue by gvasquez95** [aws/containers-roadmap#1073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary
Add Compute Optimizer support for Fargate

### Problem
Since the Compute Optimizer launch, we've been using that service for correct sizing of EC2 instances based on actual usage (automated CloudWatch metrics analysis behind the scenes). But, since we started transitioning from EC2 to Fargate, we are missing such a helpful tool to assist in correct tuning.

**Are you currently working around this issue?**
Currently, we are doing a manual metrics analysis to rightsize the RAM/CPU parameters.

PS: A similar check on Trusted Advisor might also help, like the one that flags Low Usage EC2 instances.

**Comment by mreferre** [comment]
Thanks @gvasquez95. This is not the first time we hear this and the Compute Optimizer team is interested in exploring this further. I'll reach out to you off-line to start a conversation around how you use today Compute Optimizer and what you would like to use when applied to Fargate. 

BTW, in an effort to intercept some of these requirements and create some sort of prototype of what an optimizer for Fargate would look like, I created this sample project: https://github.com/mreferre/container-insights-custom-dashboards . This is not intended to be a replacement for a Compute Optimizer for Fargate but rather a prototype to collect feedback about how a real product should look like and what it should be doing.

**Comment by RyanFrench** [comment]
I would also like to see similar functionality for ECS. We have a lot of containers that our engineers have lifted and shifted without really considering the resources required. A compute optimizer for both Fargate and ECS that took into consideration CPU/Memory and Network traffic would be a huge benefit to us.

**Comment by gvasquez95** [comment]
@RyanFrench kind of the same problem nature on our side, as lift and shift is the first migration step out of EC2.

**Comment by omieomye** [comment]
Thanks for your patience. This is something we've begun work on.

**Comment by ollypom** [comment]
A quick update, Compute Optimizer for AWS Fargate launched in Dec 2022.

- [Whats New post](https://aws.amazon.com/about-aws/whats-new/2022/12/aws-compute-optimizer-amazon-ecs-services-aws-fargate/. )
- [Docs](https://docs.aws.amazon.com/compute-optimizer/latest/ug/view-ecs-recommendations.html)
- Quick demo on a recent [containers from the couch episode](https://www.youtube.com/live/Osi9Nmj3C9Y?feature=share&t=660).
