### ISSUE TITLE
OCI Artifact Support In Amazon ECR - unexpected status: 500 Internal Server Error

### ISSUE THREAD

**Issue by quater** [aws/containers-roadmap#1074]
We have been using Oras in conjunction with the GitLab registry for a couple of months now. We were excited when we read issue https://github.com/aws/containers-roadmap/issues/308 that ECR supports OCI artifacts now.

Unfortunately, this does not appear to work. We have followed the AWS blog post https://aws.amazon.com/blogs/containers/oci-artifact-support-in-amazon-ecr/ to the tee and also tried with a number of regions "**ap-southeast-2**", "**eu-west-1**" and **"us-east-1**" and in all cases we get the error:

**Error: failed commit on ref "unknown-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855": unexpected status: 500 Internal Server Error**

```BASH
# Follow the instructions for Oras at https://aws.amazon.com/blogs/containers/oci-artifact-support-in-amazon-ecr/ to create the OPA bundle.

export OPA_BUNDLE=opa-temporal-0;
export OPA_MEDIA_TYPE_LAYER=application/vnd.cncf.openpolicyagent.manifest.layer.v1+json;
export OPA_MEDIA_TYPE_CONFIG=/dev/null:application/vnd.cncf.openpolicyagent.config.v1+json;
oras push -u AWS -p $(aws ecr get-login-password --region us-east-1) \
     111111111111.dkr.ecr.us-east-1.amazonaws.com/test2:$OPA_BUNDLE \
     --manifest-config $OPA_MEDIA_TYPE_CONFIG \
     bundle.tar.gz:$OPA_MEDIA_TYPE_LAYER
Uploading e54db36692ee bundle.tar.gz
Error: failed commit on ref "unknown-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855": unexpected status: 500 Internal Server Error
```
> Note: The above command had the AWS account number replaced with "111111111111".

**Comment by mhausenblas** [comment]
Thanks for bringing this to my attention! Could you do me a favour and try the following: rather than `/dev/null` use a file `empty-config.json` with the content `{}` and report back if you still see the same behaviour?

**Comment by mhausenblas** [comment]
@quater I've updated our blog post with the instructions:

```
...
echo '{}' > empty-config.json
OPA_MEDIA_TYPE_CONFIG=empty-config.json:application/vnd.cncf.openpolicyagent.config.v1+json
```

Note that in the fullness of time we plan to support `/dev/null` as well. Can you please check and tell me if this works for you now?

**Comment by Javirln** [comment]
Hello, sorry to comment on a closed issue.

I've just wanted to know if custom OCI config media types is something supported at the moment on AWS ECR? We are aiming to push custom OCI artifacts to AWS ECR that we can do right now but, only if the default mediaType for the config file is used: application/vnd.unknown.config.v1+json.

It basically means that it's failing every time we try to push an artifact with a custom mediaType.
