### ISSUE TITLE
[EKS ARM] [Documentation] Update documentation for EFS + EBS CSI driver support

### ISSUE THREAD

**Issue by scottmalkie** [aws/containers-roadmap#1077]
Please let us know how we can improve the [EKS ARM preview program](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview). This can be a bug report, feature, or functionality request.

**Describe the issue**
Both the documentation pages for the[ EBS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) and the [EFS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) specifically call out Arm nodes as being not supported, however PRs have been merged upstream for [EBS](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/527) and [EFS](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/241) support.

**Additional context**
Also as Arm support is GA, we can probably remove the "ARM Preview Feedback" issue template.

**Comment by mikestef9** [comment]
Resolved. Thx for the report!
