### ISSUE TITLE
Enhanced ECS GPU support

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#11]
Enhanced support for GPUs in ECS: The ability to run GPU workloads on top of p2/p3 instances. 

GPU support will offer:
* The ability to designate the number of GPUs on a per container basis in Task Definitions for placement consideration. 
* Pinning of GPUs to containers orchestrated by the ECS Agent. 
* An ECS GPU Optimized AMI with Nvidia drivers, a docker nvidia compatible run-time and a default version of CUDA.

**Comment by abby-fuller** [comment]
shipped 2/4!  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html

**Comment by lou-k** [comment]
The docs cover p2 & p3s, any chance it will work on g2s?

**Comment by rtsio** [comment]
@abby-fuller could you comment on whether G3 will ever be supported? We're making a decision for our cluster GPUs based on what ECS supports, or will support in the future.
