### ISSUE TITLE
[ECS] [request]: restrict usage of public images in ECS task definition 

### ISSUE THREAD

**Issue by nameprabhat** [aws/containers-roadmap#1117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Looking for a way to restrict use of public docker images in ECS cluster task definition.  Only wants to allow the use of ECR images in task definition.

**Which service(s) is this request for?**
ECS task definition 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Have not implemented any workaround for it. 

**Are you currently working around this issue?**
May implement VPC proxy to block connections for "index.docker.io"(docker hub)

**Additional context**
There is currently no way to setup this restriction on ECS cluster.

**Comment by coultn** [comment]
You should be able to control this by using [ECR PrivateLink](https://aws.amazon.com/blogs/compute/setting-up-aws-privatelink-for-amazon-ecs-and-amazon-ecr/) and not allowing outbound network connections.
