### ISSUE TITLE
New EKS region: São Paulo

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#112]
Support EKS in sa-east-1

**Comment by luizcarraro** [comment]
Hi there folks! Any ideia when we might expect this to be available in Brazil?

**Comment by wesleyfantinel** [comment]
For those who want to play with Kubernetes on AWS without paying extra only for the managing panel, check out [kops](https://github.com/kubernetes/kops).

**Comment by hubner** [comment]
> For those who want to play with Kubernetes on AWS without paying extra only for the managing panel, check out [kops](https://github.com/kubernetes/kops).

Running Kops successfully in sa-east-1 with only 2 AZs. Due to etcd quorum, master nodes should run all together in one single AZ, each node inside one AGS (one ASG for one master node). In the case of an AZ failure, master nodes will be recreated in the remaining AZ (that might take some time depending on your instances) but service and applications will continue to run fine in the worker nodes (as long as you make sure they are evenly distributed in the two AZs). Highly recommended. I've tested other options (RKE, Kubespray, Conjure.up, etc.). Kops was the best.

**Comment by robsonalves** [comment]
Do you guys have any date to launch this sevice in sa-east-1?

**Comment by lfpalacios** [comment]
Any idea for release date? Tks

**Comment by franciscotbjr** [comment]
Any idea for release date? Tks

**Comment by thiagolsfortunato** [comment]
look this: https://github.com/weaveworks/eksctl/pull/1403

**Comment by hubner** [comment]
EKS for sa-east-1 is just around the corner and pretty much ready to be officially launched. I've recently tested it for a customer and it's working just fine (see attached screenshot). 

Probably related, it also appears that AWS will re-open the 1b AZ. This AZ was constrained/closed long time ago (more than 2 years if I'm not wrong). As for the e-mail I've received (see attached screenshot too), this may happen tomorrow (16/10/2019). Fingers crossed.

![eks-sa-east-1](https://user-images.githubusercontent.com/1842962/66871356-d8ddb300-ef79-11e9-8379-c4d67f25f52f.png)
![aws-1b-az-back](https://user-images.githubusercontent.com/1842962/66871357-d8ddb300-ef79-11e9-9525-3ba1e1eb5f2f.png)

**Comment by hubner** [comment]
And just to add more suspense, AWS Brasil deleted a tweet from 08/10 where they announced EKS as available in sa-east-1. Nonetheless way-back-machine captured the (good) news:


http://web.archive.org/web/20191008132024/https:/twitter.com/AWSBrasil/status/1181557107801432065

**Comment by tabern** [comment]
Happy to announce that EKS is now generally available in the AWS São Paulo (sa-east-1) region!

* [What's new post](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eks-generally-available-in-sao-paulo-region/)
* [EKS documentation & AMIs](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html)
* **eksctl** - creating clusters in sa-east-1 is supported with eksctl starting with [version 0.7.0](https://github.com/weaveworks/eksctl/releases)
