### ISSUE TITLE
[Fargate] [request]: Fargate PV 1.4.0 fail with "CannotPullContainerError: failed to find a descriptor for platform {linux/amd64}"

### ISSUE THREAD

**Issue by parikshitataws** [aws/containers-roadmap#1120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
Fargate PV 1.4.0 & ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Fargate version 1.4 fail's to run a container image with error:

 `"CannotPullContainerError: failed to find a descriptor for platform {linux/amd64}"`

Same image works fine with ECS EC2 Launch type or Fargate 1.3.0

**Are you currently working around this issue?**

Build image with --format=docker :
`buildah bud --format=docker -f Dockerfile -t 064250592128.dkr.ecr.ap-southeast-2.amazonaws.com/centosbybuildah:docker .`

Push image with --format=docker :
`buildah push --format=docker 064250592128.dkr.ecr.ap-southeast-2.amazonaws.com/centosbybuildah:pushdocker`

One can use Docker instead where possible. 

**Additional context**
Image created and pushed with buildah (buildah bud) OR podman (which under the hood use buildah code to build image), are failing with Fargate Platform Version 1.4.0 with error :

"CannotPullContainerError: failed to find a descriptor for platform {linux/amd64}"

Steps to reproduce :
Step 1 :
On Ubuntu Server 18.04 LTS (HVM), SSD Volume Type instance, install Buildah :
```
sudo apt update -y
uname -r
. /etc/os-release
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update -qq
sudo apt-get -qq -y install buildah
```
Step 2 : Build and push image to ECR :
```
buildah bud -t 064250592128.dkr.ecr.ap-southeast-2.amazonaws.com/centosbybuildah .
aws ecr get-login --no-include-email --region ap-southeast-2
buildah login -u AWS -p <copy password from above>
buildah push 064250592128.dkr.ecr.ap-southeast-2.amazonaws.com/centosbybuildah
```
Step 3 :
Run Fargate PV 1.4.0 Task using above image, it will fail with following error :
`"CannotPullContainerError: failed to find a descriptor for platform {linux/amd64}"`

Same image works with PV 1.3.0. OR EC2 launch type as its using Docker with is more forgiving in pulling image.

Step 4 - FIX : Build/Push with "--format=docker" to make it work :

Build image with --format=docker :
`buildah bud --format=docker -f Dockerfile -t 064250592128.dkr.ecr.ap-southeast-2.amazonaws.com/centosbybuildah:docker .`

Push image with --format=docker :
`buildah push --format=docker 064250592128.dkr.ecr.ap-southeast-2.amazonaws.com/centosbybuildah:pushdocker`

Root cause :
Currently as on this writing, On Fargate PV 1.4.0 fails because it wants to comply with OCI image spec in favour of checking platform field.

As per OCI Image spec :

https://github.com/opencontainers/image-spec/blob/master/descriptor.md
https://github.com/opencontainers/image-spec/blob/master/image-index.md#image-index-property-descriptions
"Descriptors pointing to application/vnd.oci.image.manifest.v1+json SHOULD include the extended field platform, see Image Index Property Descriptions for details."

buildah by default use oci version hence `PutImage` API goes out with

`"imageManifestMediaType": "application/vnd.oci.image.manifest.v1+json"`

But if we use `--format=docker` then PutImage API goes out with hence it works :
`"imageManifestMediaType": "application/vnd.docker.distribution.manifest.v2+json"`

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by SaloniSonpal** [comment]
The fix for parsing of image descriptors with OCI manifest has been deployed.
