### ISSUE TITLE
[ECR] [request]: Add 'retain' action to life cycle policy

### ISSUE THREAD

**Issue by zhaomengru2015** [aws/containers-roadmap#1129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Which service(s) is this request for?**
 ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We want to use lifeCycle policy to clean up images without disrupting the product. We have a lot of services using ECR to store images, and different services have different using patterns. At the very beginning, we want to use the following rules to only keep 10 images in ECR:
```shell
{
    "rulePriority": 1,
     "description": "Keep only 10 tagged image, expire all others"
     "selection": {
         "tagStatus": "tagged",
         "countType": "imageCountMoreThan",
         "countNumber": 10
      },
     "action": {
         "type": "expire"
     }
}
```

But we realized that we have some services, which though actively developed and pushed images to ECR, but only release to production every few months. If we apply the rules as above, the image which is used in current production will much likely be cleaned because there are a bunch of images pushed later than it. So if the ECR life cycle policy can support like:
```shell
{
  "rulePriority": 1,
   "description": "Retain images newer than 180 days",
   "selection": {
        "tagStatus": "tagged",
        "countType": "sinceImagePushed",
         "countUnit": "days",
         "countNumber": 180
    },
    "action": {
         "type": "retain"
     }
},
{
    "rulePriority": 2,
     "description": "Keep only 10 tagged image, expire all others"
     "selection": {
         "tagStatus": "tagged",
         "countType": "imageCountMoreThan",
         "countNumber": 10
      },
     "action": {
         "type": "expire"
     }
}
```
to only expire images older than 180 days.

**Are you currently working around this issue?**
We currently not solve this issue with current lifecycle policy.

**Comment by rpnguyen** [comment]
One way to express this would be to have a lifecycle policy rule match tag 'latest' with expire imageCountMoreThan 1. Then, any further rules will not expire your 'latest' image. Would that work for your use case?

> An image that matches the tagging requirements of a rule cannot be expired by a rule with a lower priority. [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html)
