### ISSUE TITLE
New EKS Region: Canada Central

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#113]
EKS in ca-central-1

**Comment by pienio7** [comment]
Hey, when EKS Canada will be available?

**Comment by rtkgjacobs** [comment]
+1

**Comment by paulkendobnc** [comment]
Any information on this? 
Thanks

**Comment by jmellor** [comment]
This seems to be taking a lot longer than expected.  What is the new estimated availability date?

**Comment by AndrzejKomarnicki** [comment]
Frustrating that almost every other region is getting EKS before Montreal...AWS needs to step up their game in Canada.

**Comment by mbelang** [comment]
EKS needs 3 AZs to be working. So all Region with at least 3 AZs have EKS and all other products that requires 3 AZs... But yeah I need EKS in Canada for compliance reasons and it is still not available....

**Comment by tmbell** [comment]
mbelang:
 > But yeah I need EKS in Canada for compliance reasons and it is still not available....

I have the same issue, I want to start leveraging the power of EKS, but compliance requirements keep me in Canada

**Comment by mkameni** [comment]
finally when EKS will be available in Canada ?

**Comment by selslack** [comment]
Any updates?

**Comment by vparekh94** [comment]
Hey any update on this? Can we get some sort of timeline?

**Comment by springroll12** [comment]
Any update or timeline on this? Are we waiting on a 3rd AZ for ca-central? Any reason this was moved back to `We're Working on it` ?

Similar to others, we have a client who would like to explore EKS with compliance requirements dictating that it be hosted in Canada.

**Comment by BenCoughlan15** [comment]
AFAIK the next possible date will be Q4 2019, in time for the RE:invent. 👍

**Comment by springroll12** [comment]
Thanks for the update. Any idea what the odds are on hitting that target? It's really difficult to make the argument to stay on AWS and use something like ECS in the interim...

**Comment by yingmu52** [comment]
I would love to get my hands on EKS :). any updates?

**Comment by mikestef9** [comment]
Happy to announce that EKS is now generally available in the AWS Canada (ca-central-1) region!

* [What's new post](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-eks-now-available-in-the-canada-central-region/)
* [EKS documentation & AMIs](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html)
