### ISSUE TITLE
[EKS] [request]: Manage CoreDNS nodeAffinity with CloudFormation

### ISSUE THREAD

**Issue by MitchellJeppson** [aws/containers-roadmap#1131]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
CloudFormation resources to configure CoreDNS deployment at EKS creation. In particular the ability to configure nodeAffinity of CoreDNS. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Our cluster has two classes of worker nodes, say classA and classB. We only want CoreDNS to run on the classA nodes. Currently we deploy the cluster then edit the CoreDNS deployment to add our customized nodeAffinity, then add worker nodes of both classes.

**Are you currently working around this issue?**
Explained above.

**Comment by mikestef9** [comment]
Closing as this is now possible with the EKS addon
