### ISSUE TITLE
[EKS] [request]: Add new EKS 1.18 platform with k8s >= 1.18.9

### ISSUE THREAD

**Issue by nicolas-geniteau** [aws/containers-roadmap#1132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Last EKS platform for 1.18 is eks.1 with kubernetes version 1.18.8.
Would it be possible to create a new EKS platform with a kubernetes version update >= 1.18.9 ?

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I currently have this issue:
https://github.com/kubernetes/kubernetes/issues/90512
which is solved with kubernetes  >= 1.18.9

**Are you currently working around this issue?**
We are planning to create new clusters in 1.17 ... :(

**Comment by tabern** [comment]
done!

The latest EKS platform version `eks.2` now supports Kubernetes 1.18.9 - [EKS platform version documentation](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html)
