### ISSUE TITLE
[EKS] [request]: Feature request to auto-replace worker nodes that go into NotReady status

### ISSUE THREAD

**Issue by jeremyjpaws** [aws/containers-roadmap#1140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
A way to have both self managed and managed node groups, automatically replace nodes that go into NotReady status for a length of time.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
A problem can arise if a node group has many nodes go into NotReady status, such as production downtime. Many nodes can go from Ready => NotReady if say, they're all in the same AZ and the AZ goes down. Or, if all nodes have similar software running with a memory leak, and so system health issues occur at the same time across all nodes even in a multi-AZ setup. Or if nodes log in a similar manner, and so a disk full issue occurs.

Outside EKS, it is relatively easy to leverage existing features of ASGs and ELBs to replace EC2 instances that fail some kind of health check. But EKS doesn't have a feature that bridges Kubernetes to leverage such an existing solution; all existing Kubernetes health checks are within a pod context and not a node context.

**Are you currently working around this issue?**
At the moment there doesn't seem to be a great workaround. A multi-nodegroup architecture can alleviate production risk. In theory, a very clever custom Lambda function could do a custom healthcheck leveraging the k8s API and AWS API to query for node status, and flag each node/EC2 as unhealthy to an ASG. But this seems tedious to attempt.

**Comment by mikestef9** [comment]
Closing this one out with the launch EKS Node Health Monitoring and Auto-Repair

- [What's New](https://aws.amazon.com/about-aws/whats-new/2024/12/node-health-monitoring-auto-repair-amazon-eks/)
- [Docs](https://docs.aws.amazon.com/eks/latest/userguide/node-health.html)
