### ISSUE TITLE
[EKS]: Support for Asia Pacific (Osaka) Region

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#1142]
Amazon EKS support in Asia Pacific (Osaka) Region - `ap-northeast-3`. 

Related to [Osaka becoming a standard AWS region](https://aws.amazon.com/about-aws/whats-new/2020/01/aws-to-launch-standard-aws-region-in-osaka-in-early-2021/)

**Comment by kirtichandak** [comment]
EKS is now available in the Asia Pacific (Osaka) Region - ap-northeast-3.
