### ISSUE TITLE
[ECS] [request]: Capacity Providers should be aware of proactive ASG Capacity Rebalancing

### ISSUE THREAD

**Issue by arlofaria** [aws/containers-roadmap#1143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
An ECS cluster's Capacity Provider and/or service should be aware of the Capacity Rebalancing functionality of an Autoscaling Group.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Autoscaling Groups recently added [support for Capacity Rebalancing](https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html), which will proactively terminate a spot instance after provisioning a replacement -- rather than reactively terminating it with a 2-minute warning.  However, it seems that ECS is unaware of this capability and so the instance termination is rather abrupt.  Using the ECS cluster's Capacity Provider's managed termination protection functionality doesn't seem to apply in this case, as it's not a matter of the ASG scaling in.  It'd be nice if the ECS could somehow notice the proactive Capacity Rebalancing signal and then trigger a task stop (i.e. send a SIGTERM to the essential container(s)).

**Are you currently working around this issue?**
Currently, we have to either disable the Capacity Rebalancing feature or deal with the possibility of very abrupt instance termination.

**Additional context**
It seems Capacity Rebalancing is a very new feature for the ASG.

**Comment by uname-yang** [comment]
@arlofaria I met this problem too.

In my case, the rebalancing action did notice the ECS, but there is a problem with using ALB & ECS together.  Our task can get the kill signal, but the ALB seems not ready to deregister the task at that time. SO there will be a short time range that ALB sending the requests to the killed ECS instance.
And I try to add a sleep time in the task ENTRYPOINT script to solve the problem, for example:
```
#!/bin/bash
# set -x

## Sigterm Handler
sigterm_handler() {
    if [ $pid -ne 0 ]; then
        echo >&3 "PID[$pid] SLEEP 29s"
        sleep 29
        echo >&3 "PID[$pid] CODE[143] SIGTERM"
        kill -SIGTERM "$pid"
        wait "$pid"
    fi
    exit 143; # 128 + 15 -- SIGTERM
}

## Sigquit Handler
sigquit_handler() {
    if [ $pid -ne 0 ]; then
        echo >&3 "PID[$pid] SLEEP 29s"
        sleep 29
        echo >&3 "PID[$pid] CODE[131] SIGQUIT"
        kill -SIGQUIT "$pid" # https://docs.docker.com/engine/reference/builder/#stopsignal
        wait "$pid"
    fi
    exit 131; # 128 + 3 -- SIGQUIT
}

## Setup signal trap
# on callback execute the specified handler
trap 'sigterm_handler' SIGTERM
trap 'sigquit_handler' SIGQUIT

## Start Process
# run process in background and record PID
"$@" &

pid="$!"
echo >&3 "running command[$pid]: $@ "

## Wait forever until app dies
wait "$pid"
return_code="$?"

echo >&3 "return code: $return_code"
# echo the return code of the application
exit $return_code
```

It can overcome the problem in most of the rebalance events, except this one: [rebalancing & scaling hit]

```
At 2023-02-11Txx:xx:xxZ instances were launched to balance instances in zones us-east-1c us-east-1d with other zones resulting in more than desired number of instances in the group. At 2023-02-11Txx:xx:xxZ an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 10 to 9. At 2023-02-11T20:55:07Z instance i-0766*******f190 was selected for termination.
```

I found a solution: create a lifecycle Hook to trigger lambda function that will deregister the instance from the ALB before terminating. https://github.com/aws-samples/aws-lambda-lifecycle-hooks-function  But I have not try it yet. hope it works.

@anoopkapoor  Do we have any update on this request?  It seems a simpler, automated strategy is needed in here.

**Comment by AbhishekNautiyal** [comment]
With the launch of Amazon ECS Managed Instance Draining in Jan '24 (https://github.com/aws/containers-roadmap/issues/256), ECS automatically drains any EC2 instance undergoing termination, including termination from ASG capacity rebalancing. Please refer to the [What's New](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-managed-instance-draining/), [blog](https://community.aws/content/2bMN99heQOCAAkJDC7wwB6ObVyx/manage/), and [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-instance-draining.html) 

Let us know if you experience any issues.
