### ISSUE TITLE
[EKS] [request]: Allow updating EKS control-plane additional security group(s) without recreating the EKS cluster

### ISSUE THREAD

**Issue by rocketspacer** [aws/containers-roadmap#1148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I want to update the list of additional security groups that EKS attaches to the control plane cross-account ENIs, without recreating the EKS cluster.
![image](https://user-images.githubusercontent.com/17026876/99940656-922ad100-2da7-11eb-96c1-16435ab24ac2.png)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
My EKS default cluster security group ran out of rules. I need additional security groups so I can add more rules.

**Are you currently working around this issue?**
Currently, I'm filtering out the EKS control plane ENIs and manually attach new security groups on them. Since this can be done quite easily on the console, I think it's fair we have this as an automated option in EKS.

**Additional context**
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
Closing as duplicate of #738. This is a feature request we plan to address in 2021.
