### ISSUE TITLE
[Fargate]: Nitro-backed ECS/Fargate tasks

### ISSUE THREAD

**Issue by senseibaka** [aws/containers-roadmap#116]
**Tell us about your request**
I'd like to be able to run Fargate tasks on Nitro-based infrastructure, as this comes with some networking benefits -- the biggest of which (for me) is the ability to use NLB in a VPC peering scenario.

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The setup/problem is: I have two VPCs, "A" and "B", in a peering relationship, and (due to various requirements/restrictions) I must load balance traffic from applications in VPC A to services running in VPC B.

VPC A contains Lambdas, other apps, and a NLB (which forwards traffic to targets in B).
VPC B contains an ECS cluster running Fargate tasks (which are registered in the NLB's target group).

Attempts to connect to the NLB in VPC A from a Lambda (also in VPC A) result in timeouts.
Attempts to connect directly to fargate tasks running in VPC B succeed, but obviously this isn't a tenable solution...

**Are you currently working around this issue?**
I'm attempting to work around this issue, but haven't found a good workaround yet...

I've resorted to managing my own cluster using nitro-based EC2 (e.g. m5.large) container instances, but this comes with its own problems:
1) Running the tasks in `awsvpc` networking mode allows the tasks to be accessible from the NLB but the max number of ENIs on the container instances is rather low -- sometimes prohibitively (e.g. when replacing tasks during an upgrade).
2) Running the tasks in `bridge` networking mode bypasses the ENI restriction, but target registration in the NLB fails

Is there something else I've missed which might work?

Cheers,
Nick

**Comment by taylorb-syd** [comment]
Since this feature request was raised it appears that the AWS VPC no longer his this restriction. I cannot see any reference to it in AWS' current documentation. 

@senseibaka Do you want to confirm that non-Nitro issues now work in the situation you've outlined? If they do, we can confidently assume that Fargate tasks will similarly be able to work.

**Comment by senseibaka** [comment]
Hi @taylorb-syd,

Sorry for the delayed response, I finally got around to testing this.
[Here's the testing cfn stack I wrote.](https://gist.github.com/senseibaka/fe4fb0e642a7254c0d0dcc4540d5a96b)

Happy to say, fargate appears to support this situation now!
