### ISSUE TITLE
[EKS]: Support EFS CSI driver as add-ons

### ISSUE THREAD

**Issue by ckdarby** [aws/containers-roadmap#1169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Provide the EFS CSI driver as an EKS add-on

**Which service(s) is this request for?**
EKS

**Are you currently working around this issue?**
Currently using kubectl or helm to apply the EFS CSI driver as a post step after the EKS cluster is set up and use a pre-cluster terraform to create the EFS volumes themselves as dynamic provisioning isn't supported in the EFS CSI driver.

**Additional context**
Dynamic provisioned EFS volumes should probably get tackled before adding it as an add-on, [seen here](https://github.com/aws/containers-roadmap/issues/891#issuecomment-737450103).

**Comment by mohag** [comment]
A setting for the EFS volume to use would be a decent start as well... (Not sure about the CSI driver, I used efs-provisioner previously)

**Comment by makarov-roman** [comment]
Not sure when it was added, but here it is https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**Comment by mikestef9** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-eks-configure-efs-shared-file-storage/
