### ISSUE TITLE
[ECR Public] [request]: Shared docker authentication between private and public ECR for public pulls

### ISSUE THREAD

**Issue by sparrc** [aws/containers-roadmap#1177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

It would be great if I could authenticate to a single ECR endpoint and be able to do authenticated pulls of both public and private ECR container images. 

**Which service(s) is this request for?**

ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

In our CI system, we have both private ECR container images and public dockerhub images that we pull. To avoid dockerhub throttling, we have written some scripts to pull the public dockerhub images and replicate them in our private ECR registry. This solution works but does add operational overhead.

We would like to migrate the dockerhub images to public ECR, but we can't due to the possibility of being rate-limited.

Because we are already authenticating to private ECR it would be nice if the credentials from this could be used to authenticate and prevent rate-limiting of public ECR pulls.

It seems like docker technically may support caching multiple authentication configurations with the [--config](https://docs.docker.com/engine/reference/commandline/cli/#configuration-files) flag, but it's not as convenient or portable as if ECR itself was able to share a single set of credentials.

**Are you currently working around this issue?**

Pulling and pushing all necessary images to private ECR, avoiding any public registries.

**Comment by omieomye** [comment]
We'll investigate what it takes to use existing ECR auth for ECR Public pulls. Requesting a token from ecr-public to take public repo and public image management actions would still remain as those are currently controlled by IAM. This sounds like it would meet your use case, correct?

**Comment by sparrc** [comment]
yes essentially we'd like for something like this workflow to work:

```bash
# login to ecr once:
aws ecr get-login-password | docker login --password-stdin
# pull an image from our private ECR registry:
docker pull $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/myrepo/image:latest
# pull a public ecr image and have it count as an "authenticated" pull:
docker pull public.ecr.aws/bitnami/golang:1.15.5 
```

**Comment by sparrc** [comment]
Closing because I've come to realize that this can be solved by logging into both something like this:

```
aws ecr get-login-password --region us-west-2 | docker login $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com
aws ecr-public get-login-password --region us-east-1 | docker login public.ecr.aws
```

and docker pull will know which credentials to use based on the pull URL
