### ISSUE TITLE
[eks] [request]: delete the lb when deleting the cluster

### ISSUE THREAD

**Issue by bseenu** [aws/containers-roadmap#1179]
**Tell us about your request**
Deleting eks cluster, should delete the loadbalancers which are created as part of the services in that cluster

**Which service(s) is this request for?**
EKS

**Are you currently working around this issue?**
Manually deleting it by checking the cluster tags

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
Thanks for feature request, closing as this is being tracked under #1044
