### ISSUE TITLE
[EKS] [request]: Service Level Agreement (SLA) for Control Plane

### ISSUE THREAD

**Issue by heidemn** [aws/containers-roadmap#118]
**Tell us about your request**
Web application, including multiple microservices.
Currently running partially on EC2, partially on FarGate.
Two production and two staging environments (each on eu-west-1 and us-east-1).
Planning to move everything to EKS.

**Which service(s) is this request for?**
EKS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Both EC2 and FarGate provide an SLA of 99.99%.
If would be awesome to have the same also for EKS, to be sure that Amazon is committed to fix any operational issues as quickly as possible.
https://aws.amazon.com/compute/sla/

In my understanding, the EKS worker nodes should be covered by the existing EC2 SLA, so this request is specific for the Control Plane managed by AWS.
Once the Control Plane is down, we would't be able to make any changes to the Kubernetes state. E.g. we would not be able to schedule new Pods, or add new Worker nodes.

That's why we're not sure if we should move to EKS at this moment, without any uptime guarantees provided by AWS.
We don't want to reduce the availability of our products.

**Are you currently working around this issue?**
By not using EKS.

**Additional context**
...

**Attachments**
...

**Comment by abby-fuller** [comment]
this is up: https://aws.amazon.com/eks/sla/

**Comment by heidemn** [comment]
Great, that was fast!
Were you waiting for someone to open an issue? ;-)
