### ISSUE TITLE
[ECR] [request]: Enable global/default lifecycle policies for repositories

### ISSUE THREAD

**Issue by iamsudip** [aws/containers-roadmap#1188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for having global/default lifecycle policies which applies to all the repositories in a region or even better if it supports filters based on repo prefix.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Setting up the same policies again and again for each new repository we create feels cumbersome.

**Are you currently working around this issue?**
We try to manage repositories using terraform module (repository creation using the UI/AWS Console takes less time for me btw) which has a few default lifecycle policies.

**Comment by rpnguyen** [comment]
Thanks for the suggestion! This sounds similar to #799, please +1 and add your input there
