### ISSUE TITLE
[ECS] [request]: Restart option for ECS task container dependencies

### ISSUE THREAD

**Issue by besbes** [aws/containers-roadmap#1189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Provide a way to specify that a `ContainerDependency` of an `ECS::TaskDefinition` should be automatically restarted if it crashes while the task is running.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I can specify a number of `ContainerDependency` instances for an `ECS::TaskDefinition`, which we use to start supporting services for running tasks. However, these dependencies' health cannot be managed well from the task: for instance, if a dependency container terminates, there is no way to restart it so that the task can continue. Instead, the task is being stopped because the dependency is no longer present.

**Are you currently working around this issue?**
One workaround is to run the dependency as an ECS service, which makes sure the dependency is always running. However this also implies that the dependency's lifecycle is not coupled to the task's lifecycle, therefore additional management overhead is implied.

**Comment by sparrc** [comment]
hi @besbes, would this feature request also be solved by https://github.com/aws/containers-roadmap/issues/326 ?

**Comment by besbes** [comment]
@sparrc Yes it would!

**Comment by sparrc** [comment]
OK, I will close this issue in favor of #326, might have something to share on that issue soon :)
