### ISSUE TITLE
[ECR] [Replication]: Add an API to get the status of replication for a given image and any failure details

### ISSUE THREAD

**Issue by michaelb990** [aws/containers-roadmap#1193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to query for the status of replication for an image.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This will help understand when images have been replicated, and it is important to diagnose failures.

**Are you currently working around this issue?**
N/A

**Additional context**
This issue was filed by the ECR team. Please let us know if you have a use case for this feature / help us prioritize.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jguionnet** [comment]
another alternative would be to guranatee an SLA like S3 does for example: https://docs.aws.amazon.com/AmazonS3/latest/dev/replication.html

**Comment by srrengar** [comment]
hey everyone, today we launched filtering for cross account and region replication, along with an API to see replication status! 

https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-ecr-replicate-individual-repositories-regions-accounts/
https://aws.amazon.com/blogs/containers/using-amazon-ecr-replication-rules-to-optimize-your-application-delivery-process/
