### ISSUE TITLE
[ECR] [Replication]: Support for replicating manifest lists across regions

### ISSUE THREAD

**Issue by michaelb990** [aws/containers-roadmap#1195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to replicate manifest lists just like we do container images today.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I deploy to multiple architectures and use manifest lists to handle this seamlessly. With replication, we can't replicate the manifest lists today.

**Are you currently working around this issue?**
Deploying by different image tags.

**Additional context**
This issue was filed by the ECR team. Please let us know if you have a use case for this feature / help us prioritize.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mogggggg** [comment]
Hi, just wondering if there's a timeline on roughly when this will be available?

**Comment by smitagu** [comment]
We are working on this. Expect to deploy this later this month/early April.

**Comment by omieomye** [comment]
This is now available.

**Comment by stevejr** [comment]
Is this working in all regions that support cross region replication? I have an image that supports both linux/amd64 and linux/arm64. When I pull the image from the primary region and use `docker buildx imagetools inspect` on the image it shows the correct manifest. When I do the same on the replicated image I do not see a manifest but instead the image layers.

**Comment by michaelb990** [comment]
@stevejr yes, this works across all regions that CRR is enabled for.
