### ISSUE TITLE
[EKS] [request]: Allow adding extra disks to instances when creating managed node groups

### ISSUE THREAD

**Issue by iliastsi** [aws/containers-roadmap#1199]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We would like to be able to specify additional disks that should be attached to instances, during the creation of managed node groups.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When creating a managed node group (either through the AWS Management Console, or `awscli`) there is no way to specify extra disks for the instances. The only option available is to use an **existing** EC2 launch template, but going down that road seems way too difficult and error prone, since the launch template requires specific user data for the nodes to work and join the cluster. We also tried achieving this with self-managed node groups, but we couldn't (see https://github.com/aws/containers-roadmap/issues/1198).

**Comment by mikestef9** [comment]
When using a launch template with managed node groups, you do not have to specify any user data. 

https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data

EKS automatically adds the necessary bootstrap commands for the nodes to join the cluster. So you can create a launch template that just specifies additional EBS volumes.

**Comment by iliastsi** [comment]
Thank you @mikestef9. As you suggested, I created a new launch template with the desired `BlockDeviceMappings` that includes extra EBS volumes for my nodes and used it with the `--launch-template` option of `aws eks create-nodegroup`.

It worked, and my nodes got the additional EBS volumes, so I am going to close this issue. Thanks again.
