### ISSUE TITLE
[ECR] CloudFormation for CRR and SRR

### ISSUE THREAD

**Issue by rnzsgh** [aws/containers-roadmap#1200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
CloudFormation support for both cross-region and same-region replication (i.e., between accounts) repositories.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The ability to fully automate multi-region architectures or disaster recovery environments using CloudFormation.

**Are you currently working around this issue?**
Clicks in the AWS Console, CLI or a CFN Custom Resource

**Additional context**
NA

**Attachments**
NA

**Comment by apurvmahajan** [comment]
ReplicationConfiguration and RegistryPolicy resources are now added to CloudFormation for ECR (Private) Cross Region Replication:
[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECR.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECR.html)
