### ISSUE TITLE
[EKS] [request]: Use systemd cgroupdriver by default

### ISSUE THREAD

**Issue by Callisto13** [aws/containers-roadmap#1210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please start the docker daemon and the kubelet with the `cgroupdriver` set to `systemd` when `systemd` is the init system.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This is standard in the community https://github.com/kubernetes/kubeadm/issues/1394#issuecomment-462878219.

**Are you currently working around this issue?**
We are using cloudconfig/userdata to edit the `kubelet.yaml` and `/etc/docker/daemon.json` (in the case of EKS AMIs), or `/etc/sysconfig/docker` (in the case of accelerated AL2-GPU AMIs, as the `daemon.json` is removed there).

**Additional context**
I believe this is soon to happen in standard EKS AMIs https://github.com/awslabs/amazon-eks-ami/issues/490, but the builder for the accelerated AMIs does not appear to be public. (If there is a public accelerated AMI builder somewhere and it is just particularly well hidden, let me know and I will go PR something 😄  .)

**Comment by reegnz** [comment]
I've reopened the change in https://github.com/awslabs/amazon-eks-ami/pull/593, and that was actually reverted by someone because the change initially broke eksctl. Now that eksctl can work with this change, there should be no problem with making systemd the default cgroup driver in amazon-eks-ami.

**Comment by reegnz** [comment]
@Callisto13 maybe another request issue would be in order to request the GPU AMI-s to also become open-source.

**Comment by josephprem** [comment]
Any thoughts how this can be set in nodegroup launch templates ?

**Comment by josephprem** [comment]
This is what I have put in my userdata

# Docker options set via systemd drop-in files 
mkdir -p /etc/systemd/system/docker.service.d
cat << EOF > /etc/systemd/system/docker.service.d/9999-docker-options.conf
[Service]
Environment="OPTIONS=--icc=false --exec-opt=native.cgroupdriver=systemd"
EOF

# Kubelet extra args set via systemd drop-in files
mkdir -p /etc/systemd/system/kubelet.service.d
cat << EOF > /etc/systemd/system/kubelet.service.d/9999-kubelet-extra-args.conf
[Service]
Environment='KUBELET_EXTRA_ARGS=--cgroup-driver=systemd'
EOF

**Comment by josephprem** [comment]
Hello folks,
Now that containerd can be enabled as cri, looks like we will need to handle ourselves to enable cgroup in /etc/containerd/config.toml. 
It pretty much messy when EKS does not support out of the box to enable these production settings

**Comment by stevehipwell** [comment]
Is there a valid PR for this open? I can see that https://github.com/awslabs/amazon-eks-ami/pull/593 is blocked over concerns over users of older `eksctl` versions. Maybe a PR to only enable this for containerd by adding a _kubelet-config.containerd.json_ file and using _bootstrap.sh_ to swap this in if the containerd runtime is enabled? I assume that older versions of `eksctl` don't support containerd?

**Comment by josephprem** [comment]
@stevehipwell  agree, no clear view if this issue is in backlog.
Not sure why folks talk about eksctl when these requirements should be first addressed natively in EKS AMI's

**Comment by josephprem** [comment]
checkout how I enable  cgroup-driver to systemd when containerd is used as CRI
https://github.com/awslabs/amazon-eks-ami/pull/593#issuecomment-888516579

**Comment by reegnz** [comment]
> @stevehipwell  agree, no clear view if this issue is in backlog.
> Not sure why folks talk about eksctl when these requirements should be first addressed natively in EKS AMI's   

That's exactly what I've been saying... 😒 eksctl is downstream, shouldn't block upstream work.

**Comment by reegnz** [comment]
Can someone open a new PR for this though? The containerd stuff is different enough from my PR to be worked on separately, and I also don't have any capacity to deal with this.

**Comment by josephprem** [comment]
There are three tickets already on this subject. Not sure if a new one should be opened

1. https://github.com/aws/containers-roadmap/issues/1413
2. https://github.com/aws/containers-roadmap/issues/1210
3. https://github.com/aws/containers-roadmap/issues/1118

**Comment by stevehipwell** [comment]
@reegnz I can open a PR to just make the changes for containerd.

**Comment by reegnz** [comment]
@josephprem I don't want a new ticket, just a separate PR for containerd. 

@stevehipwell that would be great!

**Comment by stevehipwell** [comment]
@mikestef9 there is an open PR (https://github.com/awslabs/amazon-eks-ami/pull/717) to add this for containerd, which hasn't had a single maintainer response, and the Docker version (https://github.com/awslabs/amazon-eks-ami/pull/593) appears to be stuck due to concerns with `eksctl`. Could we at least get some sort of feedback on the status of this? It's quite clear in the [Kubernetes documentation](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers) that the systemd driver should be used when systemd is the init system so unless there is a good reason not to do this it should be a priority, especially now that resources not IPs will be the limiting factor for nodes. Furthermore when containerd was introduced as a brand new runtime why was it was setup to use cgroupfs instead of the best practice systemd?

**Comment by stevehipwell** [comment]
@mikestef9 or any of the other maintainers could we get a comment on this?

**Comment by stevehipwell** [comment]
@mikestef9 do you know where this has got to? The AMI PRs had responses a couple of months ago but there has been nothing since.

I'm also interested in the status of cgroup v2 in the EKS optimised AMI? Do we need a new issue opened for this (#1535 is for ECS and I don't think it's AL2 based)?

**Comment by dims** [comment]
- https://github.com/awslabs/amazon-eks-ami/pull/717 has landed. 
- https://github.com/awslabs/amazon-eks-ami/pull/593#issuecomment-1275857845 is a WONT-FIX.

yes, please open another issue for `cgroup v2`

**Comment by stevehipwell** [comment]
See also.

- https://github.com/awslabs/amazon-eks-ami/pull/1051
