### ISSUE TITLE
[Fargate] [Logging]: Being able to get fluentbit logs for Fargate Logging

### ISSUE THREAD

**Issue by lindarr915** [aws/containers-roadmap#1218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When EKS Fargate Logging is enabled, there is no way to get the logs of the underlying fluentbit daemon, making it difficult to troubleshoot configuration or IAM permission issues.       

**Which service(s) is this request for?**
This could be Fargate and EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Like EKS Control Plane logs, provide an option for EKS customers to get the logs of fluentbit to troubleshoot issues. 

**Are you currently working around this issue?**
No 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by AlexeyRaga** [comment]
I am having an issue (logs are not being shipped to ES) and have no clue to how to approach this problem. 
Are there any hints or workarounds? Or anything that can help me understand what is going on?

**Comment by lennartt** [comment]
@AlexeyRaga We have the exact same issue. Did you manage to find a workaround?

**Comment by lennartt** [comment]
@AlexeyRaga Thanks for letting me know! That just saved me a couple of hours.

**Comment by rsumukha** [comment]
Check out `To ship Fluent Bit process logs to your account` part in 
https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html
