### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.13 on Vulnerability Scans

### ISSUE THREAD

**Issue by itchyny** [aws/containers-roadmap#1224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for Alpine 3.13 on vulnerability scans.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Using `alpine:3.13.0` image causes `UnsupportedImageError: The operating system 'alpine' version 'v3.13' is not supported.` on ECR.

**Are you currently working around this issue?**
Using `alpine:3.12.3`, or ignoring the scanning error.

**Comment by heykarthikwithu** [comment]
here's the screenshot.. 
![screenshot-ap-southeast-1 console aws amazon com-2021 01 19-08_20_55](https://user-images.githubusercontent.com/7745441/104981899-82d6a580-5a2f-11eb-8af6-2e64d9934659.png)

**Comment by bradgr** [comment]
Hi,
Are you still getting this UnsupportedImageError for alpine:3.13.0 ?
I have been able to push and scan into that image into ECR successfully on my end.

**Comment by itchyny** [comment]
ECR now shows Complete for scan status so it seems that it supports scanning alpine:3.13. Closing.

**Comment by shaunlandau1973** [comment]
This is still an issue. I just ran a scan and got the error:

Not supported
UnsupportedImageError: The operating system 'alpine' version 'v3.13' is not supported.

**Comment by bradg-aws** [comment]
@shaunlandau1973 Alpine support for v3.13 ended in Nov 2022 ([Alpine docs](https://alpinelinux.org/releases/)) and is no longer supported in either ECR [Basic](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html#image-scan-basic-support-operating-systems) or [Enhanced](https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr) scanning.
