### ISSUE TITLE
[ECR] [request]: support delete image registry API

### ISSUE THREAD

**Issue by ipmb** [aws/containers-roadmap#1229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support [delete image](https://docs.docker.com/registry/spec/api/#deleting-an-image) from the Docker Registry v2 API in private ECR registries.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to use [pack](https://github.com/buildpacks/pack) to build images and upload a cache image to ECR. During the process, I encounter this error:

```
Unable to delete previous cache image: DELETE https://xxx.dkr.ecr.us-east-1.amazonaws.com/v2/ecrrepository-ns9dbfvxadcv/manifests/sha256:a16e6b50e11222fe92b2e1adb357c351b352aed1f165254b56919dec23779a23: unexpected status code 404 Not Found: 404 page not found
```

While researching the issue, I noticed other projects have encountered this as well, see https://github.com/goharbor/harbor/issues/10264.

**Are you currently working around this issue?**
Harbor works around this issue by using the AWS SDK.

`pack` is using `go-containerregistry` (specifically this function https://github.com/google/go-containerregistry/blob/38d292ec4b6203bf86ec7f4540d77fa8adf7ee6b/pkg/v1/remote/delete.go#L26-L57) to interact with the remote repository. It's unlikely that project would accept a custom AWS implementation over the standard registry APIs.

**Comment by jlbutler** [comment]
The manifests endpoint on ECR's OCI / Docker Registry API now supports delete. Thanks for the issue!
