### ISSUE TITLE
[EKS] [request]: enable load reader in cAdvisor

### ISSUE THREAD

**Issue by booleanbetrayal** [aws/containers-roadmap#1230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We would like for cAdvisor metrics to include non-zero `container_cpu_load_average_10s` results for our EKS Fargate cluster. Polling the cAdvisor metrics directly (`kubectl get --raw /api/v1/nodes/<NODE_NAME>/proxy/metrics/cadvisor`) reveals it is always `0`.

**Which service(s) is this request for?**
EKS, Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The cAdvisor metrics are currently working great in a stock EKS Fargate cluster, with the exception of the `container_cpu_load_average_10s` metric, which always returns `0`. This is apparently due to the fact that it [must be explicitly enabled](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#cpu) via `--enable_load_reader=true`.

**Are you currently working around this issue?**
We currently poll load averages directly from the container and are looking into alternatives to cAdvisor to provide these values to metric.

**Additional context**
Perhaps this has performance implications for the node, but seems likely to be minimal. The [top result article on monitoring EKS Fargate](https://aws.amazon.com/blogs/containers/monitoring-amazon-eks-on-aws-fargate-using-prometheus-and-grafana/) explicitly mentions this metric as a supported cAdvisor metric, which felt misleading. It might need updating.

**Attachments**
NA

**Comment by mikestef9** [comment]
Hi @booleanbetrayal 

This flag is not enabled, as it is not supported running inside a network namespace. This [issue](https://github.com/google/cadvisor/issues/1287) has more details. 

We will get the blog post updated to make it more clear that metric is not supported on Fargate. We are also exploring alternatives to expose this kind of information for Fargate pods.

**Comment by booleanbetrayal** [comment]
Thanks for the timely response and underlying issue ref, @mikestef9 ! Hopefully there's a corresponding AWS announcement if any new metrics support gets rolled out.

Closing since there isn't much that can be done about this on your end, atm. Thanks again.
