### ISSUE TITLE
[EKS] [request]: Cloudwatch metrics

### ISSUE THREAD

**Issue by runningman84** [aws/containers-roadmap#124]
**Tell us about your request**
It would be cool to have some metrics about an eks cluster exposed to cloudwatch. For example these metrics could help to understand the load and the status of any given cluster:
* node count (healthy, unhealthy)
* pod count (active, pending, crash, ...)
* cpu reserveration (used, total)
* memory reservation (used, total)
* volume count (active, pending)
* ...

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
These metrics could be easily retrieved from cloud watch without the need for any agent like prometheus. They provide an overall health assessment and long term usage data of the whole cluster. These data could also be used to decide whether the nodes are under or over utilized (integration in trused advisor is also a good idea).  

Right now most users rely on software like prometheus which is running within the same cluster. An outside view would help even in situations where most nodes are down or software like prometheus does not work anymore.

It would also help you guys to provide some general stats on the eks console similar to the current ecs stats. Right now eks is a blackbox compared to ecs in the aws console.

**Are you currently working around this issue?**
There is no solution right now.

**Comment by max-rocket-internet** [comment]
100% and perhaps also some statistics from the k8s API itself. e.g. API response times and request rate would be good.

**Comment by jldork** [comment]
I believe the new release of Cloudwatch Container Insights covers the first part: 

- [Container Insights Docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html)
- [List of Metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics.html)

Doesn't seem to include API response times and request rate though.

**Comment by runningman84** [comment]
If these metrics are billed like custom metrics this could be a very expressive solution.

**Comment by mikestef9** [comment]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html
