### ISSUE TITLE
[EKS] [request]: Support Kubernetes 1.20

### ISSUE THREAD

**Issue by gitizenme** [aws/containers-roadmap#1244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Support Kubernetes 1.20

**Which service(s) is this request for?**
EKS

**Comment by lloydchang** [comment]
@mikestef9 In April, will this progress to Coming Soon, then Just Shipped? Thanks.
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/kubernetes-versions.md#amazon-eks-kubernetes-release-calendar
says EKS 1.20 release in April, 2021.

**Comment by crechandan** [comment]
Any update on EKS 1.20 release.

Thanks in advance for support !

**Comment by stijndehaes** [comment]
@crechandan If you look at the release calendar here: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

It now says may 2021, so I guess they couldn't get it ready on time

**Comment by streak324** [comment]
> Hello,
> Do you have an ETA for EKS 1.20 release?
> Thanks in advance!

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

**Comment by stevehipwell** [comment]
I think the question is that as it was documented as April and has now slid to May, are you confident that this will ship in May or will it slide again to June?

**Comment by vdahmane** [comment]
yes @stevehipwell it was the purpose of my question :)

**Comment by rubroboletus** [comment]
Hello,
now we all know, that releasing 1.20 in April was just April Fools! But is there information about real release date?
Thanks in advance!

**Comment by Skaronator** [comment]
1.20 AMI Images where just released. So EKS 1.20 update should be due next week: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210512

**Comment by kirtichandak** [comment]
Kubernetes version 1.20 is now available on EKS!

[Documentation
](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.20)
[What's New
](https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-eks-eks-distro-supports-kubernetes-version-1-20/)
[eksctl support](https://github.com/weaveworks/eksctl/releases/tag/0.51.0-rc.0)
[EKS Blog ]( https://aws.amazon.com/blogs/containers/amazon-eks-1-20-released/)

**Comment by tsndqst** [comment]
> Kubernetes version 1.20 is now available on EKS!
> 
> [Documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.20)
> [What's New](https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-eks-eks-distro-supports-kubernetes-version-1-20/)
> [eksctl support](https://github.com/weaveworks/eksctl/releases/tag/0.51.0-rc.0)le re
> [EKS Blog ](https://aws.amazon.com/blogs/containers/amazon-eks-1-20-released/)

Congratulations on the release of 1.20.  I'm looking forward to kicking the tires.

While reading the EKS blog post I noticed the link describing the new "default Service Accounts and Roles" is wrong. 
I think it should be https://docs.aws.amazon.com/eks/latest/userguide/default-roles-users.html instead of https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html

**Comment by eddiezane** [comment]
@tsndqst thanks a ton for catching that! Will get it fixed.
