### ISSUE TITLE
[EKS] [Fargate] [Bug] Fargate node larger than needed for pod

### ISSUE THREAD

**Issue by TBeijen** [aws/containers-roadmap#1248]
While experimenting with Fargate on EKS, I noticed the Fargate nodes created for the pods have more CPU and memory capacity than expected based on [the documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html). Even when taking into account the extra 250Mb memory for kubelet and other processes, the resulting node, as reported by `kubectl describe node`, could not be explained.

Kubernetes version: 1.16
Platform version: eks.5

Examples:

**Small pod**:

Would have expected 0.25vCPU/0.5Gb, maybe 0.5vCPU/1Gb. Actual node is **4x** or even **8x** as large.

```
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         2
  ephemeral-storage:           30832548Ki
  hugepages-2Mi:               0
  memory:                      4037540Ki
  pods:                        1

<truncated>

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests    Limits
  --------                    --------    ------
  cpu                         150m (7%)   150m (7%)
  memory                      150Mi (3%)  150Mi (3%)
  ephemeral-storage           0 (0%)      0 (0%)
  hugepages-2Mi               0 (0%)      0 (0%)
  attachable-volumes-aws-ebs  0           0
```

**large pod**:

Would have expected 2vCPU/4Gb. Actual node is **2x** as large

```
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         4
  ephemeral-storage:           30832548Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      7650216Ki
  pods:                        1

<truncated>

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         1500m (37%)   1500m (37%)
  memory                      1500Mi (20%)  1500Mi (20%)
  ephemeral-storage           0 (0%)        0 (0%)
  hugepages-1Gi               0 (0%)        0 (0%)
  hugepages-2Mi               0 (0%)        0 (0%)
  attachable-volumes-aws-ebs  0             0
```

From cost explorer I get the impression that it's indeed these figures that are billed, so not just kubelet reporting too large figures. (Although I would need to properly test that without changing a lot of things during the day to be sure).

Am I overlooking something? Or might there indeed be a problem in the right-sizing of Fargate nodes?

*Edit 2021-01-30:* Added kubernetes and platform version.

**Comment by mreferre** [comment]
@TBeijen sorry for the confusion. This [comment on another thread](https://github.com/aws/containers-roadmap/issues/942#issuecomment-747416514) may give you a little bit more context (along with another way to check the pod size - i.e. via the annotation we recently introduced). We should also update the doc page you linked to reflect this background + the new annotation (note to self).

**Comment by TBeijen** [comment]
@mreferre Thanks for the head up. I totally overlooked that when searching the issues, and also overlooked the annotation which indeed is there, e.g.:

```
  annotations:
    CapacityProvisioned: 0.25vCPU 0.5GB
```

This seems to relates to https://github.com/aws/containers-roadmap/issues/998 a bit. Currently quite some abstractions of the underlying Fargate platform leak into the way to use it in EKS. 

I suppose to some extent that's inevitable (Can't force a seconde pod on a fargate node by tolarating the taint and specifying the node, that would be interesting) but this one might be 'low hanging fruit' since the Fargate kubelet most likely is customized anyway.

**Comment by mreferre** [comment]
#998 indeed has some interesting feedback. There are a few reasons why we did not go down the virtual Kubelet route and that is because it's a heavy fork of the Kubelet and we did not want to go there. We are sticking to providing a fully upstream experience to users. The current model allows us to do that. In general our idea was/is to move away from the notion of "nodes" (as much as possible but as you could see Kubernetes has that notion too baked in to make it completely disappear). Things like taints, affinity etc are very node-specific mindsets whereas we wanted to abstract this experience in a way that would allow users to not think about nodes (e.g. via namespaces and pod annotations). Having that said, it's excellent food for thoughts, thanks for pointing me to it (my radars missed that thread).

**Comment by mreferre** [comment]
FYI we have updated [the documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html) to clarify this important point. Thanks for raising this issue @TBeijen .

**Comment by TBeijen** [comment]
@mreferre I see, great! And thx for explaining some of the considerations made while designing Fargate EKS. Interesting.
