### ISSUE TITLE
[EKS]: Kubernetes v1.15 End of Support (May 3rd, 2021)

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#1253]
Kubernetes version 1.15 on Amazon EKS will no longer be supported on **May 3, 2021**. On this day, you will no longer be able to create new 1.15 clusters. Existing 1.15 clusters will be automatically updated by Amazon EKS to the latest available platform version of Kubernetes version 1.16 through a gradual deployment process after the end of support date. 

We recommend you upgrade existing 1.15 clusters and worker nodes to at least 1.16 as soon as practical. Note that Kubernetes version 1.16 includes a number API changes that you must take into account before upgrading.

Learn more:
* [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
* [Kubernetes version 1.16 update prerequisites](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prerequisites)

**Comment by zcicala** [comment]
@mikestef9 Any idea when EKS 1.16 will be EoL'd? The calendar still only says `July 2021`

**Comment by chickenbeef** [comment]
@mikestef9 The calendar says EKS 1.16 will reach end of support on July 25, 2021

The [docs](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation) also say

```
Q: Am I notified when support is ending for a Kubernetes version on Amazon EKS?

A: Yes. If any clusters in your account are running the version nearing the end of support, Amazon EKS sends out a notice through the AWS Personal Health Dashboard approximately 12 months after the Kubernetes version was released on Amazon EKS. The notice includes the end of support date, which is at least 60 days from the date of the notice.
```

I don't see any notification in my PHD and there's no [GitHub issue for it](https://github.com/aws/containers-roadmap/issues?q=is%3Aissue++Kubernetes++End+of+Support+in%3Atitle++label%3AEKS+). Were notices sent out and will we still see GitHub issues being created?

**Comment by mikestef9** [comment]
Just created #1423. We sent out notices around a month ago, perhaps your cluster wasn't on 1.16 yet when we pulled that list?
