### ISSUE TITLE
[EKS] [request]: Desired size should be set to current amount for update nodegroup

### ISSUE THREAD

**Issue by dza89** [aws/containers-roadmap#1259]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When you update a nodegroup you have to pass the desired size. 
This field should be only be actively used when creating a nodegroup, and not during a nodegroup update.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Create nodegroup -> forward desired size
Update nodegroup -> ignore desired size, and set desired in the asg to the current amount of nodes, as this should be controlled by cluster autoscaler only.

**Are you currently working around this issue?**
Not

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by MyannaHarris** [comment]
Hi @dza89 ,
Are you still seeing this issue? Our CLI doesn't require all sizes to be entered and we made a change recently so updating the managed nodegroup through CFN shouldn't have this issue anymore. eksctl also recently put out a fix for this issue (https://github.com/weaveworks/eksctl/issues/3532). If you're still seeing this, please let us know how you're calling EKS so we can investigate some more.

**Comment by dza89** [comment]
@MyannaHarris 
I don't know what 'our' cli is, I guess the aws-cli?
I still see this issue, but maybe I don't understand what the solution should be?
I tried to update the nodegroup without the desiredAmount parameter, but it errored. How should I approach this?

Also, eksctl does not contain a fix, but a workaround; by getting the current amount of nodes from the asg and inserting that as desired amount, which is what I am doing as well, but should not be necessary tbh.

**Comment by dza89** [comment]
@MyannaHarris 
Maybe it wasn't rolled out in eu-west-1? 
DesiredAmount is no longer mandatory in the scaling config, it's working now :)
Thanks!

**Comment by dza89** [comment]
@MyannaHarris 

This is missing when updating the scaling config without the desiredSize.
```
if MaxAmount < desiredSize {
  desiredSize = MaxAmount
} else if MinAmount > desiredSize {
  desiredSize = MinAmount
}
```

**Comment by MyannaHarris** [comment]
@dza89 
Glad it's working for you now! 
eksctl is different but the CLI and CFN templates should allow the desiredSize parameter to be omitted.

We still require that the maxSize >= desiredSize >= minSize and currently don't have any plans to automatically and permanently alter a customer's desiredSize. If this is an important feature for you to have, please open a new feature request specifically for it so we can investigate.

Thank you for checking this and please let us know if you have any other questions.

**Comment by dza89** [comment]
OK, thanks for your input and help.

Last comment:
If I have a nodegroup with min 1 max 2 and I want to increase it to min 3 max 4, I still have to feed it the desired size, hence my previous comment.
