### ISSUE TITLE
[EKS] [request]: Remove cluster autoscaler tags from asg during nodegroup upgrade

### ISSUE THREAD

**Issue by dza89** [aws/containers-roadmap#1261]
**Community Note**
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Tell us about your request
When you update a nodegroup you have to pass the desired size.
This field should be only be actively used when creating a nodegroup, and not during a nodegroup update.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Right now Amazon advises to scale the cluster autoscaler down during a nodegroup upgrade. This becomes less and less acceptable the more nodegroups you have. (Downtime of hours for the cluster autoscaler during a rolling upgrade) 
Instead of downscaling the cluster autoscaler, I would propose to remove the cluster autoscaler tags from the autoscaling group during upgrade. And reinstate them afterwards.

**Are you currently working around this issue?**
Doing this manually

**Comment by mikestef9** [comment]
This was resolved as part of #916, is there another issue you are seeing?

**Comment by dza89** [comment]
Hmm I'm closing this for now. Missed those. 
Thanks @mikestef9

**Comment by dza89** [comment]
@mikestef9 
Can you confirm that step 7 here is obsolete?
https://docs.aws.amazon.com/eks/latest/userguide/update-managed-node-group.html

**Comment by mikestef9** [comment]
Yes thank you, that is no longer required, will get that removed from docs
