### ISSUE TITLE
[EKS] [request]: add support for eks.amazonaws.com/token-expiration annotation

### ISSUE THREAD

**Issue by rittneje** [aws/containers-roadmap#1274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Recently the pod identity webhook added support for configuring the duration of the JWT based upon a service account annotation. https://github.com/aws/amazon-eks-pod-identity-webhook/commit/599cfe7cfc8c72d48a8870e675e19a8169b3dafe

I am hoping this change can be applied to the webhook running in EKS.

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We want to be able to configure the JWT lifetime. Currently it is hard-coded to 24 hours. This is useful for two main reasons:
1. It gives us finer control over our security.
2. It makes it easier to test cases surrounding JWT refresh/expiration without having to literally wait 24 hours.

**Are you currently working around this issue?**

As far as I can tell, there is no simple workaround for this.

**Comment by mikestef9** [comment]
The webhook will be updated to include this feature along with launch of EKS support for v1.19, which is coming very soon.

**Comment by rittneje** [comment]
@mikestef9 Just to be clear, do you mean we will have to upgrade our cluster to 1.19 to use the new webhook, or do you mean the webhook for all clusters will be updated when 1.19 is released?

**Comment by mikestef9** [comment]
You will have to update to 1.19 in order to get the updated webhook this week. Separately, we are looking at updating the webhook on existing clusters, but no timeline to share there.
