### ISSUE TITLE
[EKS] [request]: Manage aws-auth ConfigMap in AWS Console

### ISSUE THREAD

**Issue by lnalex** [aws/containers-roadmap#1278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Add a feature to allow customers to manage and configure the `aws-auth` ConfigMap for an EKS cluster directly from the AWS Management Console.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Make it easier for customers to get started with EKS clusters from the AWS Console, particularly when using different roles for Console and CLI access. This would also make managing clusters from the AWS Console a more complete experience.

**Are you currently working around this issue?**
How are you currently solving this problem?

N/A

**Additional context**
Probably related to/requires implementation of the underlying API to manage aws-auth:
https://github.com/aws/containers-roadmap/issues/185#issuecomment-706636321

**Attachments**
N/A

**Comment by siqusoft** [comment]
This is one of  bottle neck for enterprises where single aws account managed by multiple teams with different responsibilities.   As a developer, you may not assume automation execution roles  for security reasons  and it makes difficult very difficult to  get access to the cluster you just created with out going through a lot of hustles or with out writing a lot of automation to accomplish this. it would be best handle by aws in native way.

**Comment by mikestef9** [comment]
This will be solved by #185

**Comment by siqusoft** [comment]
> This will be solved by #185

Thanks @mikestef9! do we have  any ETA?

**Comment by mikestef9** [comment]
Addressed with #185
