### ISSUE TITLE
[EKS] [request]: Add VPC resource controller and admission webhook cluster add-ons

### ISSUE THREAD

**Issue by jeffreycoe** [aws/containers-roadmap#1280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Create EKS cluster add-ons for the VPC resource controller and admission controller webhook. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, we have to run external scripts to generate a deployment when following the documentation at the link provided below. This can make it more difficult to manage and deploy using cloud orchestration tools. Managing this add-on using CloudFormation would make managing these resources much easier, too.

https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

**Are you currently working around this issue?**
We are manually executing the documentation or having to write our own scripts to wrap the scripts provided by AWS to integrate with our cloud orchestration workflows.

**Comment by mikestef9** [comment]
We are actually planning on moving this component directly to the control plane. The Windows functionality will be added to this project (which manages trunk/branch network interfaces for the security groups for pods feature)

https://github.com/aws/amazon-vpc-resource-controller-k8s

which is already running on the K8s control plane of every EKS cluster

**Comment by jeffreycoe** [comment]
@mikestef9 That's great news. I have to ask the million dollar question - any ETA on when this might be GA?

**Comment by mikestef9** [comment]
@jeffreycoe now :). Check out EKS Windows documentation below for how to transition Windows IP address management to VPC resource controller running on the control plane.

https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
