### ISSUE TITLE
[EKS/Fargate] [Question] Terminate Fargate Node after Pod completion

### ISSUE THREAD

**Issue by Hunter-Thompson** [aws/containers-roadmap#1284]
We run our Tekton Tasks on EKS, in a Fargate enabled namespace.

When the Tekton task completes, the pod does not terminate it just shows as completed. Similar to a Kubernetes job.

```
build-docker-image-hf2n5-build-image-fht88-pod-x2lj4   0/4     Completed   0          13h
```

When I list available nodes, I can see there is a Fargate node that exists even after the pod is completed. Does this mean I am getting charged some money? The pod has completed and is not using any resources so I would assume I am not getting charged.

After deleting the completed pod, the Fargate node is terminated.

Is there a way for the Fargate node to be terminated after the pod has completed its job without having to delete the pod? We run out of IPs in our VPC after 10 completed jobs and have to manually go and delete the completed pods in order to free the IPs.

A possible hacky way would be to run a Kubernetes job that deletes completed pods in the Fargate enabled namespace every 5 minutes.

**Comment by mreferre** [comment]
@Hunter-Thompson in EKS/Fargate the lifecyle of the node is tied to the pod. As long as the pod is not removed the node supporting it will be there. Given the pod is active you are charged for it. We are working to be more explicit in the EKS documentation about this nuance with Kubernetes jobs. We have seen customers successfully using tools in the ecosystem to clean up the pods after the jobs are completed. These are two that often comes up: 

https://github.com/lwolf/kube-cleanup-operator
https://github.com/aramse/k8s-job-reaper

Massimo.

**Comment by Hunter-Thompson** [comment]
> @Hunter-Thompson in EKS/Fargate the lifecyle of the node is tied to the pod. As long as the pod is not removed the node supporting it will be there. Given the pod is active you are charged for it. We are working to be more explicit in the EKS documentation about this nuance with Kubernetes jobs. We have seen customers successfully using tools in the ecosystem to clean up the pods after the jobs are completed. These are two that often comes up:
> 
> https://github.com/lwolf/kube-cleanup-operator
> https://github.com/aramse/k8s-job-reaper
> 
> Massimo.

Thanks for the links. They will help solve my issue.

**Comment by rpgreen** [comment]
Commenting for posterity: 
As of Kubernetes 1.23, this can be handled automatically using [TTL Controller](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/)
