### ISSUE TITLE
[ECS] [request]: Control which tasks are stopped when service desiredCount is updated

### ISSUE THREAD

**Issue by alexmac** [aws/containers-roadmap#1293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like a way to stop a specific task within a service and simultaneously decrement the desired task count. i.e equivalent to how task draining works for an ECS service associated with a load balancer. I can see a few possibilities:
- An extension to the stop-task api that also decrements the associated service count
- Something like "termination protection" on a task so the update-service api avoids certain tasks
- A priority value on a task indicating a preference in which tasks should be stopped before others.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a service that runs N tasks, all listening on an SQS queue for work to be done. there are times when we know that some of the workers are busy handling a message and some workers are idle. During such a scenario I would like to "scale-in" the number of tasks running, but I want to pick the specific tasks to be stopped - using the normal ECS service update api ECS would randomly select which tasks to stop, and that would cause active workers to be stopped, causing wasted work.

Essentially we have no way to effectively scale-in a service that isn't associated with a load balancer because there is no way to indicate which tasks are the best candidates to be drained.

**Are you currently working around this issue?**
We end up letting ECS kill active tasks, and waste time/money while the work is re-done on other workers (we don't lose any updates, we make effective use of SQS and retry etc, but it is a time/money issue)

**Comment by raags** [comment]
The ability to control which tasks get scaled in would also be useful for TaskSets. The use case is when doing deployments using the External deployment type, it's useful to be able to stop tasks in a Taskset, and prevent the Taskset from immediately replace the stopped task. So something like stop+change the computed desired count.

**Comment by vibhav-ag** [comment]
Hi, this use case should be addressed with the capability to protect a task from scale-in (launched in 2022). 
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-ecs-task-scale-in-protection/

Closing this issue for now- please reopen if this doesn't address the use case.
