### ISSUE TITLE
[ECR] [request]: Support for Alpine Edge on Vulnerability Scans

### ISSUE THREAD

**Issue by heykarthikwithu** [aws/containers-roadmap#1294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for Alpine Edge on vulnerability scans.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Using `alpine:edge` image causes `UnsupportedImageError: The operating system and/or package manager are not supported`. on ECR.

**Are you currently working around this issue?**
Ignoring the scanning error.

**Comment by heykarthikwithu** [comment]
Have a similar issue with Alpine 3.13 version as well. Here's the reference - https://github.com/aws/containers-roadmap/issues/1224

**Comment by bradgr** [comment]
Since edge is not an official release, there's no vulnerability data source for this release in [here](https://secdb.alpinelinux.org/). ECR's scanner will not be able to support this namespace.

**Comment by srrengar** [comment]
Closing this as alpine edge cannot be supported by ECR without vulnerability data. If alpine begins to release data that ECR can consume, we can build in support at that time.

**Comment by neijurli** [comment]
Looks like alpine is supporting vulnerability data for edge now - https://secdb.alpinelinux.org/edge/, will work on integrating this into scanning.

**Comment by kash66** [comment]
The same errors show up for `golang:1.15-alpine3.13` and `golang:1.15-alpine`.
