### ISSUE TITLE
Improved continuous delivery support for Fargate and ECS

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#13]
Improved continuous delivery support for the Amazon Container Services. Support for blue/green deployments via AWS CodeDeploy. Additionally, AWS CodePipeline now supports Amazon Elastic Container Registry (ECR) as a source provider. 

What's New post: https://aws.amazon.com/about-aws/whats-new/2018/11/the-aws-developer-tools-improve-continuous-delivery-support-for-aws-fargate-and-amazon-ecs/

**Comment by jespersoderlund** [comment]
I would like to raise the request for Canary deployment suport through CodeDeploy as well. The canary promotion needs to be possible to promote with an API-call, so that a human can be in the loop if needed. Deployment speed is also important to allow fast cycle times.

**Comment by deleugpn** [comment]
@abby-fuller are there any public CF templates that can help us set this up? The `image1containerName` and attributes alike are a bit confusing for me.

**Comment by clareliguori** [comment]
@jespersoderlund I opened a separate issue for canary deployments if you'd like to give feedback there: https://github.com/aws/containers-roadmap/issues/229

**Comment by srrengar** [comment]
ECS now supports canary style deployments too through CodeDeploy. 
https://aws.amazon.com/blogs/containers/aws-codedeploy-now-supports-linear-and-canary-deployments-for-amazon-ecs/
