### ISSUE TITLE
[ECR] [Request] : Cross Account Replication for Existing Images in Repository

### ISSUE THREAD

**Issue by pmehul** [aws/containers-roadmap#1305]
Tell us about your request
Cross Account Replication for Existing Images in Repository

Which service(s) is this request for?
ECR

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

we can replicate the image from one account to other account by configuring private image replication to the repository, but it will not replicate any existing images, which means you have to configure private image replication before you pushed the image to ECR. 

We would like to replicate existing images from one account to other account 

Cross region replication for existing images works fine in same account(https://github.com/aws/containers-roadmap/issues/140) but it does not work for cross account  

Can this be considered feature request?

Are you currently working around this issue?
NA

**Comment by pmehul** [comment]
it's already provided

**Comment by sathya-potharla** [comment]
No, it doesnt work atleast for me, i just tried creating a new ecr repo with new image pushed to it and this particular new ecr repo along with image gets pushed to destination account fine but on all existing repos & their images with in it doesnt get replicated to destination accounts.

**Comment by tekno45** [comment]
This definitely is not happening for me.
