### ISSUE TITLE
[ECS] [Debugging]: ECS Exec setting settable via create-service api --cli-input-json

### ISSUE THREAD

**Issue by brogersyh** [aws/containers-roadmap#1307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The ECS Exec feature is currently settable on a new service via cli only if using a cmd-line argument, --enable-execute-command. It is not settable via the --cli-input-json argument

What do you want us to build?

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We use deployment tools which create a new ecs service by passing a json 'service-spec' via the create-service cli -cli-input-json. We'd like to use the ECS exec feature by specifying its settings in the json 'service-spec', but cannot since --enable-execute-command isn't listed in --generate-cli-skeleton

**Are you currently working around this issue?**
One workaround would be to add custom scripting to our tooling after the deploy, via the update-service call, to specify this - but that reduces the simplicity benefit of our relying on out-of-the-box deploy features of our tooling.

**Additional context**
Is there any reason not to add new feature settings like ECS Exec and circuit breaker to the 'service spec' (specifiable via --cli-input-json) when a feature is first released? 

**Attachments**

**Comment by mansidabhole** [comment]
Hi, our latest service models and AWS CLI have exec feature settable in create service via the --cli-input-json argument. Upgrade the AWS CLI to [latest version](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html) to be able to use it . Please note that it is also listed in --generate-cli-skeleton as `enableExecuteCommand`

**Comment by brogersyh** [comment]
aws cli 2.1.32 supports this
