### ISSUE TITLE
[ECS-Fargate] [request]: Fargate 1.4.0 showing connection refused on DNS resolution

### ISSUE THREAD

**Issue by henriquesantanati** [aws/containers-roadmap#1308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Fargate 1.4.0 is showing the following error while using a image generated with a non-root user (UID 1000): `lookup DNSNAME on [::1]:53: read udp [::1]:34289->[::1]:53: read: connection refused`

**Which service(s) is this request for?**

ECS/Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Please find below the steps to reproduce the issue:

1 - Create getdns.go file with the following content: 

```
package main

import (
  "fmt"
  "net"
)

func main() {
  addr, err := net.LookupHost("amazon.com")
  if err != nil {
    fmt.Println(err)
    return
  }
  fmt.Println(addr)
}
```

2 - Compile the file with the following command: `CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o getdns getdns.go`
3 - Create a Dockerfile with the following:
```
FROM scratch
COPY ./getdns .
USER 1000
CMD ["/getdns"]
```
4 - Build it and push to ECR
5 - Create a Task definition using the same image
6 - Run it with Fargate 1.4.0

I've made some tests from my side and these are the outputs:

#### Fargate 1.3.0:
`[205.251.242.103 54.239.28.85 176.32.103.205]`

#### Fargate 1.3.0 binding mouting /etc RO:
`[205.251.242.103 176.32.103.205 54.239.28.85]`

#### Fargate 1.3.0 binding mouting /etc RW:
`[176.32.103.205 54.239.28.85 205.251.242.103]`

#### Fargate 1.3.0 NOT using user 1000 on Dockerfile: 
`[176.32.103.205 54.239.28.85 205.251.242.103]`

#### Fargate 1.4.0: 
`lookup amazon.com on [::1]:53: read udp [::1]:34289->[::1]:53: read: connection refused`

#### Fargate 1.4.0 binding mouting /etc RO:
`container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/var/lib/two/volumes/29f415582eff4235898b3c095bce885d/volumes/vf-3428535046/hosts" to rootfs at "/run/containerd/io.containerd.runtime.v2.task/fargate.task/29f415582eff4235898b3c095bce885d-1595959772/rootfs/etc/hosts" caused: open /run/containerd/io.containerd.runtime.v2.task/fargate.task/29f415582eff4235898b3c095bce885d-1595959772/rootfs/etc/hosts: read-only file system`

#### Fargate 1.4.0 binding mouting /etc RW:
`[205.251.242.103 54.239.28.85 176.32.103.205]`

#### Fargate 1.4.0 NOT using the user 1000 on Dockerfile: 
`[54.239.28.85 176.32.103.205 205.251.242.103]`

**Are you currently working around this issue?**
Either mount the /etc/ container path with write option or remove the USER line from the Dockerfile.

**Comment by emerzon** [comment]
Creating a minimal /etc/passwd file with an entry for the current UID user seems to also work as a workaround.

**Comment by henriquesantanati** [comment]
This issue was resolved 3 months ago! Thank you all!

**Comment by aweld** [comment]
Can you share how you solved the problem?

**Comment by henriquesantanati** [comment]
It was fixed by Fargate platform team. You shouldn't have this issue anymore while running tasks launched after around end of April.
