### ISSUE TITLE
[EKS] [Fargate]: Deployment other then "CapacityProvisioned: 0.25vCPU 0.5GB" is not printed out correctly

### ISSUE THREAD

**Issue by vorti2** [aws/containers-roadmap#1309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I want to have a pod with a higher capacity as the default value `0.25vCPU 0.5GB`, because with the default values my pod is always restarted.

**Which service(s) is this request for?**
EKS Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
If I set the following annotation in the pod deployment
```
...
      annotations:
        CapacityProvisioned: 0.5vCPU 1.0GB
...
```
the output with `kubectl describe pod  <pod name>`gives the default values:
```
...
Annotations:          CapacityProvisioned: 0.25vCPU 0.5GB
...
```

**Are you currently working around this issue?**
Not now ... Pod is restarting ...

**Comment by mreferre** [comment]
@vorti2 that's now how you size your pod. The `CapacityProvisioned` annotation is just an output. [This is how you set the pod size](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html). It's basically using `requests`.

**Comment by vorti2** [comment]
Hi @mreferre, thanks for the fast reply.

 I have read the page, but it don't help me resize the pod. Where (the hell 😉 ) can I set the pod size and consumed CPU units?

**Comment by mreferre** [comment]
> When pods are scheduled on Fargate, the vCPU and memory reservations within the pod specification determine how much CPU and memory to provision for the pod. 

[This Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) has more info re how you set up `requests` in your pod YAML (you only need to specify `requests`, not `limits`).

**Comment by mreferre** [comment]
From the [doc](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html) I linked above: 
> Fargate adds 256 MB to each pod's memory reservation for the required Kubernetes components (kubelet, kube-proxy, and containerd).

So in your case it's 900m+256m=1.156m. 

> Fargate rounds up to the compute configuration shown below that most closely matches the sum of vCPU and memory requests in order to ensure pods always have the resources that they need to run. 

That's what makes it 2GB (because of the 1GB increments). 

If you want to provision 1GB of memory you can specify a memory `request` between 300 and 700 (e.g. 512 if you want to keep it "elegant") and it will land at 1GB.

**Comment by vorti2** [comment]
Thanks @mreferre for the information!

I set `"512Mi"` and the output of `describe` is 👻 
```
...
CapacityProvisioned: 0.25vCPU 1GB
...
```
