### ISSUE TITLE
[ECR] [PrivateLink]: support for VPC endpoint policy

### ISSUE THREAD

**Issue by jtoberon** [aws/containers-roadmap#132]
When you create a VPC endpoint, you can attach an endpoint policy to it that controls access to the service to which you are connecting. For more details, see [the VPC documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html).

**Comment by mailjunze** [comment]
Even after updating ECS-agent to 1.25.1, I am getting Error time="2019-01-26T11:13:50.045279325Z" level=error msg="Handler for POST /v1.38/images/create returned error: Get https://******************.dkr.ecr.eu-west-1.amazonaws.com/v2/nginxlinux/manifests/latest: no basic auth credentials"

**Comment by jtoberon** [comment]
https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html
