### ISSUE TITLE
[lambda] [request]: Cross-account same region Container Lambda image reference

### ISSUE THREAD

**Issue by dclayton-godaddy** [aws/containers-roadmap#1327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We'd love if Container Lambdas in account A (region A) can pull images from ECR in account B (region A).

**Which service(s) is this request for?**
Lambda, ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have several AWS accounts and publish our shared Docker images to one of those accounts. We have started to build Container Lambdas and noticed it does not currently support pulling images from another account in the same region. We would like to push our shared images in a single ECR per region so all accounts can share the images.

**Are you currently working around this issue?**
Not yet.

**Additional context**
No.

**Attachments**
NA

**Comment by toricls** [comment]
Hi @dclayton-godaddy! Have you already checked on this? It supports cross-account replication.
https://docs.aws.amazon.com/AmazonECR/latest/userguide/replication.html

**Comment by dclayton-godaddy** [comment]
@toricls Thank you for the response. We will certainly look into this if this request is not feasible. Thanks!

**Comment by toricls** [comment]
Hi @dclayton-godaddy! Have you looked into the feature above? I'd like to hear your thoughts on this 🙌

**Comment by metroidprototype** [comment]
@toricls Not the OP, but this is definitely a feature I would think is useful to a lot of organizations. For some perspective on my personal use case, we have a centralized ECR where multiple accounts representing our various environments all pull from which contains close to 500 repositories (and growing) all being actively used. Of those 500, I have approx. 6 which I would want to be able to access from each environment account for lambda to run. On the replication end, its an all or nothing operation, so I would be constantly copying all these repositories to all these remote accounts, paying to store, and never use them. The latency of cross account pulls is not a factor for our use cases, and this is an already established design paradigm within AWS.

**Comment by danielloader** [comment]
To echo above, replication is heavy handed for what could be short lived transient AWS accounts - we're trialling a system where each client gets their own AWS account and they're extremely light - few s3 buckets, lambda and sqs - so setting up replication for an aws account which might be active for a day or two is a fair bit of overhead, in this case a pull system rather than push would be extremely beneficial to us. Just having organisation unit access to automatically grand pull image access just by virtue of being in the correct OU would be a game changer for our stack.

**Comment by pjungermann** [comment]
https://github.com/aws/containers-roadmap/issues/1281 requests cross-account cross-region which may imply cross-account same region then. Of course, having to pull images across regions can be sub-optimal and you might then want to use cross-region replication of images to improve on that (which ends up at this request).

**Comment by toricls** [comment]
Here you go! 🚀🚀🚀
https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-support-cross-account-image-amazon-elastic-container-registry/

**Comment by danielloader** [comment]
Sorry to reply here @toricls but I can't for the life of me work out how to reference an ECR image in another account from a CDK stack, is there any prior art to refer to here?

**Comment by yongzhang** [comment]
Please support this in AWS China, please, please, please, the end of 2022 now ...
