### ISSUE TITLE
[EKS]: Control default storage class

### ISSUE THREAD

**Issue by ckdarby** [aws/containers-roadmap#1330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Be able to provide a default storage class when EKS being created.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We're trying to have reproducible EKS clusters that come up with encrypted volumes or to have the ability to influence the default storage class during EKS creation.

**Are you currently working around this issue?**
Upon the EKS cluster being spun up we're applying a kubectl yaml to make gp2 not the default and then during our helm install we're creating a storage class called like, 'gp2-encrypted' with encrypted flag turned on.

**Comment by mikestef9** [comment]
Starting EKS v1.30 we will remove the default annotation from the storage class created with EKS.

**Comment by toVersus** [comment]
Is it only affecting newly created EKS clusters, or does it also impact existing clusters?

**Comment by mikestef9** [comment]
Newly created EKS v1.30+ clusters no longer add the default annotation to the storage class applied to the cluster.
