### ISSUE TITLE
ECS [request]: Capture more of the error message from failed launches

### ISSUE THREAD

**Issue by dacut** [aws/containers-roadmap#1332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When a task fails to launch, the error message is truncated at 252 characters (255 - 3 for ellipses). This omits the interesting bits of the error.

Please up this to 1024 characters.

**Which service(s) is this request for?**
ECS / ECS Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Right now, when I don't have some permission *just* right, it ends up being a case of trial and error. Or wait 15 minutes for the event to (maybe) appear in CloudTrail, if it appears at all. The error messages here just don't have quite enough:

```
ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve ecr registry auth: service call has been retried 1 time(s): AccessDeniedException: User: arn:aws:sts::123456789012:assumed-rol...
```

Argh! What API? What service call? What role? The only useful bits here are the account number (which I know) and `AccessDeniedException`, and a bit of a hint that ECR is involved.

**Are you currently working around this issue?**
Trial and error. *Lots and lots* of trial and error. Typically takes me hours to solve, especially since I can't create roles normally due to enterprise security rules -- change requests have to go through another pipeline.

**Additional context**

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by iniinikoski** [comment]
There's another issue about this here, I believe: https://github.com/aws/containers-roadmap/issues/1133

**Comment by mreferre** [comment]
Yes #1133 is the issue we are using to track this. I am closing this one.
