### ISSUE TITLE
[EKS] [request]: allow to change configuration on vpc-cni addon

### ISSUE THREAD

**Issue by fasher** [aws/containers-roadmap#1333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Adding vpc-cni as a managed add-on is very nice. however right now you cannot change any configuration through it. 
for example: to set AWS_VPC_K8S_CNI_EXTERNALSNAT I have to modify aws-node daemonset. 
it would be nice if this can be controlled through the add-on 

**Which service(s) is this request for?**
EKS

**Are you currently working around this issue?**
Yes

**Comment by mveitas** [comment]
What sort of configuration are we going to be able to set? For example, we are starting to require that all workloads running in a cluster specify resource values for cpu and memory. Is this something that will be included?

**Comment by kishoregv** [comment]
It would be nice if we can set labels and annotations

**Comment by jbilliau-rcd** [comment]
Agreed; I don't want to manage the CNI lifecycle myself, but that's my only option if i want to control WARM_IP_TARGET and MINIMUM_IP_TARGET, which the defaults take up a LOT of IP's from the VPC.

**Comment by liammurray** [comment]
Also would be useful for enabling SG for pods (which I do currently via separate k8s patch step)

**Comment by jwenz723** [comment]
I would love to see the ability to enable/configure Custom Networking using the vpc-cni addon. 

Not sure if that would be handled by this issue or by https://github.com/aws/containers-roadmap/issues/867

**Comment by sriramranganathan** [comment]
Amazon EKS team recently announced the general availability of advanced configuration feature for managed add-ons. You can now pass in advanced configuration for cluster add-ons, enabling you to customize add-on properties not handled by default settings. Configuration can be applied to add-ons either during cluster creation or at any time after the cluster is created.

Custom configuration will also allow you to set AWS_VPC_K8S_CNI_EXTERNALSNAT environment variable for the Amazon VPC CNI add-on.

To learn more about this feature, check out this blogpost - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

Check out the Amazon EKS documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html

**Comment by miranda-delfiacco** [comment]
Thank you for adding this feature, is there any chance `WARM_IP_TARGET` will be a configurable option in the future or should I open a new request for that?

**Comment by mikestef9** [comment]
Yes, that's coming with v1.12.0-eksbuild.2

**Comment by jdn5126** [comment]
Just wanted to update here that in `v1.13.0-eksbuild.1`, you will also be able to configure `tolerations`, `affinity`, liveness and readiness probe timeouts, and ENIConfigs

**Comment by avnerv** [comment]
what about annotations and labels?

**Comment by jdn5126** [comment]
Configuring additional pod labels and pod annotations via EKS managed addons will ship with VPC CNI v1.15.5, for which the release is currently in progress
