### ISSUE TITLE
[EKS] [request]: Support Kubernetes 1.21

### ISSUE THREAD

**Issue by billinghamj** [aws/containers-roadmap#1334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Add support for Kubernetes 1.21

**Which service(s) is this request for?**
EKS

**Comment by Skaronator** [comment]
Just a head up in case anyone subscribed to this issue. EKS Support seems to be official since yesterday. You can find the changelog here: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by georgejohnis** [comment]
EKS support for Kubernetes version 1.21 is now available!

- [What's new post](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-eks-eks-distro-support-kubernetes/)
- [EKS Blog](https://aws.amazon.com/blogs/containers/amazon-eks-1-21-released/)
- [eksctl support](https://github.com/weaveworks/eksctl/releases/tag/0.58.0-rc.0)
- [EKS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.21)
