### ISSUE TITLE
[ECS] [Container AMI]: Allow smaller EBS root volumes with container optimized AMI

### ISSUE THREAD

**Issue by talawahtech** [aws/containers-roadmap#134]
**Tell us about your request**
For ECS the root volume size defaults to 30GB. That is a good default, but I would like the option to use smaller volume sizes as well. Overriding the BlockDeviceMappings of the launch template allows us to increase the size of the root device, but we cannot *decrease* it beyond the size of the *snapshot* associated with the AMI.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
If I want to use the ECS AMI to launch a large number of small instances with minimal containers, I am forced to use 30GB root volumes. In the most extreme  example if I were launching a bunch of t3.nano instances, the EBS cost would be almost as much as the instance cost

**Are you currently working around this issue?**
The only current workaround is to build my own AMI.

**Additional context**
It is possible to maintain the 30GB *default* for the AMI while still allowing instances to be launched with a smaller root volume size as long as **the snapshot** associated with the AMI is smaller. The size of the snapshot is determined by the size of the block device on the instance used to *build* the AMI.

I can use the EKS AMI as a practical example since the source is available. The [previous Packer configuration](https://github.com/awslabs/amazon-eks-ami/blob/d1c3e0c35c4038261be4344c0d4c94216fd1016c/eks-worker-al2.json) used the `launch_block_device_mappings` property to set the volume size to 20GB and in doing so forced the snapshot to be 20GB as well.

If instead the volume size specified under [launch_block_device_mappings](https://www.packer.io/docs/builders/amazon-ebs.html#launch_block_device_mappings) was 4GB **and** the [ami_block_device_mappings](https://www.packer.io/docs/builders/amazon-ebs.html#ami_block_device_mappings) property was added with a volume size of 30GB then we would have the best of both worlds. A 30GB default that can be resized as low as 4GB or as high as EBS supports. 

The Amazon Linux 2 minimal AMI has a snapshot size of 2GB. After the ECS AMI is built disk usage is about 1.1GB, so 4GB seems like a reasonable *minimum* value to me.

I opened separate [issue in the amazon-eks-ami repo](https://github.com/awslabs/amazon-eks-ami/issues/162) and created a [pull request for the fix.](https://github.com/awslabs/amazon-eks-ami/pull/163). It would be great if there was an amazon-ecs-ami repo as well, then I could submit a pull request for ECS too 😉

**Update**: The EKS [PR was merged ](https://github.com/awslabs/amazon-eks-ami/pull/163)and is now incorporated into the [v20190211 EKS AMI](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;search=ami-0c5b63ec54dd3fc38;sort=name). Now even though the default volume size for EKS is 20GB, [the snapshot size is now 4GB](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Snapshots:visibility=public;search=snap-0327aa87e6cf3c096;sort=snapshotId).

Edit: Updated with additional details and links to the EKS PR
Edit: Updated with the fact that the EKS PR was merged and a new AMI with the reduced snapshot size was released.

**Comment by FernandoMiguel** [comment]
The background issue is that AMI can't use a smaller EBS, as you described.
Setting the default EBS smaller would most certainly cause issues to all clients that don't set a bigger EBS. 

slow take in consideration that really small EBS volumes will run out of IO credits and performance is really poor

**Comment by talawahtech** [comment]
@FernandoMiguel I am not suggesting that we change the default. The change that I am proposing would *optionally* allow user to launch instances with smaller root volumes **without** changing the default.

Regarding IOPS, even if the user deliberately reduces the volume size, all gp2 volumes have a baseline of 100 IOPS, so every volume smaller than 33.33GB has the same amount of [baseline IOPS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html#EBSVolumeTypes_gp2). Additionally, there are many workloads that are not disk bound at all.

**Comment by amlodzianowski** [comment]
+1, this is a feature we would also like to see

**Comment by trav-c** [comment]
+1, We generate an encrypted AMI from the base provided AMI and set up Metadata firewalling etc in our Cloudformation stack, and it would be preferable to keep this as small as possible to speed up CreateImage/CopyImage during that process.

**Comment by leovin** [comment]
how much thumbs up and waiting are needed ... to copy 5 lines from talawahtech's EKS PR?

**Comment by nalinguptalinux** [comment]
+1

**Comment by miltzi** [comment]
+1

**Comment by GiladE** [comment]
+1

**Comment by Akitsu** [comment]
+ 1

**Comment by stream-toma** [comment]
+1

**Comment by BrandonTeixeiraStream** [comment]
+1

**Comment by leorseligman** [comment]
+1

**Comment by beornf** [comment]
@talawahtech @FernandoMiguel Setting smaller volume sizes doesn't reduce the baseline of 3000 IOPS anymore using gp3 volumes. In addition gp3 volumes are [20% cheaper per GB](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/) than gp2 volumes.

**Comment by chirayu-miles** [comment]
We launch many single purpose EC2 machines that don't really use much disk.  The EBS costs add up and it's pretty important for us to cut down the disk size from 30G to 20G.

**Comment by vibhav-ag** [comment]
This is generally available now: 
https://aws.amazon.com/blogs/containers/creating-custom-amazon-machine-images-with-the-ecs-optimized-ami-build-recipes/
