### ISSUE TITLE
[EKS] [request]: Support VPC CNI 1.7.9

### ISSUE THREAD

**Issue by msaitz** [aws/containers-roadmap#1341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Use the VPC CNI plugin v1.7.9 as the default version for EKS

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Amongst other bug fixes and improvements, we have found that this version bumps the plugins version to v0.9.0, which includes the bug fix https://github.com/containernetworking/plugins/pull/553

This fixes an issue we've been experiencing with Datadog node agents with an UDP listener for custom metrics. If the agent pod gets replaced for any reason, the node's conntrack keeps this pod stale connection and the UDP traffic send to it would not make it to the new pod destination.

**Are you currently working around this issue?**
We're considering upgrading our clusters to this version after thoroughly test it.

**Comment by mikestef9** [comment]
We have updated our docs to recommend the latest v1.7 patch version

https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

You can use the following manifest to upgrade to to the latest patch version

https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml

Note that the default vpc cni version installed in new clusters today may lag the recommended version, and we have plans to address that later this year.
