### ISSUE TITLE
[EKS] [request]: Support Security Groups for EKS Public Access CIDRs

### ISSUE THREAD

**Issue by kevin-hicks-sp** [aws/containers-roadmap#1349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
In its current implementation, public network access to the EKS cluster endpoint is governed by a list of CIDR ranges configured as part of the cluster itself. This requires us to update each EKS cluster's access list individually to maintain a consistent rule set across clusters. Additionally, EKS access lists are limited to 40 CIDRs, which is less than my organization requires.

An improved model would be for EKS public endpoints to support Security Groups for access control.

Benefits:

* Consistent rule sets across EKS clusters by attaching the same SG to multiple clusters.
* The ability to leverage EC2 Managed Prefix Lists for especially messy CIDR lists.
* Up to 1,000 rules,

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Security Groups are commonly used to control perimeter access to several AWS components, but EKS public endpoints seem to be an odd exception. Our organization is used to implementing Security Groups nearly everywhere, and we've even solved some interesting challenges with them. EKS not supporting Security Groups for its public endpoints is a big miss, and it's forced my organization to go back to the drawing board in an attempt to solve this issue of having a large list of CIDR ranges to allow into the EKS clusters.

**Are you currently working around this issue?**
We have to instruct our engineers to only use a limited number of VPN endpoints from which their traffic can originate. And from each of those endpoints, it's a gamble of which outbound public IP will be assigned to the engineers. Without support for Security Groups, we have to implement and maintain an automation to continuously query our network service provider and keep our EKS rules consistent with their network configuration. Given how often they change, how many EKS clusters we have, and how many additional rules not pertaining to the engineer networks we have, this is far from ideal.

Thanks for reading!

**Comment by mikestef9** [comment]
Closing as duplicate of #1063
