### ISSUE TITLE
[EKS] [question]: Lambda interaction with services inside EKS cluster

### ISSUE THREAD

**Issue by anvouk** [aws/containers-roadmap#1353]
Hello, I need to pass an http address to some lambdas so that they can call a service that's running inside my cluster EKS.

The k8s service may use a NodePort if necessary, but I'm still puzzled as to what ip/dns assign to the cluster nodes....

Both cluster and lambdas share the same VPC (possibly even subnets), but I didn't find a way to set a private DNS/static ip that could load-balace through the various dynamic EC2 instances managed by EKS.

The only way I found to achieve this was by setting every k8s service needed to LoadBalancer, but since NLBs start at ~20$ per-month, traffic excluded, this is a complete no-go.

k8s Ingresses are limited to ports 80 and 443, so this isn't an option either.

Found no way to assign elastic IPs, or to create dynamic TargetGroups.

How are lambdas supposed to communicate internally to k8s services without exiting the VPC? Am I missing something?? Couldn't find anything useful on stackoverflow or anywhere. Well, except a ridiculoulsy complicated procedure of setting-up an internal hosted zone with route 53... and I still wouldn't know if it'd work as expected...

Any help on the matter?

Thanks.

**Comment by ckdarby** [comment]
@anvouk You'd want to set up an ingress controller if you want to avoid duplicate load balancers costs. To bridge from the Lambda to EKS VPC use VPC endpoint services.

You'll be able to set up an EKS VPC endpoint and on the lambda side, you'll be able to have a VPC endpoint service to allow the private DNS of EKS exposed to your lambda.

**Comment by anvouk** [comment]
Thanks!
