### ISSUE TITLE
[ECS][CodeDeploy] [Blue/Green]: blue/green deployments under the same target group

### ISSUE THREAD

**Issue by webertrlz** [aws/containers-roadmap#137]
**Tell us about your request**
An improved builtin Blue/Green deployment for ECS  that uses the same Target Group for TaskSets instead of using 1 different Target Group for each TaskSet (as we currently have in CodeDeploy Blue/Green deployments). This should register new tasks on the same Target Group and drain connections from the old tasks. A rollback should be possible by registering back the previous tasks in such Target Group and deregistering the newer ones, optionally draining connections.

**Which service(s) is this request for?**
ECS, CodeDeploy, EC2

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to gracefully switch versions of an application without making complex changes in infrastructure and without relying in external tools for traffic shifting. I want to drain existing connections from the old version and have new connections open on the new version. I want to do all this and still keep the old version running to be able to do an "instant" rollback if I need to.

**Are you currently working around this issue?**
Sort of. I have to either use the rollout upgrades to gracefully switch versions regarding user connection draining but no quick rollback, or I use Blue Green deployments, being able to Rollback instantly but without draining connections.

**Additional context**
I tried to accomplish this by doing the following:
 * create 2 services, blue and green
 * create one target group and one load balancer for both services
 * deploy to one of them (let's say Green) and deregister the other's tasks (Blue) from the target group so it drains connections and keep running
 * if rollback needed, just deregster the new tasks from Blue and register Green's back

With this I would have rolling upgrades, draining connections and quick rollbacks all at the same time. But when I deregister targets, the service registers them back, so it doesn't work as I expected.

Draining connections is good for house cleaning and not abruptly swapping versions in production.

**Comment by steven-cuthill-otm** [comment]
yes please !

**Comment by clareliguori** [comment]
Can you tell me more about why you want to use a single target group vs two?

Flipping at the listener rule level allows for fast traffic flips and fast rollbacks in seconds, even for services with up to 1000s of containers.  Registering and deregistering all of those containers can take a while when using a single target group.  Connections still drain gracefully because updating the listener rule only impacts new incoming connections.

I'm also curious about how you see CodeDeploy as an external tool.  We see it as part of the same platform, like application load balancers.  How can we make it feel like it's more built-in to ECS?

**Comment by webertrlz** [comment]
Hello @clareliguori,

the point of using a single target group would be not to have an abrupt flip at the listener level, which on my tests seemed to kill existing connections, that's all.

I agree with you on cases where the number of containers is massive. That's not my case, so I didn't think about it before.

I don't see CodeDeploy as an external tool, I used the word _built-in_ just to enforce it, because we (and probably many people) use external scripts and CI Pipelines to make a custom Blue/Green-like deployments.

I will re-test the existing connections persistence when flipping versions and will comment back here asap.

**Comment by webertrlz** [comment]
Hey @clareliguori, how are you?

I have redone tests and what happens is that when the switch happens to the new version deployed, I get a few `502`s, that's why I was thinking that the switch didn't cover existing connections. On my previous tests I wasn't accounting what requests were failing, old or new ones.

Now I see the case is different, it's for new connections that errors happen a few times. I got about 1 second downtime with 1 single container, with an external client issuing sequential requests every 200 milliseconds.

This could be a bug or something else on my set up, but anyways the problem that I see is not related to this ticket, I think you can point me to where I can open a ticket for this `502`s case and close this one.

**Comment by clareliguori** [comment]
@webertrlz This [documentation page](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues) has some possible reasons for ALB returning 502s.  You can check the [ALB access log](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html) for the full request.  If that doesn't track down the problem, then open a ticket with AWS Support or post on the AWS Forums.

**Comment by clareliguori** [comment]
Before we close this issue, I'd love to hear if anyone else that +1'ed this issue still needs single-target-group blue-green after the conversation above?
