### ISSUE TITLE
[EKS] Increased pod density on smaller instance types

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
All instance types using the VPC CNI plugin should support at least the Kubernetes recommended pods per node limits.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today, the [max number of pods](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) that can run on worker nodes using the VPC CNI plugin is limited by the number of ENIs and secondary IPv4 addresses the instance supports. This number is lower if you are using CNI custom networking, which removes the primary ENI for use by pods. VPC CNI should support at least the [Kubernetes recommended pods per node thresholds](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md), regardless of networking mode. Not supporting these maximums means nodes may run out of IP addresses before CPU/memory is fully utilized.

**Are you currently working around this issue?**
Using larger instance types, or adding more nodes to a cluster that aren't fully utilized.

**Additional context**
Take the m5.2xlarge for example, which has 8 vCPUs. Based on Kubernetes recommended limits of pods per node of min(110, 10*#cores), this instance type should support 80 pods. However when using custom networking today, it only supports 44 pods.

**Comment by spronin-aurea** [comment]
@tabern could you please elaborate a bit what this feature brings? 

Right now the number of pods on a single node is limited by `--max-pod` flag in kubelet, which for EKS is calculated based on the max number of IP addresses instance can have. This comes from AWS CNI driver logic to provide an IP-address per pod from VPC subnet. So for r4.16xl it is 737 pods.

**Comment by spronin-aurea** [comment]
@max-rocket-internet gotcha. Does it mean instances will get more IPs/ENAs or changes are coming to CNI?

**Comment by max-rocket-internet** [comment]
It means we need to run a different CNI that is not limited by the number of IPs. Currently is more or less a DIY endeavour but it would be great to have a supported CNI from AWS for this use 🙂

**Comment by laverya** [comment]
Yeah, running weave-net (and overriding the pods-per-node limitations) isn't much of an additional maintenance burden but it would have been nice to have that available by default.

**Comment by lgg42** [comment]
Any idea how exactly are you going to proceed with this one?
Seems very much alike to #71

**Comment by tabern** [comment]
Sorry it's been a bit of time with out a lot of information. We're committed to enabling this feature and will be wrapping this into the [next generation VPC CNI plugin](https://github.com/aws/containers-roadmap/issues/398).

Please let us know what you think on https://github.com/aws/containers-roadmap/issues/398

**Comment by gitnik** [comment]
The comment by @mikestef9 on #398 refers to this issue for updates regarding the specific issue of pod-density. Since there has been no update on this issue in over a year, could someone from the EKS team give us an update?

**Comment by mikestef9** [comment]
We are working on integrating with an upcoming VPC feature that will allow many more IP addresses to be attached per instance type. For example, a t3.medium will go from allowing 15 IPs per instance, to 240, a 1500% increase. No timeline to share, but it is a high priority for the team.

**Comment by bambooiris** [comment]
@mikestef9 hi! Will be pod density increased for bigger instances types as well? 
This is very important because we are thinking to switch to a different CNI plugin, but if you will increase the IP addresses count any time soon we will stay with AWS CNI :)

**Comment by mikestef9** [comment]
It will be a 1500% increase in IP addresses on every instance type. However, I don't feel that matters on larger instance types. For example, a c5.4xl today supports 234 IP addresses for pods. Which particular instance type are you using?

**Comment by bambooiris** [comment]
We are using m5.xlarge and still have enough resources to schedule additional pods but we out of free IPs.

**Comment by mikestef9** [comment]
Got it. I'm consider "smaller" to mean any instance type 2xl and below. In this case, m5.xlarge will go from supporting 56 IPs to 896, which will be more than enough to consume all instance resources by pods.

**Comment by billinghamj** [comment]
Pods can be very very small 😉 But nevertheless, this is a great step

**Comment by billinghamj** [comment]
To just get clarity, this is 16x the IPs while still using IPv4? Whereas longer term, for huge numbers of IPs etc, it's expected that EKS will shift to IPv6 instead?

**Comment by mikestef9** [comment]
Exactly. The same upcoming EC2/VPC feature that will allow us to increase IPv4s per instance, will also allow us to allocate a /80 IPv6 address block per instance. That's what we will leverage for IPv6 support, which is a top priority for us in 2021.

**Comment by davidroth** [comment]
> We are working on integrating with an upcoming VPC feature that will allow many more IP addresses to be attached per instance type. For example, a t3.medium will go from allowing 15 IPs per instance, to 240, a 1500% increase. No timeline to share, but it is a high priority for the team.

@mikestef9 Sounds awesome. I'm currently evaluating EKS and the current pod limitation is a blocker for our workload. Could you please share an approximate release date? Thanks.

**Comment by Z3R6** [comment]
> Exactly. The same upcoming EC2/VPC feature that will allow us to increase IPv4s per instance, will also allow us to allocate a /80 IPv6 address block per instance. That's what we will leverage for IPv6 support, which is a top priority for us in 2021.

I'm currently evaluating EKS and the current pod limitation is a blocker for our workload. Could you please share an approximate release date? Thanks.

**Comment by forsberg** [comment]
Unfortunately, there are few things in life more certain than the fact that AWS will never ever ever ever ever ever share an approximate release date for a future feature. I'm pretty sure pigs will fly and the Universe will cease to exist before we see it happen.

**Comment by billinghamj** [comment]
It would be very helpful to at least get an idea of magnitude - are we talking weeks/months/quarters/years?

**Comment by jwenz723** [comment]
@mikestef9 Can you please clarify for us if this feature will require using IPv6 in order to get the 1500% increase in IPs per node? I'm really hoping that I can continue to use IPv4 and get this pod density increase.

**Comment by mikestef9** [comment]
The 1500% increase is for IPv4. With IPv6, you'll get a /80 per node, so pod density is no longer an issue for any use case.

**Comment by dearsaturn** [comment]
I come to this page every few months as a religious procedure

**Comment by rohith-gittest** [comment]
Issue Summary:
EKS worker nodes has limitations for running number of pod based on the instance type. In our case we use instance type-c5.2xlarge which allows 58 pods per instance. If the pods are scheduled more than that number on the same instance, then those pods are getting stuck in ContainerCreating status.
Describing the pods gives us following errors: " Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "8be3026cc6bb2b311570f118dfef8ab93ae491e6d6fc20e12a46e9b814cff716" network for pod "pod-name": networkPlugin cni failed to set up pod "pod-name" network: add cmd: failed to assign an IP address to container "

As part of solution we tried adding --use-max-pods false --kubelet-extra-args '--max-pods=110' into our EKS worker node bootstrap script. Still the issue remains same.
Please guide us the solutions if there are any to remove pods restriction based on instance type and run max number of pods in a worker node.

Note:
Based on the AWS premium support they suggest us to consider greater instance types to achieve our use-case(which is to run max number of pods in a worker node).
This solution provided by AWS is absolutely weird in many ways as listed below:

If we run maximum number of pods in a EKS worker node, Still we can see worker nodes are being underutilized in terms of CPU and memory. In this case using higher instance type will cost us more.
Even if i run max number of pods in a worker node consuming the total % of CPU will not cross double digits. In this use case again having greater instance type is not the cost optimization strategy.

If the pods are stuck in ContainerCreating state, the same pod can't move to running state unless it's being killed and restarted.
So our requirement is kube-scheduler should know if the node have the sufficient IPs, Then only it should schedule the pod on that particular node. Indeed kube-scheduler should know if IPs are exhausted in the worker node before placing the pods.

If we use aws vpc custom cni then worker nodes cant make use of all the NIC available for that instance type.
For Ex: We use c5.2xlarge which supports max 4 NIC. Since we use a different subnets each for nodes and pods. 1 NIC will be assigned to our node which will have only 1 IP and rest of the 14 IPS will be wasted.
other 3 NIC*15=45 pods only we can run instead of 58 pods. Please give us a justification on this.

If pods stuck in Container creating status any auto scaling option available to bring new nodes as like cluster autoscaler will monito CPU and memory.

**Comment by Z3R6** [comment]
F

**Comment by stevehipwell** [comment]
@rohith-mr-rao with the aws-vpc-cni each container needs an IP address on a node ENI. If you're **NOT** using a secondary subnet for your pods the number of pods per instance type can be found in the [EKS AMI repo](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) and this is automatically set for `kubelet`. If you **ARE** using a secondary subnet for your pods you will need to calculate the limit yourself (the formula `maxPods = (number of interfaces - 1) * (max IPv4 addresses per interface - 1) + 2` is in the EKS docs) to pass to `kubelet --max-pods` and you should set the `--use-max-pods false` bootstrap argument so the default value isn't persisted in the config (although in practice this has no impact).

**Comment by thanhma** [comment]
Current workaround is to use third-party CNI plugins, I used **Calico** and can easily change the `max-pod-per-nodes` to whatever I want and utilized the host efficiently, but keep your eyes on reserved resources for `kubelet` and the node itself.

Very happy to see the status changed to **Coming Soon** after 2 years, and I hope we can soon try new native CNI to test the performance in large clusters.

**Comment by tsndqst** [comment]
Will this change increase the density when ENABLE_POD_ENI is true or only when it's false?  Currently there are very few pod ENIs on each host.

**Comment by davidroth** [comment]
@mikestef9  If only we could get an estimated release date. Its on "Coming Soon" since 2 months, but no idea if this means we need to wait another 2 months, 6 months, 1 year?

**Comment by Vlaaaaaaad** [comment]
@davidroth the definition of "Coming Soon" is in the FAQ on this repository:
> Q: What do the roadmap categories mean?
>
> Just shipped - obvious, right?
> Coming soon - coming up. Think **a couple of months out, give or take.**
> We're working on it - in progress, but further out. We might still be working through the implementation details, or scoping stuff out.
> Researching - We're thinking about it. This might mean we're still designing, or thinking through how this might work. This is a great phase to send how you want to see something implemented! We'd love to see your usecase or design ideas here.

Based on that, the release could be in 2 weeks, or it could be in 4 months. Software development is weird like that. AWS specifically never shares release dates; you never know if you'll discover a massive issue 2 days before release. "_You can now run a lot more pods, but we drop 50% of network packets_" is not something anybody wants.

There's also KubeCon+CloudNativeCon in October (and re:Invent in December), but that feels like a stretch.

**Comment by adelwin** [comment]
I'd like to say that some use-case is not necessarily for "increasing" the pod density. My use-case is actually to "reduce" the pod density.
We are running in an environment where VPC(and therefor IP) are shared from a centralized network account. And already sliced upfront to the number of accounts using the VPC.
And this led to an unfortunate situation where we actually "ran out of IP".

So my use-case is to actually reduce the pod density to about 30-40 pods per nodes.
- if I use the default ENI max pods setting, then the IP in my VPC will be drained before all others. not even any space to spin up a bastion host
-  having the "reduced" max pods actually means that I can predictably say "if the cluster is full, we will have utilized X amount of IPs

Solving this issue by setting the max pods in an obscure file inside the AMI seems to be bordeline "hard-coding".
I've managed so solve the issue temporarily by using launch templates as such.
```hcl
data "template_file" "launch_template_userdata" {
  template = file("${path.module}/templates/userdata.sh.tpl")

  vars = {
    max_pods  = 30
  }
}

resource "aws_launch_template" "default" {
  name_prefix             = "lt-${local.eks_name}-"
  update_default_version  = true

  user_data = base64encode(
    data.template_file.launch_template_userdata.rendered,
  )
...
}
```
```bash
# userdata.sh.tpl
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -e
sed -i -E "s/^USE_MAX_PODS=\"\\$\{USE_MAX_PODS:-true}\"/USE_MAX_PODS=false/" /etc/eks/bootstrap.sh
KUBELET_CONFIG=/etc/kubernetes/kubelet/kubelet-config.json
echo "$(jq ".maxPods=$max_pods" $KUBELET_CONFIG)" > $KUBELET_CONFIG
--//--

```

Now where did that snippet comes from? from eksctl code under `nodebootstrap/managed_al2.go`, adapted to Terraform.
So it's essentially, patching the kubelet.json during bootstrap

It'd be nice to have either the provider of modules from AWS does it with simplicity under `node_groups` variables perhaps?

**Comment by stevehipwell** [comment]
Is this having moved to coming soon related to [IP prefixes](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-virtual-private-cloud-vpc-customers-can-assign-ip-prefixes-ec2-instances/)?

**Comment by stevehipwell** [comment]
It looks like it is via a new [ENABLE_PREFIX_DELEGATION](https://github.com/aws/amazon-vpc-cni-k8s#enable_prefix_delegation-v190) option in the aws-vpc-cni. Based on the docs it looks like this should work with custom networking too.

**Comment by mikestef9** [comment]
Hey all,

You can run significantly more pods on AWS Nitro based instance types by upgrading to [VPC CNI v1.9](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.0) and leveraging the integration with the recently released EC2 prefix assignment [feature](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html). An additional benefit of this feature is improved pod launch times, especially in clusters with high pod churn or lots of nodes, as fewer EC2 API calls to allocate network interfaces are required to support IP addresses for pods. 

We expect to enable prefix assignment by default in a future release of the VPC CNI plugin. For now, you will need to set the variable `ENABLE_PREFIX_DELEGATION` to true and set a value for `WARM_PREFIX_TARGET`. More details can be found in the EKS [documentation](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html) and VPC CNI GitHub [repo](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/prefix-and-ip-target.md). 

For backwards compatibility reasons, the default max-pods value in the [file](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) built into the EKS AMI is not changing. For users with self managed nodes, we have included a helper [script](https://github.com/awslabs/amazon-eks-ami/blob/master/files/max-pods-calculator.sh) in the EKS AMI repo to help calculate the right max pods value based on instance type, CNI version, and CNI settings. Within the next few days, managed node groups will begin using a server side version of this formula to automatically set the right max pods value, as long as you have upgraded to VPC CNI version 1.9. This will help for both prefix assignment use cases, as well as [CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) where you previously needed to manually set a lower max pods value. (I will update this issue once that functionality has been fully rolled out for managed node groups)

- [What's New Post](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-vpc-cni-plugin-increases-pods-per-node-limits/)
- [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html)
- [EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html)

**Comment by tsndqst** [comment]
@mikestef9 Can you comment on my earlier question?  Based on the description and CNI code I'm guessing the number of IP addresses when using POD ENI will not increase with this change.
> Will this change increase the density when ENABLE_POD_ENI is true or only when it's false? Currently there are very few pod ENIs on each host.

**Comment by mikestef9** [comment]
`ENABLE_POD_ENI` is for a totally separate networking mode not related to this launch, ie each pod gets its own (branch) network interface, versus prefix assignment, where each pods get an IP from a prefix assigned to an interface. The number of branch network interfaces available per instance are advertised as a Kubernetes extended resource. There are essentially 3 distinct networking modes now with the VPC CNI plugin (in order of when they were launched):
1. [Pod gets an ENI secondary IP address](https://docs.aws.amazon.com/eks/latest/userguide/pod-networking.html)
2. [Pod gets a dedicated branch network interface](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)
3. [Pod gets an ENI prefix IP address](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html)

We are working on a containers blog post to dive into these networking modes in more detail, and use cases where each can be used.

**Comment by stevehipwell** [comment]
@mikestef9 could you confirm that `ENABLE_PREFIX_DELEGATION` will work correctly with custom networking?

**Comment by zswanson** [comment]
Am I reading this correctly that the new prefix feature does NOT allow use of security group on pods?

**Comment by z0rc** [comment]
@mikestef9 any way to manage vpc-cni configuration aside from editing env vars via kubectl? This approach isn't declarative, it isn't possible to set this var on cluster creation and can be accidentally overridden on addon upgrade.

**Comment by stevehipwell** [comment]
@z0rc I'd suggest using the official [Helm chart](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni).

**Comment by z0rc** [comment]
@stevehipwell AFAIK using helm chart introduces its own challenge where I need to delete existing deployment prior to chart installation.

**Comment by stevehipwell** [comment]
@z0rc that's what we do and again my recommended solution but there is the `originalMatchLabels` [value](https://github.com/aws/eks-charts/blob/252459778157bbb79dc54822239aaedbbe711371/stable/aws-vpc-cni/values.yaml#L52) to enable Helm to adopt the existing resources.

**Comment by mikestef9** [comment]
Yes, prefix delegation works with CNI custom networking enabled.

**Comment by jwenz723** [comment]
@mikestef9 does enabling CNI custom networking reduce the number of IPs available per instance when using prefix delegation? 

I believe 110 IPs are available to an m5.large instance when using prefix delegation without CNI custom networking. How many IPs would be available if CNI custom networking was enabled?

**Comment by chandrakanthkannam** [comment]
@mikestef9 this might be a basic question, lets say I have a m5.large worker node deployed in a subnet whose CIDR range is x.x.x.x/26 then irrespective of the instance type (even for larger instance) I will be only able to attach 4 (/28) prefixes correct? 

to make most of this implementation it's better to have larger CIDR ranges for the subnet where worker nodes deploy. Am I understanding it in the right direction?

**Comment by mikestef9** [comment]
@jwenz723 take a look at the helper [script](https://github.com/awslabs/amazon-eks-ami/blob/master/files/max-pods-calculator.sh) we recently added to the EKS AMI repo.
Previously with custom networking, a node could only have max 20 pods
```
./max-pods-calculator.sh --instance-type m5.large --cni-version '1.9.0' --cni-custom-networking-enabled
20
```
With prefix delegation, you still get one less ENI for pods, however, pod density is still much higher because you can attach a /28 prefix to each slot on the ENI, instead of a /32 individual IP.
```
./max-pods-calculator.sh --instance-type m5.large --cni-version '1.9.0' --cni-custom-networking-enabled --cni-prefix-delegation-enabled
110
```
In this case, you can actually attach 288 IPs to the instance (2 ENIs * (16IPs per 9 slots)), so you could override max pods to up to 288 if you wanted to. However, the script is following best practices and [capping](https://github.com/awslabs/amazon-eks-ami/blob/master/files/max-pods-calculator.sh#L143) this number at 110 for a smaller instance type.

@chandrakanthkannam correct, prefix assignment is not a solution for IPv4 exhaustion, as the prefixes are still pulled from your VPC subnets. By default, that means the worker node subnet. If using CNI custom networking, you can specify a separate subnet from the worker node.

**Comment by stevehipwell** [comment]
@jwenz723 depending on your daemonset usage you might be able to add a couple of IPs back from the host network.

**Comment by zswanson** [comment]
@mikestef9 can you clarify whether the new vpc prefix solution is compatible with Pod Security Groups?

**Comment by mikestef9** [comment]
Depends what you mean by compatible. As I explained [above](https://github.com/aws/containers-roadmap/issues/138#issuecomment-887782937), pod security groups leverages a separate networking mode, where each pod its own dedicated branch network interface. 

Can pod security groups getting branch interfaces co-exist with pods getting ENI prefix IP addresses in the same cluster and even on the same node? Yes

Is the prefix assignment launch related to pod security groups feature at all, and does prefix assignment help increase pod density if you are only running pods with dedicated security groups? No

Again, we are working on a blog to dive into this in more detail. You need to choose your networking mode/strategy based on your use case and requirements. If pod launch time and pod density on smaller instance types is important to you, and you can work with node level security groups, then use prefix assignment.

If you have security requirements where pods need a specific set of security groups, then use a SecurityGroupPolicy and pods will be allocated dedicated branch network interfaces with those security groups applied.

At the moment, there is no option to get the best of both worlds, ie pod level security groups with very high density and fast pod launch time. One potential idea is described in #1342, which we are researching, however, that becomes quite a tricky scheduling problem.

**Comment by zswanson** [comment]
> Can pod getting branch interfaces/security groups co-exist with pods getting ENI prefix IP addresses in the same cluster and even on the same node? Yes

@mikestef9 This is what I meant yes, hopefully your upcoming blog post will address this hybrid use-case too. There's workload on the clusters that doesn't need a pod security group and branch-eni (ie, prometheus, argo, etc) and packing more of those in per-node would be nice. 

Would there be any concern about a pod needing the branch-ENI for security groups getting scheduled on a node that is full on ENIs but had room for pods due to the prefixes? Or can the scheduler account for that?

**Comment by mikestef9** [comment]
No concerns with that, totally valid use case and is supported. The scheduler handles that. Prefix ENIs are associated with "regular" EC2 ENIs, while pods requiring security groups are attached to separate branch ENIs.

**Comment by zswanson** [comment]
That's fantastic thank you, this helps a lot.

**Comment by sstoyanovucsd** [comment]
@mikestef9, is it possible to optionally take sig-scalability's defined thresholds into account and limit the max pods per node on a managed nodegroup to min(110, 10*#cores).

Reference: [https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md)

**Comment by mikestef9** [comment]
What problem are you trying to solve by having us change to that formula? You think 110 is too high for an instance type like m5.large? This feature request is targeted at such users of m5.large where the previous limit of 29 was too low. 

The formula for MNG now is

<=30 vCPUs min(110, max IPs based on CNI settings)
>30 vCPUs   min(250, max IPs based on CNI settings)

This is based on internal testing done by our scalability team. However, it's impossible to simulate all possible combinations of real world workloads. As a best practice, you should be setting resource requests/limits on your pods. The point is IP address is no longer the limiting factor for pods per node when using prefix assignment.

**Comment by sstoyanovucsd** [comment]
I understand that this feature solves the issue with too few pods being allowed on a node that can potentially handle more.  Depending on the type of workloads, the opposite may also be needed i.e. setting max pods on the node to less than the IP/ENI limit would impose.  Setting maximums like the 110 and 250 is a good start, but it would be much better if it was a nodegroup setting that one can use to self-restrict nodes to a lower number.

We do set requests/limits per pod, but running at high pod densities leaves few resources to be shared by burstable workloads.  For example, some Java apps need the extra resources buffer to scale up as opposed to out.  When there's too many of these on a single node, memory pressure causes pods to get evicted from the node.  While this is a normal behavior, the startup time of such pods is not the best so we'd rather prevent such occurrences as much as possible.

**Comment by mikestef9** [comment]
Understood, that makes sense. Today, you can override the max pods setting when using managed node groups, but it requires extra effort. You need to use a launch template, specify the EKS AMI ID as the "custom" image ID in the LT, then manually add the bootstrap script in user data, like

```
#!/bin/bash
set -ex
/etc/eks/bootstrap.sh my-cluster --kubelet-extra-args "--max-pods=25"
```

I think it's a valid feature request to expose max pods directly through the MNG API, can you open a separate containers roadmap issue with that request?

**Comment by sstoyanovucsd** [comment]
Request submitted: [https://github.com/aws/containers-roadmap/issues/1492](https://github.com/aws/containers-roadmap/issues/1492)

Thanks!

**Comment by stevehipwell** [comment]
@sstoyanovucsd [terraform-aws-modules/terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) has a working pattern that doesn't require a custom AMI and [terraform-aws-modules/terraform-aws-eks#1433](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1433) shows how to optimise this as well as set other _bootstrap.sh_ options.

**Comment by mikestef9** [comment]
Blog is out that dives into this feature in more detail

https://aws.amazon.com/blogs/containers/amazon-vpc-cni-increases-pods-per-node-limits/

**Comment by gpothier** [comment]
Thanks @mikestef9 !
Quick question: how do I troubleshoot the Managed Node Group not updating the max pods per node configuration? I have the 1.9.0 CNI plugin (through the addon), I added the ENABLE_PREFIX_DELEGATION and WARM_PREFIX_TARGET values to the aws-node DaemonSet, and I deleted and recreated the MNG, but by max pods per node is still 17 (on t3.medium instances).

```
gpothier@tadzim4:~ (⎈ |ecaligrafix-playground-eks:default)$ kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni-init:v1.9.0-eksbuild.1
amazon-k8s-cni:v1.9.0-eksbuild.1
gpothier@tadzim4:~ (⎈ |ecaligrafix-playground-eks:default)$ kubectl describe daemonset -n kube-system aws-node | grep ENABLE_PREFIX_DELEGATION
      ENABLE_PREFIX_DELEGATION:            true
gpothier@tadzim4:~ (⎈ |ecaligrafix-playground-eks:default)$ kubectl describe daemonset -n kube-system aws-node | grep WARM_PREFIX_TARGET
      WARM_PREFIX_TARGET:                  1
gpothier@tadzim4:~ (⎈ |ecaligrafix-playground-eks:default)$ kubectl describe node |grep pods
  pods:                        17
  pods:                        17
  Normal  NodeAllocatableEnforced  24m                kubelet     Updated Node Allocatable limit across pods
  pods:                        17
  pods:                        17
  Normal  NodeAllocatableEnforced  24m                kubelet     Updated Node Allocatable limit across pods
```

**Comment by stevehipwell** [comment]
@gpothier have you updated the kubelet args to override the defaults?

**Comment by gpothier** [comment]
@stevehipwell No I haven't, but according to the blog post @mikestef9 linked, the MNG should take care of that:

> As part of this launch, we’ve updated EKS managed node groups to automatically calculate and set the recommended max pod value based on instance type and VPC CNI configuration values, as long as you are using at least VPC CNI version 1.9

Or did I misunderstand something?

**Comment by stevehipwell** [comment]
@gpothier sorry I hadn't read the blog post, I'll leave this one to @mikestef9.

**Comment by stevehipwell** [comment]
@mikestef9 what happens when we're using custom networking and ENI prefixes with the official AMI? We manually set `USE_MAX_PODS=false` in the env and add `--max-pods` to `KUBELET_EXTRA_ARGS` to both be picked up by _bootstrap.sh_.

**Comment by stevehipwell** [comment]
@mikestef9 could you also confirm that the other EKS ecosystem components work correctly with `ENABLE_PREFIX_DELEGATION` set, I'm specifically thinking of the _aws-load-balancer-controller_ but it'd be good to know that NTH and the CSI drivers have all been tested and work correctly.

**Comment by thanhma** [comment]
@stevehipwell I tested AWS Load Balancer Controller v2.2.0 on `ENABLE_PREFIX_DELEGATION` enabled cluster haven't seen any problem yet.

**Comment by mikestef9** [comment]
Support for prefix delegation was in v2.2 of LB controller

https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.2

@gpothier are you specifying an image id in a launch template used with the managed node group?

**Comment by gpothier** [comment]
@mikestef9 I didn't create the launch template explicitly, so I didn't specify an image id myself, but the launch template does exist and its image id is ami-0bb07d9c8d6ca41e8. The cluster and node group were created by terraform, using the terraform-aws-eks module.

**Comment by mikestef9** [comment]
I'm not very familiar with the Terraform EKS module. But if it is creating a launch template and specifying an image id (even if it's the official EKS AMI image id), that's considered a custom AMI to managed node groups, and the max pods override won't be set.

**Comment by stevehipwell** [comment]
> I'm not very familiar with the Terraform EKS module. But if it is creating a launch template and specifying an image id (even if it's the official EKS AMI image id), that's considered a custom AMI to managed node groups, and the max pods override won't be set.

Thanks @mikestef9 this is actually the answer I needed to my above question.

**Comment by gpothier** [comment]
Thanks a lot @mikestef9. As far as I can tell, the launch templates were created by the MNG, not by terraform. The `node_groups` submodule of the `terraform-aws-eks` module has the `create_launch_template` option set to false by default (and I do not override it). And I checked that there is no mention of the node groups' launch templates in the terraform state (the ones that appear here are used by the NAT gateways):
```
gpothier@tadzim4:~/ownCloud-Caligrafix/dev/ecaligrafix/infrastructure $ terraform-1.0.3 state list |grep launch_template
aws_launch_template.nat_gateway_template[0]
aws_launch_template.nat_gateway_template[1]
gpothier@tadzim4:~/ownCloud-Caligrafix/dev/ecaligrafix/infrastructure $ 
```

Also, in the AWS console, the node groups' launch templates appear to have been created by the MNG: the _Created by_ field says "arn:aws:sts::015328124252:assumed-role/AWSServiceRoleForAmazonEKSNodegroup/EKS".

**Comment by gpothier** [comment]
Hi @mikestef9, do you think you could give me a pointer on how to troubleshoot the Managed Node Group not updating the max pods per node configuration? Given that as far as I can tell I meet all the requirements, in particular the launch template is the one created by the MNG so I don't have control over it, I am a bit at a loss.

**Comment by mikestef9** [comment]
Do you have multiple instance types specified in the managed node group? If so, MNG uses the min value calculated for all instance types. So if you have a non nitro instance like m4.2xlarge for example, the node group will use 58 as the max pod value.

**Comment by gpothier** [comment]
@mikestef9 no, all instances are t3.medium

**Comment by gpothier** [comment]
Thanks @mikestef9 that was it! Although all the existing instances were indeed Nitro (t3.medium), the allowed instances included non-nitro ones. I recreated the MNG allowing only t3.medium and t3.small instances and the pod limit is now 110. 

This raises a question though: shouldn't the max pods per node property be set independently for each node?

**Comment by mikestef9** [comment]
Glad to hear it. Managed node groups must specify the max pods value as part of the launch template that we create behind the scenes for each node group. That launch template is associated with an autoscaling group that we also create. The autoscaling group gets assigned the list of desired instance types, but there is no way to know ahead of time which instance type the ASG will spin up. So to be safe, we pick the lowest value off all instance types in the list.

**Comment by mikestef9** [comment]
The recommended value of max pods is a function of instance type and the version/configuration of VPC CNI running on the cluster. At the time of bootstrapping, we don't have a way to determine the latter. We can't make a call to the API server (k get ds aws-node) and retrieve the CNI version because calls from there will not be authenticated until the aws-auth CM is updated first.

**Comment by lwimmer** [comment]
> The recommended value of max pods is a function of instance type and the version/configuration of VPC CNI running on the cluster. At the time of bootstrapping, we don't have a way to determine the latter. We can't make a call to the API server (k get ds aws-node) and retrieve the CNI version because calls from there will not be authenticated until the aws-auth CM is updated first.

I see. Thank you for the explanation.

**Comment by renebarbosafl** [comment]
How to override the 110 Max Pods enforcement in managed Node groups?

We are using m5.4xlarge nodes in our cluster and by default it has 234 max pods and 205 max pods (if using custom networking config). With prefix delegation we have only 110 max pods, even if using --max-pods-per-node 300 in our eksctl create nodegroup command.

How to get 300 pods running in a m5.4xlarge instance?
