### ISSUE TITLE
[Fargate] [Batch] [request]: Ephemeral Storage Parameter for Batch Job Definition

### ISSUE THREAD

**Issue by dalir** [aws/containers-roadmap#1383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
Fargate, Batch

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Batch Fargate has limit of 20Gb of ephemeral storage by default per job. ECS Fargate recently has introduced `ephemeralStorage` parameter that gives the option to set the ephemeral storage up to 200Gb in task definitions. However this parameter is not present for batch job definitions.

**Are you currently working around this issue?**
Work around ways at the moment is to either use EC2 batch environment instead of Fargate or use EFS with Fargate.

**Additional context**
Anything else we should know?
Document for ephemeralStorage in Task definiton: https://docs.aws.amazon.com/AmazonECS/latest/userguide/create-task-definition.html#task-definition-template 

###

**Comment by aitorres** [comment]
+1

**Comment by dsalaza4** [comment]
Are there any news regarding this?

**Comment by p0rygon** [comment]
I had to use the EC2 environment due to this issue. What a strongly needed feature!
It seems not to be prioritized :(

**Comment by laiKwunSing** [comment]
Mounting a NFS/EFS is not an acceptable option for a lot of tasks like handling small files or large throughput. Please prioritize this task. Thank you for your time!

**Comment by arunskurian** [comment]
+1 on this request.

**Comment by lavisht22** [comment]
Need this urgently for a prod workflow. Our pipeline started failing as files grew in size.

**Comment by andrey-legayev** [comment]
I've just bumped into disk size limit. 
This is what `df -h` shows inside container. 
So, currently we're limited to 15G free disk space which is not enough for our batch tasks.
Please add ability to configure size of volume. EFS will decrease performance.

```
Filesystem      Size  Used Avail Use% Mounted on
overlay          30G   14G   15G  48% /
tmpfs            64M     0   64M   0% /dev
shm              31G     0   31G   0% /dev/shm
tmpfs            31G     0   31G   0% /sys/fs/cgroup
/dev/nvme1n1     30G   14G   15G  48% /etc/hosts
tmpfs            31G     0   31G   0% /proc/acpi
tmpfs            31G     0   31G   0% /sys/firmware
```

**Comment by jonathan-gimpelman** [comment]
+1 on this issue my company is very interested in this feature

**Comment by rrana** [comment]
Bum, +1 please work on this feature request!

**Comment by aksel** [comment]
My company is very interested in this feature. Is there some way one can to contribute to this?

My contributions would probably be dubious at best, but I'd still love to help!

**Comment by nikhil-tahalramani** [comment]
AWS Batch launched the support for configurable Ephemeral Storage on AWS Fargate.  Customers can expand the available ephemeral storage beyond the default value of 20 GiB for your Fargate jobs to up to 200GiB! See the WN post for details: https://aws.amazon.com/about-aws/whats-new/2023/03/aws-batch-configurable-ephemeral-storage-fargate/

**Comment by nikhil-tahalramani** [comment]
@dalir @SaloniSonpal Could you please update this to launched?

**Comment by andrey-legayev** [comment]
So far I did not find how to use it via CloudFormation.
Does anyone know where parameter `ephemeralStorage` should be added?

**Comment by hpthomas** [comment]
^ Seconding this question - can this be used via CloudFormation or CDK? Also, the announcement linked above says that this can be configured via the `RegisterJobDefinition` API call, but I don't see it mentioned in the [docs for that call](https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html). 

Is there any documentation that describes how this feature can be used?

**Comment by nikhil-tahalramani** [comment]
Documentation:
https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobDefinitions.html
https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html
https://docs.aws.amazon.com/batch/latest/userguide/create-job-definition-Fargate.html

CFN support to follow within a week.
