### ISSUE TITLE
[EKS] Support for Kubernetes v1.22

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#1397]
**Tell us about your request**
EKS support for K8s v1.22

**Which service(s) is this request for?**
Amazon EKS

**Comment by stevehipwell** [comment]
Could we get K8s v1.22 onto the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)?

**Comment by johnkeates** [comment]
Well, this is a bummer. I thought a few months was the new release-to-EKS period to keep EKS more up-to-date but it appears that is not the case.

**Comment by xrl** [comment]
I can only assume Amazon is shifting priorities on EKS or the team is overwhelmed with outages and instability. Y'all hiring?

**Comment by johnkeates** [comment]
If EKS doesn't increase its predictability we can probably switch to rancher and just use the CNI, but I'd rather not.

**Comment by rubroboletus** [comment]
Dear Amazon, can you at least communicate? I know, that winter is comming, but I hope, you are not a bear.

**Comment by mreferre** [comment]
We are working on it, sorry for not having updated this issue sooner.

@xrl we think/hope we have been doing good with outages/instability but the EKS team is definitely growing and hence hiring. If you are interested in exploring the roles available please let me know offline. Thanks.

**Comment by stevehipwell** [comment]
> Could we get K8s v1.22 onto the Amazon EKS Kubernetes release calendar?

@tabern @mreferre

**Comment by johnkeates** [comment]
Thanks for the response! 😀

**Comment by mreferre** [comment]
> Could we get K8s v1.22 onto the Amazon EKS Kubernetes release calendar?

We are trying to be more cautious in how we communicate the availability of future releases because there are many factors that influence the cadence and there may be situations where a specific release takes longer to be available in the EKS service compared to our goals. Being more open while not creating false expectations is a fine line we all need to learn how to walk better. Needless to say we are always trying to improve our processes to be in a position to release new versions as soon as possible. I can say, however, that we will always trade "a few weeks" to match our high bar on security and stability. Which remain our priorities and what people came to love about (and expect from) EKS among other things.

**Comment by stevehipwell** [comment]
@mreferre I think a provisional date based on the current progress would be far better than leaving the calendar empty until shortly before the release. It's far better to be part of a conversation with a moving goal than to be left in the dark until the release date has been finalised. It'd be fine to asterisk uncertain release dates or even to use quarters, just as long as we're kept informed.

In this case we've only got until 2022-06-28 before Kubernetes v1.21 is official deprecated, so information enabling the planning of when we can do this work is really important.

**Comment by georgejohnis** [comment]
Hey everyone, sorry for the radio silence. Yes we are working on v1.22 for EKS. We expect this to be available in early 2022.  We will update the  [EKS release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) over the next few weeks as we narrow down on the exact date.

**Comment by inductor** [comment]
One thing that will be available(at least that I expect) is `CSIMigration` for Amazon EBS.

Right now I have running StatefulSets on my EKS cluster that uses in-tree storage provider with `gp2` and I would like to migrate it to `gp3` with EBS Storage Driver.

To do so, we need CSIMigration enabled as a feature gate on a cluster but at the moment EKS does not have it enabled, and it will be available as GA on 1.22.

**Comment by stevehipwell** [comment]
@inductor did you see the [Migrating Amazon EKS clusters from gp2 to gp3 EBS volumes](https://aws.amazon.com/blogs/containers/migrating-amazon-eks-clusters-from-gp2-to-gp3-ebs-volumes/) blog post?

**Comment by inductor** [comment]
@stevehipwell Oh I did not, I will have a look!

**Comment by 617m4rc** [comment]
Given the delay in the rollout of 1.22, are there any plans to extend support for 1.21? The transition period until September 2022 is not exactly opulent.

**Comment by stevehipwell** [comment]
It looks like the [calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) has been updated to show March 2022 as the release date for EKS v1.22.

**Comment by rubroboletus** [comment]
I understand, that releasing new version with all the vendor patches etc needs some time. But this long? At that time 1.24 will be almost released :-(

**Comment by stevehipwell** [comment]
@mikestef9 is there anything you can share with us around why the v1.22 release has taken so long? There may be things that the community could assist with moving forwards, but at a minimum it would help provide the context to understand and emphasise.

**Comment by pcgeek86** [comment]
kubectl is now complaining about minor version skew, because Amazon EKS is so far behind.

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

**Comment by johnkeates** [comment]
Yeah, this isn't great. I don't know if this is just an Amazon Thing™ at this point or if there is some complication with hosting a  custom managed control plane, but I do know that the results just aren't there.

**Comment by chickenbeef** [comment]
> kubectl is now complaining about minor version skew, because Amazon EKS is so far behind.
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
> WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
> ```

This is expected. You should use kubectl 1.20, 1.21 or 1.22:
https://kubernetes.io/releases/version-skew-policy/#kubectl

**Comment by johnkeates** [comment]
I started using things like https://github.com/kenichi-shibata/kubectl-switch for EKS clusters because my other context are all higher versions and will complain about a version skew if I use a kubectl that is on EKS's level on those other apiservers...

**Comment by pcgeek86** [comment]
My strategy is to ignore the warning and just use the newest version of `kubectl`. 😆

**Comment by mikestef9** [comment]
Kubernetes v1.22 is a larger effort for us than many prior Kubernetes versions, as 1.22 [removes](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) a number of deprecated APIs, including older versions for webhooks, custom resources, certificate signing, and ingress. So in addition to control plane changes, we've been working on updating many other components that previously relied on deprecated API versions. For example, we are working on providing and documenting an official way to sign [certificates](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/), given 1.22 removes the "legacy-signer" functionality that many customers are using #750. 

Additionally, behind the scenes we are moving to the out-of-tree [AWS cloud provider](https://github.com/kubernetes/cloud-provider-aws) as part of this launch, which allows us to move faster on AWS specific Kubernetes changes moving forward. 

Appreciate the patience as we get closer to launch. We also recognize v1.23 #1595 has been out for some time and v1.24 is expected in April, and we are considering multiple options for catching up.

**Comment by johnkeates** [comment]
Thanks again for the update @mikestef9, we're all very eager to see the upcoming release happen! It's also great to see a pretty precise date on the calendar!

**Comment by stevehipwell** [comment]
@mikestef9 are we still expecting EKS v1.22 to switch to Containerd by default? I think the original plan was to remove Docker altogether in v1.22, but it now looks like that will be happening in v1.23?

**Comment by mikestef9** [comment]
We delayed that change one version to 1.23. Dockerd will remain the default runtime in 1.22. See [docs](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html).

**Comment by stevehipwell** [comment]
> We delayed that change one version to 1.23. Dockerd will remain the default runtime in 1.22. See [docs](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html).

I was aware of the removal being moved back to EKS v1.23 but I though the default change was still planned for EKS v1.22? The original announcement of removal in the same release as changing the default sounded bold and a bit of a stretch, do you think Docker will actually be removed from EKS v1.24 without Containerd having been the default for a cycle?

On a related note, https://github.com/awslabs/amazon-eks-ami/pull/855 would make it much easier to change bootstrap args such as container runtime on MNGs. I'd be happy to add some docs on it's use to the guide once it's merged.

**Comment by stevehipwell** [comment]
@mikestef9 has the release date moved? I'm pretty sure the calendar previously said March 17th but now it's just saying March?

**Comment by johnkeates** [comment]
I spotted that change as well. I guess they are close but not as sure as they were when the last calendar change was made. Maybe they'll even release earlier. But it's still march, we'll see it when we see it.

**Comment by pcgeek86** [comment]
Kubernetes version 1.24 is due out on April 19th.

https://www.kubernetes.dev/resources/release/

**Comment by inductor** [comment]
One good sign of this progress

https://github.com/bottlerocket-os/bottlerocket/pull/1962

**Comment by srenzo-perceptolab** [comment]
Any news on this topic? It's the end of March and still nothing on sight

**Comment by baileydoestech** [comment]
Why are AWS so slow on this?

Appreciate 1.22 is more '_involved_' with a number of deprecations but looks like [Azure ](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) and [GKE ](https://cloud.google.com/kubernetes-engine/docs/release-notes) are already on 1.23. 

Are AWS so confident that people are tied into EKS they don't need to match the competition anymore?

**Comment by rubroboletus** [comment]
> Why are AWS so slow on this?
> 
> Appreciate 1.22 is more '_involved_' with a number of deprecations but looks like [Azure ](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) and [GKE ](https://cloud.google.com/kubernetes-engine/docs/release-schedule) are already on 1.23.

they are just waiting for some special date like 1. April

**Comment by tyrken** [comment]
Well, `amazon-eks-node-1.22-v20220317` AMI is now visible in eu-west-1 ...

**Comment by pcgeek86** [comment]
Vultr has 1.23.5 available, as of March 23rd, 2022 

https://www.vultr.com/zh/docs/vultr-kubernetes-engine-changelog/

Digital Ocean has offered 1.22 since March 3rd, 2022

https://docs.digitalocean.com/products/kubernetes/changelog/

**Comment by mariobris** [comment]
At least the latest patch versions would be nice to have more often

**Comment by inductor** [comment]
Everyone please calm down. I don't want any more notification that just complains about the schedule.

AWS has reasons to delay this and they put their schedule on it. Please hold on.

**Comment by inductor** [comment]
@pcgeek86 I get it but at the same time it's not productive to keep saying the exact same thing about which is obviously not ignored and recognised. I still need to be notified when 1.22 has officially been rolled out.

**Comment by stevehipwell** [comment]
> I still need to be notified when 1.22 has officially been rolled out.

It usually hits the recent announcements blog and/or container blog first.

**Comment by Skaronator** [comment]
Totally agree with @inductor. I subscribed to this issue to get an email when stuff starts moving or even get released. Unnecessary comments here don't change anything. If you want to apply pressure to AWS, then use your AWS contact directly.


> It usually hits the recent announcements blog and/or container blog first.

True, but you don't get an active notification, instead you would have to check the blog and filter by yourself. And you wouldn't update a production cluster within the first few days of release anyway, so subscribing to an issue is a valid use case.

---

Speaking of notifying about true progress. Just saw that the latest EKS AMI now contains a 1.22 version, which means that the EKS support is usually right around the corner (less than 10 days).

https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220317

**Comment by crechandan** [comment]
Any idea on Release of EKS 1.22 ? I think its already April 2022. Really appreciate any news here.

**Comment by dylanrichards** [comment]
Good news, there is an update available now!

![image](https://user-images.githubusercontent.com/13801547/161608537-e6ebe4a0-f684-4d52-b789-9cf6fb3956ec.png)

**Comment by stevehipwell** [comment]
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-1-22/

**Comment by EugeneChung** [comment]
But with eksctl 0.90.0, it shows `Error: invalid version, supported values: 1.18, 1.19, 1.20, 1.21`. I installed the latest eksctl with brew on Mac.

**Comment by mbevc1** [comment]
0.91 unfortunately doesn't include that change yet, but there is RC build that it does: https://github.com/weaveworks/eksctl/releases/tag/v0.92.0-rc.0

2022-04-08 09:45:29 [ℹ]  eksctl version 0.91.0
2022-04-08 09:45:29 [ℹ]  using region eu-west-1
Error: invalid version, supported values: 1.18, 1.19, 1.20, 1.21
```

**Comment by inductor** [comment]
https://github.com/weaveworks/eksctl/releases/tag/v0.92.0
