### ISSUE TITLE
Allow populating files from s3, ssm when starting a task

### ISSUE THREAD

**Issue by sj26** [aws/containers-roadmap#1405]
### Summary

Many applications require a config file or set of files. Running these applications on ecs currently requires building a custom container image which can load those files from s3, or similar. Cooking custom images for each application isn't a great developer experience, and creates additional operational burden. It would be wonderful is ecs had something like config maps, or could load volumes/files from s3 or ebs similar to loading env from ssm.

Originally in https://github.com/aws/amazon-ecs-agent/issues/328#issuecomment-445055747

### Description

I'd really like something in the realm of:

```
{
  "volumes": [
    // unsure of syntax, options include:
    // download every object under this prefix into a volume
    {"name": "config", "s3": {"uri":"s3://config.example.com/redis/"}}
    {"name": "config", "s3": {"bucket":"config.example.com", "prefix":"/redis/"}}
    // or individual objects
    {"name": "config", "s3": {"uri":"s3://config.example.com/redis.conf"}}
    {"name": "config", "s3": {"bucket":"config.example.com", "key":"/redis/redis.conf"}}
    // maybe many
    {"name": "config", "s3": {"bucket":"config.example.com", "keys":["/redis/redis.conf", "/redis/cert.pem"]}}
    // maybe archives, a la Dockerfile ADD and layer/volume exports
    {"name": "config", "s3": {"uri":"s3://config.example.com/redis.tar.gz"}}
  ],
  "containerDefinitions": [
    {
      ...,
      "mountPoints": [
        {"sourceVolume": "config", "containerPath": "/etc/redis/"}
      ]
    }
  ]
}
```

or even allow ssm secrets to be put onto disk instead of into env, or something.

I don't think these volumes should write back to s3, just initialise an ephemeral volume from s3. I'm mostly wanting read-only volumes which are loaded from s3 at task start, and I'm specifically interested in this capability on fargate.

A solid example is that I'm trying to run [pgbouncer](https://www.pgbouncer.org) in Fargate. It only allows configuration via files. We currently need to bake custom docker images which include an s3 utility to download some files into the right place before starting the service, or otherwise prepare the files from injectable configuration. We chose to build a tiny binary to grab the files from s3 because aws-cli is huge and we don't need most of it, it just makes booting our tasks slower. Ideally we'd be able to add something to our task definitions which would automate the process without requiring injecting extra binaries and take care of glueing the aws pieces together.

**Comment by angelcar** [comment]
Transferred this issue to the https://github.com/aws/containers-roadmap repo for proper tracking.

**Comment by vibhav-ag** [comment]
We are already tracking this issue here: https://github.com/aws/containers-roadmap/issues/56

**Comment by vibhav-ag** [comment]
@sj26 please feel free to +1 on that issue
