### ISSUE TITLE
ECS Anywhere: Windows Support

### ISSUE THREAD

**Issue by jasonumiker** [aws/containers-roadmap#1406]
It appears that ECS Anywhere does not support Windows Containers / External Instances.

Is this on the roadmap? If not then this is a request for it.

**Comment by Csantagadea** [comment]
Hi, this was released on March 2022. Link to What's New here: https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ecs-on-premises-orchestration-windows/

Blog post: https://aws.amazon.com/blogs/modernizing-with-aws/amazon-elastic-container-service-ecs-anywhere-support-on-windows/

Closing this issue.
