### ISSUE TITLE
[EKS]: CoreDNS add-on transitions to CREATE_FAILED when overwriting a manual installation

### ISSUE THREAD

**Issue by gws** [aws/containers-roadmap#1411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When installing the CoreDNS managed add-on overwriting a previously-installed set of CoreDNS resources, the add-on health check fails to detect the newly-created replicas. After a timeout period, the add-on status transitions to `CREATE_FAILED`, requiring CoreDNS downtime to resolve.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am attempting to perform a no-downtime transition to the CoreDNS managed add-on for EKS. It is extremely difficult to achieve reliably, because once the add-on transitions to CREATE_FAILED, only deleting and re-creating the add-on will resolve the situation. The period between add-on deletion and recreation incurs downtime for cluster DNS.

**Are you currently working around this issue?**
Avoiding use of the CoreDNS managed add-on for EKS for existing clusters that had a previous CoreDNS installation.

**Comment by cheeseandcereal** [comment]
A fix was rolled out for this bug which should be in all regions. If anyone is still experiencing this issue, please leave a comment. For anyone who currently has their CoreDNS addon in CREATE_FAILED, issuing a new create addon request should install successfully if the original root-cause was this issue (the particular error for this issue would be `InsufficientNumberOfReplicas`).

**Comment by tabern** [comment]
@cheeseandcereal rocks. Thanks!
