### ISSUE TITLE
[ECS][Fargate] [request]: CloudWatch Metrics for ephemeral_storage

### ISSUE THREAD

**Issue by haarchri** [aws/containers-roadmap#1414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently, CloudWatch ContainerInsights not displays Metric for ephemeral_storage

**Which service(s) is this request for?**
ECS Fargate - CloudWatch Metrics for ephemeral_storage

**Comment by ollypom** [comment]
In 2022, Container Insights added support for `EphemeralStorageReserved` and `EphemeralStorageUtilized` for Tasks running on AWS Fargate.

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-fargate-monitoring-storage-utilization/
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html
