### ISSUE TITLE
[EKS]: Kubernetes v1.16 End of Support (September 27th, 2021) [Updated]

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#1423]
Kubernetes version 1.16 on Amazon EKS will no longer be supported on ~~**July 25, 2021**~~  **September 27th, 2021**. On this day, you will no longer be able to create new 1.16 clusters. Existing 1.16 clusters will be automatically updated by Amazon EKS to the latest available platform version of Kubernetes version 1.17 through a gradual deployment process after the end of support date. 

We recommend you upgrade existing 1.16 clusters and worker nodes to at least 1.17 as soon as practical. 

Learn more:
* [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by georgejohnis** [comment]
Amazon EKS has extended the end of support date for Kubernetes version 1.16. The new end of support date for Kubernetes version is September 27th 2021.
