### ISSUE TITLE
EKS Cluster version upgrade 1.18 to 1.19 doesn't upgrade core deployments and daemon sets(CoreDNS,Kube-proxy & VPC CNI)  via cft

### ISSUE THREAD

**Issue by Srikanth1992** [aws/containers-roadmap#1424]
I have created a EKS cluster v1.18 using cloudformation template by passing clustername & version as parameters to cft stack.

So I have performed the eks cluster version upgrade to 1.19 by passing version number as parameter to the stack and aws eks update-stack was triggered and cluster version upgrade was successful.

Once cluster version was done successfully,  I have checked the versions of  core deployments and daemon sets( (CoreDNS,Kube-proxy & VPC CNI) but they didn't get upgraded to recommended version for EKS 1.19.

Do we have to manually upgrade them via aws cli?

Does EKS ControlPlane should be responsible for performing the  upgrades to core deployments and daemon sets(CoreDNS,Kube-proxy & VPC CNI) when eks cluster version was performed by cft.

Please let me know if you need more information

**Comment by tabern** [comment]
@Srikanth1992 add-on updates are not chained with the control plane update today. You will need to define all of the objects that you want to manage and update (cluster, add-ons, etc) in the CFN stack and then update them together. This can also be done via separate stacks. 

The issue for this feature is tracked here: https://github.com/aws/containers-roadmap/issues/600
