### ISSUE TITLE
[EKS] [request]: please use a config file for kube-proxy

### ISSUE THREAD

**Issue by dawidmalina** [aws/containers-roadmap#143]
**Tell us about your request**
We should migrate to config file for kube-proxy

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
There are a deprecated log entries during kube-proxy startup:
```
W0111 11:35:10.730137       5 server.go:195] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
```

Command line docs: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/
Config file "docs": https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-proxy/config/v1alpha1/types.go

**Comment by christopherhein** [comment]
Thanks for filing this here. Adding the original EKS AMI Issue for tracking as well.

https://github.com/awslabs/amazon-eks-ami/issues/149

**Comment by mbarrien** [comment]
Note that in my investigation, any EKS clusters created from 1.12 onwards use a config file (by mounting a configmap called kube-proxy-config) for kube-proxy. There is still the issue of migrating any EKS clusters created before 1.12 to using a configmap; this might be possible to do manually.

**Comment by mikestef9** [comment]
Closing as EKS has a config map for kube proxy for a while now
