### ISSUE TITLE
[EKS/Fargate] [request]: Unable to use KANIKO as builder of images for eks fargate containers

### ISSUE THREAD

**Issue by QualoZe0t** [aws/containers-roadmap#1431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
I would like to clarify if any docker building as a feature will be supported using by Kaniko ( not privilege mode ). I would like to have the possibility to build docker containers using kaniko scheduled via GitLab on EKS fargate profile.

**Which service(s) is this request for?**
EKS-fargate profile

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Our design is working on priciple that gitlab-runner (master) is deployed on EKS-fargate profile ( fargate cont)
After triggering pipeline from gitlab - gitlab-server itself is trying to deploy runner on another fargate container using by configuration specified on runner-confuguration itself + use image: as a source where is defined kaniko with debug mode for getting shell .. After deploying job in gitlab pipeline .. getting error that image: kaniko is not able to use .. 

**Are you currently working around this issue?**
How are you currently solving this problem?
currently I am building images directly deployed on the EKS cluster (ec2 nodes) where I am able to build containers

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by Hunter-Thompson** [comment]
It is possible to use Kaniko with Fargate.

https://aws.amazon.com/blogs/containers/how-to-build-container-images-with-amazon-eks-on-fargate/

This blog uses Jenkins, but I highly recommend looking at ArgoWorkflow.

**Comment by ollypom** [comment]
Hi @QualoZe0t , thank you for creating an issue.

I am one of the co-authors of the [blog](https://aws.amazon.com/blogs/containers/how-to-build-container-images-with-amazon-eks-on-fargate/) linked above and have succesfully ran Kaniko on EKS/Fargate. I am going to close this issue, but if you are still seeing an issue with Kaniko on EKS/Fargate, feel free to re open it.
