### ISSUE TITLE
[Batch] [ECS] [request]: Container Insights support for Batch jobs

### ISSUE THREAD

**Issue by ilyasotkov** [aws/containers-roadmap#1432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Trying to monitor individual jobs for AWS Batch is a poor experience. Container Insights support for AWS Batch jobs would help with this. Currently, this [AWS docs page](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html) explicitly states:

> Currently, Container Insights isn't supported in AWS Batch.

**Which service(s) is this request for?**
Batch (indirectly ECS and Fargate)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Monitor containerized AWS Batch jobs that could be running on EC2 or Fargate compute.

**Are you currently working around this issue?**
...

**Additional context**
...

**Attachments**
...

**Comment by seanv507** [comment]
@ilyasotkov just to be clear.  The underlying ECS job supports container insights, you just have to enable it in ECS cluster
you can retrieve the ecs task id  from your logstream name or from setting up https://docs.aws.amazon.com/batch/latest/userguide/batch_cwet.html
what is missing is link up between container insights/batch events stream and app logs...

**Comment by ilyasotkov** [comment]
AWS quietly rolled out Container Insights support for AWS Batch jobs. Works as you'd expect.

In Batch console, in the left sidebar, go to Console settings -> Permissions -> Container Insights and enable it for one (or all) of your compute environments.
