### ISSUE TITLE
[ECS/Fargate][bug]: Dockerfile healthcheck is ignored

### ISSUE THREAD

**Issue by paya-cz** [aws/containers-roadmap#1443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Using `HEALTHCHECK` instruction in `Dockerfile` is ignored by Fargate. The health status does not appear in the AWS Console, and the task will not get killed even if I make the healthcheck always fail. If I however setup the healthcheck in the task definition, it works fine and health status appears in the console as well.

**Which service(s) is this request for?**
Fargate

**Are you currently working around this issue?**

Duplicating healthcheck instruction via AWS CDK / Console does the trick.

**Additional context**
I use node.js v14, docker, and healthcheck process written in node.

**Comment by joebowbeer** [comment]
There is and has been a lot of discussion about Dockferfile HEALTHCHECK in AWS container issues.

Note that the HEALTHCHECK was added to Dockerfile for Docker Swarm, relatively recently.

I think the EKS (Kubernetes) approach to this is the most maintainable:

https://stackoverflow.com/q/41475088/901597

> Since Kubernetes 1.8, the Docker HEALTHCHECK has been disabled explicitly in Kubernetes.

I find that HEALTHCHECK depends a lot on deployment, so as a rule I do not add HEALTHCHECK to Dockerfile, but instead I add it to docker-compose, [ECS taskdef](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-healthcheck.html), and EKS Deployment, as needed.

**Comment by paya-cz** [comment]
Closed, dupe of #1041
