### ISSUE TITLE
[EKS] [request]: ENABLE_PREFIX_DELEGATION should be manageable by Add-on web UI or CFn/Terraform 

### ISSUE THREAD

**Issue by inductor** [aws/containers-roadmap#1456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
First of all, thank you very much for https://github.com/aws/containers-roadmap/issues/138. Thanks to this we can finally run more workloads per node now. Previously DaemonSets, Ingress controller and some system components pressured the pod-to-node assignment very badly.

Now, I see in [the documentation](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html), you must set `ENABLE_PREFIX_DELEGATION` environment variable as true to enable this feature after upgrading AWS VPC CNI plugin.

I understand that currently there's no other way to set this variable than to execute `kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true` from CLI, but this way is not *declarative* and I think this must be done by Terraform/CFn or any sort of GitOps way. One thing I can think of as a solution is managing CNI plugin with self-managed manifest or Helm, but it's not ideal since AWS provides CNI as an Add-on on EKS.

So, I believe there's a demand to make EKS Add-ons able to manage their environment variables.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

**Are you currently working around this issue?**
Execute `kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true` from CLI

**Additional context**

**Attachments**

**Comment by inductor** [comment]
Also I really hope that AWS doc describes something regarding [this](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/prefix-and-ip-target.md)...

**Comment by inductor** [comment]
This post looks fun to read if you're interested in this issue
https://aws.amazon.com/jp/blogs/containers/amazon-vpc-cni-increases-pods-per-node-limits/

**Comment by inductor** [comment]
Guess this is a good news?
https://aws.amazon.com/about-aws/whats-new/2022/12/eks-add-ons-supports-advanced-configuration/

**Comment by sriramranganathan** [comment]
Amazon EKS team recently announced the general availability of advanced configuration feature for managed add-ons. You can now pass in advanced configuration for cluster add-ons, enabling you to customize add-on properties not handled by default settings. Configuration can be applied to add-ons either during cluster creation or at any time after the cluster is created.

Using advanced configuration feature, you can now set ENABLE_PREFIX_DELEGATION environment variable for the Amazon VPC CNI add-on.

To learn more about this feature, check out this blogpost - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

Check out the Amazon EKS documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html

**Comment by dverzolla** [comment]
For TF use case: that's possible using `terraform-aws-modules/eks/aws/` module.

```
module "aws_eks" {
  source = "terraform-aws-modules/eks/aws//"

  cluster_name                   = "cluster-prod"
  cluster_version                = "1.28"

  cluster_addons = {
    vpc-cni = {
      most_recent = true
      configuration_values = jsonencode({
        env = {
          # Reference docs https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
          ENABLE_PREFIX_DELEGATION = "true"
          WARM_PREFIX_TARGET       = "1"
        }
      })
    }
  }
...
}
```
