### ISSUE TITLE
EKS EBS CSI Driver Beta release

### ISSUE THREAD

**Issue by leakingtapan** [aws/containers-roadmap#146]
**Tell us about your request**
EBS CSI Driver Beta 

**Which service(s) is this request for?**
EKS

**Comment by tabern** [comment]
https://github.com/kubernetes-sigs/aws-ebs-csi-driver

**Comment by whereisaaron** [comment]
A great extension goal for the EBS CSI driver would be support for VolumeSnapshot for EBS with k8s 1.12

https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/
https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/

Does this need a separate road map issue @tabern?

**Comment by tabern** [comment]
This driver is now available as Beta!

https://github.com/kubernetes-sigs/aws-ebs-csi-driver

**Comment by mikestef9** [comment]
This driver is now supported on EKS 1.14 clusters!

See the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) for more details

**Comment by whereisaaron** [comment]
Sadly @leakingtapan @mikestef9, VolumeSnapshot is [still alpha in 1.14 (and 1.15 and 1.16)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), so [EKS won’t support it](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html). So snapshots are sadly are at least 9 months away...
