### ISSUE TITLE
[ECR][Feature Request]:  Repository policies allowing roles from other accounts

### ISSUE THREAD

**Issue by pablods90** [aws/containers-roadmap#1467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
ECR Repository policies allowing roles from other accounts

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
[ECR repository policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html) allow to configure [cross-account access](https://aws.amazon.com/premiumsupport/knowledge-center/secondary-account-access-ecr/). They allow to add specific users in other accounts, but they **do not allow to specify roles**. Being able to specify roles in other accounts will enable customers to grant permissions to [ECS Task Execution roles](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html). There might be scenarios where granting access to the whole secondary account is not applicable and the intention would be to only allow ECS Tasks to have access to certain Docker Images. Even more, specific ECS Services using a given Task execution role may have access but some other services do not.

**Are you currently working around this issue?**
The alternative implies granting access to the whole secondary account for now. This requires limiting access to ECR in the secondary account only.

**Additional context**
N / A
**Attachments**
N / A

**Comment by toricls** [comment]
Hi @pablods90, thank you for reaching out to us!

It, specifying cross-account IAM roles in ECR repository policy, is available today, so now I'm guessing that you've already tried and couldn't make it working. If so, could you possibly share more details about what you've tried?

---

Just FYI but what I tested and succeeded was:
1) Have two AWS accounts, account A (pulling image from account B's ECR repo) and account B (storing image and allow account A via ECR repo policy)
2) In account A, create an ECS Task Execution role with the AWS managed `AmazonECSTaskExecutionRolePolicy` policy attached
3) In account B, create a `nginx` ECR repository and push `nginx:latest` image to that repository
4) In account B, configure the policy of the `nginx` ECR repository to allow account A's task execution role above
5) In account A, create an ECS task definition with the task execution role and to use account B's `nginx:latest` image
6) In account A, run an ECS task with the task definition above

Here is the repository policy I used.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ECR Repository Policy",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::{AWS_ACCOUNT_A_ID}:role/ecsTaskExecutionRole"
      },
      "Action": "ecr:*"
    }
  ]
}
```

**Comment by michaelb990** [comment]
As far as I know, this should work today. @pablods90 please let us know if you are having specific issues getting this working and we can take a look.

You should be able to use the first policy in our [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html), but instead of granting access to a `user`, you would use a `role` ARN.

**Comment by jlbutler** [comment]
Closing this one out, but @pablods90 if this was not resolved for you please reopen. Thanks!
