### ISSUE TITLE
[ECS] [request]: ECS Capacity Provider to work with Warm Pool instances in ASG

### ISSUE THREAD

**Issue by psaint** [aws/containers-roadmap#1471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Autoscaled ECS cluster with warm pool instances.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I using ECS with AutoScaling Group managed by Capacity Provider. I want to be able to scale-out fast and thus configured ASG to use Warm Pool instances. 
Right now Capacity Provider and Warm Pool instances are not fully compatible. 
Scaling-Out works as expected and new instances are added to the cluster almost instantaneously from Warm Pool.
However Scaling-In has some issues where sometimes it is stuck for a while trying to remove active instances with error:
> Cancelled: Could not scale to desired capacity because all remaining instances are protected from scale-in.

Leading to cluster running more instances then it's needed for all the tasks.

Other times it works fine:
>  Successful: Terminating EC2 instance: i-06efedxxxxx

**Are you currently working around this issue?**
When Scale-In gets stuck I remove Scale-In protection from unused instances.

**Additional context**
AWS Support Case 8669463111

**Comment by richardgavel** [comment]
@psaint How are you handling the registration of the instance into the ECS cluster? Are you letting it happen in user data and it gets added to cluster as it sits in the warm pool or do you have something custom to defer the registration til the scale out happens?

**Comment by g1001p** [comment]
me too!!!, Hi guys, Do you have any progress on this topic?

**Comment by vibhav-ag** [comment]
This is available now: https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ecs-supports-warm-pools-amazon-ec2-auto-scaling/
