### ISSUE TITLE
Amazon FSx for Lustre CSI Driver for Kubernetes

### ISSUE THREAD

**Issue by leakingtapan** [aws/containers-roadmap#148]
**Tell us about your request**
A CSI Driver that can make FSx for lustre filesystem available to application on Kubernetes as PV

**Which service(s) is this request for?**
EKS

**Comment by Akramio** [comment]
Thanks for opening this issue. Can you tell us a little bit more about the workload you're planning to run? For example, is this a machine training framework?

**Comment by StevenACoffman** [comment]
aws/aws-fsx-csi-driver#16

**Comment by tabern** [comment]
https://github.com/kubernetes/org/issues/467

**Comment by tabern** [comment]
Just shipped!
- https://github.com/kubernetes-sigs/aws-fsx-csi-driver
- https://aws.amazon.com/blogs/opensource/using-fsx-lustre-csi-driver-amazon-eks/
- https://aws.amazon.com/about-aws/whats-new/2019/04/aws-introduces-csi-drivers-for-amazon-efs-and-amazon-fsx-for-lus/

**Comment by mikestef9** [comment]
This driver has reached beta status and is now officially supported by EKS.

What's New: https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-eks-announces-beta-release-amazon-fsx-lustre-csi-driver/
Docs: https://docs.aws.amazon.com/eks/latest/userguide/fsx-csi.html
