### ISSUE TITLE
[EKS] [Query]: Managed Node Group scaling down doesn't work 

### ISSUE THREAD

**Issue by amitkatyal** [aws/containers-roadmap#1481]
I am not able to scale down the Managed Node group. I had deployed the 2 nodes cluster (Managed node group) and was able to scale the number of nodes from 2 to 3 but scaling down doesn't work. I tried from AWS managed console and CF template but no luck.

On scaling down the nodes, the node does go into the scheduling disabled state but the workload is not evicted from that node and eventually, the node becomes ready. 

Are we expecting a manual step to drain the workload?

For scaling up or down the managed node group, I am only updating the scaling config of the Managed node group.

NAME STATUS ROLES AGE VERSION
ip-10-0-24-220.ap-northeast-1.compute.internal Ready,SchedulingDisabled 101m v1.21.2-eks-c1718fb
ip-10-0-36-47.ap-northeast-1.compute.internal Ready 5h48m v1.21.2-eks-c1718fb
ip-10-0-5-244.ap-northeast-1.compute.internal Ready 25m v1.21.2-eks-c1718fb

**Comment by johnthedev97** [comment]
Do you have calico installed as following the official AWS docs? If yes, this could be the issue - https://github.com/tigera/operator/issues/1441

**Comment by amitkatyal** [comment]
@johnthedev97 Thanks for the quick reply!
Yes, I have calico installed following the AWS official docs. I'll test it w/o the calico & update it.

**Comment by amitkatyal** [comment]
I've tested w/o calico and it is working fine. Hence, closing this issue. Thanks.
