### ISSUE TITLE
[EKS] [request]: Official support for network policies and ARM workers

### ISSUE THREAD

**Issue by mtparet** [aws/containers-roadmap#1489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Provide official support for network policies to be able to use ARM workers.

**Which service(s) is this request for?**
EKS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently EKS does not official support network policy and rely on third parties. 
But Calico does not support ARM for now so anyone that care a little bit about security cannot use ARM workers...

**Are you currently working around this issue?**
No workaround for now, this is a blocker to run production workloads on EKS using Graviton workers.

**Additional context**
cf https://github.com/projectcalico/cni-plugin/issues/869

**Comment by sjastis** [comment]
Closing this issue as EKS supports network policies on EC2 graviton instances with the recent launch. To learn more about configuring it, please refer to --
(https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html)
