### ISSUE TITLE
[EKS] [request]: Release CNI Plugin 1.4 for EKS

### ISSUE THREAD

**Issue by mogren** [aws/containers-roadmap#149]
**Tell us about your request**
Next CNI release with all changes since CNI 1.3.2

https://github.com/aws/amazon-vpc-cni-k8s/milestone/5

**Which service(s) is this request for?**
EKS team, CNI plugin https://github.com/aws/amazon-vpc-cni-k8s

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Some major features have been added since the last release:
 * [Explicitly set the IP on secondary ENIs](https://github.com/aws/amazon-vpc-cni-k8s/pull/271)
 * [ENIConfig set by custom annotation or label names](https://github.com/aws/amazon-vpc-cni-k8s/pull/280)
 * [Fix return path of NodePort traffic when using Calico network policy.](https://github.com/aws/amazon-vpc-cni-k8s/pull/263)
 * [Many smaller bug fixes...](https://github.com/aws/amazon-vpc-cni-k8s/pulls)

**Are you currently working around this issue?**
Some users are currently limited by not being able to use these new features.

**Additional context**
Tracking issue for CNI 1.4

**Comment by mogren** [comment]
Created a [1.4 Milestone](https://github.com/aws/amazon-vpc-cni-k8s/milestone/5)

**Comment by StevenACoffman** [comment]
ref weaveworks/eksctl#736

**Comment by mogren** [comment]
Released on GitHub, but still not used in the default EKS AMI.

**Comment by StevenACoffman** [comment]
@tabern is this the AMI default now?

**Comment by mogren** [comment]
@StevenACoffman It's not yet the default, we are working on a few minor tweaks, like updating metrics to work with the new prometheus endpoints (https://github.com/aws/amazon-vpc-cni-k8s/pull/413) and some Calico cleanups (https://github.com/aws/amazon-vpc-cni-k8s/pull/410, https://github.com/aws/amazon-vpc-cni-k8s/pull/421) before making it the default.

**Comment by StevenACoffman** [comment]
Where can we track the change to AMI default, if not this issue?

**Comment by StevenACoffman** [comment]
@mogren I see 1.4.1 just released with all the issues you mention merged. Is there a tracking issue for when 1.4.x will be the AMI default?

**Comment by tabern** [comment]
Hey @StevenACoffman this is actually the issue for tracking 1.4.2 as the AMI default. We closed it in error last week.

**Comment by mogren** [comment]
Still not the default, but we will roll it out soon.

**Comment by mogren** [comment]
Starting today, CNI v1.4.1 is the default for new EKS clusters. If you were using the old `cni-metrics-helper`, please update to the newer build.
