### ISSUE TITLE
[ECS] [request]: Support ENI trunking for m6i instances

### ISSUE THREAD

**Issue by juan-pascale** [aws/containers-roadmap#1491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support ENI trunking for m6i instances

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I run lot of containers in an ECS cluster, some of them use awsvpc networking mode and since I updated the cluster to m6i, not all the tasks can run due to a lack of ENI resources. 

**Are you currently working around this issue?**
Running the cluster in m5

**Additional context**
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html#eni-trunking-supported-instance-types

**Comment by joshuabaird** [comment]
To clarify - ENI trunking *is* supported on `m6i`, but the ENI limits with ENI trunking enabled are much lower on `m6i` compared to `m6g` and `m5`:

* 40 ENIs on m5.2x/m6g.2x
* 19 ENIs on m6i.2x

We tried to deploy `m6i.2xlarge` recently and had to rollback immediately because of this.  I'm curious why the ENI limit on `m6i` is much lower than m5/m6g?  Will it be increased?  If not, we're stuck on m5.2xlarge for now.

**Comment by juan-pascale** [comment]
When I created the request, the page wasn't up to date, now I saw it updated and look at this:

![image](https://user-images.githubusercontent.com/34168227/131965566-aa7633ea-7899-4b61-8636-127d941e2e28.png)

ENIs with trunking in m6i.large are 1, and without trunking are 2.

**Comment by toricls** [comment]
Closing since the docs has been updated now. Feel free to reopen if I'm missing something!

**Comment by joshuabaird** [comment]
Why is the limit on `m6i` less than `m5` and `m6g`?
