### ISSUE TITLE
[ECS] Tagging & Cost Allocation

### ISSUE THREAD

**Issue by pauncejones** [aws/containers-roadmap#15]
Support for AWS resource tagging and cost allocation tags for ECS and Fargate. 

What's New post: https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-ecs-and-aws-fargate-now-allow-resources-tagging-/

**Comment by daveslutzkin** [comment]
Any chance of getting CloudFormation support for this excellent functionality?

**Comment by Nr18** [comment]
Would love to see support for CloudFormation as well.
