### ISSUE TITLE
[eks] [request]: Please publish kube-proxy helm chart

### ISSUE THREAD

**Issue by tomelliot16** [aws/containers-roadmap#1503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Please publish kube-proxy charts use with eks.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We cannot use kube-proxy eks addon as we need to set service requests for the service because we need to tune around scaling a cluster. We want to rely on a helm chart for kube-proxy that we can tune the resource requests of.

**Are you currently working around this issue?**
Right now we are not setting the service request however it puts kube-proxy at risk in our clusters. We are thinking we might need just to pull the raw manifest from the cluster and convert into a makeshift chart however this feels very wrong and one off.

**Comment by jj-fontana** [comment]
Hi,
This a mandatory for all EKS addon because since addons have been introduced the sources files are no more maintained in the amazon-eks S3 bucket for CNI, Proxy and CoreDNS..
A lot of users don't want to (or can't) mix AWS and Kubernets resources management (CF or Terraform for AWS and Helm for Kube).
Futhermore, as customers using SElinux cannot run AWSCNI addon without modifying it, it should be mandatory to provide the source yaml files so we can tune them and make it work.
It's not a big work overhead to push the files in the s3 bucket like it was done before IMO.

Thanks.

**Comment by sriramranganathan** [comment]
Amazon EKS team recently announced the general availability of advanced configuration feature for managed add-ons. You can now pass in advanced configuration for cluster add-ons, enabling you to customize add-on properties not handled by default settings. Configuration can be applied to add-ons either during cluster creation or at any time after the cluster is created.

Using advanced configuration feature, you can now set the resource requests and limits for the kube-proxy addon. Additionally, if you need direct access to the raw manifest, you can delete the add-on with the preserve flag set. Please check this link - https://docs.aws.amazon.com/eks/latest/APIReference/API_DeleteAddon.html

To learn more about this feature, check out this blogpost - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

Check out the Amazon EKS documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html

**Comment by stevehipwell** [comment]
@mndoci could you please re-open this issue as it's not been resolved. When removing the add-on (or not installing it) it still needs to be managed externally and a Helm chart for this would both be useful and consistent with how other components can be managed.

**Comment by mikestef9** [comment]
@stevehipwell are you ok using #1045 to track request for helm charts for add-ons?

**Comment by stevehipwell** [comment]
@mikestef9 is there likely to be some feedback on #1045 about how to progress this? I'd be happy to contribute a chart for `kube-proxy` but I'd need a bit of guidance about which repo the source should live in?
