### ISSUE TITLE
[EKS] [request]: Instance Store for Managed Node Groups

### ISSUE THREAD

**Issue by mariomerco** [aws/containers-roadmap#1539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Provide the option of standing up Managed Node Groups with Instance Store instead of EBS.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
[Instance Store](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) is an alternative to EBS which volume is an **ephemeral device** that lives only during the life of the EC2 instance. In the world of containers, most of the times a worker node is really **disposable**, so some times there's **no need to have all the EBS functionality** around if it is only for storing Container Images (which, if not present they will be downloaded to the node) and the instanced containers.

With Instance Store, could represent **cost savings** and **performance boosts** for most of the workloads.

**Are you currently working around this issue?**
Just using EBS. For Sandbox environments we are going to develop a CloudFormation template to manage the Worker Node with Instance Store, but it loses all the features of a Managed Node Group.

**Comment by mikestef9** [comment]
There shouldn't be anything special about managed node groups with instance store family instances. The following issues have some context on setting the right user data commands to take advantage of instance store volumes

https://github.com/awslabs/amazon-eks-ami/issues/326
https://github.com/awslabs/amazon-eks-ami/issues/349

**Comment by mariomerco** [comment]
@mikestef9 right, that's how we are doing it now. Custom launch templates for managed node groups are a new feature, it came after we raised this feature request

**Comment by mikestef9** [comment]
Managed node groups launch templates was launched in 2020, but this feature request was opened several weeks ago? Either way, if you have everything working, I'll close this issue
