### ISSUE TITLE
[Fargate] [request]: Task Limit Notification

### ISSUE THREAD

**Issue by sarphram** [aws/containers-roadmap#154]
**Tell us about your request**
We hit the default limit on number of tasks we can run in Fargate and would like a way to send out a notification/alert/etc if we hit this.

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
There doesn't seem to be a direct way to query for the limit or send a notification on this specific event happening.

**Are you currently working around this issue?**
Considering a CWE rule on Create/UpdateService calls and looking for mention of a limit being hit.

**Comment by SaloniSonpal** [comment]
We just launched Usage Metrics and applied Service Quotas visibility for Fargate. You can now proactively monitor Fargate resource usage against quotas and configure alarms to alert about usage approaching a service quota. Usage metrics and service quotas can both be retrieved using the Console, AWS CLI, and SDK.
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-fargate-launches-usage-metrics-applied-service-quotas-visibility/
