### ISSUE TITLE
[EKS] [request]: PodSecurity admission control

### ISSUE THREAD

**Issue by sftim** [aws/containers-roadmap#1542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add [Pod Security admission control](https://kubernetes.io/docs/concepts/security/pod-security-admission/) into EKS
 - document a way to run the Pod Security admission webhook safely
 - build in Pod Security admission control (currently alpha, but on course to become beta) into EKS itself
 - configure reasonable defaults

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Restrict access to run privileged containers. Only trusted, cluster-critical or node-critical components should be able to use Pods that launch a privileged container. More broadly, I want to disallow a workload from elevating its privileges via a container / containment escape.

It's hard to do this well because Pod Security admission is an essential security control. If you run this component as an in-cluster workload, and it fails, then either:
- you enabled fail-dangerous, and a DoS attack can become an elevation of privilege
- you set the admission webhook to fail safe, and now your cluster can't launch any Pods, including for healing. Maybe even critical Pods like CoreDNS and the CNI plugin can't launch.

With that in mind, it's useful to either have a documented method for adding Pod Security admission or, better, to have it available as part of EKS itself.

**Are you currently working around this issue?**
Various options, including using (deprecated) [PodSecurityPolicies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).

**Additional context**
- follows on from https://github.com/aws/containers-roadmap/issues/174

Pod Security admission is the in-tree replacement for PodSecurityPolicy, which will is scheduled to disappear from Kubernetes in v1.25.

**Comment by dec5e** [comment]
v1.22 is not under support anymore, v1.23 has Pod Security Admission in beta, v1.23 has a full support and PodSecurityPolicies are removed. ([ref](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html))

This issue is not relevant anymore?
