### ISSUE TITLE
[EKS] [request]: Enable Bandwidth support on VPC-CNI addon

### ISSUE THREAD

**Issue by edwardaskew** [aws/containers-roadmap#1543]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Enable the Bandwidth plugin support added to the vpc-cni plugin by aws/amazon-vpc-cni-k8s#1560 by default when using the EKS vpc-cni addon

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have an EKS cluster where pods occasionally experience high spikes in network usage which cause the node that pod is on to temporarily become unavailable. We would like to be able to limit the bandwidth use of these pods.

**Are you currently working around this issue?**
We are currently using cpu and memory limits as a proxy for network usage as these are correlated. However, choosing the correct limits for these proxy metrics requires a certain amount of experimental fiddling that a direct limit would not.

**Additional context**
#865 would allow us to work around the issue in a more robust way than manually updating the daemonset manifest (which we've avoided so far) but I'm not sure I can see any good reason *not* to have this enabled by default

**Comment by mikestef9** [comment]
This was launched as part of VPC CNI v1.10

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.10.0
