### ISSUE TITLE
[Fargate] [request]: Windows Server 2022 support

### ISSUE THREAD

**Issue by SaloniSonpal** [aws/containers-roadmap#1547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for other windows versions, specifically 2022.

**Which service(s) is this request for?**
Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The recently launched ECS/Fargate support for Windows containers supports Windows Server 2019 only (#508)
https://aws.amazon.com/about-aws/whats-new/2021/10/aws-fargate-amazon-ecs-windows-containers/
This request is to add support for other windows versions, specifically 2022.

**Comment by goyalpurvi** [comment]
This is now launched and available in AWS commercial regions: https://aws.amazon.com/about-aws/whats-new/2022/08/aws-fargate-microsoft-windows-server-2022-images-amazon-ecs/
