### ISSUE TITLE
ECS Fargate: Add support to Windows Nano Server (Windows Containers)

### ISSUE THREAD

**Issue by FANMixco** [aws/containers-roadmap#1556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
**Add support to Windows Nano Server in Fargate**

**Which service(s) is this request for?**
**ECS, Fargate**

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I was trying to run a container using a Windows Container with Windows Nano Server in Fargate with ECS, but it failed. The app works fine in EC2, but every EC2 instance is considerably expensive, especially, because I have to run only one app there. This post provides you with some context of my challenge:
https://dev.to/fanmixco/how-to-create-a-nexus-repository-with-windows-containers-e0p

This is the current error:

> CannotStartContainerError: CannotStartContainerError: hcs::System::CreateProcess 9e93bb86b5a54b4ca30e552e3dd99a47-2388863384: The system cannot find the file specified.: unknown

**Are you currently working around this issue?**
- An EC2 instance where you have to open some ports.
- I'm trying to build a new image with Windows Core but this one has a significant limitation. The image would be over 1 GB vs around 200 MB.

**Additional context**
[Anything else we should know?](https://dev.to/fanmixco/how-to-create-a-nexus-repository-with-windows-containers-e0p)

**Attachment:**
[example_not_working.txt](https://github.com/aws/containers-roadmap/files/7543658/example_not_working.txt)
[example1.txt](https://github.com/aws/containers-roadmap/files/7543659/example1.txt)

**Comment by vsiddharth** [comment]
Thanks a lot for reporting this @FANMixco . 

Could you please share additional details around the ECS task/container definitions for us to debug this further?

**Comment by FANMixco** [comment]
Hi @vsiddharth, I attached the examples to the case. Thanks!

**Comment by jterry75** [comment]
@FANMixco - Thanks for providing the examples. I think you'r hitting a known bug that we are tracking for a fix unrelated to NanoServer. In your task definitions I see that you'r not setting an EntryPoint or a Command for the container. I'm guessing that the image you are pulling from ECR has a default command/entrypoint and that is why your not passing them. Unfortunately there is a known issue in containerd that will cause this to fail to start until we get the fix in place. For now could you retry your task definition with an EntryPoint or Command (or both) even if these are identical to what is set in the image already?

Let me know how it goes.

**Comment by FANMixco** [comment]
Hi @jterry75,

I found that the bug happens in this line:

> WORKDIR c:/nexus/nexus-3.36.0-01/bin
> CMD ["nexus.exe /run"]

In EC2, it works perfectly, but in Fargate requires this specific syntax:

> CMD [ "c:\\nexus\\nexus-3.36.0-01\\bin\\nexus.exe", "/run" ]

Something is odd in my opinion. The second syntax work in both cases.

**Comment by jterry75** [comment]
Hey @FANMixco,

Providing an update since it is taking a lot longer to upstream the fix to containerd than expected. Unfortunately Docker runtime (which is used ECS+EC2) is doing something proprietary here that is not supported by the OCI Image Spec that the community supports. On Fargate we use containerd as the runtime and it cannot cope with what Docker has done in this case. 

In your example:

```
CMD c:\\nexus\\nexus-3.36.0-01\\bin\\nexus.exe /run
```

this ends up creating a Docker image in the manifest that looks like this:

```
            "Cmd": [
                "cmd /S /C c:\\\\nexus\\\\nexus-3.36.0-01\\\\bin\\\\nexus.exe /run"
            ],
            "ArgsEscaped": true,
```

The problem with this is that `ArgsEscaped` is not supported in OCI and when containerd tries to run this image it then takes Cmd[0] and escapes the arg (again). When it tries to launch the resulting string it fails.

We have a discussion ongoing here about how to support this in containerd: https://github.com/containerd/containerd/pull/6479

For now, the safest option is to use the `EXEC` form of the CMD as you have shown in your second example:

```
WORKDIR C:/nexus/nexus-3.36.0-01/bin
CMD ["nexus.exe", "/run"]
```

Which is encoded like this:

```
            "Cmd": [
                "nexus.exe",
                "/run"
            ],
            "WorkingDir": "C:\\nexus\\nexus-3.36.0-01\\bin",
```
Note how none of the args are escaped and Docker does not include the `ArgsEscaped` entry in the json.

**Comment by FANMixco** [comment]
Hi @jterry75, we were able to publish it, here you have a tutorial how to create it:

https://dev.to/fanmixco/how-to-create-a-nexus-repository-with-windows-containers-e0p

However, the **nanoserver** is still not working as expected. We kept the other version for AWS and our images are significantly bigger.

**Comment by jterry75** [comment]
@FANMixco - Would you be willing to try Nanoserver out again on the latest platform with the same changes to the Dockerfile you mentioned and provide an updated error message? I think it was missed that this is nanoserver specific given the ArgsEscaped bug that was found first.
