### ISSUE TITLE
[Fargate] [request]: disable remote-execution "Shutdown as a Service"

### ISSUE THREAD

**Issue by lifeofguenter** [aws/containers-roadmap#156]
**Tell us about your request**

It would be great - similar to autoscaling-groups, to be able to set the health-check-type to "FARGATE" as opposed to currently "ELB" - in which it will take the FARGATE/container health (e.g. if the container is running or exited) instead of the target-groups health-check. (see: https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#health_check_type)

**Which service(s) is this request for?**

Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Because http based health-checks are being forced, depending on the deployed web-application (see: https://thisdata.com/blog/making-a-rails-health-check-that-doesnt-hit-the-database/) it is possible to remotely shutdown someones server simply by hitting any of their public URL and basically causing the health-check to fail due to overload.

Fargate will unfortunately FIRST drain "faulty" containers before launching new ones, thus completely putting the service offline 😱 

**Are you currently working around this issue?**
We are setting the health-check to ridiciously high settings

**Additional context**
-

**Attachments**
-

**Comment by clareliguori** [comment]
Hi @lifeofguenter, I believe using the following configuration would resolve this issue for you:
* Set `healthCheckGracePeriodSeconds` in the ECS service to MAX_INT (2,147,483,647).  This effectively disables ECS from stopping containers that are failing load balancer health checks.
* Configure a [Docker health check](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck) in your task definition, so you have an alternative method of making sure that your application is still running in the container.  ECS will use this non-LB health check to determine when the container should be stopped
* Set the load balancer health check config (like UnhealthyThreshold) back to reasonable settings so it can be used for traffic routing decisions by the LB (and will no longer be used by ECS to determine whether a container should be stopped)

**Comment by lifeofguenter** [comment]
Thanks @clareliguori!
