### ISSUE TITLE
[ECR] [request]: Option For Full vs. Incremental Replication For Cross Account ECR Replication

### ISSUE THREAD

**Issue by jrbil** [aws/containers-roadmap#1568]
### Community Note
- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
&nbsp;

**Tell us about your request**

(Submitted on behalf of customer.)

When a new image tag is pushed to the Source registry the Destination registry only gets the small delta changes (new images) and not the entire Source repository images. Can there be an option of full vs. incremental replication?

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

**Are you currently working around this issue?**
No

**Comment by pdhav** [comment]
Thank you for converting the request into this ticket.

**Comment by jlbutler** [comment]
We are tracking this on #1289  , will close this one out. Thanks
