### ISSUE TITLE
[ECR] [request]: "Push Manual Replication" Button In The ECR Console

### ISSUE THREAD

**Issue by jrbil** [aws/containers-roadmap#1569]
### Community Note
- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
&nbsp;

**Tell us about your request**

(Submitted on behalf of customer.)

Add a "Push Manual Replication" button as a forced manual step in the ECR Console.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
N/A

**Are you currently working around this issue?**
No

**Comment by pdhav** [comment]
Thank you very much converting the request into a ticket.

**Comment by jlbutler** [comment]
@jrbil Apologies for coming to this so late. Can you elaborate on the feature request? I'd like to understand more what "push manual replication" means. I'll set this closing soon in case it's gone stale or is no longer relevant. 
Thanks!
