### ISSUE TITLE
[eks] [request]: AMI to use v5.10 kernel

### ISSUE THREAD

**Issue by stevehipwell** [aws/containers-roadmap#1570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
With the [GA release of the v5.10 kernel](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-linux-2-ami-kernel-5-10/) I'd like to see this used in the EKS AMI images.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to make use of the improvements that the v5.10 kernel provides, especially round eBPF.

**Are you currently working around this issue?**
n/a

**Additional context**
n/a

**Attachments**
n/a

**Comment by stevehipwell** [comment]
It looks like the EKS AMI code has been updated by [awslabs/amazon-eks-ami#765](https://github.com/awslabs/amazon-eks-ami/pull/765) to support the v5.10 kernel.

**Comment by akestner** [comment]
Closing this issue as shipped 🚀

Starting with the [EKS AMI Release v20230217](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230217) for Kubernetes versions 1.24 and above, the default kernel version for the non-accelerated EKS Optimized AMI is 5.10.
