### ISSUE TITLE
[service] [request]: Add DNS support for Windows Containers (EC2) with FSx

### ISSUE THREAD

**Issue by FANMixco** [aws/containers-roadmap#1571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

I wanted to connect the FSx directory that I created in AWS and there were issues because we had to modify the VM manually in EC2 and add these commands:

```
netsh interface ipv4 set dnsservers "Interface Name" static preferred-DNS-address primary
netsh interface ipv4 add dnsservers "Interface Name" alternate-DNS-address index=2
```

In order to connect the FSx with our Windows Instance. I wouldn't imagine this situation in the future with Fargate where we cannot modify the instance.

**Which service(s) is this request for?**

- ECS with EC2.
- ECS with Fargate.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Connect an FSx volume with the EC2 Windows Server. We had to do all configurations manually and the container failed without any log. It only said status 1. There were no logs or anything that could give us a hint.

**Are you currently working around this issue?**
How are you currently solving this problem?

We had to add the IPs manually in the EC2 instance.

**Additional context**
Anything else we should know?

N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by goyalpurvi** [comment]
hi @FANMixco 
In case you missed the announcement, for ECS on EC2, you can do this with DNS (launched in Feb 2022): https://docs.aws.amazon.com/AmazonECS/latest/developerguide/wfsx-volumes.html
For ECS on Fargate, there is a workaround available in this blog: https://aws.amazon.com/blogs/containers/use-smb-storage-with-windows-containers-on-aws-fargate/
