### ISSUE TITLE
[EKS] [request]: Enable Admin container for Bottlerocket hosts with launch template

### ISSUE THREAD

**Issue by der-eismann** [aws/containers-roadmap#1576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Since I want to attach a custom security group to my EKS workers I needed to create a launch template. However when doing that I can't configure SSH access to the worker anymore because the security group and key is taken from the launch template.
The problem now is that this isn't enough to get SSH access to Bottlerocket. One also needs to set the following line in the userdata:
```
[settings.host-containers.admin]
"enabled" = true
```
But it is impossible to set this from the launch template because the userdata gets overwritten by EKS.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want SSH access to a Bottlerocket worker that was created with a launch template.

**Are you currently working around this issue?**
Haven't found a way.

**Comment by der-eismann** [comment]
I just saw that it is not true that EKS is overwriting this, the docs say
> Bottlerocket structures user data in the TOML format. You can provide user data that is to be merged with the user data provided by Amazon EKS.

**Comment by mikestef9** [comment]
EKS only merges the user data needed for nodes to join the cluster, 

`settings.kubernetes.cluster-certificate`
`settings.kubernetes.api-server`
`settings.kubernetes.cluster-name`
`settings.kubernetes.cluster-dns-ip`

Any other Bottlerocket settings you can set in the launch template, such as admin container
