### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.15 on Vulnerability Scans

### ISSUE THREAD

**Issue by rgoltz** [aws/containers-roadmap#1578]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Tell us about your request
What do you want us to build?
Add support for Alpine 3.15 on vulnerability scans

Which service(s) is this request for?
ECR

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
My images no longer get scanned for vulnerabilities, it used to scan it before 26.11.2021 but have now stopped for version Alpine 3.15 and says `UnsupportedImageError: The operating system 'alpine' version 'v3.15' is not supported`.

![image](https://user-images.githubusercontent.com/16392819/143609450-223f33b5-6d66-4f71-8793-4ac196051728.png)

Are you currently working around this issue?
How are you currently solving this problem?
Not solving it, currently it fails on Amazing ECR image scans.

Feedback from AWS Support? (from 26.11.2021)
> After reaching out to our internal service team, I do want to inform you that alpine:3.15 is currently not supported for image scan functionality.
> Please note that the alpine:3.15 version was pushed one day ago. It takes a while to update the database with the latest alpine version. You should be able to use the previous version while this one is not yet supported.
> We will add support for it later but this is the expected behavior as of now.

**Comment by xXPOLYGONXx** [comment]
Right now Clair doesn't support Alpine version 3.15
There is a [merge request](https://github.com/quay/claircore/pull/524) pending, which includes this version and would enable Clair to Scan the newest Alpine Image.

**Comment by rgoltz** [comment]
We've re-tested scanning of Docker-Images in AWS/ECR based on Alpine 3.15 successfully. Today, claircore has been released the including the above mentioned PR from Jamie.

I'll go ahead and close this issue as resolved on Clair- and AWS-level. Thanks for providing this PR :)

**Comment by rgoltz** [comment]
Hi @KyleKotowick. The ECR Scan Function in AWS is working in our account without issues, while using Alpine 3.15 - it's tested in eu-central-1 region. You are using a public image? - If yes, I can run a re-test in our account by adding to our ECR repo and triggering a scan. Best, Robert

**Comment by KyleKotowick** [comment]
It's a private image in us-east-1 for us, unfortunately. Thanks for the confirmation though.

**Comment by vasireddy99** [comment]
> Hi @KyleKotowick. The ECR Scan Function in AWS is working in our account without issues, while using Alpine 3.15 - it's tested in eu-central-1 region. You are using a public image? - If yes, I can run a re-test in our account by adding to our ECR repo and triggering a scan. Best, Robert

Hi @rgoltz , I am currently testing this image in `public.ecr.aws/aws-observability/aws-otel-collector:latest` in my private ECR repository. can you please provide any insights. or let me know if a new issue needs to be created to track it.

**Comment by blakepettersson** [comment]
> I am currently having the same issue as @KyleKotowick but i am using alpine:latest and the scan status is `UNSUPPORTED_IMAGE`.

Seeing the same issue. I'm using a pull-through cache of `ecr-public` FWIW.

**Comment by tallpaul-embark** [comment]
I am having the same issue as @vasireddy99 with public.ecr.aws/aws-observability/aws-otel-collector:v0.29.1
