### ISSUE TITLE
[EKS] [request]: Managed etcd service

### ISSUE THREAD

**Issue by jaxxstorm** [aws/containers-roadmap#158]
**Tell us about your request**
Abstract away the etcd portion of EKS so that those of us need more cluster flexibility (ie, managed controlplanes and the ability to set API flags for things like oidc configuration) can have less overhead in our cluster managed.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Because of EKS's lack of control over the controlplane, we're building our clusters manually using configuration mgmt (kubeadm). Unfortunately, the hardest part for us is the etcd part.

It would be awesome to have etcd as a service in AWS, for Kubernetes clusters as well as other services which might want to use etcd

**Are you currently working around this issue?**
Manual management of etcd

**Comment by tabern** [comment]
Not planned in EKS.
