### ISSUE TITLE
[ECR]: Pull through cache for authenticated registries 

### ISSUE THREAD

**Issue by srrengar** [aws/containers-roadmap#1584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
ECR launched pull through cache recently which reliably and anonymously retrieves public images from ECR Public and Quay.io, caches them in a customer's private ECR registry, and keeps the images in sync. Customers also want the same functionality for other private registries that require authentication, and registries need accounts to have higher pull limits
https://aws.amazon.com/blogs/aws/announcing-pull-through-cache-repositories-for-amazon-elastic-container-registry/

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
To cache images from private registries or images from public registries that require authentication for higher pull limits. Customers need to pass credentials through ECR pull through cache for ECR to access the images from private registries or to let ECR have access to higher pull limits. 

**Are you currently working around this issue?**
Customers need to build tooling to log in to private registries, copy those images into ECR, and keep those images in sync with the upstream private registry, and maintain this entire system.

**Comment by benjimin** [comment]
Would this also enable anonymous access, proxied through the customer's VPC, and some configuration for how frequently image tags (such as `latest`) are polled for updates?

Maintaining our own ECR sync lambda system has a tendency to counter-productively retrieve even more image versions than we actually need (e.g. skipped increments, alternate architectures).

**Comment by afirth** [comment]
## Working around - dockerhub

1. adding image-pull-secret to every namespace and every service account as required. Usually after they break once, e.g. during a cluster upgrade when we have to redeploy all the managed nodes at once. Outages caused in the past by spot-termination-handler, aws-alb-ingress-controller, kube2iam (that was bad because downstream services didn't crashloop), and probably others. [This](https://github.com/titansoft-pte-ltd/imagepullsecret-patcher) exists, but ends up either patching all serviceAccounts including the AWS and K8s ones like `kube-system/statefulset` and `kubesystem/aws` or needing manual config for every service anyway.
2. Moving images to ECR. This is mostly ok except that
    1. we build with skaffold, and the ECR login system doesn't work with the docker-api, so need to override that to use docker-cli
    2. devs adding services from helm/upstream are typically unaware of the imagePullSecret requirement (or alternatively image registry, if separately exposed in the chart) << biggest problem
    3. dependabot setup is not so straightforward
    
2.ii. would be solved if EKS/ECR supported setting something like 
```json
{
  "registry-mirrors": ["https://mirror.gcr.io"]
}
```

ideally 1) without editing bootstrap data (just slap it in [here](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) :trollface:) and 2) without using gcr

**Comment by joebowbeer** [comment]
Being able to configure our ECR to pull-through our private GitHub Container Registry (ghcr) would be super.

**Comment by sumanthkumarc** [comment]
👍

**Comment by mwos-sl** [comment]
One more use case ew have is several deployments across different aws regions. We need a pull through cache in each each region for images produced by CI into one of the regions, for services like ECS and EKS. Why not ECR replication? Costs. We don't need all of the images in each region to be replicated, only used one.

**Comment by wosiu** [comment]
Excited to see "Work in Progress" label!
@coultn is there any ETA for this to be GA? Asking because we've got very hot discussion about alternatives in out company. And ETA could help to judge whether we should wait for a native aws solution or invest in developing some workaround in-house.

**Comment by mwos-sl** [comment]
Bumping question for ETA for pull through caching of private registries hosted on AWS?

**Comment by blakepettersson** [comment]
Now ACR has support for pull-through caches (Azure/acr#599), at least for Dockerhub (which still is a whole load more images than ECR pull-through supports). Given the rate things are going it's likely that ACR will build out its support for other registries way before ECR...

**Comment by seumassoltysik** [comment]
Hard to believe this is not an existing capability. We use artifactory on the corporate build level but it would be great to mirror that docker registry with ECR running in account in which we have our Jenkins and EKS infra running.

**Comment by tigercxx** [comment]
Just tried pull through repository for a private docker repository in GAR, and it worked smoothly. Surprised to see that it's not supported in ECR yet.

**Comment by rfulwell** [comment]
@rnene100 I see [you added](https://github.com/aws/containers-roadmap/issues/1584#event-10857849010) the `Coming Soon` label. Can you provide any more details?
![image](https://github.com/aws/containers-roadmap/assets/470472/7f897fb4-ae2c-4532-9afc-fd8d14e7fb36)

**Comment by rnene100** [comment]
Amazon Elastic Container Registry (ECR) now includes Docker Hub, Azure Container Registry, and GitHub Container Registry as supported upstream registries for ECR’s pull through cache feature.
See announcement- https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-pull-through-cache-additional-upstream-registries/

**Comment by nxf5025** [comment]
> Amazon Elastic Container Registry (ECR) now includes Docker Hub, Azure Container Registry, and GitHub Container Registry as supported upstream registries for ECR’s pull through cache feature. See announcement- https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-pull-through-cache-additional-upstream-registries/

So this will only work for those registries and not others such as a privately hosted Artifactory?

**Comment by Sodki** [comment]
> Amazon Elastic Container Registry (ECR) now includes Docker Hub, Azure Container Registry, and GitHub Container Registry as supported upstream registries for ECR’s pull through cache feature.

I'm confused about this decision. Why couldn't it be a generic solution since the vast majority of Docker registries work in the same way and authenticate in the same way? We're on GitLab, so we can't take advantage of this.

**Comment by wosiu** [comment]
@rnene100 does the new functionality allows ECR pull-though cache for ECR in abother region?
So basically these 2 use-cases mentioned in this thread:
1) https://github.com/aws/containers-roadmap/issues/1584#issuecomment-1710477241
2) https://github.com/aws/containers-roadmap/issues/1584#issuecomment-1253452879

After reading the announcement it sounds like it is still not supported :(

**Comment by rnene100** [comment]
@wosiu ECR to ECR pull through cache is not part of this but something we are actively considering. I don't have a timeline on that. Thanks for checking.

@Sodki Our goal is to continue to add support for additional upstream registries that authenticate in the same way (will add GitLab to the list).

@nxf5025 AWS Lambda is looking at adding this support. I don't have timelines on that but I have reached out to the team. Thanks for checking

**Comment by wosiu** [comment]
@rnene100 I don't this this ticker should be marked as closed. Many people (including me) have been voting for this one because of ECR to ECR pull-through. Now we need to start from 0 when collecting votes, which means tens of months before it gets a critical mass and start being considered by AWS.

**Comment by mmerickel** [comment]
Is there a different open issue for tracking that? I’m here for the ecr to ecr as well as ecr from self-hosted-gitlab-in-private-vpc features. But since the latter feels very far off - the ecr to ecr is really important for folks doing regional deployments on standard aws offerings.

**Comment by rnene100** [comment]
@mmerickel Please open a separate issue for ECR to ECR pull through cache so that it's easier to track. As mentioned earlier, we are actively considering that feature. Thank you!

**Comment by wosiu** [comment]
Opened: https://github.com/aws/containers-roadmap/issues/2208
Anyone here, please vote for this one

fyi @mmerickel

**Comment by karaluh** [comment]
@rnene100 Any update on Lambda support for this?

**Comment by thejosephstevens** [comment]
@rnene100 , I'm seeing that Quay.io is not among the providers with support for auth, is it best to open a separate Github Issue for that? Along the lines of Sodki's comment, it's not clear why there isn't a generic provider for Docker-compatible registries supporting basic auth (that's basically what ACR and GCP Artifact Registry did). ACR allows you to override the hostname of registries, so you could coerce an unsupported registry to fit, and Artifact Registry just gives you a full `Custom` option where you provide the hostname and auth. Since all the ECR options lock the hostname config I'm stuck having to move to a different registry in order to do auth'd caching.

**Comment by abhivyakti-d** [comment]
Amazon ECR now supports ECR to ECR pull through cache, enabling customers to cache images from one ECR private registry to another, across AWS regions and/or accounts. 
See announcement– https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-ecr-cache-repositories/

This address the following use-cases mentioned in the thread–
[[ECR]: Pull through cache for authenticated registries  #1584 (comment)](https://github.com/aws/containers-roadmap/issues/1584#issuecomment-1710477241)
[[ECR]: Pull through cache for authenticated registries  #1584 (comment)](https://github.com/aws/containers-roadmap/issues/1584#issuecomment-1253452879)

**Comment by hobti01** [comment]
@abhivyakti-d perhaps you mistakenly linked the old announcement and meant this one? https://aws.amazon.com/about-aws/whats-new/2025/03/amazon-ecr-pull-through-cache/

**Comment by abhivyakti-d** [comment]
> [@abhivyakti-d](https://github.com/abhivyakti-d) perhaps you mistakenly linked the old announcement and meant this one? https://aws.amazon.com/about-aws/whats-new/2025/03/amazon-ecr-pull-through-cache/

yes corrected- thanks!

**Comment by bilnels** [comment]
This feature has been released
https://aws.amazon.com/about-aws/whats-new/2025/03/amazon-ecr-pull-through-cache/

**Comment by jaferrando** [comment]
Still needing pull through cache for Quay authenticated repositories. Why was this closed with part of the use cases not met?

**Comment by joebowbeer** [comment]
@rnene100 Remove labels `Proposed`, `Work in Progress` and `Coming Soon`, and add label `Shipped`?

@jaferrando See https://github.com/aws/containers-roadmap/issues/2652 for private quay

**Comment by ggjulio** [comment]
@joebowbeer , I don't see any docs updated. 
- https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-creating-rule.html

Is what have been stated in the issue implemented ? 
Can we do pull through from private oci registry while being authenticated?
