### ISSUE TITLE
Support Fargate Spot for Graviton for ECS/EKS

### ISSUE THREAD

**Issue by melaraj2** [aws/containers-roadmap#1594]
It was great to see that now Graviton2 is supported on Fargate, but we are still missing spot support.  Is this coming soon?

I currently run most of my dev workloads in spot Fargate services, but I would love to switch to Graviton. However, without spot support, the cost would be much greater; it kind of beats the notion of better price-performance!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by ciphero** [comment]
Any update on the progress here? Would be great to have this!!

**Comment by kennu** [comment]
Also interested in this, would be great to have the option to freely choose ARM vs. X64 for spot containers.

**Comment by rahzsha** [comment]
Any updates on this feature request?

**Comment by guilhermemunizsantos** [comment]
It will help a lot in cost reduction and temporary scalability.

**Comment by dmytroillarionov** [comment]
Also looking forward to switch to Fargate Spot on ARM

**Comment by kastningj** [comment]
Looking forward to this. We use ARM64 across the board. It's sizeable lift to switch back to X64, but it would help a lot for cost reduction. Please make this a priority!

**Comment by anton-demydov-zoral** [comment]
Would love to see graviton spot

**Comment by ciphero** [comment]
Apologies for being a bringer of bad news... but for those that are not aware and with high hopes of seeing this feature request implemented anytime soon (maybe?), someone working in the AWS containers team recently made this comment on a related Reddit thread:

> I'm on the container services team at AWS. I can assure you that Fargate Spot + ARM64 is not a thing (yet). What will happen is in your service's event tab it will say that it was unable to find capacity to launch any tasks. The Spot market is basically for selling unused compute capacity (often powered by older generations of hardware) at a discount. Graviton and ARM64 instances are so new and so popular that we don't really have extra unused compute capacity to offer at a Spot discount.

Source: https://www.reddit.com/r/aws/comments/17maney/comment/k7oqlqy/

**Comment by Smotrov** [comment]
> so popular that we don't really have extra unused compute capacity to offer at a Spot discount.

If so, how he would explain that I'm perfectly using EC2 backed ECS with Spot C7G?

**Comment by CGarces** [comment]
> > so popular that we don't really have extra unused compute capacity to offer at a Spot discount.
> 
> If so, how he would explain that I'm perfectly using EC2 backed ECS with Spot C7G?

Because probably Fargate not use C7G. 
The last time that I check, was using M5 and C5 for x86, probably the same happens with ARM64.

**Comment by BrentOnRails** [comment]
Related.  Graviton arch isn't supported on EKS Fargate currently. https://github.com/aws/containers-roadmap/issues/1629

**Comment by herrhound** [comment]
Today we added Graviron support for Amazon ECS / Fargate Spot compute:

https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-ecs-graviton-based-spot-compute-fargate/

Note, Fargate Spot is not available with Amazon EKS.

**Comment by guilhermemunizsantos** [comment]
Great!! Already testing!

**Comment by vibhav-ag** [comment]
Marking this done- please create a separate one for EKS Fargate if still needed.

**Comment by gatesjd** [comment]
@vibhav-ag or @jenmlinaws: Please remove EKS from the description as only the ECS part of the request was shipped.
