### ISSUE TITLE
[EKS]: Support for Kubernetes v1.23

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#1595]
**Tell us about your request**
EKS support for K8s v1.23
https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/

**Which service(s) is this request for?**
Amazon EKS

**Comment by stevehipwell** [comment]
@mikestef9 could we get a rough date added to the [calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) for v1.23 now that v1.22 has been released?

**Comment by stevehipwell** [comment]
For anyone watching this issue the [EKS release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) has been updated to show EKS v1.23 as planned for August 2022.

**Comment by georgejohnis** [comment]
EKS support for Kubernetes version 1.23 is now available!

- [What's new post](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-eks-distro-support-kubernetes-version-1-23/)
- [EKS Blog](https://aws-blogs-prod.amazon.com/containers/amazon-eks-now-supports-kubernetes-1-23/)
- [EKS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23)

NOTE: If you are running stateful workloads using Amazon EBS on your cluster, please pay close attention to the call out in EKS documentation about installing EBS CSI driver prior to upgrading your cluster to version 1.23.

**Comment by ahamlinman** [comment]
@georgejohnis It looks like that blog link points to an internal Amazon site, and the public post is at https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-1-23/
