### ISSUE TITLE
[ECS Fargate] Allow increasing ephemeral storage on Windows

### ISSUE THREAD

**Issue by mwcampbell** [aws/containers-roadmap#1598]
AWS's documentation is inconsistent about whether the ephemeral storage of Windows Fargate tasks can be increased from the default 20 GiB. When I try to increase it, I get this error:

PlatformTaskDefinitionIncompatibilityException: One or more of the requested capabilities are not supported.

**Comment by pkrbj** [comment]
I need this feature. 20GB is nothing for Windows containers and my windows containers refuse to launch on Fargate.
ECS with EC2 is a no-go. Who wants to maintain Windows infrastructure?  Please provide a method to increase disk space for Windows containers.

 CannotPullContainerError: ref pull has been retried 1 time(s): failed to extract layer sha256:20ba09231e05c5bd253427261d27d7f26e7588bfe682b586a2767f0419305236: hcsshim::ImportLayer - failed failed in Win32: There is not enough space on the disk. (0x70)...

**Comment by jterry75** [comment]
@pkrbj - Thank you for the additional information. Would you mind sharing the size of your overall image including Windows Base Layers it is build from? This is on our roadmap but would like to understand your use case more as well.

**Comment by pkrbj** [comment]
@jterry75  I'm trying to launch a microsoft supplied docker container on Fargate - https://hub.docker.com/_/microsoft-msedge-msedgedriver

When I launch it, I get the following error:
CannotPullContainerError: ref pull has been retried 1 time(s): failed to extract layer sha256:20ba09231e05c5bd253427261d27d7f26e7588bfe682b586a2767f0419305236: hcsshim::ImportLayer - failed failed in Win32: There is not enough space on the disk. (0x70)...


`[
    {
        "Id": "sha256:bccca5631c2b1a8b0c95db09c1039a9cfe6789b47c1ec91e75417dfb64ce476d",
        "RepoTags": [
            "mcr.microsoft.com/msedge/msedgedriver:latest"
        ],
        "RepoDigests": [
            "mcr.microsoft.com/msedge/msedgedriver@sha256:237ea19f5dedc1d48d2da71664257a0a32422c371252a44b9d6430e92bdad8b8"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-10-17T22:48:29.9699299Z",
        "Container": "63cd7bc5c12da010e6ea3054a6151bea175c33f8a4ced265f3dcc1d3b1034a73",
        "ContainerConfig": {
            "Hostname": "63cd7bc5c12d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9515/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH_WITH_SPACE=c:/msedgedriver/",
                "EDGE_PATH=C:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Edge SxS/Application/"
            ],
            "Cmd": [
                "cmd",
                "/S",
                "/C",
                "#(nop) ",
                "ENTRYPOINT [\"msedgedriver.exe\" \"--verbose\" \"--whitelisted-ips=\"]"
            ],
            "Image": "sha256:49dc6769032e5579c82b1a67404bebc8281bc7bca459365f15c4fa83551780f0",
            "Volumes": null,
            "WorkingDir": "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Microsoft\\Edge SxS\\Application",
            "Entrypoint": [
                "msedgedriver.exe",
                "--verbose",
                "--whitelisted-ips="
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "stahon@microsoft.com"
            }
        },
        "DockerVersion": "19.03.2",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9515/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH_WITH_SPACE=c:/msedgedriver/",
                "EDGE_PATH=C:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Edge SxS/Application/"
            ],
            "Cmd": null,
            "Image": "sha256:49dc6769032e5579c82b1a67404bebc8281bc7bca459365f15c4fa83551780f0",
            "Volumes": null,
            "WorkingDir": "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Microsoft\\Edge SxS\\Application",
            "Entrypoint": [
                "msedgedriver.exe",
                "--verbose",
                "--whitelisted-ips="
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "stahon@microsoft.com"
            }
        },
        "Architecture": "amd64",
        "Os": "windows",
        "OsVersion": "10.0.18362.418",
        "Size": 14073333256,
        "VirtualSize": 14073333256,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\2f8281ad260c3e26905944585dfbc47de4e7a1e0956eeb1facb72f32e2803815"
            },
            "Name": "windowsfilter"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:33636467ff66aabeebf693cbbede2fbf6312accb3139c1e66ffadcd3d2a97c90",
                "sha256:20ba09231e05c5bd253427261d27d7f26e7588bfe682b586a2767f0419305236",
                "sha256:eb09c5d117f196d4868291a3acebae25b21b5765d88a5e740f8a8d618c9f8110",
                "sha256:1785e2765e5dc5b9e0adf20e720b655e7a709f5071d771cdeb4e07ce3ef0a228",
                "sha256:7f0d2bc931043841e89dab4856334c96425265d84640a786541338a44c226ee4",
                "sha256:e75432334326851ed71a40490da16090c6fe463756f9f67a7a2194f928f236b8",
                "sha256:b2321d5bc88496af5be20749091f08a6ce68d6d2d34ad56b8f8d0c86d534edfa",
                "sha256:206b1246ecaee0cdbc516abaa9a1918dc9d6833d8351216d7a87c2ac73af9d2f",
                "sha256:ba5583b60743c9efa03fd031098a61b4a037156eec194ac25abf2489aa26bee2",
                "sha256:f0bf059dbb9010a7eb23dbbdb96129373f04c477fb19f6ef2b2160b5657280b8"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
`

Output of docker  image
`C:\Users\Administrator>docker image ls | findstr bccca5631c2b
mcr.microsoft.com/msedge/msedgedriver   latest    bccca5631c2b   2 years ago   14.1GB

C:\Users\Administrator>docker image history bccca5631c2b
IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
bccca5631c2b   2 years ago   cmd /S /C #(nop)  ENTRYPOINT ["msedgedriver.…   41kB
<missing>      2 years ago   cmd /S /C #(nop) WORKDIR C:\Windows\System32…   41kB
<missing>      2 years ago   cmd /S /C powershell.exe -Command     Invoke…   75.6MB
<missing>      2 years ago   cmd /S /C #(nop)  EXPOSE 9515                   41kB
<missing>      2 years ago   cmd /S /C #(nop)  ENV EDGE_PATH=C:/Windows/S…   41kB
<missing>      2 years ago   cmd /S /C #(nop)  ENV PATH_WITH_SPACE=c:/mse…   41kB
<missing>      2 years ago   cmd /S /C powershell.exe -Command     $edgeI…   909MB
<missing>      2 years ago   cmd /S /C #(nop)  LABEL maintainer=stahon@mi…   41kB
<missing>      2 years ago   Install update 1903-amd64                       4.81GB
<missing>      2 years ago   Apply image 1903-RTM-amd64                      8.28GB
`

**Comment by jterry75** [comment]
Yea unfortunately that image is right on the storage boundary. When you consider the compressed layer tar files, and then the uncompressed layers that are unpacked on disk you end up with ~20GB of space. Problem is that the image itself is not based on any of the base images we cache and is effectively rolling its own base image. This means that there is no space savings of the image and it consumes the entire drive space available for customer layers. Ephemeral storage is a must for an image like this and unfortunately there are no workarounds at the moment. You could potentially apply the edge installer yourself in a servercore based image if possible and see if you can make a smaller image. But not sure since I really don't track edge or what its requirements are.

**Comment by janivimal** [comment]
Hello,
Is there way to rectify this issue ? 
I am trying to run windows container on fargate. I have provisioned 30 GB memory in my task definition and the image (including base) size to run this task,  is around 15 GB and still get this error;

"CannotPullContainerError: ref pull has been retried 1 time(s): failed to extract layer sha256:9f7d281f701e6f21614d8e0e7bbc08f5650c427949acbc81977689ab82763f30: hcsshim::ImportLayer - failed failed in Win32: There is not enough space on the disk. (0x70): unknown"

Really appreciate your help here,
Thank you

**Comment by parisholley** [comment]
running into the same issue, trying to run InDesign Server which only works on the full docker image `mcr.microsoft.com/windows:1809-amd64`, suppose my only resort is to launch my own ec2 instances :(

**Comment by croddin** [comment]
@jterry75 You mentioned that the base layer may not count towards the storage quota if it is cached. Is there a list anywhere of what base images are cached?

**Comment by jterry75** [comment]
@croddin - To my knowledge the only text on that is here: https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/pull-behavior.html#fargate-windows-behavior. But it basically says this:

We cache the latest servercore:ltsc2019 for each months AMI released every Patch Tuesday (2nd Tuesday of the Month). If your container image is based off the latest months servercore:ltsc2019 image, the base images would be included in the cache and therefore not count toward the 20GB space.

**Comment by hb2638** [comment]
We have the same problem. We created a gitlab runner ( https://docs.gitlab.com/runner/configuration/runner_autoscale_aws_fargate/ ) that has VS Build Tools 2019. It will start up but will blow up as we start pulling stuff from git and building.

See the below docker file... It's already big and we tried to trim it down further by commenting out the "nice to haves"

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Add root user so gitlab runner can ssh into server as "root"
#RUN NET USER root /RANDOM /ADD
RUN NET USER root /ADD
RUN NET localgroup Administrators root /ADD
USER root

# Install 2019 community edition to get MS Test libraries
ADD https://aka.ms/vs/16/release/vs_community.exe vs_community.exe
RUN (START /WAIT vs_community.exe --quiet --wait --norestart --nocache \
--add Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites \
|| IF "%ERRORLEVEL%"=="3010" EXIT 0)
RUN DEL vs_community.exe

# Install Microsoft Build Tools 2019
ADD https://aka.ms/vs/16/release/vs_buildtools.exe vs_buildtools.exe
RUN (START /WAIT vs_buildtools.exe --quiet --wait --norestart --nocache \
--installPath "C:\BuildTools" \
# https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019
--add Microsoft.Component.MSBuild \
#--add Microsoft.Net.Component.4.8.SDK \
--add Microsoft.VisualStudio.Component.NuGet.BuildTools \
--add Microsoft.VisualStudio.Component.Roslyn.Compiler \
--add Microsoft.Net.ComponentGroup.TargetingPacks.Common \
--add Microsoft.Net.Component.4.6.1.TargetingPack \
--add Microsoft.Net.Component.4.6.2.TargetingPack \
--add Microsoft.VisualStudio.Component.WebDeploy \
#--add Microsoft.VisualStudio.Component.AspNet45 \
--add Microsoft.Component.MSBuild \
--add Microsoft.VisualStudio.Component.Roslyn.LanguageServices \
--add Microsoft.VisualStudio.Component.CoreBuildTools \
#--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
#--add Microsoft.VisualStudio.Component.Windows10SDK.18362 \
--add Microsoft.VisualStudio.Web.BuildTools.ComponentGroup \
#--add Microsoft.VisualStudio.Wcf.BuildTools.ComponentGroup \
#--add Microsoft.VisualStudio.Component.TestTools.BuildTools \
|| IF "%ERRORLEVEL%"=="3010" EXIT 0)
RUN DEL vs_buildtools.exe

# Include path to VsDevCmd because AWS CodeBuild ignores ENTRYPOINT
# https://github.com/aws/aws-codebuild-docker-images/issues/254
RUN SETX PATH "%PATH%;C:\BuildTools\Common7\Tools"

#RUN powershell -c Install-WindowsFeature NET-Framework-45-ASPNET
#RUN powershell -c Install-WindowsFeature Web-Asp-Net45

# Include AWS CLI
RUN START /WAIT msiexec.exe /a https://awscli.amazonaws.com/AWSCLIV2.msi /quiet /q /norestart /l!*vx "%temp%\aws.log" TARGETDIR=C:\awscli
RUN SETX PATH "%PATH%;C:\awscli\Amazon\AWSCLIV2"

# Install python
# ADD https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe python.exe
# RUN python.exe /quiet InstallAllUsers=1 Include_debug=1 Include_symbols=1
#
# ADD https://www.python.org/ftp/python/3.8.9/python-3.8.9-amd64.exe python.exe
# RUN python.exe /quiet InstallAllUsers=1 Include_debug=1 Include_symbols=1
#
# ADD https://www.python.org/ftp/python/3.9.9/python-3.9.9-amd64.exe python.exe
# RUN python.exe /quiet InstallAllUsers=1 Include_debug=1 Include_symbols=1
# RUN DEL python.exe
#
# ENV PYTHONBREAKPOINT 0

# Start Visual Studio Developer Command Prompt
ENTRYPOINT ["VsDevCmd.bat", "-arch=amd64", "&&"]
CMD ["cmd.exe"]
```

**Comment by theouteredge** [comment]
Are there any plans on fixing this issue to at least increase the default disk size? And are then any plans to support Server 2022 and "full" server 2022 by supporting server:ltsc2022?

**Comment by David-M-Bui** [comment]
I am also most recently facing this issue, have there been any updates?

**Comment by goyalpurvi** [comment]
The extensible ephemeral storage is only supported for Linux containers on Fargate. Please note that Windows support for the feature is tracked here: https://github.com/aws/containers-roadmap/issues/1598

**Comment by goyalpurvi** [comment]
Apologies for the incorrect closure of this issue. This is still work in progress.

**Comment by goyalpurvi** [comment]
> I am also most recently facing this issue, have there been any updates? It is unclear to me whether or not this is possible as there appears to be a contradiction in AWS Documentation...
> 
> Here it says that the default Ephemeral Storage cannot be configured in Fargate 1.0.0 for Windows:
> 
> * https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html
> 
> But here it says that this can in fact be done, using the ephemeralStorage object:
> 
> * https://docs.aws.amazon.com/AmazonECS/latest/userguide/bind-mounts.html

The extended ephemeral storage capability on Fargate only supports Linux right now. The Windows support is work in progress. Please monitor this github issue for updates!

**Comment by goyalpurvi** [comment]
Hi all! This feature just launched for Windows on Fargate! Please read the below for more details, and let us know if you have more requests for the service team!

Launch announcement: https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-ecs-aws-fargate-extensible-ephemeral-storage-windows-tasks/
Documentation: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html

Thanks!

**Comment by johan-smits** [comment]
Loved the update but I still get the disk error with the `1.0.0` version in Fargate:

`CannotPullContainerError: ref pull has been retried 1 time(s): failed to extract layer sha256:bdf205c908f7198cbe1c909730f9c93ea125565550334cc82ee961ece7e14fd5: write \\?\D:\ProgramData\containerd\temp\hcs481201980\Files\Windows\SysWOW64\oleaut32.dll: There is not enough space on the disk.: unknown`

```yaml
    Task:
      Type: AWS::ECS::TaskDefinition
      Condition: CreateResources
      Properties:
        NetworkMode: awsvpc
        RequiresCompatibilities:
          - FARGATE
        Cpu: 1024
        Memory: 2GB
        EphemeralStorage:
          SizeInGiB: 40
        ExecutionRoleArn: !Ref ExecutionRole
        TaskRoleArn: !Ref TaskRole
        ContainerDefinitions:
          - Name: ${self:service}
            Image: ${self:worker.${opt:stage}.image}
            EntryPoint: []
            Command: []
            Interactive: true
            PseudoTerminal: true
            StartTimeout: 3600
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-region: !Ref AWS::Region
                awslogs-group: !Ref LogGroup
                awslogs-stream-prefix: ${self:service}
        Family: ${self:service}
        RuntimePlatform:
          CpuArchitecture: X86_64
          OperatingSystemFamily: WINDOWS_SERVER_2019_CORE
        Tags: []
```

This disk size was sufficient for the EC2 machine. The image is just above 20Gb. Did I miss something?

**Comment by rashidaga** [comment]
Thank you for raising this issue @johan-smits. We are investigating this now.

**Comment by croddin** [comment]
I am also still having this issue 

`CannotPullContainerError: ref pull has been retried 1 time(s): failed to extract layer sha256:d9d9f6074eef8b71a5b3ed6e3bd609cc233daf3878d0c77c7b4b2b3ec8aa9c56: hcsshim::ImportLayer failed in Win32: There is not enough space on the disk. (0x70): unknown`

**Comment by goyalpurvi** [comment]
@johan-smits and @croddin - Thanks for reporting the issue. We were able to reproduce and identify the issue on our end, and are working on the fix. Please stay tuned for updates here.

**Comment by johan-smits** [comment]
@goyalpurvi is there a solution available or is this still broken?

**Comment by goyalpurvi** [comment]
hi @johan-smits  We've been rolling out the fix for the issue for the last few days, and are expecting a completion in all regions by end of day today! If you'd like to try this out in IAD/PDX - the fix is already available there. Please let us know if you run into any issues.
