### ISSUE TITLE
[EKS] [request]: Set IRSA pod identity webhook to use regional STS by default

### ISSUE THREAD

**Issue by mmerickel** [aws/containers-roadmap#1599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

EKS clusters should default to AWS_STS_REGIONAL_ENDPOINTS=regional instead of legacy for pods using IRSA. It is possible to define this via `--sts-regional-endpoint=true` on the pod-identity-webhook daemon, however this deployment is not exposed for configuration.

Please set this value by default and/or provide a new EKS addon to support configuring this value.

This issue caused outages with pods using IRSA in us-east-2 during the downtime in us-east-1 which is an unacceptable default.

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Isolate EKS deployments using IRSA to their regional endpoints instead of relying on the "global" (legacy) STS endpoint when running workloads an AWS-hosted resource tied to a specific region.

**Are you currently working around this issue?**

Manually defining AWS_STS_REGIONAL_ENDPOINTS=regional environment variable in each pod config.

**Additional context**

The AWS CLI v2 switched the default to "regional" already. This indicates they felt changing a default was important enough for the community to do it already.

The docs for the webhook state that "regional" is what you want almost always - so why is it left at legacy?

- https://github.com/aws/amazon-eks-pod-identity-webhook/issues/130
- https://github.com/boto/botocore/issues/2577

**Comment by georgejohnis** [comment]
You can annotate a service account with`sts-regional-endpoints=true` to make use of the AWS Security Token Service's regional endpoint on the newer EKS platform versions. Please find the annotation instruction and platform version requirements in EKS doc [here](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html).

We are evaluating making the regional STS endpoint as the default in a future EKS version release.

**Comment by mmerickel** [comment]
@mikestef9 is there more information somewhere on what “Just Shipped” means for this issue?

**Comment by mikestef9** [comment]
Yes, the documentation link that @georgejohnis mentioned above has instructions

https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

**Comment by mikestef9** [comment]
Actually, I'll re-open the issue, as the ask is to change default.

**Comment by bryantbiggs** [comment]
> Update: We are going to change the default to regional STS endpoint for all clusters, without a need to opt in with annotations on service accounts. This will be available for new clusters soon, and will be rolling out for existing clusters over next several weeks.

would the STS principal endpoint address for EKS be receiving a similar update or no? Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1904

**Comment by sidewinder12s** [comment]
@mikestef9 Did this finish rolling out/would the way to check if you've got the new behavior be to check the pod env vars for the AWS_STS_REGIONAL_ENDPOINTS env var?

**Comment by georgejohnis** [comment]
All newly launched pods on EKS clusters running below platform versions or later will use regional STS endpoint by default. EKS documentation has been updated to reflect this [[here](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html)]. 

EKS v1.18 eks.10
EKS v1.19 eks.8
EKS v1.20 eks.4
EKS v1.21 eks.5

**Comment by georgejohnis** [comment]
~~All newly launched pods on EKS clusters running below platform versions or later will use regional STS endpoint by default. EKS documentation has been updated to reflect this [[link](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html)].
EKS v1.18 eks.10
EKS v1.19 eks.8
EKS v1.20 eks.4
EKS v1.21 eks.5 ~~

We have decided to roll this change out only starting from EKS version 1.22 clusters.

**Comment by mikestef9** [comment]
Closing as EKS 1.22 is now released
