### ISSUE TITLE
[EKS] [Feature Request]: m6i and m6a instance availability to Amazon EC2 supported instances and branch network interfaces.

### ISSUE THREAD

**Issue by baneramu** [aws/containers-roadmap#1608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Requesting to add M6i instances and M6a Instances in Amazon EC2 supported instances and branch network interfaces.
https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#supported-instance-types

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This will allow to use security group for pods in  newer generation instances also Would like to take advantage of the compute-price performance of M6i and M6a and this will make nodes more effectively and save money.

**Are you currently working around this issue?**
 able to start the nodes with the new generation, noticed that the nodes were labeled with vpc.amazonaws.com/has-trunk-attached=false which will note make it possible to use branch interfaces as we use security group for pods

**Comment by caleb15** [comment]
looks like this was done by https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/95?

**Comment by mikestef9** [comment]
Moved to coming soon. PR is merged https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/111. We need to cut a release, then roll out new version of vpc resource controller to all clusters. Will update this issue once that completes.

**Comment by ClareCat** [comment]
@mikestef9 Is there a timeline for when this will be rolled out?

**Comment by mikestef9** [comment]
This is now supported for new clusters. Existing clusters will be supported over the next several weeks.

**Comment by sjastis** [comment]
Closing this as its supported starting v1.3.0
