### ISSUE TITLE
[EKS] [request]: Managed Node Groups IAM Policy flexibility

### ISSUE THREAD

**Issue by Vlaaaaaaad** [aws/containers-roadmap#1610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to create EKS Managed Node Groups without hardcoding specific IAM Policies to the IAM Role.

**Which service(s) is this request for?**
EKS Managed Node Groups

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I tried creating a Managed Node Group using an IAM Role that I defined myself, but I got the following error:
```
Error: error creating EKS Node Group (...): InvalidParameterException: 
  The provided role doesn't have the Amazon EKS Managed Policies associated with it. 
  Please ensure the following policies 
    arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, 
    arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  are attached
```

The IAM Role that I provided has the same permissions that are in the managed policies, but a bit tweaked (ECR image pulling is only allowed for certain ECR Repositories and only through VPC Endpoints).

Is there a specific reason those exact policies **have to be** attached to the IAM Role?

**Are you currently working around this issue?**
I will reluctantly attach the managed policies to the IAM Role.

**Additional context**
The API call that tried to create the Managed Node Group and failed had a `RequestID` of `f1c2ff2c-fef4-43be-be49-57040b849e00`.

This was also an issue/surprise in https://github.com/weaveworks/eksctl/issues/1576.

**Comment by ssarbadh** [comment]
+1
