### ISSUE TITLE
[ECS] [request]: Fargate disk space metrics

### ISSUE THREAD

**Issue by hampld** [aws/containers-roadmap#1613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
So far we have CPU and RAM metrics for ECS Services. It would be great to have the same for disk usage (total/free/free_percent).

**Which service(s) is this request for?**
Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Disk space fills up due to various problems (lazy devs not cleaning up tmp files, logs, ...), there is no convenient way of monitoring disk space. I'd like to be able to set up a cloudwatch alarm per service on high disk space usage. 

**Are you currently working around this issue?**
I have implemented a sidecar container with the cloudwatch agent, but there is no way to easily monitor and alert on high disk space usage, as tasks frequently scale up and down and there is no way to get the task ID into the `append_dimensions` hash.

**Additional context**
Anything else we should know?

**Comment by vaibhavkhunger** [comment]
Closing this issue.

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-fargate-monitoring-storage-utilization/
