### ISSUE TITLE
[EKS]: ECR Pull Through Cache not working as expected for EKS use-case. 

### ISSUE THREAD

**Issue by nsb413** [aws/containers-roadmap#1614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
This request was submitted on behalf of a customer.

**Which service(s) is this request for?**
ECR, EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Pods are failing to start due to ImagePullBackOff issues, when using Pull through cache ECR [feature](https://aws.amazon.com/blogs/aws/announcing-pull-through-cache-repositories-for-amazon-elastic-container-registry/). 

```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  11m                 default-scheduler  Successfully assigned default/eks-ecr-cache-test-67ff48c7cb-tn8ft to ip-x-xx
  Normal   BackOff    10m (x6 over 11m)   kubelet            Back-off pulling image "<account>.dkr.ecr.us-west-1.amazonaws.com/quay-4/prometheus/prometheus"
  Normal   Pulling    10m (x4 over 11m)   kubelet            Pulling image "<account>.dkr.ecr.us-west-1.amazonaws.com/quay-4/prometheus/prometheus"
  Warning  Failed     10m (x4 over 11m)   kubelet            Failed to pull image "<account>.dkr.ecr.us-west-1.amazonaws.com/quay-4/prometheus/prometheus": rpc error: code = Unknown desc = Error response from daemon: repository <>.dkr.ecr.us-west-1.amazonaws.com/quay-4/prometheus/prometheus not found: name unknown: The repository with name 'quay-4/prometheus/prometheus' does not exist in the registry with id '<account>'
  Warning  Failed     10m (x4 over 11m)   kubelet            Error: ErrImagePull
  Warning  Failed     82s (x44 over 11m)  kubelet            Error: ImagePullBackOff
```

**Are you currently working around this issue?**
`docker pull <image>` manually is triggering the cache repository creation and new pods are starting without issues. 

**Additional context**
Did not observe this issue in ECS/EC2. When Tasks are launched, cache repository is getting created and Tasks are Running without issues.

**Comment by jlbutler** [comment]
Hi @nsb413 sorry for the troubles. Have you set up registry permission for the node(s) in your EKS cluster?

In case you've not, you'll need to create a registry permission statement for your EKS cluster's node instance role. See "Using registry permissions" (step 5c) in the ECR docs:

 https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html

Hope that helps! If not, let us know. Thanks!

**Comment by arunsollet** [comment]
@nsb413 - Please do share an update if the registry permissions resolved your issue? Thanks

**Comment by JoseAlvarezSonos** [comment]
I was facing the same issue and adding the registry permission solved it 👍 . The only issue I faced was that I created the registry permission via Terraform and I had a small typo with the resource (I forgot to add :repository) that took me some hours to realize. So maybe you can generate the policy via the UI, and then add it to your IaC if that's your case.

**Comment by adis-io** [comment]
In our case I needed to give `ecr:BatchImportUpstreamImage` for my Jenkins IRSA to make it work
