### ISSUE TITLE
[EKS]: Kubernetes v1.18 End of Support (March 31st, 2022)

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#1630]
Kubernetes version 1.18 on Amazon EKS will no longer be supported on **March 31st, 2022**. On this day, you will no longer be able to create new 1.18 clusters. Existing 1.18 clusters will be automatically updated by Amazon EKS to the latest available platform version of Kubernetes version 1.19 through a gradual deployment process after the end of support date.

We recommend you upgrade existing 1.18 clusters and worker nodes to at least 1.19 as soon as practical.

Learn more:

- [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by stevehipwell** [comment]
@mikestef9 is there any guidance on when the automated upgrades will happen if any clusters aren't upgraded before this date?

**Comment by mikestef9** [comment]
We are unable to provide specific timeframes. From [docs](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation)

> Q: When exactly will my control plane be automatically updated after the end of support date?

> A: Amazon EKS can't provide specific timeframes. Automatic updates can happen at any time after the end of support date. We recommend that you take proactive action and update your control plane without relying on the Amazon EKS automatic update process.

**Comment by beyondbill** [comment]
@mikestef9 Is the target deprecation date still March 31 considering the delay of 1.22 release?

**Comment by beyondbill** [comment]
> Existing 1.18 clusters will be automatically updated by Amazon EKS to the latest available platform version of Kubernetes version 1.19 through a gradual deployment process after the end of support date.

@mikestef9 Also, how long is the grace period after the deprecation date until EKS automatically upgrades existing 1.18 clusters?
