### ISSUE TITLE
[ECR] [request]: Support Ubuntu 21.04

### ISSUE THREAD

**Issue by CodeFreezr** [aws/containers-roadmap#1632]
Tell us about your request
What do you want us to build?

Add support for scanning ubuntu 21.04 based images for security vulnerabilities.

Which service(s) is this request for?
ECR

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Are you currently working around this issue?
None

Additional context
Anything else we should know?
Tried to scan yesterday and it told me ubuntu 21.04 was not supported.,

Attachments
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jritchey** [comment]
I think Ubuntu 21.04 is consider end of life as of January 20, 2022. From AWS' documentation: " Once a distribution loses support from its vendor, Amazon ECR may no longer support scanning it for vulnerabilities. Amazon ECR does not support scanning images built from the Docker scratch image."  [(https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.html)]

**Comment by CodeFreezr** [comment]
Ok, so we have to find another Scan-Solution. Thanx.

**Comment by bradg-aws** [comment]
Ubuntu 21.04 is supported in both ECR basic and enhanced scanning.
As mentioned, however, 21.04 is end of life. Importantly, the end of life operating systems are no longer updated with patches and, in many cases, new security advisories are no longer released for them. In this case, Ubuntu security notices and feeds are no longer updated for 21.04: https://ubuntu.com/security/notices

Any findings that ECR does generate for a discontinued/EOL OS should be used for informational purposes only.

Please see https://docs.aws.amazon.com/inspector/latest/user/supported.html#formerly-supported-os
