### ISSUE TITLE
[ECS] [request]: ECS describe-tasks API should return imageDigest for all supported container registries

### ISSUE THREAD

**Issue by bhorev** [aws/containers-roadmap#1640]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The following limitation currently exists with respect to **imageDigest** field in ECS describe tasks API:
**_The imageDigest is only returned if the container is using an image hosted in Amazon ECR, otherwise it is omitted._**
(documented here: https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-tasks.html)

To be more accurate: It seems imageDigest is returned only when working with private ECR. In case of working with public ECR or other container registry, imageDigest will not be populated with a SHA value.

**Which service(s) is this request for?**
ECS (some relation to ECR)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This issue is scoped to anyone using registries other than private ECR.
Not having imageDigest means one cannot check which image is in fact running for an ECS task.
First, this has the following security/governance drawbacks:
- An admin looking to govern the use of specific images on ECS cannot monitor for compliance using the describe API.
- An admin looking to identify the use of a specific vulnerable image cannot run the describe API to obtain this information.

Second, 3rd party services looking to provide image assurance services, cannot know which image to scan for vulnerabilities.

**Are you currently working around this issue?**
No known workaround.

**Additional context**
n/a

**Attachments**
n/a

Thank you!

**Comment by ollypom** [comment]
Hey @bhorev , following the changes in the [v1.70](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.70.0) version of the ECS Agent there should now be an `imageDigest` for all container repositories. I've just tested this and confirmed it was the case for my container image stored on Docker Hub. I tested on EC2 ([AMI](https://github.com/aws/amazon-ecs-ami/releases): 20240610, Agent: 1.83.0) and on Fargate PV 1.4. So I'll close this issue.

If I've misunderstood the ask, and the issue still exists, let me know and I'll happily reopen it. 😄
