### ISSUE TITLE
[ECR] [request]: Support scanning of Ubuntu 21.10 based images

### ISSUE THREAD

**Issue by bchew** [aws/containers-roadmap#1647]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for scanning Ubuntu 21.10 based images for security vulnerabilities

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Continue to have the ability to scan images pushed to ECR after upgrading the base image to Ubuntu 21.10. https://github.com/quay/claircore/pull/491 to support this was merged in in October 2021.

**Are you currently working around this issue?**
No

**Additional context**
Pushed an image based on Ubuntu 21.10 and received `UnsupportedImageError` from ECR scan on push

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by singron** [comment]
I noticed that the docs purport to support 21.10 for ECR scanning, but I just confirmed that you will still get a UnsupportedImageError: https://docs.aws.amazon.com/inspector/latest/user/supported.html

**Comment by bchew** [comment]
No longer required as superseded by https://github.com/aws/containers-roadmap/issues/1728
