### ISSUE TITLE
[Batch] [Fargate] [request]: Add ARM64 architecture support for Batch jobs running on AWS Fargate

### ISSUE THREAD

**Issue by tlinhart** [aws/containers-roadmap#1652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for ARM64 architecture when running Batch jobs on AWS Fargate.

**Which service(s) is this request for?**
Batch, Fargate, ECS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
There is already [ARM64 support for ECS tasks running on AWS Fargate](https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/) that we use extensively. The runtime platform can be specified in the [task definition parameters](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html). However, there is currently no option for specifying the runtime platform for Batch jobs running on AWS Fargate in the [job definition parameters](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html).

We use Batch jobs for a substantial portion of our workload and being able to use ARM64 architecture would lower the costs significantly. 

**Are you currently working around this issue?**
No, we use x86-64 architecture for the workload.

**Comment by dhstockwell** [comment]
I second this request. We have a large number of ECS clusters/Fargate Tasks and batch jobs and have recently been migrating over to ARM64 to cut down on costs. Without this support, we have to dual-build into an ECR manifest which introduces environment differences.

**Comment by tlinhart** [comment]
Any updates on this? Is this considered, worked on or ignored?

**Comment by jamesev15** [comment]
Is this issue still opened?

**Comment by sacundim** [comment]
Just the other day (Jul 14, 2023) AWS announced that [Batch on AWS Fargate now supports Linux ARM64](https://aws.amazon.com/about-aws/whats-new/2023/07/aws-batch-fargate-linux-arm64-windows-x86-containers-cli-sdk/)... but posted no clear instructions at all on how to get it to work.  The announcement has a link to [ECS documentation on running ARM64 workloads](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-arm64.html), but I couldn't guess the config. I'm using Terraform, so there's the added complication that it might require a new version of its AWS provider.

**Comment by jamesespichan** [comment]
Thanks for posting that! I'm going yo try it. I solved the problem using an EC2 and doing the compilation in that EC2 to generate the docker image for x86.

**Comment by aaronabf** [comment]
> Just the other day (Jul 14, 2023) AWS announced that [Batch on AWS Fargate now supports Linux ARM64](https://aws.amazon.com/about-aws/whats-new/2023/07/aws-batch-fargate-linux-arm64-windows-x86-containers-cli-sdk/)... but posted no clear instructions at all on how to get it to work. The announcement has a link to [ECS documentation on running ARM64 workloads](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-arm64.html), but I couldn't guess the config. I'm using Terraform, so there's the added complication that it might require a new version of its AWS provider.

The provider will likely need to be updated to support  `runtime_platform` in the `aws_batch_job_definition`:
```
  runtime_platform {
    operating_system_family = "LINUX"
    cpu_architecture        = "ARM64"
  }
```

**Comment by sacundim** [comment]
> Can confirm that adding this to the job definition worked:

Nice @aaronabf, I was just doing the same:

* https://github.com/sacundim/covid-19-puerto-rico/blob/e552f44d817c8468cd3a4cbdef8c34dc08e9e350/Terraform/WalgreensJob.tf#L35

I couldn't find in the Batch UI any indication that my job ran on ARM64, so I went to [the extra step to put a logging message on my app to confirm so](https://github.com/sacundim/covid-19-puerto-rico/commit/f2ad05458e119931231f7ac847250a5509d3836e). Log output confirms it:

```
2023-07-17 17:41:12,151 MainThread Platform: system=Linux, machine=aarch64, version=#1 SMP Tue Jun 27 21:48:49 UTC 2023
```

**Comment by ollypom** [comment]
AWS Batch Jobs on AWS Fargate now supports Linux arm64 and Windows x86. 

Whats new post: https://aws.amazon.com/about-aws/whats-new/2023/07/aws-batch-fargate-linux-arm64-windows-x86-containers-cli-sdk/
