### ISSUE TITLE
[EKS][Issue]: EKS Managed EBS CSI Driver fails to deploy on ARM(AL2_ARM_64) node groups

### ISSUE THREAD

**Issue by vara-bonthu** [aws/containers-roadmap#1655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I have tried to deploy a **managed add-on EBS CSI Driver** (`1.4.0-eksbuild.preview`) to an existing EKS Cluster with one managed node group which uses ARM instance (`t4g.medium`). EBS CSI Driver fails to deploy on _t4g.medium_ instances.

But the same works for Linux instances with AL2_x86_64

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
EBS CSI Driver (`1.4.0-eksbuild.preview`) managed add-on fails to deploy on ARM instances (AL2_ARM_64)

**Are you currently working around this issue?**
There is no workaround for this problem 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by stevehipwell** [comment]
@vara-bonthu I'm not sure if it's related but the EBS CSI driver doesn't currently detect nitro instances which aren't 5 series correctly.

Issue: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1139.
PR: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1075

**Comment by gtxu** [comment]
The deployment failed to pull sidecar images because the images for ARM64 is missing. Reference here: [kubernetes-sigs/aws-ebs-csi-driver/issues/1136#](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1136)

**Comment by gtxu** [comment]
> @vara-bonthu I'm not sure if it's related but the EBS CSI driver doesn't currently detect nitro instances which aren't 5 series correctly.
> 
> Issue: [kubernetes-sigs/aws-ebs-csi-driver#1139](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1139). PR: [kubernetes-sigs/aws-ebs-csi-driver#1075](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1075)

This issue is for maximum volumes that attach to one node. It won't matter until you attach more that limited volumes(25 on average for nitro instances) to one node, thank you for attempting to figure it outwith us!

**Comment by MichaelHauss** [comment]
This issue has been addressed with the GA of EBS CSI driver support in EKS add-ons. Checkout the announcement announcement https://aws.amazon.com/about-aws/whats-new/2022/03/eks-add-ons-ebs-csi-driver-available/
