### ISSUE TITLE
ECS fargate is not able to pull image from Jfrog artifactory

### ISSUE THREAD

**Issue by Ram2322** [aws/containers-roadmap#1658]
Hi Team,
We are using ecs fargate 1.4.0 version for my dev environmnet. I am using jfrog artifactory to docker images. My ecs fargate is not able to pul image from jfrog. We are getting following error. Please assist me on this issue.
CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "rrr-docker-nonprod-virtual.us.artifactory.r1.rrr.com/rrr-backend-service/aws2o:20220128.2": failed to authorize: failed to fetch anonymous token.
Thanks

**Comment by osterik** [comment]
@Ram2322, I'm not 100% sure, but it looks like you just need to add JFrog artifactory credentials. 
You can find more details here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html

**Comment by ollypom** [comment]
Closing this issue as I believe specifying [Registry Credentials](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html) (as @osterik mentioned) will solve your issue. If I've misunderstood, please let me know and I can reopen the issue.
