### ISSUE TITLE
[ECR Public] [bugfix]: ECR Gallery Public - number of official docker images out-of-sync

### ISSUE THREAD

**Issue by tbugfinder** [aws/containers-roadmap#1660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Amazon ECR Public Gallery is supposed to provide all official docker hub images.
As-of-today AWS ECR Public Gallery lists 139 images compared to 173 on docker hub. So there a several images missing. I kindly ask to get this in sync as "promised".

**Which service(s) is this request for?**
ECR Public Gallery

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Use AWS ECR Gallery as advertised.

**Are you currently working around this issue?**
Use dockerhub or quay.io instead of ECR Public Gallery.

**Additional context**
n/a

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by davidkhala** [comment]
Any reason for these two provider exactly match in all time? Of course there is a usecase to use Public Gallery as a full replacement of docker hub. But since they are in-design different, will it consume more effort to maintain their similarity?

**Comment by tbugfinder** [comment]
It's only about
Docker Official Images, not all images stored within dockerhub.


https://www.docker.com/blog/news-from-aws-reinvent-docker-official-images-on-amazon-ecr-public/

**Comment by rafavallina** [comment]
Hi @tbugfinder thanks for pointing this out!

Is there a particular repository or image that you are trying to pull from ECR Public and can't find? There are indeed Official Docker repositories in Docker Hub that are not in ECR Public, but they are all deprecated, empty or simply host images created during DockerCon, so we don't expect or recommend that customers pull from those repositories - indeed, many have not been updated in several years, which means that there are not updates to push either.

**Comment by rafavallina** [comment]
I'm going to close this for now. Please feel free to reopen if you find a current Docker Official image that is missing rom ECR Public! We will be glad to work with our friends at Docker to update it

**Comment by cleaton** [comment]
Clickhouse is not available https://hub.docker.com/_/clickhouse
