### ISSUE TITLE
[EKS] [request]: Inspecting containers for CVEs

### ISSUE THREAD

**Issue by manpreet-singh-sf** [aws/containers-roadmap#167]
**Tell us about your request**
There is a service for EC2 to inspect for the CVEs, i.e. AWS Inspector. Similar service is required for EKS containers. In the absence of it, time consuming integration with systems like Clair is required. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently other solutions like integrating Clair in the CI/CD pipelines needs to be used to do vulnerability analysis on the containers. It is possible to do, but it requires constantly updating Clair database, manual process to manage the results of scans. AWS Inspector can be enhanced to scan components as well. And unifying the CVE scans on EC2 as well as containers.

**Are you currently working around this issue?**
By using Clair and CI/CD pipeline.

**Comment by nathanpeck** [comment]
This should be solved by ECR image scanning, another item on the containers roadmap: https://github.com/aws/containers-roadmap/issues/17

**Comment by manpreet-singh-sf** [comment]
Closing this one as it will be solved by https://github.com/aws/containers-roadmap/issues/17
