### ISSUE TITLE
[EKS] [request]: Remove emptyDir from coredns deployment

### ISSUE THREAD

**Issue by jonathan-conder-sm** [aws/containers-roadmap#1675]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
My issue is the same as https://github.com/kubernetes/kops/issues/8309: when running `cluster-autoscaler` on EKS, it refuses to scale down a node running a `coredns` pod, because it uses an `emptyDir` volume. Apparently the volume was a workaround for an old issue which doesn't affect newer versions of `coredns`.

**Which service(s) is this request for?**
EKS (specifically the `coredns` addon).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I was trying to update the pods in a deployment. The autoscaler spun up a new node for the new pods (as they won't fit on a node running an old pod). After that, the old pods stopped. At that point I expected the old nodes to spin down. But the ones running `coredns` stuck around, even though the new nodes could have easily accommodated a few `coredns` pods.

**Are you currently working around this issue?**
Running `cluster-autoscaler` with `skip-nodes-with-local-storage=false`.

**Additional context**
N/A

**Attachments**
N/A

**Comment by lambchr** [comment]
Just adding another work around, I added this annotation to the Deployment `cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: "tmp"`. However long term that is an anti-pattern as it isn't applied via IaC and could easily be overwritten.

**Comment by sjastis** [comment]
emptyDir has been removed starting with CoreDNS release v1.9.3-eksbuild.10 and v1.10.1-eksbuild.6
