### ISSUE TITLE
[EKS] [request]: Managed node group support for bottlerocket with NVIDIA GPU

### ISSUE THREAD

**Issue by ozahavi** [aws/containers-roadmap#1682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Managed node group support for bottlerocket with NVIDIA GPU

**Which service(s) is this request for?**
EKS

**Comment by awoimbee** [comment]
This has always been possible via a launch template. It seems possible even without a launch template by using the AMI type `Bottlerocket NVIDIA (BOTTLEROCKET_x86_64_NVIDIA)`.

**Comment by mikestef9** [comment]
Yes, closing as this has been launched
