### ISSUE TITLE
[ECR] [Tags]: immutable image tags

### ISSUE THREAD

**Issue by jtoberon** [aws/containers-roadmap#169]
After an image tag is pushed to a repository, prevent a user from pushing an update that points the tag to a different image. This feature can be used to ensure that an image tag such as "2.1.1" refers to the same content over time. Such tags can be easier to use than the longer image digest.

An example of the pros and cons of using mutable image tags can be found [here](https://github.com/nodejs/docker-node/issues/649).

**Comment by rpnguyen** [comment]
🎉 https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecr-now-supports-immutable-image-tags/

**Comment by yrsurya** [comment]
Hello all , we create two tags for the image where one is latest and another is Jenkins build number but with recently released tag immutability where we enabled for repo seems to be latest tag is not being tagged to the recent image as it not able to overwrite . Any one faced similar situation

**Comment by FernandoMiguel** [comment]
@yrsurya that's the all point if immutable tags.
Your latest tag is just like any other tag (it has no special meaning) and now refers to the 1st image it tagged

**Comment by yrsurya** [comment]
I was in a impression that image which pushed recently will be getting latest tag by default. Is there any way we can get that(latest) by default after enabling immutable option on ECR as we use latest tagged base images for the application to built on top of

FROM xxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/corretto11:latest
VOLUME ["/tmp"]
ADD ${project.name}-${version}.jar /
EXPOSE 8080
ENTRYPOINT [xxx]

**Comment by therealppa** [comment]
@yrsurya You could use the cli to untag _latest_ before tagging your new image.

**Comment by Roberdvs** [comment]
Nexus now allows redeploying the 'latest' tag even if tag immutability is enabled, which is very convenient.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/15369573/75542476-300f8c00-5a20-11ea-9665-55a98b836b84.png">

Having the same on ECR would be nice.

**Comment by mike-stewart** [comment]
We have the same issue with the `latest` tag. I've opened a new issue in https://github.com/aws/containers-roadmap/issues/878.

**Comment by pablote** [comment]
The link @therealppa suggests is not working for me. Is it possible that it refers to some other type of tags, like aws resource tags, but not really docker container image tags?

**Comment by therealppa** [comment]
@pablote Looking at the description, you're probably right. According to https://stackoverflow.com/questions/56299191/remove-tag-from-image the correct command should be `aws ecr batch-delete-image --repository-name <REPO NAME> --image-ids imageTag=<TAG NAME>`
