### ISSUE TITLE
ECR Image vulnerability scanning

### ISSUE THREAD

**Issue by yinshiua** [aws/containers-roadmap#17]
Static scanning for software vulnerabilities in container images.

**Comment by connorthomasmccabe** [comment]
![Alt Text](https://i.giphy.com/media/Is1O1TWV0LEJi/giphy.webp)

**Comment by MarcusNoble** [comment]
Would this be able to alert us using something like CloudWatch or by sending alerts to an SNS topic or similar?

**Comment by jtoberon** [comment]
> Will this be an integration to services like Aqua and TwistLock? Or will you implement the scanning yourself?

I can't share the details of how we implement scanning, but as part of this project, we do plan to include in our public APIs the endpoint that we use to publish new scan results.

> Would this be able to alert us using something like CloudWatch or by sending alerts to an SNS topic or similar?

Scanning is an asynchronous process, and we will create an event stream so that you can work with that process programatically.

**Comment by manpreet-singh-sf** [comment]
In addition to scanning at creation of image revision, it will help if images are rescaned at regular intervals to take care of new vulnerabilities discovered.

**Comment by rikkuness** [comment]
In theory the images shouldn't need rescanning, the contents won't change so as long as there's a manifest of packages and versions found, comparing that against what vulns exist for given versions should be possible just from the manifest of image contents.

**Comment by mllanes** [comment]
Looking forward to this one...

**Comment by jtoberon** [comment]
> In addition to scanning at creation of image revision, it will help if images are rescanned at regular intervals to take care of new vulnerabilities discovered.

You're right: when there's a new version of the CVE "database" images need to be rescanned. This means that new vulnerabilities can be found in old images.

A few new considerations arise here that we want users to be aware of. First, programmers might only care about new scan results for a few images (the image running in production, the image from the HEAD commit, etc.), so you may want a way to filter out some of the information generated by rescanning. Second, you may find a big problem in an image you're still running in production, and you don't necessarily want to blacklist an image with new vulnerabilities immediately. A standard way to think about this problem is in terms of a schedule: you have X days to fix a low severity finding, Y days to fix a medium severity finding, etc.

**Comment by ricosega** [comment]
I think is a needed feature, as it is being implemented by many other registries.

**Comment by Arsen-Uulu** [comment]
hopefully this will be done soon

**Comment by dmarkey** [comment]
Any movement? :cake:

**Comment by Arsen-Uulu** [comment]
Still nothing?

**Comment by jtoberon** [comment]
We are still working on this as our top priority. Some customers are testing the feature as part of a private beta, but in general we don’t share specific GA dates.

**Comment by dmarkey** [comment]
If you need any more testers please reach out.

**Comment by Arsen-Uulu** [comment]
We are the customers. Can we reach out to AWS support for beta? @jtoberon

**Comment by tdmalone** [comment]
Hi guys, AWS don't share release dates; don't prioritise based on additional comments here; and will ask if they need more people for a beta (naturally a private beta is only shared privately with certain customers). Every time you post a comment asking when this is going to be done, 1) everyone subscribed to this issue is notified, and 2) you probably slow down AWS staff a bit because _they're_ also subscribed. So, if you want this feature, please just add a thumbs up reaction to the first message in this thread and rest easy knowing that since this is in [We're Working On It](https://github.com/aws/containers-roadmap/projects/1#card-15501695), well, AWS is working on it :)

**Comment by ChrisRut** [comment]
Prediction: This will be announced during the [re:Inforce keynote](https://pages.awscloud.com/reInforceLivestream_registration.html) next week

**Comment by inductor** [comment]
Wooo can't wait!

GCR just released the same feature as beta this week and I really hope it comes on ECR as well!

**Comment by rikkuness** [comment]
> A few new considerations arise here that we want users to be aware of. First, programmers might only care about new scan results for a few images (the image running in production, the image from the HEAD commit, etc.), so you may want a way to filter out some of the information generated by rescanning. Second, you may find a big problem in an image you're still running in production, and you don't necessarily want to blacklist an image with new vulnerabilities immediately. A standard way to think about this problem is in terms of a schedule: you have X days to fix a low severity finding, Y days to fix a medium severity finding, etc.

CVE databases generally only contain package names and version numbers affected by any given CVE, in a built image those things won't change. Most CVE scanners don't do any magic when scanning for vulnerabilities, they'll simply catalog names and version numbers of software in the image, usually just by checking the package database (rpm/apk/deb etc.) and then compare those version numbers against a CVE database to find any hits. 

If you've a catalog of the contents of your images stored then you don't need to unpack and "scan" the image again, you're just comparing the versions from your catalog of the image contents against fresh CVE data, which can be done in realtime, as soon as new CVE data is available that flags for example a critical vuln in version 0.3 of package "whatever", you'll already have a catalog of which of your images have that package in.

**Comment by operationW** [comment]
With security being "job zero" at AWS i would have liked for this feature to have been available much much sooner. In the interim I'm looking at solutions like https://aws.amazon.com/blogs/publicsector/detect-vulnerabilities-in-the-docker-images-in-your-applications/

**Comment by jcode** [comment]
any updates about this?

**Comment by av82** [comment]
any update on this ?

**Comment by jtoberon** [comment]
I know there's a lot of interest in this issue. Rest assured that we continue to work on it and to address feedback from beta customers. We will move the issue to Coming Soon when we are confident that the feature will ship very soon.

Security tools are a major focus for the team this year. For example, we expect that our customers will use vulnerability scanning, support for [VPC endpoint policies](https://github.com/aws/containers-roadmap/issues/132), and support for [KMS CMKs](https://github.com/aws/containers-roadmap/issues/52) to improve their security posture.

**Comment by gibbsie** [comment]
I'd love to see this feature, along with [KMS CMK](#52 ) support. It would be great if the targetted image vulnerability scanning feature could support multi-account strategies, support AWS SecurityHub and aggregate data to the defined AWS SecurityHub master to permit a single pane of glass for interested stakeholders.

**Comment by nickbabkin** [comment]
Any updates on that? Eagerly waiting

**Comment by garyfeltham** [comment]
Is there an open beta program for this? - I've been after this for 10+months and really need this feature to fall into our compliance program. We've attempted running our own scanning with Claire as an interim but really want this in the ECR

**Comment by mhausenblas** [comment]
@garyfeltham there's no open beta program, however (as hinted at by the "coming soon" category) we're really close to shipping it.

**Comment by okor** [comment]
@mhausenblas Rad! Is it Claire under the hood or something else?

**Comment by stefansedich** [comment]
@mhausenblas can you comment on how soon? I am about to look at solutions for scanning and would be good to know if it is something I can hold out for ECR to support or not.

**Comment by mhausenblas** [comment]
@stefansedich, you know how we are, we don't comment on or commit to a specific date ...  but "coming soon" usually means weeks rather than months ;)

**Comment by jtoberon** [comment]
Thanks for your patience everyone. We are in the final stages of this release.

@okor We'll answer your question in the blog post that accompanies the release. I don't want to spoil the surprise!

@gibbsie We will not publish results to Security Hub in the initial release, but we plan to fast follow with this integration. It would be extremely useful to understand how you want to look at findings in Security Hub. Have you played around with that tool yet? Would you be interested in providing feedback about how we plan to publish findings?

**Comment by inductor** [comment]
I see this feature on the AWS control panel. Hope to see the official announcement!

**Comment by siwyd** [comment]
@inductor Where exactly? You're in a test group perhaps? :)

**Comment by stefansedich** [comment]
I am seeing the ability to scan and turn on "scan on push" in the UI, but nothing in the CLI yet, looks like it might be soon!

**Comment by Zaulao** [comment]
@siwyd In the Repositories list you can see the "Scan on push" option for each repository. When entering a repository, you can select an image and click the "scan" button at the top.

**Comment by dmarkey** [comment]
Wohoo! Next feature request - Github integration :)

**Comment by jtoberon** [comment]
@dmarkey Can you explain what you mean by Github integration?

**Comment by mhausenblas** [comment]
And we're live: https://aws.amazon.com/blogs/containers/amazon-ecr-native-container-image-scanning/

**Comment by whereisaaron** [comment]
Well that is great, thanks for the article and example @mhausenblas!

Now to look a gift-horse in the mouth... the UI is currently, well, non-existent. Not quite the quay.io equivalent implementation 😄  Will there be a console update to ECR console UI down the line? And maybe some CloudWatch events/metrics to work with? Or is this going to remain a DIY service?

Even if we schedule it as a CI trigger, a UI for browsing the results would be welcome!

![image](https://user-images.githubusercontent.com/1109585/67717147-8baf0780-f9a3-11e9-81c3-8ec441dcf35d.png)

**Comment by whereisaaron** [comment]
Digging in there are ECR Console changes. You can enable 'Scan on push' when creating a repo, although I so no UI to enable/diable it on an existing repo?

![image](https://user-images.githubusercontent.com/1109585/67718139-8357cc00-f9a5-11e9-944f-e5b4e2a8f49b.png)

And in a repo there is a 'Scan' button for selected images and a couple of extra columns.

![image](https://user-images.githubusercontent.com/1109585/67718255-c619a400-f9a5-11e9-946a-e20509f8e837.png)

**Comment by rikkuness** [comment]
Does this mean Amazon will now be actively contributing fixes and improvements back to Clair?

**Comment by stefansedich** [comment]
Will there be OOTB support in the future for things like re-scanning? having to cobble together 4 Lambda functions, an API gateway, S3 bucket and Cloudwatch is not ideal.

**Comment by whereisaaron** [comment]
@stefansedich I was thinking for re-scanning it would be nice if ECS and EKS has a facility to trigger re-scanning of images that are actually deployed. I was thinking 'scan on push', plus regular re-scanning of images in use would be more efficient (and less distracting/noisy) than blindly re-scanning every historic image in a repo.

Plus it would probably be simpler than maintaining 4 Lambda functions, an API gateway, S3 bucket and Cloudwatch 😄

**Comment by jtoberon** [comment]
@whereisaaron If you have any specific feedback about the results browser, feel free to open a new issue. It also would be useful to know if Security Hub integration would help. To enable scanning for an existing repository, click the Settings/Gear icon on a repository to get to the preferences page.

@rikkuness Yes. For example, we opened https://github.com/coreos/clair/pull/867 today, we will fix https://github.com/coreos/clair/issues/866, and we would like to fix https://github.com/coreos/clair/issues/762 if nobody else gets to it first. We talked to the Clair maintainers when we started working on this, and we look forward to working with them!

Regarding rescans, it can be hard to know which images to rescan. If clear patterns emerge, we can support them natively. Please open a separate issue.

**Comment by rikkuness** [comment]
@jtoberon that's great, thanks!

**Comment by RyPeck** [comment]
Can we close this issue to comments now that the feature is launched and the issue is closed?
