### ISSUE TITLE
[ECS] [bug]: daemon task should be last to be stopped when instance is draining

### ISSUE THREAD

**Issue by stlava** [aws/containers-roadmap#1700]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
It would seem that there might be a regression because according to https://github.com/aws/containers-roadmap/issues/128#issuecomment-720262219 the daemon tasks should be last to be drained.

I currently have a daemon task which other services depend on. From the guidance of AWS support I've included a placement constrain on the service that depends on the daemon (`memberOf(task:group == service:my-daemon)`) because on occasion the scheduler would place the dependent task before placing the daemon and then not have room on the host to run the daemon.

The issue I'm running into now is that when the instance is draining the daemon is sometimes stopped before the dependent task when the instance is in draining. The placement constraint that ensures the daemon is started before the other tasks isn't respected during draining. I think there might be a regression here because an earlier comment described that this was previously addressed.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The daemon task proxies connections for the dependent task so if the daemon goes away then the dependent task isn't able to talk to the data store. From the application's perspective it can't track that this is not an intermittent failure to talk with the daemon.

**Are you currently working around this issue?**
No work around. Though I've considered increasing the internal shutdown time within the daemon to be a little longer but even then it won't be long enough to encompass the other containers being signaled and stopped.

**Comment by nathanpeck** [comment]
Hi Slava. Are you using service launched tasks or `RunTask` launched tasks? 

Unfortunately [the linked comment](https://github.com/aws/containers-roadmap/issues/128#issuecomment-720262219) only applies to service launched tasks. All service launched tasks will be stopped first, then daemon launched tasks. 

However, there is no ordering guarantee for standalone `RunTask` API launched tasks. This may explain the behavior you are seeing.

**Comment by stlava** [comment]
The dependent tasks described are service launched tasks. I have a parallel AWS support case open where I referenced this issue and provided some logs from one of our ECS instances. I heard back this morning that the issue is being investigated as a bug by the service team.

**Comment by dt-atkinson** [comment]
We have this happening on our ECS container hosts sometimes also.

**Comment by ericdahl** [comment]
We're running into this same issue (reverse issue of #428)

When an ECS Container Instance is in DRAINING mode, we've observed that the DAEMON tasks are one of the first ones to shut down, while the various REPLICA tasks will stick around for longer as they are waiting to spin up replacement tasks, or because of ALB Deregistration Delay.

The result of this is that our key DAEMON tasks for Logging, Metrics, etc are shut down prior to the application tasks, so we lose visibility on the final minutes of the REPLICA tasks. This means those container level docker logs are lost (we use json-file with fluentd daemon) and we lose visibility. For example, we were recently trying to analyze the shutdown behavior of some REPLICAS during draining phase and could not because the logging DAEMON had shut down before the REPLICA.

**Comment by AbhishekNautiyal** [comment]
Happy to share that Amazon ECS rolled out an improvement in Daemon scheduling to ensure that Daemon tasks are the last to stop after all replica tasks shutdown on a DRAINING instance (as documented [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html#:~:text=the%20daemon%20tasks.-,The%20daemon,-service%20scheduler%20doesn%27t). We are also actively working on delivering an ECS-managed instance draining solution as highlighted in https://github.com/aws/containers-roadmap/issues/256.  Let us know if you face any other issues.
