### ISSUE TITLE
[EKS] [bug]: EKS v1.22 is intermittently reporting the incorrect InternalIP address

### ISSUE THREAD

**Issue by stevehipwell** [aws/containers-roadmap#1702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like EKS v1.22 to always report the correct `InternalIP` in the `status.addresses` field rather than occasionally reporting the IP from a secondary ENI when custom networking is enabled.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When running Metrics Server on EKS v1.22 we're seeing errors as reported in [kubernetes-sigs/metrics-server#999](https://github.com/kubernetes-sigs/metrics-server/issues/999). This is because the `InternalIP` isn't being reported consistently, to recreate this issue you can run the following script against a node in a cluster using custom networking.

Bash
```shell
while true; do kubectl get node ip-10-52-12-90.eu-west-1.compute.internal -o json | jq -r '.status.addresses[0].address'; done
```

PowerShell
```shell
do {kubectl get node ip-10-52-12-90.eu-west-1.compute.internal -o json | jq -r '.status.addresses[0].address'} while ($true)
```

**Are you currently working around this issue?**
Not possible

**Additional context**
I'm happy to open this issue in the EKS distro repo if that's the correct place for issues like this?

**Attachments**
n/a

**Comment by archoversight** [comment]
As the original creator of the bug report on the metrics-server bug tracker, I too can confirm the same behavior:

```
% while true; do kubectl get node ip-10-58-123-11.us-gov-west-1.compute.internal -o json | jq -r '.status.addresses[0].address'; done
2600:1f12:c8f:5f1e:0:0:0:1b1b
[30 similar lines]
10.58.123.11
10.58.123.11
10.58.123.11
10.58.123.11
2600:1f12:c8f:5f1e:0:0:0:1b1b
[50 similar lines]
```

**Comment by archoversight** [comment]
Although in my case even though the EKS cluster is in IPv6 mode it sometimes reports the IPv4 address of the node.

**Comment by mikestef9** [comment]
We have are investigating this, will provide more details here asap

**Comment by stevehipwell** [comment]
@mikestef9 I'm pretty sure that this isn't dependent on custom networking, just that the node has multiple ENIs attached. Obviously custom networking makes this easy to configure, especially with IP prefixes.

@archoversight how many ENIs are there attached on your nodes? I guess the IPv6 cause might be subtly different with the same symptoms.

**Comment by archoversight** [comment]
@stevehipwell I've got a single ENI attached to the instance, that single ENI gets a /80 attached for the pods to get IP's out of.

The problem for me is that it's advertising that IPv4 address of that ENI, but the certificate the kubelet has does not contain that IP address in its certificate.

That private IPv4 address should never be advertised in k8s in the first place.

![Screen Shot 2022-04-07 at 12 05 09 PM](https://user-images.githubusercontent.com/67296324/162268077-c3ff5495-00fd-486f-9873-ed7a276f32df.png)

**Comment by stevehipwell** [comment]
@archoversight yeah, the same but different to the IPv4 issue. Hopefully a single easy fix.

**Comment by mikestef9** [comment]
We are in the middle of rolling out a fix for all clusters, will close this issue once it's complete

**Comment by stevehipwell** [comment]
@mikestef9 how's the rollout going? Are we expecting to see a new platform version and is there an actual issue to track on the EKS distro repo or elsewhere?

**Comment by mikestef9** [comment]
Forgot to update. The fix completed roll out several days ago. No new platform version, and all existing clusters are patched.

**Comment by archoversight** [comment]
@mikestef9 thank you!
