### ISSUE TITLE
[EKS] [request]: Internal NLB TLS Protocol Support

### ISSUE THREAD

**Issue by maguire007** [aws/containers-roadmap#171]
**Tell us about your request**
What do you want us to build?

Would like to see support for TLS termination with k8 service loadbalancer 
type loadbalancer aws-load-balancer-type: nlb , so internal NLBs created via k8 services can be TLS/secure-TCP protocol.  It looks like the only protocols supported now are TCP.  It seems that the TLS protocol support it needs to read are the  aws-load-balancer-ssl-cert and aws-load-balancer-ssl-policy settings from the annotations.

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

The goal is to provide TLS with nlb internal using k8 service annotations.

**Are you currently working around this issue?**

Using internal LB TLS with nginx.

**Comment by alex-berger** [comment]
Having https://github.com/kubernetes/kubernetes/pull/74910 in upstream kubernetes, which eks release will support TLS termination with NLB?

**Comment by jamesduffy** [comment]
@alex-berger [Looks like it is available in 1.15](https://github.com/kubernetes/kubernetes/pull/74910#issuecomment-491384111)

**Comment by astrived** [comment]
The support for NLB TLS came with release 1.15 https://github.com/kubernetes/kubernetes/pull/74910
