### ISSUE TITLE
[EKS] [request]: Windows Server 2022 support

### ISSUE THREAD

**Issue by ChrisMcKee** [aws/containers-roadmap#1710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for the latest LTS version of windows server (2022)
https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We try to maintain build agents based on lts releases and windows docker containers lock you into using base containers based on the operating system you build on which has to also match the one you'll run on. (due to the way it shares kernel space)
20H2 is EOL this august; 2022 ltsc is available. https://hub.docker.com/_/microsoft-windows-servercore

**Are you currently working around this issue?**
As 2019 doesn't contain .net 4.8 by default we have to install it in the image during creation 
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-48

**Comment by gitfool** [comment]
There's an [_ecs_ optimized ami](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;v=3;search=:Windows_Server-2022-English-Full-ECS;sort=desc:name) but still no [_eks_ optimized ami](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;v=3;search=:Windows_Server-2022-English-Full-EKS;sort=desc:name). 😕

**Comment by goyalpurvi** [comment]
Hi there! Windows 2022 support in Amazon EKS is being worked on and should be available soon. If you're curious about what other features are on the AWS containers roadmap, please check out our public roadmap here: https://github.com/aws/containers-roadmap

**Comment by dropdeadfu** [comment]
We are anxiously on a new 2022 LTSC ami since networking is broken on 2019 for us (due to calico and the need of DSR to be enabled). I would like to avoid manually hacking a weird version that can be used a worker node. Our cluster still has 3 20H2 SAC nodes running which the developers rely on but stand on their last leg. Please give us an update.

**Comment by goyalpurvi** [comment]
Windows Server 2022 EKS optimized AMIs are launched and publicly available now!
Please refer to the public AWS documentation for more details: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html
