### ISSUE TITLE
[ECR] [request]: Ability to configure scan expiration threshold age for ECR repo or registry to control SCAN_ELIGIBILITY_EXPIRED status. 

### ISSUE THREAD

**Issue by bogdannazarenko** [aws/containers-roadmap#1722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add ability to configure scan expiration age for repository or registry for enhanced scanning to control SCAN_ELIGIBILITY_EXPIRED status age threshold.

**Which service(s) is this request for?**
ECR Enhanced Scanning

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It is possible to have images older than 30 days running in production, but for security compliance are needed to be scanned regardless of age. Further, ECR repositories can be IMMUTABLE therefore impossible to update existing image tag. Therefore a deployment of a new a new image SHA is required to keep particular service/image scanned.

**Are you currently working around this issue?**
Existing workaround is to setup pipelines for hundreds of images to re-build every 30 days (not just re-build but re-build with a change to achieve a new SHA for the image because ECR scan selection is based on SHA and not on image tag). This is extremely tedious and time consuming task and all in effort just to have images continuously scanned.

**Additional context**
Our ECR repositories are IMMUTABLE therefore we need to push new SHA, hence an actual change to the image.

**Comment by lukas-eu** [comment]
See also: https://github.com/aws/containers-roadmap/issues/1605

**Comment by bradg-aws** [comment]
Thanks for raising this.

Enhanced scanning now supports configuring the scan duration for continuously scanned images: https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-enhanced-duration.html
