### ISSUE TITLE
[EKS] [request]: Support EC2 Resource Based Naming

### ISSUE THREAD

**Issue by archoversight** [aws/containers-roadmap#1723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Allow EC2 Resource Based Naming to be used on IPv4 and IPv4/IPv6 dual stack subnets with EKS

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Resource based naming removes the IPv4 address from hostname, and makes it easier to search for a node. It also allows the internal node DNS to have an AAAA record unlike the IPv4 address based naming.

**Are you currently working around this issue?**

N/A

**Additional context**

It's documented that it doesn't work, but why it doesn't work is not documented or known, any additional info AWS is able to provide for this? If you enable RBN after deploying an EKS cluster and roll your nodes, the new nodes don't get a certificate that is valid for the kubelet.

**Comment by georgejohnis** [comment]
Amazon [EKS version 1.23](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23) added support for worker nodes with [EC2 resource based naming](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-modify) enabled. As called out in EC2 documentation [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-modify), you can enable resource naming at a subnet level or at an EC2 instance level. 

**Note**: Support for resource based naming is not available for worker nodes created as part of an [EKS Managed Node Group](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html) (MNG) yet. We plan to add support for resource based naming in MNG over the next few months. Hence leaving this issue open.

**Comment by ecerulm** [comment]
>Amazon [EKS version 1.23](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23) added support for EC2 based worker nodes with [resource based names](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-modify).

@georgejohnis , I don't see any mention on [EKS 1.23 release notes](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23) about `resource-name`\resource-based naming. 

Is there any official source stating that EKS supports resource-based naming in addition to the IP address-based naming? 

The only thing I could find in the EKS User Guide says "The subnets must use IP address-based naming. Amazon EC2 resource-based naming isn't supported by Amazon EKS."

**Comment by mikestef9** [comment]
Closing as RBN is fully supported in EKS. Will make sure our docs get updated.
