### ISSUE TITLE
[EKS] [EBS CSI Addon]: Allow updates on nodeSelector/affinity

### ISSUE THREAD

**Issue by archoversight** [aws/containers-roadmap#1724]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I would like to force the `ebs-csi-controller` pods to always live on certain nodes in my k8s cluster. Unfortunately the `nodeSelector` field is managed, as is the `affinity` field so I can't add any additional restrictions on where these runs.

**Which service(s) is this request for?**

EKS Addon: EBS CSI

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I have certain nodes that I would prefer not to run the ebs-csi-controller on due to security constraints/requirements. Such as CI/CD pipeline nodes where I may not have full control over the security of the code running on those nodes and I don't want to accidentally allow a container breakout to get access to the the EBS CSI IRSA account credentials.

**Are you currently working around this issue?**

There is no work-around, unfortunately.

**Additional context**

- https://github.com/aws/containers-roadmap/issues/1706 is similar in that it wants to add/change the tolerations

**Comment by sriramranganathan** [comment]
Amazon EKS team recently announced the general availability of advanced configuration feature for managed add-ons. You can now pass in advanced configuration for cluster add-ons, enabling you to customize add-on properties not handled by default settings. Configuration can be applied to add-ons either during cluster creation or at any time after the cluster is created.

Using advanced configuration feature, you can now configure nodeSelector property for the Amazon EBS CSI driver add-on.

To learn more about this feature, check out this blogpost - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

Check out the Amazon EKS documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html
