### ISSUE TITLE
[EMR on EKS] [Job Templates]: Capability to create templates for EMR on EKS Jobs

### ISSUE THREAD

**Issue by janakagarwal** [aws/containers-roadmap#1726]
Create and use Job Templates to enforce application parameters and simplify EMR on EKS job submission

**Which service(s) is this request for?**
EMR on EKS

Customers need to pass in parameters such as virtual cluster ID, job execution IAM role, and amount of capacity to use for the job as part of their EMR on EKS StartJobRun API calls. Many parameters do not change between jobs. Also, administrators often want to enforce specific parameters such as those for security and log locations. With this feature, customers can create job templates by providing default values for certain parameters while allowing end-users to supply overrides. Additionally, administrators can also mark specific parameters as immutable to enforce values for security or compliance reasons.

**Comment by dalbhanj** [comment]
Feature is shipped: https://aws.amazon.com/about-aws/whats-new/2022/11/emr-eks-job-templates-store-share-parameters-job-runs/
