### ISSUE TITLE
[ECR] [request]: Support scanning of Ubuntu 22.04 LTS based images

### ISSUE THREAD

**Issue by bchew** [aws/containers-roadmap#1728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for scanning Ubuntu 22.04 LTS based images for security vulnerabilities

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Continue to have the ability to scan images pushed to ECR after upgrading the base image to Ubuntu 22.04 LTS.

**Are you currently working around this issue?**
No

**Additional context**
Pushed an image based on Ubuntu 22.04 and received `UnsupportedImageError` from ECR scan on push

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sumanthst25** [comment]
From the documentation : https://docs.aws.amazon.com/inspector/latest/user/supported.html I see that scanning for ubuntu 22.04 is supported through Amazon Inspector .
I have tested this and I see the vulnerabilities reported for enhanced scanning . I also checked that basic scan for ubuntu 22.04 is not supported at the moment and I too got the same error : "UnsupportedImageError: The operating system 'ubuntu' version '22.04' is not supported."

**Comment by arunsollet** [comment]
As mentioned above, Ubuntu 22.04 LTS is now supported in ECR basic scan.

**Comment by subhranil05** [comment]
Please add support ubuntu '23.10' version to ECR basic scan. Currently  not supported

`UnsupportedImageError: The operating system 'ubuntu' version '23.10' is not supported.`

@tylerread @arunsollet
