### ISSUE TITLE
[ECS] [request]: Scheduled autoscaling of ECS services.

### ISSUE THREAD

**Issue by rohanmangal** [aws/containers-roadmap#173]
**Tell us about your request**
Scheduled Scaling for Amazon ECS Service like it happens for EC2.

Reference Link for EC2 Scheduled Scaling: https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html

**Which service(s) is this request for?**
This could be Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Outcome would be to schedule a ECS Service based on schedule for predictable load changes.

For example, every week the traffic on web application starts to increase on Wednesday, remains high on Thursday, and starts to decrease on Friday. We can plan your scaling actions based on the predictable traffic patterns of web application. Scaling actions are performed automatically as a function of time and date.

**Are you currently working around this issue?**
Right now a custom solution is used CloudWatch Event -> Lambda -> ECS UpdateService API.

**Comment by rohanmangal** [comment]
missed it!
Its already available under https://docs.aws.amazon.com/autoscaling/plans/userguide/what-is-aws-auto-scaling.html#scalable-resources

**Comment by abby-fuller** [comment]
this already exists! https://aws.amazon.com/about-aws/whats-new/2017/11/scheduled-scaling-now-available-for-application-auto-scaling/

**Comment by lamhaison** [comment]
Yes, I can't see the feature on AWS console. However, I can do it by AWS CLI or using terraform.
Here is the references
* Terraform - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_scheduled_action
* AWS CLI - https://docs.aws.amazon.com/zh_tw/cli/latest/reference/application-autoscaling/index.html

My AWS-CLI for esc fargate

```
aws application-autoscaling register-scalable-target --service-namespace ecs --scalable-dimension ecs:service:DesiredCount --resource-id service/<CLUSTER>/<SERVICE> --min-capacity <NUM_TASKS> --max-capacity <NUM_TASKS>

aws application-autoscaling put-scheduled-action --service-namespace ecs   --scalable-dimension ecs:service:DesiredCount   --resource-id service/<CLUSTER>/<SERVICE> --scheduled-action-name scale-out-cron --schedule "cron(* * * * ? *)" --scalable-target-action MinCapacity=3 
```
