### ISSUE TITLE
Support for PodSecurityPolicy Admission Controller

### ISSUE THREAD

**Issue by gavinbunney** [aws/containers-roadmap#174]
**Tell us about your request**
We are looking at adding a PodSecurityPolicy to our EKS clusters, mostly focused on restricting privileged containers and hostPath mounting. It looks like EKS doesn’t yet support the PodSecurityPolicy Admission Controller.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We operate a shared group of EKS clusters for a wide-range of internal development teams. For this multi-tenant nature, we like to prevent inadvertent changes by developers to kernel parameters, breaking host components etc which may cause issues in other pods.

**Are you currently working around this issue?**
Hoping 🙏 

**Additional context**

**Attachments**

**Comment by spronin-aurea** [comment]
Will AWS break "alpha feature rule" for PodSecurityPolicy?

PSP turns beta in 1.13 only. 

See https://github.com/awslabs/amazon-eks-ami/issues/145#issuecomment-459052026

**Comment by pawelprazak** [comment]
Will delivering #30 help with this issue (as also asked in the other issue: https://github.com/aws/containers-roadmap/issues/30#issuecomment-459144990)?

**Comment by llamahunter** [comment]
Why do you say that PodSecurityPolicy is in alpha until 1.13?   Docs seem to indicate it was beta long before that.  e.g. https://v1-11.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#podsecuritypolicy-v1beta1-extensions

**Comment by rvadim** [comment]
We can't use EKS until PSP support will be added =(

**Comment by tabern** [comment]
Can confirm that EKS will support the PodSecurityPolicy admission controller along with K8s version 1.13 - https://github.com/aws/containers-roadmap/issues/30

**Comment by tabern** [comment]
As part of 

Learn more on the AWS Blog: [Using Pod Security Policies with Amazon EKS Clusters](https://aws.amazon.com/blogs/opensource/using-pod-security-policies-amazon-eks-clusters/) or [documentation](https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html)
