### ISSUE TITLE
[EKS] [request]: upgrade to Kubernetes v1.22.9

### ISSUE THREAD

**Issue by aschleck** [aws/containers-roadmap#1749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Kubernetes released v1.22.9 on April 13th, which fixes https://github.com/kubernetes/kubernetes/pull/108366 (marked priority/critical-urgent.) We have been using Argo to sequence large jobs that schedule lots of pods quickly and are getting bitten pretty hard by this bug ever since we upgraded to 1.22 last week.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The main problem is that currently our large job scheduling breaks under load. I imagine this is exposing a bug in Argo too, but this set up worked fine under 1.21 and I think 1.22.9 will work the root cause.

If this problem remains unresolved, we are thinking about downgrading to 1.21 by any means necessary. But that sounds like a nightmare.

**Are you currently working around this issue?**
Currently have no viable workaround

Thank you!

**Comment by aschleck** [comment]
Super exciting to see that my cluster's control plane got updated to 1.22.9 today, thanks for making this happen! Though the latest worker AMI seems to still be at 1.22.6, looking forward to https://github.com/awslabs/amazon-eks-ami/issues/914 being resolved.

**Comment by cartermckinnon** [comment]
The latest AMI release, [v20220610](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220610), includes kubelet 1.22.9. 👍

@mikestef9 you can close this. 🎉
