### ISSUE TITLE
[ECS] [request]: Updating the ecs service using terraform does not show any idempotence nature. Instead of updating via rolling update, they would simply get deleted and recreated creating a significant downtime.ply get

### ISSUE THREAD

**Issue by HarvinderSinghDiwan** [aws/containers-roadmap#1750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
 ECS service has a feature of updating the service for new desired counts, new task definition reference,s and so on. And this works perfectly fine with aws cli as well as with the ECS-cli.  But we in our organization trust cloud-native applications with a cloud-native deployment strategy wherein we follow principles of GitOps along with DevSecOps. 

So, we provision the infrastructure with Terraform and also deploy serverless applications using terraform and again keeping GitOps in mind. Now when we deploy ECS task definition and service using terraform, it works fine but when we update our container thereby creating a new revision for task definition, we also have to update our service. But when we update the service, it does not happens the way it should. The service first gets deleted and then again gets recreated with a significant amount of downtime even if we set rolling update along with minimum healthy pods percentage and lifecycle policy as create_before_destroy.  On top of this, using lifecycle resource gives an error saying ( InvalidParameterException: Creation of service was not idempotent. )

Second is if you even try to update the desired count from 3 to 5 or 6 and so on, the service will still get deleted first and then recreate.

https://github.com/hashicorp/terraform-provider-aws/issues/2283   <----------- this is the github discussion where u will find all the related issues. They are all unsolved. 

I tried searching for solutions in google but many guys have already faced this issue and they didnot get any permanent fix. So they simply fixed this by changinf the service name at every terraform run .

**Are you currently working around this issue?**
How are you currently solving this problem?

https://github.com/hashicorp/terraform-provider-aws/issues/2283   <----------- this is the github discussion where u will find all the related issues. They are all unsolved.  
**Additional context**
Anything else we should know?

https://github.com/hashicorp/terraform-provider-aws/issues/2283   <----------- this is the github discussion where u will find all the related issues. They are all unsolved.  
**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
![image](https://user-images.githubusercontent.com/46323744/168979258-794136af-2bcc-439e-8ce4-e60975694b76.png)

![image](https://user-images.githubusercontent.com/46323744/168979332-1ac0fd49-87fe-4992-8bcc-33a2e5032af1.png)

below image shows that the resource is first deleted upon removig the lifecycle block.

![image](https://user-images.githubusercontent.com/46323744/168979558-c8989c98-3647-4083-8c94-24925c55ddd8.png)

Finally it is being destroyed.

![image](https://user-images.githubusercontent.com/46323744/168979639-449386ee-b4e1-44f7-b8ac-7a68f83bad50.png)

**Comment by HarvinderSinghDiwan** [comment]
Please help me resolve this soon AWS team. Looking forward for your support.

**Comment by mreferre** [comment]
@HarvinderSinghDiwan can you clarify one thing? issue https://github.com/hashicorp/terraform-provider-aws/issues/2283 seems to be laser focused on in-place updating the deployment strategy for an ECS service (which, as you noted is supported by the AWS APIs). You seem to be saying you have also problems in updating the task definition and desired count (which is also obviously supported by the AWS APIs and it's at the core of what ECS does). Issue https://github.com/hashicorp/terraform-provider-aws/issues/2283 does not seem to be reporting this as a limitation. I am not super familiar with Terraform but are you saying that TF requires to destroy and recreate a service when you need to update the task definition and the task desired count? That would seem weird?

**Comment by otterley** [comment]
@HarvinderSinghDiwan From your plan output, it appears that you are removing the Capacity Provider Strategy from your service. Was this intentional?  If so, Terraform may require you to recreate the service. If the service is behind a load balancer, this should not impact availability, provided you instruct Terraform to create a new service with the same Load Balancer Target Group before removing the older generation of the service.

**Comment by HarvinderSinghDiwan** [comment]
![image](https://user-images.githubusercontent.com/46323744/169041272-cfc01423-8983-423c-bf8c-1a1496317d8d.png)


Even if I use strategy, I can't as I am using fatgate not ec2 or external

**Comment by HarvinderSinghDiwan** [comment]
Please help me update services without any downtime
I have been into this trouble since last 2 months

**Comment by otterley** [comment]
Correct, you can't use a placement strategy with Fargate. Placement strategies are used to place multiple tasks onto EC2 instances. Since Fargate only runs 1 task per instance, placement strategies do not apply.

**Comment by HarvinderSinghDiwan** [comment]
So what is the solution to this ? GitOps is at peak at this moment and if ECS won't allow such features then we will have to look for some alternatives, which is quite painful. Migration is always painful. Please help .

**Comment by HarvinderSinghDiwan** [comment]
Any update on support ?

**Comment by otterley** [comment]
Hi @HarvinderSinghDiwan ,

We understand you’re having some difficulties with ECS and Terraform, and we want to help you have a positive experience. However, this GitHub Issue Tracker is for receiving specific customer requests for new features or improvements to AWS Container Services, and it’s not monitored by AWS Support. If you need AWS Support, we offer [various support plans](https://aws.amazon.com/premiumsupport/), and you can also receive community support by visiting [re:Post](https://repost.aws). Additionally, Hashicorp is the vendor of Terraform and offers [commercial support](https://support.hashicorp.com/hc/en-us) as well. Since this issue is relating to how Terraform is manipulating ECS services, it is likely that Hashicorp will be able to investigate your situation and provide a resolution for you.

**Comment by HarvinderSinghDiwan** [comment]
ok No Problem

**Comment by HarvinderSinghDiwan** [comment]
Hello AWS Team, I am glad to inform you that my problem has been resolved. I figured out the solution which I am also going to mention below in the chat so that other geeks can take help out of it. But I would like to thanks the entire team for being here and keeping the chat perennial and healthy. I am glad to engage wiith you guys and have really no words to explain my feelings. Once again thank you every one.


Below is the solution: 

![image](https://user-images.githubusercontent.com/46323744/169640426-81a3e015-fecd-4c4f-9668-930ebb18805d.png)

**Comment by bruce-szalwinski** [comment]
> Hello AWS Team, I am glad to inform you that my problem has been resolved. I figured out the solution which I am also going to mention below in the chat so that other geeks can take help out of it. But I would like to thanks the entire team for being here and keeping the chat perennial and healthy. I am glad to engage wiith you guys and have really no words to explain my feelings. Once again thank you every one.
> 
> Below is the solution:
> 
> ![image](https://user-images.githubusercontent.com/46323744/169640426-81a3e015-fecd-4c4f-9668-930ebb18805d.png)

@HarvinderSinghDiwan glad you were able to resolve this.  Can you explain more about what you changed?  
- bumped `deployment_min_healthy_percent` from `50` to `70`?
- changed `name` from `addition-v1` to `addition-v2`?

**Comment by HarvinderSinghDiwan** [comment]
@bruce-szalwinski I just mentioned the **launch type** and removed lifecycle block. The main thing is to include the launch type. terraform actually has bug or some loose consideration of gitops in case of ECS I think. Let me know if the recommended changes works for you.
