### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.16 on Vulnerability Scans

### ISSUE THREAD

**Issue by rgoltz** [aws/containers-roadmap#1753]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today, 23.05.2022, Alpine Linux 3.16 has been released (please see https://gallery.ecr.aws/docker/library/alpine and https://alpinelinux.org/posts/Alpine-3.16.0-released.html). We are using AWS ECR Basic (Image) Scanning to check for vulnerabilities.

We are aware that AWS ECR Basic (Image) Scanning using Clair - Hence, we created a PR which extends claircore for 3.16: https://github.com/quay/claircore/pull/605 - This PR is already reviewed & merged by clair-team.

AWS ECR Basic (Image) Scanning should handle & support Alpine Linux 3.16, which might be releated to an update of clair within AWS backend.

**Are you currently working around this issue?**
We might need to skip the Vulnerability Scans using AWS ECR Basic (Image) Scanning in case of the ECR returning ```UnsupportedImageError: The operating system 'alpine' version 'v3.16' is not supported```. There is no further workaround known while using AWS ECR Basic (Image) Scanning.

**Additional context**
Alpine SecDB also already added version 3.16, please see https://secdb.alpinelinux.org/v3.16/ (supporting vulnerability data)

**Attachments**

**Comment by bradg-aws** [comment]
Thank you for raising this. 
AWS ECR Basic Image Scanning now supports alpine v3.16.
