### ISSUE TITLE
[FARGATE] [request]: Update the AWS SSM Session manager to 3.1.1374.0 or later to provide the newest features

### ISSUE THREAD

**Issue by FlorisBondzio** [aws/containers-roadmap#1756]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Update the underlying AWS SSM Session Manager

**Which service(s) is this request for?**
Fargate/ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, we are implementing an ECS _openssh-server_ instance, which we use to forward a database port to our local machine, to access the isolated database behind the instance.
This works fine, but requires two steps:

- Starting a session through the AWS SSM Session Manager
- Using SSH to forward the port to the local machine

AWS announced on Friday (27.05) a new function for the Session Manager, which makes the second step obsolete: https://aws.amazon.com/about-aws/whats-new/2022/05/aws-systems-manager-support-port-forwarding-remote-hosts-using-session-manager
This new function requires an update of the SSM Agent on the managed instance: "To get started, install SSM Agent version 3.1.1374.0 or later on the managed instances that you are establishing a port forwarding session with".  The AWS support told us to open a GitHub issue to request the update for the underlying Fargate infrastructure. 
Would you please consider an update?

**Comment by andymac4182** [comment]
@FlorisBondzio If you want to accelerate this you can install your own copy of the SSM agent and force stop the original executables and run yours. I have done this and it works perfectly well. 

Been waiting for this to add this features to https://github.com/tedsmitt/ecsgo

**Comment by megane42** [comment]
It seems the version is bumped. Thank you so much 🎉 

```
# /managed-agents/execute-command/amazon-ssm-agent --version
SSM Agent version: 3.1.1732.0
```

**Comment by ollypom** [comment]
Closing because I believe this issue has been solved (as per @megane42 's comment) . If I've misunderstood, let me know and I can reopen the issue.
