### ISSUE TITLE
[EKS] [request]: allow to change configuration on aws-ebs-csi-driver addon

### ISSUE THREAD

**Issue by bhushanchirmade** [aws/containers-roadmap#1757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently we get OOM errors with 128MB default memory for the pod. When we increase it to 256MB it works fine for our workload. There is no direct way of passing this parameter into our Terraform code and we have to modify the deployment object. But next upgrade it resets it back to 128MB which we would like to avoid. We can use the helm chart but we lose the benefit of EKS add-on. It would be nice to have resource parameter support where we can extend the memory based on the usage. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We use 200 PVCs to manage the stateful workload. 

**Are you currently working around this issue?**
How are you currently solving this problem?
Currently we modify the deployment object but its not a permanent solution. 

**Additional context**
Anything else we should know?
No. 

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by ConnorJC3** [comment]
Hi, today's release of the EBS CSI Driver addon (`v1.14.0-eksbuild.1`) now supports full configuration of both the node and controller's resource requests/limits via the new [Advanced Configuration](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/) feature for EKS Addons!

The configuration parameters are the same as the upstream helm chart: `node.resources` and `controller.resources`. This should be supported with Terraform as well: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#example-add-on-usage-with-custom-configuration_values

**Comment by sriramranganathan** [comment]
Amazon EKS team recently announced the general availability of advanced configuration feature for managed add-ons. You can now pass in advanced configuration for cluster add-ons, enabling you to customize add-on properties not handled by default settings. Configuration can be applied to add-ons either during cluster creation or at any time after the cluster is created.

Using advanced configuration feature, you can now configure resource requests and limits for the Amazon EBS CSI driver starting version v1.14.0-eksbuild.1

To learn more about this feature, check out this blogpost - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

Check out the Amazon EKS documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html
