### ISSUE TITLE
[EKS] [request]:  Amazon EKS end of support or Kubernetes version deprecation details in EKS console

### ISSUE THREAD

**Issue by gowthasa** [aws/containers-roadmap#1759]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently, if any clusters in account are running the version nearing the end of support, Amazon EKS sends out a notice which includes the end of support date. However, it is seen that many customers miss these E-mails or notifications and would later have very tight timelines to upgrade their EKS clusters Kubernetes versions to avoid Amazon EKS perform auto-upgrade on these clusters. 

It would be good, if the EKS teams can implement and add a column or tab in the EKS console that would give the `End of Support` or `Version deprecation` date, so that customers are aware of their EKS clusters version end of support and can plan for upgrading the same accordingly. 

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/98508448/172605827-5dbf63e1-edb9-4a83-9ae6-edf6aaf50cf6.png">

For example below versions end of support date are as below: 

1.18 | March 31, 2022
1.19 | June 30, 2022

If the same can be shown in EKS console for respective versions of EKS clusters it would help many customers. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Amazon EKS end of support or Kubernetes version deprecation notice in the EKS console 

**Are you currently working around this issue?**
Currently, we need to watch for the Deprecation notice E-mails from EKS teams or check the EKS documentation page https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar 

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by neerajprem** [comment]
This is highly important, a must-required Feature Request.
- G24x7

**Comment by amedirr** [comment]
The EKS console now shows the end of support date for both standard and extended support as well as the upgrade policy for the cluster in the cluster table. Closing this issue.
