### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.16 on Enhanced Vulnerability Scans

### ISSUE THREAD

**Issue by cnocula-peg** [aws/containers-roadmap#1766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Add Alpine 3.16. to the supported operating systems for ECR Enhanced Scanning / Inspector 2(https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os)

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In https://github.com/aws/containers-roadmap/issues/1753 - Alpine 3.16 has beed added as a supported version for basic scanning only. Our scanning for an image based on Alpine 3.16 fails, when ECR Enhanced Scanning is activated due to:
```
No scan findings
Scan status: UNSUPPORTED_IMAGE
```

**Are you currently working around this issue?**
We need to currently switch the Enhanced Scanning back to Basic, since otherwise we are not getting any vulnerability scan results in our deployment pipeline

**Additional context**
[Anything else we should know?](https://github.com/aws/containers-roadmap/issues/1753)

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sumanthst25** [comment]
I checked that the enhanced scanning for Alpine 3.16 versioned images is now supported and I can confirm through replication.

Although the documentation : https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os hasn't been updated yet

**Comment by arunsollet** [comment]
Thank you for raising this issue. Amazon ECR Enhanced Image Scanning now supports Alpine 3.16. The documentation page ( https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os ) has also been updated.
