### ISSUE TITLE
[ECS] [request]: Ability to configure Task Set Capacity Provider Strategies via CloudFormation

### ISSUE THREAD

**Issue by the-avid-engineer** [aws/containers-roadmap#1773]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to see support for Capacity Provider Strategies on ECS Task Sets

**Which service(s) is this request for?**
ECS, CloudFormation

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
[Task Sets](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskSet.html) have support for Capacity Provider Strategies (at least in the CLI), but this feature is either unavailable (or undocumented?) from CloudFormation's [AWS::ECS::TaskSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskset.html) resource type. I would like to be able to configure a Task Set's Capacity Provider Strategy via CloudFormation.

**Are you currently working around this issue?**
N/A

**Additional context**
I'm trying to set up ECS Services that deploy using CloudFormation and have Auto-scaling via Capacity Providers as well as Blue-Green deployment, which involves (among other things) using the `EXTERNAL` deployment type and Task Sets. When I have the Capacity Provider Strategy set on the ECS Service, the tasks are forever stuck in provisioning, presumably because the Capacity Provider Strategy is not set up (and apparently cannot be set up via CloudFormation)

**Comment by the-avid-engineer** [comment]
Sorry if this is the wrong place

**Comment by rgoltz** [comment]
Hej @the-avid-engineer - I would recommend to open a issue at https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues and link this CFN request with this request here :)

**Comment by the-avid-engineer** [comment]
Thank you for the redirect!
