### ISSUE TITLE
[EKS] [Bug]: Kubernetes Resource View in Amazon EKS console is not working as expected as the Go Client doesn't perform pagination and only supports upto 100 requests

### ISSUE THREAD

**Issue by LearningNewbie** [aws/containers-roadmap#1786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Kubernetes resource view is a convenient way to view resources in aws console. However it is only displaying 100 objects (pods,namespaces or any thing) making it a less desirable tool. If there are more than 100 objects (for example: 600 namespaces), the tools only shows 100 of these objects. Although, when we run the command `kubectl get namespaces` , we can still see all 600 namespaces. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Please review the code, fix the "Go-http-client/1.1" client to support pagination and display all the resources as they are supposed to be.

**Are you currently working around this issue?**
No, there is no workaround for this until an up-to date go client version is introduced. 

**Additional context**
Anything else we should know?

Below attached is the output of `kubectl get namespaces` with verbosity 7. As per the output, there is pagination after the first API Call `/api/v1/namespaces?limit=500` and the paginated uri is as follows `api/v1/namespaces?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NTczMDUwNCwic3RhcnQiOiJ0ZXN0LTU0XHUwMDAwIn0&limit=500`

    I0712 10:01:42.944382   36188 round_trippers.go:432] GET https://<redeacted>/api/v1/namespaces?limit=500
    I0712 10:01:42.944420   36188 round_trippers.go:438] Request Headers:
    I0712 10:01:42.944430   36188 round_trippers.go:442]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
    I0712 10:01:42.944438   36188 round_trippers.go:442]     User-Agent: kubectl/v1.21.2 (darwin/arm64) kubernetes/092fbfb
    I0712 10:01:44.189898   36188 round_trippers.go:457] Response Status: 200 OK in 1245 milliseconds
    I0712 10:01:44.244756   36188 round_trippers.go:432] GET https://<redeacted>/api/v1/namespaces?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NTczMDUwNCwic3RhcnQiOiJ0ZXN0LTU0XHUwMDAwIn0&limit=500
    I0712 10:01:44.244781   36188 round_trippers.go:438] Request Headers:
    I0712 10:01:44.244787   36188 round_trippers.go:442]     User-Agent: kubectl/v1.21.2 (darwin/arm64) kubernetes/092fbfb
    I0712 10:01:44.244793   36188 round_trippers.go:442]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
    I0712 10:01:44.287971   36188 round_trippers.go:457] Response Status: 200 OK in 43 milliseconds

Since, i didn't have similar visibility for AWS Console Client, i skimmed through the audit logs and found the following:
- Instead of limit being 500, the client is only listing 100 resources for any object. 
- There is no pagination occurring after the 100 resources. 

```
{
    "kind": "Event",
    "apiVersion": "audit.k8s.io/v1",
    "level": "Request",
    "auditID": "21ecf631-ec36-4120-9a1e-11d3e2dbd5c7",
    "stage": "ResponseComplete",
    "requestURI": "/api/v1/namespaces?limit=100",
    "verb": "list",
    "user": {
        "username": "eksadmin",
        "uid": "aws-iam-authenticator:123456789321:<redacted>",
        "groups": [
            "system:masters",
            "system:authenticated"
        ],
        "extra": {
            "accessKeyId": [
                "<redacted>"
            ],
            "arn": [
                "arn:aws:sts::123456789321:assumed-role/<redacted>"
            ],
            "canonicalArn": [
                "arn:aws:iam::123456789321:role/<redacted>"
            ],
            "sessionName": [
                "<redacted>"
            ]
        }
    },
    "sourceIPs": [
        "<redacted>"
    ],
    "userAgent": "Go-http-client/1.1",
    "objectRef": {
        "resource": "namespaces",
        "apiVersion": "v1"
    },
    "responseStatus": {
        "metadata": {},
        "code": 200
    },
    "requestReceivedTimestamp": "2022-07-12T13:09:48.390653Z",
    "stageTimestamp": "2022-07-12T13:09:48.414712Z",
    "annotations": {
        "authorization.k8s.io/decision": "allow",
        "authorization.k8s.io/reason": ""
    }
}
```

**Comment by kakarotbyte** [comment]
This was fixed. I believe we can close it.
