### ISSUE TITLE
[ECS] [request]: Please add docker compose support for boto3

### ISSUE THREAD

**Issue by narenaryan** [aws/containers-roadmap#179]
**Tell us about your request**
Currently, docker-compose is supported via ECS CLI. Please add it in API features too.

**Which service(s) is this request for?**
This is for ECS Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are having our whole development/deployment of services in the form of docker-compose file. We have a boto3/python pipeline management project that deploys above docker compose services to ECS Fargate. Since fargate doesn't support the deployment of docker-compose files through API, we need to hack our project using ec2-cli

**Are you currently working around this issue?**
We are spawning a process with ec2-cli supplying necessary arguments which is not a clean approach.

**Additional context**
Anything else we should know?
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by clareliguori** [comment]
Hi @narenaryan, we're unlikely to support the docker-compose format directly in our APIs.  But, would a tool like [container-transform](https://github.com/micahhausler/container-transform) to transform a docker-compose file into an ECS task definition work for you?  Then you can use the resulting ECS task definition file in boto.
