### ISSUE TITLE
[ECR] [request]: public registry tag listing API not OCI Compliant

### ISSUE THREAD

**Issue by vasireddy99** [aws/containers-roadmap#1795]
The [OCI spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery) mandates that the response MUST be in the following format:
 
'''
{
  "name": "<name>",
  "tags": [
    "<tag1>",
    "<tag2>",
    "<tag3>"
  ]
}
'''

For More info see Comments here : https://github.com/aws/containers-roadmap/issues/1262#issuecomment-1196031981

 * https://github.com/aws/containers-roadmap/issues/1262 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

<!--

**Security disclosures**

If you think you’ve found a potential security issue, please do not post it in the Issues.  Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).

**Which service(s) is this request for?**
ECR

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by coultn** [comment]
Closing this as we are working on it via https://github.com/aws/containers-roadmap/issues/1262.  See the comments there.  Apologies for the confusion.
