### ISSUE TITLE
[ECR] CloudWatch events for push/delete image

### ISSUE THREAD

**Issue by yinshiua** [aws/containers-roadmap#18]
Send push and delete image events to CWE. Customers can use push events to, for example, trigger another another action such as automated testing or rebuilding another container image with the image that was pushed as a base layer.

Today, customers can find this data via CloudTrail. Providing the data via CWE will make integration easier for customers.

**Comment by showaltb** [comment]
Is this functionality implemented?

I've followed the documentation at https://docs.aws.amazon.com/codepipeline/latest/userguide/create-cwe-ecr-source.html and the event rule is not being triggered. I've also tried creating a pipeline through the wizard, and the event rule created is not being triggered.

**Comment by jtoberon** [comment]
This is still in the release process. The final step is to update the CloudWatch web console, and this work has started.

**Comment by jtoberon** [comment]
https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html
https://docs.aws.amazon.com/eventbridge/latest/userguide/event-types.html#ecr-event-types
