### ISSUE TITLE
[ECR] [request]: Support for ECR / Inspector Scanning for AmazonLinux2022

### ISSUE THREAD

**Issue by vahedq** [aws/containers-roadmap#1800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Describe alternatives you've considered
Guidance on whether or not AL20xx will be on the roadmap for ECR scan

**Tell us about your request**
Is there a plan to support ECR Image Scanning for AL2022

(reference: https://github.com/amazonlinux/amazon-linux-2022/issues/145)

**Which service(s) is this request for?**
ECR and/or Inspector.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Switching from AL2 to AL2022 causes scans to fail with `UnsupportedImageError: The operating system 'amzn' version '2022' is not supported`

**Are you currently working around this issue?**
Currently planning to either manually monitor [here](https://alas.aws.amazon.com/alas2022.html) and switch to another scanner.

**Additional context**
N/A

**Attachments**
N/A

**Comment by guihernandez-ncl** [comment]
Hi. Any news on this? How come AWS's own recommended image is not supported to be scanned on ECR?

**Comment by ppi-agray** [comment]
Kind of weird that AL2022 is listed as a supported OS for ECR Scanning:
https://docs.aws.amazon.com/inspector/latest/user/supported.html
But it's clearly not

**Comment by mayankbpatel** [comment]
This is certainly disappointing.
As @ppi-agray mentioned, the docs are out of alignment with reality.
ECR scan compatibility of AL2022 images ought to be a **default** feature of Amazon Linux 2 images.

**Comment by IvDoorn** [comment]
AL2023 has been released now as well, and (obviously) suffers from the same bug.
Moreover, Amazon released a new Docker image for XRay daemon which is now based on AL2023, making it more embarrassing that Amazon ECR does not support scanning AL2023 images.

**Comment by mmehrten** [comment]
There are two types of scanning for ECR images:

* [Enhanced Scanning](https://docs.aws.amazon.com/inspector/latest/user/supported.html) which uses Amazon Inspector
* [Basic Scanning](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html) which uses the Clair open-source project

Amazon Linux is supported via Enhanced Scanning in Inspector, but not Basic Scanning as the Clair project [only supports AL2018 and 2 at this time](https://github.com/quay/claircore/blob/1405b573a27c08e12d974f0f2b7f4dcf1b149183/aws/distributionscanner.go#L32-L41).

**Comment by imhyeons** [comment]
So, Does anyone know when the vulnerability scanning feature for AL2022 & AL2023 OS will be supported on AWS ECR?

**Comment by frehov** [comment]
We just contacted AWS Support regarding this, and in their words.
The docs are pertaining to amazon inspector, which is the advanced image scanning option for ECR.

The basic scan is using Clair, and there is an open issue for it https://github.com/quay/claircore/issues/968

That being said, this issue being open close to a year, and AWS not contributing a fix towards Clair to ensure that AL2022/AL2023 images can be scanned, leaves a certain bad taste in my mouth.

The way I'm looking at this is that AWS wins either way, either by driving customers towards advanced scanning and higher cost, or by not having to lift a finger while the community most likely implements the required change in Clair for detection of AL2022/AL2023 and later versions

**Comment by dims** [comment]
@frehov see https://github.com/quay/claircore/pull/990 from @stewartsmith

**Comment by frehov** [comment]
> @frehov see [quay/claircore#990](https://github.com/quay/claircore/pull/990) from @stewartsmith

Yeah, good to see it gaining some attention. PR was opened a day after we reached out to support about it.

**Comment by r-heimann** [comment]
I seriously hope the ETA for this feature is not 1+ year.

**Comment by rgoltz** [comment]
Hi @r-heimann . From my personal estimation this topic is proceeding: As far as I can see Stewart @stewartsmith as AWS Amazon-Linux team-member already created a PR against claircore via https://github.com/quay/claircore/pull/990. During review of claircore maintainer Joseph @crozzy they hit a blocking issue. From my experience this requested dynamic distribution discovery is really necessary.

This blocking issue is addressed by AWS Amazon-Linux team into their own AL2023-repo via: 
* https://github.com/amazonlinux/amazon-linux-2023/issues/389

Hence, 👍 for https://github.com/amazonlinux/amazon-linux-2023/issues/389 would may help to get more attention into this topic of AL2023 support in ECR Basic Scanning. 

Let's keep our fingers crossed and up-votes, up-votes, up-votes 🚀

**Comment by r-heimann** [comment]
Clair now supports AL2023: https://github.com/quay/claircore/compare/v1.5.13...v1.5.14
Any ETA when ECR will update basic scanning to Clair >v1.5.14?

**Comment by jlbutler** [comment]
Hi all. I wanted to clarify that while ECR Basic Scanning does use Clair, it is not on the upstream current release (from claircore). We started a migration to it last year, but found the scan findings to be so different that it was disrupting customers and causing issues, so we rolled back to v2 and are currently maintaining that while we work on a path to migrate from it.

We are currently working on a plan to improve the Basic Scanning feature overall, which will bring AL:2023 support with it. That has been slower-going than we'd like, so we are also scoping out one-off work to get AL:2023 supported in the current Basic Scanning feature.

When we have a more specific update, we'll land it here. Thanks for your patience, we know this has been an issue and we are working toward the least-disruptive path toward improvements.

**Comment by frichtarik** [comment]
Hello @jlbutler, any news/updates on the topic ?

**Comment by r-heimann** [comment]
> I seriously hope the ETA for this feature is not 1+ year.

Pointing to my own comment

**Comment by jamiem-code** [comment]
Yep, just switched from a different image to this specifically to reduce vulnerabilities in basic image scanning, and very disappointed to find amazonlinux (2023) isn't supported!

Eagerly awaiting an update!

**Comment by r-heimann** [comment]
I might be wrong, but it seems to work now? Is AL2023 finally supported?
