### ISSUE TITLE
[EKS] [request]: Support for Kubernetes v1.24

### ISSUE THREAD

**Issue by stevehipwell** [aws/containers-roadmap#1802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like EKS support for Kubernetes v1.24 ([release blog](https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/)).

In preparation for this I'd like to see EKS v1.24 added to the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar); I think all pending upstream Kubernetes releases should be added to the calendar when they're released, even if the due date is initially only accurate to a quarter.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to use Kubernetes v1.24 from EKS and be able to plan when this is likely to happen.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
n/a

**Attachments**
n/a

**Comment by stevehipwell** [comment]
@mikestef9 given that EKS v1.24 is currently scheduled for November in the [release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar); is it work in progress or still researching?

**Comment by vipin-mohan** [comment]
EKS support for Kubernetes version 1.24 is now available
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-eks-eks-distro-support-kubernetes-version-1-24/

**Comment by vipin-mohan** [comment]
Closing this issue
