### ISSUE TITLE
[EKS] [request]: eks ami for ubuntu 22.04

### ISSUE THREAD

**Issue by vfx1b** [aws/containers-roadmap#1803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Create eks ubuntu 22.04 ami

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently with the ubuntu 20.04 lts eks ami cgroupsv2 need to be turned on manually in grub, kubectl-eks driver has to be set to systemd, and containerd has to be configured

**Are you currently working around this issue?**
Via ansible playbooks that wait until nodes come up -> configure -> reboot

**Comment by ashishkcs** [comment]
Is there any update on this support? @vfx1b

**Comment by martin31821** [comment]
@vfx1b can you share the workarounds youve described in your issue?

**Comment by rpocase** [comment]
This was fixed a couple months back. Please reference the [Ubuntu EKS docs](https://cloud-images.ubuntu.com/docs/aws/eks/) for an AMI in your region.
