### ISSUE TITLE
Support for Public IP space in VPC with EKS

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#181]
Ability to launch EKS clusters into a VPC that includes public IP space (non-RFC1918 addresses)

**Comment by kidanekal** [comment]
@tabern can you please expand/explain more about this task? I'm curious to know if this feature allows controlling the EKS k8s API endpoint DNS on a private mode. Currently, EKS private DNS is hidden from us and cannot be resolved outside of the VPC.

**Comment by tabern** [comment]
@kidanekal this is completely different. This feature allows you to define public IP space (non-[RFC1918 addresses](https://tools.ietf.org/html/rfc1918) such as 40.x) as part of the VPC for your Kubernetes worker nodes. Today, you must specify private IP space or the cluster creation will fail.

I think you are referring to the issue of DNS resolution to the Kubernetes endpoint when the private endpoint is enabled when using direct connect or a peered VPC: https://github.com/aws/containers-roadmap/issues/221

**Comment by ctyjrsy** [comment]
any updates on the ETA?

**Comment by tabern** [comment]
Coming soon 😀

**Comment by tabern** [comment]
This is now live! You can launch and run EKS clusters into AWS VPCs with non-RFC1918 addresss.

https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-adds-support-for-public-ip-addresses-within-cluster-v/
