### ISSUE TITLE
Control Plane Metrics Endpoint

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#182]
Prometheus metrics endpoint for EKS control plane API server

**Comment by tdmalone** [comment]
Hi @tabern, I'm interested in being able to get metrics from the control plane (was hoping to CloudWatch), but I haven't used Prometheus before. I'm thinking I might need to check it out, but, wondering if it's possible to add some more details here on what you're working on for k8s newbies like me?

**Comment by whereisaaron** [comment]
@tdmalone there is an EKS / Prometheus example you can try out here:
https://eksworkshop.com/monitoring/

**Comment by tabern** [comment]
This is live. You can see instructions for access the metrics endpoint in the EKS documentation: https://docs.aws.amazon.com/eks/latest/userguide/prometheus.html
