### ISSUE TITLE
[Fargate] [request]: cloudwatch metric for storage usage

### ISSUE THREAD

**Issue by lifeofguenter** [aws/containers-roadmap#183]
**Tell us about your request**
Cloudwatch metrics that returns the storage utilisation.

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Fargate limits the task storage to 10GB, additionally (on-top?) provides a 4GB volume. It would be great to create some type of monitoring on that to avoid fail-overs on production load.

Yes, its docker and should always be stateless. However, mishaps happen, for example not cleaning out tmp files.

**Are you currently working around this issue?**
Nope

**Additional context**

**Attachments**

**Comment by luis-farje-wcar** [comment]
Is this included on the roadmap? Is there "other" way to know the allocated space left of a container? metadata?

**Comment by debayandesarkar** [comment]
Hi,
We are facing space issue for several containers hosted on Fargate. This feature will greatly help in monitoring the allocated disk space for the containers. 

Regards
Debayan

**Comment by haarchri** [comment]
@debayandesarkar did you have an public example for this ?

**Comment by hampld** [comment]
Is there any chance this will be included in the roadmap?

**Comment by lifeofguenter** [comment]
Seems like this has just been released: https://aws.amazon.com/about-aws/whats-new/2022/11/aws-fargate-monitoring-storage-utilization/

Closing & thanks! :)
