### ISSUE TITLE
[EKS] [request]: New EKS Region: UAE

### ISSUE THREAD

**Issue by jeenadeepak** [aws/containers-roadmap#1833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support for EKS in UAE (me-central-1).

**Which service(s) is this request for?**
EKS

**Comment by jeenadeepak** [comment]
@mikestef9 : Do you have any ETA when EKS expected to be available in UAE region?

**Comment by bagelstrm** [comment]
Any ETA on when EKS is expected to be available in the UAE region?

**Comment by jeenadeepak** [comment]
@mikestef9 : Any ETA here?

**Comment by jeenadeepak** [comment]
Hi @mikestef9 : Kindly share update on this.

**Comment by jku8** [comment]
@jeenadeepak Completed
