### ISSUE TITLE
[EKS] [request]: snapshot-controller as add on

### ISSUE THREAD

**Issue by Jeinhaus** [aws/containers-roadmap#1838]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Are there any plans to include the [SnapshotController](https://kubernetes-csi.github.io/docs/snapshot-controller.html) in the ebs csi addon or do you plan another addon for that?
According to the [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html) you must install the snapshotter before installing the ebs csi driver.
This is not ideal when provisioning a cluster using IaC and having to install the snapshotter before the ebs csi driver addon.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I would like to provision an EKS cluster with addons without having to coordinate the dependencies between the ebs csi driver and the snapshot controller.

**Are you currently working around this issue?**

I'm currently installing the ebs csi driver and snapshotter as helm charts but would like to use the AWS provided add on.

**Comment by ConnorJC3** [comment]
Hi everyone, I am happy to announce the initial release of the CSI Snapshot Controller as an EKS Addon!

This addon is now available in all regions where EKS is offered, more information is available [at the AWS documentation for this addon](https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html).

**Comment by Hronom** [comment]
What the configuration parameters there? At lease how to select on what node it deployed?
