### ISSUE TITLE
[Request]: Provide option to add http_proxy and no_proxy settings to AWS-EBS-CSI-Driver Addon in EKS

### ISSUE THREAD

**Issue by kommipraneeth** [aws/containers-roadmap#1850]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Give the user an option to configure http_proxy and no_proxy values when installed aws-ebs-csi-0driver using EKS Addon functionality.

Similar to how we don it using helm chart 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L102

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Projects which have strict network connectivity like those of the public domains need a mechanism to expose proxy values to connect to the internet in a secure way.

**Are you currently working around this issue?**
We are mitigating this issue by installing the driver using helm chart which adding more code

**Additional context**
Error Message when no proxy config is provided 
`Warning   ProvisioningFailed       persistentvolumeclaim/storage-volume-1   failed to provision volume with StorageClass "ebs-sc": rpc error: code = DeadlineExceeded desc = context deadline exceeded`

**Comment by ConnorJC3** [comment]
Hi, this is now available in the latest version of the EBS CSI Driver addon (`v1.14.0-eksbuild.1`) via the new [Advanced Configuration](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/) feature for EKS Addons.

The configuration parameters are the same as the upstream equivalents (`proxy.http_proxy` and `proxy.no_proxy`) and should act identically.

**Comment by sriramranganathan** [comment]
Amazon EKS team recently announced the general availability of advanced configuration feature for managed add-ons. You can now pass in advanced configuration for cluster add-ons, enabling you to customize add-on properties not handled by default settings. Configuration can be applied to add-ons either during cluster creation or at any time after the cluster is created.

Using advanced configuration feature, you can now configure http_proxy and no_proxy properties for the Amazon EBS CSI driver starting version v1.14.0-eksbuild.1

To learn more about this feature, check out this blogpost - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

Check out the Amazon EKS documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html
