### ISSUE TITLE
[EKS] [Feature Request]: Support Network Policies on Calico add-on with VPC-CNI on IPv6 EKS Clusters

### ISSUE THREAD

**Issue by wilief** [aws/containers-roadmap#1871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please add support for the Network Policies to take effect when using Calico add-on to work alongside the VPC-CNI on IPv6 EKS Clusters.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am trying to add Network Policies to reject traffic that enters certain pods. Attempting this method due to Pod Security Groups not being supported for IPv6. The Applied Network Policies do not have any effect on IPv6. Used this guide "https://docs.aws.amazon.com/eks/latest/userguide/calico.html" to get set up and ran into issues getting policies to work. 

What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
I have not been able to work around this issue on IPv6, using IPv4 until a work around or solution on IPv6 is presented.

**Additional context**
There is an open issue with the Calico team regarding this functionality "https://github.com/projectcalico/calico/issues/5761"

**Comment by achevuru** [comment]
@wilief Are you using `NetworkPolicy` CRD to define your policies? or custom CRDs? Did you enable IPv6 support in Calico?

Please check for `ipv6Support` and related IPv6 config @  https://projectcalico.docs.tigera.io/reference/resources/felixconfig

**Comment by sjastis** [comment]
Closing as stale, please reopen if you are still seeing issues.
