### ISSUE TITLE
[ECS] [request]: Enable old parameters present in new console which are present in old console

### ISSUE THREAD

**Issue by lakshayJain2303** [aws/containers-roadmap#1872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add parameters private registry authentication, entrypoint override in the console while creating task definition using new console.

Also enable creating scheduled task from new console experience.

**Which service(s) is this request for?**
This could be Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently in order to leverage new functionality I have to use new console experience. But the new console experience does not have al the old parameters present which is there in old console. Hence this is forcing us to first use new console for new functionalities and then switch back to old console to add old functionalities.

**Are you currently working around this issue?**
First we are creating task definition using new console and adding OS as windows 2022, then we swithc back to old console and create a new task definition adding private registry authentication and entrypoint override.

**Comment by genbit** [comment]
@lakshayJain2303 Thanks for submitting your feedback. We are actively working on migrating the features to the new experience, and private registry authentication and entry point overrides are coming. As a workaround, now you can use JSON to create and update Task Definitions in new ECS Console.

And for others in the community: Please 👍 and share your feedback on what features are you missing the most?

**Comment by genbit** [comment]
You can now use the new console experience and edit private registry and entrypoint override parameters.
