### ISSUE TITLE
[EKS] [Feature request]: Container insights for Windows containers/ pods in EKS

### ISSUE THREAD

**Issue by keyan1603** [aws/containers-roadmap#1880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Container insights for Windows containers/ pods in EKS

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, we do not have this feature which is useful to get the logs and metrics using the CloudWatch agent which is available for only Linux containers/ pods. A new CloudWatch agent daemonset type for windows containers/ pods is required for this.

**Comment by chanpit-rakbank** [comment]
Any update on feature

**Comment by mikestef9** [comment]
https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-cloudwatch-container-insights-windows-containers-eks/
