### ISSUE TITLE
[EKS] [Fargate] [Bug]: EKS Fargate failed to create my pod

### ISSUE THREAD

**Issue by khacminh** [aws/containers-roadmap#1890]
Within the last 2 days, my fargate pods usually failed to start with the common issues:

- Pod provisioning timed out (will retry)
- failed to create containerd task
    ```txt
    message: 'failed to create containerd task: failed to create shim task: OCI
            runtime create failed: runc create failed: unable to start container process:
            error during container init: error setting cgroup config for procHooks process:
            failed to write "100000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/podxxx/cpu.cfs_quota_us:
            invalid argument: unknown'
    reason: StartError
    ```

There is no configuration update on my cluster and the fargate pods are can be scheduled sometimes

**Comment by mikestef9** [comment]
See the EKS Fargate [documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html#fargate-cpu-and-memory)

Specifically this content

> All Amazon EKS Fargate pods run with guaranteed priority, so the requested CPU and memory must be equal to the limit for all of the containers.

That error while not intuitive, means your pods do not have CPU and memory requests == limits.

**Comment by khacminh** [comment]
Hi @mikestef9 

No it's not. It's always equals. I run some of my services on Fargate since it was GA. There is no configuration update or service update on my cluster within the last several days. In the last a few hours, I suffered the error `Pod provisioning timed out (will retry)`, the fargate pods were stuck in Pending for about 3 hours, then could be scheduled after that without any update from my team.

Therefore I believe it is the issue from AWS. I'm so disappoint that instead of providing a clear explain or platform update announcement, you close this issue so quickly and deny the problem.

**Comment by mikestef9** [comment]
Apologies, then I'd recommend opening a ticket with AWS support - containers roadmap generally isn't best place to get help with this type of issue.

**Comment by khacminh** [comment]
Yeah, I did. But AWS really don't have a good channel to report problem/outage (unless you have to buy the support plan)
