### ISSUE TITLE
[EKS] [request]: Add support for marketplace eks addons to cluster created before 27/11/2022

### ISSUE THREAD

**Issue by marcincuber** [aws/containers-roadmap#1899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to deploy Kubecost EKS addon but my cluster was created before 27/11/2022. Only newly created EKS cluster can utilise Addons marketplace.

**Which service(s) is this request for?**
EKS

**Are you currently working around this issue?**
Deploying it with Flux + Helm

**Comment by mikestef9** [comment]
We are working on this, will update this issue when we have progress to share.

**Comment by marcincuber** [comment]
Looks like this is not supported on existing clusters. I managed to launch kubecost just fine.

**Comment by Vito-castai** [comment]
@marcincuber you could try CAST AI K8s cost monitoring. It's free and got no limits to the number of clusters you can connect, # of nodes and no limits to data retention.
