### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.17 on Enhanced Vulnerability Scans

### ISSUE THREAD

**Issue by rgoltz** [aws/containers-roadmap#1904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Using Vulnerability Scans with for latest Alpine release.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
At 22.11.2022, Alpine Linux 3.17 has been released (please see https://gallery.ecr.aws/docker/library/alpine and https://alpinelinux.org/posts/Alpine-3.17.0-released.html). 
We are using AWS ECR Enhanced (Image) Scanning to check for vulnerabilities.

Once you using the latest (= 3.17) image-tag of Alpine, you will get the following output in ECR:
```
No scan findings
Scan status: UNSUPPORTED_IMAGE
```

**Are you currently working around this issue?**
No workaround known. This repo have to use Vulnerability Scans using AWS ECR Enhanced (Image) Scanning.
Currently we have to skip Image Scanning.

**Additional context**
* Alpine SecDB also already added version 3.17, please see https://secdb.alpinelinux.org/v3.17/ (supporting vulnerability data)
* If we trying the same Alpine 3.17 image along with ECR Basic Scanning, there is no error. It seems that claircore now supporting new released within extra steps.

**Attachments**
* The same [issue](https://github.com/aws/containers-roadmap/issues/1766) happend with Enhanced Scanning, once Alpine release  3.16 came up.

**Comment by cnocula-peg** [comment]
@aws team:

Will this continue like that for the AWS ECR / Enahced scanning, that the community constantly needs to raise a feature request everytime a new operating system version is available?
This kind of defies the purpose of such a scanner to be able to react quickly on CVEs.

**Comment by heidemn-faro** [comment]
@aws team: Please note that the latest version of the `node:18-alpine` image is now based on Alpine 3.17.
* Node 18 is the current LTS version, so it's what everybody should use.
* Alpine is probably the most used image variant, since much smaller.

**Comment by cnocula-peg** [comment]
> @aws team:
> 
> Will this continue like that for the AWS ECR / Enhanced scanning, that the community constantly needs to raise a feature request everytime a new operating system version is available? (I had to request support for Alpine 3.16 already) This kind of defies the purpose of such a scanner to be able to react quickly on CVEs.

@hou-yimin please kindly take some action here. We are using the enhanced ECR scanning in production in automated quality gates. 
Yes -  to be fair -  the documentation at https://docs.aws.amazon.com/inspector/latest/user/supported.html indicates exactly the supported versions. But if critical/urgent CVEs are addressed in new OS versions it does not make sense for me to have to wait weeks / months for the ECR to catch up (Alpine 3.17 was released on 22.11.2022).

**Comment by hou-yimin** [comment]
Thanks for the feedback. We have shared this request/question with the Inspector team and learned Inspector plans to support Alpine 3.17 by mid-Feb, 2023.

**Comment by roded** [comment]
Are there any plans for reducing the time between future Alpine releases and subsequent Inspector support?

We cannot release a version of our product without a CVE report, and 3 months will prevent us from using Inspector.
 
Thank you.

**Comment by hou-yimin** [comment]
Update: Inspector support for Alpine 3.17 is live.

**Comment by rgoltz** [comment]
> Update: Inspector support for Alpine 3.17 is live.

![image](https://user-images.githubusercontent.com/16392819/210622603-84e99f62-6aaa-4c75-b473-08c8f6f2b747.png)
Confirmed - Scan of Alpine 3.17/latest via ECR Enhanced Scanner in eu-central-1 is working. 🚀

**Comment by hou-yimin** [comment]
Fantastic. Can we close this issue, if no other questions?

**Comment by rgoltz** [comment]
@hou-yimin - Should we split this partof the discussion/question:
> And I am following up with the Inspector team about the wait to support new Alpine releases.

to a new/separate issue or follow here for now?

**Comment by hou-yimin** [comment]
Just heard back from Inspector team about the wait time to support new OS: Inspector actively monitors OS releases and add support based on customer demand. Best to provide feedback directly to Inspector is to email them at inspector-feedback@amazon.com.

**Comment by hou-yimin** [comment]
I opened a new issue to request faster support for new OS versions on Enhanced Scanning. Please plus one [here](https://github.com/aws/containers-roadmap/issues/1959) if interested.
