### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.17 on Vulnerability Scans

### ISSUE THREAD

**Issue by LostGladiator0** [aws/containers-roadmap#1905]
Tell us about your request
What do you want us to build?

Which service(s) is this request for?
ECR

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

 22.11.2022, Alpine Linux 3.17 has been released (please see https://alpinelinux.org/posts/Alpine-3.17.0-released.html). We are using AWS ECR Basic (Image) Scanning to check for vulnerabilities.

AWS ECR Basic + Advanced (Image) Scanning should handle & support Alpine Linux 3.17

Are you currently working around this issue?
We might need to skip the Vulnerability Scans using AWS ECR Advanced (Image) Scanning in case of the ECR returning UnsupportedImageError: The operating system 'alpine' version 'v3.17' is not supported. There is no further workaround known while using AWS ECR Basic (Image) Scanning.

Additional context
Alpine SecDB also already added version 3.17, please see https://secdb.alpinelinux.org/v3.17

Attachments

**Comment by matejkloska** [comment]
Duplicate, former issue: https://github.com/aws/containers-roadmap/issues/1904

**Comment by adrianosela** [comment]
This issue can be closed. It is now 3.18 which we need support for :D

**Comment by bradg-aws** [comment]
Thanks for raising this. Alpine 3.17 and 3.18 are now both supported.
