### ISSUE TITLE
Feature request: per-container Target Group registration

### ISSUE THREAD

**Issue by jeffb-stell** [aws/containers-roadmap#191]
### Summary
ECS services comprised of multiple complementary microservices would benefit from the ability to register individual containers with Target Groups.

ECS currently only provides for service-level registration with a single TargetGroup. This registration and subsequent health checks are used as a determination of whether an ECS service is healthy.

For ECS services comprised of multiple containers that should be accessed via a single endpoint (for example https://microservice/ where containers are accessed under https://microservice/foo, https://microservice/bar, https://microservice/baz) there is no capability provided by the ECS agent for registration/deregistration with Target Groups used in ELBv2 Listener Rules. A workaround is to run a reverse proxy routing container within each task, which is wasteful and not necessary from an architecture standpoint

I request that an additional (optional) attribute be added to http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html in the conatinerDefinition, such as targetGroup, allowing a list of target groups to register the container with. At task launch time, the ECS agent should iterate over a task's container definitions for target groups, and register with the appropriate instance ID/port tuplet. At task stop time, the ECS agent should handle deregistration as is currently done.

**Comment by coultn** [comment]
This capability launched recently: https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecs-services-now-support-multiple-load-balancer-target-groups/
