### ISSUE TITLE
[EKS] [request]: Support for Kubernetes v1.26

### ISSUE THREAD

**Issue by stevehipwell** [aws/containers-roadmap#1914]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like EKS support for Kubernetes v1.26.

In preparation for this I'd like to see EKS v1.26 added to the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar); I think all pending upstream Kubernetes releases should be added to the calendar when they're released, even if the due date is initially only accurate to a quarter (this is the same request I made in #1817).

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to use Kubernetes v1.265 from EKS and be able to plan when this is likely to happen.

**Are you currently working around this issue?**
n/a

**Additional context**
- [Release blog](https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/)
- [Sysdig blog](https://sysdig.com/blog/kubernetes-1-26-whats-new/)
- [Aqua blog](https://blog.aquasec.com/kubernetes-version-1.26-an-overview)
- [ARMO blog](https://www.armosec.io/blog/kubernetes-1-26-everything-you-should-know/)

**Attachments**
n/a

**Comment by mbevc1** [comment]
Nice one with 1.25 out of the door, so this can be started now! :rocket:

**Comment by mbevc1** [comment]
Would it be possible to add something ot the calendar and give indication of a v1.26 release timeline?

**Comment by stevehipwell** [comment]
> Would it be possible to add something ot the calendar and give indication of a v1.26 release timeline? 

@mbevc1 I put this in the new release issue each time but it's yet to happen. I'd like to see each new version in the calendar at release even if just with a TBC release date.

CC @dims

**Comment by dims** [comment]
cc @vipin-mohan

**Comment by aavileli** [comment]
seems eks 1.26 has landed, docs do not seem to be updated but console shows the option interesting.

**Comment by stevehipwell** [comment]
The [docs](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.26) have been updated and the RSS says there is a [release announcement blog post](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/) but the blog post is returning a 404.

**Comment by stevehipwell** [comment]
The what's new [announcement](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-eks-distro-kubernetes-version-1-26/) also has the blok link throwing a 404.

**Comment by dims** [comment]
should be back up now @stevehipwell

**Comment by stevehipwell** [comment]
Thanks @dims, I was just about to say the same thing.

**Comment by amedirr** [comment]
Amazon EKS now supports Kubernetes 1.26 please see these posts to learn more:
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/
https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-eks-distro-kubernetes-version-1-26/
