### ISSUE TITLE
[kubecost] [request]: support of EKS optimized ARM64 for kubecost marketplace addon 

### ISSUE THREAD

**Issue by rajprafull** [aws/containers-roadmap#1920]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
kubecost addon currently is not installable for anyone running ARM worker nodes in their EKS environment. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We recently deployed the Kubecost marketplace addon into one of our EKS clusters.

The addon failed to start successfully with the following error in th epod logs:
exec /go/bin/app: exec format error

This is because the container image used for the kubecost marketplace addon apparently does not support ARM worker nodes and is not a multiarch container image.

Additionally, the deployment does not seem to have any taints/tolerations specificed that prevents it from trying to start on ARM nodes. 

**Are you currently working around this issue?**
yes

**Additional context**
The resolution is 2 fold:
- Building multiarch images. The upstream Kubecost project already does this so its quite a surprise that an official AWS marketplace addon does not
- Setting taints/tolerations in the addon deployment to prevent kubernetes from trying to schedule an intel only container to an arm node. This should be standard whenever an image is not multiarch.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
We are working on this, Arm compatible version will be available soon

**Comment by sriramranganathan** [comment]
A new version of the Kubecost addon (v1.99.0-eksbuild.0) is now available through Amazon EKS. This new version also supports ARM64 based nodes.
