### ISSUE TITLE
[ECS] [Health Check grace period update on new console]: This is a feature request to support updating Health Check grace period update on the new console

### ISSUE THREAD

**Issue by amisfari** [aws/containers-roadmap#1938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
While updating an ECS service with the new ECS console, there is no option to edit the Health check grace period. 
Updating health check grace period is always possible by using the aws CLI. However, we would like to be able to update this parameter using the console as well.
PS: in the old console, it was possible to do so.

**Which service(s) is this request for?**
ECS

**Are you currently working around this issue?**
Currently, we have to use the old console.

**Comment by genbit** [comment]
You can now edit service health check grace period in update service page, under load balancing section.
