### ISSUE TITLE
Port mappings: add support of port ranges

### ISSUE THREAD

**Issue by tuusberg** [aws/containers-roadmap#194]
Hi there!

Some applications do require wide range of open ports and the only option we have at the moment is to set them explicitly (e.g. one by one) when defining tasks.

I think that it would be useful to allow use of port ranges, like

```
{
          "hostPorts": 3000-3025,
          "containerPorts": 3000-3025,
          "protocol": "tcp"
}
```

Also, I've noticed that ecs-agent throws an error if there is > 100 ports specified in task definition, regardless of port numbers: 

```
 Run tasks failed
 Reasons : RESOURCE:PORTS
```

Please advice.

**Comment by houey** [comment]
> > Obviously in your security group you still need to allow the dynamic range you use, but here you can use a range.

Does this mean we can specify a narrower range of ports in the Security Group?  is there a setting to match the dynamic port range to the Security group port range... IE we dont need 20,000 ports as a possibility.

**Comment by kerryjj** [comment]
+1

Erlang node clustering. Ports 4369 and the range 9100 - 9155 are the default.

**Comment by ccapndave** [comment]
+1

**Comment by kazz187** [comment]
+1

**Comment by bramevo** [comment]
+1 (FTP)

**Comment by asandeep** [comment]
+1 

Running dask worker with `--nprocs > 1` assigns multiple ports that can be controlled by specifying a range i.e. `--worker-port 9000:9100`. 

Currently it requires to add all the ports individually.

**Comment by luis02lopez** [comment]
+1 as per PCI DSS requirements of not having that huge amount of open ports.

**Comment by mmoallemi99** [comment]
> Confirmed that using `NetworkMode`: `host` instead of `bridge` does not require you to explicitly expose ports. Rather, all traffic to the host is directly mapped to the same port on the container. We've successfully run an RTP proxy for WebRTC inside ECS.

In Fargate only `awsvpc` network mode is accepted and I'm also struggling with port range specification for a WebRTC application.

**Comment by hyavari** [comment]
+1
Required for RTP protocol.

**Comment by ogonzalez-sd** [comment]
We're using fargate to house a TURN (rfc5766) server and this would really be helpful!

**Comment by shlomisas** [comment]
+1

**Comment by webpolis** [comment]
> In Fargate only `awsvpc` network mode is accepted and I'm also struggling with port range specification for a WebRTC application.

what was your solution @mmoallemi99 ?

**Comment by mmoallemi99** [comment]
> > In Fargate only `awsvpc` network mode is accepted and I'm also struggling with port range specification for a WebRTC application.
> 
> what was your solution @mmoallemi99 ?
> 
> I'm trying to find if there's a way to support WebRTC using ECS FARGATE.
> 
> The ICE negotiation works great (tested using [this tool](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)) both outside or inside a container, but I am still unable to establish communication from outside with a peer located inside a container. All Security Groups and Network ACLs currently allow TCP/UDP traffic for WebRTC interaction.

I remember taking care of it with Terraform range function, pragmatically generating static port values in the end.

**Comment by httpiga** [comment]
Any update about this?

**Comment by vibhav-ag** [comment]
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ecs-supports-container-port-ranges-port-mapping/
