### ISSUE TITLE
[EKS]: Upgrade readiness (pre flight) checks

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#1946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like EKS to surface potential cluster upgrade impacting issues to address before upgrading. This is sometimes referred to as pre flight checks. 

Examples include but are not limited to:
- Usage of deprecated Kubernetes APIs
- EKS cluster health issues like lack of free IP addresses in subnet required for upgrade
- Versions of worker node kubelets beyond the supported Kubernetes version skew [policy](https://kubernetes.io/releases/version-skew-policy/)
- Checking for compliance with many EKS specific changes covered in EKS version release [notes](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html), for example
    * Usage of Dockershim
    * Installation of EBS CSI driver
    * Service account token expiration
    * Certificate signing request compliance
- Missing application best practices for Kubernetes upgrades, such as lack of pod disruption budgets, liveness/readiness probes, use of “[naked](https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs)” pods (pods not tied to replication controller)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Kubernetes is a fast-paced, evolving open source project with 3 releases per year, each releasing consisting of thousands of changes contributed by a large open source community. 

When making the decision to adopt Kubernetes, having a plan to keep up with Kubernetes versions is a critical component to ensure [security](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation). While EKS provides an API for upgrades to the next Kubernetes version, it is a shared responsibility, and there is time consuming validation work users need to perform to make sure software deployed in their cluster works with newer versions of Kubernetes. Changes across versions can include EKS behavior changes, Kubernetes API deprecations/removals, and Kubernetes features/bug fixes. 

**Are you currently working around this issue?**
Spending lots of time with detailed reading of EKS and upstream Kubernetes release notes, using 3rd party tools to check usage of deprecated Kubernetes API versions.

**Additional context**
Some questions we have as start exploring this feature:
- Would you want EKS to block a cluster upgrade if we detect any issues we believe will have application impact? (potentially with a force flag to override if desired)
- Would you expect to only get a report of upgrade readiness when you call the cluster upgrade API? Or would you want to see a report at any time available through an API, for example that you could see in the EKS Console, before having to call the upgrade API?
- Any other upgrade readiness checks you would like EKS to include?
- Are there any post upgrade checks you perform?
- Would you like to EKS expose hooks so you could add custom checks? If so, what are examples of custom upgrade checks you perform?

**Comment by mikestef9** [comment]
Yes that's basically answering my question above

> Would you expect to only get a report of upgrade readiness when you call the cluster upgrade API? Or would you want to see a report at any time available through an API, for example that you could see in the EKS Console, before having to call the upgrade API?

So in your case, you'd expect to see this report snapshot at any time, not just only get feedback when you call update version API.

**Comment by RichiCoder1** [comment]
Yah, the ability to get warned during an update, but then be able to re-validate without kicking of a full update again would be nice.

**Comment by stevehipwell** [comment]
> So in your case, you'd expect to see this report snapshot at any time, not just only get feedback when you call update version API.

I'd like to get some sort of warning whenever a deprecated API was used, not just a warning about something that would be removed in the next release. These alerts could be used for update readiness but they could also be used for other use cases (e.g. compliance with policy).

**Comment by mikestef9** [comment]
Makes sense. Would also be interested in your feedback in #1949 that was just opened.

**Comment by mikestef9** [comment]
https://aws.amazon.com/blogs/containers/accelerate-the-testing-and-verification-of-amazon-eks-upgrades-with-upgrade-insights/

As mentioned in the blog, upgrade insights will expand over time to include additional types of upgrade related checks.
