### ISSUE TITLE
EKS [request]: Support cgroup v2

### ISSUE THREAD

**Issue by stevehipwell** [aws/containers-roadmap#1953]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to run EKS using cgroup v2, I think this would require the following steps.

- Confirm cgroup v2 works with EKS
- Add cgroup v2 to official AWS EKS AMIs (AL2 & bottlerocket)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like all of the benefits which [cgroup v2](https://kubernetes.io/docs/concepts/architecture/cgroups/) provides for Kubernetes; or at least be able to start testing it.

**Are you currently working around this issue?**
n/a

**Additional context**
n/a

**Attachments**
n/a

**Comment by dims** [comment]
xref: https://github.com/awslabs/amazon-eks-ami/issues/824

**Comment by stevehipwell** [comment]
xref: https://github.com/bottlerocket-os/bottlerocket/issues/2843

**Comment by stewartsmith** [comment]
for Amazon Linux based AMIs such as the EKS Optimized AMI, this will be part of moving to Amazon Linux 2023, and isn't something that should be attempted on Amazon Linux 2.

**Comment by markusboehme** [comment]
Bottlerocket has been supporting cgroup v2 since release v1.13.0. The variants aws-k8s-1.26, aws-k8s-1.27, as well as future Kubernetes variants default to using cgroup v2. (See https://github.com/bottlerocket-os/bottlerocket/discussions/2874)

**Comment by mikestef9** [comment]
Closing as EKS now supports cgroup v2 with the launch of AL2023 based AMIs.

**Comment by hjkatz** [comment]
@mikestef9 Could you point us to the docs on the new AMIs for use in EKS specifically please?
