### ISSUE TITLE
[EKS] [request]: Support configuration to add tolerations and affinity to eks addons.

### ISSUE THREAD

**Issue by Sharath456p** [aws/containers-roadmap#1955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

eks addon configurations does not support for all helm values in their json schema.

1.coredns addon : Both tolerations and affinity not supported.
2.aws-ebs-csi-driver addon : Tolerations are supported but not affinity

What do you want us to build?

we are trying to  add custom configuration values like tolerations and affinity to the eks addons like coredns and aws-ebs-csi-driver through terraform. Getting InvalidParameterException because these values are not supported in their respective json schema
![image](https://user-images.githubusercontent.com/95084540/217748286-825bb9d7-ef5a-4dc8-a215-ba8396a22aa5.png)

![image](https://user-images.githubusercontent.com/95084540/217748470-feba2489-a454-461f-84a7-c4f36b3fc5ad.png)

**Which service(s) is this request for?**
This could be EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by ConnorJC3** [comment]
Hi! On the EBS CSI Driver side, the latest release of the EKS-managed version of the driver (`v1.16.0-eksbuild.1`) now supports specifying affinity! The parameters are the same as the upstream helm chart (`node.affinity` and `controller.affinity`) and should work identically.

**Comment by fernandezcuesta** [comment]
What about coreDNS? IMHO it's quite contradictory to allow nodeSelector without tolerations,

**Comment by gp42** [comment]
Can we have some priority for this please? No support for specifying `tolerations` is a blocker for migrating to Addons and AWS pages ([this](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html#coredns-add-on-self-managed-update) and [this](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)) state that instructions for self-managed addons will be removed on July 1st 2023! 😱

**Comment by vadlungu** [comment]
we also need `tolerations` feature, could you please urgent this ?

**Comment by hhannani** [comment]
same here, we have some tolerations in core-dns that I can't push from Add-ons console.

**Comment by ivankatliarchuk** [comment]
Is anyone aware of how to set/update annotations and labels?

**Comment by itssimon** [comment]
We also need this for CoreDNS. Can this please be prioritised?

**Comment by fernandezcuesta** [comment]
should be on the way as commented [here](https://github.com/aws/containers-roadmap/issues/1930)

**Comment by sjastis** [comment]
With coreDNS v1.9.3-eksbuild.3, you can configure toleration and affinity for coreDNS pods

**Comment by mgnrby** [comment]
> With coreDNS v1.9.3-eksbuild.3, you can configure toleration and affinity for coreDNS pods

thanks! working now.

**Comment by sjastis** [comment]
Support starting with  -
EBS CSI Driver : v1.16.0-eksbuild.1
CoreDNS EKS Addon :  v1.9.3-eksbuild.3

**Comment by ForbiddenEra** [comment]
> Support starting with - EBS CSI Driver : v1.16.0-eksbuild.1 CoreDNS EKS Addon : v1.9.3-eksbuild.3

What about VPC-CNI?

I see `Affinity` under definitions but it's just..

```
    "Affinity": {
      "type": [
        "object",
        "null"
      ]
    },
```

**Comment by skumsi** [comment]
Similar to 'aws-ebs-csi-driver' is there a plan to add more customization options to 'aws-efs-csi-driver' add-on also? We want to add affinities to the deployment and the current schema doesn't allow us to do so.
