### ISSUE TITLE
[ECS] [request]: Add an ability to change the timeout time of ECS ServiceConnect

### ISSUE THREAD

**Issue by Seiya6329** [aws/containers-roadmap#1958]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Could you add an abililty to change the timeout value of ECS ServiceConnect like the App Mesh?
To my understanding, ECS ServiceConnect does not have that feature.
In addintion, I confirmed that the upstream request was stopped after 15 seconds which are default limit of Envoy timeout.[1][2]

[1]
```
"request": {
"protocol": "http",
"method": "GET",
"path": "/",
"querystring": "size=1000-2000&sleep=9000-10000&status=200",
"header": {
  "Accept": "*/*",
  "Host": "gelbo-80-tcp",
  "User-Agent": "curl/7.74.0",
  "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
  "X-Forwarded-Proto": "http",
  "X-Request-Id": "62ebccc2-7dd5-4de1-9234-1dff3a45f160"
},
```
[2] HTTP route components (proto) — envoy 1.26.0-dev-a9eb13 documentation
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout

```
timeout
    (Duration) Specifies the upstream timeout for the route. If not specified, the default is 15s.
```

**Which service(s) is this request for?**
ECS Service Connect

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Needing an ability to control the timeout on Envoy

**Are you currently working around this issue?**
N/A
**Additional context**
N/A
**Attachments**
N/A

**Comment by joe-mutti** [comment]
2 months and still no progress :(

**Comment by manjunsd** [comment]
Received a use-cases to allow increasing "x-envoy-expected-rq-timeout-ms" via support. Cx need the timeout to be longer than 15 Secs to prevent the connection from being pulled prematurely.

**Comment by aaronsmithtv** [comment]
I asked AWS support and got this response:

>Unfortunately, with the existing ServiceConnectConfiguration parameter we do not have have an option to override the default envoy timeout value, please refer [a]. However I could see that there is an open feature request [b] in our AWS container roadmap to provide ability to update this default timeout value and I have added my vote on behalf of you. 

>Unfortunately, I will not be able to provide an ETA on when this feature will be released. In the meantime it is best to keep an eye on the feature request [b] and add your voice in this feature request. You can also follow What’s New Page [c] and AWS Blogs [d] to know more about the future releases.

>Reference:
[a] : https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectConfiguration.html 
[b] : https://github.com/aws/containers-roadmap/issues/1958
[c] : https://aws.amazon.com/new/?whats-new-content-all.sort-by=item.additionalFields.postDateTime&whats-new-content-all.sort-order=desc&awsf.whats-new-categories=*all
[d] : https://aws.amazon.com/blogs/aws/

Looks like no ETA on the issue for now

**Comment by zhaohaom-aws** [comment]
We are working on the design right now and will provide ETA soon.

**Comment by 93910676wangd** [comment]
I want the latest information.

ETA or serviceconnect timeout (default) to increase to 15 seconds or more.

thanks

**Comment by francesco-avola-enginius** [comment]
Need an ETA as soon as possible. Please update

**Comment by herrhound** [comment]
We can not provide an ETA on when this feature will be released. Please add your vote and keep an eye on this feature request and we will post updates as soon as we have them.

**Comment by varunchillara27** [comment]
@herrhound Was disappointed seeing this issue after spending significant time on a huge monolith implementation effort. Appreciate the teams ongoing effort addressing this. In the interim, is there any workaround that you would suggest looking into?

**Comment by herrhound** [comment]
@varunchillara27 - it really depends on your use case. I'd like to learn about the requests that take longer than 15 seconds in your case, and what level of timeout customization you'd expect.

**Comment by varunchillara27** [comment]
> 

@herrhoundMultiple services invoked per API call, including OpenSearch, Redshift, and PostgreSQL connections, contribute to request durations exceeding 15 seconds. Service-to-service data retrieval from Redshift and transfer to S3 introduces additional delays. Optimizations, such as connection pooling, caching, and streamlining data transfer, will be taken care of, but the limit needs to be increased in first place for all of the above to be implemented.

**Comment by francesco-avola-enginius** [comment]
In the meanwhile the work to enable customization of this timeout is in progress, would be very helpful a flat increasing of this value for everybody (e.g 30 or 60 seconds). Also considering that this disruptive limitation is not clearly mentioned in any ECS documentation I was able to find.

**Comment by Seiya6329** [comment]
@francesco-avola-enginius
We apologize that this limitation was not clearly mentioned in the ECS documents. I have shared this feedback with my team.

**Comment by patricksculley** [comment]
Just completed migration to ECS and now finding out about this issue in production with real workloads.
This is a major problem/showstopper for real applications while they are under load and I don't see any good workaround.
Other than implementing asynchronous flows or an ALB, does anyone know a solution here? 
REST requests and timeouts seem fundamental to ServiceConnect :)

**Comment by patricksculley** [comment]
> > Just completed migration to ECS and now finding out about this issue in production with real workloads. This is a major problem/showstopper for real applications while they are under load and I don't see any good workaround. Other than implementing asynchronous flows or an ALB, does anyone know a solution here? REST requests and timeouts seem fundamental to ServiceConnect :)
> 
> @patricksculley Had to make a hard and quick pivot to Service Discovery. Only after doing so I realized how easy and straightforward setting up ServiceConnect was. Kudos to the team for this amazing feature, hopefully this is resolved soon

Thank you for the suggestion, @varunchillara27. Yes, ServiceConnect was absurdly easy to setup and provides super-power capabilities. It's even working for my UDP and non-HTTP connections.

For my use case, I think I will go with a long-polling strategy that kicks off whenever the Gateway Timeout Exception is thrown (luckily I can amend both the client and the service with an additional endpoint). That should be fairly easy to unwind once there is a supported solution in place.

**Comment by akil-rails** [comment]
We have a production cutover planned in July, would be great to understand if there's any ETA, or we should move out of Service Connect - the timeout of 15 secs needs an increase for us well

**Comment by Taikono-Himazin** [comment]
i need this too.
Because of this, the timeout is forced to 15 seconds for all requests executed on ECS, which I think is a big obstacle in migrating traditional (non-async) web services.
Anything updated with information?

**Comment by Taikono-Himazin** [comment]
@Seiya6329 
https://github.com/aws/containers-roadmap/issues/1958#issuecomment-1584831215
Has the statement been corrected?
What document is it in?
If you don't mind, could you give me the URL?

**Comment by Seiya6329** [comment]
@Taikono-Himazin 
Our team is actively reviewing our AWS doc and working on this improvements.
We apologize for the inconvenience and we really appreciate your understanding.

I will update this thread with the status on AWS doc review closer to end of this Month.

**Comment by Mendes11** [comment]
@Seiya6329 I have two services in ECS, that are communicating through ServiceConnect (a backend and a frontend).

My frontend is behind an LB and for long-running requests, I'm seeing that after 15s the connection is dropped and a 504 is returned.

Is what I'm experiencing related to this issue?

**Comment by Seiya6329** [comment]
Hello @Mendes11 ,
Yes, that behavior does look like related with the timeout limitation.

**Comment by emma-qt** [comment]
We ran into this issue and had a bit of a headache tracing it back to ServiceConnect. Better documentation that there is a default, unchangeable timeout of 15 seconds would be a great starting point - we'll switch to Service Discovery for now, but would love to see making this configurable prioritised!

For anyone else investigating mysterious `HTTP 504` errors/`upstream request timeout` on ECS, I'd strongly recommend reading this thread and turning off ServiceConnect. 

Commenting for reach and searchability in case others face this problem.

**Comment by Seiya6329** [comment]
AWS doc update is going through a final review. I will add a link to the revised AWS doc once the change is being published.

**Comment by akil-rails** [comment]
Curious to know - is this update to clarify in the docs that there's a hard limit of 15 secs, or is there a change to make this timeout configurable?

**Comment by Seiya6329** [comment]
@akil-rails - My [previous comment](https://github.com/aws/containers-roadmap/issues/1958#issuecomment-1624175177) is referring to AWS doc update only.

**Comment by kurevin** [comment]
Also why and how this timeout is enforced for EXTERNAL connections from ALB too?

Just enabling the Service Connect checkbox enforces 15 seconds timeout on all incoming connections to this service, not just via SC. Service Connect right now works like a "cripple this service" checkbox -_-

**Comment by Seiya6329** [comment]
@kurevin - Thanks for sharing your experience. We are looking into this and will respond in timely manner.

**Comment by vaietc** [comment]
@kurevin that is a good call out and we'll keep that in mind as well as we design the configurable timeout property for Service Connect. In the meantime, you are able to have the ALB traffic 'bypass' the Service connect agent by setting a different port for the Service Connect Agent (ingressPortOverride defined [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectService.html)) which will allow non-Service Connect traffic (like Load balancer traffic) to not be intercepted by the Service Connect Agent.. this in turn will ensure your existing clients using load balancers are not limited to the 15 second timeout.

**Comment by akil-rails** [comment]
> @kurevin that is a good call out and we'll keep that in mind as well as we design the configurable timeout property for Service Connect. In the meantime, you are able to have the ALB traffic 'bypass' the Service connect agent by setting a different port for the Service Connect Agent (ingressPortOverride defined [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectService.html)) which will allow non-Service Connect traffic (like Load balancer traffic) to not be intercepted by the Service Connect Agent.. this in turn will ensure your existing clients using load balancers are not limited to the 15 second timeout.

Is **ingressPortOverride** available via the CDK ?

**Comment by vaietc** [comment]
> Is **ingressPortOverride** available via the CDK ?

Yes, documented [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ServiceConnectService.html)

**Comment by brafales** [comment]
We've unfortunately hit this wall as well. We carefully planned and designed a system that used Service Connect when it was released only to find out recently about this non-configurable timeout.

The fact that this was not documented until late July has really let us down, as we have now spent a significant amount of time implementing a solution which is not fit for purpose.

Any updates on whether being able to configure this timeout is on the roadmap at all?

**Comment by Seiya6329** [comment]
To all customers,

Thank you very much for your patience and we understand this timeout issue is causing multiple pains. Our team has picked up this task and actively working on implementing a solution.

We keep everyone posted with next update in this thread.

**Comment by lovababu** [comment]
++1 eagerly waiting for it. Thanks

**Comment by jy-zheng** [comment]
I am new to AWS, not sure if the problem I am facing now is related this. After days of troubleshooting, couldn't found any solution for this.

I setup a NGINX with ALB in a ECS, the NGINX service connect to the application service with Service Connect . I got code `503` randomly, `upstream connect error or disconnect/reset before headers. reset reason: connection failure`. 

I can see the request with `503` code in the NGINX service log, but not in application service.  The request was never send to the application service.

**Comment by xvector-dev** [comment]
Eagerly waiting for timeout issue to be sorted cause service connect is definitely the way to go when working with ECS.

**Comment by dlopezb93** [comment]
+1 waiting this feature! any news about it ?

**Comment by shivangi231** [comment]
Hi all, 

Thank you for your patience regarding this feature. Our team is actively working on implementing a solution for it.

**Comment by edorio** [comment]
Hi, Do you know an estimated date for the feature?

Thanks

**Comment by jwang186** [comment]
The ETA is 11/13/2023.

**Comment by egemen-touchstay** [comment]
+1 Waiting for an ETA, at least it would be good to know if it will be done by this year, because the issue opened in February

Thanks

**Comment by starbirdtech383** [comment]
This is turning out to be go/nogo call for us using ecs in our solution. Is there a workaround to achieve this ie increase timeout ?

**Comment by o1lab** [comment]
@zhaohaom-aws @Seiya6329 & AWS team: could you pls share a _really rough_ estimate time for this : weeks, months, quarters. This will help our planning.

**Comment by herrhound** [comment]
@starbirdtech383 – unfortunately, we cannot provide time estimates for unreleased features. I can tell you that the engineering team is close to the finish line with this release.

**Comment by j-d-b** [comment]
Hello, it is great to see activity here and like many others I am looking forward to the feature.

I want to add my experience that brought me here in case it helps others with troubleshooting. 

In our deployment in which one service connects to another that is hosting a gRPC service, we were seeing server-streaming requests failing with gRPC status code "Unavailable" and error detail "upstream request timeout". These were long-running, infinite streams used as real-time notifications which the ServiceConnect Envoy server timeout was causing to fail.

**Comment by romoore** [comment]
> Also why and how this timeout is enforced for EXTERNAL connections from ALB too?
> 
> Just enabling the Service Connect checkbox enforces 15 seconds timeout on all incoming connections to this service, not just via SC. Service Connect right now works like a "cripple this service" checkbox -_-

Happened to us as well. Spent a day trying to debug where the 15-second limit was imposed and found this comment. Disabled Service Connect (we weren't using it) and now our long-lived requests survive.

**Comment by bmariesan** [comment]
@herrhound I would also like to ask for a ball-park estimate, we really want to use Service Connect with ECS however due to the hardcoded timeout it forced us to rollback after having an incident in production. If not delivery timeline can be provided, do you  guys at least have a Alpha/Beta project for Service Connect that we can opt into?

**Comment by kevinh-autoserve1** [comment]
This is an absolutely crippling setting affecting production workloads. It's really disappointing seeing how long this is taking to get resolved. Time to move off ECS.

**Comment by FabianNet** [comment]
Any idea if a variable timeout > 15 sec is being worked on? This is a real show stopper for us unfortunately.

**Comment by jczyzyk** [comment]
Could you please provide an update on the current status of this task? According to feedback from others, this situation is causing some impediments on our end as well. It would be greatly appreciated if you could share some insights into the expected timeline. This information will help us assess whether we should continue to wait or consider exploring alternative solutions. 
Thank you for your attention to this matter.

**Comment by shivangi231** [comment]
@jczyzyk : Thank you for your patience. We understand that this timeout issue is causing multiple pains. Although we cannot provide an exact timeline, let me assure you that we are very close to the finish line on this feature.

**Comment by tusharvaswanicoder** [comment]
Just found this issue yesterday I was getting 504 timeout. Now seeing this github issue's wonderful progress taking them almost one year on this very basic feature request just makes me feel that choosing ECS was the worst mistake :slightly_smiling_face:

**Comment by bmariesan** [comment]
@shivangi231 another month has passed and we still don't have a timeline for this, could you again if possible give us a ball park estimate if this might hit Q1 or Q2 this year? if not we really need to think about doing something else because we can't keep waiting for it

**Comment by shivangi231** [comment]
@bmariesan - Thank you for your patience. At the moment, I can tell you that we are very close to releasing this feature for our customers.

**Comment by romoore** [comment]
> @bmariesan - Thank you for your patience. At the moment, I can tell you that we are very close to releasing this feature for our customers.

Excellent news! Does that mean 2024Q1, 2024Q2, 2024H2? Something else?

**Comment by shivangi231** [comment]
We're happy to announce that we have successfully launched this long-awaited feature!!! Thanks for your patience everyone. Please refer our What's new post for more details - https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-configurable-timeout-service-connect/

**Comment by fabianKnobloch** [comment]
great stuff !
Has anyone an idea if this is already mapped to Terraform?

**Comment by cuotos** [comment]
> you are able to have the ALB traffic 'bypass' the Service connect agent by setting a different port for the Service Connect Agent (ingressPortOverride defined [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectService.html)) which will allow non-Service Connect traffic (like Load balancer traffic) to not be intercepted by the Service Connect Agent

@vaietc Please can you confirm if this is documented. We just experienced an outage due to the fact that the ALB will use Service Connect to talk to and ECS container, even if there is no mention in ALB to use this.

We have a service listening on port 8000 and an ALB that routes traffic to it, as soon as SC was enabled, the traffic would appear to come from localhost and not the ALBs IP. This needs to be documented

**Comment by vaietc** [comment]
Thanks for the feedback @cuotos and sorry about the issues you encountered. If I understand correctly, you'd like the explicit documentation that ALB traffic would default to routing through the Service Connect agent? I want to make sure we address your ask properly.

**Comment by cuotos** [comment]
Im aware that this is not directly related to this thread but just your comment, so i'll leave just this one message.

In a word, yes, that is what we'd like to see documented. It was unexpected that when you have an existing ALB->ECS relationship, when turning on SC, that the traffic from the ALB would use it.
We expected to be able to turn on SC in isolation and not use it until we started addressing services by their SC dns, we never expected that the ALB traffic would be effected.
There is no mention of SC in the ALB settings, and the SC Namespace doesn't indicate the ALB is a member.
Having requests unexpectedly coming from localhost caused Kong / Nginx issues.
 
https://dev.to/cuotos/aws-alb-and-ecs-service-connect-unexpected-behaviour-18bm

**Comment by Seiya6329** [comment]
Thanks for the feedback on the AWS doc improvement suggestion.

I have placed the request for adding a mention of ALB traffic by default intercepted by a Service Connect agent.

**Comment by rnhurt** [comment]
It looks like this hasn't landed in CloudFormation yet.  I get this error when I try to configure it:
```
Resource handler returned message: 
 "Model validation failed (#: extraneous key [ServiceConnectService] is not permitted)"
(RequestToken: 996eedde-f001-c289-ae1f-5dab45cf2270, HandlerErrorCode: InvalidRequest)
```

The AWS::ECS::Service CloudFormation documentation [does mention this configuration option](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html), but the syntax is not yet updated.  When can we expect CFN to support this new feature?

**Comment by Seiya6329** [comment]
Hi @rnhurt ,
That error message seems to indicate an issue with the `ServiceConnectService` object rather than the new [TimeoutConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-timeoutconfiguration.html).

If you are still having an issue, please kindly raise a separate post or issue along with your CloudFormation template.

**Comment by nwsparks** [comment]
what is the default request timeout now? it does not seem to be documented anywhere that I can find.

**Comment by Seiya6329** [comment]
@nwsparks - You can find the default values in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-connect-concepts-deploy.html#service-connect-concepts-proxy -> "Timeout" entry.
