### ISSUE TITLE
[EKS] [Bug]: Windows Managed Node Groups are treated as healthy even if kube-proxy has crashed

### ISSUE THREAD

**Issue by ChrisMcKee** [aws/containers-roadmap#1969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Windows services created for kubelet and kubeproxy are currently created without any recovery options set.
![image](https://user-images.githubusercontent.com/83597/223148208-de983b25-37e0-4b5c-ba33-123694a326d4.png)
meaning any transient error will cause the node to break silently; in comparison the pods in linux would retry indefinately.

Our kube-proxy failed to start...

**Exception**
```
     525 Mar 06 11:15  Information kube-proxy                      0 ChildProcess exited
     524 Mar 06 11:15  Information kube-proxy                      0    cmd/kube-proxy/app/server.go:758 +0xb8a

     523 Mar 06 11:15  Information kube-proxy                      0 created by k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
     522 Mar 06 11:15  Information kube-proxy                      0    pkg/proxy/config/config.go:325 +0xe6

     521 Mar 06 11:15  Information kube-proxy                      0 k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).Run(0xc0005226e0, 0x0?)
     520 Mar 06 11:15  Information kube-proxy                      0    pkg/proxy/winkernel/proxier.go:1029 +0x76

     519 Mar 06 11:15  Information kube-proxy                      0 k8s.io/kubernetes/pkg/proxy/winkernel.(*Proxier).OnServiceSynced(0xc0005c44e0)
     518 Mar 06 11:15  Information kube-proxy                      0    pkg/proxy/winkernel/proxier.go:1495 +0x261d

     517 Mar 06 11:15  Information kube-proxy                      0 k8s.io/kubernetes/pkg/proxy/winkernel.(*Proxier).syncProxyRules(0xc0005c44e0)
     516 Mar 06 11:15  Information kube-proxy                      0 goroutine 149 [running]:
     515 Mar 06 11:15  Information kube-proxy                      0 [signal 0xc0000005 code=0x0 addr=0x0 pc=0x166cc5d]
     514 Mar 06 11:15  Information kube-proxy                      0 panic: runtime error: invalid memory address or nil pointer dereference
```
**Logs**
https://gist.githubusercontent.com/ChrisMcKee/54e11646452e2543bd7a1668ee308b09/raw/b21ad30d5397cc4b0f0795c46e53e51138ea3e1b/node_kubeproxylog.txt

Which left the service dead as there was no retry policy (it wouldn't have recovered anyway) the `kubelet` process was still running. As such the node was considered healthy even though it wasn't capable of serving any use.

**Which service(s) is this request for?**
EKS Windows Managed Node Groups

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

You shouldn't have to remote in to an eks worker node to tell why it has imploded. With the managed windows eks nodes that's basically the only option as the system maintains that the nodes are healthy, logs aren't available via kubectl and the majority of issues are just swallowed.

**Are you currently working around this issue?**
How are you currently solving this problem?

We're not; I'm not sure what caused the issue with kube-proxy either. No single deployment should be able to break a core component in such an opaque way.

**Comment by ChrisMcKee** [comment]
@mikestef9 I know stuff tends to float around here for quite a while; as we're still seeing it happen like node roullette are there any other useful logs etc I could attach to this so its debuggable later on? 

![image](https://user-images.githubusercontent.com/83597/223378501-c19e8748-210e-4345-89f5-6a2bd16ca361.png)

**Comment by ChrisMcKee** [comment]
The same cluster/pods functions fine using Windows_Server-2019-English-Core-EKS_Optimized-1.23-2023.02.14

Windows_Server-2019-English-Core-EKS_Optimized-1.24-2023.02.14 Fails

**Comment by ChrisMcKee** [comment]
Though the issue is more pronounced in the containerd based eks images. 
We had a docker based (23) instance lose pod->172net communication.

* `ipconfig /all` was the same between the working node and the failing node
* `ipconfig /all` was the same between the working node *pod* and the failing node
* Making a dns request for a service via the kube-dns returned results on both of the nodes without issue.

You could write a volume of docs just on troubleshooting this managed service. 
But importantly, both docker based nodes kubelet/kube-proxy were still running and microsofts attempt at iptables routing was still working from the nodes. Just the connectivity from docker.

---

All this is probably different in cause from the containerd based ami issues. Just the resounding ability of unhealthy nodes to stay active in k8s.

**Comment by ChrisMcKee** [comment]
https://github.com/kubernetes/kubernetes/issues/116389

The kube-proxy release 1.24.10 used in the latest Febuary EKS 1.24 AMI release seems to have a bug.

**Comment by goyalpurvi** [comment]
Thanks for reporting the issue. We're looking into it, and will keep you posted!

**Comment by ChrisMcKee** [comment]
I'll add to this that similarly if the `amazon-vpc-cni` isn't present or `enable-windows-ipam: "true"` is missing *OR* if the `aws-auth` configmap role matching the windows nodes doesn't contain the `- eks:kube-proxy-windows` group.

Most of the networking will fail. But again the nodes are classed as healthy and even though EKS can peer into these areas it doesn't in anyway notify you of the issue. So your deployments suddenly start failing on mass.

**Comment by KlwntSingh** [comment]
Hi @ChrisMcKee,
Asking some questions to better understand what caused this crash
1. Did kube-proxy crash after any specific deployment(pod, daemon set, service etc)? or
2. Did it just crash right after launching Windows MNG without doing anything?

**Comment by KlwntSingh** [comment]
Hi @ChrisMcKee,
EKS Optimized AMIs now have retry mechanism to start `kubelet` and `kube-proxy` if they crash. This change was released in April's AMI release.

Also, Latest Optimized AMIs now have `kube-proxy.exe` v1.24.7 which don't crash.

**Comment by ChrisMcKee** [comment]
👍 thanks that's great news
