### ISSUE TITLE
[EKS] [request]: Minimal type image in kube-proxy managed addon

### ISSUE THREAD

**Issue by psks1994** [aws/containers-roadmap#1986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Need to have option to select minimal type image in EKS managed addon.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Were using kube-proxy self-managed add-on and it had Minimal type image available. Now wanting to switch to managed addon and we don't find minimal type image listed just the Default type.

**Are you currently working around this issue?**
Currently we are deploying managed addon and there after manually updating the image version using below command:
   ####
kubectl set image daemonset.apps/kube-proxy -n kube-system kube-proxy=_602401143452.dkr.ecr.us-west-1.amazonaws.com/eks/kube-proxy:v1.22.11_-minimal-_eksbuild.2_

**Comment by mikestef9** [comment]
Starting in EKS v1.23, the minimal image is used by default and the only available one through EKS add-ons

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23

**Comment by sidewinder12s** [comment]
@mikestef9 I assume this can be closed as completed?

**Comment by sjastis** [comment]
Yes, this can be closed.

**Comment by s6-marct** [comment]
@mikestef9 said a while back:
> Starting in EKS v1.23, the minimal image is used by default for kube-proxy and the only available one through EKS add-ons

With the change to a minimal-only image type, what is your recommendation for situations where the older non-minimal default image is needed (eg. when debugging, having `dnf` available would be helpful.)
