### ISSUE TITLE
[EKS] [Support]: Support for EKS 1.27

### ISSUE THREAD

**Issue by amedirr** [aws/containers-roadmap#1994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like EKS support for Kubernetes v1.27.

In preparation for this I'd like to see EKS v1.27 added to the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) with a release date initially accurate up-to the quarter.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to use Kubernetes 1.27 on EKS and be aware of the release timeline to help plan for it.

**Are you currently working around this issue?**
N/A

**Additional context**
[Change Log](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md)
[Upcoming Changes](https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/)

**Attachments**
N/A

**Comment by mbevc1** [comment]
Upstream has released 1.27 yesterday: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md

Good to see we're getting close to upstream now :+1:

**Comment by dims** [comment]
Also watch the upstream patch schedule - https://kubernetes.io/releases/patch-releases/#upcoming-monthly-releases

**Comment by stevehipwell** [comment]
IMHO the Sysdig _"What's new?"_ [blog post](https://sysdig.com/blog/kubernetes-1-27-whats-new/) is essential reading for each new Kubernetes version.

**Comment by stevehipwell** [comment]
The ARMO [Kubernetes 1.27 release blog](https://www.armosec.io/blog/kubernetes-1-27-release/) is also well worth reading.

**Comment by stevehipwell** [comment]
So it looks like EKS v1.27 is now available; even though there isn't even a rough date in the release calendar 😉. I make that about 6 weeks from the upstream release which is pretty impressive.

![image](https://github.com/aws/containers-roadmap/assets/6552347/c10f72e9-1c6b-4c9f-a616-50c115002f99)

**Comment by mbevc1** [comment]
Nice one, under the radar? 😅

**Comment by amedirr** [comment]
Amazon EKS now supports Kubernetes 1.27 please see these posts to learn more:
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-27/
https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-eks-eks-distro-kubernetes-version-1-27/

**Comment by dims** [comment]
> So it looks like EKS v1.27 is now available; even though there isn't even a rough date in the release calendar 😉

thanks for noticing :)
