### ISSUE TITLE
ECR FIPS Compliance

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#2]
Use FIPS compliant software to terminate TLS. If we don't do this, then we should expect limited adoption in GovCloud regions.

**Comment by colmmacc** [comment]
Just a note to say that we have FIPS support in Amazon s2n (https://github.com/awslabs/s2n).

**Comment by paavan98pm** [comment]
Does this refer to running the ECR software (used to terminate TLS) in FIPS-compliant mode? If so, the issue title could be revised. Achieving FIPS compliance for ECR, which the issue title reads as-is, could be misleading to customers as that is an extensive process (independent validation of crypto modules in use within a service) we follow for KMS and CloudHSM.

**Comment by willfarrell** [comment]
Would be awesome if this was rolled out to Canada as well.

**Comment by jtoberon** [comment]
ecr-fips.us-east-1.amazonaws.com
ecr-fips.us-east-2.amazonaws.com
ecr-fips.us-west-1.amazonaws.com
ecr-fips.us-west-2.amazonaws.com
ecr-fips.us-gov-east-1.amazonaws.com
ecr-fips.us-gov-west-1.amazonaws.com

We will create a separate issue to track the Canada work.

**Comment by jtoberon** [comment]
Created https://github.com/aws/containers-roadmap/issues/501
