### ISSUE TITLE
ECS PrivateLink Support

### ISSUE THREAD

**Issue by Bensign** [aws/containers-roadmap#20]
Provide customers with private endpoint access to Amazon ECS.

**Comment by copumpkin** [comment]
This appears to be live! And with policies! 🎉 🎉 🎉

**Comment by copumpkin** [comment]
For anyone excited to try these endpoints out, I posted a closely related request on the ECS awsdocs issue tracker: https://github.com/awsdocs/amazon-ecs-developer-guide/issues/55

**Comment by abby-fuller** [comment]
shipped 1/25!

**Comment by christopherhein** [comment]
🚀 https://aws.amazon.com/about-aws/whats-new/2019/01/aws-fargate--amazon-ecs--and-amazon-ecr-now-have-support-for-aws/
