### ISSUE TITLE
[EKS] add lameduck option by default to the coreDNS health plugin to minimise DNS resolution failures

### ISSUE THREAD

**Issue by amisfari** [aws/containers-roadmap#2026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
This is a request to add the "lameduck" option to the coreDNS health plugin. Lameduck is useful to delay coredns pods shutdown. Setting up this option will minimize/prevent DNS failures during coreDNS pod restart or deployment rollout.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In the following scenarios : coreDNS pod restart or deployment rollout or while deleting the nodes on which coredns pods are running, we will experience DNS resolution failures. Setting up the lameduck option for a given duration will resolve this issue. However, the lameduck is not set by default on the current releases of coredns plugin and we have to manually add it by editing the coredns config map.

**Are you currently working around this issue?**
Currently, the workaround is to add this option manually by editing the coredns configmap.

**Attachments**
https://coredns.io/plugins/health/
https://cloud.ibm.com/docs/containers?topic=containers-coredns_lameduck

**Comment by dims** [comment]
related https://github.com/aws/aws-eks-best-practices/pull/314/files

**Comment by sjastis** [comment]
Added support starting coreDNS v1.9.3-eksbuild.6 and v1.10.1-eksbuild.3
