### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.18 on Enhanced Vulnerability Scan - Inspector

### ISSUE THREAD

**Issue by rgoltz** [aws/containers-roadmap#2027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Using Vulnerability Scans with for latest Alpine release.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
At 10.05.2023, Alpine Linux 3.18 has been released (please see https://gallery.ecr.aws/docker/library/alpine and https://alpinelinux.org/posts/Alpine-3.18.0-released.html). 
We are using AWS ECR Enhanced (Image) Scanning to check for vulnerabilities.

Once you using the latest (= 3.18) image-tag of Alpine, you will get the following output in ECR:
```
No scan findings
Scan status: UNSUPPORTED_IMAGE
```

At the same moment, Alpine SecDB also already added version 3.18, please see https://secdb.alpinelinux.org/v3.18/ (supporting vulnerability data)

**Are you currently working around this issue?**
No workaround known. This repo have to use Vulnerability Scans using AWS ECR Enhanced (Image) Scanning.
Currently we have to skip Image Scanning.

**Additional context**
A general improvement is needed and already requested here:
* https://github.com/aws/containers-roadmap/issues/1959

**Comment by adrianosela** [comment]
Can we get an ETA for this?

**Comment by colinbjohnson** [comment]
The [Inspector product page](https://aws.amazon.com/inspector/details/) states "Inspector also checks against common security compliance standards (e.g. PCI), and vulnerabilities." -> I feel like this should say "Inspector also checks against common security compliance standards (e.g. PCI), and vulnerabilities for _supported_ OSes and images".

As the default is _being unable to scan the latest version of Alpine_ companies that use Alpine or Alpine based images should probably reconsider their use of the Inspector product.

**Comment by 0n0w1c** [comment]
I believe the stated target date for release is July 18th.

**Comment by heidemn-faro** [comment]
> target date for release is July 18th.

That's obviously too late:
E.g. Node.js 18 LTS in the Alpine variant now defaults to Alpine 3.18.
https://hub.docker.com/_/node

![image](https://github.com/aws/containers-roadmap/assets/66078329/917f0ed1-e913-40c5-911d-843c36458eea)

Why do we always have to jump through extra hoops to get ECR scanning to work with the latest official Docker images?
The Alpine 3.17 -> 3.18 upgrade shouldn't be a surprise for AWS. (Or maybe it was a surprise, that's then another problem.)

**Comment by forty** [comment]
July 18th is for the unrelated corretto image based on alpine 3.18.

I could not find any ETA anywhere, it would be good if AWS could give us some visibility here (and also I'd be curious to know what's so special on alpine 3.18 that it would take time to add support for it)

**Comment by svaranasi-corporate** [comment]
For those waiting, AWS has added 3.18 support. I can confirm our repos are able to scan newly pushed 3.18 images. 3.18 is also added here: https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr

**Comment by rgoltz** [comment]
I'm closing this issue, since support for Alpine 3.18 has been added. Thanks for adding back in June.

@adrianosela I would kindly request you to copy your (comprehensible) statement from your comment above to the overall-issue of this topic: https://github.com/aws/containers-roadmap/issues/1959 (delay between OS-release and Scan-support in ECR Scanner) - Thanks :)
