### ISSUE TITLE
[EKS] [request]: add `topologySpreadConstraints` setting on the EKS CoreDNS addon configuration schema

### ISSUE THREAD

**Issue by iul1an** [aws/containers-roadmap#2033]
**Tell us about your request**
EKS CoreDNS addon `v1.9.3-eksbuild.3` added support for setting `affinity` and `tolerations`. However, it does not support `topologySpreadConstraints` and you can't achieve the same pods' distribution with only `affinity`.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to achieve an even distribution of CoreDNS pods across Kubernetes nodes, to improve service performance and reliability.

**Are you currently working around this issue?**
We work around this issue by manually patching the CoreDNS deployment after EKS deployment, but this is not a nice solution.

**Additional context**
We're deploying Kubernetes using [terraform-aws-eks](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) Terraform module.

**Comment by iul1an** [comment]
Similar issue: https://github.com/aws/containers-roadmap/issues/295

**Comment by iul1an** [comment]
Looks like CoreDNS addon `v1.9.3-eksbuild.5` added support for `topologySpreadConstraints`:
```
➜  aws eks describe-addon-configuration --addon-name coredns --addon-version v1.9.3-eksbuild.5 --query 'configurationSchema' --output text | gron | rg topologySpreadConstraints 
json.definitions.Coredns.properties.topologySpreadConstraints = {};
json.definitions.Coredns.properties.topologySpreadConstraints.description = "The coredns pod topology spread constraints";
json.definitions.Coredns.properties.topologySpreadConstraints.type = "array";

```

**Comment by sjastis** [comment]
Yes! the support is with coredns v1.10.1-eksbuild.2 and v1.9.3-eksbuild.5. From these 2 versions we are supporting PodDisruptionBudget and topologySpreadConstraints.

For more details on the release - https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html
