### ISSUE TITLE
[ECR] [request]: Support scanning of Ubuntu 23.04 LTS based images

### ISSUE THREAD

**Issue by albertlobbc** [aws/containers-roadmap#2035]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for scanning Ubuntu 23.04 LTS based images for security vulnerabilities

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Continue to have the ability to scan images pushed to ECR after upgrading the base image to Ubuntu 23.04 LTS.

**Are you currently working around this issue?**
Struggling to downgrade the version of Ubuntu and Python

**Additional context**
Pushed an image based on Ubuntu 23.04 and received UnsupportedImageError from ECR scan on push

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sbocinec** [comment]
@albertlobbc I just wonder - Ubuntu `23.04` is not an LTS release, it's just an interim release with 9 months support https://ubuntu.com/about/release-cycle - is it indeed `23.04` support you are requesting, or `22.04` that's LTS?

**Comment by albertlobbc** [comment]
I am sorry that I don't know the non-TLS OS is not supported.

**Comment by bradg-aws** [comment]
Hi @albertlobbc, thanks for raising this.
Ubuntu 23.04 is now supported in both ECR basic and enhanced scanning.
