### ISSUE TITLE
After updating to EKS 1.27 our EKS Managed Windows nodes don't seem to be able to pull from any AWS ECR anymore.

### ISSUE THREAD

**Issue by buckleyGI** [aws/containers-roadmap#2042]
We got word from AWS support that this [merge ](https://github.com/kubernetes/kubernetes/pull/116329#issuecomment-1576772951)is the cause.
Now waiting on the fix which is a new AMI release I believe. This issue had a big impact on our cluster and we had to rollback.

After updating to EKS 1.27 our EKS Managed Windows nodes don't seem to be able to pull from any AWS ECR anymore.
Pulling custom images from our own ECR fails with a 401: Unauthorized and pulling images from managed addons (like aws ebs csi driver) cross-account also fail with 401:Unauthorized.
We don't have this issue on 1.26 though and IAM permissions are all fine.

`Failed to pull image REDACTED: rpc error: code = Unknown desc = failed to pull and unpack image REDACTED: failed to resolve reference REDACTED: pulling from host REDACTED failed with status code [manifests v1.19.0]: 401 Unauthorized `

This got first posted to https://github.com/kubernetes/kubernetes/pull/116329#issuecomment-1576772951
Sorry for the cross post.

**Comment by buckleyGI** [comment]
Thanks @mikestef9 🙇‍♂️

**Comment by elitistphoenix** [comment]
Any updates on the Windows AMI release please? Hopefully without sounding terrible it's been at least a day and a half since AWS released this and we're still stuck with the old Win AMIs

**Comment by buckleyGI** [comment]
Hi @elitistphoenix We rollbacked to V1.26 for now. I haven't tried the mitigation as we had everything in terraform so the rollback was an opton.

**Comment by mikestef9** [comment]
Closing as new AMIs have been rolled out
