### ISSUE TITLE
[ECR] [Scan OS support]: Support security scanning of Debian 12

### ISSUE THREAD

**Issue by petarlishov** [aws/containers-roadmap#2047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like you to add support for ECR scanning of images with a Debian 12 base. Currently you only support up to Debian 11.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We automate our ECR scans and disallow use of images with security vulnerabilities. We would like to upgrade to Debian 12 but sadly we cannot as ECR scanning is not supported for that OS.

**Are you currently working around this issue?**
We are currently working around this by pinning our base OS to Debian 11

**Additional context**
We have wrapped our own feature of ignoring certain vulnerabilities around the ECR scanning process, it would be good if ECR scanning supports that natively.

**Attachments**
<img width="504" alt="Screenshot 2023-06-16 at 10 43 30" src="https://github.com/aws/containers-roadmap/assets/38254944/f2404607-6393-464d-a2d1-4b16511e8fe3">

**Comment by shelisiag** [comment]
I have the same issue.
debian 11 has 5 Hight Vulnerabilities, fixed in debian 12.
when pushing image base on debian 12 (bookworm), ECR Image scan's status is "Not Supported"

**Comment by volleio** [comment]
I'm seeing this issue resolved now, new Debian 12 Bookworm images are being scanned successfully.
Previously created images are not automatically rescanned, but manually rescanning works.

**Comment by jlbutler** [comment]
This finished deployment last week and should be available in all regions. Please comment if any further issues. Thanks!

**Comment by sebastiandaberdaku** [comment]
I am getting `UnsupportedImageError: The operating system and/or package manager are not supported.` error on bookworm-based Docker Images on ECR.

![Image](https://github.com/user-attachments/assets/7ce15515-ea72-482e-9a10-bfe64c50697a)

For instance, images based on public.ecr.aws/docker/library/python:3.9.21-slim-bookworm will result in the shown error.
