### ISSUE TITLE
[ECS] Bug in new ECS UI

### ISSUE THREAD

**Issue by ragumix** [aws/containers-roadmap#2050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Fix new ECS UI

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In new ECS UI when you are trying to update something in scheduled task, it shows the following warning in the Networking block:
![image](https://github.com/aws/containers-roadmap/assets/39560105/05585cbc-f2eb-4104-b0e4-60bd7821b0c4)
And after saving changes it shows the following error:
![image](https://github.com/aws/containers-roadmap/assets/39560105/0aa2a67c-71e0-4895-87df-f628f28536ac)
But anyway it saves changes which made during the update.
This problem appeared several days ago.

BTW, in the old UI this problem didn't exist.

**Comment by goto1** [comment]
Hi @ragumix - this was addressed last week, could you give it a try again?
Thanks

**Comment by ragumix** [comment]
Yes, now it's ok. Problem gone.
Thank you!
