### ISSUE TITLE
[ECR] [request]: Some ECR pull through cache features do not work cross-account

### ISSUE THREAD

**Issue by billhammond-dev** [aws/containers-roadmap#2053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Allow ECR pull through cache image pulls for new images that are not yet in a pull-through repo to be pulled from remote accounts without having to first assume a role in the account the ECR pull through repo is in.

Steps to reproduce 'issue' below

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
If you already have an ECR pull through repo in one account, with permissions setup to allow any other account in your org to have ECR:* access, it is not actually possible to pull 'new' images that arent already in the ECR pull through repo: i.e. images that are part of the ECR public or QUAY public repos that would automatically get cached in the pull through repo that havent yet been cached there.

Ex: I have an existing pull through repo <acct_id>.dkr.ecr.us-east-1.amazonaws.com/ecr-public/docker/library/python

this repo contains a previously cached image A with tag <tag_a>

I have a permission set on the repo which is something like:
`{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "Allow all org access",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "ecr:*",
      "Condition": {
        "StringEquals": {
          "aws:PrincipalOrgID": "<org_id>"
        }
      }
    }
  ]
}`

I can pull the already cached image tag_a from the repo from a remote account in the org, but not tag_b which has not already been cached to the ECR pull through repo. Pulling tag_b would require me to assume a full ECR access role in the account that contains the ECR pull through repo. After pulling tag_b the first time in this way then yes I can now pull tag_b also from other accounts in the org. The first caching of the image is what requires this different authentication for some reason.

**Are you currently working around this issue?**
Manually pulling images if new ones are needed in the cache for use by EKS clusters in other org accounts

**Additional context**
n/a

**Attachments**
n/a

**Comment by jlbutler** [comment]
Hi @billhammond-dev. Sorry for the delay in responding. It sounds like your permissions are set up for your repository, have you set up permissions in the registry for other principals to pull new images into the cache?  Specifically, this would be granting permission for the `ecr:BatchImportUpstreamImage` action. This is done at the registry scope, vs in the repository. 

See the pull through cache ['Required IAM Permissions'](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html) section in the ECR docs. Let us know if that sorts things, thanks!

**Comment by billhammond-dev** [comment]
Sorry I missed the updates above. All of what you suggested above has been done, I have already confirmed with AWS internal support that this does not work as expected and they told me to open this ticket. Unless something has changed on the AWS side I would assume that it still does not work. I have not found a case where you can pull a 'new' as yet unpulled ECR pull through image without actually assuming a role in that ECR account yet.

**Comment by neogibson** [comment]
I am also running into this, as you said, if a pull through cache repository already exists, the other account is able to pull the image cross-account.

It's the case where a non-cached image is attempted to be pulled-through from a cross-account role/user for the first time that does not work. My Private Registry Policy is as follows:

```{
  "Sid": "PullThroughPolicy",
  "Effect": "Allow",
  "Principal": {
    "AWS": "arn:aws:iam::<account-id>:root"
  },
  "Action": "ecr:*",
  "Resource": [
    "arn:aws:ecr:ca-central-1:<account-id>:repository/quay/*",
    "arn:aws:ecr:ca-central-1:<account-id>:repository/k8s/*"
  ]
}```

When I try to pull an image that is not cached already in one of those repos, the role in the other account gets an error: 

```ecr:BatchGetImage on resource: arn:aws:ecr:ca-central-1:<account-id>:repository/k8s/metrics-server/metrics-server because no resource-based policy allows the ecr:BatchGetImage action```

I assume because `ecr:BatchGetImage` isn't in the repository policy, but it's impossible to add it because the `k8s/metrics-server/metrics-server` repo does not exist yet, because it's the first time an image from this namespace is being pulled.

Is it just that first-time pulls need to happen in the same account?

**Comment by kereza** [comment]
I also face this problem now. That is quite strange behaviour.  I guess it is not intentional :) . 

It is strange that cross-account roles are not able to pull through cache images and create the repo.

**Comment by cgansen-devoted** [comment]
I encountered this issue as well: role in account A could not pull uncached images from ECR in account B. I solved it by adding both `ecr:CreateRepository` and `ecr:BatchImportUpstreamImage` to the role in A **and** the registry permissions in account B. After that I was able to pull cached and uncached images using the account A role. Good luck.

**Comment by bodgit** [comment]
I'm getting the same behaviour as @neogibson in that the action that fails is `ecr:BatchGetImage`. I've tried @cgansen-devoted suggestions and it doesn't make any difference, (I had those permissions set in both places anyway).

I also think this issue isn't going to go anywhere as it's closed, so should probably make a new one.

**Comment by internetstaff** [comment]
If it helps, I added `ecr:BatchImportUpstreamImage` to my cross-account repository policies and am able to pull-through from other accounts.

I am only using pre-created pull-through repositories - I wasn't able to get CreateRepository working.

**Comment by davidnortonjr** [comment]
Utilizing the new (in public preview) [Repository Creation Templates](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-initial-configuration-repositories-pull-through-cache-preview/), I was able to get this working. On the account that will hold the new ECR repo, I added a creation template with policy that will allow cross-account pulls.

Then I authenticated my AWS CLI to a different account, authenticated Docker to pull from the ECR registry, and was able to initiate a cross-account pull, which automatically created the repository!

**Comment by cpboyd** [comment]
I followed these steps:
1. Creating the [repository creation templates](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-creation-templates.html#repository-creation-templates-create) with the required policy
   - Manually adding the policy for any repos that'd already been created
2.  Adding the [cross-account registry policy](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html#pull-through-cache-iam)
3. Manually adding the policies for each of the roles/users that need access

Now it **_seems_** to be working.

Certainly, it seems like there should be a more straight-forward, unified workflow.

**Comment by davidnortonjr-sps** [comment]
> I cannot confirm this. I am using the Repository Creation Templates too, this will help you with setting up correct permissions, but cross-account Repository creation still fails, I just created a support case, and they confirmed this, a cross account IAM Role is not able to create the initial repository for pull-through-repos. Repository creation must be initiated for pull-through repos in the account where the ECR is located. Afterwards everything is working fine. If you have done some additional magic, it would be great if you can share it.

@zeb-it-saas I just tried this with two, brand-new accounts. I created everything using Terraform except for the repository creation templates, which have to be created via the console. Here's a blog post walking through it step by step, with a GitHub repo linked at the bottom: https://platformers.dev/log/2023/ecr-cross-account-pull-through-cache/

Feel free to reach out from that website if you run into further issues. It should work if you have all the pieces in place. Cheers!

**Comment by davidnortonjr-sps** [comment]
> I cannot confirm this. I am using the Repository Creation Templates too, this will help you with setting up correct permissions, but cross-account Repository creation still fails, I just created a support case, and they confirmed this, a cross account IAM Role is not able to create the initial repository for pull-through-repos. Repository creation must be initiated for pull-through repos in the account where the ECR is located. Afterwards everything is working fine. If you have done some additional magic, it would be great if you can share it.

@zeb-it-saas I just tried this with two, brand-new accounts. I created everything using Terraform except for the repository creation templates, which have to be created via the console. Here's a blog post walking through it step by step, with a GitHub repo linked at the bottom: https://platformers.dev/log/2023/ecr-cross-account-pull-through-cache/

Feel free to reach out from that website if you run into further issues. It should work if you have all the pieces in place. Cheers!

**Comment by davidnortonjr** [comment]
> I cannot confirm this. I am using the Repository Creation Templates too, this will help you with setting up correct permissions, but cross-account Repository creation still fails, I just created a support case, and they confirmed this, a cross account IAM Role is not able to create the initial repository for pull-through-repos. Repository creation must be initiated for pull-through repos in the account where the ECR is located. Afterwards everything is working fine. If you have done some additional magic, it would be great if you can share it.

@zeb-it-saas I just tried this with two, brand-new accounts. I created everything using Terraform except for the repository creation templates, which have to be created via the console. Here's a blog post walking through it step by step, with a GitHub repo linked at the bottom: https://platformers.dev/log/2023/ecr-cross-account-pull-through-cache/

Feel free to reach out from that website if you run into further issues. It should work if you have all the pieces in place. Cheers!

**Comment by mxie1563** [comment]
In my case, while docker pull command works for cross account in ptc, but the EKS helm does not work. 
Here is the test based the configuration:
Configure PTC rule, Configure Repo Template policy;
In the same account, Docker pull works to create the ptc repo; I deleted the ptc image; the start helm deployment in EKS, it trigger PTC, create the ptc repo and works;
In a different account, Docker pull works to create the ptc repo; I deleted the ptc image; the start helm deployment in EKS, it failed to create the ptc repo. 
However, if I manually use docker pull to create the ptc repo, the EKS helm has no issue to read the ptc repo.
`Failed to pull image "XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/kubernetes/autoscaling/cluster-autoscaler:v1.23.0": rpc error: code = NotFound desc = failed to pull and unpack image "XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/kubernetes/autoscaling/cluster-autoscaler:v1.23.0": failed to resolve reference "XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/kubernetes/autoscaling/cluster-autoscaler:v1.23.0": XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/kubernetes/autoscaling/cluster-autoscaler:v1.23.0: not found`

**Comment by mxie1563** [comment]
Finally I resolved my issue. The EKS Node Group needs to have explicit policy to allow it to pull from PTC.

**Comment by rzala** [comment]
Hi @mxie1563, could you share some details on how you attached a policy to the node group? Thanks.

**Comment by mikebreed** [comment]
I was having this same issue and the only way I could get it to work was by setting the actions to `ecr:*` in the registry policy. I tried the two mentioned in the articles (`ecr:CreateRepository` and `ecr:BatchImportUpstreamImage`) and that didn't work, but `*` does, so it's almost like there is an undocumented action that needs to be there. Other than this change, I followed the doc linked above by @davidnortonjr

**Comment by quanlk2511** [comment]
Hi guys, @mikebreed  @davidnortonjr ,

The creation template doesn't seems working. When I try to pull a repo (thtrough PullThroughCacheRule), no policy from template can be applied at all; even with ROOT or specific prefix case.

Here is my ROOT template:
`{
  "prefix": "ROOT",
  "encryptionConfiguration": {
    "encryptionType": "AES256"
  },
  "imageTagMutability": "MUTABLE",
  "repositoryPolicy": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowPushPullIAMRole",
        "Effect": "Allow",
        "Principal": {
          "AWS": "*"
        },
        "Action": [
          "ecr:BatchGetImage",
          "ecr:BatchCheckLayerAvailability",
          "ecr:CompleteLayerUpload",
          "ecr:GetDownloadUrlForLayer",
          "ecr:InitiateLayerUpload",
          "ecr:PutImage",
          "ecr:UploadLayerPart"
        ]
      }
    ]
  },
  "appliedFor": [],
  "createdAt": "2024-03-22T02:37:47.688Z",
  "updatedAt": "2024-03-22T02:37:47.688Z"
}`

**Comment by quanlk2511** [comment]
@der-eismann ,

AWS team had fixed this from their end. The template is working with me as well, policies are now applicable to PullThroughCache repo.

**Comment by muawiakh** [comment]
The approach by @davidnortonjr worked for me but I see some strange behavior i.e. when I add any `lifecycle policy` or `resourceTags` to the repository template, it stops working.

Works with the following configuration:

```
{
  "prefix": "k8s",
  "description": "test",
  "encryptionConfiguration": {
    "encryptionType": "AES256"
  },
  "imageTagMutability": "MUTABLE",
  "repositoryPolicy": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowCrossAccountPull",
        "Effect": "Allow",
        "Principal": {
          "AWS": "<someaccount>"
        },
        "Action": [
          "ecr:BatchGetImage",
          "ecr:GetDownloadUrlForLayer"
        ]
      }
    ]
  },
  "appliedFor": [
    "PULL_THROUGH_CACHE"
  ],
  "createdAt": "<timestamp>",
  "updatedAt": "<timestamp>"
}
```

Stops working when I add `resourceTags`:

```
{
  "prefix": "k8s",
  "description": "test",
  "encryptionConfiguration": {
    "encryptionType": "AES256"
  },
  "resourceTags": [
    {
      "Key": "CreateBy",
      "Value": "foobar"
    }
  ],
  "imageTagMutability": "MUTABLE",
  "repositoryPolicy": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowCrossAccountPull",
        "Effect": "Allow",
        "Principal": {
          "AWS": "<someaccount>"
        },
        "Action": [
          "ecr:BatchGetImage",
          "ecr:GetDownloadUrlForLayer"
        ]
      }
    ]
  },
  "appliedFor": [
    "PULL_THROUGH_CACHE"
  ],
  "createdAt": "<timestamp>",
  "updatedAt": "<timestamp>"
}
```

Same for lifecycle policy. I am able to pull existing images from the repository but unable to create a new one.

**Comment by danielloader** [comment]
> Has anyone managed to get this working when setting the needed IAM permissions only on the registry level?
> 
> It works if I add the ecr permissions to the IAM role of the entity which pulls the image, but I expect it to work even if the permissions are only one-sided (if registry permissions allow it).

I got bitten by this recently with karpenter nodes and not having the additional IAM roles bolted on to give additional ECR permissions to pull images cross account - I'd agree that you'd want to do it registry side as the source of truth and EKS nodes should just be able to pull any image the registry IAM permissions permit them to.

Not insurmountable but it's been extra work to find the root cause and fix the terraform and write some documentation internally on why we need to do it.

**Comment by danielloader** [comment]
Sorry to make it clear, I'm using terraform internally here so I had to handle the IAM on both sides of the account (and more pertinently org wide so any account can pull through the cache in a centralised ECR account).

I get why it's potentially the way it is, but I also agree there's scope to simplify this or at the least, document it clearly.

**Comment by sgarlick987** [comment]
For us it seems that we'd need to add `ecr:TagResource` in the registry policy as we have tags defined in repo templates, but it is rejected currently claiming invalid policy. We get around this using `ecr:*` and I assume other api calls the repo templates use would fail if they can't be added to the registry policy.

**Comment by johnoct-au** [comment]
@sgarlick987 I think this is a bug with aws. I'm not sure why it is claiming invalid policy when adding `ecr:TagResource`. Adding `ecr:*` is way to permissive. The documentation should be updated with the exact permissions required to allow cross account pull through ecr caching.

**Comment by kattmang** [comment]
Just to give an update for folks, repository creation templates is now generally available, and has a simplified approach to permission for KMS actions and `ecr:TagResource`: https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-creation-templates-create.html . There will be a forthcoming blog post diving into how this all works.

For folks using Resource Tags and/or KMS keys in their templates, you will need to onboard your templates to use an repository creation role (the `customRoleArn` field in a template) which will enable ECR to tag repositories on your behalf. There's no longer a cross-account Registry policy permission requirement, however as you can now enable templates for Replication repository creation use cases, the normal cross-account replication permission setup still applies.

**Comment by navera-mb** [comment]
> Finally I resolved my issue. The EKS Node Group needs to have explicit policy to allow it to pull from PTC.

Can you please share the policy for node group as an example here? Thanks!

**Comment by digdiego13** [comment]
> > Finally I resolved my issue. The EKS Node Group needs to have explicit policy to allow it to pull from PTC.
> 
> Can you please share the policy for node group as an example here? Thanks!

Hey, Navera, you need to add the policy to nodegroup with these permissions:
```

**Comment by speller** [comment]
So how to create a pull-through cache accessible from another account? Any documentation for this? I'm getting the `no resource-based policy allows the ecr:BatchGetImage` error.

**Comment by felipewnp** [comment]
> So how to create a pull-through cache accessible from another account? Any documentation for this? I'm getting the `no resource-based policy allows the ecr:BatchGetImage` error.

I'm lost too on how to make this work. At the moment, It just doesn't.

**Comment by shmileee** [comment]
@speller, @felipewnp

I’ve resolved the issue by attaching the `ecr:CreateRepository` and `ecr:BatchGetImage` permissions to both the instance profile used by Karpenter and the ECR repository policy. I've documented my setup here, including instructions on configuring access within an AWS organization: 

- https://blog.oponomarov.com/posts/setting-up-pull-through-cache-repositories-in-aws-ecr

**Comment by ryancouto** [comment]
> So how to create a pull-through cache accessible from another account? Any documentation for this? I'm getting the `no resource-based policy allows the ecr:BatchGetImage` error.

+1 - are there any updates here?
