### ISSUE TITLE
[EKS] [request]: Systemd upgrade to > v239 for enabling node graceful shutdown 

### ISSUE THREAD

**Issue by shivaprasad-balaji** [aws/containers-roadmap#2057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Upgrade systemd version in AWS optimized EKS AMI to version greater than v239

**Which service(s) is this request for?**
This is for EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We were looking into configuring graceful shutdown for kubernetes nodes. The feature is enabled by default from  kubernetes version 1.21.([https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/ ](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/)). Our clusters are running v1.24. 

After enabling it and configuring the ShutdownGracePeriod and ShutdownGracePeriodCriticalPods - using the kubelet configuration options, we see that the graceful shutdown is not working as expected. When karpenter(we use karpenter for cluster scaling) detects a node is empty, it terminates the node and the node is terminated immediately without any grace period. 

We checked for the issue and we found out few references which indicate there is an issue with the systemd version on the node. We use the AWS EKS optimized linux AMI for the nodes and we see that the systemd version is v219. 
As per the links below, it seems this is fixed after v239 of systemd. 
1. https://github.com/kubernetes/kubernetes/issues/107043#issuecomment-997546019 
2. https://github.com/aws/karpenter-core/pull/248#issuecomment-1494390601

**Are you currently working around this issue?**
How are you currently solving this problem?
No known workaround is known at this point. 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sayap** [comment]
All these comments about "a known BUG in upstream Systemd" seems to be quite misleading. After spending some time trying to get this to work on Amazon Linux 2, I found the culprit that prevents systemd from doing anything:
```
$ cat /usr/lib/systemd/logind.conf.d/acpid.conf
# Disable logind's handling of ACPI events when acpid is installed.
[Login]
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchDocked=ignore
```
So we just need a `yum remove acpid` followed by a `systemctl restart systemd-logind`, and then systemd-inhibit will work fine on Amazon Linux 2. 

I am not sure how well the graceful node shutdown feature works yet, but any issue there shall be blamed on kubelet, not systemd.

**Comment by shivaprasad-balaji** [comment]
I followed https://www.skouf.com/posts/enabling-graceful-node-shutdown-on-eks-in-kubernetes-1-21/ and added the following to the user data of the EC2 instance and was able to get graceful shutdown to work. 

`mkdir -p /etc/systemd/logind.conf.d`
`echo "[Login]" > /etc/systemd/logind.conf.d/50-max-delay.conf`
`echo "InhibitDelayMaxSec=360" >> /etc/systemd/logind.conf.d/50-max-delay.conf`
`systemctl restart systemd-logind`

As @sayap has mentioned, it is probably not related to systemd. I am not a linux expert to understand what component is causing this though.

**Comment by aberle** [comment]
I followed those steps as well and graceful shutdown is not working for me so I'm wondering what I'm missing. Like I said, when I reboot the instance, the inhibitor does not block the shutdown and executes right away.

**Comment by sayap** [comment]
@shivaprasad-balaji  Indeed we need to follow https://www.skouf.com/posts/enabling-graceful-node-shutdown-on-eks-in-kubernetes-1-21/, to avoid triggering the if-block in https://github.com/kubernetes/kubernetes/blob/v1.23.17/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L182-L202, which would fail with error:
```
Failed to start node shutdown manager" err="failed reading InhibitDelayMaxUSec property from logind: Message recipient disconnected from message bus without replying"
```
because `ReloadLogindConf` would restart systemd-logind and break the connection.

@aberle You are right, the EKS worker node doesn't come with acpid, so my finding above was just a red herring, but it can probably explain why the k8s developer misattributed this as a systemd bug (https://github.com/kubernetes/kubernetes/issues/107043#issuecomment-997546019)

Anyway, if it still doesn't work after following the blog post, can you check:
* the output of `systemd-inhibit --list` as root
* log lines from kubelet that starts with `Shutdown manager`

Note that the configured shutdown grace period is just the upperbound. As soon as kubelet has successfully terminated all the pods, it will remove the inhibitor and allow the system to shutdown.

**Comment by sayap** [comment]
Just realize that the `sed` & `grep` commands from https://www.skouf.com/posts/enabling-graceful-node-shutdown-on-eks-in-kubernetes-1-21/ doesn't work anymore in newer worker AMIs, due to https://github.com/awslabs/amazon-eks-ami/commit/30ccd211b67. The `echo` command added by that commit doesn't have double quotes, causing kubelet-config.json to collapse into a single line.

We can replace the `sed` & `grep` with a jq one-liner:
```shell
echo "$(jq '.shutdownGracePeriod="60s" | .shutdownGracePeriodCriticalPods="20s"' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```

**Comment by youwalther65** [comment]
@shivaprasad-balaji I wonder why we need graceful node shutdown at all for Karpenter. Karpenter  [Termination Controller](https://karpenter.sh/v0.32/concepts/disruption/#termination-controller) is calling the [Kubernetes Eviction API](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/) and properly drain the node before terminating it via cloud provider. For "Instance Terminating Events" related to Spot instances Karpenter needs to be integrated with build-in Node Termination Handling which ensures a proper drainign as well.

**Comment by sayap** [comment]
Out of all the options, I think only graceful node shutdown can gracefully terminate the normal pods first, and then gracefully terminate the daemonset pods.

**Comment by shivaprasad-balaji** [comment]
@youwalther65 : As per my understanding and also observation on how it works, karpenter drains all the non-daemonset pods on a node and then terminates the instance. However the node terminates immediately after the cloudprovider API is called and there is no inhibitor or wait, which waits for the daemonset pods to gracefully shutdown. 

Setting up the kubernetes graceful shutdown adds inhibitor to the node, so that the daemonsets are given sufficient time to gracefully shutdown.

**Comment by youwalther65** [comment]
@shivaprasad-balaji I agree  now, I wasn't completely aware of that. But there are still other problems in the kubelet itself where even graceful node shutdown  wont help, see [Graceful node shutdown doesn't wait for volume teardown #115148](https://github.com/kubernetes/kubernetes/issues/115148).
But coming back to the systemd version. My recent EKS optimized 1.29 AMI already runs systemd 259, but still graceful node termination isn't enabled. There is a stuck PR [[WIP] Enable graceful node shutdown for 1.29+ #1544](https://github.com/awslabs/amazon-eks-ami/pull/1544)

**Comment by cartermckinnon** [comment]
I think this should be closed. `systemd` isn't a problem (and it won't be updated on AL2 anyway). We should track this in the AMI's repository: https://github.com/awslabs/amazon-eks-ami/pull/1544

**Comment by stevehipwell** [comment]
@mikestef9 @cartermckinnon I'm not sure closing this issue without a replacement (#1651 is currently tagged for MNGs) to track the availability of graceful node shutdown in EKS is in the interest of the community. Could we either get EKS documentation on where/when graceful shutdown is supported, reopen this issue (maybe updated), or open a new issue to track graceful node shutdown?
