### ISSUE TITLE
[ECS] [FSx,FARGATE]: Support FSx mounting on ECS Linux fargate

### ISSUE THREAD

**Issue by prashanthbgoud** [aws/containers-roadmap#2063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support FSx mounting on ECS Fargate running Linux, we have a requirement to mount FSx on ECS Fargate and a Windows EC2 instance. Its a nightmare now to find a possible alternates.

**Which service(s) is this request for?**
Fargate, ECS, Windows, Linux, FSx

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a Windows ec2 instance from which we can have a SMB share, which cannot be mounted. other option we could think of is to mount EFS or FSX on both sides. Unfortunately none of them are supported.

**Are you currently working around this issue?**
No solution yet, trying to do some cron from a lambda to sync between smb share and the EFS share.

**Comment by ollypom** [comment]
Hi @prashanthbgoud , I believe this is a duplicate for existing issues: [FSx for Windows on Fargate](https://github.com/aws/containers-roadmap/issues/1654) and [FSx for Linux on Fargate](https://github.com/aws/containers-roadmap/issues/650). So I am going to close this issue.

If I have misunderstood, and this is a request not covered by the existing issues, then I apologize and we can reopen this one.
