### ISSUE TITLE
[ECS] [request]: Support Ubuntu 22.04

### ISSUE THREAD

**Issue by katsew** [aws/containers-roadmap#2064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I request the support Ubuntu 22.04 for ecs-agent (or ecs-init maybe?).
I found the issue at https://github.com/aws/amazon-ecs-agent/issues/3770 and routed to here.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I've installed the ecs-agent via deb file documented on [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).
However, the ecs-agent lauched by systemd service cannot launch the ECS Service and ECS Task,
as the same issue as https://github.com/aws/amazon-ecs-agent/issues/3227.

**Are you currently working around this issue?**
I've tested the command documented on [here](https://github.com/aws/amazon-ecs-agent#on-other-linux-amis), and it seems to be worked (but not fully tested).

```
docker run --name ecs-agent \
    --detach=true \
    --restart=on-failure:10 \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --volume=/var/log/ecs:/log \
    --volume=/var/lib/ecs/data:/data \
    --net=host \
    --env-file=/etc/ecs/ecs.config \
    --env=ECS_LOGFILE=/log/ecs-agent.log \
    --env=ECS_DATADIR=/data/ \
    --env=ECS_ENABLE_TASK_IAM_ROLE=true \
    --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
    amazon/amazon-ecs-agent:latest
```

**Additional context**

Service Type: DAEMON
Launch Type: EC2

```
$ uname -r
5.19.0-1028-aws
```

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Attachments**

The task definition and ecs.config that I use to test is something like [this](https://gist.github.com/katsew/35747af3afba73441696c938ca8bf11b)

**Comment by sparrc** [comment]
Hi everyone, this is now supported in agent/init version 1.80.0: https://github.com/aws/amazon-ecs-agent/releases.

Support was added via this PR: https://github.com/aws/amazon-ecs-agent/pull/4062

Working on updating the docs now.
