### ISSUE TITLE
[ECR] [Scanning]: AWS OTEL Collector is failing scans when used as a base for a docker image

### ISSUE THREAD

**Issue by tallpaul-embark** [aws/containers-roadmap#2066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Not looking for a new feature, just support for image scanning

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Our team is using the docker image of [aws-otel-collector](https://github.com/aws-observability/aws-otel-collector) version 0.29.1 as the base for our open telemetry dockerfile. When we attempt to scan the image we get the error `"imageScanStatus":{"status":"FAILED","description":"UnsupportedImageError: The operating system and/or package manager are not supported."}}`. This feels like a bug as the [dockerfile](https://github.com/aws-observability/aws-otel-collector/blob/main/cmd/awscollector/Dockerfile) from aws-otel-collector seems to be using alpine which is listed as a [supported version](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.html#:~:text=CentOS%2C%20Oracle%20Linux%2C-,Alpine,-%2C%20and%20RHEL%20Linux). 

The ideal outcome of this would be supported scanning for this package to help our team protect ourselves. 

**Are you currently working around this issue?**
How are you currently solving this problem?

We are not scanning the image for vulnerabilities which could be okay or could be an issue.

**Comment by Aneurysm9** [comment]
>This feels like a bug as the [dockerfile](https://github.com/aws-observability/aws-otel-collector/blob/main/cmd/awscollector/Dockerfile) from aws-otel-collector seems to be using alpine which is listed as a [supported version](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.html#:~:text=CentOS%2C%20Oracle%20Linux%2C-,Alpine,-%2C%20and%20RHEL%20Linux).

The ADOT Collector image is [built `FROM scratch`](https://github.com/aws-observability/aws-otel-collector/blob/main/cmd/awscollector/Dockerfile#L69).  Prior stages use `alpine` for obtaining CA certificates and `golang` for building the binary, but those stages are only used to prepare data to be copied into the final stage.

**Comment by jlbutler** [comment]
Hi @tallpaul-embark. As the previous comment explains, this image is actually built from `scratch` (thanks @Aneurysm9) and therefore doesn't contain a packaging system which scanners depend upon. I think we can close this issue, but please loop back here if I'm missing an opportunity for us to do more. Thanks!
