### ISSUE TITLE
[EKS] [Feature Request]: EKS Optimized AMI has very low open-files ulimit

### ISSUE THREAD

**Issue by trimbleAdam** [aws/containers-roadmap#207]
**Tell us about your request**
Update EKS optimized AMI ulimits nofile should be far greater than what is currently set. (1024 for system ulimit, and 8192 for Docker). These limits are rather weak, as for a normal ElasticSearch deployment the pods won't even start if nofiles < 65536.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In this case, I am trying to release elasticsearch. In the old KOPS cluster, the default limits were set much higher than in this case.

**Are you currently working around this issue?**
To work around the issue, I have to add userdata which manually changes ulimits in /etc/security/limits.conf for system-wide limits, and update /etc/docker/daemon.json to set limits for Docker.

**Comment by kamirendawkins** [comment]
I think this will be solved by https://github.com/awslabs/amazon-eks-ami/pull/206

**Comment by rtkgjacobs** [comment]
Some deployments will also modify this per container / pod. This helm chart uses an init container to do this w/ Elasticsearch on K8s. I assume this approach below steps around the above issue until its corrected in future AMI's by default? 

https://github.com/helm/charts/blob/master/stable/elasticsearch/templates/data-statefulset.yaml#L77

**Comment by trimbleAdam** [comment]
Closing as dupe of awslabs/amazon-eks-ami#206
