### ISSUE TITLE
[EKS] [Feature Request]: EKS Usage Metering

### ISSUE THREAD

**Issue by kamirendawkins** [aws/containers-roadmap#208]
**Tell us about your request**
EKS usage dashboard enabling operators to track resource spend by namespace or label to provide better usage visibility in multi-tenant clusters in regards to asset cost.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As an Infrastructure Team that hosts multiple multi-tenant clusters for internal teams, being able to associate the resource usage in terms of asset cost is a fair bit of effort. While it is possible to leverage resource metrics and math to render the results in a presentation layer is doable it would be easier on teams adopting EKS to have the report generated for them. It would also help teams give context and understanding to the capabilities Kubernetes has to reduce cloud costs, as well as help teams, identify areas of improvement.

**Are you currently working around this issue?**
Currently, we integrate our clusters with a SaaS offering as well as gather metrics via Prometheus and perform some napkin math.

**Additional context**
In an ideal world, it would be great to be able to associate all spend for an application in one single view. For example, if the pod labels where `app1` and we tagged ELBs and Aurora Databases with a cluster identifier and app identifier tag it would be great to pull those costs together to get a better picture of what exactly the application is costing.

I suppose this sounds exactly like the new GKE Usage Metering but I feel having the ability to relate usage from other managed services would be a bonus.

**Comment by krmayankk** [comment]
For context here is what gke supports https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering

**Comment by Vlaaaaaaad** [comment]
[Amazon CloudWatch Container Insights preview](https://aws.amazon.com/about-aws/whats-new/2019/05/cloudwatch-container-insights-for-eks-and-kubernetes-preview/) is a good step in this direction. Would that + billing tags support fix this?

**Comment by cristian-radu** [comment]
@countspongebob, any plans to roll out a native EKS usage metering solution in the near future? 

I feel like this is of great value to customers looking to adopt a soft multi-tenancy model.

**Comment by soupdiver** [comment]
Same here 🙋‍♂ 
Looking for a way to break down the costs of our clusters by multiple tenants (departments).
Which department would have to pay how much in the end of the month.
Ideally even having a way to assign different Billing Accounts to (Managed) Node Groups or so.

**Comment by SapientGuardian** [comment]
I requested something like this from our AWS Solutions Architect many months ago. I ended up deploying https://github.com/operator-framework/operator-metering/ , which works pretty well, but puts a burden on administration because the granularity it provides is outside of our standard AWS cost and usage reporting, against which we have already built internal tooling.

**Comment by mikestef9** [comment]
EKS now offers support for Kubecost. With this announcement, Amazon EKS customers can deploy an EKS optimized bundle of Kubecost for cluster cost visibility. This is available free of charge, and customers can get Kubecost support from AWS as part of their existing AWS support agreements.

Details:
- [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/cost-monitoring.html)
- [Announcement blog](https://aws.amazon.com/blogs/containers/aws-and-kubecost-collaborate-to-deliver-cost-monitoring-for-eks-customers/)

**Comment by vipin-mohan** [comment]
Granular cost visibility for EKS in the AWS Cost and Usage Reports (CUR) is now available. Customers can aggregate costs by cluster, namespace, and other Kubernetes primitives, and allocate costs to individual business units or teams for chargeback purposes.

What's New Post: https://aws.amazon.com/about-aws/whats-new/2024/04/aws-split-cost-allocation-data-amazon-eks/
Launch blog: https://aws.amazon.com/blogs/aws-cloud-financial-management/improve-cost-visibility-of-amazon-eks-with-aws-split-cost-allocation-data/
