### ISSUE TITLE
[ECS] [Console]: Support for creating scheduled tasks

### ISSUE THREAD

**Issue by genbit** [aws/containers-roadmap#2087]
### Community Note
* Amazon ECS console team is working on migrating remaining functionality from the classic console experience to the new one. This issue is created to provide transparency into the new ECS console roadmap and as a channel to provide feedback for the specific functionality.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Console functionality: Creating scheduled tasks

The new ECS console supports view and edit existing scheduled tasks. This issue is to track work in progress for adding functionality to Create new scheduled tasks.

**Comment by genbit** [comment]
Thank you for the feedback @rhyd42. Could you share more details, what do you mean by using "latest" for task definition version? For a scheduled task to always pick up latest available task definition? Could you provide examples, when this would be useful for you?

**Comment by rhyd42** [comment]
@genbit Yes, that's right, to use the latest task definition version available.

Our use case is a mix of scheduled tasks that run things like a monthly audit, and an ECS service running cron for more frequent jobs such as order confirmation emails etc. These all run the same docker image build through github actions.

When the codebase is updated, the service can be updated to use the right task definition version using "aws-actions/amazon-ecs-deploy-task-definition", but there's no equivalent for scheduled tasks.

When creating a scheduled task through the classic ECS console, the task definition version has to be selected, e.g. "145 (latest)" and this doesn't change when there's a new deployment. I can then edit the scheduled task through CloudWatch > Events > Rules or EventBridge > Buses > Rules and both have a radio button to choose between "latest" or a specific version. It would be handy if the ECS console used the same option, to avoid having to use two different consoles when creating a new scheduled task.

As for scheduleExpressionTimezone, I have a job that needs to run at 00:00 on the first of the month in our local timezone. As the scheduled tasks use UTC, I have the same job scheduled twice - once at 00:00 on the non-daylight savings months, and another at 23:00 on the last day of the month for the summer months. I have many other jobs that would benefit from the fixed schedule too. I believe this can be achieved through API / CLI, but it's not even included in the EventBridge console.

**Comment by genbit** [comment]
@rhyd42 I'll create a separate issue for your feature request. 

the main experience has been shipped to the new console.
