### ISSUE TITLE
[EKS] [Support]: Support for EKS 1.28

### ISSUE THREAD

**Issue by vipin-mohan** [aws/containers-roadmap#2095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like EKS support for Kubernetes v1.28.

In preparation for this I'd like to see EKS v1.28 added to the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) with a release date initially accurate up-to the quarter.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to use Kubernetes 1.28 on EKS and be aware of the release timeline to help plan for it.

**Are you currently working around this issue?**
How are you currently solving this problem?
N/A

**Additional context**
Change log: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md

**Attachments**
N/A

**Comment by rhbecker** [comment]
My org is planning a version upgrade on our clusters. Due to limited capacity, we typically can only afford to do this ~once/yr. We'd love for our next upgrade iteration to be a move to `v1.28`, to buy us an extra few months before we again need to act (ahead of EKS's end-of-support date for whatever version we land on).

Is there any chance this issue might get shipped within the next week or two, making `v1.28` an option for us, this round?

**Comment by mbevc1** [comment]
Hi @rhbecker! I'm not working for AWS, but since this is still in the Research phase and we don't have an updated EKS calendar yet, I highly doubt this will be released in the next couple of weeks.

**Comment by stevehipwell** [comment]
@mbevc1 I'm yet to see a new EKS release in the calendar until it's available, despite having the calendar track the pending versions as a request on each new K8s minor version.

I generally find the best signals to be the EKD-D release of the K8s minor version followed by the availability of an EKS optimised AMI for the K8s minor version.

**Comment by rhbecker** [comment]
Thanks to you both for the responses!

@mbevc1: I had a similar thought regarding this issue only having the `Researching` label applied to it, but then I found the issue for adding `v1.27` support (#1994), and noticed that it received the `Researching` and `Just Shipped` labels on the same day 😆.

@stevehipwell: Can you help me understand what `EKD-D` refers to? (My googling is so far failing me.) Where do you keep tabs on the "availability of an EKS optimised AMI"?

**Comment by stevehipwell** [comment]
@rhbecker [EKS-D](https://github.com/aws/eks-distro), and yes the link you posted is correct for the AMIs.

**Comment by mbevc1** [comment]
We have a calendar entry to expect 1.28 in September 2023 :partying_face:

**Comment by amedirr** [comment]
Amazon EKS now supports Kubernetes 1.28 please see these posts to learn more:
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-28/
https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-eks-distro-kubernetes-version-1-28/
