### ISSUE TITLE
EKS Kubernetes Version Updates

### ISSUE THREAD

**Issue by pauncejones** [aws/containers-roadmap#21]

**Comment by gtaylor** [comment]
How is this similar to or different from #24 ?

**Comment by micahhausler** [comment]
@gtaylor This is for an upgrade API, rather than creating clusters with specific versions of Kubernetes

**Comment by tabern** [comment]
https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-eks-adds-managed-cluster-updates-and-support-for-kubernetes/

**Comment by darrenhaken** [comment]
Does this upgrade the workers too?
