### ISSUE TITLE
[EKS] [request]: EKS optimized AMI for GPU support for CUDA10

### ISSUE THREAD

**Issue by mbelang** [aws/containers-roadmap#210]
**Tell us about your request**
EKS optimized AMI for GPU that support CUDA10 driver

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are currently doing some Machine Learning using GPUs and some of our code requires Tensorflow 1.13 and up which only support CUDA 10 drivers. Current EKS optimized AMI for GPU only support CUDA 9.2.

**Are you currently working around this issue?**
No, the libraries that we are using are not under our control (https://github.com/RasaHQ/rasa_nlu and https://github.com/RasaHQ/rasa_core).

**Comment by tabern** [comment]
Requires NVIDIA driver 410.104 or higher

**Comment by mbelang** [comment]
As tested with latest EKS AMI for GPU, the CUDA 10 drivers are there and we tested and it is working.

@tabern you can probably close this one. Thx

**Comment by tabern** [comment]
correct @mbelang 

The latest [EKS-Optimized GPU AMIs](https://docs.aws.amazon.com/eks/latest/userguide/gpu-ami.html) now have NVIDIA driver v410.104, which supports CUDA 10.
