### ISSUE TITLE
[ECS] [Service AutoScaling policy creation]: Service auto-scaling policy creation silently fails in new console experience

### ISSUE THREAD

**Issue by markhatton-axs** [aws/containers-roadmap#2103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Fix the creation of a service auto-scaling policy when updating a service definition via the console.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The only way to _successfully_ create a scaling policy in the ECS console at the moment is to create it in the _old_ console experience. The functionality ostensibly exists in the new console experience, but if you try to update a service that has no scaling policy by adding a new scaling policy in the new experience, it will make all the right noises, show success messages, but if you check the configuration, no scaling policy has actually been created. It is silently failing. This needs to be fixed before the old console is retired.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
No

**Attachments**
None

**Comment by genbit** [comment]
Hi @markhatton-axs we are investigating the issue, thanks for reporting it! Would you be able to provide steps to reproduce it? Or you can also reach out directly to me serggen@amazon.com to provide your account details, or create AWS support case, so we can take a look at issue details.

**Comment by markhatton-axs** [comment]
@genbit I will reach out to your privately since the easiest repro steps are not something I can share publicly here.

**Comment by markhatton-axs** [comment]
To confirm, this was resolved very quickly after the private messaging last year.
