### ISSUE TITLE
[ECS] [Select deployment type codedeploy in console]: unable to select codedeploy as the deployment type for new ECS console

### ISSUE THREAD

**Issue by monelgordillo** [aws/containers-roadmap#2112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
unable to select codedeploy as the deployment type for new ECS console

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Unable to select codedeploy as the deployment type for new ECS console.  I was able to select CodeDeploy in the old console.

**Are you currently working around this issue?**
I am using the old ECS console.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by pallymore** [comment]
Hello - we shipped CodeDeploy support recently, please give it a go and let us know if it works for you. Thanks!

**Comment by monelgordillo** [comment]
> Hello - we shipped CodeDeploy support recently, please give it a go and let us know if it works for you. Thanks!

Maybe its not in production yet? I don't see the CodeDeploy option within N. Virginia region.

**Comment by pallymore** [comment]
Hi - the option is nested under "Deployment options" in the Create Service page. Could you check if this is showing up for you? Thanks! 

![CleanShot 2023-11-15 at 10 00 23@2x](https://github.com/aws/containers-roadmap/assets/2566530/cd26b7ea-c94b-473a-a9c0-1fdd76e7e1e2)

**Comment by monelgordillo** [comment]
I see it.  I was able to try it out.

I guess the ECS Service console generates a CloudFormation stack now.  The old one did not generate a CloudFormation stack.

**Comment by pallymore** [comment]
Hi - yes, in the new console, all the newly created resources associated with the service like security groups, load balancers, target groups, listeners, code deploy application/deployment group are all created in the same CloudFormation stack. So when the stack is deleted, or when the service is deleted from the new console, everything will be cleaned up along with the service itself, while in the old console, customers had to delete these resources individually. 

Please let us know if you have any thoughts & feedback regarding the new console - we are continuously pushing out updates & improvements. 

Thanks!

**Comment by JohnPremKumar** [comment]
This only shown for new service. But if we want to change the deployment option from rolling to blue green or vice versa there is still no option in the console.

I think it would be better to have that also
