### ISSUE TITLE
[EKS]: Support for Kubernetes 1.14

### ISSUE THREAD

**Issue by whereisaaron** [aws/containers-roadmap#212]
**Tell us about your request**
Support for k8s 1.14 control plane and nodes

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Keep EKS clusters running supported releases on k8s and maintain security compliance requirements. It is hard because the EKS product is not keeping up with the k8s release cycle.

**Are you currently working around this issue?**
Making do with 1.11.x, which is, so last year 😆, and is [EOL **now** ~in 10 days~](https://kubernetes.io/docs/setup/version-skew-policy/#supported-versions) that 1.14 ~goes~ **is** GA.

**Additional context**
k8s 1.14 has been in beta release for about a month and ~goes~ went GA ~in 10 days~ on 25 March. Given the lead times we are seeing on [1.11](https://github.com/aws/containers-roadmap/issues/29)/[1.12](https://github.com/aws/containers-roadmap/issues/24)/[1.13](https://github.com/aws/containers-roadmap/issues/30) it would be nice to think AWS has the resource to be at least be testing 1.14 already, so it can make its way to customers in a timely manner. But it is not currently on the [road map](https://github.com/aws/containers-roadmap/projects/1).

~When~ **Now** 1.14 ~comes~ **is** out ~on 25 March~ [1.11 is not longer supported for security updates](https://kubernetes.io/docs/setup/version-skew-policy/#supported-versions), unless AWS is promising to back-port all security patches, EKS users have only 10 days left to upgrade clusters from 1.11 to 1.12, which is [not even available on EKS yet](https://github.com/aws/containers-roadmap/issues/24), to be on a supported release and maintain security compliance requirements.

I understand and appreciate AWS is operating a rigorous and careful release process. And that that is takes time and provides the huge benefit of offering a reliable upgrade process and a stable platform. But this rigorous approach appears to need to start earlier for upcoming releases than it is right now.

So to be clear, I am not requesting 1.14 now. I am requesting to get started on 1.14 soon, so that customers can have it well before 1.17 is released in ~8-9 months (and 1.14 is EOL)

**Comment by geerlingguy** [comment]
Note that 1.13 will need to be supported prior to 1.14, as Kubernetes masters need to be upgraded from minor to minor version (can't do a direct upgrade from 1.12 to 1.14). There is currently no issue in the containers-roadmap for 1.13.

**Comment by whereisaaron** [comment]
Issue #30 for 1.13 is in the "We're working on it" column @geerlingguy.

**Comment by whereisaaron** [comment]
Looking at the 1.14 meeting notes for today, bar some test flakes, it looks all 'green' for launch on 25 March.

![image](https://user-images.githubusercontent.com/1109585/54845425-a869bb00-4caf-11e9-817c-6e70959600a4.png)

**Comment by whereisaaron** [comment]
[v1.14 went GA today](https://developers.redhat.com/blog/2019/03/25/kubernetes-v1-14-what-you-need-to-know/).

**Comment by lukaszgryglicki** [comment]
Seems like we will need to wait a bit, there is no v1.13 yet, and v1.14 was release a long time ago...

**Comment by guitcastro** [comment]
1.14 Kustomize is very useful, we really appreciated if 1.14 this could be shipped soon

**Comment by whereisaaron** [comment]
It looks AWS/EKS is being more informative about release timings. 🎉 This AWS blog article suggests 1.14 will be not be available before September 2019, So about 6 months after it [went GA](https://kubernetes.io/blog/2019/03/25/kubernetes-1-14-release-announcement/). It looks like from my reading of the article the plan is to stay at that ~6 months behind GA for future versions.

https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/

**Comment by pawelprazak** [comment]
cool, clarification is good, on that note, will NLB fixes be backported to 1.13?

e.g. this one: https://github.com/kubernetes/kubernetes/pull/68422/commits/f052146a96193dc8d9b0afa9db7aa3c3651b2441

**Comment by whereisaaron** [comment]
I know supported versions and the lag between K8s GA and managed provider GA is discussed a lot here. Looking forward to 1.14, this this is I think the state of play across a range of providers.

- K8s supports: 1.13, 1.14. 1.15
- IBM supports: 1.12, 1.13, 1.14
- AWS EKS supports: 1.11, 1.12, 1.13 (1.14 in Sep, 1.11 support ends in Sep)
- Google GKE supports: 1.11, 1.12, 1.13 (1.14 in preview, 1.11 support until ~Aug/Sep?)
- Azure AKS supports: 1.10, 1.11, 1.12, 1.13 (1.14 in preview, 1.10 support until ~Jul/Aug, 1.11 support until ~Dec?)
- Redhat OpenShift supports: 1.9, 1.10, 1.11, 1.12, 1.13 (1.14 in Aug/Sep, 1.9/10 support until Oct, 1.12 support until Dec, 1.11 support until Jun 2022)
- DigitalOcean supports: 1.13, 1.14 (new kid)

The lag following a k8s GA release varies from 1-6 months, roughly breaking down as:
1. IBM and DigitalOcean targeting ~30 days after k8s GA
2. Google and Azure targeting ~3 months after k8s GA with preview access
3. AWS and Redhat targeting ~6 months after k8s GA

**Comment by pawelprazak** [comment]
> cool, clarification is good, on that note, will NLB fixes be backported to 1.13?
> 
> e.g. this one: [kubernetes/kubernetes@f052146](https://github.com/kubernetes/kubernetes/commit/f052146a96193dc8d9b0afa9db7aa3c3651b2441)

Also, any chance for NLB TLS support?
https://github.com/kubernetes/kubernetes/pull/74910

**Comment by tabern** [comment]
@pawelprazak we're not able to backport this into 1.14 upstream as it's a big set of feature changes. This will be available in 1.15

**Comment by pawelprazak** [comment]
Thank you for the answer, it's unfortunate to wait so long, but I appreciate the confirmation.

**Comment by bgagnon** [comment]
1.14 is now GA on Azure AKS

**Comment by InAnimaTe** [comment]
> Note that 1.13 will need to be supported prior to 1.14, as Kubernetes masters need to be upgraded from minor to minor version (can't do a direct upgrade from 1.12 to 1.14). ~There is currently no issue in the containers-roadmap for 1.13.~

Is there a way for people deploying fresh clusters to utilize 1.14 while others who want to upgrade wait? i.e. our team doesn't upgrade clusters, we just build new ones.

**Comment by devkid** [comment]
1.14 appeared in the [documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.14) but it's not available for new clusters nor for upgrades in our AWS accounts.

**Comment by InAnimaTe** [comment]
Maybe it takes a bit?? Announcement: https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-now-supports-kubernetes-version-1-14/

**Comment by mikestef9** [comment]
**Amazon Elastic Kubernetes Service (EKS) now supports Kubernetes version 1.14.6 for all clusters.**

Kubernetes version 1.14 highlights include stable support for [Durable Local Storage Management](https://kubernetes.io/docs/concepts/storage/volumes/#local) and [Pod Priority](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/), as well as the beta launch of [Pid Limiting](https://kubernetes.io/blog/2019/04/15/process-id-limiting-for-stability-improvements-in-kubernetes-1.14/). Learn more about Kubernetes version 1.14 in the Kubernetes project [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#kubernetes-v114-release-notes).

Learn more about the Kubernetes versions available for production workloads on Amazon EKS and how to update your cluster to version 1.14 in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html).

Notes:

- All EKS APIs support creating 1.14 clusters in all AWS regions with EKS today.
- The AWS console does not yet support creating EKS 1.14 clusters in all regions, we are rolling out console support for creating 1.14 clusters to all regions over the next week.
- eksctl support for K8s 1.14 is coming soon.
We will close this issue when 1.14 cluster creation is supported in the console in all regions.

**Comment by rparsonsbb** [comment]
Is there a timeline for availability of the Windows EKS node AMI?  Currently appears the latest version is 1.11.5?
