### ISSUE TITLE
[EKS] [request]: v1.10.1-eksbuild.3+ breaking change

### ISSUE THREAD

**Issue by ForbiddenEra** [aws/containers-roadmap#2152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
v1.10.1-eksbuild.3+ adds the `ready` statement to the default `corefile` and changes the readiness checks to use port `:8181`, where v1.10.1-eksbuild.2 and previous used `:8080` for both liveness and readiness.

This isn't immediately obvious or intuitive and is a breaking change for anyone providing their own `corefile` without that statement. 

**Which service(s) is this request for?**
EKS

**Comment by sjastis** [comment]
This is resolved in EKS add-on versions v1.9.3-eksbuild.6 and later and v1.10.1-eksbuild.6 and later. 
If you are supplying your own corefile then you'd need to add the ready plugin in the corefile as called out in the updated documentation - https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html
