### ISSUE TITLE
[ECS] [request]: Blue/Green deployment type doesn't available in new UI ECS services

### ISSUE THREAD

**Issue by farishdnt** [aws/containers-roadmap#2157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please support blue/green deployment type in new UI ECS when create Services.

**Which service(s) is this request for?**
Fargate, ECS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When create services in ECS Cluster, the deployment type just seeing rolling update, there's not available blue/green deployment in new UI ECS. but in the old UI, I can see the blue/green deployment type in configuration Services.

**Are you currently working around this issue?**
create Services with using blue/green deployment for codedeploy.

**Old UI**
![image](https://github.com/aws/containers-roadmap/assets/38666741/d770b4bb-0e2d-497c-96d4-c6bae18a205e)

**New UI**
![image](https://github.com/aws/containers-roadmap/assets/38666741/e20e47a7-4ef6-444d-86e8-1da8d31b823f)

**Comment by yahya-uddin** [comment]
It's also worth mentioning the old UI sometimes has a bug where the blue/green deployment type is greyed out.

Currently only way to do Blue/Green deployments is through the CLI:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-blue-green.html

Very fustrating

**Comment by genbit** [comment]
The new console experience now has support for the Code Deploy deployments.
