### ISSUE TITLE
[EKS] [request]: Independent control plane and cluster addons management

### ISSUE THREAD

**Issue by cpoole** [aws/containers-roadmap#217]
**Tell us about your request**
I would like to be able to install/upgrade/configure the control plane version (1.11-eks.n) and the cluster addons (vpc cni, CSI driver, kube-dns) versions independently.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to have a more consistent cluster instantiation and cluster upgrade process. I want to know that regardless of the timing in AWS release cycle I can declaratively state the components present within my cluster and have them come online without any guesswork. 

This should allow me to also specify null versions for each cluster addon and have amazon present a cluster _without_ any addons present. This would allow me to fully control the versions of these services outside of amazons release process

**Are you currently working around this issue?**
Currently we delete all resources on first cluster start and install our own from helm charts. 

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by dawidmalina** [comment]
It's very good idea! :+1:

**Comment by tabern** [comment]
This should be solved by #252
