### ISSUE TITLE
[ECS] [Bug]: Getting error while updating the service with an empty string "" for the namespace name.

### ISSUE THREAD

**Issue by rajprafull** [aws/containers-roadmap#2172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Further from the Aws document [1], "If you update the service with an empty string "" for the namespace name, the cluster configuration for Service Connect is removed. Note that the namespace will remain in Cloud Map and must be deleted separately." However this is not happening here.

[1]  https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ClusterServiceConnectDefaultsRequest.html

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When trying to run below command getting error:

$ aws ecs update-cluster --cluster <clustername> --service-connect-defaults namespace=""

	An error occurred (InvalidParameterException) when calling the UpdateCluster operation: Namespace () must match ^[!-~&&[^<>/"]]{1,1024}$.

**Are you currently working around this issue?**
NA

**Additional context**
Identified it as a bug.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jwang186** [comment]
We have identified this bug. ECS team is actively working on fixing it.

**Comment by sborsje** [comment]
Seems like this was fixed! :+1:

**Comment by kshivaz** [comment]
Closing as this is fixed now.
