### ISSUE TITLE
New EKS Region : Beijing

### ISSUE THREAD

**Issue by wholroyd** [aws/containers-roadmap#219]
**Tell us about your request**
New region support in Beijing, China (cn-north-1)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to own less and use managed service where we can, and an automated deployment using tooling for one region, and other tooling for literally everywhere else comes with a resource cost.

**Are you currently working around this issue?**
Using Kubespray to stand up full Kubernetes deployment using automation not normally used by our team in other regions.

**Additional context**
None

**Attachments**
None

**Comment by karthimohan** [comment]
Hi, do we an approximate date for this?

**Comment by gaochundong** [comment]
still coming soon?

**Comment by qqbuby** [comment]
any updates?

**Comment by rbse** [comment]
any updates ?

**Comment by mikestef9** [comment]
Happy to announce that EKS is now generally available in the AWS Beijing (cn-north-1) region!

- [What's new post](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-eks-now-available-aws-china-beijing-sinnet-ningxia-nwcd/)
- [EKS documentation & AMIs](https://docs.amazonaws.cn/en_us/eks/latest/userguide/eks-optimized-ami.html)
