### ISSUE TITLE
[EKS] : Support for EKS 1.29

### ISSUE THREAD

**Issue by vipin-mohan** [aws/containers-roadmap#2191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
I'd like EKS support for Kubernetes v1.29.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to use Kubernetes 1.29 on EKS and be aware of the release timeline to help plan for it.

**Are you currently working around this issue?**
How are you currently solving this problem?
N/A

**Additional context**
Anything else we should know?
Change log: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md

**Attachments**
N/A

**Comment by sidick** [comment]
Unfortunately they haven't updated the addons fully yet, there's no recommended version of adot for 1.29 yet

**Comment by prajaysingh** [comment]
Hello Team, Based on EKS release announcement, sidecar containers are available in Amazon EKS clusters. However, sidecar containers aren't supported with IAM roles for service accounts or EKS Pod Identity. Can you please confirm if there is going to be any fix to be able to use IAM roles for service accounts with sidecar feature in EKS 1.29?

**Comment by mikestef9** [comment]
See https://github.com/aws/amazon-eks-pod-identity-webhook/pull/209

It will take several weeks before this change is rolled out across the EKS fleet.

**Comment by ceastman-r7** [comment]
Status of rollout?

**Comment by dims** [comment]
all done.
