### ISSUE TITLE
[EKS] [request]: Allow EKS control plane to run on internal vpc addresses

### ISSUE THREAD

**Issue by trondhindenes** [aws/containers-roadmap#220]
**Tell us about your request**
The current model where EKS control plane is running outside the VPC is problematic because it doesn't allow reaching back into the worker node networks unless workers are running on public ips. This is a deal-breaker for customers who don't want to run workers with public ip addresses. I don't know if the new "API server endpoint access" addresses this, but I suspect that it won't, since changing it won't affect the "outbound" source ip for the control plane. 

Simply put, we need tighter network integration between control plane and workers, also when _not_ using the aws-supplied vpc-cni plugin (since that plugin limits binpacking on smaller nodes)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
EKS is too much of a black box at the moment, with too many limitations around networking. I'm trying to spin up a cluster with internal-only (no public) worker nodes and enable the metrics-server.

**Are you currently working around this issue?**
No.

**Comment by devkid** [comment]
No idea what you are talking about, the EKS control plane *is* running in a VPC (you need to select the VPC, subnets and security groups) and does *not* require the worker nodes to have public IPs for reaching back into them (like for logs, exec, etc.).

**Comment by trondhindenes** [comment]
Thanks. In that case I have more research to do. Closing.

**Comment by whereisaaron** [comment]
@trondhindenes try creating with [`eksctl` and the `--node-private-networking`](https://github.com/weaveworks/eksctl#vpc-networking) option to get a working example of this.
