### ISSUE TITLE
[Fargate] [request]: ARM64 Spot market

### ISSUE THREAD

**Issue by danielcompton** [aws/containers-roadmap#2202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I want to be able to run ARM64 containers on Fargate Spot.

**Which service(s) is this request for?**

Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We have ARM64 containers which could be run on the spot market as they are tolerant of disruptions, but can't because there is no ARM64 Fargate Spot.

**Are you currently working around this issue?**

Not using spot, or running on x86 Fargate Spot.

**Additional context**

https://www.reddit.com/r/aws/comments/17maney/spot_ecs_fargate_instances_on_arm64/k7oqlqy/

From @nathanpeck:

> I'm on the container services team at AWS. I can assure you that Fargate Spot + ARM64 is not a thing (yet). What will happen is in your service's event tab it will say that it was unable to find capacity to launch any tasks. The Spot market is basically for selling unused compute capacity (often powered by older generations of hardware) at a discount. Graviton and ARM64 instances are so new and so popular that we don't really have extra unused compute capacity to offer at a Spot discount.

**Comment by dnorth98** [comment]
Is this not a duplicate of https://github.com/aws/containers-roadmap/issues/1594 ?

**Comment by danielcompton** [comment]
Yup, thanks!
