### ISSUE TITLE
[ECS] [request]: Cannot create a task definition linking 2 containers using new ECS console

### ISSUE THREAD

**Issue by marc-enseo** [aws/containers-roadmap#2209]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

The old AWS console had the ability to link container together.  The new one does not have that option

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

No loss of functionality compare to existing console

**Are you currently working around this issue?**
How are you currently solving this problem?

Using then old console but on December 4th this is going away

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by henriquesantanati** [comment]
I can see the link option from the new console. @marc-enseo, could you please confirm if this was fixed for you? If not, can you please inform what is missing from your point of view? Thanks!

**Comment by marc-enseo** [comment]
Yes, I saw it recently.  Was told initially that AWS did not find that feature to be essential as docker was deprecating it but seems to have made it.
