### ISSUE TITLE
[EKS] [request]: Pull image in private network for the Amazon CloudWatch Observability add-on

### ISSUE THREAD

**Issue by ChauAnhTuan** [aws/containers-roadmap#2210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
I want to pull the images in private networks like the CoreDNS, VPC-CNI, ...

**Which service(s) is this request for?**
EKS, ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
No
**Additional context**
No

**Comment by lisguo** [comment]
There is now a helm-chart to install container insights and application signals: https://github.com/aws-observability/helm-charts/tree/main/charts/amazon-cloudwatch-observability

This is the equivalent of the Amazon CloudWatch Observability EKS Add-On

**Comment by sky333999** [comment]
Hello,
The recent versions of the `amazon-cloudwatch-observability` EKS add-on should only pull from private ECR registries as outlined here: https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html

Please try updating to the latest version of the add-on and let us know if you still face any issues.
