### ISSUE TITLE
[ECR] [BUG]: Cannot pull docker-hub official images with ECR Pull-through

### ISSUE THREAD

**Issue by patriciocostilla** [aws/containers-roadmap#2211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I've configured the new docker-hub pull-through cache rule for ECR. It works fine while downloading images like [bitnami/postgresql](https://hub.docker.com/r/bitnami/postgresql), but if I try to download one of the official images like [alpine](https://hub.docker.com/_/alpine) i've got a docker auth error

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm just testing this new feature, because I will like to implement it. 

**Are you currently working around this issue?**
We can solve this by using a public-ecr rule of the pull-through cache feature, because we can target the [docker/library/alpine](https://gallery.ecr.aws/docker/library/alpine) image, for example. But I think we should be able to download this images directly from Dockerhub. 

**Additional context**
I will use this space to write an example, targeting the bitnami/mongodb image and the official python image:

First, let's check that the rule is working:

```sh
➜  ~ docker run --rm -it -v ~/.aws:/root/.aws amazon/aws-cli ecr validate-pull-through-cache-rule --ecr-repository-prefix docker-hub
{
    "ecrRepositoryPrefix": "docker-hub",
    "registryId": "xxxxyyyyzzzz",
    "upstreamRegistryUrl": "registry-1.docker.io",
    "credentialArn": "arn:aws:secretsmanager:us-east-1:xxxxyyyyzzzz:secret:ecr-pullthroughcache/dockerhub-XXXXXX",
    "isValid": true,
    "failure": ""
}
```

Now let's try to download the images:

```sh
➜  ~ docker pull xxxxyyyyzzzz.dkr.ecr.us-east-1.amazonaws.com/docker-hub/bitnami/mongodb
Using default tag: latest
latest: Pulling from docker-hub/bitnami/mongodb
91ff53eb4656: Pull complete 
Digest: sha256:5ff367bc2bd7435b15754ffcc1f3c90e13a5ebe0269f29a2332ae1d131ef82a4
Status: Downloaded newer image for xxxxyyyyzzzz.dkr.ecr.us-east-1.amazonaws.com/docker-hub/bitnami/mongodb:latest
xxxxyyyyzzzz.dkr.ecr.us-east-1.amazonaws.com/docker-hub/bitnami/mongodb:latest
```

```sh
➜  ~ docker pull xxxxyyyyzzzz.dkr.ecr.us-east-1.amazonaws.com/docker-hub/python         
Using default tag: latest
Error response from daemon: pull access denied for xxxxyyyyzzzz.dkr.ecr.us-east-1.amazonaws.com/docker-hub/python, 
repository does not exist or may require 'docker login': denied: The authentication to the upstream registry failed. 
Verify that the credentials are correct, that the required access is provided, and try again.
```

**Attachments**
None

**Comment by empeekdev** [comment]
+1. We have same issue. All non-official images that can be pulled using <username>/<reponame> reference pulling successfully.

**Comment by z0rc** [comment]
This isn't an issue with registry, you're dealing with docker-cli default behavior. Docker cli allows to use "short" form when referencing images in registry. Default namespace is "official" `library`, default url is `docker.io`. If you're referencing image using non-default registry url, you *must* specify namespace, even if it's default one.

That being said, `docker pull xxxxyyyyzzzz.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/python` works just fine.

**Comment by patriciocostilla** [comment]
Oh I see, so sorry that I missed that. 

Made that change and worked like a charm. 

Thank you so much! Will close this issue

**Comment by juan-vg** [comment]
Short forms are used everywhere. The ECR Pull through cache should be transparent, and it should be able to deal with it when just the registry is changed. Having to change the image names just to overcome this issue is completely against cache/proxy transparency. From my POV this is a no-go for ECR Pull through cache.

**Comment by nwz-zooneon** [comment]
FYI. [official docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-working-pulling.html#:~:text=Quay-,Docker%20Hub,-GitHub%20Container%20Registry) for ECR pull through cache when pulling Docker Hub official image
