### ISSUE TITLE
[EKS] [kube-proxy addon]: Adding custom label and annotations on kube-proxy Addon

### ISSUE THREAD

**Issue by avnerv** [aws/containers-roadmap#2216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Adding custom annotations like `cloud.xxx.ai/owner-display-name: infra` on kube-proxy addon so that it can be put on pods.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It seems like there is potentially a missing setting on the DaemonSet, the custom annotation via the `configuration_values`.
The example terraform configuration:
```
resource "aws_eks_addon" "kube_proxy" {
  cluster_name      = aws_eks_cluster.eks.id
  addon_name        = "kube-proxy"
  addon_version     = "v1.25.11-eksbuild.2"
  resolve_conflicts = "OVERWRITE"
  configuration_values = jsonencode({
    podAnnotations = {
      "cloud.xxx.ai/owner-display-name" = "infra"
    }
  })
}
```
The terraform error message:
```
│ Error: error updating EKS Add-On (hadc-xxxxx-eks:kube-proxy): InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "1c971b0c-bb71-400e-b8dc-f4b64df2180c"
│   },
│   AddonName: "kube-proxy",
│   ClusterName: "hadc-xxxxx-eks",
│   Message_: "ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]"
│ }
│ 
│   with module.eks_cluster.aws_eks_addon.kube_proxy,
│   on ../../modules/aws/eks/cluster/addon.tf line 14, in resource "aws_eks_addon" "kube_proxy":
│   14: resource "aws_eks_addon" "kube_proxy" {
│ 
╵
Releasing state lock. This may take a few moments...
```

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by Raj-Popat** [comment]
@mikestef9 Any updates on this. Do we have any timeline when the proposed change would get added?

**Comment by ri-roee** [comment]
Wanted to follow up on this and say that this did work for me, might be a stale issue

**Comment by avnerv** [comment]
> Wanted to follow up on this and say that this did work for me, might be a stale issue

for what kube-proxy addon version?

**Comment by ri-roee** [comment]
`v1.16.2-eksbuild.1` on EKS 1.25

Config (used for DD scrape of prometheus-compatible metrics endpoint):
```
resource "aws_eks_addon" "vpc_cni_addon" {
  cluster_name      = module.eks.cluster_id
  addon_name        = "vpc-cni"
  addon_version     = data.aws_eks_addon_version.vpc_cni_latest.version
  resolve_conflicts = "OVERWRITE"

  configuration_values = jsonencode({
    podAnnotations = {
      "prometheus.io/scrape" = "true"
    }
  })
}
```

**Comment by avnerv** [comment]
> v1.16.2-eksbuild.1 on EKS 1.25
Config (used for DD scrape of prometheus-compatible metrics endpoint):

sorry but not sure i follow, the example you provided above is for vpc-cni, whereas the issue we're discussing pertains to kube-proxy

**Comment by ri-roee** [comment]
My bad, copied the wrong config. Same concept applies to the `kube-proxy` addon

**Comment by avnerv** [comment]
> My bad, copied the wrong config. Same concept applies to the `kube-proxy` addon

for which version? in `v1.27.8-eksbuild.4` is not supported yet

```
│ Error: error updating EKS Add-On (test-eks:kube-proxy): InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "fb118817-2124-4c1a-b9a2-d1d93c1abeb7"
│   },
│   AddonName: "kube-proxy",
│   ClusterName: "test-eks",
│   Message_: "ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]"
│ }
```

**Comment by suankan** [comment]
Same problem happens when trying to apply `podAnnotations` for the aws-efs-csi-driver EKS Addon via the Terraform:

```
resource "aws_eks_addon" "efs" {
  cluster_name = aws_eks_cluster.kafka_connect.name
  addon_name   = "aws-efs-csi-driver"

  configuration_values = jsonencode({
    podAnnotations = {
      "eks.amazonaws.com/role-arn" = "${aws_iam_role.AmazonEKS_EFS_CSI_DriverRole.arn}"
    }
  })
}
```

And when I do `terraform apply` I'm getting this error:
```
╷
│ Error: updating EKS Add-On (gnp-kafka-connect:aws-efs-csi-driver): InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "38475613-24be-4ca8-b607-c2feb89b4d19"
│   },
│   AddonName: "aws-efs-csi-driver",
│   ClusterName: "gnp-kafka-connect",
│   Message_: "ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]"
│ }
│ 
│   with module.eks.aws_eks_addon.efs,
│   on ../modules/eks/main.tf line 139, in resource "aws_eks_addon" "efs":
│  139: resource "aws_eks_addon" "efs" {
│ 
```

**Comment by sjastis** [comment]
This is now supported with EKS kube-proxy add-on version, starting with Kube-proxy v1.25.16-eksbuild.3, v1.26.13-eksbuild.2, v1.27.10-eksbuild.2, v1.28.6-eksbuild.2, v1.29.1-eksbuild.2
Doc Updated: (https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)

**Comment by karthichu** [comment]
Can following change be backported to 1.29 - https://github.com/kubernetes/kubernetes/blob/release-1.31/pkg/proxy/topology.go#L172?

**Comment by acookin** [comment]
How do I get around the json schema validations, if this is, in fact, supported.

In terraform, I have:
```
resource "aws_eks_addon" "kube-proxy" {
  cluster_name      = aws_eks_cluster.cluster.name
  addon_name        = "kube-proxy"
  addon_version     = "v1.29.0-eksbuild.1"
  resolve_conflicts = "OVERWRITE"
  configuration_values = jsonencode({
    podAnnotations = {
      "app"           = "internal-kube-system"
    }
  })
}
```
And get this error when trying to apply:
```
Error: updating EKS Add-On (graphql:kube-proxy): operation error EKS: UpdateAddon, https response error StatusCode: 400, RequestID: 9f02fb8d-08d0-4527-a69d-aabe75159c06, InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.podAnnotations: is not defined in the schema and the schema does not allow additional properties]
```
