### ISSUE TITLE
[EKS] [Feature Request]: Monitoring Memory and Disk Metrics

### ISSUE THREAD

**Issue by cdenneen** [aws/containers-roadmap#222]
Copying request from @nicholasgcoles here: https://github.com/awslabs/amazon-eks-ami/issues/173

**What would you like to be added:**
Seeing as we specify an AMI for the worker nodes I think it would be great if the official eks ami supported exporting of memory and disk metrics. Instead of having to create a custom AMI and then following this guide below.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

**Why is this needed:**
If using Cloudwatch, these are super useful for alerts and monitoring. Perhaps this is an unreasonable request but I think it would be great.

@micahhausler asked to have this created here so doing so as I've gotten bitten by evicted pods because of `[DiskPressure]`. Along with other monitoring open issues really need better insight into the worker nodes.

**Comment by bradleyess** [comment]
This makes total sense - currently baking a custom AMI asking why!?

**Comment by mikestef9** [comment]
AWS recently went GA with Container Inights

https://aws.amazon.com/blogs/aws/operational-insights-for-containers-and-containerized-applications/

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-reference-performance-entries-EKS.html

**Comment by tabern** [comment]
This is possible with AWS CloudWatch Container Insights. Additionally, the EKS Console now shows basic node stats like memory allocation in the node detail page.
- https://docs.aws.amazon.com/prescriptive-guidance/latest/implementing-logging-monitoring-cloudwatch/kubernetes-eks-metrics.html
