### ISSUE TITLE
[Fargate] [request]: Add support for Graviton3

### ISSUE THREAD

**Issue by FalkWoldmann** [aws/containers-roadmap#2230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for Graviton3

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
AWS Graviton3 processors offer significant improvements in performance compared to Graviton2. On the AWS ARM page, Graviton3 is recommended for general workloads [0], so it would also be suitable for Fargate imo. Since Graviton4 was recently unveiled, it would also be nice to catch up. 

**Are you currently working around this issue?**

**Additional context**

**Attachments**
[0] - https://aws.amazon.com/ec2/graviton

**Comment by BwL1289** [comment]
Looking forward to this. Is there an ETA?

**Comment by BwL1289** [comment]
Following up - is there an ETA? Also [linking my Bottlerocket/Amz Linux 2023 request here](https://github.com/aws/containers-roadmap/issues/2285) for convenience.

**Comment by herrhound** [comment]
We added Graviton 3 to Fargate fleet across. Resolving issue.

**Comment by xxdd13** [comment]
> We added Graviton 3 to Fargate fleet across. Resolving issue.

Thank you. Are there any documentations or announcements available?

Also I’m curious if Graviton2 is still part of the fleet, and is it possible to use Graviton3 exclusively?

**Comment by Frtrillo** [comment]
> @xxdd13 I was unable to find any other announcements or documentation changes — the comment on this thread was seemingly the only announcement.
> 
> I also was unable to get a public answer from AWS regarding the ECS on Fargate fleet sooooo I tested it myself: in early October the ECS on Fargate fleet was using both Graviton2 and Graviton3, for both Spot and On-Demand. Depending on the time of day and the size of the task the split was `rand(30%, 100%)` 😅 AWS always optimizes and evolves the fleet so I would always expect changes and flux 🤷
> 
> **EDIT**: here are some testing screenshots I shared with some folks in early October:
> 
> ECS on Fargate ARM Spot 1vCPU and 2GB in early-morning `us-east-1` being 50-50 Graviton2 and Graviton3: <img alt="ecs-on-fargate-spot-us-east-1-morning" width="1058" src="https://private-user-images.githubusercontent.com/5440007/391971785-ccbf77af-2980-45ee-920a-be2d6052fc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgyMDksIm5iZiI6MTczMzkxNzkwOSwicGF0aCI6Ii81NDQwMDA3LzM5MTk3MTc4NS1jY2JmNzdhZi0yOTgwLTQ1ZWUtOTIwYS1iZTJkNjA1MmZjMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDlkYmY1NGI3YmQzYmQwMGE3MTQyNTc5MjMxYTY0MTNkZjUwZDUyMTdiMzIzYWFlNjgwNzBlYTE0NDcwMDk0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f_nDIw69w7r-AF_9GN19-LAvbiuw1IzXuyMmsq8zCeE">
> 
> ECS on Fargate ARM On-Demand 1vCPU and 2GB in early-morning `us-east-1` being 100% Graviton3: <img alt="ecs-on-fargate-ondemand-us-east-1-morning" width="1048" src="https://private-user-images.githubusercontent.com/5440007/391971801-acf2c469-6d85-4d1f-a1b6-19dbeda36b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgyMDksIm5iZiI6MTczMzkxNzkwOSwicGF0aCI6Ii81NDQwMDA3LzM5MTk3MTgwMS1hY2YyYzQ2OS02ZDg1LTRkMWYtYTFiNi0xOWRiZWRhMzZiN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZiOTE4MjUxNDUxMmIzNzM3YmM5MTkzOTE2MDg3MzY0YjczNDgxM2I3NWFlMGU4OTQyNDQ5NWNhODAyNTQ0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XnhBU7jvidTXbnJVKLEpx43XSHjcnVX9nTe-bzh2EDk">
> 
> ECS on Fargate ARM On-Demand 1vCPU and 2GB in evening `eu-west-1` being 100% Graviton3: <img alt="ecs-on-fargate-ondemand-eu-west-1-evening" width="1040" src="https://private-user-images.githubusercontent.com/5440007/391971807-21f4893e-4dfc-47a6-88fb-87e05a7c9242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgyMDksIm5iZiI6MTczMzkxNzkwOSwicGF0aCI6Ii81NDQwMDA3LzM5MTk3MTgwNy0yMWY0ODkzZS00ZGZjLTQ3YTYtODhmYi04N2UwNWE3YzkyNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODkzZDVjNTQ3MjM5ZjdiYTExM2QzMTRkMmY3MWE4Y2ZiMmU2ZWRmZjU5YmE5NmY2ZGY5ZmRmMTc3NDAxN2NmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QeZzktp9xUYxHcxMWZDJxazcriswdIgcR-2YhhIJsYU">
> 
> ECS on Fargate ARM Spot 1vCPU and 2GB in mid-day `us-east-1` being 50-50 Graviton2 and Graviton3: <img alt="ecs-on-fargate-spot-us-east-1-midday" width="1546" src="https://private-user-images.githubusercontent.com/5440007/391971810-7ed16dc5-bcdf-491f-a606-9bd7292b3ae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgyMDksIm5iZiI6MTczMzkxNzkwOSwicGF0aCI6Ii81NDQwMDA3LzM5MTk3MTgxMC03ZWQxNmRjNS1iY2RmLTQ5MWYtYTYwNi05YmQ3MjkyYjNhZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU5YmY0YjJiNWY1OGM3YmZhNTgxODNkYmRjZWEwYWQ2ODQ3NjE3NjNkOTQzNWNmOGY2MDNlYzBkNTVmZTRkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IOt1jvAux9HJbXVpxSR_X0w58WxzAVMXximagwiRUjI">
> 
> ECS on Fargate ARM On-Demand 1vCPU and 2GB in mid-day `us-east-1` being 100% Graviton3: <img alt="ecs-on-fargate-ondemand-us-east-1-midday" width="1564" src="https://private-user-images.githubusercontent.com/5440007/391971818-bfa35b79-feeb-4f93-92c6-13a1e22b1d84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgyMDksIm5iZiI6MTczMzkxNzkwOSwicGF0aCI6Ii81NDQwMDA3LzM5MTk3MTgxOC1iZmEzNWI3OS1mZWViLTRmOTMtOTJjNi0xM2ExZTIyYjFkODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA0OGJiMWUwODIyOTU4ZWVlZmJmOGI4NjRiMTljMWZlNjY0OWZlZmNkMGZkNmIyM2JjYzFhYmE5ZTI4ODM5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.626E2HQezMssVba4CkVhMNYsD-uVHaAAZSazr8jCOEY">
> 
> ECS on Fargate ARM On-Demand **4vCPUs and 10GBs** in mid-day `us-east-1` being 70-30 Graviton2 and Graviton3: <img alt="ecs-on-fargate-ondemand-us-east-1-midday-large" width="1545" src="https://private-user-images.githubusercontent.com/5440007/391971824-6eb08930-bfa6-4263-a9a7-f3d93816d3bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgyMDksIm5iZiI6MTczMzkxNzkwOSwicGF0aCI6Ii81NDQwMDA3LzM5MTk3MTgyNC02ZWIwODkzMC1iZmE2LTQyNjMtYTlhNy1mM2Q5MzgxNmQzYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE1MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FkYmUwYjIwZmNjOTE2MGZkM2FjYjRkMDAyN2RkZDMyMTQ1MzViNWYzYjI4YWZkZmYxNjU4MjJmMWVhYzFjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F_LSJ7Trq7T-pEUkWeSV-5NDFUe9kUlXnXt1ZNjB9nA">
> 
> Again, this was only a **handful of super-small tests** so don't trust them too much! Still, they provided valuable information and they seem to be matching with real-life usage reports I saw/am seeing 🤷

Thanks for the checks!
Still fleet enhancements from Amazon looks quite slow. Graviton4 has been out for half a year and we still are using a mix of graviton2 and no sight of graviton, and fargate isn't cheap

**Comment by adrian-skybaker** [comment]
The lack of choice to opt-in to the faster tiers is the issue, not price. At the moment if you want Graviton4 or to guarantee Graviton3, your have to resort to EC2 instances. The choice to launch newer generations on EC2 first and then quietly drip-feed these into Fargate *years* later creates a false choice between modern cpus vs serverless compute.
