### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.19 on Enhanced Vulnerability Scan - Inspector

### ISSUE THREAD

**Issue by Fran-Rg** [aws/containers-roadmap#2237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
ECR Scan for Alpine 3.19

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Alpine SecDB added version 3.19, please see https://secdb.alpinelinux.org/v3.19/ (supporting vulnerability data)

**Are you currently working around this issue?**
Unable

**Additional context**
Link to:
https://github.com/aws/containers-roadmap/issues/1959

**Comment by rgoltz** [comment]
Confirmed (Alpine 3.19 with AWS ECR Enhanced Scanning enabled):
![image](https://github.com/aws/containers-roadmap/assets/16392819/0239d0bc-1787-40a4-9333-d71507b90ac7)

**Comment by rgoltz** [comment]
I've re-tested the scan of an Alpine 3.19 image using AWS ECR Enhanced Scanning in region eu-central-1. **It's working now!**

![image](https://github.com/aws/containers-roadmap/assets/16392819/64ac938e-c37d-47aa-b3f1-96e6376021f9)
![image](https://github.com/aws/containers-roadmap/assets/16392819/765665c5-3092-4b2b-a56c-e62ab6fa63b0)

Thanks you, @smoell for the trigger to retry it now ❤️. It would be great, if the ECR/Inspector team would inform us via the github issue #2237 here as well and also follow & participate at the common discussion here: https://github.com/aws/containers-roadmap/issues/1959

**Comment by bradg-aws** [comment]
Thanks for the request. Alpine 3.19 is supported in both enhanced scanning (https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr) and basic scanning (https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html#image-scan-basic-support-operating-systems).
