### ISSUE TITLE
[EKS] [request]: Amazon EKS optimized Amazon Linux 2023 AMI

### ISSUE THREAD

**Issue by delvinguzman** [aws/containers-roadmap#2240]
Is there a timeline for the implementation of an EKS optimized AL2023 AMI? Would this EKS optimized AMI be available before the Amazon Linux 2 EOL on 2025?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by delvinguzman** [comment]
Hi @mikestef9, would you be able to address any of the questions on the description for planning purposes? Thanks!

**Comment by mikestef9** [comment]
We are working on this. Best place to follow for updates is the issue in EKS AL AMI repo https://github.com/awslabs/amazon-eks-ami/issues/1385

**Comment by ptailor1193** [comment]
Hi Folks, we have an exciting update on this. Amazon Linux 2023 (AL2023) is now available for testing in Tech Preview for self managed nodes, and for Managed Node Groups (MNG) and Karpenter nodes via a custom AMI. For more information on using the Tech Preview AMI, see our [Github Announcement](https://github.com/awslabs/amazon-eks-ami/issues/1672).

**Comment by aravind-jl** [comment]
Amazon has releases eks optimized ami with AL2023: https://aws.amazon.com/about-aws/whats-new/2024/02/amazon-eks-support-linux-2023/

But still its not available for gpu based instances

**Comment by mikestef9** [comment]
AL2023 standard AMIs are launched. We are working on AL2023 GPU based AMIs for both Neuron and NVIDIA. Going to close this issue, can you open a separate issue to request and track AL2023 GPU AMIs
