### ISSUE TITLE
[EKS] [request]: Include get/list secrets in EKS access entry ViewPolicy

### ISSUE THREAD

**Issue by vennemp** [aws/containers-roadmap#2244]
Love the new direct integration with EKS access policies.  Just would like the ability to create custom policies OR add get and list secrets in default ViewPolicy.  I have an app that needs read access to secrets and would like to not give it Write access.  
<img width="1057" alt="image" src="https://github.com/aws/containers-roadmap/assets/26049891/631aabda-0549-4e2d-b1a2-6a19a3a97b7a">
<img width="1232" alt="Screenshot 2023-12-19 at 5 19 15 PM" src="https://github.com/aws/containers-roadmap/assets/26049891/35f3f5d1-212d-44c2-a5e8-2b5b41c53b5b">

**Comment by mikestef9** [comment]
Seems like a reasonable request, we could potentially introduce a new read policy with slightly elevated permissions. Will move this to researching.

**Comment by stevehipwell** [comment]
@mikestef9 an admin read-only policy (read access to all resources) would be useful for automation. I'm not sure if there is much value in managing cluster access outside of the native K8s RBAC, but without an admin read-only policy it's not even an option we could explore.

**Comment by ofirc-wiz** [comment]
@vennemp this will be an awesome feature and bring EKS closer to other managed Kubernetes services in terms of ease of access. Looking forward to it!

**Comment by mikestef9** [comment]
We added a new policy called `AmazonEKSAdminViewPolicy` which is a read only policy for any K8s resource. A new request can be opened if any users still desire support for custom policies.

**Comment by vennemp** [comment]
Awesome! @mikestef9 does it include custom resources?

**Comment by pdeva** [comment]
@mikestef9 is it possible to restrict this policy to *not* read secrets. we want to apply this to logged in AWS Identity Center users to see k8s resources from the aws console, but we dont want those users to read contents of k8s secrets.

**Comment by mikestef9** [comment]
Yes, this includes custom resources. It's equivalent to get/list/watch on any K8s resource.

@pdeva what is missing from the previous non admin AmazonEKSViewPolicy that doesn't meet your requirements?

**Comment by ofirc** [comment]
@mikestef9 this feature is stellar, thanks for that!
There is a clear mapping between the [AWS Access policy permissions](https://docs.aws.amazon.com/eks/latest/userguide/access-policies.html#access-policy-permissions) and the [Kubernetes ClusterRoles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles), so for example AmazonEKSEditPolicy maps to admin, and AmazonEKSViewPolicy maps to view.

However, there doesn't seem to be a Kubernetes ClusterRole that is equivalent to AmazonEKSAdminViewPolicy, and it would be nice to document this exception and understand what it maps to.

Thanks a lot again!

**Comment by vennemp** [comment]
@ofirc https://docs.aws.amazon.com/eks/latest/userguide/access-policies.html

It's read access to * which would capture custom resources. 

The regular view policies seems to only have read access to default objects.

**Comment by ofirc** [comment]
@vennemp thanks for the comment! I understand and appreciate what the access allows, I'm still arguing that for transparency sake it would be nice to show the underlying ClusterRole and ClusterRoleBinding that allows this read access.

If I understand correctly (and please feel free to correct me), when we use the API mode of authentication to EKS, it uses a [Webhook Token Authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication) which means that the remote service must return a response using the same TokenReview API version that it received with Kubernetes username and/or Kubernetes groups. Then the RBAC authorizer kicks in and based on the RoleBinding and ClusterRoleBinding, it decides whether or not to allow the request, e.g. `kubectl get pods`.

If that is not the case - I would love to learn what happens in practice, if that is indeed the case - it would be nice to know what ClusterRoles are involved.
For all of the other 4/5 policies it is well documented in AWS's documentation and is crystal clear which ClusterRole and ClusterRoleBinding it (the AWS policy) maps to, and I just don't see why `AmazonEKSAdminViewPolicy` is any different.

Hope it makes sense :-)

**Comment by mikestef9** [comment]
EKS built its own authorizer as part of this feature, it's totally separate from RBAC. So there is no mapping to ClusterRole or ClusterRoleBinding.

**Comment by ofirc** [comment]
Got it @mikestef9, thanks for the clarification!

**Comment by mikestef9** [comment]
This blog goes into more detail 

https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/

Specifically the section titled "Kubernetes authorizers"
