### ISSUE TITLE
[EKS] [request]: Allow EKS to create a pod identity association prior to service account creation

### ISSUE THREAD

**Issue by jebbens** [aws/containers-roadmap#2245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Modify the way the EKS pod identity association works to allow creating an association before a service account exists. Without any in-depth knowledge of how this works, possibilities might include: allowing an association to be event-driven, e.g. creation of the service account specified in the association triggers the pod identity agent to complete the association; or, creating a custom resource type that could be specified in a manifest or chart.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We often create service accounts with applications/services in a single Helm chart or manifest. Creating an association currently requires the specified service account to already exist, however pods that need IAM permissions may not reach ready status without the permissions at startup. An ideal solution would allow us to create the association before the service account exists so that their applications/services work out of the box.

**Are you currently working around this issue?**
Continue to use IRSA, which allows us to specify a service account in the IAM role trust policy before the service account exists.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
@jebbens see our documentation

https://docs.aws.amazon.com/eks/latest/userguide/pod-id-association.html

> Optionally, you can specify a service account by name that doesn't exist in the cluster.

**Comment by jebbens** [comment]
Just tested again and I stand corrected. I will test again with the deployment - something else must have been going on.

**Comment by georgejohnis** [comment]
Resolving this issue since it should already be supported as mentioned by mikestef@ [here](https://github.com/aws/containers-roadmap/issues/2245#issuecomment-1863796453).  Feel free to reopen if the issue persists.
