### ISSUE TITLE
[service] [request]: Custom Tagging for EKS Security Group

### ISSUE THREAD

**Issue by jafferaws** [aws/containers-roadmap#2247]
**Tell us about your request**
Custom Tagging for EKS Security Group

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When a cluster is created, EKS creates a Security Group called "eks-cluster-sg-my-cluster-uniqueID." As of right now, there's no way to add Custom Tags to the Security Group. In order for AWS resources to comply with Security Governance, customers must add specific tags; otherwise, the resources will be destroyed. In order to create custom tags for EKS SG, we must find a quick solution to this issue.

**Are you currently working around this issue?**
How are you currently solving this problem?
We are currently running a Lambda automation to find new SG's that are being created during EKS cluster creation and adding the custom Tags. It is not a optimal solution.

**Comment by mikestef9** [comment]
Closing as duplicate of #977
