### ISSUE TITLE
[EKS] [EBS CSI Addon]: BUG: Node service account is not annotated with IAM role

### ISSUE THREAD

**Issue by ebr** [aws/containers-roadmap#2248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

The EBS CSI driver add-on creates two service accounts: one for the controller, and one for the node daemonset. When specifying an IAM role in the add-on configuration, the *controller* service account is correctly annotated, but  the *node* service account is not annotated. This results in the node pods having no permissions to assume the role and inability to provision volumes.

Service accounts after add-on deployment:

```
kubectl describe sa ebs-csi-controller-sa ebs-csi-node-sa
Name:                ebs-csi-controller-sa
Namespace:           kube-system
Labels:              app.kubernetes.io/component=csi-driver
                     app.kubernetes.io/managed-by=EKS
                     app.kubernetes.io/name=aws-ebs-csi-driver
                     app.kubernetes.io/version=1.25.0
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::<accountId>:role/ebs-csi-driver-addon-453619e
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>


Name:                ebs-csi-node-sa
Namespace:           kube-system
Labels:              app.kubernetes.io/component=csi-driver
                     app.kubernetes.io/managed-by=EKS
                     app.kubernetes.io/name=aws-ebs-csi-driver
                     app.kubernetes.io/version=1.25.0
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

The expectation is that when an IAM role is selected at the time of add-on deployment, the annotation should be added on both service accounts.

**Which service(s) is this request for?**
EKS

**Are you currently working around this issue?**
I am currently manually annotating the service accounts after add-on creation. I am also trying the `Advanced Configuration` JSON where I can set custom annotations. But this is quite fragile and error-prone.

**Comment by mikestef9** [comment]
This is intentional. Only the controller portion of the CSI drivers needs IAM permissions to call AWS APIs. Can you elaborate why you need IAM permissions on the node agents?

**Comment by ebr** [comment]
Until the node agents' services were annotated with the correct role, any attempt to mount a volume on the node fails with being forbidden to `AssumeRoleWithWebIdentity`. To be clear, the nodes' roles do not have any policies attached. Does the node agent assume that the permissions to call AWS APIs will be granted by the node role?

**Comment by youwalther65** [comment]
As @mikestef9 already wrote, neither the ebs-csi-node DaemonSet container nor the worker node need any EBS related permissions. All AWS API related actions are provided by respective sidecars from the ebs-csi-controller deployment. So having the annotation there is all you need.
My clusters are running the add-on as well without DaemonSet SA annotation for month without any problem. 
Having some logs from the controller and node Daemonset container would help clarifying the issue.

**Comment by ebr** [comment]
Tested this with a brand-new cluster and it seems to be working as described. Thank you
