### ISSUE TITLE
Amazon EKS Windows Nodes (Preview)

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#225]
Amazon EKS now supports Windows containers and Windows worker nodes as a public preview. 

Learn more and get started here: https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-windows-preview

Please leave feedback and comments on the preview using this ticket.

**Comment by JasonChinsen** [comment]
I believe that this line is causing this error: 

https://github.com/aws/containers-roadmap/blob/master/preview-programs/eks-windows-preview/amazon-eks-cfn-quickstart-windows.yaml#L194

```EKSWindowsWorkerStack | TemplateURL must be an Amazon S3 URL.```

**Comment by whereisaaron** [comment]
Apparently not a restriction applied to AWSers @JasonChinsen 😄

**Comment by tabern** [comment]
@JasonChinsen are you referring to [Step 2](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-windows-preview#step-2-create-your-vpc-iam-role-amazon-eks-cluster--worker-nodes)?

You cannot launch a CFN template that is not in S3, we recommend you download the file and upload it when you create your stack.

**Comment by JasonChinsen** [comment]
@ tabern yes, I was following the instructions as is. I have uploaded the file to s3 now and are running into other issues. I will keep you posted. 

I am very excited to see this work btw.

**Comment by tabern** [comment]
Ok, great! Just let us know... 👍

**Comment by tabern** [comment]
Hi all - we're doing a little consolidation, closing this ticket and moving the discussion to our original ticket for EKS Windows Support - https://github.com/aws/containers-roadmap/issues/69

Please follow along on https://github.com/aws/containers-roadmap/issues/69 and leave feedback there.
