### ISSUE TITLE
[EKS] [request]: Version policy similar to upstream kubernetes

### ISSUE THREAD

**Issue by ksudate** [aws/containers-roadmap#2250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

EKS version policy similar to upstream kubernetes

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

In-place upgrades of EKS allow only one version to be upgraded at a time.
This is because Control Plane and Data Plane support only one version difference.

**Are you currently working around this issue?**

Cluster migration is needed to upgrade multiple versions at once.

**Comment by mikestef9** [comment]
This is no longer the case, see https://github.com/aws/containers-roadmap/issues/1473#issuecomment-1762073043

**Comment by ksudate** [comment]
@mikestef9 
Thanks for the reply!

> [Ensure Managed Node Groups, if used, are on the same Kubernetes version as the control plane.](https://aws.github.io/aws-eks-best-practices/upgrades/#track-the-version-skew-of-nodes-ensure-managed-node-groups-are-on-the-same-version-as-the-control-plane-before-upgrading) EKS managed node groups and nodes created by EKS Fargate Profiles only support 1 minor version skew between the control plane and data plane.

https://aws.github.io/aws-eks-best-practices/upgrades/#track-the-version-skew-of-nodes-ensure-managed-node-groups-are-on-the-same-version-as-the-control-plane-before-upgrading

EKS Best Practice Guides mentioned above, is this already out of date?

**Comment by mikestef9** [comment]
The best practices guide is up to date https://aws.github.io/aws-eks-best-practices/upgrades/#confirm-version-compatibility-with-existing-nodes-and-the-control-plane

**Comment by ksudate** [comment]
Thanks for the useful information!
I will close this issue as it is no longer needed.
