### ISSUE TITLE
[EKS] [Issue] aws eks list-insights: command not found in aws-cli version 2.15.3

### ISSUE THREAD

**Issue by l0ris** [aws/containers-roadmap#2251]
Following https://aws.amazon.com/blogs/containers/accelerate-the-testing-and-verification-of-amazon-eks-upgrades-with-upgrade-insights/ I am encountering an issue while attempting to use the aws eks list-insights command.

*Environment:*

    AWS CLI Version: 2.15.3
    Python Version: 3.11.6

*Steps to Reproduce:*

    Install AWS CLI version 2.15.3 as per https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    Run the command aws eks list-insights.

*Expected Behavior:*
The aws eks list-insights command should be recognized and executed without errors.

*Actual Behavior:*
The command is not recognized, and the system returns an error indicating that the command is not found.

**Comment by joebowbeer** [comment]
Merged into default branch yesterday (1.32.5) but v2 branch looks to be a couple days behind

https://github.com/aws/aws-cli/commit/ac2e4feae38152287e3f17f8326a267b025b8404

**Comment by mikestef9** [comment]
AWS CLI v2 only releases twice a week, compared to v1 CLI and other SDKs (not entirely sure why). Support for EKS Insights API commands should be available in the AWS CLI v2 release scheduled for later today.

**Comment by mikestef9** [comment]
2.15.4 is released https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst
