### ISSUE TITLE
[ECR] [Feature Request]: Amazon ECR Scanning support for OS Alpine Linux (Alpine) v3.19

### ISSUE THREAD

**Issue by AnuSharma51** [aws/containers-roadmap#2257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

We have a requirement to use OS Alpine Linux (Alpine) v3.19 (Base OS) to create application image, however currently Amazon ECR does not support v3.19 for Image scanning and we are getting error "UNSUPPORTED_IMAGE".

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
The Current workaround is to use the supported OS Alpine Linux (Alpine) versions (v3.14, v3.15, v3.16, v3.17, v3.18). 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by wcmjunior** [comment]
Duplicated from https://github.com/aws/containers-roadmap/issues/2237.

**Comment by bradg-aws** [comment]
Alpine 3.19 is now supported in both ECR's basic scanning powered by Clair and the improved basic scanning: https://aws.amazon.com/about-aws/whats-new/2024/08/new-version-amazon-ecr-basic-scanning/

Support list: https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html#image-scan-basic-support-operating-systems
