### ISSUE TITLE
[EKS] [request]: Extended Kubernetes version support

### ISSUE THREAD

**Issue by vipin-mohan** [aws/containers-roadmap#2265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please support Kubernetes versions for longer than 14 months in EKS.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Kubernetes version releases happen every 4 months, and it is hard for customers to balance business priorities and staying current on new Kubernetes versions. Supporting a Kubernetes version in EKS for longer than 14 months will give customers more time to plan and execute cluster upgrades.

**Comment by tabern** [comment]
We announced extended version support for K8s versions 1.23 and higher in October » https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eks-support-kubernetes-versions-preview/

On January 17, we announced pricing and GA timing for April 1, 2024 » https://aws.amazon.com/blogs/containers/amazon-eks-extended-support-for-kubernetes-versions-pricing/

**Comment by justin007755** [comment]
Hi @tabern will both cn-north-1 & cn-northwest-1 regions support this new feature as well on April 1, 2024?

**Comment by vipin-mohan** [comment]
@justin007755 - Extended Kubernetes version support is already available in China regions. Pricing details are here: https://www.amazonaws.cn/en/eks/pricing/ The feature is currently in free preview, and billing will begin from April 1, 2024.

**Comment by justin007755** [comment]
@vipin-mohan When I check my eks cluster in the China region, and just find this feature is still not available (I compared the eks console between China region and other regions), and there is no "Support type" shown in the eks Clusters' console, so this feature launch date gets delayed again? Is there any firm date for this feature in China region? Thank you!

**Comment by tabern** [comment]
Extended version support is GA as of April 1, 2024 with support in all regions for K8s versions 1.21 and higher.

More info: https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-eks-support-kubernetes-versions/ 

See the EKS version lifecycle calendar: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar
