### ISSUE TITLE
[ECS] [BUG]: Support for Docker version 25.0 with ECS-Agent

### ISSUE THREAD

**Issue by awsjake** [aws/containers-roadmap#2267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
ECS Agent support for Docker version 25.0 and higher

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For instances that are not running the ECS Optimized AMI, where the Docker version and ECS agent version is preconfigured, launching new instances that pull the latest docker version will fail to run the ECS agent.  

For instances that launch and install the latest version of Docker, **downtime occurs**, as no Container Instances will register with the ECS API until the version is downgraded.

[Docker version 25.0](https://docs.docker.com/engine/release-notes/25.0/) was released January 19, 2024

The new version prevents the pause container from running with the following error:
`Failed to load pause container: container load: failed to load container image: /images/amazon-ecs-pause.tar : Error response from daemon: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version" module=agent.go`

**Are you currently working around this issue?**
Downgrade Docker to version [24.0.7](https://docs.docker.com/engine/release-notes/24.0/)

**Additional context**
Upgrading the ECS-Agent to the latest 1.80.0 does not have support for Docker 25.0

**Comment by sparrc** [comment]
Workaround for ECS Anywhere customers:

add flag `--docker-install-source distro` to the ecs-anywhere-install.sh script, as in:

```
sudo bash /tmp/ecs-anywhere-install.sh --region "us-west-2" --cluster "XXX" --activation-id "XXX" --activation-code "XXX" --docker-install-source distro
```

**Comment by awsjake** [comment]
[ECS Agent version 1.81.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.81.0) fixes this issue and is released.
