### ISSUE TITLE
[EKS]: eksctl support status update

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#2280]
AWS is aware of the recent [announcement](https://www.linkedin.com/posts/richardsonalexis_hi-everyone-i-am-very-sad-to-announce-activity-7160295096825860096-ZS67/) from Weaveworks about shutting down commercial operations. In addition to their significant contributions to the the CNCF and open source, Weaveworks has been a great partner to EKS and we are continuously grateful to Weaveworks for their leadership and development of the eksctl project.

In 2019, AWS and Weaveworks formed a [partnership](https://aws.amazon.com/blogs/opensource/eksctl-eks-cli/) to designate the open-source eksctl CLI tool as the officially supported CLI for Amazon EKS, driven by significant customer demand and the tool's capability to streamline and automate numerous EKS cluster management tasks. Since then, EKS as a service has evolved, implementing features that closed some of those early automation gaps. eksctl has always stayed a step ahead, adding usability enhancements before similar features are built into EKS service APIs.

Last year, AWS and Weaveworks [announced](https://aws.amazon.com/blogs/opensource/weaveworks-and-aws-joining-forces-to-maintain-open-source-eksctl/) a renewed partnership to co-develop eksctl. As part of that announcement, the eksctl project was moved under the shared /eksctl-io GitHub organization, and AWS engineers were added as project maintainers. Moving forward, AWS will take over full responsibility and ownership of the eksctl. We plan to continue development to meet the needs of customers with continued frequent eksctl [releases](https://github.com/eksctl-io/eksctl/releases). We are fully committed to the ongoing development and maintenance of eksctl. Later in 2024, we will move the eksctl project repo to the /aws GitHub organization. We will leave this issue open in case of any questions, comments, or concerns.

**Comment by colinbjohnson** [comment]
Although this outcome is "good" (many people will still be able to use this tool) it is rare for a company to end up utilizing a _third party_ to create official tooling (eksctl: "CLI for Amazon EKS").

It is, therefore, very rare for a company like AWS to end up in a situation where [approximately 4,590 documentation pages](https://www.google.com/search?q=%22eksctl%22+site%3Adocs.aws.amazon.com) and [approximately 152 "workshop" pages](https://www.google.com/search?q=%22eksctl%22+site%3Awww.eksworkshop.com) reference a tool that is developed by a third-party and almost ceased to exist.

**Comment by mikestef9** [comment]
Understand how some might see it that way but the reality is this has been developed in conjunction with Weave for the last 3 years. We’ve provided direct hands-on support and our PM team has worked directly with engineers on the project to guide it forward. While most large tech companies do tend to do a lot themselves, we think an amazing aspect of OSS and our approach is the ability to deeply partner with people outside of AWS to create useful tools. We fully support eksctl and it was never in danger of going away.

**Comment by colinbjohnson** [comment]
I wanted to followup on this because AWS *has* supported eksctl per the comments above:

- the project was never moved to the `aws` although that doesn't seem to matter much
- over the last 12 months it appears that at least 38 PRs are from AWS staff

So while the project is *not* within the "AWS" github organization they appear to have at least 3 staff members contributing (> 5 PRs) and 11 contributors total.
