### ISSUE TITLE
[EKS] : Support for Kubernetes 1.30

### ISSUE THREAD

**Issue by vipin-mohan** [aws/containers-roadmap#2290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
I'd like EKS support for Kubernetes v1.30.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
I'd like to be able to use Kubernetes 1.30 on EKS and be aware of the release timeline to help plan for it.

**Are you currently working around this issue?**
How are you currently solving this problem?
N/A

**Additional context**
Anything else we should know?
https://www.kubernetes.dev/resources/release/#summary

**Attachments**
N/A

**Comment by dejwsz** [comment]
You can check on their roadmap and see what is going on there: https://github.com/aws/containers-roadmap/projects/1

**Comment by LockedThread** [comment]
I think we can all agree that we would like our EKS [Uwubernetes](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/) cluster

**Comment by dims** [comment]
![image](https://github.com/aws/containers-roadmap/assets/23304/327bcb67-b0f7-4dcd-804a-0e92904b2111)

**Comment by rontendo-tabistJP** [comment]
When do you think this will be available in EKS pls?

**Comment by stevehipwell** [comment]
My hunch would be that as the K8s v1.30 AMIs have been released ([AL2/AL2023](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240514) & [Bottlerocket](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.20.0)), we're probably not too far away from seeing EKS support K8s v1.30.

**Comment by bryanasdev000** [comment]
Already seeing 1.30 as a possible version to upgrade or create clusters on us-east-2.

![130](https://github.com/aws/containers-roadmap/assets/53131727/4168baa9-d49f-4cd3-a2e2-ddbc0ba7bda4)

**Comment by dims** [comment]
eksctl is out too - https://github.com/eksctl-io/eksctl/releases/tag/v0.179.0

**Comment by bryanasdev000** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.30

**Comment by mikestef9** [comment]
https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-eks-distro-kubernetes-version-1-30/

**Comment by rrsela** [comment]
Note appearing yet on the [eks-distro](https://github.com/aws/eks-distro) github as release/readme manifest, although the images themselves can be found on the public ECR (for example the [kube-apiserver](https://gallery.ecr.aws/eks-distro/kubernetes/kube-apiserver))..
