### ISSUE TITLE
Can't join a AL2023 node to AWS EKS cluster

### ISSUE THREAD

**Issue by Alexhha** [aws/containers-roadmap#2296]
Hello,

I can't join the node to the cluster if I change image to AL2023. I'm getting the following error

`Instances failed to join the kubernetes cluster`

Is that expected ? The only issue I have found - there is no `/etc/eks/bootstrap.sh` script anymore

AMI ID: ami-022b389f6d4b64999

**Comment by dims** [comment]
please open an issue in https://github.com/awslabs/amazon-eks-ami repository. thanks!
