### ISSUE TITLE
[EKS] [CoreDNS] [request]: Option to enable Topology Aware Routing 

### ISSUE THREAD

**Issue by alt-dima** [aws/containers-roadmap#2310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add an option in the EKS Addon CoreDNS config to enable  Topology Aware Routing on the coredns service

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to enable Topology Aware Routing for the CoreDNS to minimize latency for DNS requests and decrease cross-AZ traffic.
We have 3 AZ and about 15 coredns pods (so TAR should work)

**Are you currently working around this issue?**
Manually added `service.kubernetes.io/topology-mode` annotation to the `kube-dns` service

**Additional context**

**Attachments**

**Comment by Nuru** [comment]
@alt-dima How are you adding the `service.kubernetes.io/topology-mode` annotation to the `kube-dns` service?

**Comment by juan-vg** [comment]
Kyverno policy is a way to add that annotation, but I would like to not use Kyverno for kube-system NS. EKS Addons should allow customizations like this one.

**Comment by mikestef9** [comment]
The latest version of the EKS Add-on for CoreDNS contains a parameter named `annotationTopologyMode` with possible values of `Disabled` or `Auto` (`Disabled` being the default).

When set to Auto, Topology Aware Routing ([docs](https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/)) will be enabled, helping keep network traffic within the zone where it originated. 

When enabled, DNS queries from pods are routed to CoreDNS pods in the same zone. If zone-local CoreDNS is not available, there will be automatic fallback to default behavior. Kubernetes  detects zone information from node labels. The service endpoint controller distributes endpoints based on zone topology.

This is available today with EKS add-ons. We are evaluating enabling Auto value by default in the node local CoreDNS shipped with EKS Auto Mode.

**Comment by TheBaus** [comment]
Old issue but if you still concerned, why not use NodeLocal DNS Cache @alt-dima ?

**Comment by mliner** [comment]
Are there any plans to add support for setting up the `TrafficDistribution` field inside the coredns service object?

**Comment by mikestef9** [comment]
There is separate issue open already for that request #2628
