### ISSUE TITLE
[EKS][CSI Snapshot Controller] [request]: Add advanced configuration like resources, tolerations and nodeSelector, ...

### ISSUE THREAD

**Issue by duboisph** [aws/containers-roadmap#2311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

The Snapshot Controller was added as EKS managed add-on via #1838. However it's missing advanced configuration like other addons.

The main problem for us is there's no support for setting `tolerations` and `nodeSelector` config. Ideally we can also specify the container's `resources`.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We use separate node pools for running system components. It's currently not possible to schedule the snapshot-controller pods to this pool.

Not being able to specify `resources` for evey component is also agains best practices.

**Are you currently working around this issue?**
Just deploying as is to a non-tainted node pool.

**Additional context**
/

**Attachments**
/

**Comment by shedimonG** [comment]
This would be helpful for us during the initial cluster creation. While Carpenter is not yet installed, CSI Snapshot Controller EKS addon pods are stuck in the pending state and cannot schedule on the tainted controller nodes, resulting in Terraform hangs.

**Comment by ConnorJC3** [comment]
Hi all, thanks for your patience. I am happy to announce that the latest version of the `snapshot-controller` addon (version `v8.0.0-eksbuild.1`) features several new configuration options, including resources, tolerations, and node selector.

We are also looking into adding more parameters in future versions of the addon, please leave suggestions on this issue or by opening a new one.

You can use the [`DescribeAddonConfiguration`](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonConfiguration.html) API to see the full details of the supported parameters for any specific addon version.
