### ISSUE TITLE
[aws/amazon-ecs-service-connect-agent] [support for blue/green deployment]: support blue/green deployments for ECS service connect

### ISSUE THREAD

**Issue by monelgordillo** [aws/containers-roadmap#2322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support blue/green deployments for ECS service connect

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
All my ECS services currently use CodeDeploy (blue/green) deployments. Rolling deployments are not used at all.

**Are you currently working around this issue?**
Not using ECS service connect.

**Additional context**

**Attachments**

**Comment by liubnu** [comment]
https://github.com/aws/amazon-ecs-service-connect-agent/issues/74

**Comment by kshivaz** [comment]
Issue #1993
