### ISSUE TITLE
Full Spinnaker support for Fargate & ECS services

### ISSUE THREAD

**Issue by clareliguori** [aws/containers-roadmap#234]
Spinnaker does already have support for Fargate & ECS!  You can see the current documentation here: https://www.spinnaker.io/setup/install/providers/aws/aws-ecs/

However, some ECS attributes cannot be specified in Spinnaker for deployment.  This roadmap entry tracks being able to deploy ECS Services in Spinnaker with any valid ECS task definition attribute or service attribute.

Missing attributes are (as of Apr 2):
- [ ] Scheduling strategy (i.e. daemon services)
- [x] Many task definition attributes.  Our plan to reach parity in Spinnaker for task definitions is documented here: https://github.com/spinnaker/spinnaker/issues/4070
- [x] Service discovery
- [x] Fargate platform version
- [x] Placement constraints
- [x] Tags
- [x] Non-load-balanced services
- [x] Service autoscaling with target-tracking policies

If you have feature requests for the ECS support in Spinnaker beyond these missing attributes or find bugs, please [open a Spinnaker issue here](https://github.com/spinnaker/spinnaker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aprovider%2Fecs), so the Spinnaker community can see it!

**Comment by clareliguori** [comment]
The Spinnaker 1.14 release window opens Monday, May 13.  The following ECS driver improvements are merged in, and will be part of that release:
* Service discovery
* Fargate platform version
* Placement constraints
* Tags
* Non-load-balanced services
* Service autoscaling with target-tracking policies

**Comment by allisaurus** [comment]
The Spinnaker 1.15 release windows opens today, Monday, July 8. It includes support for [task definition artifacts](https://github.com/spinnaker/spinnaker/issues/4070), unblocking use of multiple containers and missing task definition attributes!

**Comment by clareliguori** [comment]
We have moved the roadmap for our ongoing work on the Spinnaker ECS provider over to the Spinnaker community roadmap, here:
https://github.com/spinnaker/community/blob/master/roadmap.md#amazon-ecs
We'll continue to keep the Spinnaker community roadmap up to date with support for newly released ECS features in Spinnaker, for example the recent launch of multi-target-group services.

If you have feature requests or bug reports for the Spinnaker ECS provider, please [open a Spinnaker issue here](https://github.com/spinnaker/spinnaker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aprovider%2Fecs).
