### ISSUE TITLE
[ECR] [request]: Support scanning of Ubuntu 24.04 LTS based images

### ISSUE THREAD

**Issue by KylePeterDavies** [aws/containers-roadmap#2342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Add support for scanning Ubuntu 24.04 LTS based images for security vulnerabilities

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
Continue to have the ability to scan images pushed to ECR after upgrading the base image to Ubuntu 24.04 LTS.
**Are you currently working around this issue?**
How are you currently solving this problem?
No

**Additional context**
Pushed an image based on Ubuntu 24.04 and received UnsupportedImageError from ECR scan on push

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by kenfringe** [comment]
Hello, is there any update on this issue?

**Comment by bradg-aws** [comment]
Hi, thanks for reaching out. Ubuntu 24.04 is now supported through ECR's new improved basic scanning: https://aws.amazon.com/about-aws/whats-new/2024/08/new-version-amazon-ecr-basic-scanning/
