### ISSUE TITLE
 EKS Managed core-dns Addons Not able to change deployment replicaCount

### ISSUE THREAD

**Issue by rajeevpnair** [aws/containers-roadmap#2350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
I am trying to change the replicaCount for coredns addon in EKS, I see its configurable item in the add-on json schema, but after deployment. the replicaCount reset to its original value, sometimes 2 and sometimes 3.. I don't find a fixed value in our clusters. The ReplicaCount is not even able to change using kubectl, it reset to its original value.
Not sure this something managed by EKS, If this is not a configurable item, please remove it, otherwise its seems to be a bug.

**Which service(s) is this request for?**
This could be Fargate,EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I need to have less number of replicas in our dev environment for the control-plane components.

**Are you currently working around this issue?**
No workaround, Excluded coredns.

**Additional context**
Anything else we should know?
Add ON Version -   addon_version = "v1.10.1-eksbuild.7"
EKS version 1.27
**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
Do you have HPA or coredns autoscaling configured in the cluster? It's likely some other controller/component is changing the replica count.

**Comment by M00nF1sh** [comment]
@rajeevpnair 
We are not able to reproduce this behavior, did you specify the replica count correctly?
e.g. 
it shall be something like 
```
aws eks update-addon --cluster-name=<> --addon-name=coredns --addon-version v1.10.1-eksbuild.7 --configuration-values '{"replicaCount":20}' --resolve-conflicts OVERWRITE
```
If you cannot override via kubectl, it could be you installed some form of autoscaler in your cluster, e.g. CPA, would you help enable the apiserver logs for your eks cluster and check which component modified the coredns replica?

**Comment by rajeevpnair** [comment]
yeah, it was due to cluster promotional autoscaler in the cluster..
I will close the ticket.
