### ISSUE TITLE
[ECR] [request]: Support for Alpine Linux v3.20 on Enhanced Vulnerability Scanning - Inspector

### ISSUE THREAD

**Issue by rgoltz** [aws/containers-roadmap#2357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Using Vulnerability Scans with for latest Alpine release.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
At 22.05.2023, Alpine Linux 3.20 has been released (please see https://gallery.ecr.aws/docker/library/alpine and https://alpinelinux.org/posts/Alpine-3.20.0-released.html). 
We are using AWS ECR Enhanced (Image) Scanning to check for vulnerabilities.

Once you using the latest (= 3.20) image-tag of Alpine, you will get the following output in ECR:
```
Image not supported
UnsupportedImageError: The operating system and/or package manager are not supported.
```
![image](https://github.com/aws/containers-roadmap/assets/16392819/92fe0834-94f2-4e10-aee2-1344b0253b49)

At the same moment, Alpine SecDB also already added version 3.20, please see https://secdb.alpinelinux.org/v3.20/ (supporting vulnerability data)

**Are you currently working around this issue?**
No workaround known. This repo have to use Vulnerability Scans using AWS ECR Enhanced (Image) Scanning.
Currently we have to skip Image Scanning.

**Additional context**
A general improvement is needed and already requested in the following issue. You can find the same pattern of this issue for previous regular Alpine major-releases 3.19, 3.18, ... linked in this issue as well.
* https://github.com/aws/containers-roadmap/issues/1959

**Comment by hannes-ucsc** [comment]
Docker just [updated](https://github.com/docker-library/docker/commit/1b21e433dccaa4d0dfc84d53644fbdab14b210e1) the base of their [Docker images](https://hub.docker.com/_/docker) to Alpine 3.20. This means that ECR cannot scan these popular images.

I originally posted this comment on [another issue](https://github.com/aws/containers-roadmap/issues/2358#issuecomment-2141363006) but it applies to this one, too.

**Comment by gcagle3** [comment]
It appears that AWS Inspector supports Alpine 3.20 now: 

![image](https://github.com/aws/containers-roadmap/assets/81821730/6de51119-f1ce-4b94-8585-5e5ffb84caed)

Source: https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr

**Comment by bradg-aws** [comment]
Resolving. Enhanced scanning does support alpine 3.20. Basic scanning does also support it as well, although our docs aren't yet updated to reflect this.
