### ISSUE TITLE
[EKS] [request]: No available versions of AWS Cloudwatch Observability Add-on for EKS 1.30

### ISSUE THREAD

**Issue by azmelanar** [aws/containers-roadmap#2359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
No available versions of AWS Cloudwatch Observability Add-on for EKS 1.30

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
```
$ aws eks describe-addon-versions --kubernetes-version 1.30 --addon-name amazon-cloudwatch-observability
{
    "addons": []
}

# example for 1.29
$ aws eks describe-addon-versions --kubernetes-version 1.29 --addon-name amazon-cloudwatch-observability
{
    "addons": [
        {
            "addonName": "amazon-cloudwatch-observability",
            "type": "observability",
            "addonVersions": [
                {
                    "addonVersion": "v1.6.0-eksbuild.1",
                    "architecture": [
                        "amd64",
                        "arm64"
                    ],
                    "compatibilities": [
                        {
                            "clusterVersion": "1.29",
                            "platformVersions": [
                                "*"
                            ],
                            "defaultVersion": true
                        }
                    ],
                    "requiresConfiguration": false
                },
...
```

**Are you currently working around this issue?**
There are no immediate impact for now that I noticed.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jacobwoffenden** [comment]
Commenting just to say `aws-guardduty-agent` is the same, I have raised with enterprise support.

**Comment by hustshawn** [comment]
the adot addon as well

**Comment by jacobwoffenden** [comment]
`aws-guardduty-agent`'s compatibility has been updated

```json
  {
    "addonName": "aws-guardduty-agent",
    "type": "security",
    "addonVersions": [
      {
        "addonVersion": "v1.6.1-eksbuild.1",
        "architecture": [
          "amd64",
          "arm64"
        ],
        "compatibilities": [
          {
            "clusterVersion": "1.30",
            "platformVersions": [
              "*"
            ],
            "defaultVersion": true
          },
```

But the [docs](https://docs.aws.amazon.com/guardduty/latest/ug/prereq-runtime-monitoring-eks-support.html#gdu-agent-supported-k8-version) haven't been _yet_

I have raised an issue with our TAM about the EKS service team ensuring EKS add-ons are updated when new EKS versions are released.

**Comment by lisguo** [comment]
Hello, we are working on adding support for K8s version 1.30 in the amazon-cloudwatch-observability add-on.

I just merged PRs related to 1.30 compatibility in the [operator](https://github.com/aws/amazon-cloudwatch-agent-operator/pull/179) and the [helm-chart](https://github.com/aws-observability/helm-charts/pull/51).

We are expecting to have the support released by tomorrow, May 31st. Additionally, we will release the new helm chart version 1.7.0 which will work on 1.30.

**Comment by lisguo** [comment]
1.30 support has been added to the amazon-cloudwatch-observability add-on in all regions. Thank you for your patience.

**Comment by Ramneek-kalra** [comment]
Thanks @lisguo ! I second that and tested successfully. It's working fine as expected.

**Comment by dejwsz** [comment]
do the same for ADOT add-on as it is not avilable for 1.30

**Comment by hustshawn** [comment]
1.31 still the same
