### ISSUE TITLE
[ECS] [Fargate]: Stopped task error message enhancements

### ISSUE THREAD

**Issue by weijuans** [aws/containers-roadmap#2366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We are starting an effort to enhance the stopped task error messages on Amazon ECS to help customers troubleshoot task failures. The intent is to make those error messages prescriptive and actionable to help you more productive when running applications on ECS. We will also be updating the relevant documentation such as this one on [stopped tasks error codes](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-error-codes.html) to provide more details helping you analyze failures, and resolving the failures. We would love to hear your input and feedback.

**Which service(s) is this request for?**
This could be Fargate, ECS

**Comment by stsitsonis** [comment]
[Stopped Task error message enhancements](https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-ecs-stopped-task-error-messages-troubleshooting/) are released.
