### ISSUE TITLE
Support for RDP ?

### ISSUE THREAD

**Issue by GavinDixon69** [aws/containers-roadmap#237]
We would very much like to access a Windows Container using RDP 
Could this functionality be in the scope of this project?

**Comment by goyalpurvi** [comment]
@GavinDixon69 Have you tried ECS Exec? 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html
https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/

**Comment by rawahars** [comment]
Hi @GavinDixon69,

Presently, you can access your Windows instances using RDP or you can use Fleet Manager to RDP inside the instance.
Alternatively, if you want to access your containers directly on Amazon ECS, then you can use Amazon ECS Exec (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html). For Amazon EKS, you can use `kubectl exec` for the same (https://kubernetes.io/docs/tasks/debug/debug-application/get-shell-running-container/).
