### ISSUE TITLE
[EKS] [request]: Fargate support for EKS Pod Identity

### ISSUE THREAD

**Issue by runningman84** [aws/containers-roadmap#2383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please support EKS Pod Identity also for EKS Fargate.

**Which service(s) is this request for?**
Fargate, EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Right now we cannot move to EKS Pod Identity with out cluster consisting of mixed workloads using EKS Fargate and normal EKS nodes. https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html#pod-id-considerations

**Are you currently working around this issue?**
We cannot migrate to EKS Pod Identity in this mixed setup

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by aslatter** [comment]
I would be interested in this feature because I'd like to host Karpenter on Fargate and manage my EC2 nodes with Karpenter exclusively, so that I can fully automated upgrading instance-ami-versions, and that everything else in my deployment is able to adopt EKS Pod Identity.

**Comment by josegonzalez** [comment]
I believe this is a duplicate of https://github.com/aws/containers-roadmap/issues/2274, so might be worth consolidating conversation there :)

**Comment by mikestef9** [comment]
Closing as duplicate of #2274
