### ISSUE TITLE
[EKS] [request]: Amazon EKS optimized GPU Amazon Linux 2023 AMI

### ISSUE THREAD

**Issue by DhruvWasTaken** [aws/containers-roadmap#2391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Is there a timeline for the implementation of an EKS optimized GPU AL2023 AMI ?

This is in-continuation from [issue#2240](https://github.com/aws/containers-roadmap/issues/2240)

**Comment by dims** [comment]
we have them now ... https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240924

**Comment by jlbutler** [comment]
And now launched 🚀 

https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-eks-nvidia-aws-neuron-instance-types-al2023/
https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-accelerated-amis-now-available/

Thanks everyone!
