### ISSUE TITLE
[ECS] Feature Request: Document 'force new deployment' as an official workaround for the Software Version Consistency feature

### ISSUE THREAD

**Issue by danielferraz-git** [aws/containers-roadmap#2402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As announced on July 11, 2024, any services created or updated within Amazon ECS after June 25, 2024, will resolve container image tags to image digests to ensure consistent software versions moving forward.

This change in behavior was not communicated and disrupted our deployment strategy, which relies on using the latest tag for blue-green and rolling updates.

**Which service(s) is this request for?**
ECS

**Are you currently working around this issue?**
We are currently using the 'Force new deployment' flag in each build. This approach has been working so far, allowing us to use the latest image. However, we're concerned that this solution might stop working unexpectedly.

**Tell us about your request**
We request clarification in the Amazon ECS documentation regarding the 'Force new deployment' flag for ECS service updates. Specifically, the new feature documentation should explicitly state that:

* The 'Force new deployment' flag resets the cache and uses the latest image. This is critical to establish at least a documented workaround for our blue-green and rolling update deployments process.

* Only new tasks are affected when the flag is enabled, maintaining service stability by not disrupting already running tasks.

By providing clear and comprehensive documentation, ECS users negatively impacted by this new feature will have a better understanding of how to effectively utilize the 'Force new deployment' flag as a workaround.

**Additional context**
* What's New: https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-ecs-software-version-consistency-containerized-applications/
* Blog Post: https://aws.amazon.com/blogs/containers/announcing-software-version-consistency-for-amazon-ecs-services/
* Documentation: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-ecs.html#deployment-container-image-stability

**Comment by pmcevoy** [comment]
Got caught by this today when one of our tasks needed to restart due to memory overload and then eventually was killed cos restart was unable to download a datadog sidecar image that we were referencing in TaskDefinition by floating tag, but the tag had moved to a new version and the old image had been purged.
I hate this new feature - I'm compentent enough to use unique buildserver assigned tags for containers that count, but when I decide to use a floating tag (eg based on SemVer) I understand that I may have small internal inconsistencies that I accept.
At the very least, allow us to override this new default...

**Comment by vibhav-ag** [comment]
We've added this to documentation. For updates on opting-out of consistency, please use #2393
