### ISSUE TITLE
[EKS] [EBS CSI addon]: Add PriorityClass as configurable field for 'node'

### ISSUE THREAD

**Issue by tinder-robolague** [aws/containers-roadmap#2405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to set PriorityClass as a configurable field in ebs-csi 'node' json schema

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Previous configuration allowed us to set priorityclass for this daemonset, which allows us to avoid calculations on requests and limits where we always want this to schedule first.

**Are you currently working around this issue?**
We're just setting requests and limits

**Additional context**
This could also apply to any addon which utilizes a daemonset

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by AndrewSirenko** [comment]
Thank you @tinder-robolague for your request! We will expose the parameter in our next EBS CSI Driver add-on release.

**Comment by ConnorJC3** [comment]
This has been completed as of the EBS CSI Driver EKS Addon version `v1.34.0-eksbuild.1`

Here's an example addon configuration to set the priority class of the DaemonSet:

```yaml
node:
  priorityClassName: daemonset-priority-class
```
(yaml)

```json
{
  "node": {
    "priorityClassName": "daemonset-priority-class"
  }
}
```
(json)
