### ISSUE TITLE
[ECS/FARGATE] [EventBridge triggered Fargate Tasks]: Support launching using Spot for ARM

### ISSUE THREAD

**Issue by ChrisMcKee** [aws/containers-roadmap#2407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Add support for Spot pricing.

**Which service(s) is this request for?**
Fargate/EventBridge launched Tasks

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Fargate doesn't support spot pricing for ARM architecture

```
    "errorMessage": "FARGATE_SPOT capacity provider is not supported when using ARM architecture.",
```

**Are you currently working around this issue?**
How are you currently solving this problem?

Using on-demand at the moment but will probably switch back to non-arm arch if it works out advantageous from a pricing perspective (that parts harder to quantify).

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by vibhav-ag** [comment]
@ChrisMcKee this should be possible using CapacityProviderStrategy already. Am I missing something?

Docs: https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_EcsParameters.html

**Comment by ChrisMcKee** [comment]
@vibhav-ag Changed the title/description its the lack of support for spot pricing on graviton. 
Though the API has a bit to be desired as you can set capacity providers on a cloudwatch event target and there's no introspection to check if those exist on the cluster till runtime.
Similarly you can have a capacity strategy for spot, the ecs target takes the arn of the task but it doesn't validate if the configuration could run till runtime.

**Comment by vibhav-ag** [comment]
My bad, I missed the part about ARM architecture, We're working on this.

**Comment by ChrisMcKee** [comment]
👌
