### ISSUE TITLE
[EKS] [request]: support VolumeAttributesClass

### ISSUE THREAD

**Issue by csuzhangxc** [aws/containers-roadmap#2412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Support modify EBS via `VolumeAttributesClass` as the CSI driver has supported it (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md#v1290)

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Modify EBS IOPS/throughput/type via K8s standard APIs.

This needs to enable the `VolumeAttributesClass` feature gate in K8s at least until v1.31

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by ConnorJC3** [comment]
`VolumeAttributesClass` support is enabled on the recently released EKS 1.31: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.31

If you are using the EBS CSI Driver, please upgrade to version `v1.35.0` or later, which will automatically detect and enable `VolumeAttributesClass` support (if you are already using `v1.35.0` or later on a cluster that is upgraded to EKS 1.31, reinstall the driver to cause this auto-detection to occur and enable VAC support).
