### ISSUE TITLE
[EKS] Cloudformation support for control plane logging and endpoint access control

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#242]
Ability to define control plane logging and endpoint access control (public/private) during EKS cluster creation and update via Cloudformation.

**Which service(s) is this request for?**
Amazon EKS, AWS Cloudformation

**Are you currently working around this issue?**
You can currently control these settings for EKS clusters using the EKS APIs, console, and AWS CLI.

**Attachments**
Control Plane logging: https://github.com/aws/containers-roadmap/issues/26
Endpoint access control: https://github.com/aws/containers-roadmap/issues/22

**Comment by icereed** [comment]
Hello,

is there any ETA on this? We need to build dirty workarounds for this.

Best,
Icereed

**Comment by max-allan-surevine** [comment]
Most people are doing "secure by default" and here AWS are doing "open to the internet" by default and all my carefully secured instances without any internet connectivity cannot join an EKS cluster. Unless I run the cloudformation and then manually enable the private access later.
Please hurry it up!
The feature is already there, it just needs exposing to CloudFormation.

**Comment by PatMyron** [comment]
[CloudFormation Roadmap issue for logging](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/208)

**Comment by sbonasu** [comment]
+1

**Comment by quocdung3007** [comment]
+1

**Comment by zetas** [comment]
Big +1. This just caused me a solid week of pulling my hair out trying to figure out why my private EC2 nodes won't bootstrap. Why amazon, why would you ever default to private off. I get public on but private off? why?

**Comment by ismailyenigul** [comment]
I would like to configure EKS endpoint parameter by Cloudformation templates.
Current cloudformation AWS::EKS::Cluster does not have any parameter to configure private/public endpoints.  It creates the cluster with public endpoint enabled and we have to run some cli commands to enable private endpoint.

**Comment by vikram-katkar** [comment]
+1
Would love to see these features in CloudFormation:
- endpointPrivateAccess
- endpointPublicAccess
- publicAccessCidrs
- clusterLogging

This already available in API:
https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html

**Comment by clayvan** [comment]
It's not a good look when even Terraform beats CloudFormation to support both logging and private endpoints.

https://www.terraform.io/docs/providers/aws/r/eks_cluster.html#vpc_config-1

**Comment by clayvan** [comment]
FYI the AWS Quick start team created their own custom CF resource to do this https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider

Commit to the quick start guide for reference https://github.com/aws-quickstart/quickstart-amazon-eks/commit/0bf72f132fbe9c34c84e4d2b9b2e0a603ec06d0b

It seems..weird..that the AWS quick start team had to create a workaround to do this instead of just baking that logic into the EKS CF resource itself?

**Comment by clayvan** [comment]
I noticed today that the EKS cloudformation resource has been updated to mention these parameters, but are not in the example.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html

I have not tried it yet.

**Comment by evanlurvey** [comment]
@clayvan I tried today and got a failed deploy. `Property validation failure: [Encountered unsupported properties in {/ResourcesVpcConfig}: [EndpointPrivateAccess]]` I know there is some sort of way to disable validation that sometimes works but I can't remember the syntax.

**Comment by dectl** [comment]
How is this still not implemented?

**Comment by zetas** [comment]
It is... in terraform. Which is what my organization switched to because
of stuff like this. 

On April 17, 2021, Github Notifications ***@***.***>
wrote:
> How is this still not implemented?
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/aws/containers-roadmap/issues/242#issuecomment-
821923370>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAH5ECWZLL5LMJKFQU4GTY3TJJE37ANCNFSM4HELIDRA>.

**Comment by finkj** [comment]
Really disappointing that such an important feature is still missing after 2 years... 
I'm thinking about switching back to Terraform.

**Comment by haoming-db** [comment]
We need it! Please prioritize!

**Comment by dgard1981** [comment]
We want to move away from Terraform towards CloudFormation, because Terraform is a fickle beast at time, but stuff like this makes it hard to justify.

Can someone from AWS at least give an indication as to whether or not this is going to happen?

**Comment by tabern** [comment]
@dgard1981 yes. this is going to happen. We are working on this, though it has required a bit more time and effort than we originally had estimated.

**Comment by xor007** [comment]
+1. We need this. How is Terraform pulling it off?

**Comment by zetas** [comment]
@xor007 Terraform uses the AWS api directly behind the scenes so it can do anything the api can.... unlike amazons own CloudFormation 🤦

**Comment by acesir** [comment]
Do we have any ETA for this feature? It has been 2 years

**Comment by mrklc** [comment]
Still no sign to fix cloudformation to support endpoint access control?

**Comment by mikestef9** [comment]
Good news to share!! You can now configure control plane logging and cluster endpoint access control through AWS CloudFormation. Details can be found in the EKS Cluster resource documentation below

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html

Official AWS What's New post will be out tomorrow.

**Comment by mohag** [comment]
Thanks. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-loggingtypeconfig.html

That can do with a list of supported values for "Type" (or where to find them)
