### ISSUE TITLE
[ECR] [Scanning]: Ubuntu 24.04 not supported

### ISSUE THREAD

**Issue by jonkerw85** [aws/containers-roadmap#2434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Ubuntu 24.04 is not supported for scanning. While https://github.com/aws/containers-roadmap/issues/2342 notes that it is posible. 

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
After changing the image from Ubuntu 22.04 to 24.04 i get the error
* Not supported
UnsupportedImageError: The operating system 'ubuntu' version '24.04' is not supported.

The base image is from public.ecr.aws/lts/ubuntu:24.04

**Are you currently working around this issue?**
Staying on Ubuntu 22.04

**Attachments**
![image](https://github.com/user-attachments/assets/ee513b95-f2e8-41b7-9278-3ffe17f7272b)

**Comment by gdm-io** [comment]
Despite #2342 saying that this is supported (with the enhanced, native scanning), it is not listed on the [support matrix](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html).  The enhanced scanner reports 0 findings now vs. saying the OS is unsupported.

**Comment by bradg-aws** [comment]
Are you using enhanced scanning or basic scanning? If basic scanning, are you using the old basic scanning or the new improved basic scanning?
Ubuntu 24.04 is supported in all but the old basic scanning. 

ECR [basic scanning docs ](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html) should be updated shortly to reflect this. Enhanced scanning with Inspector already shows 24.04 as supported: https://docs.aws.amazon.com/inspector/latest/user/supported.html#w123aac53c15

**Comment by jonkerw85** [comment]
@bradg-aws You are correct, I used the old scanner. Thnx for the support!

**Comment by ElvenSpellmaker** [comment]
@bradg-aws I'm extending off Ubuntu 24.04 also, and have Enhanced Scanning Enabled, but I'm still getting the same message that the image isn't supported, any ideas please?

![Image](https://github.com/user-attachments/assets/1ac95cc6-ba3b-4a33-9c5c-d978a71e341e)

```Dockerfile
ARG UBUNTU_VERSION=24.04

FROM ubuntu:${UBUNTU_VERSION}
```
