### ISSUE TITLE
[EKS] [request]: No available versions of ADOT add-on for EKS 1.31

### ISSUE THREAD

**Issue by dejwsz** [aws/containers-roadmap#2435]
AWS EKS 1.31 is available but again ADOT is not so it blocks the upgrade a bit. When we can expect it ? Why it is not shipped when a new version of EKS is released ? It was the same for 1.30 as I recall - so what is the release policy for ADOT in regard to EKS itself ? Should we (the users) forget about this add-on ?

**Comment by dejwsz** [comment]
if current adot should work (I guess so?) then please update the metadata to allow it also for 1.31 maybe

**Comment by dejwsz** [comment]
https://github.com/aws-observability/aws-otel-collector/issues/2873

**Comment by mhausenblas** [comment]
FYI: support for Kubernetes 1.31 is now available, see the [launch blog post](https://aws-otel.github.io/docs/ReleaseBlogs/aws-distro-for-opentelemetry-eks-add-on-v0.109.0) for details.
