### ISSUE TITLE
[ECR] [request]: ECR access logs

### ISSUE THREAD

**Issue by ajohnstone** [aws/containers-roadmap#244]
**Tell us about your request**
Unable to determine source of pull requests for individual images, once you have authenticated, this limits traceability and auditability 

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve**. 
Access log for ecr so that can identify last pull and up address/resource that pulled the image.

**Are you currently working around this issue?**
Not with ecr

**Comment by clareliguori** [comment]
Hi @ajohnstone can you tell me more about why CloudTrail doesn't provide sufficient access logs for ECR?  Docker pulls translate into BatchGetImage (getting the image manifest) and GetDownloadUrlForLayer (pulling an individual layer) events in CloudTrail, and they have the identity of the user pulling.

For example, Docker's request for the image manifest will look like this in CloudTrail:
```
{
    "eventVersion": "1.04",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "AIDAXXXX",
        "arn": "arn:aws:iam::123456789012:user/clare",
        "accountId": "123456789012",
        "accessKeyId": "ASIAXXXX",
        "userName": "clare",
        "sessionContext": {
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2019-04-09T23:49:23Z"
            }
        },
        "invokedBy": "AWS Internal"
    },
    "eventTime": "2019-04-09T23:49:41Z",
    "eventSource": "ecr.amazonaws.com",
    "eventName": "BatchGetImage",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "AWS Internal",
    "userAgent": "AWS Internal",
    "requestParameters": {
        "imageIds": [
            {
                "imageTag": "latest"
            }
        ],
        "acceptedMediaTypes": [
            "application/vnd.docker.distribution.manifest.list.v2+json",
            "application/vnd.docker.distribution.manifest.v1+prettyjws",
            "application/json",
            "application/vnd.oci.image.manifest.v1+json",
            "application/vnd.oci.image.index.v1+json",
            "application/vnd.docker.distribution.manifest.v2+json"
        ],
        "repositoryName": "clares-repo",
        "registryId": "123456789012"
    },
    "responseElements": null,
    "requestID": "24d1b71d-XXXX",
    "eventID": "f0536f83-XXXX",
    "resources": [
        {
            "ARN": "arn:aws:ecr:us-west-2:123456789012:repository/clares-repo",
            "accountId": "123456789012"
        }
    ],
    "eventType": "AwsApiCall",
    "recipientAccountId": "123456789012"
}
```

**Comment by ajohnstone** [comment]
Perfect, thanks for clarifying that for me.

**Comment by kgoenkaaw** [comment]
I see this marked as completed. However i dont see much of a change in current logs vs what was posted in this issue in 2019. I'm looking for image digest details for BatchGetImage event and also systems which pulled certain image
