### ISSUE TITLE
[EKS] EKS add-ons support for Amazon EBS CSI Driver

### ISSUE THREAD

**Issue by leakingtapan** [aws/containers-roadmap#247]
EBS CSI driver installed on EKS clusters by default.

**Comment by aviau** [comment]
How is this going to work for customers that have installed the CSI driver manually?

Also, is it going to manage updates automatically?

**Comment by tabern** [comment]
This will be solved by a feature release following #252

**Comment by mikestef9** [comment]
Changing the title, as we will not be auto installing EBS CSI driver as part of cluster creation. Rather, we will add EBS CSI driver to EKS add-ons, so you can declare to have it installed as part of cluster creation through the add-ons system.

**Comment by inductor** [comment]
https://github.com/aws/containers-roadmap/issues/1397#issuecomment-977610623

**Comment by SamuelBagattin** [comment]
> 

It would be really useful. Currently there is, in my opinion, no clean way to deploy the CSI snapshotter with the corresponding CRDs. The only way for now is to apply [the required manifests](https://github.com/kubernetes-csi/external-snapshotter#usage). There is not even an official helm chart to handle resources and CDRs creation.

**Comment by stevehipwell** [comment]
@SamuelBagattin you [shouldn't use Helm to install CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/).

**Comment by MichaelHauss** [comment]
The EBS CSI Driver is now available in EKS add-ons in preview. Check out the [announcement](https://aws.amazon.com/about-aws/whats-new/2021/12/eks-add-ons-ebs-csi-driver/) and the [documentation](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html) to get started. Feel free to leave feedback here.

**Comment by MichaelHauss** [comment]
The EBS CSI driver is now available in EKS add-ons in GA! Checkout the announcement https://aws.amazon.com/about-aws/whats-new/2022/03/eks-add-ons-ebs-csi-driver-available/

**Comment by nuriel77** [comment]
Thank you! Great work.

I must admit, I was expecting that the add-on would also take care of the role creation when oidc is enabled for the cluster.
Same for the up-coming AWS lb controller: https://github.com/aws/containers-roadmap/issues/1162

Should I create a new issue requesting for this feature?

**Comment by GrigorievNick** [comment]
I have question, and I am not sure where is best way to ask it.
So leave it here.
What is the best way to set up [tags](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/TAGGING.md) or other properties with this add-on?

**Comment by youwalther65** [comment]
@GrigorievNick The tagging feature will be implemented in AWS EBS CSI v1.6.0 and it will enable you to tag underlying EBS volumes by making use of StorageClass attributes. v1.6.0 will be eventually used for the managed EKS add-on as well , currently it uses v1.5.1

**Comment by youwalther65** [comment]
@GrigorievNick No, you can't change the container arguments for the sidecar "ebs-plugin" in managed EKS add-on because those are managed by AWS. You can verify all the managed fields using:
$ k get deploy -n kube-system -**-show-managed-fields** ebs-csi-controller -o yaml
...
metadata:
...
  managedFields

So you either have to wait for 1.6.0 or use the self-managed Helm based installation where you can set them using a values.yaml which contains:
controller:
  extraVolumeTags:
    your-key1: your-value1

**Comment by GrigorievNick** [comment]
@youwalther65 So can I propagate tags right now, some how?
Or I need wait until EKS add-on for EBS Driver will support 1.6.0 version.

**Comment by youwalther65** [comment]
@GrigorievNick: You can propagate tags right now only using the Helm chart and modifying the controller ebs-csi container args but NOT using the managed EKS add-on.

**Comment by GrigorievNick** [comment]
Thanks for help @youwalther65 . Do there is any open to community roadmap for ebs add-on on eks?

**Comment by youwalther65** [comment]
@GrigorievNick You can raise an issued for EKS add-on on [AWS public containter roadmap](https://github.com/aws/containers-roadmap/projects/1)

**Comment by mikestef9** [comment]
EBS CSI driver [version 1.6](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v160) is now available through EKS add-ons, which supports [tagging](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/TAGGING.md) through Storage Classes.
