### ISSUE TITLE
[EKS] [Feature Request]: Enable feature gates TTLAfterFinished

### ISSUE THREAD

**Issue by Looooopy** [aws/containers-roadmap#248]
**Tell us about your request**
I would be able to enable feature gates TTLAfterFinished

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Jobs that are "Complete" or "Failed" should be removed automatically.
It takes up unnecessary resources, if they are left there.

**Are you currently working around this issue?**
Manually remove the jobs.

**Additional context**
List of feature gates, TTLAfterFinished
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by scravy** [comment]
This is a duplicate of https://github.com/aws/containers-roadmap/issues/255

**Comment by tabern** [comment]
This feature launched in v1.20 - see https://github.com/aws/containers-roadmap/issues/255#issuecomment-843610648
