### ISSUE TITLE
[EKS] [request]: Support CNI Prefix Delegation when using EKS Auto

### ISSUE THREAD

**Issue by danielloader** [aws/containers-roadmap#2488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Configurable, or defaulting to using VPC CNI Prefix Delegation when using EKS Auto mode.

**Which service(s) is this request for?**
EKS Auto Mode

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Packing lots of smaller pods onto a node than otherwise possible due to ENI limits; knative etc.

**Are you currently working around this issue?**
Not using AWS EKS Auto Mode.

**Comment by danielloader** [comment]
I've since read you can and should configure this in the Karpenter node pools, but the default one isn't configurable.

https://docs.aws.amazon.com/eks/latest/userguide/auto-networking.html#_vpc_cni_networking

**Comment by jayanthvn** [comment]
EKS auto defaults to prefix delegation and when prefix cannot be allocated we fall back to secondary IP mode
