### ISSUE TITLE
[service] [request]: Add / Modify EKS subnets

### ISSUE THREAD

**Issue by b52guy** [aws/containers-roadmap#249]
**Tell us about your request**
What do you want us to build?  
The ability to modify or add subnet's to existing EKS clusters

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Adding subnets when growing EKS environment size / scale.

**Are you currently working around this issue?**
None

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by whereisaaron** [comment]
'[service]' -> '[EKS]'

**Comment by mbarrien** [comment]
Duplicate of #170?

**Comment by mikestef9** [comment]
Closing as duplicate of #170
