### ISSUE TITLE
[EKS] [request]: auto mode: Allow access to set additional tags on resources managed by Data Plane

### ISSUE THREAD

**Issue by rafaelleonardocruz** [aws/containers-roadmap#2495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Some Data Plane components that are being managed by _EKS Auto Mode_ manages resources at AWS Cloud, this is the case mostly:
- [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/)
- [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver)
- [aws-load-balancer-controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller)
- [karpenter](https://github.com/aws/karpenter-provider-aws/)

Although the resources created by _aws-ebs-csi-driver_, _aws-efs-csi-driver_ and _aws-load-balancer-controller_ relies on internal configurations managed through k8s API, allowing the definition of tags BEFORE getting the controller managing concrete resources, _karpenter_'s managed _nodepools_ relies on `nodeclass` `default` (object that defines the tags what EC2 instances should use), which cannot be changed.

This limitation prevent users from adopting _built-in node pools_ if they:
- Need to set tags to perform cost allocation
- If they have guardrails preventing resources without pre-defined tags (E.g. SCPs and Tag Policies)

**Are you currently working around this issue?**
By not using `default` `nodeclass`

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
You need to attach additional permissions to the cluster IAM role to support user defined tags. See EKS documentation for this topic 

https://docs.aws.amazon.com/eks/latest/userguide/auto-learn-iam.html#tag-prop

Lmk if this solves your use case here.

**Comment by rafaelleonardocruz** [comment]
@mikestef9 , I do not wish to create a `NodeClass` with my own defined tags (which would required the setup you've suggested), instead, I'd like to be able to define tags for the `NodePool` managed by AWS (wich users a `NodeClass` named `default`), in order to be able to keep a slim setup. Therefore, your suggestion doesn't help me.

**Comment by mikestef9** [comment]
The built in default NodeClass is managed by AWS and not designed to be edited by users. If you need custom tags, you will need to create your own NodeClass, after adding those required permissions in the docs.

**Comment by pschulten** [comment]
@mikestef9 sorry to comment on a closed issue, but what would be really nice for customers is to have some kind of flag, that propagates every custom tag defined on the eks control plane to all resources created "under the hood".

**Comment by mikestef9** [comment]
That request is tracked here #374
