### ISSUE TITLE
EKS CNI Plugin 1.3

### ISSUE THREAD

**Issue by pauncejones** [aws/containers-roadmap#25]
CNI Plugin 1.3 available by default for all new clusters 
<br>
https://github.com/aws/amazon-vpc-cni-k8s

**Comment by fincd-aws** [comment]
VPC CNI v1.3.0 as released Nov 24, before this issue was made: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.3.0

**Comment by tabern** [comment]
Shipped! https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-eks-releases-vpc-cni-plugin-v1-3-2-with-enhancements-for-/

Includes support for P3dn24XL instances
