### ISSUE TITLE
[ECR] [Basic Scanning for Alpine]: The operating system 'alpine' version 'v3.21' is not supported.

### ISSUE THREAD

**Issue by andrei-dascalu** [aws/containers-roadmap#2503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support Alpine version v3.21 for ECR basic scanning

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Despite an existing request that was marked as done, at the moment I can see that alpine images are not supported on ECR Basic Scanning

**Comment by andrei-dascalu** [comment]
Even in the enhanced image scanning it seems that this base image of alpine 3.21 is not supported

**Comment by rgoltz** [comment]
Hi @andrei-dascalu - Here is my current status (as an AWS-user):

Regarding Basic-Scan:
* Please take a look at this issue: https://github.com/aws/containers-roadmap/issues/2489
* In a nutshell: The "old" Basic-Scan (Clair) will not [never] support Alpine 3.21. The "new" Basic-Scan (called "improved version of basic scanning based on AWS native technology") already supporting Alpine 3.21. (You can switch via Console: >> Private registry >> Features & Settings >> Scanning >> Scanning configuration - You can switch to "Improved version of basic scanning")

Regarding Enhanced-Scan:
* It's still pending/open: https://github.com/aws/containers-roadmap/issues/2490. I've re-tested it today - It's still showing an UnsupportedImageError. I've open a Support-Case with ID 173349973200439 for Enhanced Vulnerability Scan / Inspector.

**Comment by bradg-aws** [comment]
@rgoltz is correct - Clair basic scanning will not be updated with new version support. In addition to switching to the new improved, AWS native basic scanning via console, you can also switch by using the PutAccountSetting API ([docs](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutAccountSetting.html)).

The pending GitHub request is still valid, and I'd like to resolve this in favor of that one for tracking in enhanced. A support case with Inspector also makes sense - as ECR leverages AWS Inspector for enhanced scanning, Inspector support for new versions is key. You can also check the Inspector support docs here: https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr
