### ISSUE TITLE
[EKS] [request]: Enable TTLAfterFinished in alpha on control plane

### ISSUE THREAD

**Issue by geerlingguy** [aws/containers-roadmap#255]
**Tell us about your request**

Kubernetes 1.12 added an awesome new feature that makes working with Jobs so much simpler: [TTL Controller for Finished Resources](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/).

It is currently in alpha, so anyone who wants to be able to run Jobs but then have the Jobs go away after some period of time (or right after they complete) has to build their own Job garbage collection system.

Can EKS allow this feature (feature gate `TTLAfterFinished`) on the EKS Control Plane so we can use it on EKS 1.12 or later?

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I want to not have to write and maintain my own Job garbage collection system since a simple, easy-to-use one is already built into Kubernetes 1.12 and later.

**Are you currently working around this issue?**

I have to maintain my own Job garbage collection system instead of using the alpha one that's built-in.

**Additional context**

Related issue: https://github.com/awslabs/amazon-eks-ami/issues/238

**Attachments**

N/A

**Comment by acesir** [comment]
Any update on this with Kubernetes 1.13 version?

**Comment by bart613** [comment]
> Any update on this with Kubernetes 1.13 version?

It's not working on EKS 1.13.

**Comment by whereisaaron** [comment]
I’d like this feature too. It entered alpha in 1.12 but it has not graduated to beta, it is still alpha in 1.15. That means there is almost no chance we’ll see it enabled on managed k8s before next year at the earliest.
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

The way to promote it is to work with the k8s project to get the feature over the line to a beta release. Then it will be available on managed k8s 3-6 months later.

The feature is an active controller with a watch, queue, and workers. So not much different than an operator. You could try https://github.com/lwolf/kube-cleanup-operator

**Comment by doprdele** [comment]
I would like this feature as well.

**Comment by whereisaaron** [comment]
Also, even simpler than an operator, CronJobs with something like:
```
kubectl delete job $(kubectl get job -o=jsonpath='{.items[?(@.status.succeeded==1)].metadata.name}')
```
While we wait for native support.

**Comment by imdhruva** [comment]
> Also, even simpler than an operator, CronJobs with something like:
> 
> ```
> kubectl delete job $(kubectl get job -o=jsonpath='{.items[?(@.status.succeeded==1)].metadata.name}')
> ```
> 
> While we wait for native support.

that is very simply put and not a solution; it will almost break a lot of things than solving a  problem. I would like something asynchronous for this as a work-around. so after job deployment we start the watch and then after say n seconds we run trigger `kubectl delete job $(kubectl get job -o=jsonpath='{.items[?(@.status.succeeded==1)].metadata.name}')`

Currently though I am using [helmfile](https://git.invoice2go.org/ops/helmfile) for performing all the deployments so I am leveraging `postSync` hooks to watch for a job completion (my job only takes <40 secs to run) and then perform 
```bash 
echo Logs:  $(kubectl logs job/abc) && kubectl del job/abc
```
 Leveraging helm-hooks would be ideal. In that we run a `post-install` job to perform job-deletion. In my case though that's a deployment overhead because the post-installjob would need a deployment container which is heavy and will create a needless resource overload on eks when I can very well run the helmfile hook locally in the deployment pipeline

**Comment by TonyBarganski** [comment]
I would like this feature too which doesn't seem to be working on EKS version **v1.14.6**

**Comment by seb-steuer** [comment]
Yep I would like to see that added too. Very useful for anyone that launch jobs frequently and then need to do cleanups. TTL controller would solve that

**Comment by whereisaaron** [comment]
Unfortunately this is still an **alpha** feature in 1.16. So it will be at least 9 months or more before it is enabled in EKS, that is assuming it even graduates to beta in 1.17. So could a year or more in the future. So for now you should consider an alternative such as a CronJob or an operator.

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by antoniotamer** [comment]
Would be really nice if EKS allowed customers to enable K8S alpha features, at our own risk. I hope the number of votes on this issue is an indication that we are willing to live with the risk.

**Comment by eightlimbed** [comment]
+1

**Comment by frankgu968** [comment]
+1

**Comment by jaygorrell** [comment]
Put +1s on the top post rather than replies

**Comment by mageyuki** [comment]
👍

**Comment by bryanisgreat** [comment]
has this been updated? it appears to work on EKS v1.14.8

**Comment by stanislav-zaprudskiy** [comment]
> has this been updated? it appears to work on EKS v1.14.8
Doesn't work on EKS 1.14.9

**Comment by bryanisgreat** [comment]
Yeah, i was mistaken. the spec validated fine when applied, but the setting had no effect on ttl

**Comment by aramse** [comment]
Here's a quick solution that provides the same functionality via a `ttl` annotation. Feedback/PRs are welcome!

https://github.com/aramse/k8s-job-reaper

**Comment by casidiablo** [comment]
![waiting](https://media.tenor.co/images/a8fffcf7a02aa895eefb6a52be888637/tenor.gif)

**Comment by Schnitzel** [comment]
waiting on this as well, in the meantime found https://github.com/lwolf/kube-cleanup-operator and happy with it.

**Comment by whereisaaron** [comment]
TTLAfterFinished is still alpha in 1.18, and that doesn't appear to be changing in 1.19, so I think it will be at least 2021 before we could hope to see this feature in EKS. So for now you should consider an alternative like https://github.com/aramse/k8s-job-reaper

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates

**Comment by kqzh** [comment]
you also can consider a controller implementation like https://github.com/kqzh/kube-job-cleaner

**Comment by scravy** [comment]
There's a broader issue which would enable this as well: https://github.com/aws/containers-roadmap/issues/512

**Comment by mhumeSF** [comment]
This feature has graduated to beta and coming in 1.21 release. https://github.com/kubernetes/kubernetes/pull/98678

**Comment by kirtichandak** [comment]
TTL controller his now available with EKS support for Kubernetes version 1.20. We made an exception and enabled an alpha feature in 1.20 since the TTL controller has already moved to beta in 1.21, it has seen no significant changes over the past few releases.

**Comment by artem-zinnatullin** [comment]
That’s very good news, thanks!
