### ISSUE TITLE
[ECS, App Mesh] App Mesh integration in the ECS console

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#258]
The ECS console will enable users to add a ECS service to an existing mesh.  The steps are as follows:
1. Create a new task definition (or edit an existing one) in the ECS Console.
2. Click the checkbox marked 'Enable App Mesh Integration' and fill in the Envoy image ID (pre-filled with a default choice), mesh name, and virtual node name.  (This will automatically add Envoy to your task definition, add proxyConfiguration, configure container ordering, and add the necessary environment variables).
3. Save the new task definition.
4. Create/edit an ECS service that uses the task definition to use the task definition revision created in step 3.  
5. If not already enabled, enable service discovery for the ECS service.
6. Deploy the new service version.
Your ECS service will now be integrated into your mesh as a[ virtual node](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_nodes.html)!

**Comment by steven-cuthill-otm** [comment]
will this have the added support into cloudformation as part of the task definition resource   ?

**Comment by coultn** [comment]
> will this have the added support into cloudformation as part of the task definition resource ?

This feature is specifically targeted at the ECS console, not CloudFormation.  What are you asking for in Cloud Formation?

**Comment by coultn** [comment]
This has launched!  Look for 'Enabled App Mesh Integration' when creating or editing a task definition in the console.

**Comment by 0xMH** [comment]
@coultn Hey! Is there a reason I don't have a `Service Integration` section on ECS FARGATE? I only have this `Proxy Configuration` as shown on this pic.
![image](https://user-images.githubusercontent.com/12420351/79259336-d60e3d00-7e8c-11ea-813c-a7d5c1ecc287.png)

**Comment by pavneeta** [comment]
@0xMH You can configure your ECS task definition with the App Mesh Virtual node and Mesh name using the Service Integration as shown in the image. However these are auto-populated, so you need to first create a Mesh, Virtual Service, Nodes and Router using the Appmesh APIs or Console. 

ECS Console: 
![Screen Shot 2020-04-27 at 4 16 54 PM](https://user-images.githubusercontent.com/51172702/80430292-11543700-88a3-11ea-8cd5-112329e15912.png)

App Mesh Console:
![Screen Shot 2020-04-27 at 4 21 01 PM](https://user-images.githubusercontent.com/51172702/80430336-3052c900-88a3-11ea-9ba8-5a1e1371b8ee.png)
