### ISSUE TITLE
EKS Control Plane Logs

### ISSUE THREAD

**Issue by pauncejones** [aws/containers-roadmap#26]
View Kubernetes API Server and Audit Logs in your account.

**Comment by brynmathias** [comment]
Would be nice to be able to push the logs into an Elasticsearch service running on aws.

**Comment by jesse-peters** [comment]
If it goes to cloudwatch it would be more flexible than elasticsearch - would also follow the ECS pattern.

**Comment by vijaykatam** [comment]
Is this going to include other control plane components such scheduler, kubelet and controller-manager? Also interested in logs from iam authenticator pod for auditing purposes.

**Comment by tiffanycitra** [comment]
Is there an ETA for this feature?

**Comment by tdmalone** [comment]
@tiffanycitra 
From the [README](https://github.com/aws/containers-roadmap/blob/master/README.md#faqs):
> A: Because job zero is security and operational stability, we can't provide specific target dates for features.

However given this has just moved to Coming Soon, that's a good sign! 😅

**Comment by sankareds** [comment]
+1

**Comment by max-lobur** [comment]
How is it supposed to be PCI compliant if I can't get an audit log (k8s events / api logs)

**Comment by pc-rshetty** [comment]
Our migration to EKS has come to a halt due to this. From security and audit perspective i have no way to know who did what. So this has become a blocker for us.

**Comment by tabern** [comment]
Just shipped! You can now export Kubernetes control plane logs from your EKS clusters to CloudWatch Logs.

- https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-eks-now-delivers-kubernetes-control-plane-logs-to-amazon-/
- https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

**Comment by nickschuch** [comment]
Super awesome! Thanks to everyone involved!

**Comment by pc-rshetty** [comment]
thank you very much AWS EKS team

**Comment by bnutt** [comment]
Thank you for this!

**Comment by StevenACoffman** [comment]
Can you enable this with cloudformation yet? The API yes: https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html

**Comment by tabern** [comment]
@pc-rshetty so happy to hear that this unblocked you!
@StevenACoffman - yes. I've opened https://github.com/aws/containers-roadmap/issues/242 to track this.

**Comment by rtkgjacobs** [comment]
Side note, this isn't available within troposphere yet. I already opened a ticket there. 

See (or vote) - https://github.com/cloudtools/troposphere/issues/1362

**Comment by pc-rshetty** [comment]
@tabern yeah our Security and compliance had refused to let us migrate if this was not in place. so thank you very much. We moved couple into EKS but to move all existing production workload we need it to be fool proof.

**Comment by pc-rshetty** [comment]
Today i saw on our prod cloudwatch(we did not configure master logs yet) that kube-controller-manager, authenticator, kube-apiserver-audit logs showingup. I haven't researched on it yet but is it due to this new feature(some kind of default )

**Comment by pc-rshetty** [comment]
ok sorry , i just checked our devops went superfast and enabled it :) so that explains why we see the logs now.
