### ISSUE TITLE
[ECS] Container ordering configuration UI in the ECS console

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#260]
This will add support for [container ordering](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDependency.html) in the ECS console.

**Comment by dsouzajude** [comment]
Would also be great if Container Ordering was supported in CloudFormation. We're in great need of this in CloudFormation. Do I create a new proposal for this or can we just label it here?

**Comment by coultn** [comment]
It already is actually!  See here:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

On Apr 20, 2019, at 12:35 PM, Jude DSouza <notifications@github.com<mailto:notifications@github.com>> wrote:


Would also be great if Container Ordering was supported in CloudFormation. We're in great need of this in CloudFormation. Do I create a new proposal for this or can we just label it here?

**Comment by coultn** [comment]
This has shipped!
