### ISSUE TITLE
[EKS] Encrypt secrets at rest in etcd

### ISSUE THREAD

**Issue by ChrisCooney** [aws/containers-roadmap#263]
**Tell us about your request**
As part of K8s 1.13, encryption of k8s secret resources inside etcd is now fully supported. EKS should support this, as many organisations require that their sensitive information is stored in an encrypted format.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Many organisations have a hard requirement that sensitive information is encrypted, both in transit and in storage. Currently, EKS does not support encryption of k8s secrets at rest, which creates a barrier to adoption.

**Are you currently working around this issue?**
There are third party controllers that we're using, but since k8s 1.13 is going to support this natively, this will likely become the dominant method for at rest encryption.

**EDIT**: Since EKS does support encryption in Etcd, this should clearly be documented somewhere in the Aws documentation.

**Comment by ejc3** [comment]
AWS encrypts etcd at rest:
https://blog.uprightvinyl.co.uk/2018/02/08/aws-builders-day-part-3-kubernetes-on-aws-with-amazon-eks/

Are you looking for keys you control?

**Comment by ChrisCooney** [comment]
Ah wow, nevermind then. I read an article recently that pointed out EKS was still plaintext at rest. I'll be sure to comment on the article. Thank you, I'll close this now.

**Comment by thisisananth** [comment]
I think we would be more comfortable if AWS states that in their documentation. It is not stated anywhere!!!

**Comment by temal-** [comment]
I opened an issue about this exact topic a couple of days ago with AWS support. I'm still waiting for an answer.

I also asked to put this information somewhere in the documentation to make sure I don't have to forward customers to a third party blog when they ask me about encryption of EKS.

**Comment by thisisananth** [comment]
HI @temal- Did you hear back from AWS about this?  Can you please update this with what they told? Thanks!

**Comment by temal-** [comment]
@thisisananth Sadly not. As soon as I hear back, I'll write it down here!

@ChrisCooney Do you think it is worth reopening this issue? From my point of view it is still not clear if EKS supports encryption at rest for etcd.

**Comment by ChrisCooney** [comment]
I'm inclined to agree. The absence of detail in the documentation is enough. Perhaps the title needs to change to prevent it being benched.

**Comment by jacob-koren-zooz** [comment]
Any update on this issue? Was the documentation updated? I can't find anything about encryption of secrets in EKS

**Comment by temal-** [comment]
Latest update:

> I heard from the service team that they are working on the official documentation and will be published soon.

**Comment by pmnhatdn** [comment]
Hi @temal- have you got any update from AWS on the update of EKS secret encryption documentation?

Thanks

**Comment by temal-** [comment]
@pmnhatdn Not yet, no.

**Comment by temal-** [comment]
I got an answer:

> Greetings Malte!!!
> I appreciate for the patience while I get the response from the service team.
> Good news is that I was able to get the answer to this particular query from service team. The answer is yes, the data stored by etcd is encrypted at rest. 
> EKS team planning to share the details through the FAQ in future, however no ETA can be provided.
> Again, should you have any other questions or queries, please so not hesitate to reach out to us and we will be happier to assist.
> Have a great day ahead!
> Best regards,

🎉 

My issue with AWS about this topic is closed. I guess we should let the github issue open till the documentation appears in the [FAQ](https://aws.amazon.com/eks/faqs/). Else this comment from me is as worthy as the blogpost posted in the beginning.

**Comment by fgreinacher** [comment]
Based on the information above is it safe to assume that using Kubernetes secrets for sensitive data in a production environment is an appropriate solution?

**Comment by jason-riddle** [comment]
Can this title be updated to “Add etcd encryption-at-rest documentation to EKS service docs/faq”? The title in its current form makes it seem like etcd isn’t encrypted at rest which is not the case.

**Comment by tabern** [comment]
It seems like there are two asks here, a public statement about the encryption of etcd within EKS and the ability to further encrypt Kubernetes secrets using a customer managed key (CMK).

As of today, we now include a public statement about etcd encryption in the [EKS documentation](https://docs.aws.amazon.com/en_us/eks/latest/userguide/clusters.html):

> All of the data stored by the etcd nodes and associated Amazon EBS volumes is encrypted. Amazon EKS uses master encryption keys that generate volume encryption keys which are managed by the Amazon EKS service.

As for the second ask, this is something we are actively working on. Specifically, we plan to enable the [AWS Encryption Provider](https://github.com/kubernetes-sigs/aws-encryption-provider) on EKS and allow you to provide a KMS CMK that will be used for envelope encryption of Kubernetes secrets on the cluster. 

We will keep this issue open until this feature is delivered.

-nate

**Comment by ChrisCooney** [comment]
As the person who opened this issue, the docs was my only ask. Thanks for
sorting ❤️❤️
