### ISSUE TITLE
[EKS] New EKS Region: Hong Kong

### ISSUE THREAD

**Issue by paulwilljones** [aws/containers-roadmap#267]
Tell us about your request
New region support in Hong Kong (ap-east-1)

Which service(s) is this request for?
Amazon EKS

This would facilitate EKS support in China in a feature rich region.

**Comment by tabern** [comment]
We're excited to announce that EKS is now generally available in the AWS Hong Kong region (`ap-east-1`)!

You can get the worker AMI IDs for this region in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html). 

_**Note**  GPU instance types are not available in Hong Kong region, so Amazon EKS does not publish the Amazon EKS-optimized AMI with GPU support in this region._
