### ISSUE TITLE
[Fargate] [request]: Fargate in GovCloud

### ISSUE THREAD

**Issue by ellj** [aws/containers-roadmap#268]
**Tell us about your request**

Add support for Fargate in GovCloud

**Which service(s) is this request for?**

Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Eliminate the need to manage underlying server instances when using containers.

**Are you currently working around this issue?**

Managing EC2 instances :-(

**Comment by ellj** [comment]
Thanks!

**Comment by coultn** [comment]
Launched!  https://aws.amazon.com/about-aws/whats-new/2019/06/aws_fargate_now_available_in_aws_govcloud/
