### ISSUE TITLE
[EFS] [request]: Support for Canada (Central)

### ISSUE THREAD

**Issue by schottsfired** [aws/containers-roadmap#274]
Requesting EFS support for `ca-central-1`

Use case is running `StatefulSet`s on EKS that tolerate zone outages.

**Comment by tabern** [comment]
EFS is [generally available in the AWS Canada (Central) region](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/). 
Open issue for adding EKS support in this region is here: https://github.com/aws/containers-roadmap/issues/113
