### ISSUE TITLE
EKS [request]: PriorityClass

### ISSUE THREAD

**Issue by marcincuber** [aws/containers-roadmap#276]
**Tell us about your request**
I am not sure but it looks like PriorityClass from scheduling.k8s.io/v1 are not support. Could I ask for a feature which enables me to create PriorityClass resources in EKS?

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am trying to use PriorityClasses. I can't create them as I am getting an error; no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1"

Sample script;
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority
value: 5000000
globalDefault: false
```

**Are you currently working around this issue?**
N/A

**Additional context**

1.11 | beta | enabled by default
1.12 | beta | enabled by default
1.13 | beta | enabled by default
1.14 | stable | enabled by default
[relevent docs](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/)

Looks like it is turned into stable feature and previously it was in beta which means that EKS should be supporting it.

May I find out what the update is on PriorityClasses for EKS?

**Comment by szymonpk** [comment]
Shouldn't it be `apiVersion: scheduling.k8s.io/v1` then?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl explain priorityclass
KIND:     PriorityClass
VERSION:  scheduling.k8s.io/v1beta1
...
```

```
$ kubectl
explain priorityclass --api-version v1
error: Couldn't find resource for "/v1, Kind=PriorityClass"
```

**Comment by marcincuber** [comment]
Yeah, thanks for clarifying and solving my issue.
