### ISSUE TITLE
[ECS] [request]: Allow --security-opt to be specified for Windows containers

### ISSUE THREAD

**Issue by jdebbink** [aws/containers-roadmap#277]
When creating an ECS task definition for a Windows container, I get a 400 bad request when trying to specify `--security-opt`. The [documentation page for task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html) says:
```
This parameter is not supported for Windows containers or tasks using the Fargate launch type.
```
However ***this is a valid option for Windows containers*** and is required in order for Windows authentication to work. Here is [Microsoft's documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#run-a-container-with-a-gmsa) for getting Windows containers to work with Windows auth, noting the use of that flag.

My organization worked around this by forking the ECS agent and looking for a certain tag on the EC2 instance and passing the parameters to the `docker run --security-opt`.

Since this is a valid flag to set for Windows containers, I'm requesting the removal of this validation and allow `--security-opt` to be specified on task definitions for Windows containers.

**Comment by pavneeta** [comment]
Hi Justin, 

Thank you for your valued feedback. We are currently researching this feature for Windows containers on ECS and I had a couple of follow-up questions regarding your comment :

- What is the use case for you wanting to pass through --security-opt for docker run? Is this for gMSA support for windows containers or are using some other form of authentication construct?
- Would you rather use the existing dockerSecurityOptions parameter in ECS container definition or rather use a new field in ECS task definition specifically for Windows authentication use cases?

Thank you so much for your input.

**Comment by jdebbink** [comment]
Hi that is great news!

Yes, this is for gMSA support. 

A new field where I can specify the credential spec specifically would be nice but reusing the existing field would be fine as well.

**Comment by pavneeta** [comment]
Closing this issue as it is the same as #346
