### ISSUE TITLE
[Fargate/ECS] [request]: Fargate in EU (Stockholm)

### ISSUE THREAD

**Issue by raehalme** [aws/containers-roadmap#280]
**Tell us about your request**
Please add Fargate to ECS in the EU (Stockholm) region, ie. eu-north-1.

**Which service(s) is this request for?**
Fargate and ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to be able to run containers in ECS without managing EC2 container instances.

**Are you currently working around this issue?**
I am running EC2 container instances in the ECS cluster.

**Comment by perbergland** [comment]
Any news to report on the roadmap here?

**Comment by perbergland** [comment]
Ping @coultn

**Comment by coultn** [comment]
We are still working on it!   We will provide an update here as soon as the status changes.

**Comment by akshayram-wolverine** [comment]
Shipped! https://aws.amazon.com/about-aws/whats-new/2019/09/aws-fargate-now-available-in-eu-stockholm-paris-middle-east-bahrain-regions/
