### ISSUE TITLE
[ECS, Fargate] Delete cluster warning when tasks are running

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#281]
In the ECS console, present a warning before allowing a user to delete a cluster that has running tasks.

**Comment by jdebbink** [comment]
I was shocked by this as well when I accidentally deleted a cluster (luckily only a dev environment). You have to type `delete me` to delete a service but destroying a whole cluster is one click away?

**Comment by coultn** [comment]
You have to type 'delete me' when deleting a cluster also, but it is not checking if there are running tasks.  Is there more checking/verification needed beyond typing 'delete me' in the console dialog?

**Comment by coultn** [comment]
Just saw this is a duplicate issue, whoops!:  https://github.com/aws/containers-roadmap/issues/206
