### ISSUE TITLE
[ECS, Fargate] CloudWatch metrics for number of running and pending tasks per service and cluster

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#282]
ECS should publish CloudWatch metrics that show the number of currently running tasks, as well as the number of tasks not yet running but waiting to be run, both per service and per cluster.

**Comment by Missshao** [comment]
+1 need this feature.

**Comment by gaddamanugu** [comment]
+1 need this

**Comment by coultn** [comment]
This functionality will be provided by https://github.com/aws/containers-roadmap/issues/70

**Comment by coultn** [comment]
This is now in preview: https://aws.amazon.com/about-aws/whats-new/2019/07/introducing-container-insights-for-ecs-and-aws-fargate-in-preview/

**Comment by akshayram-wolverine** [comment]
Shipped! Learn more here: https://aws.amazon.com/about-aws/whats-new/2019/08/container-monitoring-for-amazon-ecs-eks-and-kubernetes-is-now-available-in-amazon-cloudwatch/
