### ISSUE TITLE
EKS: Get-Token CLI Subcommand

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#292]
**Tell us about your request**
Replace the need for the aws-iam-authenticator as a separate binary. 

**Which service(s) is this request for?**
Amazon EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Previously, setting up an Amazon EKS cluster required you to download and configure the binary for the AWS IAM Authenticator in order to authenticate using IAM to your EKS cluster.

Now, the Amazon EKS CLI includes the subcommand eks get-token that generates the required token to authenticate to the EKS cluster. You can use update-kubeconfig to generate a kube config that will now use the get-token command, instead of the aws-iam-authenticator binary. This simplifies setting up and connecting to your Amazon EKS cluster.

**Note** this removes a setup for setting up an EKS cluster, it is not a sub-command that users need to explicitly run.

**Getting started**
What's new: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication/

EKS documentation: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html

**Comment by mbarrien** [comment]
Any plan to add an equivalent of aws-iam-authenticator token --token-only support?

**Comment by devkid** [comment]
Any one else having massive problems with this update? With this update:
* you need to have a region set when running `kubectl`; this was not the case before and also doesn't really make sense considering the token generation is offline and doesn't incorporate the region
* even with the region set, we got `Unauthorized` errors from kubectl in like 9 out of 10 invocations; `kubectl --v=9` wasn't conclusive about the reason of these errors at all (and we didn't investigate further yet, we switched back to version 1.16.154 of the AWS CLI)
