### ISSUE TITLE
[EKS] [request]: Support DryRun on API server

### ISSUE THREAD

**Issue by vdboor** [aws/containers-roadmap#294]
**Tell us about your request**
Could you enable the `DryRun` feature gate on the API server?
This feature is available in Kubernetes 1.13, but on 1.12 it's still an alpha feature.

See: https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/

**Which service(s) is this request for?**
This could be EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
During deployments, we'd like to use `kubectl --server-dry-run` to make sure the whole deployment output contains valid Kubernetes syntax. Otherwise, there is a risk of partial deployments.

The used deployment strategy is running: `kustomize build | kubectl apply -f -`

**Are you currently working around this issue?**
Not possible.

**Comment by bdashrad** [comment]
This also would allow the use of `kubectl diff` which would be super useful

**Comment by tabern** [comment]
Dry-run and diff are both stable and available from Kubernetes v1.13 (beta) and [Kubernetes 1.18 (stable)](https://v1-18.docs.kubernetes.io/docs/reference/using-api/api-concepts/#dry-run). Closing this issue as these features are available for all EKS supported versions of Kubernetes.
