### ISSUE TITLE
ECR Tagging for Resources & Cost Allocation

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#3]
Customers will be able to tag ECR resources and attribute costs based off of tags.

**Comment by tabern** [comment]
https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-ecr-now-allows-repository-tagging/

**Comment by jritsema** [comment]
Terraform support for this: https://github.com/terraform-providers/terraform-provider-aws/issues/6923

**Comment by nikovirtala** [comment]
> Terraform support for this: [terraform-providers/terraform-provider-aws#6923](https://github.com/terraform-providers/terraform-provider-aws/issues/6923)

Terraform support will be released as a part of AWS provider version 1.53.0, later this week: https://github.com/terraform-providers/terraform-provider-aws/issues/6896
