### ISSUE TITLE
[EKS]: Kubernetes v1.10 Deprecation (July 22, 2019)

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#300]
In line with the Kubernetes community support for Kubernetes versions, Amazon EKS will deprecate Kubernetes version 1.10 on **July 22, 2019**. On this day, you will no longer be able to create new 1.10 clusters and all EKS clusters running Kubernetes version 1.10 will be updated to the latest available platform version of Kubernetes version 1.11.

We recommend that you update your 1.10 EKS clusters to Kubernetes version 1.11, 1.12, or 1.13 as soon as possible.

Learn more:
* [Updates to Amazon EKS Version Lifecycle](https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/)
* [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by tabern** [comment]
Starting today, we're deprecating K8s v1.10 in Amazon EKS. This week we'll be removing the ability to create v1.10 clusters. Next, we'll begin updating existing 1.10 clusters to v1.11.

**PLEASE UPDATE**
If you have a v1.10 Kubernetes cluster, please update it to v1.11 ASAP to avoid any service interruption.

**Comment by MarcusNoble** [comment]
Should this not be closed and replaced with a 1.11 deprecation issue?

**Comment by tabern** [comment]
@MarcusNoble yes. We are in the final stages of 1.10 deprecation now. Closing this. EKS 1.11 deprecation notice is here: https://github.com/aws/containers-roadmap/issues/464
