### ISSUE TITLE
[EKS] [Win]: EKS Windows nodes Webhooks

### ISSUE THREAD

**Issue by dayyehm** [aws/containers-roadmap#301]
Is there any documentation on the VPC-Resource-Controller , mutating admission webhook and what is the function of those in this configuration

Can you please provide any documentation on that.

**Comment by vsiddharth** [comment]
The `vpc-resource-controller` is designed to manage VPC level resource constructs. 
The `vpc-admission-webhook` is used to inject extended resource requirements for pods. 

For more details, please take a look at `https://static.sched.com/hosted_files/kccnceu19/99/Kubecon-EU-2019-Template-Deck.pdf`

**Comment by mikestef9** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
