### ISSUE TITLE
Fargate in Paris data center

### ISSUE THREAD

**Issue by daya** [aws/containers-roadmap#309]
**Tell us about your request**
Make Fargate available in Paris data center

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have hospitals in France and its the country's law that does not permit apps to be running and data to be hosted outside of France.

**Are you currently working around this issue?**
Yes by using EC2

**Additional context**
Read about French laws around HealthCare data

**Attachments**

**Comment by daya** [comment]
any ETAs on it?

**Comment by akshayram-wolverine** [comment]
Shipped! https://aws.amazon.com/about-aws/whats-new/2019/09/aws-fargate-now-available-in-eu-stockholm-paris-middle-east-bahrain-regions/
