### ISSUE TITLE
Spot Pricing for Containers (Fargate)

### ISSUE THREAD

**Issue by tedivm** [aws/containers-roadmap#31]
One of the things still holding me on EC2 when Fargate and Sagemaker may be better suited is the lack of spot pricing for containers. I have a lot of tasks which are not time critical which could really benefit from this.

**Comment by deleugpn** [comment]
My company actually decided to sacrifice a few bucks to help bring the numbers up for Fargate. We run about 100 containers 24/7 worldwide on Fargate. We know EC2 cluster can be quite cheaper but if Fargate doesn't get traction it might take longer for them to evolve it. 
We're not big enough to matter, but we like to believe we help the cause and I bet there's tons of smaller companies that cannot afford to do the same.

**Comment by deleugpn** [comment]
We didn't get spot container yet, but we just got a 35/50% cut on price!

**Comment by asztal** [comment]
I guess this can't be far off now if it's showing on the pricing/FAQ pages. (Unless it was there before, but it looks new to me)

> Fargate supports Spot and Compute Savings Plan pricing options just like with Amazon EC2 instances. You can find additional details on the pricing page.

> Fargate Spot provides up to 70% discount for interrupt-tolerant applications, and Compute Savings Plan offers up to 50% discount on committed spend for persistent workloads.

![Screenshot_20191203-180948_Chrome](https://user-images.githubusercontent.com/68302/70077438-c33f4e00-15f8-11ea-9f21-2bd1c7ae206c.jpg)

**Comment by akshayram-wolverine** [comment]
Shipped! https://aws.amazon.com/blogs/aws/aws-fargate-spot-now-generally-available/
