### ISSUE TITLE
Fargate ephemeral volume encryption 

### ISSUE THREAD

**Issue by akshayram-wolverine** [aws/containers-roadmap#314]
AWS Fargate will encrypt ephemeral volumes with a service managed key.

**Comment by pda** [comment]
Thanks for putting this on the public roadmap.

It's common for web servers to spool large HTTP requests (uploads) to temporary disk, and for applications to use temporary disk for building large downloads etc. This data spooled to disk often contains sensitive customer data including personally identifying information.

Many businesses would make contractual commitments to their customers that this data is always encrypted at rest. One could argue that “on disk” doesn't necessarily mean “at rest” when it's ephemeral storage scoped to the lifetime of a container/Task. But one could also argue the other way.

We assume that this EBS data is securely made unreadable after the container/Task ends, prior to the underlying storage being reallocated to another AWS customer. However without encryption (using a Task-scoped key) we're less confident that another AWS customers couldn't somehow read that data later on.

**Comment by yb101** [comment]
can the volume be encrypted by customers' KMS key or account KMS key?

**Comment by gamma425** [comment]
any update on this?  particularly with KMS-CMK?

**Comment by maly7park** [comment]
I have the same issue here. We can't encrypt the data itself as we are doing processing on it and we are working around that by encrypting the drive. However, in the case of fargate there is no option to encrypt the drive. Using KMS as an option to encrypt the drive will be a really good step for securing data end to end

**Comment by sbe-arg** [comment]
My 2 cents here while this feature is still being built and in order to comply with regulations:

https://aws.amazon.com/about-aws/whats-new/2018/03/aws-fargate-supports-container-workloads-regulated-by-iso-pci-soc-and-hipaa/

To review, accept, and manage the status of the BAA for your account, sign in to AWS Artifact in the AWS Management Console.

https://aws.amazon.com/compliance/hipaa-eligible-services-reference/

**Comment by vattybear** [comment]
Announcement : https://aws.amazon.com/about-aws/whats-new/2020/05/aws-fargate-now-encrypts-data-stored-on-ephemeral-storage-by-default-in-platform-version-1-4/

Detailed blog : https://aws.amazon.com/blogs/containers/introducing-server-side-encryption-ephemeral-storage-using-aws-fargate-managed-keys-aws-fargate-platform-version-1-4/

This is using a service key - see https://github.com/aws/containers-roadmap/issues/915 for the proposal around Customer Managed CMK / KMS...

**Comment by akshayram-wolverine** [comment]
Shipped: https://aws.amazon.com/about-aws/whats-new/2020/05/aws-fargate-now-encrypts-data-stored-on-ephemeral-storage-by-default-in-platform-version-1-4/

As @vattybear called out we are working on CMK with KMS tracking here: [#915 ](https://github.com/aws/containers-roadmap/issues/915)
