### ISSUE TITLE
[EKS] [request]: Integration with App Service Mesh

### ISSUE THREAD

**Issue by piclemx** [aws/containers-roadmap#320]
**Tell us about your request**
What do you want us to build?
It will be great to have a integration with App Service Mesh. Like the demand for ECS. It will be a killing feature.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Simplify the deployment of a solution like this

**Are you currently working around this issue?**
Control plane outside of the cluster + inside the cluster

**Comment by shubharao** [comment]
@piclemx We already have an integration of AWS App Mesh with EKS - https://docs.aws.amazon.com/eks/latest/userguide/mesh-k8s-integration.html
Is this what you are asking about?

**Comment by piclemx** [comment]
Yeah, it's their now. Before wasn't.

I will closed it.
