### ISSUE TITLE
[ECS] Support use of swap memory

### ISSUE THREAD

**Issue by mhowell-ims** [aws/containers-roadmap#322]
I have an ECS workload that requires a very large amount of memory. The performance of the workload is secondary, so using swap memory would be the ideal solution.

This issue is related to #124. In that issue, @samuelkarp suggested opening a new issue if swap support is still needed. Since several others added +1 to #124 after it was closed, I'm opening this issue now.

**Comment by coultn** [comment]
This launched!  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-swap.html

**Comment by wwwouter** [comment]
Will there ever be Fargate support?

**Comment by thomas-maschler** [comment]
And support for Batch?

**Comment by effyteva** [comment]
Any updates on Fargate support for swap?

**Comment by sampathkolachana** [comment]
+1 for fargate support

**Comment by 01101100** [comment]
+1 for fargate support

**Comment by davidjb99** [comment]
+1 for fargate support

**Comment by tamirhad** [comment]
+1 fargate

**Comment by SonerAbay** [comment]
+1 for fargate

**Comment by vesahyp** [comment]
+1 for fargate swap support. 30GB is not enough.

**Comment by hugofspotqa** [comment]
+1 for fargate

**Comment by LordRatte** [comment]
+1 ~forward~ Fargate

**Comment by joeygeo** [comment]
+1 for fargate swap support.

**Comment by cbatson** [comment]
Please 👍  #2061 for Fargate swap support.

**Comment by raulamoretti** [comment]
for Fargate swap support.

**Comment by mhmdksh** [comment]
+1 for fargate swap support

**Comment by cb-shreyassreenivas** [comment]
+1 for fargate swap support
