### ISSUE TITLE
[ECS] expose container's Docker ID through ECS describe-task API

### ISSUE THREAD

**Issue by adnxn** [aws/containers-roadmap#323]
explore what would it mean expose each container's Docker ID through [describe-tasks](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-tasks.html).

related issue tracking demand for feature: https://github.com/aws/amazon-ecs-agent/issues/258

**Comment by tonyghita** [comment]
It's very difficult to find a given container without this functionality. I believe the only way currently is to manually go through the console UI and open each task in a service. This is pretty unwieldy with hundreds of containers.

**Comment by pavneeta** [comment]
Hi Everyone,
Today, August 30th , Amazon ECS launched the capability for customers to lookup the runtime container IDs of containers running as part of an ECS task. Now, the describe-tasks and stop-task APIs return the runtime container id for all the containers within an ECS task. - https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-ecs-now-exposes-runtime-containerids-to-apis-and-ecs-console/
