### ISSUE TITLE
New EKS region: Frankfurt

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#33]
EKS availability in eu-central-1

**Comment by praveenchandran** [comment]
Any estimate on when it would be available ? :)

**Comment by praveenchandran** [comment]
Any estimates on this ? :)

**Comment by rudybutter** [comment]
Would love to hear an estimate on this. Can't wait to move my clusters from Ireland to Frankfurt

**Comment by therealppa** [comment]
@praveenchandran @rudybutter If you read the FAQ in the readme you will find the answer to your question:

"Q: Why are there no dates on your roadmap?
A: Because job zero is security and operational stability, we can't provide specific target dates for features."

**Comment by rudybutter** [comment]
Not having dates on your roadmap does not mean you won't know shorter term release date for features, but fair enough.

**Comment by abby-fuller** [comment]
shipped 12/19! https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-eks-available-in-frankfurt-singapore-sydney-and-tokyo-regions/
