### ISSUE TITLE
ECS Support for Cuda 10.0

### ISSUE THREAD

**Issue by sinzin91** [aws/containers-roadmap#336]
### Summary
Are there plans to support cuda 10.0?  Right now the ECS AMI for GPU only supports cuda 9.2.

### Description
The current recommended ECS GPU AMI `amzn2-ami-ecs-gpu-hvm-2.0.20190301-x86_64-ebs (ami-0ebf2c738e66321e6)` comes with cuda 9.2 out of the box.  This means that I can't run images with cuda 10.0, since it throws driver errors: 

```STOPPED, Reason CannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=GPU-9ee6128b-d046-aeb6-a2f5-e7cd63b99197 --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=22591 /var/lib/docker/overlay2/cdd0f19b4d3fd942053e77120d68a52389466dde9d59f9ec9995a490faf9add0/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied
condition: driver < 385\\\\n\\\"\"": unknown, Known Sent: NONE] sent: false
```

If I install cuda 10.0 with the cuda toolkit run file `cuda_10.0.130_410.48_linux.run` manually on `ami-0ebf2c738e66321e6`, the tasks are able to run.  I created an AMI from this and am able to launch successfully with that custom AMI.

The deep learning base AMI `Deep Learning Base AMI (Amazon Linux 2) Version 17.0 (ami-0259ee25c7fe9214d)` comes with cuda 10.0, but does not have the ECS agent.  If I manually install the agent, it joins the cluster but I get an error when trying to start the task: `Reasons : ["RESOURCE:GPU"]`

It would be great to just have an ECS AMI that support cuda 10.0 out of the box.

**Comment by coultn** [comment]
The latest AMI supports CUDA >= 10.0. Closing this.

**Comment by schematical** [comment]
In case anyone else stumbles upon this in the future if your using a custom AMI and the ECS agent you need to make sure that you set ECS_ENABLE_GPU_SUPPORT to true in your `/etc/ecs/ecs.config` or via env vars like the link below. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html#:~:text=ECS_ENABLE_GPU_SUPPORT

I'm still working on it myself. I'll try to update if I find something else.

Best of luck.

**Comment by maishsk** [comment]
@schematical Please have a look at [https://github.com/aws/amazon-ecs-ami](https://github.com/aws/amazon-ecs-ami) for building your custom AMI's 

It has the support for all the different configurations, specifically what [you mentioned above](https://github.com/aws/amazon-ecs-ami/blob/40eab1bb4d0478a072eeb7afe488a7a6affabfa8/scripts/enable-ecs-agent-gpu-support.sh#L50) is already built in.
