### ISSUE TITLE
404 on both .sh files mentioned in EKS Windows Preview instructions

### ISSUE THREAD

**Issue by awsimaya** [aws/containers-roadmap#338]
**Both these files don't exist, essentially blocking user progress in following the instructions mentioned here - https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-windows-preview**
 

1. https://raw.githubusercontent.com/aws/containers-roadmap/preview-programs/eks-windows-preview/webhook-create-signed-cert.sh
2. https://raw.githubusercontent.com/aws/containers-roadmap/preview-programs/eks-windows-preview/webhook-patch-ca-bundle.sh

**Comment by mikestef9** [comment]
EKS Windows is GA now

https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
