### ISSUE TITLE
Adding a stop check script during Deployment/Update phase, or lifecycle hooks

### ISSUE THREAD

**Issue by aleroot** [aws/containers-roadmap#342]
### Summary

Since I have a web application that is also running some background tasks I would need to have a way to check if these tasks are finished before shutting down the task and the related docker container during a deployment/update phase.

### Description

Basically at the moment we we have a group of EC2 instances running docker(NO ECS) in which we upgrade to a new version of our web app, starting up a group of new instances with the new version of the docker image(with the updated web app), then after the new version is up and running we attach new instances to the load balancer and detach the old ones. After this migration phase we manually check if these old instances have completed all the pending tasks(we run bash script that return the number of pending tasks), before shutting them down(we shut down just when the count of the pending background tasks is equal to zero).

Is there a way to automate this process using ECS? 
Basically what we need is a feature that allows us to add a script to perform on the container at the moment of the stop task and that control the shutdown process of the task, for example, if the bash script return 0 then it is ok to stop the task, while if greater than zero run the script again after 30 seconds keeping the task in DRAINING state, not accepting new connections from load balancer, but just waiting for termination...

Another possible approach that we could embrace is adding termination timeout of the task that is longer than the actual 30 seconds, we would need something like 15 minutes...

**Comment by coultn** [comment]
With the launch of [per-container stop timeouts in the task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_timeout), this can be accomplished using the existing ECS functionality.
