### ISSUE TITLE
Add Windows Credentialspec Support

### ISSUE THREAD

**Issue by Cgettys** [aws/containers-roadmap#346]
### Summary

Add Windows Credentialspec support to enable Windows Auth in containers.

### Description

Although Docker for Windows supports Windows Auth through the use of credentialspec files, Amazon ECS does not support this capability.

Retaining the ability to use Windows Authentication within the docker ecosystem eliminates the need to refactor applications to use other forms of authentication. Given how ubiquitous Windows Auth is within many legacy dotnet applications, this feature would greatly streamline the migration process.

**Comment by pavneeta** [comment]
#277 Same request.

**Comment by coultn** [comment]
This shipped:  https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-elastic-container-service-now-supports-active-directory-authentication-using-windows-group-managed-service-accounts/

**Comment by Cgettys** [comment]
Thanks! I have passed this on to my former colleagues, and I'm sure they will be happy to hear that this is now supported by default!

**Comment by pmscad** [comment]
Guys,

Does anyone know how to check this credential spec file on a  Domain Controller? I have 2 DC's and few worker nodes synced with these Domain controllers but the gMSA account when used for a particular service is not working.

Any thoughts anyone can share would be a great help..
