### ISSUE TITLE
New EKS region: Seoul

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#37]
EKS availability in ap-northeast-2

**Comment by nalbam** [comment]
PLZ! EKS availability in Seoul!

**Comment by yoonian** [comment]
We want EKS! Please support here Seoul Korea!

**Comment by kts102121** [comment]
Everybody wants Kubernetes in Seoul.

**Comment by 0kim** [comment]
Folks cannot wait anymore "EKS in Seoul"! 🥇 😄

**Comment by gelius7** [comment]
Welcome~

**Comment by stevenshim** [comment]
Oh god. Plz. Tell me EKS will be GA in Seoul soon.

**Comment by hyunmin-mz** [comment]
Many Korean users want EKS in Seoul Region!! Thanks!!

**Comment by tabern** [comment]
Hi Jungyoul Yu, thanks for your feedback. The team is working hard on making EKS available in the Seoul region soon, however we are not able to provide more information on timing.

https://github.com/aws/containers-roadmap#faqs

**Comment by abby-fuller** [comment]
Shipped Jan 9 2019! 🇰🇷
