### ISSUE TITLE
env-file support

### ISSUE THREAD

**Issue by tbinna** [aws/containers-roadmap#371]
I open this issue to pick up a point that was made in #127 to support the `--env-file` parameter. As pointed out in #127 this would be useful e.g. to add some environment variables that contain sensitive information. This way sensitive environment variables could be stored in a private S3 bucket and be pulled in from there either directly or via a mounted volume.

If the `--env-file` parameter is supported I guess the documentation on [Task Definition Parameters](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment) could also be improved. Under `environment` it is mentioned that it is not recommended to put sensitive information in there, however it does not point to a solution on how to do this otherwise.

Extract from issue #127:

[...] Ideally it would allow an s3 endpoint:

```
"containerDefinitions":[
  {
    "env_file":[
      { "bucket":"my-bucket", "key":"myenvlist" }
    ]
  }
]
```

Elastic Beanstalk lets you do something similar in the Dockerrun.aws.json for docker private repository configuration:

```
"Authentication":{
  "Bucket":"my-bucket",
  "Key":"mydockercfg"
},
```

**Comment by FernandoMiguel** [comment]
For sensitive information, why not use parameter store?

**Comment by brent-riva** [comment]
@petderek @adnxn The use case that isn't addressed is a mass-import of environment variables. I'm currently trying to run a docker image on AWS that takes upwards of 15 variables through the env file for configuration and AWS doesn't let me. I'm surprised it's still not implemented and is something that would lend me to considering GCP or azure

**Comment by dorukgezici** [comment]
@srrengar I think it would be best to support both env-file and cluster-wide env definitions, which could also allow cluster-wide env files.

Idk if we are doing it wrong, but we have around 20 cluster specific and around 10 task definition specific env variables. Some of those task definitions have multiple container definitions that are the same as well. Also we have staging & production clusters. I had to copy around so many things that my eyes went black. There must be a better way.

**Comment by srrengar** [comment]
Hi folks we just released environment files for containers using the EC2 launch type and Fargate support coming soon

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-elastic-container-service-supports-environment-files-ec2-launch-type/

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

**Comment by shafi-khan** [comment]
@srrengar When I try to run a task after adding an env file spec in the task definition, I am getting an error, simply titled  'Reasons : ["ATTRIBUTE"]'.

**Comment by yunhee-l** [comment]
Hi @shafi-khan, 
This error message means the instance is missing required attributes to launch the task. The new envfiles feature requires a new instance attribute "ecs.capability.env-files.s3".

**Comment by shafi-khan** [comment]
@yunhee-l I am currently using v1.36.0. Does updating to the latest AMI all I need to do? Do I need to specify that attribute somewhere?

**Comment by shafi-khan** [comment]
Nevermind, It works after updating to v1.39.0. Thanks @yunhee-l .

**Comment by TusharMehtani** [comment]
> Hi folks we just released environment files for containers using the EC2 launch type and Fargate support coming soon
> 
> https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-elastic-container-service-supports-environment-files-ec2-launch-type/
> 
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

Can you please point me to some documentation that shows how to do it in a yaml config?

I've tried this:

EnvironmentFiles:
    - Value: "--s3 arn--"
       Type: "s3"

(tried the same with camelCase as well)
I keep getting - "Encountered unsupported property EnvironmentFiles"

**Comment by tehmaspc** [comment]
@TusharMehtani - the docs clearly state what format the env file needs to be in. Thus, you need to respect that format.

**Comment by TusharMehtani** [comment]
@tehmaspc - I think my question wasn't clear. I'll try to clarify it. My question isn't about the format of the env file, its about the Cloudformation ECS Task Definition template. The documentation declares the following JSON to be a valid template:

```
"environmentFiles": [
                {
                    "value": "arn:aws:s3:::s3_bucket_name/envfile_object_name.env",
                    "type": "s3"
                }
            ],
```

Since I usually write my task definitions in YAML, I tried to write the JSON as the following YAML Equivalent:
```
EnvironmentFiles:
    - Value: "arn:aws:s3:::s3_bucket_name/envfile_object_name.env"
      Type: "s3"
```
This gives the error - **Encountered unsupported property "EnvironmentFiles".** 
I'm using Container Agent v1.41.0 which is fine as per the docs (req >=v1.39.0). The env file is UTF-8 encoded and follows the proper format as per documentation. 
**I'm certain this isn't an issue with the env file as the same thing works when I'm creating the task definition using the ECS UI. So, pretty sure the issue is with the template file.** 
Is the YAML format not supported here for some reason? This would be strange!

Here is a simplified version of my complete task definition YAML file for reference:

```
Description: >
  This is an example of a long running ECS service that serves a JSON API.

Parameters:
  VPC:
    Description: The VPC that the ECS cluster is deployed to
    Type: AWS::EC2::VPC::Id

  Cluster:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 1

  MyServiceImage:
    Description: URI of the Docker Image of Service you want to deploy
    Type: String
    Default: service/service-v1
    
Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: service-defn-dev
      ContainerDefinitions:
        - Name: service-backend
          Essential: true
          Image: !Ref MyServiceImage
          MemoryReservation: 128
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
          MountPoints:
            - ContainerPath: "/container/path/"
              SourceVolume: "mount-point"
          EnvironmentFiles:
            - Value: "arn:aws:s3:::s3_bucket_name/envfile_object_name.env"
              Type: "s3"
          Environment:
            - Name: ENV_VAR_1
              Value: ENV_VAR_VAL_1
            - Name: ENV_VAR_2
              Value: ENV_VAR_VAL_2
          DependsOn:
            - ContainerName: pre-req-service
              Condition: START

      Cpu: "1024"
      Memory: "128"
      Volumes:
        - Host:
            SourcePath: "/host/path/to/mount"
          Name: "mount-point"
```

**Comment by yunhee-l** [comment]
Hi TusharMehtani, 
Cloudformation support for env files is not yet available. We are working on it however, and will be made available soon.

**Comment by TusharMehtani** [comment]
> Hi TusharMehtani,
> Cloudformation support for env files is not yet available. We are working on it however, and will be made available soon.

Thanks for the update @yunhee-l. Looking forward to this, will try to use some alternative for now.

**Comment by srrengar** [comment]
Hi folks, CloudFormation for env files is now available 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

**Comment by raehalme** [comment]
The docs say environment files are not supported by Fargate even though
they are S3 resources.

Can we expect Fargate support in the near future?
-- 
*Thomas Raehalme*
*CEO, Founder*
Mobile +358 40 545 0605

*Aitio Finland Oy*
Lutakonaukio 7
40100 JYVÄSKYLÄ, Finland
Tel. +358 10 322 0040
www.aitiofinland.com
www.hillava.com

**Comment by srrengar** [comment]
Yes Fargate support is in development

**Comment by bordeux** [comment]
Keeping secrets in S3 is bad idea. Better is just use secret manager for it.

**Comment by stadskle** [comment]
> Yes Fargate support is in development

Do you have a separat github issue for that we can follow @srrengar ?

**Comment by srrengar** [comment]
Hi everyone, thank you for your patience. This feature is now available in Fargate as of today.

https://aws.amazon.com/about-aws/whats-new/2020/11/aws-fargate-for-amazon-ecs-launches-features-focused-on-configuration-and-metrics/
