### ISSUE TITLE
[service] [request]: URLs for "Step 4: Deploy the VPC admission webhook" need to be updated.

### ISSUE THREAD

**Issue by TommyHamilton** [aws/containers-roadmap#373]
It looks like the preview-programs folder was moved under /master and the documentation just needs to be updated to reflect that.

Documentation URL: https://raw.githubusercontent.com/aws/containers-roadmap/preview-programs/eks-windows-preview/webhook-create-signed-cert.sh

Working URL: https://raw.githubusercontent.com/aws/containers-roadmap/master/preview-programs/eks-windows-preview/webhook-create-signed-cert.sh

**Comment by tabern** [comment]
Thanks for opening this PR. Closing as PR was merged.
