### ISSUE TITLE
New EKS Region: GovCloud East

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#375]
Support for Amazon EKS in gov-us-east-1

Per request https://github.com/aws/containers-roadmap/issues/253 by @joemccall86

**Comment by cmoone** [comment]
Yes please. This would be very helpful.

**Comment by mikestef9** [comment]
EKS is now generally available in AWS GovCloud (US) Regions!

- [What's New](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-eks-now-available-in-the-aws-govcloud-us-regions/)
- [Blog](https://aws.amazon.com/blogs/publicsector/announcing-amazon-elastic-kubernetes-service-eks-aws-govcloud-us/)
