### ISSUE TITLE
[EKS] Kubernetes metrics to CloudWatch

### ISSUE THREAD

**Issue by bizzelicious** [aws/containers-roadmap#38]
Some metrics from eg: Kubernetes, Kubelet, kube-state-metrics to Cloudwatch. As of today, many are using Prometheus to collect the metrics. But if you already utilize Cloudwatch you now have two monitoring systems.

**Comment by mrichman** [comment]
Would it be fair to ask for metrics from the control plane as well?

**Comment by joan-serra** [comment]
fyi: In the meantime I've been using Prometheus along with https://github.com/cloudposse/prometheus-to-cloudwatch - however, it doesn't have any sort of whitelisting/filtering for metrics so it will essentially push **everything**  to Cloudwatch - and it can only poll one metrics endpoint.

**Comment by joan-serra** [comment]
Based on that prometheus-to-cloudwatch piece I just put this thing together that listens on an endpoint for Prometheus remote path writes: https://github.com/joan-serra/prometheus-cloudwatch-adapter - haven't been able to test it much yet, but I got some metrics in. Excuse my Go noobness and the whole spaghetti. (+Info about Prometheus remote path writes: https://www.robustperception.io/using-the-remote-write-path)

**Comment by ysaakpr** [comment]
Any update on this? Though EKS is there, no proper monitoring alerting possible still on aws

**Comment by khacminh** [comment]
@ysaakpr,

On May 20, 2019, AWS announced about: CloudWatch Container Insights for Amazon EKS and Kubernetes (Preview). But the metrics are not really useful. I created a Request at #548

**Comment by mikestef9** [comment]
Closing as this now possible

see https://aws.amazon.com/blogs/containers/amazon-cloudwatch-prometheus-metrics-ga/

#548 will leave open track additional enhancements
