### ISSUE TITLE
[EKS] [request]: Low Cost Control Plane for Development

### ISSUE THREAD

**Issue by forsberg** [aws/containers-roadmap#381]
**Tell us about your request**
For development and test clusters, having a multi-AZ control plane is not necessary. I would enjoy being able to configure per cluster if the control plane should be highly available or not, with a lower cost for low-availability clusters. 

Related to #133, as stopping EKS control plane for test clusters would also help in keeping costs down.

**Which service(s) is this request for?**
EKS

**Comment by tdmalone** [comment]
I believe this duplicates #45

**Comment by mhausenblas** [comment]
Yes, I'd agree, it's a dupe. @forsberg are you OK with us closing this one in favor of #45?

**Comment by mhausenblas** [comment]
Closing it because it's a duplicate of #45 and I did not hear back from @forsberg in over two days objecting to close it.
