### ISSUE TITLE
[Fargate] [request]: Support for FluentD log driver

### ISSUE THREAD

**Issue by chungath** [aws/containers-roadmap#383]
**Tell us about your request**
Currently Fargate task definitions only support the awslogs and splunk log drivers for the log configuration. We need the support of FluentD log driver in Fargate. This is blocking us from utilizing Fargate.

**Which service(s) is this request for?**
Fargate

**Comment by inductor** [comment]
See https://github.com/aws/containers-roadmap/issues/10

**Comment by akshayram-wolverine** [comment]
Now in preview. See here: https://github.com/aws/containers-roadmap/tree/master/preview-programs/firelens
