### ISSUE TITLE
[EKS] [request]: Add ability to use Reserved Instances (RI) for the Control Plane (Master Node)

### ISSUE THREAD

**Issue by imriss** [aws/containers-roadmap#388]
**Tell us about your request**
Please add the ability to use Reserved Instances for the Master Nodes (Control Plane) of the EKS clusters.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For the Worker Nodes, Spot, On-Demand, and Reserved instances can be used via ASGs. However, it would be great to have a capability to also use RIs for the Master Nodes in order to reduce the overall cost.

**Are you currently working around this issue?**
No

**Additional context**

**Attachments**

**Comment by marcincuber** [comment]
@imriss EKS is a managed control plane for you which you pay $0.20 per hour. Why would you want an ability to use reserved instances from your account when EKS doesn't even live in your AWS account?

**Comment by imriss** [comment]
@marcincuber I am looking for an equivalent of the RI offering in the EKS. I understand that it is managed, and it is not directly linked with my AWS account. However, it would help if there is some kind of Reserved Control Plane offering by EKS that enables reducing the cost in a similar way of regular Reserved Instances. Thanks

**Comment by dbayendor-cb** [comment]
You may want to try spinning clusters with `kops` or a similar tool that will let you specify instance types for the control plane.  Not as ideal as the managed part of EKS.

**Comment by whereisaaron** [comment]
An equivalent example is RDS Reserved Instances, another AWS managed service like EKS, where AWS gives you committed resources and better prices for a long term commitment.
https://aws.amazon.com/rds/reserved-instances/

**Comment by marcincuber** [comment]
@whereisaaron RDS reserved instances work the same as ec2 reserved instances so the instances are running in your account. At the same time reserved instances are associated with your account. 
EKS is a controlplane is shared with your account and so you don't have any control over it and you don't see its instances at all. I can hardly see any correlation between rds and eks in terms of setup. 

With regards to the issue raised, rather than having EKS reserved instances (instances that you don't see at all) it would be valid to have an EKS controlplane span across a single AZ which would be used for development and could be costing e.g. $0.10 p/h.

**Comment by gruebel** [comment]
@marcincuber there are also other examples like Elasticsearch reserved instances. You don't see the nodes and they don't reside in your VPC, just the endpoint is connected to your subnet.
There is also DynamoDB reserved capacity, where you get zero access and visibility to the infrastructure.
I can't really understand, what is your problem with the wish for a price reduction, when someone is willing to run one or several clusters for 1 to 3 years and hoping to get some benefit for that commitment.
Your idea is also valid with a single master setup, but has a different use case.

**Comment by gaurish** [comment]
is there an update on this?

**Comment by tabern** [comment]
Closing this - EKS offers a fully managed Kubernetes control plane. As such, we will continue to innovate and find ways to delivery EKS at lower cost and higher availability (currently 99.95%). However, we do not plan to offer this capability as requested.
