### ISSUE TITLE
Fargate Log Driver Support - Sumo Logic

### ISSUE THREAD

**Issue by nikovirtala** [aws/containers-roadmap#39]
The list of to be supported log drivers on issues #9 and #10 is relatively short, and we as Sumo Logic users want to see that [Sumo Logic logging driver](https://github.com/SumoLogic/sumologic-docker-logging-driver) is also supported on Fargate.

The current solution to ship logs first into CloudWatch, and use Lambda to stream them to Sumo Logic works, but is unnecessarily complicated compared to a solution that is achieved with native Docker log driver.

**Comment by baversjo** [comment]
It’s also very expensive to have it shipped to cloudwatch. 10 GB / day => $1k/mo cloudwatch bill...

**Comment by frankwangw** [comment]
any new update regarding this request ?

**Comment by dayer4b** [comment]
I just want to add my voice to the chorus.  I understand that Sumo Logic can be utilized with Fargate with the CloudWatch Logs intermediary (as documented here: https://help.sumologic.com/03Send-Data/Collect-from-Other-Data-Sources/Collect_Logs_from_AWS_Fargate), but that's 2 extra pieces of infrastructure where they seemingly don't need to be.  ECS supports this already, but Fargate doesn't!  

I hope it is an easy port and look forward to this being shipped ASAP!

**Comment by mwarkentin** [comment]
Looks like the recent fluentbit announcement is related to making log shipping easier to a bunch of 3rd party endpoints:

* https://github.com/aws/containers-roadmap/issues/10
* https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/

**Comment by edsiper** [comment]
@mwarkentin 

fyi: we are in discussion to make a better integration between Fluent Bit and Sumologic, please refer to the following issue: fluent/fluent-bit#1213

**Comment by nikovirtala** [comment]
The solution for sending logs from Fargate task to Sumo Logic is described on Sumo Logic documentation: https://help.sumologic.com/07Sumo-Logic-Apps/01Amazon_and_AWS/AWS_Fargate_log_collection#A._Create_a_Fargate_launch_type

I tested it briefly this morning and it seems to fill all of our requirements, and thus this feature request can be closed. 💯
