### ISSUE TITLE
[ECS, Fargate] Scheduled Tasks in London

### ISSUE THREAD

**Issue by jmkgreen** [aws/containers-roadmap#394]
**Tell us about your request**
Enable scheduled tasks in London region.

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are required to operate our compute services in England, and have a number of processes that only need to be run periodically.

**Are you currently working around this issue?**
Running them permanently with an internal scheduler to kick off the business code. We could use EC2 instances, but that's more management overhead of patching and frankly a deviation in our CloudFormation templates.

**Additional context**
Am aware that CloudFormation lacks scheduling directives, but this is now on the roadmap separately (#392).

I have zero clue how some regions lack this feature, seems very odd from my customer perspective.

**Comment by clareliguori** [comment]
Hi @jmkgreen, to clarify, you are not able to create a scheduled task in eu-west-2 via API or console?  I'm not able to reproduce that (I was able to create a rule and see it trigger Fargate tasks).  What is the error you receive?

**Comment by jmkgreen** [comment]
@clareliguori the web console, under "Target Name > Launch Type" says EC2. I might expect the value to be a select drop-down offering EC2 or Fargate but it isn't, it just says "EC2".

Also, the [documentation](https://docs.aws.amazon.com/AmazonECS/latest/userguide/scheduled_tasks.html) clearly states that EU London is not yet supported.

**Comment by clareliguori** [comment]
Ah ok, I created mine directly through the CloudWatch Events console.  One I created the rule, it shows up in the ECS console in the Scheduled Tasks tab.  Looks like the ECS console creation wizard and docs have an outdated list of available regions, we'll get that updated.

**Comment by collin-aws** [comment]
Fargate Scheduled Tasks have now been enabled in London. Thanks for bringing this to our attention!
