### ISSUE TITLE
[ECR] [TAGS]: Increase maximum number of tags per image

### ISSUE THREAD

**Issue by groodt** [aws/containers-roadmap#396]
**Tell us about your request**
It would be great if the current maximum limit of 100 tags per image could be increased.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We work in a monorepo that creates multiple images. We use the git-sha as the "version" tag. The images are built with Bazel, so only rebuilds binary artifacts if there are changes.

In our current setup, all artifacts are released with every green CI build. However, if an image has not changed its digest, the tag will land on previous image digest. We can quickly hit the limit of 100 tags per image in this way.

**Are you currently working around this issue?**
Bump the image digest when we hit 100 tags.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by omieomye** [comment]
We've increased maximum tags per image from 100 to 1000, will be updating documentation soon @groodt give this a try?

**Comment by groodt** [comment]
> We've increased maximum tags per image from 100 to 1000, will be updating documentation soon @groodt give this a try?

Thanks very much @omieomye  This is great news! I'll take a look and see if we have any issues.

**Comment by groodt** [comment]
This has been working great for us. We've not run into any tag limits recently and we have examples where there are over 100 tags on a single image.

Thank again!

**Comment by groodt** [comment]
I see the documentation has been updated here: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service-quotas.html

I believe this issue can be closed or marked as complete.

**Comment by bradgr** [comment]
Thank you for following up. Closing this now.
