### ISSUE TITLE
ECR Console v2

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#4]
Included in this project are new, simplified repository, image, and lifecycle workflows. At the time of completion, new ECR console will also have a tagging feature followed by image scanning.

**Comment by mwarkentin** [comment]
Does "just shipped" mean that issues should be closed or is there further work being done on it?

**Comment by jtoberon** [comment]
@mwarkentin The issue should have been closed. Sorry for the confusion!
