### ISSUE TITLE
[Fargate] [request]: Fargate in São Paulo

### ISSUE THREAD

**Issue by mineiro** [aws/containers-roadmap#402]
**Tell us about your request**
Support Fargate in sa-east-1

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently Fargate is not available in São Paulo, which makes me having to manage ECS clusters.

**Are you currently working around this issue?**
The only way to workaround this issue is to use ECS and manage the clusters.

**Additional context**
N/A

**Attachments**
N/A

**Comment by truonghongphuoc** [comment]
Our project also need Fargate in sa-east-1 too, hope it will be available soon.

**Comment by pgarbe** [comment]
Any updates here?

**Comment by mlanner-aws** [comment]
Fargate launched in São Paulo on November 13, 2019.

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-fargate-now-available-in-south-america-sao-paulo-region/
