### ISSUE TITLE
Certificate automatic renewal

### ISSUE THREAD

**Issue by oceaneLonneux** [aws/containers-roadmap#403]
I am not sure this is exactly an issue, but we have an EKS cluster which certificate renews every 2 weeks. This is a short period, and we are working on having a script to update automatically our CD tool to use the new certificate.

I am wondering if this is by design, if there is anyways to change it, ...?

Ps: If this is totally out of the scope of these issues, you are more than welcome to close this, but I haven't found much documentation about this renewal.

**Comment by whereisaaron** [comment]
Hi @oceaneLonneux,
`aws eks --region region update-kubeconfig --name cluster_name`
or 
`eksctl utils write-kubeconfig --name cluster_name`
should ensure you have the current API certificate

https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html

**Comment by Srikantnh** [comment]
Does eks will manage auto renewal of ca's or it's manual process? Plz reply on urgent basis

**Comment by oceaneLonneux** [comment]
> Does eks will manage auto renewal of ca's or it's manual process? Plz reply on urgent basis

Yes it does. My kubectl command line is fine as well.

I am more referring to the CD tool who has to be updated with the new certificate every 2 weeks, which seemed like a very short time to me.

**Comment by Srikantnh** [comment]
Can you plz provide any link for reference,so that I can get it more info about eks ca's?else plz provide ans to my questions so that it would be more helpful,
What is the eks ca's life cycle?
Is that absolutely true eks cluster will auto manage ca's ? (So no need create auto signed ca's in kubernates)
How can we check CA expiration?(any command/dashboard)
Plz reply on priority

**Comment by FernandoMiguel** [comment]
@Srikantnh please take in consideration that this is not a support forum.
This is a place for discussion of the future of aws container future.

If you are not comfortable with any tool, you should better get familiar with it before using it in a production environment.

That said, you can't expect priority support here.
For anything EKS related, contact aws support from your AWS account.

**Comment by oceaneLonneux** [comment]
> @Srikantnh please take in consideration that this is not a support forum.
> This is a place for discussion of the future of aws container future.
> 
> If you are not comfortable with any tool, you should better get familiar with it before using it in a production environment.
> 
> That said, you can't expect priority support here.
> For anything EKS related, contact aws support from your AWS account.

Thank you for your answer, I will close this issue and goes towards AWS support.
