### ISSUE TITLE
[EKS] [request]: SNS topic for Amazon EKS-optimized AMIs

### ISSUE THREAD

**Issue by sonnyvan** [aws/containers-roadmap#407]
**Tell us about your request**
SNS topic for new AMIs

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to be notified when a new AMI is released so we can cycle the worker nodes.

**Are you currently working around this issue?**
Manually.

**Additional context**
Can we get a SNS topic for EKS AMIs similar to the upstream AL2?  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#linux-ami-notifications

**Comment by thatderek** [comment]
Hey @sonnyvan , while this proposal is being reviewed, I think you can do a workaround with this [thing that just got launched](https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-provides-eks-optimized-ami-metadata-via-ssm-parameters/). 

Specifically, I think you can use [these instructions](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-cwe.html) to create an SNS topic subscribed to updates on the ssm parameter at `/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended` which could then maybe trigger a lambda that updates your launch-configs, templates, etc.

**Comment by sbkg0002** [comment]
We tried that @thatderek and for our own parameters it fires, but somehow not for the Amazon provided ones.

**Comment by sonnyvan** [comment]
Looks like the docs provide SNS topics to subscribe to. Closing this issue.

**Comment by smiller171** [comment]
Any chance someone can point me in the right direction? I'm not sure if it used to exist, but I can't find any reference to an SNS topic in the docs. It also seems like this image isn't being built by Image Builder

**Comment by benjimin** [comment]
The EKS AMIs are _not_ explicitly mentioned in the docs here:
https://docs.aws.amazon.com/managedservices/latest/userguide/ams-ami-notifications.html

I also couldn't find any mention of SNS here:
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

@sonnyvan are you sure an SNS for EKS-optimised AMIs exists, and could you post a link to the relevant docs please?

**Comment by CyDickey-msr** [comment]
I setup an SNS topic to track when there are updates to `/aws/service/eks/optimized-ami/<insert_version>/amazon-linux-2/recommended/release_version`. It doesn't seem to trigger for AWS owned parameters, but it triggers fine for SSM parameters we own. Is this expected?
