### ISSUE TITLE
[ECR] CloudWatch metrics for API usage

### ISSUE THREAD

**Issue by jtoberon** [aws/containers-roadmap#408]
ECR should publish CloudWatch metrics that show the call count per API.

We're interested in feedback about these are the right metrics and how valuable these would be to customers.

**Comment by jespersoderlund** [comment]
Furthermore I think metrics to identify how close you are to having to request service limit increases would be very useful to make it easier to be proactive.

**Comment by sstkwayne** [comment]
Additionally Id like to see metrics on the last pull for an image. It would make it easier to see what images are truly being used

**Comment by jtoberon** [comment]
> Furthermore I think metrics to identify how close you are to having to request service limit increases would be very useful to make it easier to be proactive.
@jespersoderlund Thanks for the feedback.

**Comment by jtoberon** [comment]
> Additionally Id like to see metrics on the last pull for an image. It would make it easier to see what images are truly being used

@sstkwayne I see why that data is useful. It'd be great to know how you'd plan to consume it. Here are some ideas we've heard in the past:

1. View the data via ECR's list/describe APIs, such as  https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-images.html
1. Use the data to clean up old images via a lifecycle policy rule.
1. Regardless of the last pull time, link from the image in ECR to where the corresponding container is running in ECS or EKS.

**Comment by sstkwayne** [comment]
> > Additionally Id like to see metrics on the last pull for an image. It would make it easier to see what images are truly being used
> 
> @sstkwayne I see why that data is useful. It'd be great to know how you'd plan to consume it. Here are some ideas we've heard in the past:
> 
> 1. View the data via ECR's list/describe APIs, such as  https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-images.html
> 2. Use the data to clean up old images via a lifecycle policy rule.
> 3. Regardless of the last pull time, link from the image in ECR to where the corresponding container is running in ECS or EKS.

@jtoberon I would like to use it to clean up old images and see where it is being used. We have some applications which are pretty stable and aren’t getting many updates so an age based lifecycle rule wouldn’t be good for us as we might inadvertently delete the image.

**Comment by omieomye** [comment]
You can now monitor ECR API usage using CW metrics, and see how it relates to your per-account Service Quotas (rate limits).  This is live in preview, we'll announce shortly.  Read more: https://docs.aws.amazon.com/AmazonECR/latest/userguide/monitoring-usage.html

**Comment by omieomye** [comment]
Shipped. https://aws.amazon.com/about-aws/whats-new/2020/03/now-proactively-manage-your-ecr-api-use-with-cloudwatch-metrics-and-service-quotas/
