### ISSUE TITLE
[ECR] Increase some of ECR's default service limits

### ISSUE THREAD

**Issue by jtoberon** [aws/containers-roadmap#414]
Increase the maximum number of repositories per region from 1,000 to 10,000.
Increase the maximum number of images per repository from 1,000 to 10,000.

Update the public Amazon ECR service limits documentation at https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html.

**Comment by jtoberon** [comment]
This was shipped on 7/12.

**Comment by rpnguyen** [comment]
https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecr-now-supports-increased-repository-and-image-limits/
