### ISSUE TITLE
[eks] [request]: enable RunAsGroup feature gate

### ISSUE THREAD

**Issue by adamjohnson01** [aws/containers-roadmap#415]
**Tell us about your request**

In order to set gid using security context we need to enable RunAsGroup feature gate, this is enabled by default in 1.14.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When you set runAsGroup in securityContext it is not respected if the gid does not already exist so will always be the gid of the image user which in a many cases is root.

**Are you currently working around this issue?**
The only workaround is to create the group in the image which is not practical for public images.

**Comment by whereisaaron** [comment]
This feature is beta as of 1.14, so it should be enabled in EKS 1.14. Is it disabled @adamjohnson01?

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
**RunAsGroup | true | Beta | 1.14**

**Comment by adamjohnson01** [comment]
Yes, should have added a comment when I closed this. It is enabled in 1,14.
