### ISSUE TITLE
EKS Worker Nodes Not Ready Status

### ISSUE THREAD

**Issue by Jesudos** [aws/containers-roadmap#416]
Hi Guys , 
I have followed every steps from https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-windows-preview except instead of 3 Windows worker node , used only one windows worker node. Hence my EKS Windows cluster will be a mixed mode cluster (1 Linux node and 1 Windows node).
After applying ConfigMap , when i use "kubectl get nodes --watch"  to get the nodes status , my linux node is in "Not Ready" state due to the following error.

**runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized**

Can anyone pls help me on this? Thanks in Advance!

Regards , 
Jesu

**Comment by amolsh** [comment]
I am also facing exact same issue, I am using given setup 3+1 , did not modify anything.

**Comment by amolsh** [comment]
It was my mistake, i chose wrong linux ami id (which was for kube 1.13). After changing the correct ami id, it fixed.

**Comment by Jesudos** [comment]
That's it ! Choosing correct Linux ami done the trick !
