### ISSUE TITLE
[EKS] : GUI for creating EKS cluster along with worker nodes

### ISSUE THREAD

**Issue by prabhatsharma** [aws/containers-roadmap#421]
**Tell us about your request**
A GUI in AWS console that allows to create an EKS cluster (control plane and worker nodes) in a single request.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
While eksctl makes life so much easier when it comes to managing the EKS cluster, a GUI would be a lot more intuitive for starters.

**Are you currently working around this issue?**
Currently using eksctl

**Comment by tabern** [comment]
This is something we are working on. For clarification - should this include the ability to create Subnets/IAM roles from the same workflow in the console?

**Comment by tabern** [comment]
I'm going to merge this request into #44 as they are very similar. A quick note, this functionality will be delivered in stages, so we will open requisite linked tickets to track that as we go.
