### ISSUE TITLE
ecs UI makes it hard to see image name

### ISSUE THREAD

**Issue by ORESoftware** [aws/containers-roadmap#432]
Not sure where to file this ticket, but the ECS UI makes it really hard to see the image name:

-----

<kbd>
<img width="1450" alt="Screen Shot 2019-08-06 at 4 57 02 PM" src="https://user-images.githubusercontent.com/11139560/62584907-5d6dd000-b86b-11e9-9157-e91b66d550b0.png">
</kbd>

-----

I have to drag the column way over to read the whole image name:

-----

<kbd>
<img width="1422" alt="Screen Shot 2019-08-06 at 4 57 17 PM" src="https://user-images.githubusercontent.com/11139560/62584931-74142700-b86b-11e9-8a86-055d91152608.png">
</kbd>

----

It would be nice to just have the image name appear in "Details"

**Comment by coultn** [comment]
Thanks for the feedback, we are looking into it.

**Comment by FernandoMiguel** [comment]
@ORESoftware you can also do mouse over

**Comment by steven-cuthill-otm** [comment]
the ECS console is a UI car crash, defiantly the worst one. would be good to not just see this get fixed but a full refresh.
