### ISSUE TITLE
[EKS] [request]: Kernel 5.1+ in EKS Amazon Linux AMI to resolve conntrack race conditions

### ISSUE THREAD

**Issue by jaygorrell** [aws/containers-roadmap#440]
**Tell us about your request**
I would like the EKS AMIs to be on at least kernel version 5.1 to address the well-documented[0][1] `conntrack` race conditions.

**Which service(s) is this request for?**
EKS (possibly ECS as well)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
There are some kernel-level race conditions with `conntrack` that frequently manifest as timed out DNS lookups in Kubernetes clusters. Two of the three race conditions have been patched in the kernel and are released in v5.1.

The third race condition is mitigated by Local DNS cache requested in another issue[2].

**Are you currently working around this issue?**
The referenced issue should also help mitigate this until the real fixes in the kernel are available on EKS, but that solution isn't fully supported yet either.

**Attachments**
[0] https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts
[1] https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02
[2] https://github.com/aws/containers-roadmap/issues/303

**Comment by Pluies** [comment]
@jaygorrell unless I'm mistaken, that issue should be in the https://github.com/awslabs/amazon-eks-ami/ project instead?

**Comment by jaygorrell** [comment]
@Pluies Thank you, I wasn't aware of that project. Opened https://github.com/awslabs/amazon-eks-ami/issues/357 if people want to throw their support over there instead.
