### ISSUE TITLE
[EKS] New EKS Region: Bahrain

### ISSUE THREAD

**Issue by mike-stewart** [aws/containers-roadmap#441]
**Tell us about your request**
Support for EKS in Bahrain (me-south-1).

**Which service(s) is this request for?**
EKS

**Comment by mikestef9** [comment]
We're excited to announce that EKS is now generally available in the AWS Bahrain region (me-south-1)!

You can get the worker AMI IDs for this region in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html).

Note: GPU instance types are not available in Bahrain region, so Amazon EKS does not yet publish the Amazon EKS-optimized AMI with GPU support in this region.

**Comment by PatMyron** [comment]
@mikestef9 Will this be updated as well?
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

**Comment by mikestef9** [comment]
@PatMyron that page is now updated

**Comment by Anonymous263-Anonymous** [comment]
when will the Africa one be ready
