### ISSUE TITLE
[Fargate] [request]: Fargate in Bahrain

### ISSUE THREAD

**Issue by truonghongphuoc** [aws/containers-roadmap#442]
Tell us about your request
Support Fargate in me-south-1

Which service(s) is this request for?
Fargate

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
Currently Fargate is not available in Bahrain region, which makes me having to manage ECS EC2 clusters.

Are you currently working around this issue?
The only way to workaround this issue is to use ECS EC2 and manage the clusters.

Additional context
N/A

Attachments
N/A

**Comment by akshayram-wolverine** [comment]
Shipped! https://aws.amazon.com/about-aws/whats-new/2019/09/aws-fargate-now-available-in-eu-stockholm-paris-middle-east-bahrain-regions/
