### ISSUE TITLE
[ECS] [request]: Upgrade docker version in ECS-optimized AMIs

### ISSUE THREAD

**Issue by jeffj254** [aws/containers-roadmap#443]
**Tell us about your request**
Please upgrade the version of Docker included in the ECS optimized AMIs to 18.09 or newer

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are using the new secrets functionality included in the latest 1.39 version of the Docker API to pass secrets to our builds in a safe manner.  This works great on our local machines but we aren't able to build our dockerfiles using secrets on our ECS clusters due to the ECS optimized AMIs shipping with the older version 18.06.1-ce of Docker that does not support the buildkit extensions.

**Are you currently working around this issue?**
Right now we are running our builds on a non-ephemeral host where we can install the latest version of Docker

**Additional context**
The buildkit extensions are documented here: https://docs.docker.com/develop/develop-images/build_enhancements/

**Comment by jia2** [comment]
Please do the same for EKS AMI.

**Comment by jae-63** [comment]
We too need this for the EKS AMI, because Docker 18.09 supports largish (10GB) layers which Docker 18.06 does not.    We wound up "rolling our own" AMI this this functionality from the released EKS 1.14 image, but it wasn't pretty.

**Comment by ellenthsu** [comment]
@jae-63 can you please create a new issue for the EKS docker upgrade? We'll be using this request to track the progress for upgrading to Docker 18.09 in the ECS Optimized AMIs. Thanks!

**Comment by ellenthsu** [comment]
Docker 18.09.9 is available in ECS Agent 1.35.0 and higher. 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html

**Comment by CGarces** [comment]
Consider move the task from "We're Working On It" to other place, this was solved on 2020.

**Comment by jeroenhabets** [comment]
@AbhishekNautiyal could you move this Done request to "Shipped" for us, pls?

**Comment by jeroenhabets** [comment]
@ellenthsu could you move this Done request to "Shipped" for us, pls?
