### ISSUE TITLE
A Little Clarification on "Microsoft doesn't support hostnetworking mode in Windows yet"?

### ISSUE THREAD

**Issue by jg-infra** [aws/containers-roadmap#444]
Hello, I've been playing around with this code in the repo and I have some questions. I've been trying to add a windows node an existing eks cluster with 2 linux nodes. I omitted the load balancer service in the yaml template and opted instead for a nodeport so that I can use it behind my existing nlbs. My issue is that I couldn't get the iis container working until I added a linux node to my target group. After rereading the github page, I noticed the point "Microsoft doesn't support hostnetworking mode in Windows yet." Just for clarification, does this explain why I had to do it this way? Could you please elaborate a little more on hostnetworking, etc for those of us who aren't knowledgeable?

Thanks

**Comment by whereisaaron** [comment]
A NodePort doesn't require the Pod to run with host networking so not sure what the Windows issue is there. When you added the Linux node, the `kubelet` on that node would have arranged to proxy the NodePort traffic to you Pod across the cluster-internal network/addresses, which is probably why it started working. Maybe the `kubelet` on the Windows nodes can't do that.

https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model
> Kubernetes imposes the following fundamental requirements on any networking implementation (barring any intentional network segmentation policies):
> - pods on a node can communicate with all pods on all nodes without NAT
> - agents on a node (e.g. system daemons, kubelet) can communicate with all pods on that node
>
> Note: For those platforms that support Pods running in the host network (e.g. Linux):
> - pods in the host network of a node can communicate with all pods on all nodes without NAT

**Comment by rawahars** [comment]
Host networking is a mode of container networking wherein the container shares the network namespace of the host instance. This is a privileged mode wherein any changes made by container would be applicable on host as well. This is usually used for administrative tasks on the instance.
More information about host networking can be found here-https://docs.docker.com/network/host/

Unfortunately, Windows does not support docker host networking. However, Microsoft had released `Host Process Containers` which essentially are the same thing. They can be used to run a containerised application such that the namespace is shared with the host. More information can be found here- https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/
