### ISSUE TITLE
[Fargate] [request]: Fargate sysctls support

### ISSUE THREAD

**Issue by sveniu** [aws/containers-roadmap#460]
**Tell us about your request**
Add `systemControls` support for Fargate.

**Which service(s) is this request for?**
ECS, Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I think sysctls can be useful in general. They cannot be applied within the OS itself due to lack of permissions, and Fargate doesn't allow privileged mode nor adding Linux capabilities.

I'd like to tune the `net.ipv4.tcp_keepalive_time` sysctl for my Fargate containers. The reason is a bit unusual, but here goes:
* I want to set the TCP keepalive time to 290 seconds. The Linux default is 7200 seconds.
* I'm behind a Cisco Meraki appliance that has a fixed 300-second NAT timeout for TCP connections (confirmed with Cisco support).
* The Fargate task runs HAProxy, which can only disable/enable TCP keepalives; it cannot tune the parameters. (Making a feature request shortly.)
* I'd like to have the server do the frequent TCP keepalives, instead of pushing that requirement onto every client.

**Are you currently working around this issue?**
Two ways: Filing a request with HAProxy; and adding client-initiated frequent TCP keepalives where possible, which sadly doesn't cover all my cases.

**Comment by chaithanya77** [comment]
Can we disable TCP keepalives in fargate tasks?

**Comment by jackm-ts** [comment]
I would also love to see Fargate support sysctl settings, albeit for a different use case.

**Comment by YukSeungChan** [comment]
+1 ❤️

**Comment by Cody0713** [comment]
Yes this is a huge blocker for me as I need to set net.somaxcons to a higher number and a few other sysctl settings, ecs allows you to do this but not fargate...

**Comment by marnie-eure** [comment]
++ 👍

**Comment by andreburto** [comment]
Another vote for me. Maxing out the connections at 128 means I likely have to abandon Fargate and go back to ECS, which does let us adjust sysctl settings.

**Comment by skolmer** [comment]
We would like to set `kernel.perf_event_paranoid` to be able to collect CPU traces using [`perf`](https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html#perf-events-perf-unprivileged-users)

**Comment by fischaz** [comment]
Our use case related to https://github.com/SonarSource/docker-sonarqube/issues/282 and the ability to set `vm.max_map_count` (the issue provide a workaround).

**Comment by sufiyanghori** [comment]
+1 We would really like to see this enabled in Fargate too!

**Comment by bryantcj52** [comment]
We also need this for fargate tasks behind an AWS NAT gateway for requests that take longer than 5 minutes: https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html#nat-gateway-troubleshooting-timeout

**Comment by DragonStuff** [comment]
+1 We would love to see this as we use Fargate at TableCheck Japan. Our specific requirement is to be able to set `fs.inotify.max_user_watches` to a value higher than `8192`.

**Comment by sd65** [comment]
Would be very useful to set `net.ipv4.ip_forward=1` and create a transparent-proxy with Fargate!

**Comment by jtoberon** [comment]
Our asks are:
net.ipv4.ip_local_port_range
net.ipv4.ip_local_reserved_ports
/proc/sys/fs/nr_open
/proc/sys/fs/file-max

**Comment by CCludts** [comment]
Our usecases are:

/proc/sys/vm/overcommit_memory
vm.max_map_count
net.core.rmem_max
net.core.wmem_max
fs.file-max


Lack of support for the features above is a hard blocker for our team to use Fargate.

**Comment by EvgenyKarataev** [comment]
We need to set `net.core.somaxconn` value to higher than 128. Still no possible, right?

**Comment by Canuteson** [comment]
Configuring Keepalives is an RDS best practice for fast failover:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.BestPractices.html

**Comment by watarukura** [comment]
We use [Swoole](https://github.com/swoole/swoole-src), and Swoole recommends adjust sysctls change following:

- net.ipv4.tcp_mem
- net.ipv4.tcp_wmem
- net.ipv4.tcp_rmem
- net.core.wmem_default
- net.core.rmem_default
- net.core.rmem_max
- net.core.wmem_max
- net.ipv4.tcp_syncookies
- net.ipv4.tcp_max_syn_backlog
- net.ipv4.tcp_synack_retries
- net.ipv4.tcp_syn_retries
- net.ipv4.tcp_fin_timeout
- net.ipv4.tcp_keepalive_time
- net.ipv4.tcp_tw_reuse
- net.ipv4.tcp_tw_recycle
- net.ipv4.ip_local_port_range
- net.ipv4.tcp_max_tw_buckets
- net.ipv4.route.max_size

**Comment by mtommila** [comment]
I would like to set the ephemeral port range in Fargate

**Comment by alexandredavi** [comment]
We have to change the TCP keepalive config.
net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_probes

**Comment by jglick** [comment]
`vm.max_map_count` for Elasticsearch (#1452).

**Comment by dwjvaughan** [comment]
We need to be able to increase the following for logstash UDP inputs:
- net.core.rmem_default
- net.core.rmem_max
I really hope this feature is coming soon...

**Comment by andycui66** [comment]
We need the following values to tune [Shadowsocks](https://shadowsocks.org/en/config/advanced.html).
```
net.ipv4.tcp_congestion_control
net.core.rmem_max
net.core.wmem_max
net.core.netdev_max_backlog
net.ipv4.tcp_fastopen
```

**Comment by mdomsch-seczetta** [comment]
need to set vm.max_map_count for Ruby Sidekiq running with 24GB RAM in Fargate to avoid the ruby garbage collector [BUG]ging out in either allocating or freeing heap pages.

**Comment by MaxWenzel** [comment]
We also have to change the TCP keepalive config:

net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_probes

**Comment by saluzafa** [comment]
When can we expect this feature to be available?

**Comment by saluzafa** [comment]
Is anyone here?

**Comment by alexcmms** [comment]
Hi everyone, apologies for the quietness on this issue. This is something we're actively working on (we've updated the status to "Coming Soon" rather than "Proposed"). In the first release we'll make it possible to make changes to the following sysctl settings: net.*, fs.mqueue.*, kernel.msgmax, kernel.msgmnb, kernel.msgmni, kernel.sem, kernel.shmall, kernel.shmmax, kernel.shmmni, and kernel.shm_rmid_forced.

**Comment by javier-torres** [comment]
Hello,

Any aprox date for this?

Thank you
Javier Torres

**Comment by vaibhavkhunger** [comment]
@javier-torres - cant share dates here, but you should expect it to launch within the next few quarters.

**Comment by gzmarstone** [comment]
Just ran into this today, wanted to set the tcp keepalive settings.

**Comment by jasonmorris-rl** [comment]
Also ran into this, looking to set the tcp keepidle/keepintvl.

**Comment by jsonmorris** [comment]
+1 also ran into this today; looking to set tcp keepintvl. Thanks!

**Comment by aidansteele** [comment]
Good news: these sysctls are now here! Thank you Fargate team 🎉 

https://aws.amazon.com/blogs/containers/announcing-additional-linux-controls-for-amazon-ecs-tasks-on-aws-fargate/

**Comment by jglick** [comment]
(But only for ECS, not EKS.)

**Comment by ollypom** [comment]
As @aidansteele mentioned, AWS Fargate now supports kernel parameter configuration (sysctl) for Amazon ECS tasks. 

To learn more:
- [What’s New Post: AWS Fargate supports PID namespace and kernel parameters configuration](https://aws.amazon.com/about-aws/whats-new/2023/08/aws-fargate-pid-namespace-sharing-kernel-configuration/)
- [AWS Tech Blog : AWS Fargate supports additional linux controls for Amazon ECS tasks](https://aws.amazon.com/blogs/containers/announcing-additional-linux-controls-for-amazon-ecs-tasks-on-aws-fargate/)
- [Documentation: ECS task definition parameters](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)

I'm closing this issue as it related to ECS/Fargate. However there are open issues tracking sysctl support on EKS/Fargate [here](https://github.com/aws/containers-roadmap/issues/967) and [here](https://github.com/aws/containers-roadmap/issues/1452).
