### ISSUE TITLE
Region Expansion

### ISSUE THREAD

**Issue by PatMyron** [aws/containers-roadmap#462]
**ECR:**
~~`ap-northeast-3`~~
**ECS:**
~~`ap-northeast-3`~~
**EKS:**
~~[`me-south-1`](https://github.com/aws/containers-roadmap/issues/441)~~, ~~[`ca-central-1`](https://github.com/aws/containers-roadmap/issues/113)~~, ~~[`sa-east-1`](https://github.com/aws/containers-roadmap/issues/112)~~, ~~[`cn-north-1`](https://github.com/aws/containers-roadmap/issues/219)~~, ~~[`cn-northwest-1`](https://github.com/aws/containers-roadmap/issues/77)~~, ~~[`us-gov-west-1`](https://github.com/aws/containers-roadmap/issues/253)~~, ~~[`us-gov-east-1`](https://github.com/aws/containers-roadmap/issues/375)~~, ~~[`af-south-1`](https://github.com/aws/containers-roadmap/issues/848)~~, ~~[`eu-south-1`](https://github.com/aws/containers-roadmap/issues/890)~~,  ~~[`us-west-1`](https://github.com/aws/containers-roadmap/issues/119)~~, ~~`ap-northeast-3`~~
**Fargate:**
~~[`sa-east-1`](https://github.com/aws/containers-roadmap/issues/402)~~, ~~[`eu-west-3`](https://github.com/aws/containers-roadmap/issues/309)~~, ~~[`eu-north-1`](https://github.com/aws/containers-roadmap/issues/280)~~, ~~[`me-south-1`](https://github.com/aws/containers-roadmap/issues/442)~~, ~~`cn-north-1`~~, ~~`cn-northwest-1`~~, ~~`ap-northeast-3`~~

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/
https://aws.amazon.com/ecr/pricing/
https://aws.amazon.com/fargate/pricing/

**Comment by weisjohn** [comment]
@PatMyron does this mean EKS for GovCloud is in progress? Or at least, it definitely will happen?

**Comment by PatMyron** [comment]
@weisjohn I don't work on containers, so I can't say. Just wanted one place to track region expansion :)

**Comment by weisjohn** [comment]
@PatMyron awesome, ok. thank you!
