### ISSUE TITLE
[EKS]: Kubernetes v1.11 End of Support (Nov 4, 2019)

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#464]
In line with the Kubernetes community support for Kubernetes versions, Amazon EKS 1.11 is now deprecated and will no longer be supported on **Nov 4, 2019**. On this day, you will no longer be able to create new 1.11 clusters and all EKS clusters running Kubernetes version 1.11 will be updated to the latest available platform version of Kubernetes version 1.12.

We recommend customers upgrade existing 1.11 or 1.12 clusters and worker nodes to at least 1.13 as soon as practical.

Learn more:
* [Updates to Amazon EKS Version Lifecycle](https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/)
* [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by dcopestake** [comment]
Is there any possibility of the Windows preview being updated to a more recent version? At the moment I'm stuck using 1.11 purely because of this.

**Comment by dcopestake** [comment]
So, didn't really fully appreciate the significance of this - in that clusters will be _automatically_ upgraded from 1.11 to 1.12 on November 4th. So what is the plan for those of us currently running clusters on 1.11 to participate in the Windows nodes preview?

**Comment by dcopestake** [comment]
To quote @mikestef9's [reply](https://github.com/aws/containers-roadmap/issues/69#issuecomment-537159639) in #69 

> GA availability for EKS Windows will be released before 1.11 is no longer supported.

**Comment by mikestef9** [comment]
@dcopestake [Windows GA](https://github.com/aws/containers-roadmap/issues/69) has been launched

**Comment by dcopestake** [comment]
Amazing, thanks @mikestef9!

**Comment by Kylepossible** [comment]
I noticed EKS 1.11 creation of clusters nor auto-upgrade has taken effect? Any ETA when this will happen?

**Comment by hugoprudente** [comment]
Hi team,

From this date `Nov 4, 2019` following the guidelines [EKS Version LifeCycle](https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/) the v1.12 would be marked to EOS (End Of Support) on `February 02, 2020` as it's +90 days from the latest announcement.

Do we have any information about it, so we can prepare?

**Comment by mikestef9** [comment]
Hi @hugoprudente 

We will announce the deprecation of v1.12 when we launch support for v1.15. From that announcement, you will have 60 days to upgrade existing 1.12 clusters before automatic updates start rolling out.
