### ISSUE TITLE
[EKS] Windows containers unable to resolve DNS

### ISSUE THREAD

**Issue by dcopestake** [aws/containers-roadmap#465]
**Tell us about your request**
I'm having an issue where my Windows containers appear to be unable to resolve _any_ DNS records as the DNS requests just time out. The Linux containers appear to be able to resolve DNS without any issues. After enabling logging in CoreDNS I can see the requests appearing when I query using the Linux containers, but _not_ the Windows ones, suggesting the requests aren't even getting through to the DNS service.

**Which service(s) is this request for?**
EKS

**Additional context**
Output of `ipconfig /all` on the test container is:

```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : <pod-name>-7bbf54ddf7-jmqxb
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter vEthernet (cid-93758c957f4ca490b658516f48ae8eecb347fe5bb81c13fb45a47e29acad8017):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
   Physical Address. . . . . . . . . : 00-15-5D-AC-15-BA
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::55db:6e2f:1a07:c706%38(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.146.129(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.224.0
   Default Gateway . . . . . . . . . : 192.168.128.1
   DNS Servers . . . . . . . . . . . : 10.100.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

And the `kube-dns` service appears to be running correctly:

```
NAME                                           READY   STATUS    RESTARTS   AGE
pod/aws-node-6p9db                             1/1     Running   0          19h
pod/coredns-854797898c-5nvhf                   1/1     Running   0          14m
pod/coredns-854797898c-nqc26                   1/1     Running   0          14m
pod/kube-proxy-gg62s                           1/1     Running   0          22h
pod/vpc-resource-controller-57b46f69d6-tcqrr   1/1     Running   0          16h

NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
service/kube-dns   ClusterIP   10.100.0.10   <none>        53/UDP,53/TCP   1d

NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/aws-node     1         1         1       1            1           <none>          1d
daemonset.apps/kube-proxy   1         1         1       1            1           <none>          1d

NAME                                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/coredns                   2         2         2            2           1d
deployment.apps/vpc-resource-controller   1         1         1            1           22h

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/coredns-854797898c                   2         2         2       1d
replicaset.apps/vpc-resource-controller-57b46f69d6   1         1         1       22h
```

**Comment by dcopestake** [comment]
Turns out to be entirely my fault. I create my node groups with their own security groups and didn't consider the fact that the nodes would need to talk across different groups (as in this case). Allowing traffic from my Windows node group security group to the Linux one resolved the issue.

**Comment by krishnaputhran** [comment]
HI, I am struggling with this for long time. I have a mix of Windows and Linux nodes on on my EKS clusters. one my stateful mysql deployment is running in Linux along with other micro service applications. One of the application is running in a windows node. My windows application is not able to reach the mysql application. When I tried to ping the mysql ip address from windows nodes its able to reach, but its unable to reach through DNS resolution. Pods running in Linux instances are able to resolve DNS. 
Even I played around these security groups. I appreciate if you can explain how did you fix it. especially you said "Allowing traffic from my Windows node group security group to the Linux one resolved the issue". How did you allow this?
