### ISSUE TITLE
EKS pods is not getting client ip

### ISSUE THREAD

**Issue by sarath9985** [aws/containers-roadmap#472]
Requirement: In application pod level, need to see all client ip's.
I tried with type=LoadBalancer and externalTrafficPolicy: Local in local, But it is not working for me.
I've tried with alb ingress and nginx ingress, both also not working.
So, i disabled SNAT also, still my pods not getting client IP.
In load balancer level i can see client IP's.

Every time my pod logs showing source ip, Client Request comes to load balancer  then forward to nodeport and forward to pod. Due to this process my pods was getting node ip's only.

I want to see all client ip's in pod logs.

**Comment by whereisaaron** [comment]
Hi @sarath9985 if you haven't already, you need to enable Proxy Protocol on your [Network Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol) and [nginx-ingress](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol).

https://kubernetes.github.io/ingress-nginx/deploy/#aws

https://medium.com/kokster/how-to-setup-nginx-ingress-controller-on-aws-clusters-7bd244278509.

If you are using an ALB can get the original IP from the HTTP headers (as pass it on if required).
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

**Comment by sarath9985** [comment]
Hi @whereisaaron  thanks for your response.  enabled proxy protocol is working for which pod receive the request that pod only print the client ips. Rest of the pods not printing same logs.

my requirement is need to print client ips on every pod logs.

Enabled host network true and open host port.
This should works, if you have multiple pods, every pod should print client ips.

Issue solved

**Comment by jadiaheno** [comment]
Hey, @whereisaaron just to tell you your comment was really helpful. Also, it works with NLBs. Thanks.

**Comment by ibrahim-albarki-multilogin** [comment]
@sarath9985 @whereisaaron I updated the config map and added this 
```
data:
  compute-full-forwarded-for: "true"
  proxy-real-ip-cidr: 10.0.0.0/16
  use-forwarded-headers: "true"
  use-proxy-protocol: "true"
```
but all pods still logs only local IP address of nginx-ingress-controller

**Comment by ibrahim-albarki-multilogin** [comment]
I am able to fix the issue by updating the classic load balancer to the network load balancer, more details can be found here 
https://aws.amazon.com/blogs/opensource/network-load-balancer-support-in-kubernetes-1-9/
