### ISSUE TITLE
[EKS] [request]: Windows AMI Packer files

### ISSUE THREAD

**Issue by abalakersky** [aws/containers-roadmap#475]
**Tell us about your request**
Would like to have Packer files, or at least directions, to build Windows AMI for EKS worker hosts.

**Which service(s) is this request for?**
 EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to show/test EKS with Windows capability in Hong Kong region. EKS Preview is missing Windows image in that region. Trying to create a copy of the Windows AMI from another region is not working. Need Packer job, or directions, to build image directly in HK region.

**Comment by ChrisMcKee** [comment]
This would be helpful in order to PR changes aswell.
It's extra leg work to have to extract the powershell and config from an instance just to see what config is available.
