### ISSUE TITLE
[EKS][service] [request]: Kubernetes 1.14 fix for cronjobs/jobs number

### ISSUE THREAD

**Issue by kraftaa** [aws/containers-roadmap#479]
**Tell us about your request**

Kubernetes 1.14 had a bug which stopped cronjobs from firing if number of jobs / cronjobs exceeded 500.
This bug was fixed by cherry-pick 2 days ago, when is this PR showing up in EKS? 
https://github.com/kubernetes/kubernetes/pull/79178
 
**Which service(s) is this request for?**
 EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Our cronjobs are not firing and need to be pushed manually once the number of jobs/cronjobs exceeds 500.
We need it to be working as scheduled.

**Are you currently working around this issue?**
This problem is solved by Kubernetes, our master needs to be updated.

**Comment by xrl** [comment]
Here's kraftaa's bug report in the kube repo: https://github.com/kubernetes/kubernetes/issues/82539 . The bugfix will be showing up in v1.14.7, to be released September 18. Can we get a release for 1.14.7 for EKS?

**Comment by robbinscp** [comment]
Confirming that I'm seeing the same thing on our end; we upgraded the master to 1.14 and all cronjobs immediately stopped working with no indication in the logs of the issue.  An expedited release would be appreciated.

**Comment by xrl** [comment]
@kraftaa can you put the `EKS` label on this?

**Comment by jdamata** [comment]
I checked today and all of my clusters are at 1.14 eks.2 which is 1.14.7 i believe:

https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html

**Comment by xrl** [comment]
We are still waiting on our eu-central-1 cluster to receive this update. This is a slow and frustrating process over which we have no control 😇

**Comment by mikestef9** [comment]
Closing given age of this issue
