### ISSUE TITLE
[EKS]: Support for Kubernetes 1.16

### ISSUE THREAD

**Issue by andrewbenton** [aws/containers-roadmap#487]
**Tell us about your request**
Support for Kubernetes 1.16

[Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md)
[Release Announcement](https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
My primary need out of k8s 1.16 is the dualstack networking on pods.  This will allow my team to make outbound ipv4 and ipv6 network requests directly from kubernetes.  Currently this requires that we run services that need oubound dualstack access elsewhere.  There are a ton of other features that I can see being useful including ephemeral pods and the topology manager.

**Comment by mathewmoon** [comment]
This is needed for using EIP with NLB's

**Comment by antoniobeyah** [comment]
@mikestef9 Thank you for updating the tickets- question related to your comment [here](https://github.com/aws/containers-roadmap/issues/380#issuecomment-597351516). Does that imply that we could potentially see 1.16 sooner than the typical 90 day roadmap?   Asking because we are planning on performing a cluster migration to the newest available version and can wait a bit longer for 1.16 if its within the next month or so otherwise we would look at performing a migration to 1.15 and then 1.16.  Not looking for any commitments just some clarification on the `already in progress` and whether or not that has implications on the timeline.

Thanks,
Antonio

**Comment by mikestef9** [comment]
@antoniobeyah can't give any definite timelines, but one of priorities for EKS this year is reduce the gap between upstream releases and EKS support, which will require a temporary release schedule that is sooner than every 90 days.

**Comment by danielmittelman** [comment]
Good luck! this release is an opportunity to start a clean slate with your customers (us included) after v1.15. We're looking forward to see how this release plays out!

**Comment by khacminh** [comment]
As @tabern said at: https://github.com/aws/containers-roadmap/issues/380#issuecomment-570126886.

> Our GA for 1.15 is a bit later than we originally planned because the team made a conscious decision to adjust the rollout schedule in order to invest in simplifying, streamlining, and further automating our version qualification and release processes. This slowed down our timeline for releasing 1.15, but will allow us to ship new Kubernetes versions faster going forward.

Therefore, I hope version 1.16 will GA soon.

**Comment by AceHack** [comment]
Is there any update on a release date?  Thanks.

**Comment by kferrone** [comment]
So I was all kinds of excited for this project: [kubernetes-sigs/cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws). It introduces the idea of a manager cluster which manages app clusters. It didn't work because k8s must be v1.16 and we are using EKS . . . sigh

**Comment by jingweno** [comment]
Any update on the release date? Thanks

**Comment by mikestef9** [comment]
As we get closer to adding support for Kubernetes 1.16 to EKS, we want to make sure the upgrade experience is smooth for all customers. 

Kubernetes 1.16 includes a number of deprecated API removals, and you need to ensure your applications and add ons are updated, or workloads could fail after the upgrade is complete. 

For more information on the API removals, see the [Kubernetes blog post](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). 

For action you can take right now, see the steps in our [documentation](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prequisites). 

All of the replacement APIs are in Kubernetes versions later than 1.10, which means applications on any supported version of Amazon EKS can begin using the updated APIs now.

**Comment by mikestef9** [comment]
**Amazon Elastic Kubernetes Service (EKS) now supports Kubernetes version 1.16.8 for all clusters.**

For more information, see the 1.16 release notes and highlights in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html).

Learn more about the Kubernetes versions available for production workloads on Amazon EKS and how to update your cluster to version 1.16 in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html).

**Important** Read the [1.16 prerequisites](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prequisites) before upgrading, as explained in the comment above, Kubernetes 1.16 includes a number of deprecated API removals.

[What's New post](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-eks-now-supports-kubernetes-version-1-16/)

Additional Notes:
- eksctl support for Kubernetes 1.16 is coming soon and we will close this issue when that is released.
- Kubernetes version 1.13 in EKS is now deprecated, and will no longer be supported on June 30th, 2020. This is being tracked in #871
