### ISSUE TITLE
[EKS] [Coredns] use forward plugin instead of proxy plugin in kubernetes 1.14 

### ISSUE THREAD

**Issue by s-tokutake** [aws/containers-roadmap#489]
**Tell us about your request**

- Coredns's Corefile in EKS cluster k8s version 1.14 use ` proxy ` plugin. But 1.14 use CoreDNS ` forward ` plugin instead of ` proxy ` plugin by default.
- ` proxy ` plugin has problems and it was deprecated.
  - cf https://github.com/coredns/coredns/issues/1443

What do you want us to build?

- When I create a cluster version 1.14,  CoreDNS use ` forward ` plugin instead of ` proxy ` plugin by default.

**Which service(s) is this request for?**
 EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

- We sometimes face errors of name resolving. We suspect the cause is  `  proxy ` plugin's bug. So we want to use  ` forward ` plugin.

**Comment by yuri-1987** [comment]
we were hitting this issue as well, some external AAAA records took more than 5s to respond.

in addition to those performance issues, the proxy plugin is deprecated in future releases of coredns so upgrading from 1.3.1 to 1.5.2 in existing clusters using the same configmap won't be successful.

**Comment by vipulsabhaya** [comment]
@yuri-1987 @s-tokutake thanks for reporting this.  

We are looking at changing the Corefile for 1.14 from `proxy` to `forward`.  Can you validate that updating the coredns ConfigMap to (below) solves the issues you're seeing?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

**Comment by s-tokutake** [comment]
@vipulsabhaya Thank you for your reply.

I applied the configmap you presented.
It seems to work. thanks.

... and it is another matter that coredns deployment also old. it does not contain readinessprobe, but readinessProbe to CoreDNS was added in kubernetes 1.14.
cf. kubernetes/kubernetes#74137

**Comment by deiwin** [comment]
That change uses the `/health` endpoint, but CoreDNS now has a [`ready` plugin](https://coredns.io/plugins/ready/) as well.

**Comment by yuri-1987** [comment]
@vipulsabhaya, yep this config works for us, we running for a week with coredns 1.5.2, and the dns resolutions are much faster with the forward plugin.

**Comment by bhagwat070919** [comment]
Hi All,

EKS 1.14 supports the forward plugin as default plugin along with the readiness.

**Comment by owlwalks** [comment]
hi @bhagwat070919  could you link me the update guide ? thanks

**Comment by bhagwat070919** [comment]
@owlwalks ,

you can see the above comment mentioned by @vipulsabhaya 

https://github.com/aws/containers-roadmap/issues/489#issuecomment-537789170

**Comment by nitrag** [comment]
We have three clusters running EKS 1.13. We spun up a fourth EKS cluster 5 days ago that defaulted to EKS 1.14 and CoreDNS 1.3.1 with the `forward` functionality and we are seeing intermittent DNS failures.

Majority of those errors are for cluster local resolution to our rabbitmq pod (which has been UP and Running/stable for 4.5 days), but we are also (rarely) seeing external failures to services like RDS.

We are being forced to downgrade to 1.13, however we will spin up a new cluster later this week with 1.14 for continued debugging. Any tips?

**Comment by deiwin** [comment]
I addressed a similar question in https://github.com/aws/amazon-vpc-cni-k8s/issues/595#issuecomment-537077288, @nitrag. Easy to check.

**Comment by owlwalks** [comment]
@deiwin the trick doesn’t work for me, coredns (?) still intermittently fails DNS queries, positive side is failure rate on 1.6 seems to be lower, could this be a bug of aws eks cni somehow?

**Comment by deiwin** [comment]
What versions of EKS and the CNI plugin are you using?

**Comment by owlwalks** [comment]
I'm running eks 1.14 and amazon-k8s-cni:1.5.4, my python apps run on debian:jessie

**Comment by deiwin** [comment]
@owlwalks, are you aware of https://github.com/aws/amazon-vpc-cni-k8s/issues/641? Reverting to `amazon-k8s-cni:1.5.3` (and possible replacing the nodes) could help in your case.

**Comment by owlwalks** [comment]
thanks @deiwin ! wish i see that issue earlier, it bugs me for 2 wks so I just went on with cillium, so far so good, debian:jessie and even alpine all works
