### ISSUE TITLE
[EKS] [request]: Offer Prometheus as a managed service

### ISSUE THREAD

**Issue by tomfotherby** [aws/containers-roadmap#491]
**Tell us about your request**
It would be great if the [Prometheus](https://prometheus.io/) time-series database was provided as a managed service.

**Which service(s) is this request for?**
This could be useful as a stand-alone database but it could be particularly useful if it integrated with EKS, maybe via a Kubernetes Operator to power things like Grafana, AlertManager and HPA's via a custom metrics API.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Running Prometheus in a EKS cluster isn't "hard", for example there is the [Kube-Prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) project which combines the Prometheus Operator with a collection of manifests to help get started with monitoring Kubernetes itself and applications running on top of it. 
However, out of the box there is no persistent storage so everytime a Prometheus Pod is restarted, data is lost, Grafana dashboards are lost, etc. It's also quite a manual process to make upgrades when they are released. Prometheus also ends up using quite a lot of the cluster resources meaning the EKS cluster needs to be bigger than you expect for your application workload.
If Prometheus was a service outside the cluster with persistent storage, it would make things simpler.

**Are you currently working around this issue?**
Yes, by self-hosting Prometheus within the EKS cluster using the aformentioned [Kube-Prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) project.

**Comment by SripriyaMenon** [comment]
Do we have any update on this??

**Comment by max-rocket-internet** [comment]
What does "Prometheus as part of RDS" have to do with EKS?

**Comment by tomfotherby** [comment]
> What does "Prometheus as part of RDS" have to do with EKS?

Many folks using EKS will also use Prometheus. It would be great if there was a managed Prometheus service.

Good point though, Prometheus wouldn't ever be part of RDS because it's not Relational. I'll fix the Issue Title.

**Comment by sqlexception** [comment]
Running Prometheuss outside of EKS and monitor the cluster is not an so complex topic. If you need support poke me :)

**Comment by tomfotherby** [comment]
I'm unclear how compatible with Prometheus it is, but AWS now has [Amazon Timestream](https://aws.amazon.com/timestream/):

> Fast, scalable, serverless time series database

Annoucnement: https://aws.amazon.com/blogs/aws/store-and-access-time-series-data-at-any-scale-with-amazon-timestream-now-generally-available/

I can't wait to see this integrated tightly with EKS so that we don't need to self-host Prometheus.

**Comment by tomfotherby** [comment]
Announcement: https://aws.amazon.com/about-aws/whats-new/2020/12/aws-announces-amazon-managed-service-for-prometheus/ (and [Grafana too](https://aws.amazon.com/blogs/aws/announcing-amazon-managed-grafana-service-in-preview/))

Thank you AWS. :heart: 

Product Page: https://aws.amazon.com/prometheus/
