### ISSUE TITLE
[EKS] [request]: Support for tags in Cloudformation

### ISSUE THREAD

**Issue by pmontanari** [aws/containers-roadmap#506]
Tell us about your request
Support for tagging resources from CloudFormation

Which service(s) is this request for?
EKS

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
Currently there is no support for adding tags to things like AWS::EKS:Cluster

Are you currently working around this issue?
Adding the tags manually after CFN has created the stack.

**Comment by kartik-moolya** [comment]
This is such an important feature yet missing :disappointed:

**Comment by kedar700** [comment]
Yeah this is a super important feature.

**Comment by ryanpflynn** [comment]
+1 This would be very useful.

**Comment by rbuenoc** [comment]
+1

**Comment by mikestef9** [comment]
Good news to share! You can set and update tags on your cluster resource through CloudFormation.

Details in the EKS Cluster resource docs

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html
