### ISSUE TITLE
[EKS] [request]: Container Insights to support tainted nodes

### ISSUE THREAD

**Issue by samuelthan** [aws/containers-roadmap#507]
**Tell us about your request**
AWS Container Insights to support tainted EKS nodes

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When a EKS nodes is tainted, no other pods can be scheduled into nodes unless tolerance is applied.
Container Insights implementation which includes cloudwatch-agents with a non-system namespace is not abled to be scheduled into the tainted node due to such restriction.

**Are you currently working around this issue?**
Not use tainted feature in kubernetes. not a good workaraound at the moment.

**Comment by ivanmp91** [comment]
I think this would be really nice! Especially if you're running datastores inside k8s and you want to isolate those pods to be running on specific node groups.
