### ISSUE TITLE
[ECR] Use customer master keys (KMS CMKs) to encrypt your data

### ISSUE THREAD

**Issue by jtoberon** [aws/containers-roadmap#52]
Many AWS services use AWS KMS to support encryption of your data. With this feature, you can use the customer master keys (CMKs) in your account to protect the data that ECR stores for you.

**Comment by nmarchini** [comment]
Any news on when this might be available please?

**Comment by Disgruntled** [comment]
Any update on this? This is causing me, a large enterprise customer a lot of grief

**Comment by rekcah78** [comment]
I can see it now in the console, we can choose a KMS key for a repository

**Comment by Disgruntled** [comment]
Confirmed, TAM let us know this was pending and it indeed it is now visible.

Ty AWS team!

**Comment by omieomye** [comment]
We are completing worldwide deployment today and should shortly announce. Looking forward to the community’s feedback so we can continue to make this capability better.

**Comment by mwarkentin** [comment]
@omieomye as always, support here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

**Comment by omieomye** [comment]
[Shipped!](https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys)
