### ISSUE TITLE
Containers need additional storage

### ISSUE THREAD

**Issue by blaines** [aws/containers-roadmap#526]
I'm looking in to how to modify the `dm.basesize` setting. It's not incredibly clear where to push these kinds of configuration settings. Could someone please follow up with a stable place to modify some storage defaults? Thanks!

I'm seeing related settings in /etc/sysconfig/docker-storage-setup, /etc/sysconfig/docker-storage, and other files.

More info about `dm.basesize` can be found here: https://docs.docker.com/v1.10/engine/reference/commandline/daemon/

```
[ec2-user@debug ~]$ cat /etc/sysconfig/docker-storage
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true --storage-opt dm.fs=ext4"
[ec2-user@debug ~]$ cat /etc/sysconfig/docker-storage-setup
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"
DEVS=/dev/xvdcz
VG=docker
DATA_SIZE=99%FREE
AUTO_EXTEND_POOL=yes
LV_ERROR_WHEN_FULL=yes
EXTRA_DOCKER_STORAGE_OPTIONS="--storage-opt dm.fs=ext4"
[ec2-user@debug ~]$
```

For now, I modified `OPTIONS` in `/etc/sysconfig/docker` with `--storage-opt dm.basesize=20G`

Also, is there a way to allocate storage in a task definition? Do you by chance have any suggestions if one container for example needs 100G of storage, when the others may be sufficient with 10G?

**Comment by pavneeta** [comment]
https://github.com/aws/containers-roadmap/issues/348

**Comment by benmccown-amz** [comment]
For those running an ECS optimized Windows 2019 AMI, the following works if added to your UserData.

```
sc.exe config docker binPath= "C:\Program` Files\Docker\dockerd.exe --run-service --storage-opt size=40G"
net stop docker /y
net start docker
```

**Comment by johannes-gehrs** [comment]
(I am not 100% sure if this only applies to AWS Batch, but I think it applies to ECS in general)

The Amazon Linux 2 AMI no longer requires fiddling with `storage-opt dm.basesize`. You can just use a larger volume and that's it. This is because Amazon Linux 2 AMI utilizes the OverlayFS storage driver.

**Comment by libert-xyz** [comment]
Confirmed. AmazonLinux 2 does not need this workaround

**Comment by kendrexs** [comment]
Closing this issue as no longer needed
