### ISSUE TITLE
[EKS] [Global Rollout]: Deploy to all remaining AWS Regions

### ISSUE THREAD

**Issue by jsamuel1** [aws/containers-roadmap#54]
In order to allow globally consistent deployments, have feature parity in all AWS Regions, including the 2AZ regions such as Canada for EKS.

This will allow customers to move fast by avoiding maintaining kops based kubernetes deployments when deploying to regions that you are currently not supporting.

**Comment by tabern** [comment]
EKS is now in all AWS Global regions. https://docs.aws.amazon.com/general/latest/gr/eks.html
