### ISSUE TITLE
[EKS] [bug]: vpc-admission-webhook only groks deprecated beta.kubernetes.io/os=windows nodeSelector

### ISSUE THREAD

**Issue by jglick** [aws/containers-roadmap#542]
**Tell us about your request**
The EKS admission webhook that is supposed to add the annotation `vpc.amazonaws.com/PrivateIPv4Address` to a Windows pod understands

```yaml
spec:
  nodeSelector:
    beta.kubernetes.io/os: windows
```

but not

```yaml
spec:
  nodeSelector:
    kubernetes.io/os: windows
```

**Which service(s) is this request for?**
EKS, `v1.14.6-eks-5047ed`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html says to use a node selector which acc. to https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os is deprecated (acc. to https://kubernetes.io/docs/setup/release/notes/#deprecations-and-removals since 1.14). If you use the deprecated selector, Windows pods work. If you use the selector recommended by kubernetes.io, Windows pods do not work, and give a rather cryptic error

```
Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "…" network for pod "…": NetworkPlugin cni failed to set up pod "…" network: failed to parse Kubernetes args: pod does not have label vpc.amazonaws.com/PrivateIPv4Address, failed to clean up sandbox container "…" network for pod "…": NetworkPlugin cni failed to teardown pod "…" network: failed to parse Kubernetes args: pod does not have label vpc.amazonaws.com/PrivateIPv4Address]
```

(The error message is also misleading because this is an annotation, not a label.) Can be tracked down in `vpc-admission-webhook` pod logs as saying

```
…       1 webhook.go:287] Skip mutation for … as the target platform is .
```

**Are you currently working around this issue?**
Using the deprecated `beta.kubernetes.io/os`.

**Additional context**
N/A

**Attachments**
N/A

**Comment by Muchengeti** [comment]
I would like to see this feature added 👍

**Comment by johndaviesco** [comment]
Yeah it would be super helpful to have this please 💯

**Comment by mikestef9** [comment]
This was resolved in the most recent version of VPC Admission Webhook. See https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html for details on installing latest version.

**Comment by anarsen** [comment]
@mikestef9 Awesome. Going to try it out immediately.

Just in case it's not already underway, the docs [here](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support) still refer to the `beta.kubernetes.io/os` selector.

**Comment by mikestef9** [comment]
We will update the docs, thanks for the call out
