### ISSUE TITLE
[EKS] [aws-iam-authenticator]: Add aws-iam-authenticator as a CRD

### ISSUE THREAD

**Issue by galindro** [aws/containers-roadmap#550]
**Tell us about your request**
Add aws-iam-authenticator as a CRD on EKS

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/79#

**Are you currently working around this issue?**
Using aws-iam-authenticator with kubectl

**Comment by sagikazarmark** [comment]
Would be nice to have this feature in EKS. Using the configmap to manage users is a pain right now. Is there an ETA?

**Comment by 3oris** [comment]
This has been in aws-iam-authenticator for a while now:
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.1

How can this be enabled in EKS?
See also: https://github.com/aws/containers-roadmap/issues/512

**Comment by rustrial** [comment]
If you need a solution supporting CRDs with EKS, please have a look at https://github.com/rustrial/aws-eks-iam-auth-controller, I use it for all my EKS clusters. It uses the CRDs (API) from aws-iam-authenticator and therefore is compatible with aws-iam-authenticator.

**Comment by gilbahat** [comment]
Hi @mikestef9, can this please be reopened? the way this was resolved is very ISV-unfriendly

**Comment by tvalasek** [comment]
I have to disagree this was addressed with https://github.com/aws/containers-roadmap/issues/185. The ask is to automate this using K8s/EKS primitives

**Comment by mikestef9** [comment]
Would using ACK in conjunction with #185 meet your requirements?

https://aws-controllers-k8s.github.io/community/reference/eks/v1alpha1/accessentry/
