### ISSUE TITLE
[EKS] [upgrade]: upgrade to kubernetes 1.14.8 due to ELBs being broken in 1.14.7

### ISSUE THREAD

**Issue by lhotrifork** [aws/containers-roadmap#551]
**Tell us about your request**
Kubernetes 1.14.8 was recently released, which contains a fix for: https://github.com/kubernetes/kubernetes/pull/82954 
It would be good to have this released as an AMI soon, as it breaks EKS quite badly.

**Which service(s) is this request for?**
EKS

**Comment by devkid** [comment]
Correct me if I'm wrong, but this needs to be fixed in the master, not the AMI.

**Comment by vipulsabhaya** [comment]
@lhotrifork We are planning to roll out 1.14.8 soon.  Just to clarify, 1.14.7 released by EKS had the cherry-pick already, and does not impact AWS ELB functionality.

**Comment by martijnburger** [comment]
Looks like it's there:

Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
