### ISSUE TITLE
[ECR] [request]: Cloudformation integration for ECR vulnerability scanning

### ISSUE THREAD

**Issue by jeffcarrico** [aws/containers-roadmap#552]
**Tell us about your request**
Cloudformation integration to activate [image vulnerability scan](https://aws.amazon.com/blogs/containers/amazon-ecr-native-container-image-scanning) on push for ECR::Repository, #17 

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Want to take advantage of the feature, without having to invest in developing and maintaining a workaround. Cloudformation feature parity benefits all customers.

**Comment by whereisaaron** [comment]
Ref: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/245

**Comment by ngamradt-turner** [comment]
@omieomye Do we know when this will get released?  I noticed that the last update was about a month ago.

**Comment by autarchprinceps** [comment]
What's the holdup? This seems like a pretty easy 1:1 mapping of CloudFormation to AWS API call parameter.
CloudFormation is your official tool for infrastructure as code, but it is treated like an unwanted step child, meanwhile Terraform has implemented this 4 and a half months ago: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2340-october-31-2019

**Comment by JohnPreston** [comment]
I can't agree more with that. I am a forever fighter for AWS CFN and ECS and big advocate for it but there really should be something in AWS to agree that something can come out if there is support for it in CFN. Some things like the capacity providers being immutable makes it understandable that the AWS CFN team is not responsible for an unmanageable resource type for CRUD but so many features are simply already there in SDKs.
Again, appreciate that once it is released it has to work and so these sort of features must be tested again and again and rolled out to all regions supporting it. But still, CFN support should be a must-have for any resource and keep up with the new API calls available for the resource.

**Comment by glnds** [comment]
I can't agree more. IMHO CF support should be in the Definition of Done for every new feature. IaC is a constraint in many companies nowadays, so a feature lacking CF support is just useless in that context. I had our CTO delivered that message straight to Werner a while ago. I think he could more or less agree on it. Nevertheless i don't see it happen :(
Whenever the discussion CF vs Terraforms pops up this one is thrown right in my face (and I can’t blame them)

**Comment by JohnPreston** [comment]
@glnds yup, I keep fighting the good fight against over complicating infra build with 3rd party tools as AWS always comes up with a perfectly builtin feature eventually but then it's rarely supported out of the box on AWS and I just can't justify using custom resources all over the place for a simple API call.

**Comment by glnds** [comment]
@JohnPreston exactly. It seems the standard answer from AWS Support: "If you want to, you can do it using a custom resource".  I write a lot of CF code but i'm very reluctant towards custom resources, especially in this scenario, then it's just not the right answer.

**Comment by JohnPreston** [comment]
@glnds totally. I am working on [this](https://github.com/lambda-my-aws/ecs_composex) as a side project and there are so many things to think about and tweaks etc. around the containers world and this is ECR thing is a prime example of something that can save money, or even just add another layer of security if InfoSec want to use Snyk or whatever 3rd party dependencies and images scanning etc.
But, right now I am in a position where I am trying to get people onboard with not depending on any 3rd party as the nature of what we are building must work today, and in 5 years, and going with AWS purely and solely. And with CFN API being so consistent over the years (got templates from way back which still work no bother today), other tools just don't have that and won't as it is driven by so many players in the field, IMHO. 
I am wining the argument and then boom, that kind of slip from AWS gets thrown in my face.

**Comment by amitsehgal** [comment]
When is this feature coming. out ? i second comments above...it looks pretty staright forward flag set on API on the face of it and already there in terraform from day 1.

**Comment by runningman84** [comment]
What I don't get is why aws spends time and money implementing this feature in cdk using custom resources but don't solve this in the underlying Cloudformation layer.

**Comment by pipozzz** [comment]
It's funny that terraform is much faster than cloudformation team :D

**Comment by ameir** [comment]
I'm not sure when this released, but it looks like this is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagescanningconfiguration

**Comment by glnds** [comment]
> I'm not sure when this released, but it looks like this is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagescanningconfiguration

Yes it seems so and it also seems the CF release history is not up-to-date...
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by robbyt** [comment]
This change was just added yesterday: https://github.com/awsdocs/aws-cloudformation-user-guide/commit/cb59b660eecc5249dc22166a809cf6150512f78f @rachfop Here is an example using this feature.

```
  EcrRepo:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref 'AWS::StackName'
      ImageScanningConfiguration:
        scanOnPush: true
```

Also, it is a bit disappointing that "_Periodic update 18 August 2020_" is an acceptable git commit message for engineers at Amazon.

**Comment by rachfop** [comment]
@glnds I have let the ECR doc team know of update.  
@robbyt see explanation [here](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/699#issuecomment-657704577). In this case the general merge introduced a new change which the ECR team will address.

**Comment by robbyt** [comment]
> @glnds I have let the ECR doc team know of update.
> @robbyt see explanation [here](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/699#issuecomment-657704577). In this case the general merge introduced a new change which the ECR team will address.

Thanks for responding so quickly. Reasonable source control history is super useful to understand changes in documentation, so hopefully the release process for documentation will be improved in the future.

**Comment by rachfop** [comment]
@robbyt agreed. We are always looking for ways to improve our documentation process. Thank you again for your feedback.

**Comment by trainguyenx** [comment]
Hi guys,
any examples this feature code block? I tried a lot, but still get the error `Model validation failed (#/ImageScanningConfiguration: expected type: JSONObject, found: String)`

```
t.add_resource(ecr.Repository(
        "GatewayServiceRegistry",
        RepositoryName="gateway-service",
        ImageScanningConfiguration={
          'scanOnPush': 'true'
        }
    ))

t.add_resource(ecr.Repository(
        "GatewayServiceRegistry",
        RepositoryName="gateway-service",
        ImageScanningConfiguration={
          "scanOnPush": "true"
        }
    ))
```

Thanks for your help!

**Comment by njsaunders** [comment]
Looks like this is now available: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagescanningconfiguration

**Comment by omieomye** [comment]
Closing.
