### ISSUE TITLE
[ECR] [CLOUDWATCH][request]: Send scanning metrics to cloudwatch

### ISSUE THREAD

**Issue by nunofernandes** [aws/containers-roadmap#557]
**Tell us about your request**
After the closure of https://github.com/aws/containers-roadmap/issues/17, It would be great if the scanning would send metrics to cloudwatch metrics so that we can create cloudwatch alerts based on the number of vunerabilities found (critical, high, etc). Then we could send those to a lambda or any other method.

**Which service(s) is this request for?**
ECR and Cloudwatch Metrics

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Getting alerts on slack about a container pushed to ECR that has security issues.

**Are you currently working around this issue?**
Custom script that pools daily the ECR to see the number of HIGH or Critical security issues and send an alert to slack.

**Comment by siva-kumaran** [comment]
👍 
This is highly recommended! We can then pipe these for our notification systems beyond.

**Comment by jtoberon** [comment]
Great idea!

Can you clarify how you're thinking about the dimensions (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Dimension) of these metrics? For example, do you want one metric (i.e. a count) per registry/repo/severity, or does image need to be in the dimension, too? Assuming that image is not a dimension, do you want to control which image in that repo we should publish the metric for?

My approach would be to make a simplifying assumption that one should not include image as a dimension. One needs to rebuild semi-regularly anyway just to pick up the latest and greatest security patches, such as the ones from your Linux distro. When you rebuild, it creates a new image, at which point the metrics associated with older images become less valuable for notifications.

The counterargument to this is that, unless you have a great CICD system, you actually care about multiple images, the latest build and the one you're actually running in production.

**Comment by nunofernandes** [comment]
Agree with that we don't need the image as a dimension. But I'm not using more than one image name per repo. For me is enough to have registry/repo/severity.

**Comment by RameshAkkiraju** [comment]
> **Tell us about your request**
> After the closure of #17, It would be great if the scanning would send metrics to cloudwatch metrics so that we can create cloudwatch alerts based on the number of vunerabilities found (critical, high, etc). Then we could send those to a lambda or any other method.
> 
> **Which service(s) is this request for?**
> ECR and Cloudwatch Metrics
> 
> **Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
> Getting alerts on slack about a container pushed to ECR that has security issues.
> 
> **Are you currently working around this issue?**
> Custom script that pools daily the ECR to see the number of HIGH or Critical security issues and send an alert to slack.

Has this been implemented?

**Comment by omieomye** [comment]
@RameshAkkiraju @nunofernandes ECR sends a scan completed event to CW Events, so you can create a lambda to take action based on the results of a scan. [Docs here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html). See https://github.com/aws/containers-roadmap/issues/565 for more information. Would this work for the use case described (take action based on number of severity in scan results?)

**Comment by omieomye** [comment]
Closing.  This is available today, see our [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html) and see https://github.com/aws/containers-roadmap/issues/565 for follow-on discussion in using an ECR Image Scan event.

**Comment by mogggggg** [comment]
> Closing. This is available today, see our [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html) and see #565 for follow-on discussion in using an ECR Image Scan event.

Those links are around CloudWatch events whereas this issue was around CloudWatch metrics
