### ISSUE TITLE
[ECR] [request]: In addition to OS packages, also scan language specific libraries (e.g. JAR files) in a container image

### ISSUE THREAD

**Issue by jicowan** [aws/containers-roadmap#563]
**Tell us about your request**
Extend the functionality of image scanning to include all the layers of a container image. 

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Vulnerabilities can be found in the libraries and packages that are added to the image.

**Comment by jtoberon** [comment]
Can you provide a more specific example of what you mean? We do scan all layers today.

**Comment by jicowan** [comment]
I meant the application libraries.

**Comment by heidemn** [comment]
E.g. the open source tool Trivy supports scanning based on NPM's `package-lock.json`, Composer's `composer.lock`, and many more. See https://github.com/aquasecurity/trivy#application-dependencies .

For our team, NPM and Composer would be the most important dependency managers to support.

I know that Clair ([used by ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html)) does not support this feature now. but ECR scanning doesn't need to be limited to using a single tool.
ECR scanning could combine multiple tools, and provide the consolidated results of all these tools.
Or, Amazon could contribute to Clair to make this feature available to all Clair users.

**Comment by truppert-mdsol** [comment]
I was pointed to this ticket by an AWS Support Representative when we noticed that the scan results were inaccurate.  Have any decisions been made around implementing this and is there any ETA?

We need full trust from a vulnerability scanning tool or it is useless to us.  Having scan results that miss known, published vulnerabilities seems like a definite bug in a vulnerability scanner.

**Comment by mailjunze** [comment]
Any update on this . The issue has been opened in 2019 ?

**Comment by pinkavaj** [comment]
Having list of CVEs for installed PIP packages (packages installed by pip, not by OS package management) is must-have for us, withought it the scanning is pretty useless for us :(, we would really appreciate this feature.

**Comment by heidemn-faro** [comment]
This seems to be implemented now. Enable this setting under "Private Registry > Scanning".

![image](https://user-images.githubusercontent.com/66078329/155355933-e6252468-6e92-4235-87ea-4557e2ebd980.png)

**Comment by bradg-aws** [comment]
As mentioned, enhanced scanning has added programming language detection and can be enabled through ECR console or ECR's [PutRegistryScanningConfiguration](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutRegistryScanningConfiguration.html) API.


Please see https://docs.aws.amazon.com/inspector/latest/user/supported.html#w123aac53c19 for programming languages supported by ECR Enhanced Scanning with Inspector.
