### ISSUE TITLE
ECR [request]: Include summary of image scan findings in the ECR event stream

### ISSUE THREAD

**Issue by jicowan** [aws/containers-roadmap#565]
**Tell us about your request**
Add a summary of the image scan finding to the ECR event stream.  Currently, the event stream only shows when a scan has been completed. 

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to identify the images I've deployed that have developed vulnerabilities over time. 

**Are you currently working around this issue?**
I have to query the ECR API.

**Comment by pzbiegiel** [comment]
This would definitely be a welcome addition to save us having to retrieve the findings just to get the counts.

**Comment by michaelwittig** [comment]
I would add that the scan result is _the_ information.

**Comment by omieomye** [comment]
This is complete, the ECR Image Scan event now contains a count of the vulnerability severities found in a `finding-severity-counts` object in the `detail` portion of the event JSON.  For example: `"finding-severity-counts": {
	     "CRITICAL": 10,
	     "MEDIUM”: 9
	  }`  See the full event schema here: https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html

**Comment by michaelwittig** [comment]
@omieomye Are the severities documented? I can not find them in the ECR docs.

**Comment by donhector** [comment]
My use case is to be able to send out an Email notification only if `finding-severity-counts` shows something of interest (for example, CRITICAL, HIGH, or MEDIUM) and not send emails on every single scan (at work we have hundreds of repos with new images being pushed daily to those repos)

My approach was to create a CloudWatch event on ECR Image Scan, and a SNS topic 'ecr-scans' as the target. Then configure the SNS topic to have one subscriber of the type Email.

Unfortunately and according to the docs, event pattern syntax does not allow wildcards, so I don't have an easy way to send the email only when something "relevant" was detected by the scan.

I'm trying to avoid having to purposely create a Lambda to do the filtering and emailing. 

Any suggestions?

**Comment by michaelwittig** [comment]
thanks to https://aws.amazon.com/blogs/compute/reducing-custom-code-by-using-advanced-rules-in-amazon-eventbridge/  we can no filter:

```
{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "finding-severity-counts": {
      "HIGH": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "MEDIUM": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "UNDEFINED": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "CRITICAL": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ]
    }
  }
}
```

**Comment by pashasensi** [comment]
> thanks to https://aws.amazon.com/blogs/compute/reducing-custom-code-by-using-advanced-rules-in-amazon-eventbridge/ we can now filter:

this only works if you manually create the Rule in event bridge.
If you create the Rule using cloudformation or through CDK, you will get a 'Event pattern is not valid.' message.

this is a simple example:

```
const pattern = {
        "source": [ "aws.ecr" ],
        "detail-type": [ "ECR Image Scan" ],
        "detail": {
          "scan-status": [ "COMPLETE" ],
          "finding-severity-counts": { "MEDIUM": [ { "numeric": [ ">", 0 ] } ]}
        }
};
const rule = new Rule(scope, "newRule");
rule.addEventPattern(pattern);

````

**Comment by Nishintra** [comment]
@pashasensi  Yes this is not working while creating using Cloudformation. What is the way to do it in Cloudformation template for Eventbridge.

**Comment by varunreddy6999** [comment]
HI @michaelwittig ,
I'm trying to filter ECR scannings which has either HIGH or CRITICAL findings with following event pattern, but this event is matching only when there are HIGH and CRITICAL findings in my image, can you please help me with this

{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "finding-severity-counts": {
      "CRITICAL": [{
        "numeric": [">", 0]
      }],
      "CRITICAL": [{
        "numeric": [">", 0]
      }]
    }
  }
}

**Comment by man0790** [comment]
> HI @michaelwittig , I'm trying to filter ECR scannings which has either HIGH or CRITICAL findings with following event pattern, but this event is matching only when there are HIGH and CRITICAL findings in my image, can you please help me with this
> 
> { "detail-type": [ "ECR Image Scan" ], "source": [ "aws.ecr" ], "detail": { "finding-severity-counts": { "CRITICAL": [{ "numeric": [">", 0] }], "HIGH": [{ "numeric": [">", 0] }] } } }

Did you get it work for OR situation?

**Comment by michaelwittig** [comment]
```
      detail:
          finding-severity-counts:
            CRITICAL: [{exists: false}, {numeric: ['>', 0]}]
            HIGH: [{exists: false}, {numeric: ['>', 0]}]
            MEDIUM: [{exists: false}, {numeric: ['>', 0]}]
            UNDEFINED: [{exists: false}, {numeric: ['>', 0]}]
```

**Comment by man0790** [comment]
> exists: false},

Thanks for reply but no. it working for all conditions. I just want for HIGH or CRITICAL , following also work for all condition, if there is no vulnerability 
`detail:
          finding-severity-counts:
            CRITICAL: [{exists: false}, {numeric: ['>', 0]}]
            HIGH: [{exists: false}, {numeric: ['>', 0]}]`

**Comment by varunreddy6999** [comment]
Yeah, Even I faced the same problem, its working for CRITICAL and HIGH condition but I'm looking for CRITICAL or HIGH vulnerabilities, but no luck in getting that and I have decided to go with Lambda function for filtering events

**Comment by watanabejunya** [comment]
AWS has released enhanced filtering capabilities like `$or` to EventBridge on November 2022.
Document is [here](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-complex-example-or).
Now you can catch events that notify critical OR high OR middle level security vulnerabilities as bellow.

```
{
  "source": ["aws.ecr"],
  "detail-type": ["ECR Image Scan"],
  "detail": {
    "scan-status": ["COMPLETE"],
    "finding-severity-counts": {
      "$or": [
        {
          "CRITICAL": [{
            "numeric": [">", 0]
          }]
        },
        {
          "HIGH": [{
            "numeric": [">", 0]
          }]
        },
        {
          "MEDIUM": [{
            "numeric": [">", 0]
          }]
        }
      ]
    }
  }
}
```
