### ISSUE TITLE
Interactively Upgrade EKS Worker Node

### ISSUE THREAD

**Issue by mrichman** [aws/containers-roadmap#57]
Upgrading EKS worker nodes to the latest version (or to a specific version) should be as easy as clicking a button in the management console, or a single AWS CLI command.

For comparison, ECS offers the ability to upgrade the agent using both the management console and CLI.

**Comment by jaredeis** [comment]
Draining nodes before removing is important for us for this as well. We are working on improving our automation to do this but would be nice if this was part of the worker upgrade process as well.

**Comment by nukepuppy** [comment]
Ditto.. this is real pain point as it's just so ad-hoc/hacky really shouldn't involve interactions with cloudformation  directly (that's AWS problem not mine IMO)

**Comment by christopherhein** [comment]
@mrichman @jaredeis @nukepuppy thanks for submitting this, would you want to this to update the `kubelet` running on the worker nodes in your account in-place or how would you like to see this type of operation happen?

**Comment by jaredeis** [comment]
I don't have enough K8s experience to know if just updating kubelet in-place is best practice, or if draining the node off first would be better. I envision some workflow where for every node that's in the ASG, it replaces them one by one while draining off the obsolete nodes. That's how we are trying to do it right now, but our current solution using SSM and Lambda doesn't seem to work as scale (it times out and the process fails).

**Comment by mrichman** [comment]
I second @jaredeis comments. Whatever the best practice is. My assumption is a rolling update to preserve capacity in the ASG.

**Comment by vincentheet** [comment]
Would be great if the nodes are drained with respect to PodDistrubtionBudgets: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work
Adding a new (updated) node, then draining an old one until all old nodes are updated is a great thing to see happening. The applications keeps available (when more than 1 replica is requested of course) and all the nodes get updated. Then there is no need to worry about downtime anymore.

I agree the current process is way to complex and would involve (a lot of) scripting to make this happening in a sub-optimal way.

**Comment by christopherhein** [comment]
Thanks for that @mrichman and @jaredeis really helpful. If you wouldn't mind as you do go through your updates this was something that was discussed yesterday at the SIG-AWS meeting at KubeCon and brought up by @spiffxp, overall the sig-cluster-lifecycle needs help in discussing the ways people are upgrading their clusters to really get to a prescriptive approach for doing so. 

This means your experiences are incredibly useful, if you could document and make notes and share about what you are doing, and what is working well vs not you will not only help this proposed feature but also will help the Kubernetes community as a whole.

**Comment by christopherhein** [comment]
> Would be great if the nodes are drained with respect to PodDistrubtionBudgets: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work
> Adding a new (updated) node, then draining an old one until all old nodes are updated is a great thing to see happening…

Is this not what you are seeing when you `kubectl drain <node>` as far as I understand it `drain` is supposed to respect the `PodDistrubtionBudgets`? And as long as you `cordon` your old nodes it should be replacing them in place on the new instances.

**Comment by vincentheet** [comment]
@christopherhein @jaredeis yes, you are correct. The drain command respects the PodDistruptionBudgets according to the docs. Would be great if that is supported with an interactive upgrade. To clarify, cordon itself doesn't replace the nodes, it marks them as unavailable for "new" pods.

**Comment by jaredeis** [comment]
I will work up something tomorrow and post the link here. Thanks for listening to customers!

**Comment by christopherhein** [comment]
Of course, thank you for being a part of this!

**Comment by patrickleet** [comment]
with GKE you can just set node pool to autoupgrade to master version, which would be nice

**Comment by mrichman** [comment]
Do you know what strategy GKE uses to perform the upgrade?

**Comment by patrickleet** [comment]
I'm not sure if it has a specific name, but it's a rolling update of the worker nodes, one at a time, within the pool

**Comment by Graham-M** [comment]
We do this at the moment with a combination of:


```
# drop the pods from a node
kubectl drain <node-name>
```  

and then:

```
# remove a node gracefully from the ASG, including 
# allowing it to be removed and drained from the ELB
aws autoscaling \
  terminate-instance-in-auto-scaling-group \
  --no-should-decrement-desired-capacity \
  <instance-id>
```

....and then waiting for all nodes to be in the `Ready` state before we go and trash the next one.

**Comment by nukepuppy** [comment]
I think reviewing just what a kops rolling update does https://github.com/kubernetes/kops/blob/master/docs/cli/kops_rolling-update.md

In theory a button to do the rolling update for KOPS and it would mostly just work (even though there be dragons sometimes ya know)... behind the scenes of what the "button" would do in the context of EKS sounds like its already understood.. but just not wired together - so end users need to wire it up.. but probably not the best experience in end

UX wise.. what seems to be desired.. some command or process issued and the cluster will be in the desired state at the end of it...   

however it's a bit fuzzy.. how much do we want end users to control the nodes? if a lot (for user_data scripts to do monitoring/asset tracking / system users or other processes)  it becomes a double edged sword in a way.

**Comment by jaredeis** [comment]
@jlongtine If we decide to improve the functionality as is, then yes I was going to work on some way to make this more event based. However, I think we are going to have to rethink the whole thing and stand up another ASG and migrate to it. Just have to figure out how to automate that and make our existing pipeline to deploy EKS (and a few other components) still work idempotently.

**Comment by tabern** [comment]
This is partially fulfilled by https://github.com/aws/containers-roadmap/issues/139
Keeping open until upgrades supported in AWS management console.

**Comment by harshal-shah** [comment]
We have implemented a kops like rolling update functionality [here](https://github.com/hellofresh/eks-rolling-update) which works fine for us.

**Comment by mikestef9** [comment]
Support worker node upgrades is now available through the EKS API and Management Console

**Comment by inductor** [comment]
@mikestef9 Hey, why is this on "coming soon" status? :)

**Comment by tabern** [comment]
@inductor our automation missed it! Moving now.
