### ISSUE TITLE
[ECS] [Bug] Message "has reached steady state" doesnt show anymore

### ISSUE THREAD

**Issue by okossuth** [aws/containers-roadmap#582]
Hello

I have a couple of ecs clusters with services using the daemon scheduling strategy. I have noticed recently that when doing a service update the message "has reached steady state" doesnt appear anymore in the events tab of the ecs service on the aws console, only for replica services does. Is this a bug or a change in behaviour?
its happening with ecs agent versions 1.33 and 1.32.1 so far

thanks.

**Comment by fenxiong** [comment]
My findings:
(1) Service with single target group able to reach steady state.
(2) Service with multiple target groups from the same container able to reach steady state. Service events look like this:
```
2019-11-18 09:47:53 -0800
service test-daemon-customer-w has reached a steady state.
2019-11-18 09:42:45 -0800
service test-daemon-customer-w has started 1 tasks: task xxx.
```
(3) (Bug) Service with multiple target groups from different containers not able to reach steady state. The only service event:
```
2019-11-18 09:42:45 -0800
service test-daemon-customer-nw has started 1 tasks: task xxx.
```

**Comment by okossuth** [comment]
Thanks for the update, i hope a fix comes soon! :)

**Comment by coultn** [comment]
We just launched the ability to see service actions as CloudWatch Events:  https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ecs-service-events-now-available-as-cloudwatch-events/

Daemon service events are included in these events.  Please give this new feature a try and see if it addresses your issue.

**Comment by okossuth** [comment]
@coultn Thanks for the update. Although its nice to see this new functionality it doesnt fix or solve the original issue. The ECS service events tab in the AWS console is no longer showing the "XXXX has reached steady state" message, which was very helpful in order to confirm the state of an ECS deployment or autoscaling event. Is there a reason why it was removed or is it just in a pending state in order to be fixed in the near future?

**Comment by DireCorgi** [comment]
Closing this issue as this bug was fixed back in Dec of 2019. Feel free to reach out if this is still an issue.
