### ISSUE TITLE
[EKS] Managed Node Groups Launch Template Support

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#585]
*Launch template support* ability to launch managed nodes using a provided EC2 launch template. This will support multiple customization options for managed nodes including providing custom AMIs and passing user data during node provisioning.

**Comment by ivanmp91** [comment]
will this allow adding node taints for EKS managed node groups?

**Comment by eswarbala** [comment]
This issue has the unintended potential to become a bucket for all features. Let's make sure we track the launch template support separately from other feature requests like custom AMIs, passing user data, tainting nodes during provisioning/editing nodegroups. Launch template should definitely support any feature supported by NodeGroups just in a declarative way.

@ivanmp91 - Can you please open an issue if one doesn't exist for node taints and describe the use case and the expected workflow that needs to support node tainting? I am assuming here that you want nodes to be tainted as part of provisioning / editing nodegroups?

**Comment by ivanmp91** [comment]
Hi @eswarbala ! That's right, I'd like to have nodes tainted as part of the provisioning/editing nodegroups. I'm gonna check if there's any existing issue, otherwise I'll create a new one. Thanks!

**Comment by yann-soubeyrand** [comment]
Will this feature allow adding nodes to NLB target groups?

**Comment by halimwi** [comment]
we have use case to configure forward proxy to the managed worker nodes, looking forward to have this feature released.

**Comment by 0xlen** [comment]
The managed nodegroup currently only allows IAM role with following attached IAM policies:

- AmazonEKSWorkerNodePolicy
- AmazonEKS_CNI_Policy
- AmazonEC2ContainerRegistryReadOnly

It does not support the usage of IAM roles for the nodes without the above managed policies, even though the roles have required capabilities. Supporting this feature as well as can help on doing IAM role customization.

**Comment by AndrewMcFarren** [comment]
Can this feature also support associate public IPs for nodes = false.  Would like to have private subnets of managed nodes (no public IPs) on the nodes.

**Comment by tomiszili** [comment]
Hi all!
I want to use EKS managed nodegroups without automatic public IPv4 and root volume encryption. I modified the launch template genereted by the managed nodegroup, and i changed the default launch template version to the newer one. In the EKS console, now i see that the managed nodegroup is `DEGRADED` so no longer managed by EKS `The Amazon EC2 Launch Template : lt-*** has a new version (2), which is not managed by AWS EKS.`

My questions are:
This degraded nodegroup will be updated if there is a new AMI?
Do you have any workaround for this problem?

thanks

**Comment by ravisinha0506** [comment]
Update version ( update-nodegroup-version api ) is disallowed if the Launch Template of the ASG has been modified since customer changes are not guaranteed to be sticky after our upgrade. 

To be able to perform update and upgrade operation on the node group, kindly revert the manual changes made on the node group resources. 

Thanks

**Comment by llamahunter** [comment]
When using IAM Roles for Service Accounts (IRSA), the best practice describe in https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html is to edit the launch config user-data of the worker node to use iptables block docker container access to the metadata server.  When we were running self managed worker nodes, we had this configured in the user-data. The managed worker nodes don't seem to do this on their own (they really should, no?), and there's no way to add it via existing EKS managed worker node apis.

**Comment by jhoule-splice** [comment]
Hey all,
I see that this is on the roadmap but as of the last update it doesn't look like there was a timeline set. Has there been any movement on this one? We are hoping to use the launch template to push traffic to a proxy in a secured internal only environment.

Thanks

**Comment by mikestef9** [comment]
Hi @jhoule-splice we are working on this feature, but as per the roadmap [guidelines](https://github.com/aws/containers-roadmap#faqs), we can't share specific timelines in this forum.

**Comment by llamahunter** [comment]
Will this support tagging of ec2 instances launched by managed worker node groups?  https://github.com/aws/containers-roadmap/issues/608

**Comment by mikestef9** [comment]
Managed node groups now supports EC2 launch templates! See the launch [blog](https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/) and EKS [documentation](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html) for more details

This launch addresses the following feature requests, and these issues will be closed soon:

- Custom security groups #609 
- Custom user data #596 
- Tagging EC2 instances #608 
- Custom AMIs #741 
- Volume configuration and encryption #665 #719 
- Changing instance types #746 

Excited to see all the use cases this unlocks for applications running on managed node groups, and as always, we welcome your feedback!

**Comment by os-virtualretail** [comment]
Great feature! Congrats
