### ISSUE TITLE
[EKS] [request]: Managed Node Group creation from CloudFormation

### ISSUE THREAD

**Issue by tomiszili** [aws/containers-roadmap#589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
CloudFormation ability to make managed node groups within the EKS creation.

**Which service(s) is this request for?**
EKS

**Comment by tabern** [comment]
Cloudformation documentation for EKS Managed Node Groups is now published – https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html

**Comment by devkid** [comment]
@tabern This URL redirects me to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html

**Comment by mikestef9** [comment]
Link is live now
