### ISSUE TITLE
Add Monitoring Section to EKS User Guide

### ISSUE THREAD

**Issue by mrichman** [aws/containers-roadmap#61]
The [EKS User Guide](https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html) has no information on monitoring the cluster using CloudWatch or other tooling.

This documentation could detail the installation and configuration of Fluentd for log aggregation into Cloudwatch Logs, as well as Prometheus and Grafana installation.

I realize the latter two are not AWS-specific, but are probably common enough use cases to include in the product documentation.

**Comment by pawelprazak** [comment]
Maybe consider `filebeat`, `logstash` (on EKS) and the hosted ElasticSearch with Kibana for logging instead of Fluentd and Cloudwatch.

**Comment by ffjia** [comment]
@pawelprazak why use `filebeat` instead of `fluentd`?

**Comment by pawelprazak** [comment]
I have bad experience with running fluentd

wt., 23 lip 2019, 04:36 użytkownik Feifei Jia <notifications@github.com>
napisał:

**Comment by whereisaaron** [comment]
@mrichman there are fairly good instructions for on the eksworkshop website for deploying Fluentd with Cloudwatch, Elasticsearch, and Kibana.
https://eksworkshop.com/logging/

Many log tools are possible, but we always use `fluentd` with Kubernetes for its excellent, structured Kubernetes metadata. It has always been reliable for us.

**Comment by Bessonov** [comment]
May be relevant: https://docs.aws.amazon.com/eks/latest/userguide/logging-monitoring.html (and links inside)

**Comment by mickeypash** [comment]
I had collected a handful of resources:
- !! [EKS Container Logging FluentBit - AWS Blog](https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/)
- [Fluent Bit Kube Logging](https://github.com/fluent/fluent-bit-kubernetes-logging/) - this repository has the most uptodate examples of how to configure Fluent Bit.
- [Nginx to S3 via Fluentd](https://docs.fluentd.org/v/0.12/articles/recipe-nginx-to-s3)
- [AWS for FluentBit Images](https://github.com/aws/aws-for-fluent-bit#public-image)
- [EKS with CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html)

- [Containter Insights setup logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html)

**Comment by andyfeller** [comment]
> @mrichman there are fairly good instructions for on the eksworkshop website for deploying Fluentd with Cloudwatch, Elasticsearch, and Kibana.
> https://eksworkshop.com/logging/
> 
> Many log tools are possible, but we always use `fluentd` with Kubernetes for its excellent, structured Kubernetes metadata. It has always been reliable for us.

@whereisaaron : good to know.  that said, @pawelprazak has a point that `filebeat` is a solution that many AWS customers do use especially in a hybrid play and [supports autodiscover with kubernetes](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html#_kubernetes), so it would be good to extend the olive branch here despite recent holy war.

**Comment by tabern** [comment]
EKS now has a multiple resources and native integrations for monitoring. Closing this issue as it is resolved and stale.

EKS documentation resources for monitoring:
1. [Observability in the EKS User Guide](https://docs.aws.amazon.com/eks/latest/userguide/eks-observe.html)
3. [AWS Managed Service for Prometheus](https://docs.aws.amazon.com/prometheus/latest/userguide/what-is-Amazon-Managed-Service-Prometheus.html)
4. [CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-EKS.html)
5. [AWS Prescriptive Guidance for EKS monitoring](https://docs.aws.amazon.com/prescriptive-guidance/latest/implementing-logging-monitoring-cloudwatch/amazon-eks-logging-monitoring.html)
