### ISSUE TITLE
.NET Core Memory Leak in Fargate Containers

### ISSUE THREAD

**Issue by cmpcdaly** [aws/containers-roadmap#613]
For the past weeks, I've been struggling with trying to diagnose a memory leak in several of our production APIs. I tried to replicate the leak locally (both on a Windows machine and on a docker container running similar parameters to our production Fargate containers) but I can't seem to reproduce it at all.

As the only environment on which I can replicate this is a Fargate container, I packaged [dotnet-dump](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md) with the container image and had planned to invoke this from the dotnet process itself and then export the dumps to S3. Unfortunately, dotnet-trace [requires the SYS_PTRACE capability](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md#using-dotnet-dump) and as far as I can tell, this is [not available on Fargate](https://github.com/aws/containers-roadmap/issues/409).

I tried to replicate the memory leak on an ECS environment running on EC2 to no avail. I had my suspicions about what may be causing this, potentially the underlying host used by Fargate is causing the garbage collector to act in a way which causes or accelerates this leak. I've tried tuning the garbage collector with configuration environment variables but nothing seems to work.

It's really frustrating to not be able to gain access to any tracing for the process in the only environment in which it exhibits this problem, which also happens to be our production environment. Is there any way in which I can replicate this environment exactly, or is there a possibility I could run the container with SYS_PTRACE capabilities?

Many thanks.

**Comment by chucky2305** [comment]
We are facing similar problems. Any updates from the team on this would be very appreciated.

**Comment by cmpcdaly** [comment]
So long story short - this wasn't a problem with Fargate at all, it was a memory leak in my own code which was difficult to replicate outside of a production environment. In the end, I downloaded the XRay request logs over a 24 hour period from one of our APIs and replayed them locally, replicating the memory leak. It would still be useful to have these tracing capabilities on our production environment though.

In case you're interested (and on the off chance you have the same problem) my code was overloading the Entity Framework query compilation cache. It dynamically generates query expressions based on request parameters, but was using constant expressions for query values which meant that EF couldn't parameterise the SQL queries (and thus, was using embedded constants for values in queries). The fix was to 'capture' the query values so that they could be parameterised.

**Comment by nrvmodi** [comment]
I have a same problem in java microservices deployed on ecs fargate. I couldn't find the reason
