### ISSUE TITLE
[Amazon Linux] [request]: Add containerd to yum repos

### ISSUE THREAD

**Issue by kekoav** [aws/containers-roadmap#614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Add Containerd to the AmazonLinux yum repositories. This issue relates to #313. 

**Which service(s) is this request for?**

Amazon Linux Yum Repository

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Amazon Linux is the recommended base AMI for EKS. In order to install containerd on Amazon Linux, we are required to build our own containerd. Managing security patches, and updates of this package become burdensome and each AMI builder will need to perform this manually. It is a much better experience for this to be built into the Amazon Linux yum repository.

**Are you currently working around this issue?**

Build containerd via another means and installing it.

**Additional context**

Issue #313 is an issue larger in scope, this issue is just for the Amazon Linux piece which is useful on its own (even outside EKS).

**Comment by samuelkarp** [comment]
containerd 1.2.6 is currently available in the main Amazon Linux 1 repository and in the Amazon Linux 2 [`docker` Extra](https://aws.amazon.com/amazon-linux-2/faqs/#Amazon_Linux_Extras).

You can install containerd on Amazon Linux with the following command:

```
$ sudo yum install containerd
```

You can install containerd on Amazon Linux 2 with the following commands:

```
$ sudo amazon-linux-extras enable docker
$ sudo yum install containerd
```
