### ISSUE TITLE
[EKS/Fargate] Savings plan for EKS with Fargate

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#616]
Support for Savings Plan when using EKS with Fargate

**Comment by mikestef9** [comment]
This is live! See the [what's new](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-fargate-aws-eks-included-compute-savings-plan/) post and [blog](https://aws.amazon.com/blogs/containers/saving-money-pod-at-time-with-eks-fargate-and-aws-compute-savings-plans/) for more details.
