### ISSUE TITLE
[EKS/Fargate] NLB support for EKS with Fargate

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#617]
Support for service load balancing with AWS Network Load Balancer to Fargate pods when using EKS.

**Comment by mhausenblas** [comment]
See also #981

**Comment by mikestef9** [comment]
Happy to announce you can target pods running AWS Fargate using Network Load Balancers. See links below for more details.

- [What's New](https://aws.amazon.com/about-aws/whats-new/2020/10/introducing-aws-load-balancer-controller/)
- [Launch Blog](https://aws.amazon.com/blogs/containers/introducing-aws-load-balancer-controller/)
- [Documentation](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html)

An important note is that NLB IP targeting is provided by the new AWS Load Balancer Controller, which you need to first install in your cluster. To use a service of Type=LoadBalancer in NLB IP mode, you need to be running a 1.18 EKS cluster. For earlier clusters, you can still achieve NLB IP targeting, but you need to keep the service as type NodePort, while adding the "nlb-ip" annotation to your service.
