### ISSUE TITLE
[EKS]: Support for EC2 Inf1 Instances

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#619]
EKS support for recently launched EC2 Inf1 instance types based on AWS Inferentia chips

**Comment by dmegyesi** [comment]
This machine type would be super interesting for our use case. Is there any specific reason they can't be used in EKS as of today?

Is there a ballpark estimate on when they will be available?

**Comment by mikestef9** [comment]
@dmegyesi could you provide any more details on your use case?

You can follow the [DIY instructions] (https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/tutorial-k8s.md). You need to make sure you are using [version 1.6.0](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0) of the VPC CNI plugin.

We are working on making this easier to consume with EKS, by updating the [EKS GPU AMI](https://docs.aws.amazon.com/eks/latest/userguide/gpu-ami.html) with native support for Inferentia.

**Comment by dmegyesi** [comment]
@mikestef9 thanks a lot for this heads-up, this is already a good-enough solution to start :) I was not aware of this DIY documentation.

We're heavily investing on EKS for our data processing batch jobs and now the next step is to add machine learning support. Investigating the machine types and special requirements for GPU support on EKS, the Inf1 machine type came up and seems like a potentially very interesting thing to test.

**Comment by mikestef9** [comment]
EKS now officially supports EC2 Inf1 instances, see the EKS documentation below

https://docs.aws.amazon.com/eks/latest/userguide/inferentia-support.html

Additionally, we plan to publish a blog with more info in the coming weeks.
