### ISSUE TITLE
[ECS] [request]: Fargate resolve limitation for accessing to kernel settings

### ISSUE THREAD

**Issue by KursLabIgor** [aws/containers-roadmap#623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
 Give access to some kernel settings, or increase by default these values for modern app frameworks
```
net.core.somaxconn – The maximum number of connections that can be queued for acceptance by NGINX. The default is often very low and that’s usually acceptable because NGINX accepts connections very quickly, but it can be worth increasing it if your website experiences heavy traffic. If error messages in the kernel log indicate that the value is too small, increase it until the errors stop.
nofile – The user file descriptor limit, set in the /etc/security/limits.conf file
``` 
**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are using Fargate for host microservices and part of api service we use python + flask application which under the hood use uWSGI. And the biggest problem that we cant hold high connections due limitation in accessing to kernel settings. We cant access to such parameter like sysctl -w net.core.somaxconn=1024. it will gives ability increase backlog connections.

**Are you currently working around this issue?**
trying use https://www.nginx.com/products/nginx-unit/
no luck

**Additional context**
seems like workaround it is use EC2 launch type. :(

**Attachments**
when connection backlog has reached limit, by default it is only 100 connections you will such error 
`2019/12/04 09:05:29 [error] 13#13: *17013 connect() to unix:/tmp/uwsgi.socket failed (11: Resource temporarily unavailable) while connecting to upstream, client: 10.0.7.105, server: localhost, request: "GET /api/v1/ping HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.socket:", host: "****"`

**Comment by mettacrawler** [comment]
The nofile ulimits are configurable but you must edit the json directly.
See https://github.com/SonarSource/docker-sonarqube/issues/282#issuecomment-508507407

**Comment by BNMetrics** [comment]
Any news on this?
It'd be really nice to have `systemControls` available on FARGATE container too. Especially when `ulimits` is available.

**Comment by Paritosh-Anand** [comment]
+1 unable to move handful of our resources to Fargate due to this limitation. 
Hoping this to be picked in the roadmap soon.

**Comment by meysam81** [comment]
This seemed possible from `ulimits` but I wasn't able to pull this through using `nofile` [ref](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html#container_definition_limits)

**Comment by marvelph** [comment]
I face the same problem.
At the moment, we have no choice but to secure a large number of instances.

**Comment by ollypom** [comment]
AWS Fargate now supports kernel parameter configuration (sysctl) for Amazon ECS tasks, including setting the Task `net.core.somaxconn` discussed in this issue. 

To learn more about the launch see:

- [What’s New Post: AWS Fargate supports PID namespace and kernel parameters configuration](https://aws.amazon.com/about-aws/whats-new/2023/08/aws-fargate-pid-namespace-sharing-kernel-configuration/)
- [AWS Tech Blog : AWS Fargate supports additional linux controls for Amazon ECS tasks](https://aws.amazon.com/blogs/containers/announcing-additional-linux-controls-for-amazon-ecs-tasks-on-aws-fargate/)
- [Documentation: ECS task definition parameters](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)
