### ISSUE TITLE
[EKS] [request]: Managed Node Groups - security groups

### ISSUE THREAD

**Issue by christiangda** [aws/containers-roadmap#624]
**Tell us about your request**
Recently I'm working with "EKS Managed Node Groups", it is a nice solution, but, I don't understand why you don't allow the possibility to add additionals Security Groups to nodes?

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

You only allow SSH access to nodes through one security group provided by the client (I supposed in case you are using a Bastion Host) or 0.0.0.0/0.  

but, Cases:
1) What happens if I control the access to my resources into a VPC with a "special remote access Security Group" with all the IPs/CIDR protocols/ports and every time a created a resource inside a VPC attach this SG? following the best practice of "less is better" or "manage exactly what you want" and not 0.0.0.0/0

2) What happens if my bastion host is in another VPC close to EKS VPC (same account and connected through peering/TGW)?, how can I get access to my nodes without put 0.0.0.0/0?

3) What happens if I want to use k8s "nodeport" service to test my microservices in a "development environment" without the use of private "Load Balancer"?, and additionally I'm accessing from my office location through:
 VPN (office) <--> TGW (shared services account vpc) <--> EKS (product development account vpc) using the case 1 above where I have a "Special SG with all my CIDR and ports" 

Of course, I know that I can go to SG you created automatically and add all the rules what we need, but what if we use only IaC using Cloudformation how can I reference this SG?

Case 3 is the worst, anybody can't get access to the "nodeport"s from outside AWS in a private way if you want to implement all your infrastructure using Cloudformation (use of Custom::Resource -->lambda is not a good way).

**Are you currently working around this issue?**
- Using Cloudformation "Custom Resources" to modify the security groups in the  "Launch Template" that you created and add the new one I want
or 
- Going through the web-console and modify the "Launch Template manually to add all the SG what we want and then manually terminate the old instance to launch the new instances with the new SGs"

**Additional context**
We are using Cloudformation to build our IaC and AWS Service Catalog to deploy it.

We have some king of "hierarchy" using "Fn::ImportValue" in the following order:

1 - One SC product for EKS VPC (tags, R53 Resolver Inbound, etc)
2 - One SC product for Base Security Groups ( Basically, clean SGs)
3 - One SC product for Ingress Security Groups over the Base Security Groups.
4 - One SC product for Control Plane
5 - One SC product for Data Plane which import values from Control Plane Stack and the others

And of course, we don't want to do any kind of task in a "manually" way to get a fully functional cluster ready to use.

**Attachments**
Our Cloudformation data-plane template with the lines we want to use commented

[eks-data-plane.txt](https://github.com/aws/containers-roadmap/files/3922326/eks-data-plane.txt)

**Comment by adonley** [comment]
I've terminated used the same work arounds as listed above, but my managed nodes go into a degraded state since the Launch Template isn't managed by EKS.

**Comment by mikestef9** [comment]
Closing as this is a duplicate of #609
