### ISSUE TITLE
[ECS] [request]: Support network metrics for awsvpc containers

### ISSUE THREAD

**Issue by briancurt** [aws/containers-roadmap#628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please, add support (potentially via Container Insights?) to gather and view network metrics for services/containers using the `awsvpc` networking mode.

**Which service(s) is this request for?**
ECS, CloudWatch.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to monitor the network status for my ECS containers effectively. I would believe that I can monitor the ENI cards individually at the EC2 network stack and somehow map them to the corresponding ECS service, but this doesn't sound effective (if even possible). There should be a way to easily view container network metrics similar to those shown when using the `bridge` network mode. 

**Are you currently working around this issue?**
In progress/No solution found so far.

**Comment by lifeofguenter** [comment]
This is especially crucial for Fargate as we do not have EC2 metrics.

**Comment by mlanner-aws** [comment]
Launched today: https://aws.amazon.com/about-aws/whats-new/2020/04/aws-fargate-launches-platform-version-14/

**Comment by pavneeta** [comment]
This feature was shipped see documentation here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-container-insights.html
