### ISSUE TITLE
[ECS] Support for updating parameters of an ASG capacity provider

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#633]
ASG capacity providers are currently immutable objects.  With this proposed change, we will add the ability to change the managed scaling, target capacity, and managed termination protection settings on an ASG capacity provider.

**Comment by pauldraper** [comment]
Excellent!

Whoever created the error message for duplicate capacity provider certainly thought this was possible; I am glad they will eventually be correct:

> The specified capacity provider already exists.
> To change the configuration of an existing capacity provider,
> **update the capacity provider.**

**Comment by coultn** [comment]
Thanks for pointing this out, we will change the error message until such time that the update API is launched.

**Comment by jdb1441** [comment]
Very excited for this functionality! Given the complicated formula that CP's use to determine the desired count, having the ability to tweak this to find the proper level for the workload will greatly improve the usability of this tool.

**Comment by Hobbit44** [comment]
I would like to add to this the ability to change some of the policy settings as well? In my case im after the instance warm up. The ECS optimized image take a lot less than 5 minutes to start up and it would mean i could scale significantly faster.

**Comment by martincad** [comment]
Yes, please. Need to be able to change the Warm up time (300 seconds is a lot). IS there any way to change it using the Cli ?

**Comment by fspaniol** [comment]
Any updates on this?

**Comment by softwarevault** [comment]
Delighted to know this is WIP. It would be very welcomed to be able to change the target number of the capacity provider in a prod environment. It's my most frustrating encounter in AWS to date, everything usually is so flexible and awesome. Look forward to capacity providers keeping that high standard.

**Comment by anoopkapoor** [comment]
UpdateCapacityProvider API is now available:
https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ecs-capacity-providers-now-support-update-functionality/

Also, both the CreateCapacityProvider and UpdateCapacityProvider APIs support specifying a customer instance warm-up time:
https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ecs-cluster-auto-scaling-now-supports-specifying-a-custom-instance-warm-up-time/
