### ISSUE TITLE
[ECS] Full support for capacity providers in the ECS console

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#634]
Currently, there are some aspects of capacity providers that cannot be accessed through the ECS Console, including:
* using a capacity provider strategy other than the default capacity provider strategy when running tasks and creating services
* updating a service to use a new capacity provider strategy
* detaching capacity providers from a cluster

The changes proposed in this issue will add support for these features in the console.

**Comment by jrobison-sb** [comment]
Would this issue encompass specifying a capacity provider when launching a task via a Cloudwatch Event Target? For example, if I wanted to [do this](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatch-Events-tutorial-ECS.html), and as part of doing so, I wanted to use a Cloudwatch Event input transformer to specify a capacity provider strategy.

It would be nice to get such an ability, either as part of this issue or separately.

**Comment by anoopkapoor** [comment]
The following are now available in the ECS console:
- using a capacity provider strategy other than the default capacity provider strategy when running tasks and creating services
- updating a service to use a new capacity provider strategy
- deleting a capacity provider
