### ISSUE TITLE
[EKS/Fargate] [request]: See running Fargate nodes on console

### ISSUE THREAD

**Issue by tomiszili** [aws/containers-roadmap#640]
**Tell us about your request**
What do you want us to build?
Add functionality to the EKS Management Console to see the running Fargate "nodes" on EKS, as the EKS managed worker nodes.

**Which service(s) is this request for?**
EKS, Fargate

**Comment by tabern** [comment]
Can you explain why you would want to see this?

Fundamentally, Fargate is a serverless compute engine for containers. This means that while 'nodes' show up in kubectl today, they are representative of running kubelets, not actual VM resources. There are actually no node resources in Fargate to display!

**Comment by tomiszili** [comment]
I understand your point, it was just an idea.

It would be nice to see if there are any Fargate engine consumed or some info/monitoring about them, like in Lambda you can see recent invocations, duration etc. 
For example a graph of the consumed vCPUs and memory by Fargate profiles in time under the current EKS cluster which uses that Fargate profile to see what you billed for.

**Comment by tabern** [comment]
@tomiszili that's a great idea. Would you mind if we edited this request to match? I agree that being able to monitor actual Fargate pod utilization vs. request and then group at the profile level would be super useful.

**Comment by tomiszili** [comment]
@tabern i dont mind if you edit the original request. Thanks!

**Comment by Sceat** [comment]
This could be related to #942 with the ability to see on the console the resource usage

**Comment by tabern** [comment]
Should be solved as part of #135

**Comment by tabern** [comment]
You can now see Fargate nodes in the AWS console! Closing this as part of #135.

![image](https://user-images.githubusercontent.com/26726164/100773323-8f3a6c80-33b5-11eb-8c57-32877c1ef7f7.png)
