### ISSUE TITLE
[EKS] [bug] Clusters in the listing page remain stuck in the "loading" state

### ISSUE THREAD

**Issue by cPu1** [aws/containers-roadmap#642]
I noticed an issue with the EKS cluster listing page: https://us-west-2.console.aws.amazon.com/eks/home?region=us-west-2#/clusters

If we have more than a page's worth of clusters (> 10), and navigate to the next page, the status field remains stuck in the loading state. I saw that no HTTP requests are made upon clicking on a different page, so that might be an issue.

![image](https://user-images.githubusercontent.com/6298307/70541412-fa7ba500-1b8c-11ea-9338-08e9667e3509.png)

**Comment by mikestef9** [comment]
This has been resolved
