### ISSUE TITLE
[ECS] [request]: Expose propagateTags setting to ecs update-service

### ISSUE THREAD

**Issue by ealeatherman** [aws/containers-roadmap#647]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
It would be helpful to be able to update the tag propagation setting of an existing ECS service. Currently if we want to change how tags get propagated we have to re-create the service since this particular setting is not exposed for the ecs update-service CLI command or via the console. 

Ideally we could make this change in the console via Update in the ECS Service in question, and/or using the update-service CLI command either with a CLI option or just json input. The tag propagation change could take place the next time a deployment happens, or even forcing a new deployment would be better than needing to re-provision the service completely.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently we are working on our tagging and billing strategies organization wide, and this had led to periodic changes to how we want to tag resource. As the tagging propagation settings for ECS currently exist, we have to plan to bring the service down and re-provision it, OR explicitly tag the tasks after each deployment. It would be logical to be able to update the tag propagation setting and have it fix itself then the next time a deployment happens, if/when we run into similar situation in the future.

**Are you currently working around this issue?**
Manually fixing tags on tasks, or possibly developing a step to automate this after each deployment

**Additional context**
I felt like while this is a pretty low priority item, it seems like a logical thing that should be available at least through the CLI.

**Attachments**

**Comment by xzp1990** [comment]
My customer also have the same requirement.  They have over 300 services, and it's too cost for them to re-create all those services if they want to enable those tags.

**Comment by bassrock** [comment]
Encountering the same issue. Removing and re-creating services to add tag propogation is very costly, especially if the service is currently exposed to the web and required to be live.

**Comment by SrWildman** [comment]
Want to follow up on this. Recreating the service is not an option but we very much need to update the propagate tags option.

**Comment by tarfeef102** [comment]
Yes, we specifically would like to update this setting to allow us to enable ECS Exec using condition keys based on tags, and downtime is never a good thing, or even possible in some cases.

**Comment by tarfeef102** [comment]
Quarterly "where is the attention for this pretty small but useful feature" nag

wish we had a maintainer we could tag in here, the current assignee is (according to their GH) not even at amazon anymore, that doesn't inspire much confidence

**Comment by rmetcalf9** [comment]
I have come up against this issue as well. Facing the complicated process of creating a new service and switching traffic over on a busy production system. It would be great to be able to use the update API to just change the value to what we require.

**Comment by gauravprachchhak** [comment]
This is very scary but should not have to be. Any support is appreciated!

**Comment by junedkhatri31** [comment]
I have written a small script which will re-create the service and add `propagateTags` to `SERVICE`.
Python script - https://gist.github.com/junedkhatri31/29cccac0aea40b2fbf45f5cdbdf603fb

**Comment by AbhishekNautiyal** [comment]
Amazon ECS UpdateService API now supports updates for the following parameters: loadBalancers, propagateTags, enableECSManagedTags, and serviceRegistries; see what's new post for details:

https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ecs-service-api-updating-elastic-load-balancers-service-registries-tag-propagation-ecs-managed-tags/
