### ISSUE TITLE
Replicated volume

### ISSUE THREAD

**Issue by runningman84** [aws/containers-roadmap#65]
**Tell us about your request**
Build us a feature where you would have a volume running in two or more az where only one az can be active and the other read only. This would mean that in case of an az outage the volume could still work in another az. Azure has some similar feature...

**Which service(s) is this request for?**
ECS, EKS, EC2

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Right now if an az goes down or you do not have any node running in a specific az your container won't be startet again. This is bad for application like jenkins where you only have a single pod which needs to be running all the time.

**Are you currently working around this issue?**
Snapshotting and Restore

**Additional context**
Anything else we should know?

**Comment by FernandoMiguel** [comment]
https://aws.amazon.com/about-aws/whats-new/2018/07/amazon-efs-now-supports-provisioned-throughput/

**Comment by pierreozoux** [comment]
@runningman84 but for databases, you have RDS? The problem with Jenkins is not that EBS is not cross AZ or EFS slow, it is just an old piece of software.
Jenkins should read configuration from environment and/or database, store artifact in s3.
My company has the same problem, they want a fast EFS.. I keep telling them, make your application cloud native. But yeah, maybe at the end they are right, it would just be easier to have a fast EFS :)

**Comment by uprightvinyl** [comment]
FYI - This is something GKE has in Beta at the moment; https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#regional_persistent_disks

**Comment by abby-fuller** [comment]
hey!  this actually belongs with the EBS team -- we've passed this on to them!

any information on your usecase is still helpful, so feel free to add it here and we'll keep passing it on!

you can also send usecases to abbyfull@amazon.com
