### ISSUE TITLE
[ECS] Support for FSx for Windows in ECS on EC2

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#651]
Similarly to our upcoming support for EFS, we are considering support for FSx for Windows filesystems within an ECS task definition.  This would only be available on ECS on EC2 and Fargate does not support Windows containers at this time.  A sample task definition may look like the following (subject to change as we work on the design):

```json
{
    "family": "my-task-with-fsx",
    "volumes": [
        {
          "name": "myFSxVolume",
          "FSxWindowsVolumeConfiguration": {
                "filesystem": "fs-1234"
            }
        }
    ],
    "containerDefinitions": [
        {
           "name": "container-using-fsx",
           "mountPoints": [
               {
                   "sourceVolume": "myFSxVolume",
                   "containerPath": "/mount/fsx",
                   "readOnly": true
               }
        ]
    }
   ]
}

**Comment by melaraj2** [comment]
Any guidance on timelines on this?

**Comment by pavneeta** [comment]
This feature is now generally available:
AWS What's New Post : - https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ecs-supports-use-of-amazon-fsx-windows-file-server/ 
Blog post : https://aws.amazon.com/blogs/containers/using-amazon-fsx-for-windows-file-server-as-persistent-storage-on-windows-containers/
