### ISSUE TITLE
[ECR] [request]: Update ECR Container scanning to support alpine-based images

### ISSUE THREAD

**Issue by adamcrosby** [aws/containers-roadmap#662]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
ECR container scanning that supports Alpine based images.  Clair upstream has added this functionality (see https://github.com/quay/clair/commit/d62bddd6e382946b768fe5c81f49a23699d28cef for commit closing open Clair upstream issue).

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Using alpine for smallest possible container sizes, and would love to use integrated ECR scanning for vulnerabilities.

**Are you currently working around this issue?**
Running a private instance of Clair?

**Additional context**
N/A

**Attachments**
N/A

**Comment by BramWithaar** [comment]
According to the docs ECR supports Alpine right now: https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.html
Scanning of a Alpine based container also works (no 'UnsupportedImageError' anymore).
