### ISSUE TITLE
[EKS] Support for Managed nodes AMI encryption

### ISSUE THREAD

**Issue by mbig** [aws/containers-roadmap#665]
Can the EKS managed node AMI be encrypted? Is there a plan for this to be supported down the road?

**Comment by mgarber-ops** [comment]
FYI @mbig much like you pointed out the service doesn't formally offer encryption on the nodes however you can enable the following as a workaround which will cover encryption of the *root* volumes:

https://docs.aws.amazon.com/cli/latest/reference/ec2/enable-ebs-encryption-by-default.html

**Comment by mikestef9** [comment]
Closing as this feature request is addressed by launch template support. See #585 for details!
