### ISSUE TITLE
[EKS] [request]: support s3 csi driver

### ISSUE THREAD

**Issue by Missshao** [aws/containers-roadmap#667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support s3 csi driver , it will be benefit the share data in different pods

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by stpolar** [comment]
I need this feature

**Comment by leakingtapan** [comment]
fsx-csi-driver is able to create a file system that is backed by s3 bucket. Have you tried fsx-csi-driver? Could you provide more details about what are you looking for from a separate s3 csi driver ?

**Comment by Kaizhe** [comment]
My request is beyond the s3 csi driver which just turns out s3 csi may be the solution: authorize services accessing to data at data storage mounting stage when service is up.

**Comment by dims** [comment]
Please see https://github.com/awslabs/mountpoint-s3-csi-driver
