### ISSUE TITLE
Double some ECS default service limits

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#67]
* Increase the default number of clusters per Region, per account from 1,000 to 2,000.
* Increase the default number of container instances per cluster from 1,000 to 2,000.
* Increase the default number of services per cluster from 500 to 1,000.
* Update the public Amazon ECS service limits documentation at https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_limits.html

**Comment by tabern** [comment]
Shhiped
