### ISSUE TITLE
EKS: DNS resolution for EKS Private Endpoints

### ISSUE THREAD

**Issue by YakobovLior** [aws/containers-roadmap#671]
Hello,

I have an issue with the private endpoint DNS resolution.
I have read that since December 13, (https://github.com/aws/containers-roadmap/issues/221), if you start a new cluster private endpoint DNS resolution should work automatically as long as you have the matching VPC settings.
So I have raised a new cluster but still I cannot resolve the cluster endpoint from my desktop which is connected to the VPC network (I can spin up an EC2 machine, SSH it and access the cluster from it but I need to have access from desktop as well).

Is there anything else that I miss in order to make it work? 
The post says "Clients (such as the kubectl CLI tool) use the public endpoint as a DNS resolver to connect to the private endpoint through a peered VPC automatically" which I didn't fully understand how can it use the public endpoint if it is not exist.

Thanks in advance,
Lior

**Comment by YakobovLior** [comment]
So I managed to get it work, I saw in the documentation that in order to make it work the cluster should had public access at least once so because I created the cluster with private access only, enabling and disabling the public access solved this issue.
But now I'm encountering another issue, looks like the DNS is not resolvable at first time after a while without access (attached screenshot).
What can be the cause for it? this is problematic in CD terms since cluster address is not always available and may fail the pipeline.

Thanks,
Lior

**Comment by mikestef9** [comment]
@YakobovLior can you provide more details, when and how did you create the cluster? Can you share account id and cluster name? For new clusters there is no need to toggle public/private settings in order for this feature to work

**Comment by YakobovLior** [comment]
Hey @mikestef9,
so at first we created the cluster at November, so I read the article about automatic DNS resolution which was released December 13, so instead of waiting for update I have deleted the cluster and re-created it a couple of days ago.
I created it through the console without choosing public access at first. but as I read somewhere that enabling and disabling public access might solve the issue I tried it and it did partially helped.
So now the state is that on first access DNS is not resolvable but on next try it is working:
![image](https://user-images.githubusercontent.com/33580144/71616442-f86e9a00-2bbe-11ea-9147-2f84182c8c1e.png)

account number - 386841365970, cluster name - threatcloud-dev-eks

Thanks,
Lior

**Comment by sgundapu** [comment]
@YakobovLior, looks like right now the dig is working as expected, it does show the private IPs in the "ANSWER SECTION" when the endpoint is resolved and the cluster configuration seems to be public false and private true, looks like the cluster was created with this configuration and toggled to enable public and then disable public again. 

Something to keep in mind is negative caching by the DNS servers, today if you ping/resolve the endpoint when the toggle is going on it is possible to cache the response and keep it for 15 minutes. 

One way to check that is by doing a dig on the endpoint something like "dig <endpoint without the https part>" if this returns a response with status NXDOMAIN it is a indicator that it might be a cached response. Also, we are working on reducing the negative cache time to a minute from 15 minutes.

**Comment by YakobovLior** [comment]
Hey @sgundapu,
I have tried to follow your instructions but I couldn't exactly understand the output.
I didn't saw any NXDOMAIN status in dig output, but still from my desktop environment first ping was unsuccessful and then second time was able to resolve the DNS.
This issue is not occurring in linux environment for exmaple, only from my windows desktop.

Do you say it might be related to the fact that I have created the cluster without public access,
but later on enabled public access and then disabled it again?

Thanks,
Lior

**Comment by sgundapu** [comment]
@YakobovLior it should not be related to the way cluster was created. If you have a route to your VPC from where ever you are running the ping it should work ideally. What you are describing sounds like a issue with not being able to establish a route to the api server. But as far as resolving to private IPs if you see the output as part of the dig that would mean the DNS is resolving to private IPs but you are probably not able to connect to it.

**Comment by YakobovLior** [comment]
Hey @sgundapu,
so after few more checks it looks like this issue is occurring only from my Windows desktop and not I cannot reproduce it from Linux environment for example so I believe the issue is related with our specific DNS server.

Thank you for the assistance,
Lior

**Comment by cyrus-mc** [comment]
When provisioning the private endpoint EKS randomly picks which subnet (of all the subnets assigned to the cluster) in which to provision. 

As you assign both public and private subnets (so that EKS can tag them accordingly and then Kubernetes can create external and internal ELB) EKS ends up creating the private endpoint in the public subnet (in my case).

This causes a problem in my situation as public subnets are not routeable over our DX. Even if it were I think the private endpoint should be placed within the private IP space not public as that opens it up to possible external access.

**Comment by KIVagant** [comment]
I feel we should create a separate ticket since the issue (summarized by @cyrus-mc) is affecting more and more people.
