### ISSUE TITLE
[ECS/Fargate] [request]: Support pidMode: task on Fargate

### ISSUE THREAD

**Issue by deuscapturus** [aws/containers-roadmap#676]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Containers in ECS Fargate tasks cannot share namespace leaving out the possibility of using support containers in tasks for diagnostics, logging, debugging.

Specifically needed is `pidMode: task` and `ipcMode: task`

**Which service(s) is this request for?**

ESC Fargate

**Are you currently working around this issue?**

I have no workaround.  I'm unable to actively debug processes in Fargate containers in any way.

**Comment by alexcmms** [comment]
This is something we're actively working on (we've updated the status to "Coming Soon" rather than "Proposed"). In an upcoming release we'll make it possible to enable task level PID mode.
