### ISSUE TITLE
[EKS] [request]: Selecting subnets where to provision private EKS endpoints

### ISSUE THREAD

**Issue by asmontas-i** [aws/containers-roadmap#679]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When creating EKS control plane with private access only users should be able to select in which subnets EKS should provision private endpoints instead of randomly selecting subnets. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The goal is to run EKS with private access only. In our network design private VPCs have certain NACL restrictions applied for our subnets. When using EKS with private access only, provisioned EKS can become unreachable if all EKS endpoints are created in "restricted" subnets. Currently, it appears that EKS randomly selects 2 subnets where to create endpoints. 

**Are you currently working around this issue?**
Using EKS with public access and CIDR restriction enabled.

**Comment by tsunamishaun** [comment]
I recently came across this myself which explained the intermittent `kubectl` responses we had been seeing. This is an issue when we are trying to add connectivity over a pcx as we would need to add the pcx route to the public route table 🙁 I would have thought the same logic used by the ccm to determine load balancer subnets would be the same approach used to dump the endpoint enis. However this ends up happening it would be greatly appreciated!

**Comment by tsunamishaun** [comment]
Are there currently any workarounds to getting the eni's re-provisioned? I have tried deleting and switching to public then back to private with no luck.  Having to add a pxc route to a public route table is something I don't want to have to do. Does anyone know how often the ENI's change (if at all)?

**Comment by buzzsurfr** [comment]
@tsunamishaun What method are you using to deploy the VPC and EKS cluster? Can you restrict the EKS cluster creation to just the private subnets?

**Comment by tsunamishaun** [comment]
@buzzsurfr - thanks for the reply! Correct me if I'm wrong but I believe EKS uses the subnet list to determine where to deploy private and public loadbalancers. I am currently deploying both EKS and VPC using Terraform, a mix of upstream and private modules.

**Comment by buzzsurfr** [comment]
Ultimately, the EKS subnets provided when creating an EKS cluster are used for potential network interfaces for bidirectional communication between the worker nodes and the master nodes.

This does not have to include "all" subnets that will be used by worker nodes. You can use the [Cluster VPC considerations - Subnet tagging requirement](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-subnet-tagging) to tag additional subnets that can be used by worker nodes and optionally for creating load balancers (internal or external).

**Comment by tsunamishaun** [comment]
I just ran through creation of a new 1.15 eks cluster with 3 subnets. I then tagged 3 additional subnets post provision, hoping to use the approach you outlined above. I was unable to create managed node groups in the 3 new subnets (leaving load balancers out for now). I ensured the vpc and subnets (all six) were tagged correctly per the documentation, I also referenced the tags of the 3 subnets auto attached by eks during the provisioning process. Any help appreciated!

**Comment by buzzsurfr** [comment]
@tsunamishaun That sounds different than the EKS endpoints (but still worth investigating). What were you using to create the managed node groups (e.g. console, CLI, etc.)?

**Comment by tsunamishaun** [comment]
It is indeed 😉 I had to run through this myself to see if it's viable for our use-case. Looks like that worked, I was able to not only provision node groups but load balancers as well. Thanks for the advice. I believe we are relying on the automatic tagging of subnets by EKS and ignoring those tags with terraform, we would need to attach those subnet tags in the tf eks provisioning step to make use of this (for those reading this in the future). Again, thanks for all your help @buzzsurfr !

**Comment by tabern** [comment]
Because of the way the EKS control plane works, this is likely not possible for us to implement. Have you tried creating the cluster with just a limited set of subnets (two) and then tagging in additional subnets for worker nodes after the cluster is created? Check out [subnet tagging](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-subnet-tagging) in the EKS documentation.

**Comment by mikestef9** [comment]
See updates made to EKS [documentation](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html), we describe how you can control the exact subnets where cross account ENIs are placed if you have that requirement.
