### ISSUE TITLE
.cluster.local address not working in EKS 1.14 Coredns 1.3.1

### ISSUE THREAD

**Issue by romil-punetha** [aws/containers-roadmap#684]
Ever since updating to EKS 1.14 and coredns 1.3.1, the colorteller example has stopped working with `Could not resolve hostname`. There is some issue with coredns 1.3.1 and beyond.

How to reproduce:
1. Setup EKS 1.14 with aws supported coredns 1.3.1.
2. Deploy the mesh and sample application.
3. Try hitting the gateway pod.

Result: 9/10 calls fail. 
Downgrade coredns to 1.2.6 and the code works as expected.

**Comment by mikestef9** [comment]
Hi @romil-punetha 

CoreDNS 1.6.6 is now the recommend version for all EKS clusters

https://docs.aws.amazon.com/eks/latest/userguide/coredns.html

Can you try using this version and see if you still have any issues?

**Comment by romil-punetha** [comment]
It works fine on CoreDNS 1.5.5
