### ISSUE TITLE
[ECS]: Document how to update a capacity provider

### ISSUE THREAD

**Issue by pauldraper** [aws/containers-roadmap#688]
When I add a capacity provider with a conflicting name, I get an error:

```
The specified capacity provider already exists.
To change the configuration of an existing capacity provider,
update the capacity provider.
```

AWS documentation, however, is silent on how to update an existing capacity provider.

**Comment by coultn** [comment]
We are working on an API for this:  https://github.com/aws/containers-roadmap/issues/633

Closing this issue as it is a duplicate.
