### ISSUE TITLE
[ECS]: Capacity providers are broken for services

### ISSUE THREAD

**Issue by pauldraper** [aws/containers-roadmap#689]
According to https://aws.amazon.com/blogs/containers/deep-dive-on-amazon-ecs-cluster-auto-scaling/ the metric CapacityProviderReservation is "number of instances are running in an ASG to meet the needs of the tasks assigned to that ASG, including tasks already running as well as tasks the customer is trying to run" divided by "the current number of instances" times 100.

However, that doesn't seem to work with services.

If the cluster at full capacity and a new task is desired, the CapacityProviderReservation exceeds 100%. (Example included in blog.) Unless it is a service. It seems that service sizes are accounted for differently; **a service's desired capacity have no effect on CapacityProviderReservation**.

A simple experiment is to set the target utilization at 100%, then increase the service, and then watch nothing happen. (This problem is most easily visible with a 100% target, but it's not limited to that. For a 90% target there is still a problem in that service scale very slowly.)

**Comment by coultn** [comment]
Can you elaborate on your specific configuration?  Services do work with cluster auto scaling.  The tasks accounted for in the metric include both tasks started by RunTask as well as tasks started by services. Services are not account for differently.  Do you see provisioning tasks for the service?  Provisioning tasks are the key for causing the metric to go above 100%.

**Comment by pauldraper** [comment]
Oops.

It looks like I hadn't updated the (already existing) service to use the default capacity provider strategy.

Apparently a service can have an empty strategy, the default strategy, or a custom strategy.

The "provisioning tasks" does indeed solve the problem.

**Comment by jakebanks** [comment]
Thanks @pauldraper we hit the same issue - defined for cluster but service wasn't using it.
