### ISSUE TITLE
[ECS]: DAEMON cannot be used if default capacity strategy is set

### ISSUE THREAD

**Issue by pauldraper** [aws/containers-roadmap#692]
I don't know if this is a bug or a documentation issue, but daemon scheduling strategy cannot be used if the cluster has a default capacity provider.

```sh
aws ecs create-service \
  --cluster=mycluster \
  --scheduling-strategy=DAEMON \
  --service-name=myservice \
  --task-definition=mytask:1
```

> An error occurred (InvalidParameterException) when calling the CreateService operation: Specifying a capacity provider strategy is not supported when you create a service using the DAEMON scheduling strategy.

I can't find any documentation about this, nor is it clear that this behavior is correct.

I would like to run a log/metric collector on each EC2 instance in the cluster (i.e. the primary use case for DAEMON).

I don't believe that should be at odds with a default capacity provider.

**Comment by coultn** [comment]
Can you run it again but with the additional argument ```--launch-type EC2``` ?

**Comment by ipmb** [comment]
I hit this as well and confirmed `--launch-type EC2` resolves it. Thanks 🎉
