### ISSUE TITLE
[EKS]: Support for Kubernetes 1.17

### ISSUE THREAD

**Issue by andreastoyota** [aws/containers-roadmap#697]
**Tell us about your request**
Support for Kubernetes 1.17 in Amazon EKS

[Upstream Release timing](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.17)
[Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md)

**Comment by AceHack** [comment]
Just curious to when you might expect this.  Thanks.

**Comment by igrowheart** [comment]
Our app has some configurations only work with 1.17, is it possible to provide any timeline when EKS will support K8s 1.17?

**Comment by gitfool** [comment]
I see 1.17 in the AWS Console and `amazon-eks-node-1.17-v20200709` in the AMIs! 🚀

**Comment by mikestef9** [comment]
Wanted to provide an update. As some of you have noticed, 1.17 is now available for EKS!

We are working on getting our documentation updated, along with an official AWS What's New post, and expect to have that done early next week. We will close this issue once those tasks have been completed.

Additional Notes:

eksctl support for Kubernetes 1.17 is also available
https://github.com/weaveworks/eksctl/releases/tag/0.24.0-rc.0

**Comment by mikestef9** [comment]
FYI, 1.17 is also available in GovCloud regions now as well
