### ISSUE TITLE
[AWS for Fluent Bit] [request]: Support sending logs direct to managed AWS ElasticSearch

### ISSUE THREAD

**Issue by PettitWesley** [aws/containers-roadmap#698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Newer versions of Amazon ElasticSearch Service require Sigv4 auth with valid AWS credentials. Fluent Bit has an output plugin for ES, but it does not support Sigv4 auth.

Many customers have asked for the ability to send logs directly to Amazon ES. This applies to FireLens users and EKS users who run Fluent Bit as a daemonset.

**Comment by PettitWesley** [comment]
Also tracked in [fluent/fluent-bit#1807](https://github.com/fluent/fluent-bit/issues/1807) and [fluent/fluent-bit#1804](https://github.com/fluent/fluent-bit/issues/1807)

**Comment by PettitWesley** [comment]
The first step is Sigv4 and AWS Credential support in Fluent Bit; this work is almost done:
- https://github.com/fluent/fluent-bit/pull/1852
- https://github.com/fluent/fluent-bit/pull/1854
- https://github.com/fluent/fluent-bit/pull/1855
- https://github.com/fluent/fluent-bit/pull/1857

**Comment by PettitWesley** [comment]
https://github.com/fluent/fluent-bit/pull/2011

**Comment by antoine-choimet-cbp** [comment]
Hello, have you any news about this request?

**Comment by PettitWesley** [comment]
@antoine-choimet-cbp This will be released as part of Fluent Bit 1.5, tentatively planned for some time this month.

**Comment by PettitWesley** [comment]
This was shipped a while ago, closing.

**Comment by TBBle** [comment]
I realise this is closed-as-shipped, but it might be nice to mention this Fluent-bit integration as an ingestion option in the [ELK feature page](https://aws.amazon.com/elasticsearch-service/the-elk-stack/data-ingestion/), since it's talking about other non-Logstash options.
