### ISSUE TITLE
[EKS] [request]: FireLens on EKS Fargate

### ISSUE THREAD

**Issue by PettitWesley** [aws/containers-roadmap#701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Fargate for ECS has FireLens, a managed observability experience built around the open source projects Fluentd and Fluent Bit. [AWS for Fluent Bit](https://github.com/aws/aws-for-fluent-bit) provides a lightweight solution for AWS customers to process and ship telemetry data to many destinations. 

We are evaluating ways in which we can make it easy, simple, and reliable to use AWS for Fluent Bit on EKS Fargate.

**Which service(s) is this request for?**
EKS Fargate

This solved #618

**Comment by PettitWesley** [comment]
Related:
- https://github.com/aws/containers-roadmap/issues/699
- https://github.com/aws/containers-roadmap/issues/700

**Comment by farooqdevops** [comment]
@PettitWesley can we use fluentd with eks fargate to send data to aws elasticsearch  because fluentd daemonset implementation is not supported yet.

**Comment by PettitWesley** [comment]
@farooqdevops At the moment, you can, but only if you make your app container write logs to a volume and have Fluentd read the files on the volume.

**Comment by cahman** [comment]
@PettitWesley Hi, sorry for being a noob, but is it possible that you can give some more details how to do? I would be forever grateful. What kind och volume? 

/Chris

**Comment by mreferre** [comment]
@cahman we are working on a blog post that can walk users on how to do this. The yaml below is an example of how you'd configure a pod running on Fargate to do that. There will be more info in the blog. This example logs to CW but you can change the fluentbit configuration to log to other back-ends.  

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [INPUT]
        Name              tail
        Tag               *.logs
        Path              /var/log/*.log
        DB                /var/log/logs.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [OUTPUT]
        Name              cloudwatch
        Match             *
        region            us-west-2
        log_group_name    eks-fargate-logs
        log_stream_prefix fargate-
        auto_create_group true
---
apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  serviceAccountName: fargate
  containers:
  - name: count
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date) this is an app log" >> /var/log/app.log;
        echo "$(date) $(uname -r) $i" >> /var/log/system.log;
        i=$((i+1));
        sleep 1;
      done
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: count-agent
    image: amazon/aws-for-fluent-bit:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 2020
    env:
    - name: FLUENTD_HOST
      value: "fluentd"
    - name: FLUENTD_PORT
      value: "24224"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: fluentbit-config
      mountPath: /fluent-bit/etc/
  terminationGracePeriodSeconds: 10
  volumes:
  - name: varlog
    emptyDir: {}
  - name: fluentbit-config
    configMap:
      name: fluentbit-config
```

**Comment by jwvanhollebeke** [comment]
Thanks for this configuration sample @mreferre! Will this issue be updated when the blog post is published?

**Comment by mreferre** [comment]
> Thanks for this configuration sample @mreferre! Will this issue be updated when the blog post is published?

@jwvanhollebeke yes this issue is the public facing tracking element of this feature and will be updated as it progresses.

**Comment by dalgibbard** [comment]
Whilst this seems reasonable on the surface, sending your application logs to a file is one thing, but when using services developed by others (take ALB-ingress-controller for example) it's less trivial to make these changes.
Rather than just pulling the image as part of the k8s deployment, I'd have to pull the image in a build pipeline, modify how/where it writes logs, and then host the image myself - and then maintain that for the foreseeable future too.

In addition, for circumstances where the application encounters an error before or outside of initiating a log driver etc, these logs would not be exported either?

**Comment by mreferre** [comment]
@dalgibbard what you are pointing out is correct for the short term by pass we were suggesting (ie writing to a log file). We want Firelens to be able to get logs from stdout so those apps do not need to be changed.

**Comment by dalgibbard** [comment]
@mreferre awesome, thanks for confirming!

**Comment by vanagarwal** [comment]
@mreferre 

We are also planning to use the configuration that you shared in this thread to send logs to our K8s jobs (jobs that run to completion) running on EKS Fargate and we will start writing logs to files.
I have a question, since K8s pods linked to K8s jobs gets completed as soon as the application container exits with a success exit code, so in order to make sure that fluentd container does not miss transporting any logs to cloudwatch during the pod's transition from running to completed state, do we need to add any extra configuration? 

My question might be little obvious and please excuse me for that :)

**Comment by vanagarwal** [comment]
> @cahman we are working on a blog post that can walk users on how to do this. The yaml below is an example of how you'd configure a pod running on Fargate to do that. There will be more info in the blog. This example logs to CW but you can change the fluentbit configuration to log to other back-ends.
> 
> ```
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: fluentbit-config
> data:
>   # Configuration files: server, input, filters and output
>   # ======================================================
>   fluent-bit.conf: |
>     [INPUT]
>         Name              tail
>         Tag               *.logs
>         Path              /var/log/*.log
>         DB                /var/log/logs.db
>         Mem_Buf_Limit     5MB
>         Skip_Long_Lines   On
>         Refresh_Interval  10
>     [OUTPUT]
>         Name              cloudwatch
>         Match             *
>         region            us-west-2
>         log_group_name    eks-fargate-logs
>         log_stream_prefix fargate-
>         auto_create_group true
> ---
> apiVersion: v1
> kind: Pod
> metadata:
>   name: counter
> spec:
>   serviceAccountName: fargate
>   containers:
>   - name: count
>     image: busybox
>     args:
>     - /bin/sh
>     - -c
>     - >
>       i=0;
>       while true;
>       do
>         echo "$i: $(date) this is an app log" >> /var/log/app.log;
>         echo "$(date) $(uname -r) $i" >> /var/log/system.log;
>         i=$((i+1));
>         sleep 1;
>       done
>     volumeMounts:
>     - name: varlog
>       mountPath: /var/log
>   - name: count-agent
>     image: amazon/aws-for-fluent-bit:latest
>     imagePullPolicy: Always
>     ports:
>       - containerPort: 2020
>     env:
>     - name: FLUENTD_HOST
>       value: "fluentd"
>     - name: FLUENTD_PORT
>       value: "24224"
>     volumeMounts:
>     - name: varlog
>       mountPath: /var/log
>     - name: fluentbit-config
>       mountPath: /fluent-bit/etc/
>   terminationGracePeriodSeconds: 10
>   volumes:
>   - name: varlog
>     emptyDir: {}
>   - name: fluentbit-config
>     configMap:
>       name: fluentbit-config
> ```

Hi 

Thanks for sharing this. Can you please let me know which serviceaccount we are referring to here as serviceAccountName: fargate ?

**Comment by xingvivian91** [comment]
> > @cahman we are working on a blog post that can walk users on how to do this. The yaml below is an example of how you'd configure a pod running on Fargate to do that. There will be more info in the blog. This example logs to CW but you can change the fluentbit configuration to log to other back-ends.
> > ```
> > apiVersion: v1
> > kind: ConfigMap
> > metadata:
> >   name: fluentbit-config
> > data:
> >   # Configuration files: server, input, filters and output
> >   # ======================================================
> >   fluent-bit.conf: |
> >     [INPUT]
> >         Name              tail
> >         Tag               *.logs
> >         Path              /var/log/*.log
> >         DB                /var/log/logs.db
> >         Mem_Buf_Limit     5MB
> >         Skip_Long_Lines   On
> >         Refresh_Interval  10
> >     [OUTPUT]
> >         Name              cloudwatch
> >         Match             *
> >         region            us-west-2
> >         log_group_name    eks-fargate-logs
> >         log_stream_prefix fargate-
> >         auto_create_group true
> > ---
> > apiVersion: v1
> > kind: Pod
> > metadata:
> >   name: counter
> > spec:
> >   serviceAccountName: fargate
> >   containers:
> >   - name: count
> >     image: busybox
> >     args:
> >     - /bin/sh
> >     - -c
> >     - >
> >       i=0;
> >       while true;
> >       do
> >         echo "$i: $(date) this is an app log" >> /var/log/app.log;
> >         echo "$(date) $(uname -r) $i" >> /var/log/system.log;
> >         i=$((i+1));
> >         sleep 1;
> >       done
> >     volumeMounts:
> >     - name: varlog
> >       mountPath: /var/log
> >   - name: count-agent
> >     image: amazon/aws-for-fluent-bit:latest
> >     imagePullPolicy: Always
> >     ports:
> >       - containerPort: 2020
> >     env:
> >     - name: FLUENTD_HOST
> >       value: "fluentd"
> >     - name: FLUENTD_PORT
> >       value: "24224"
> >     volumeMounts:
> >     - name: varlog
> >       mountPath: /var/log
> >     - name: fluentbit-config
> >       mountPath: /fluent-bit/etc/
> >   terminationGracePeriodSeconds: 10
> >   volumes:
> >   - name: varlog
> >     emptyDir: {}
> >   - name: fluentbit-config
> >     configMap:
> >       name: fluentbit-config
> > ```
> 
> Hi
> 
> Thanks for sharing this. Can you please let me know which serviceaccount we are referring to here as serviceAccountName: fargate ?

@vanagarwal Here is the post https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/ (just got published today). But the serviceaccount is referring to the created sidecar service account for Fluentd

**Comment by xwng** [comment]
> > @cahman we are working on a blog post that can walk users on how to do this. The yaml below is an example of how you'd configure a pod running on Fargate to do that. There will be more info in the blog. This example logs to CW but you can change the fluentbit configuration to log to other back-ends.
> > ```
> > apiVersion: v1
> > kind: ConfigMap
> > metadata:
> >   name: fluentbit-config
> > data:
> >   # Configuration files: server, input, filters and output
> >   # ======================================================
> >   fluent-bit.conf: |
> >     [INPUT]
> >         Name              tail
> >         Tag               *.logs
> >         Path              /var/log/*.log
> >         DB                /var/log/logs.db
> >         Mem_Buf_Limit     5MB
> >         Skip_Long_Lines   On
> >         Refresh_Interval  10
> >     [OUTPUT]
> >         Name              cloudwatch
> >         Match             *
> >         region            us-west-2
> >         log_group_name    eks-fargate-logs
> >         log_stream_prefix fargate-
> >         auto_create_group true
> > ---
> > apiVersion: v1
> > kind: Pod
> > metadata:
> >   name: counter
> > spec:
> >   serviceAccountName: fargate
> >   containers:
> >   - name: count
> >     image: busybox
> >     args:
> >     - /bin/sh
> >     - -c
> >     - >
> >       i=0;
> >       while true;
> >       do
> >         echo "$i: $(date) this is an app log" >> /var/log/app.log;
> >         echo "$(date) $(uname -r) $i" >> /var/log/system.log;
> >         i=$((i+1));
> >         sleep 1;
> >       done
> >     volumeMounts:
> >     - name: varlog
> >       mountPath: /var/log
> >   - name: count-agent
> >     image: amazon/aws-for-fluent-bit:latest
> >     imagePullPolicy: Always
> >     ports:
> >       - containerPort: 2020
> >     env:
> >     - name: FLUENTD_HOST
> >       value: "fluentd"
> >     - name: FLUENTD_PORT
> >       value: "24224"
> >     volumeMounts:
> >     - name: varlog
> >       mountPath: /var/log
> >     - name: fluentbit-config
> >       mountPath: /fluent-bit/etc/
> >   terminationGracePeriodSeconds: 10
> >   volumes:
> >   - name: varlog
> >     emptyDir: {}
> >   - name: fluentbit-config
> >     configMap:
> >       name: fluentbit-config
> > ```
> 
> Hi
> 
> Thanks for sharing this. Can you please let me know which serviceaccount we are referring to here as serviceAccountName: fargate ?

@vanagarwal it's referring to the created sidecar service account for Fluentd. But here is the post (just got published earlier today) https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/

**Comment by tabern** [comment]
this solved #618

**Comment by akshayram-wolverine** [comment]
Now live: https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-adds-built-in-logging-support-for-aws-fargate/

**Comment by sandan** [comment]
> To define the log destination of your choice you use Fluent Bit’s configuration language. You can choose between CloudWatch, ElasticSearch, Kinesis Firehose and Kinesis Streams as outputs.

From the [blog](https://aws.amazon.com/blogs/containers/fluent-bit-for-amazon-eks-on-aws-fargate-is-here/).

Is there going to be support for datadog as output on EKS Fargate? I tried it like like so in my ConfigMap:
```
data:
  output.conf: |
    [OUTPUT]
        Name        datadog
        Match       *
```
I get:
```
Error from server: error when creating "config-dd-logging.yaml": admission webhook "0500-amazon-eks-fargate-configmaps-admission.amazonaws.com" denied the request: datadog is not a supported output plugin. Please fix the logging configmap
```

**Comment by amagnus** [comment]
Also interested in what's the right approach for Sumologic?

**Comment by PettitWesley** [comment]
@sandan @amagnus Right now the recommended approach for sending to partner destinations is to use Kinesis Firehose or CloudWatch as a middle man destination. Firehose can send to Datadog. 

With the initial launch complete, we are working on a number of improvements to EKS Fargate logging, and I think eventually we will be able to enable the datadog output plugin and have a secrets integration to safely pass it API tokens.

**Comment by amagnus** [comment]
@PettitWesley In the case of Sumologic, fluent-bit configuration is a simple HTTP output. Why not allow it out of the box?

**Comment by mtardini** [comment]
> Now live: https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-adds-built-in-logging-support-for-aws-fargate/

This feature is really useful to simplify the fluent-bit configuration but the official documentation is "there is no official documentation". There are only a few articles like [this ](https://aws.amazon.com/es/blogs/containers/fluent-bit-for-amazon-eks-on-aws-fargate-is-here/) one that do not explain all the fluent-bit options available [here](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch) and the way of using each method of authentication.

What I want.
Use the  AWS-Role-ARN in the OUTPUT configuration to be always to ship data to ElasticSearch.

What I archived.
Use AWS_Auth ON to allow the POD Execution Role to ship data to ElasticSearch.

The overhead of maintenance of that is big and unnecessary.
Maybe better documentation would help me and the AWS Support that helped me with this troubleshooting.

**Comment by AtaqueOsuno** [comment]
> > Now live: https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-adds-built-in-logging-support-for-aws-fargate/
> 
> This feature is really useful to simplify the fluent-bit configuration but the official documentation is "there is no official documentation". There are only a few articles like [this ](https://aws.amazon.com/es/blogs/containers/fluent-bit-for-amazon-eks-on-aws-fargate-is-here/) one that do not explain all the fluent-bit options available [here](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch) and the way of using each method of authentication.
> 
> What I want.
> Use the AWS-Role-ARN in the OUTPUT configuration to be always to ship data to ElasticSearch.
> 
> What I archived.
> Use AWS_Auth ON to allow the POD Execution Role to ship data to ElasticSearch.
> 
> The overhead of maintenance of that is big and unnecessary.
> Maybe better documentation would help me and the AWS Support that helped me with this troubleshooting.

Would you mind sharing your configmap that worked? as you mention no actual documentation on how the fluentd is used with ES exists at this time.

**Comment by AlexeyRaga** [comment]
> https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-adds-built-in-logging-support-for-aws-fargate/

I run the example code from this post and it doesn't produce any logs in CloudWatch. Even the log group is not getting created.
How do I debug it? I don't see any fluent-bit daemons or pods anywhere in the cluster too, should it be enabled/deployed separately? How do I find logs from it itself?

**Comment by PettitWesley** [comment]
> How do I debug it? I don't see any fluent-bit daemons or pods anywhere in the cluster too, should it be enabled/deployed separately? How do I find logs from it itself?


Getting logs from the built-in fluent bit process is not yet supported. I believe this is another roadmap issue open for that.

**Comment by AlexeyRaga** [comment]
Oh. I see. Then, what is the general way of debugging logging configurations?
Right now, I am trying to send logs to the ES and logs don't appear there. 

The config seems to be straightforward:

```
[OUTPUT]
    Name es
    Match   *
    tls On
    tls.verify Off
    Index eks-alexey-logs
    Cloud_ID ${es_cloud_id}
    Cloud_Auth ${es_cloud_auth}
```

How should I approach the problem?

**Comment by PettitWesley** [comment]
@AlexeyRaga The best advice I have is to test it on an EC2 EKS cluster first. Test your configuration there first. The setup in EKS Fargate should be very equivalent to this set up on EC2: https://aws.amazon.com/blogs/containers/kubernetes-logging-powered-by-aws-for-fluent-bit/

The other option would be to contact AWS Support, and they might be able to give you some extra insight.

**Comment by AlexeyRaga** [comment]
@PettitWesley I guess I can add an EC2 node group and test it there? Thanks, good advise, will try it today.

**Comment by AlexeyRaga** [comment]
@PettitWesley I've done what you recommended. It is a good thing overall, because now I (potentially) can deploy my pods to either EC2 node groups or Fargate node groups, and have logs sent to my ES.

However, to my surprise, logs from EC2 node group are now _successfully_ sent to the ES (thanks to my newly set up fluentbit daemon set), and I can see them. But logs from Fargate are still not being shipped, despite that I use _the same output.conf in both cases_ (physically, the same file).

So frustrating.
It looks like I am probably missing some role or something that would allow Fargate's `fluentbit` to do its job...

**Comment by PettitWesley** [comment]
@AlexeyRaga The credentials used by Fluent Bit in EKS Fargate are part of the fargate profile role: https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html

If your role has all needed permissions, and it works in EC2 but not in Fargate, then contacting AWS Support is the best option. They may be able to work with the service team to find out why your setup is not working.

**Comment by dexterm59** [comment]
@AlexeyRaga

Have you had any success resolving the issue.
I have “successfully” set up logging to CloudWatch from Fargate pods.  However, the logs seem to stop and start.  My ultimate goal was to forward the logs to Datadog so I attempted to used the Kinesis firehose configuration and set up a firehose datastream connected to DataDog. Unfortunately, I see no input to the stream.
This seems very similar to the problem you faced and I was wondering whether you found a resolution.

**Comment by AlexeyRaga** [comment]
@dexterm59 No. I gave up.

**Comment by OfirYaron** [comment]
I'm using EKS on fargate, configured everything according to the article (https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-adds-built-in-logging-support-for-aws-fargate/) 

I managed to make it work, but unfortunately it seems that I only get cluster level logging and none of the pods logs (showed on kubectl logs) are routed into cloudwatch,

Am I missing something or is this level of logging not supported by this solution? (like sidecar offers)

**Comment by PettitWesley** [comment]
@OfirYaron You should be getting the pod logs. Please contact AWS Support.

**Comment by gbvanrenswoude** [comment]
Is there a possibility to send logs to separate indexes per namespace?
