### ISSUE TITLE
[ECR] [request]: Restrict IMAGE pull based on launch type

### ISSUE THREAD

**Issue by krishnaastica** [aws/containers-roadmap#711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
It would be great If we can restrict Image pull from ECR based on Task Definition launch type.
For ex:
If the launch type is FARGATE, ECR should allow image pull and if the launch type is EC2 should deny the request.
This is because we would like to run our containers on a isolated environment / bring in the capability to lend our images to others without providing the Image to the other source account.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are working on proposal of sharing our application to end users as Images. The image will be having the executable binaries which should not be exposed. It is where FARGATE gave a strike. We were able to achieve it through it. Our application runs on FARGATE where the end user cannot view the Image or details inside the container. 

But the problem is as the Image is shared with other account, they were able to pull it to other EC2 task and view our binary, which should not work. So it would be awesome if we can restrict "GetImageLayer" API based on launch type.

Typically like:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ECR-Cross-Account",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::123456789012:root"
      },
      "Action": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:GetDownloadUrlForLayer"
      ],
      "Condition": {
        "StringEquals": {
          "ecs:LaunchType": "fargate",
        }
      }
    }
  ]
}
```

**Are you currently working around this issue?**
We are currently checking on other feasibility, like setting up a license server which is again a tedious job

**Comment by rpnguyen** [comment]
When a pull request arrives at ECR, the authorization token used does not have any context about the execution environment (i.e. EC2 or Fargate or Docker CLI etc) so it is not possible to create a resource policy based on this context.

[AWS Marketplace for Containers](https://aws.amazon.com/marketplace/features/containers) is one option to distribute your software as a container but still restrict execution privileges.
