### ISSUE TITLE
[EKS]: Support for setting Dynamic Kubelet Configuration on Managed Nodes

### ISSUE THREAD

**Issue by splieth** [aws/containers-roadmap#718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Since version 1.11, Kubernetes supports [Dynamic Kubelet Configuration](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/) using Kubelet Configuration / Config Maps. This allows users to change settings of kubelets, such as deactivating the read only port.
Since I'm managing managed nodes, I can't customize the kubelet's config file. Apparently, I also cannot make use of the Config Map feature since `--dynamic-config-dir` is not set for the kubelet process.

It would be awesome if it would be possible changing a node's configuration by applying config maps.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I like to fix some findings of kube-bench regarding the configuration of the kubelet process.
Since I'm using managed nodes, I can't edit the config during bootstrap and neither using a config map as described above.

**Are you currently working around this issue?**
Nope.

**Comment by tabern** [comment]
solved by https://github.com/aws/containers-roadmap/issues/596

**Comment by mikestef9** [comment]
Closing as with managed node groups support for [custom AMIs](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-custom-ami), you have full control over bootstrap and kubelet customization. We have no plans to implement Dynamic Kubelet Customization as a supported option.
