### ISSUE TITLE
[EKS] [Feature]: Allow to launch EC2 instance as a EBS-optimized

### ISSUE THREAD

**Issue by dawidmalina** [aws/containers-roadmap#720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, if the Managed Node Groups for EKS are not optimized by default then we can't force it.

However, some users may prefer to launch EC2 instances which will be EBS-optimized. It seems this currently isn't possible. This would be a useful feature for users who are interested in adopting Managed Node Groups for EKS but can't use EBS-optimized instances by default.

**Comment by mikestef9** [comment]
Closing as this feature request is addressed by launch template support. See #585 for details!
