### ISSUE TITLE
[EKS] [request]: tag Kubernetes managed nodes with node-role.kubernetes.io/<node-group-name>=true

### ISSUE THREAD

**Issue by yann-soubeyrand** [aws/containers-roadmap#733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

The Kubernetes managed nodes should be tagged with `node-role.kubernetes.io/<node-group-name>=true` which would make the node group name visible at a quick glance when doing `kubectl get nodes` and would allow to quickly identify the nodes.

**Which service(s) is this request for?**

EKS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

When one has many node groups in a cluster, it's really convenient to be able to quickly identify which node group a node is part of. The de facto standard node-role.kubernetes.io/<node-role>=true tag allows for this to happen when listing nodes with kubectl.

**Are you currently working around this issue?**

No, since tags ending with kubernetes.io aren't allowed on managed node groups.

**Comment by rtripat** [comment]
Nodes created using an EKS Managed Nodegroup have label key: eks.amazonaws.com/nodegroup and label value: <node-group-name> which can be used to filter nodes. Example kubectl command for a nodegroup with name `ng-4e4d73712`

`kubectl get nodes --selector=eks.amazonaws.com/nodegroup=ng-4e4d73712`

**Comment by tabern** [comment]
Closing as this functionality exists.

**Comment by yann-soubeyrand** [comment]
@tabern I disagree with you: the label exists and can be used for filtering but what I was asking for, though, is that the on purpose `node-role.kubernetes.io/<node-group-name>=true` label be used so that we can see which node group a nodes belongs to at a glance in the roles column of kubectl get nodes. Would you mind reopening this feature request please?

**Comment by zodiac12k** [comment]
@yann-soubeyrand i agree with you

**Comment by mdiver** [comment]
@yann-soubeyrand i agree too

**Comment by hong-kisung** [comment]
@yann-soubeyrand i agree with you

**Comment by yann-soubeyrand** [comment]
@tabern could you please consider reopening this issue?
