### ISSUE TITLE
[EKS] [request]: Change security group of EKS master without replacing the cluster

### ISSUE THREAD

**Issue by lukeplausin** [aws/containers-roadmap#738]
Hi, I'm having some networking problems with EKS. I need to change the security group on the EKS master, but there seems to be no way of doing this without deleting the cluster.

Cloudformation reports that a security group change requires replacement, and I cannot see a way to change this in the console either.

This is causing a bit of headache here since we want to restructure our security groups but can't do so without causing disruption to EKS services.

Thanks!

**Comment by ghandim** [comment]
We deleted some orphaned security groups and now we are not able to update our clusters anymore. Re-creation is no option for us at the moment...

**Comment by farvour** [comment]
This is a problem I am encountering. This is unacceptable, Amazon.

**Comment by harisspa** [comment]
This is a major issue even I am facing. It's not addressed till now.

**Comment by jrballot** [comment]
Having the same problem here. Can't update or add a security group without recreating the cluster. First a thought it has something related to the Terraform  aws_eks_cluster module, but apparently it is not.

Are there any way of rolling update the nodes using Terraform, CloudFormation or even AWS CLI ?  I mean as a countermeasure.

**Comment by cloudlady911** [comment]
I consider this a serious flaw.  My production cluster is on the verge of being unusable because of this.  We had a system in place that was managing security groups on my instances.  That company is ending this product on April 31.  I need to remove all the security groups that were being controlled.  I have already created replacement security groups and rolled them out using launch templates and autoscaling groups.  So the offending security group has been removed from all of my instances.  I can't change it back during production hours.  I added some rules to the main cluster security group as a work around.  Otherwise my entire cluster would crash.

This needs to be addressed ASAP!!

**Comment by cloudlady911** [comment]
This is rather like buying a house and not being able to change the locks unless you tear it down and rebuild it.

**Comment by lxjhk** [comment]
This is a serious design flaw and significantly impacts customer experience. Please address it ASAP.

**Comment by iribeirolgc** [comment]
+1

**Comment by yimeicai21** [comment]
+1 
I would like to see this feature implemented.
I am facing the same issue and I don't want to rebuild my cluster.

**Comment by runntuu** [comment]
> This is rather like buying a house and not being able to change the locks unless you tear it down and rebuild it.

+1, This is unacceptable! I really don't want to rebuilt cluster, because rebuilt and migrate is too complicated.

**Comment by sharma-abhishek-it** [comment]
+1

**Comment by zzxzz12345** [comment]
+1

**Comment by lukeplausin** [comment]
I found a solution - bin Cloudformation and switch to Terraform

**Comment by lukeplausin** [comment]
> how does that solve the issue? The SG can't be changed in either TF or CF.

You're right, the security group ID cannot be changed, but Terraform can change everything else about the security group so that it suits your requirements. If you are dealing with a cluster that is using the wrong security group, you can use the `terraform state rm` and `terraform import` commands to set the security group in your state file to the one that is currently used in the cluster. Terraform will then change everything else to fit the requirements in your code on the next apply.

```bash
terraform state rm aws_security_group.cluster_sg
terraform import sg-12345678 aws_security_group.cluster_sg
terraform apply
```

**Comment by dudicoco** [comment]
> > how does that solve the issue? The SG can't be changed in either TF or CF.
> 
> You're right, the security group ID cannot be changed, but Terraform can change everything else about the security group so that it suits your requirements. If you are dealing with a cluster that is using the wrong security group, you can use the `terraform state rm` and `terraform import` commands to set the security group in your state file to the one that is currently used in the cluster. Terraform will then change everything else to fit the requirements in your code on the next apply.
> 
> ```shell
> terraform state rm aws_security_group.cluster_sg
> terraform import sg-12345678 aws_security_group.cluster_sg
> terraform apply
> ```

I don't see how that solves anything. 
The issue states that the SG of the controller plane cannot be changed and the issue still stands, it cannot be modified.
Anything CF/TF related is irrelevant to the issue.

**Comment by yafanasiev** [comment]
Just stumbled onto this as well. Really hope AWS does something with this.

**Comment by lukeplausin** [comment]
> > > how does that solve the issue? The SG can't be changed in either TF or CF.
> > 
> > 
> > You're right, the security group ID cannot be changed, but Terraform can change everything else about the security group so that it suits your requirements. If you are dealing with a cluster that is using the wrong security group, you can use the `terraform state rm` and `terraform import` commands to set the security group in your state file to the one that is currently used in the cluster. Terraform will then change everything else to fit the requirements in your code on the next apply.
> > ```shell
> > terraform state rm aws_security_group.cluster_sg
> > terraform import sg-12345678 aws_security_group.cluster_sg
> > terraform apply
> > ```
> 
> I don't see how that solves anything. The issue states that the SG of the controller plane cannot be changed and the issue still stands, it cannot be modified. Anything CF/TF related is irrelevant to the issue.

It's a workaround that helped me and might work for some others

**Comment by agriffit79** [comment]
Just hit this issue. I don't even see it documented anywhere. It should be in bold flashing text.

**Comment by darksmoke** [comment]
I faced the same issue. I'm really looking forward to the solution. Thank you.

**Comment by dreinhardt-terminus** [comment]
Ran into this as well.

**Comment by janquijano** [comment]
Still no fix for this issue after over 3 years?

**Comment by odogwuVal** [comment]
Currently facing this issue.
there has to be a way to modify the eks sg without destroying it......it is way too costly destroying a production cluster

**Comment by kurosakisora** [comment]
I really need to change EKS security group freely.

**Comment by mkuendig** [comment]
Come on AWS, this is very poor design. The SG is not protected, can be very easily deleted...and recreating the cluster is certainly not an option. Pls fix this or at least provide an alternative option.

**Comment by mkuendig** [comment]
I have learned that upgrading the cluster (for example from 1.26 to 1.27) will restore the SG...but also this is just a silly workaround...In my case not feasible, as the whole test chain before was still on the older version. And with AWS EKS, its forward upgrades only. No downgrades.

I finally backuped the cluster with velero, destroyed the faulty cluster, deployed fresh and restored it with Velero. Far from perfect, had about 6 hours downtime because of this issue. And Velero is not perfect. Missed out on quite some objects that had to be manually brought back with fresh app deployments. Luckily, that was all very well done with pipelines. And this was a small cluster that had to be replaced. Imaging replacing a cluster with hundreds of apps on it. That will be very painful.

**Comment by hendricjabs** [comment]
Same issue here. I accidently deleted the "Additional Security Group" of the control plane. There are several things odd here:
1. "Additional" sounds a bit like "not required"/optional to me.
2. Any other service can exchange the security group.
3. I thought EKS would be more mature.

**Comment by leonmwandiringa** [comment]
AWS needs to work on their network interface attachment flexibility, its not only EKS but also ECS when services are deployed using blue/green. this is unacceptable

**Comment by mikestef9** [comment]
**What's new**: https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eks-modification-cluster-subnets-security/
**Docs**: https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

**Important Note**: The security groups passed through this API are *additional* security groups to be attached to the cross account ENIs, in addition to the "cluster security group" that EKS creates with each new cluster. We are aware of the [request](https://github.com/aws/containers-roadmap/issues/1355) to skip creation of the "cluster security group" in the first place, so only the security groups passed in this API would be associated with the cross account ENIs.

**Comment by mikestef9** [comment]
Deep dive blog published

https://aws.amazon.com/blogs/containers/enhanced-vpc-flexibility-modify-subnets-and-security-groups-in-amazon-eks/

**Comment by byoungsoo** [comment]
@mikestef9 
Can users use the option in EKS Anywhere too? 

> Users can now use the Manage VPC resources option available in the Networking section of the Amazon EKS Console to add or delete subnets.
- Deep dive blog published
https://aws.amazon.com/blogs/containers/enhanced-vpc-flexibility-modify-subnets-and-security-groups-in-amazon-eks/
