### ISSUE TITLE
[EKS]: Recommended CoreDNS version is missing metric

### ISSUE THREAD

**Issue by lachlancooper** [aws/containers-roadmap#748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The currently recommended [version and configuration](https://docs.aws.amazon.com/eks/latest/userguide/coredns.html) of CoreDNS, 1.6.6, contains [a bug](https://github.com/coredns/coredns/issues/3577) that means a fairly important metric, `coredns_cache_misses_total`, is missing. The bug is fixed in 1.6.7, so a logical response would seem to be to upgrade the recommended version.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
DNS performance is critical to the functioning of the services in our clusters. We need observability into important metrics such as cache misses in order to debug any issues should they arise.

**Are you currently working around this issue?**
We are currently running version 1.6.7, as it contains no significant feature changes but fixes the missing metric bug.

**Comment by frankreno** [comment]
Is there any eta on a fix for this for EKS?

**Comment by mikestef9** [comment]
CoreDNS 1.7.0 is now the recommended version for EKS 1.18 

https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
