### ISSUE TITLE
[ECS] [Bug] containerOverrides not working with capacity providers

### ISSUE THREAD

**Issue by NielsCorneille** [aws/containers-roadmap#749]
When launching a new task with containerOverrides onto an ECS cluster with capacityProviders, the containerOverrides are not always working.
If the task get placed in PROVISIONING, the overrides disappear when the task reached PENDING.
The containerOverrides work if there is enough capacity and the task immediately reaches PENDING state.

Was first mentioned here: https://github.com/aws/aws-cli/issues/4739
There is also a bug report on the AWS Developer forums: https://forums.aws.amazon.com/thread.jspa?threadID=314493

**Comment by K-7** [comment]
Even I am having same issue. What ever overrides I pass through goes through as part of boto POST
2020-03-19 13:22:15,894 botocore.endpoint [DEBUG] Making request for OperationModel(name=RunTask) with params:

But as part of boto Response body overrides are empty ie.
"overrides":{"containerOverrides":[],"inferenceAcceleratorOverrides":[]}

**Comment by matt-theguyw1cat** [comment]
+1  Seeing exactly the same issue.  If I allow the cluster using a capacity provider to scale down to 0 instances then (via boto or CLI) container overrides are ignored when the task is eventually run.  All of the stuff in task def is correct, but overrides requested at run-task are lost.

**Comment by sachinahj** [comment]
Same. Any update on this bug @coultn ?

**Comment by coultn** [comment]
We are working on it. We will share more information here when we can.

**Comment by ronhopper** [comment]
This seems to be working as of a few days ago. Is it fixed? Any update?

**Comment by ronhopper** [comment]
> This seems to be working as of a few days ago. Is it fixed? Any update?

@coultn any update on this?

**Comment by pavneeta** [comment]
> > This seems to be working as of a few days ago. Is it fixed? Any update?
> 
> @coultn any update on this?


Hi @ronhopper Yes, we are currently deploying this fix across all regions, hence it is available. We will announce GA launch of this along with DeleteCapacity API in a few weeks time. 

Hope that helps.

**Comment by tpesce** [comment]
We are still seeing inconsistent behavior related to this issue...

Now, when the task reaches RUNNING the containerOverrides we specify are present, so that much seems to be fixed. However, the initial return value from (boto) run_task() **does not** include the containerOverrides we specify when no capacity is available, but the return value **does** include the containerOverrides when capacity is available.

Has the return value from run_task() also been addressed with the fix for this issue?

FWIW, we're running in us-east-1.

**Comment by srrengar** [comment]
ECS Container Overrides are now available for ECS Cluster Auto Scaling. As you point out, the ECS RunTask/DescribeTasks response does not display the Container Overrides, until the Task reaches a Running state. We are following-up on this discrepancy, such that Container Overrides are always displayed in both the RunTask and DescribeTasks response.

**Comment by anoopkapoor** [comment]
This has now been resolved. Container Overrides are now always displayed in both the RunTask and DescribeTasks responses.
