### ISSUE TITLE
[ECS] [request]: Upgrade docker version in ECS-optimized AMIs to v19.03

### ISSUE THREAD

**Issue by leshik** [aws/containers-roadmap#761]
### Community Note

Please upgrade the version of Docker included in the ECS optimized AMIs to v19.03 or newer

**Tell us about your request**

Docker v19.03 has substantial improvements in the logging subsystem regarding partial metadata for messages longer than 16k. This will greatly improve reliability when using [FluentD logging driver and fluentd-plugin-concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat#usage)

**Which service(s) is this request for?**

ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Docker breaks in parts messages longer than 16k. Before v19.03 there was only `partial_message` boolean flag.

**Are you currently working around this issue?**

Using the same `fluentd-plugin-concat` and `partial_message` flag but it's unreliable.

**Comment by truppert-mdsol** [comment]
I second this request!  There has been a fix incorporated in the newest version of docker that should fix a performance issue we've been seeing in v18.09.  

Here is the issue I'm referring to: https://github.com/moby/moby/issues/39916
It was fixed in https://github.com/docker/swarmkit/pull/2927 and incorporated into v19.03 in https://github.com/moby/moby/pull/40432

**Comment by truppert-mdsol** [comment]
This request has been incredibly silent.  Could someone from the ECS team comment please?  It has become more important to us for the reason I specified on Feb 21st.

1. Is this being worked on and is there an ETA?
2. Is there something preventing the usage of Docker 19?

**Comment by fierlion** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html
The latest ECS-optiimized AMIs were released today with Docker version 19.03.6-ce.
