### ISSUE TITLE
[EKS] [issues]: Lock EKS Version Issue Conversations

### ISSUE THREAD

**Issue by RyPeck** [aws/containers-roadmap#765]
EKS Version issues attract a lot of off-topic comments and conversation. I would ask that the maintainers of the repo consider locking the "Support for Kubernetes X" issues to comments and providing updates to cut down on the noise for those of us here who want to follow developments from AWS regarding these features.

https://help.github.com/en/github/building-a-strong-community/locking-conversations

#380 
#487
#697 

EDIT - @rdonkin compromise suggestion is a better idea imho - https://github.com/aws/containers-roadmap/issues/765#issuecomment-590035904

**Comment by a7i** [comment]
@RyPeck I would encourage the maintainers to leave it open and hear their customers' feedback, even if it's not pleasant to hear. Read Amazon's leadership principle, specifically "Customer Obsession".

**Comment by rdonkin** [comment]
Please keep these discussions open.   They are useful for people already using EKS, and fior those considering whether to use EKS or not.  The slow support for upstream versions is a major consideration for me, along with the AWS CNI plugin limiting number of IP addresses per node.

As a compromise, how about two issues - one locked for EKS team updates only, and one for customer feedback/comments?

**Comment by RyPeck** [comment]
@rdonkin that's a better solution.

**Comment by walkafwalka** [comment]
As much as I hate comment +1s and other poor feedback, I would not want to also filter out the good feedback.
