### ISSUE TITLE
New EKS Region : Ningxia

### ISSUE THREAD

**Issue by pahud** [aws/containers-roadmap#77]
**Tell us about your request**
New region support in Ningxia, China(cn-northwest-1)

**Which service(s) is this request for?**
Amazon EKS

Please add the support plan in the roadmap. Thanks.

**Comment by bnusunny** [comment]
+1

**Comment by jgleonard** [comment]
Is there a timeline associated with this yet?

**Comment by micacardillo** [comment]
We're ready to jump on testing it as soon as the preview is available.

**Comment by johnnyshields** [comment]
👍 Same here, eagerly awaiting developer preview

**Comment by gaochundong** [comment]
still coming soon?

**Comment by gyj0825** [comment]
At what stage is it currently?

**Comment by zhang-zhenqing** [comment]
when is EKS ready in aws china? is there a time line?

**Comment by groodt** [comment]
Any updates on this?

**Comment by fanxu** [comment]
Any update?

**Comment by icyxp** [comment]
Any updates on this?

**Comment by ranger-huang** [comment]
Any updates on this ?

**Comment by networkshb** [comment]
Any updates on this ?

**Comment by zhang-zhenqing** [comment]
Any updates on this ?

**Comment by groodt** [comment]
This must be close now! :) Any news?

**Comment by icyxp** [comment]
Just Shipped

**Comment by mikestef9** [comment]
Happy to announce that EKS is now generally available in the AWS Ningxia (cn-northwest-1) region!

- [What's new post](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-eks-now-available-aws-china-beijing-sinnet-ningxia-nwcd/)
- [EKS documentation & AMIs](https://docs.amazonaws.cn/en_us/eks/latest/userguide/eks-optimized-ami.html)

**Comment by groodt** [comment]
Thanks to you and the team for all the hard work @mikestef9

**Comment by groodt** [comment]
What's the service Principal name?

```
An error occurred: Invalid principal in policy: "SERVICE":"eks.amazonaws.cn"
```

**Comment by mikestef9** [comment]
@groodt is the IAM role created in a China region? You can't use a non China IAM role in a China region

**Comment by groodt** [comment]
Yup, the role is in China.

**Comment by groodt** [comment]
Our role is in China. 

ARN looks as follows:
```
arn: arn:aws-cn:iam::${accountid}:role/${rolename}
```

Trust relationship looks as follows:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

The rolow has the following managed policies attached:
```
AmazonEKSClusterPolicy
AmazonEKSServicePolicy
```

**Comment by mikestef9** [comment]
Hi @groodt would recommend you open a support ticket to further troubleshoot

**Comment by groodt** [comment]
Found the issue. We have a permission boundary on the role and needed to allow:
```
iam:ListAttachedRolePolicies
```

Works now! Apologies for any noise.
