### ISSUE TITLE
[EKS ARM] Request: Mix ARM and Non-ARM based NodeGroups in the same cluster

### ISSUE THREAD

**Issue by zhujik** [aws/containers-roadmap#776]
**Describe the issue**
For various reasons, one might want to run instance of type a1 and non-a1 in the same cluster. With the current setup, this is not possible, since the CNI and the kube-proxy deployments are geared towards ARM node. I tried to change the deployments for those to run both types in the same cluster, but I am not able to start pods on the a1 worker nodes this way.

**To Reproduce**
My setup:
1 x ng with t3.small produced via eksctl 
1 x ng with a1.xlarge produced via CF (the tutorial here)
* Change pod, service account etc names of aws-k8s-cni-arm64.yaml and kube-proxy-arm-1.14.yaml to not overlap with existing aws-node and kube-proxy deployments
* Force coredns to be scheduled on t3.small ng
* Try to start pods on the a1.xlarge worker node group; result in endless restarts and errors

**Expected behavior**
Pods run on the a1.xlarge worker nodes

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/31599908/75653340-b2d15a80-5c5d-11ea-9714-49404571a848.PNG)

**Cluster Information**
k8s 1.14 eu-central-1

**Comment by mikestef9** [comment]
This functionality is available as part EKS generally available support for Arm-based instances. See launch [blog](https://aws.amazon.com/blogs/containers/eks-on-graviton-generally-available/) for more details.
