### ISSUE TITLE
[EKS] [helm chart for container insights]: I would like a helm chart for installing CloudWatch Container Insights

### ISSUE THREAD

**Issue by nbrandaleone** [aws/containers-roadmap#779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

I would like an official helm chart for Container Insights.  We have selected helm as our package management solution, and would like all aws components to be managed via a chart.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Currently it is possible to install container insights via a script, or manually.  I would like a helm chart since it the de-facto package management solution for kubernetes.

**Are you currently working around this issue?**
Yes.

How are you currently solving this problem?
I am currently using the installation script.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by bollohz** [comment]
Hello there. I have created a Helm Chart for CW Container Insights. 
It works with statsd directly and daemonset configuration. 

You can find it here. 

https://github.com/bollohz/cw_insights

Hope it helps.

FB.

**Comment by kristianfzr** [comment]
Hi there,

Just to ask as helm is used widely as a package manager by many and especially with terraform for automated IaC deployments, will this be considered anytime soon in the containers-roadmap?

Thank you in advance!

**Comment by bugok** [comment]
Does this announcement help? https://aws.amazon.com/about-aws/whats-new/2022/02/amazon-cloudwatch-container-helm-chart-distro-opentelemetry/

Looks like there's a helm chart for this now: https://github.com/aws-observability/aws-otel-helm-charts/tree/main/charts/adot-exporter-for-eks-on-ec2

**Comment by strongpauly** [comment]
Does the [EKS addon](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-addon.html) do what you want?  Could that be added to any existing EKS IaC?

**Comment by zizzencs** [comment]
The EKS addon definitely helps and it's easy to add to the existing terraform modules, which solves the issue for me.

However it is not a Helm chart - some other users might prefer to use Helm and/or ArgoCD for this purpose.

**Comment by mikestef9** [comment]
You could use ACK to manage the addon in a Kubernetes native way

https://aws-controllers-k8s.github.io/community/reference/eks/v1alpha1/addon/

**Comment by lisguo** [comment]
There is now a helm-chart to install container insights and application signals: https://github.com/aws-observability/helm-charts/tree/main/charts/amazon-cloudwatch-observability

This is the equivalent of the Amazon CloudWatch Observability EKS Add-On
