### ISSUE TITLE
[EKS] [request]: Support in-place upgrade to add Envelope encryption to existing EKS

### ISSUE THREAD

**Issue by marcincuber** [aws/containers-roadmap#782]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to see EKS Support in-place upgrade to add Envelope encryption to existing EKS clusters. Managed control-plane supports in-place upgrades so not supporting the same thing for additional features doesn't make sense.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Destroying and creating new EKS clusters for every new feature is not feasible in my opinion. I do agree that we should be treating clusters like cattle but when you run prod apps with external-dns, alb-ingress-controller etc. it is not a simple task to migrate everything in one go.

**Are you currently working around this issue?**
The only way to add envelope encryption is to re-create the cluster.

**Comment by mikestef9** [comment]
https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-eks-supports-adding-kms-envelope-encryption-to-existing-clusters/
