### ISSUE TITLE
[EKS]: Kubernetes v1.12 End of Support (May 11, 2020)

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#786]
In line with the Kubernetes community support for Kubernetes versions, Amazon EKS 1.12 is now deprecated and will no longer be supported on **May 11, 2020**. On this day, you will no longer be able to create new 1.12 clusters and all EKS clusters running Kubernetes version 1.12 will be updated to the latest available platform version of Kubernetes version 1.13.

We recommend customers upgrade existing 1.12 clusters and worker nodes to at least 1.13 as soon as practical.

Learn more:
* [Updates to Amazon EKS Version Lifecycle](https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/)
* [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by connor-cress** [comment]
Could this have any **effect** on the **EKS** Support in the **AWS** - **Cape Town Data Centre**?
