### ISSUE TITLE
[EKS ARM] Nodes not joining the cluster

### ISSUE THREAD

**Issue by RaeesBhatti** [aws/containers-roadmap#787]
**Describe the issue**
I followed the [EKS ARM preview guide](https://github.com/aws/containers-roadmap/tree/256756a6738706acfeabd3745ec851dc1fa5704d/preview-programs/eks-arm-preview) to every detail but the nodes in the created node group are not joining the cluster. I keep getting `No resources found.` when doing `kubectl get nodes`, even after waiting for 15 minutes.

**To Reproduce**
1. Follow the guide to create and configure Kubernetes 1.14 cluster in `us-east-2` region
2. Follow step 9 and swap in the ARN from newly created node groups stack
3. Apply the configuration
4. `kubectl get nodes` results in `No resources found.` even after 15 minutes

**Expected behavior**
Expected the node group to join the cluster

**Screenshots**
NA

**Cluster Information**
Kubernetes version: 1.14
Region: US East 2

**Additional context**
NA

**Comment by RaeesBhatti** [comment]
There's also confusion around which subnet should one select for the new node group. `eksctl` created 6 subnets in my instance, 3 of them were public and the other 3 were private.

**Comment by mikestef9** [comment]
Closing this issue, as EKS support for Arm instances is generally available and instructions have been updated. See launch [blog](https://aws.amazon.com/blogs/containers/eks-on-graviton-generally-available/) for more details.
