### ISSUE TITLE
[Fargate] [request]: Support for ARM based Tasks

### ISSUE THREAD

**Issue by peterjuras** [aws/containers-roadmap#793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I would like to launch and run ARM based tasks on Fargate.

**Which service(s) is this request for?**

ECS - Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

ARM based instances are cheaper than other EC2 instance types while still allowing a great number of use cases like web servers. It would be great to have the same cost savings when using ARM with Fargate.

**Are you currently working around this issue?**

Maintaining your own ECS cluster with ARM based instances.

**Comment by janaka** [comment]
and EKS

**Comment by pieterza** [comment]
+1

**Comment by kcolemangt** [comment]
This is blocked because firecracker only runs on Intel. ARM and AMD are in developer preview now. Contribute or follow the progress:

https://github.com/firecracker-microvm/firecracker/milestone/7

https://github.com/firecracker-microvm/firecracker/labels/Feature%3A%20CPU%20Support%3A%20ARM

**Comment by akshayram-wolverine** [comment]
Hi! We are currently scoping this request. To help better understand your use case, would really appreciate answers/thoughts/opinions on the following questions or other questions if you feel they are pertinent:

1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
2. Do you build multi arch images today?
3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
4. If yes, how would you incentivize developers to opt in to ARM?
5. What languages do your applications use?
6. What task sizes do you need on ARM?
7. Do you need any storage or network requirements? 
8. What partner tools do you use?

**Comment by alex** [comment]
1. We build in CodeBuild
2. Not yet.
3. We can't swap the architecture for runs without making changes to container builds first.
4. Cost/performance are the obvious ones :-)
5. Go
6. Same as x86, we'd be porting existing systems (though we'd also really like it if there were large instance sizes for fargate)

**Comment by ecliptik** [comment]
> How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?

Our images running on EKS are built either using Jenkins or Gitlab CI/CD, usually a combination of `docker build`, `docker tag` and `docker push`.

> Do you build multi arch images today?

We use `docker buildx` to create a multi-arch manifest and then push both architecture images to ECR and then the manifest. Typical workflow follows the steps in this guide: https://aws.amazon.com/blogs/containers/introducing-multi-architecture-container-images-for-amazon-ecr/

> What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?

Most likely not, as all of our apps are architecture agnostic, `java`, `python`, `ruby`, although there may be a few architecture specific dependencies we may need to tweak

> If yes, how would you incentivize developers to opt in to ARM?

Although when we've discussed it with them they were mostly excited about the cost savings and potential for ARM to out-perform x86.

> What languages do your applications use?

`java`, `scala`, `python`, `ruby`

> What task sizes do you need on ARM?

Usually 4-8 CPUs and 8Gb memory, although there are some workloads that could benefit from 32+ CPUs and 64+Gb memory.

> Do you need any storage or network requirements?

We run almost everything stateless, and as long as there is enough scratch storage on a pod for some simple temp files it's not really noticed. Network-wise having up to 10GiB would be nice.

> What partner tools do you use?

Gitlab is probably the biggest 3rd party tool that would be involved with building multi-arch docker images and running CI/CD jobs on Fargate. See this comment for how we would like to Fargate for running Gitlab jobs and building images: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4358#note_433886014

**Comment by sjurtf** [comment]
1. Using Gitlab CI with Gitlab runners on EC2 (arm/x86). Images are also built locally on dev machines for local/dev environments.
2. Yes
3. If the provided image to a task definition is multi arch, AWS could, in my option, transparently select the underlying architecture to run that given task on. That said, I would expect ARM runners to cost less than x86_64 runners, similar to what we see today with EC2 Graviton pricing. So to be able to force ARM for cost reasons would be highly appreciated. Making the auto-selection of architecture opt-in during a beta is probably a good idea.
4. Cost savings/performance gains
5. Golang / Java / Python
6. Same as today's configurations. I would also point out these issues (#110 and #79), which I would love to see some development on. They suggest to decouple CPU and RAM configuration and additionally add lower configurations to use for small services. Some would also like to see higher configurations of CPU and RAM. 
7. No
8. -

**Comment by janaka** [comment]
pertinent:
For context the uncertainty is because we are only just starting the process of making the move from ECS to EKS. Moves to Arm would come in that timeline. 
1. CI/CD 
2. Not yet. 
3. Not sure yet. Maybe ideally not. 
4. .NET Core / C# 
5. Not sure yet 
6. Not sure yet
7. Not sure yet

**Comment by akshayram-wolverine** [comment]
Thanks for the responses and noted on both ECS and EKS support! @janaka @sjurtf @ecliptik  What about dev workstations to help developers test and signal if applications are ARM compatible? Is that process easy today? Would you like it simplified?

**Comment by pieterza** [comment]
+1

**Comment by pieterza** [comment]
I would like Fargate to support ARM based tasks because:

*  I'd like to switch our CI/CD worker nodes to use less expensive ARM cores to build/test/publish docker images.
   This allows me to for example use fewer actual instances to achieve the same number of jobs per hour.

*  Unless we cross-compile back to x86 (buildx or what have you), we cannot deploy the arm images to Fargate

Thus, we can only switch our (CPU heavy) builds to cheaper ARM based instances, if the resulting images can run on Fargate.

**Comment by janaka** [comment]
@akshayram-wolverine I don't have an answer for you on the dev workstation question because we are early on in this journey. Workstations are on x86 still. Hardware will change organically over the coming years as refresh cycles come in.

Our main interest is the price-performance gain for web app workloads. So expecting that to be reflected in Fargate pricing. The code build use case comes hand-in-hand with the web app hosting use case. Hope that helps.

**Comment by kapilt** [comment]
docker buildx and buildkit, significantly ease multi-arch building from an x86 dev environment, which automates the cross build via qemu

https://github.com/docker/buildx#building-multi-platform-images
https://mirailabs.io/blog/multiarch-docker-with-buildx/

also looking at a cost consideration for ARM fargate, images builds via pipelines (github actions and codebuild) using buildx for cross arch.

**Comment by JohnPreston** [comment]
> Hi! We are currently scoping this request. To help better understand your use case, would really appreciate answers/thoughts/opinions on the following questions or other questions if you feel they are pertinent:
> 
> 1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
> 2. Do you build multi arch images today?
> 3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
> 4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?
> 5. What languages do your applications use?
> 6. What task sizes do you need on ARM?
> 7. Do you need any storage or network requirements?
> 8. What partner tools do you use?

1. CodeBuild
2. Yes
3. We could switch rather transparently without changes to the apps
4. No, no need for dev workstations using ARM although a fair amount of people play with Pis and alike
5. Python / Java
6. From 0.25vCPU to 1vCPU sizes so far, rarely more than 2vCPUs and that is already a big one. RAM averages at 1GB, max so far at 4GB
7. Yes, obviously awsvpc mode and local storage as defined in Fargate 1.4.0 really. EFS rarely used but defo has to be an option
8. AWS only.



> https://github.com/docker/buildx#building-multi-platform-images
> https://mirailabs.io/blog/multiarch-docker-with-buildx/

For those of you using AWS Codebuild (FTW), that might be of help
https://blog.compose-x.io/posts/docker-images-multi-arch-manifest-build-with-aws-codebuild-batch/index.html

**Comment by likeabbas** [comment]
1. CDKPipeline
2. No
3. Transparently
4. Cost. No because we use docker/virtualization
5. Rust, Java, Golang, Python
6. .25vCPU - 12vCPU, .5GB - 64GB
7. Yes. awsvpc, ephemeral storage, EFS, EBS
8. CDK for Terraform at some point

**Comment by tehGoti** [comment]
1. Gitlab CI/CD with Runners on EC2
2. Yes
3. We can switch transparently, yes
4. Cost and performance - we are doing heavy computing in web servers and know from other applications using EC2 fargate that this will run much faster and cheaper in ARM
5. Go
6. 4vCPU & 8GB RAM
7. No special requirements here
8. None

**Comment by mhat** [comment]
1. CICD
2. Not yet, but we will to support developers w/ Apple-ARM.
3. Transparent to minimal 
4. Folks will be getting Apple-ARM devices. 
5. Ruby, Go, Java, TypeScript
6. Same -- would love more CPUs in general
7. Depends
8. TF

**Comment by nicois** [comment]
1. CI/CD, using AWS autoscaling group. Ideally it would have a mix of arm64 and amd64 runners but we would happily use just arm64 at a pinch
2. no
3. no need to opt in, as pushes to fargate are via CI
4. N/A
5. python / node
6. 2-4 VCPUS 4-8Gb RAM
7. nothing special
8. terraform

**Comment by negrusti** [comment]
1. Gitlab CI/CD
2. No
3. We will need changes in CI/CD pipeline, nothing to do for devs
4. No they won't
5. Python, NodeJS, Golang, PHP
6. 1GB to 8GB RAM
7. Not at the moment, but EFS connectivity might be required in the future

**Comment by KTamas** [comment]
1. Gitlab CI/CD
2. No because no support for it in Fargate yet
3. Kind of, we'll reconfigure the CI and devs will have to use buildx if they want to push a container manually but that's not that common
4. no
5. TypeScript
6. Whatever Fargate provides right now
7. Just what Fargate already has
8. None, we use the AWS CDK

**Comment by iandelahorne** [comment]
> Hi! We are currently scoping this request. To help better understand your use case, would really appreciate answers/thoughts/opinions on the following questions or other questions if you feel they are pertinent:
> 
>     1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?

CI/CD on CircleCI
 
>     2. Do you build multi arch images today?

Not yet.

>     3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?

Most likely not.
 
>     4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?

Cost. We can start by having devs run tests/build on arm64 instances and then consider ARM laptops if needed.
 
>     5. What languages do your applications use?

Python, Node/TypeScript and Java. 

>     6. What task sizes do you need on ARM?

1024-4096 CPU
 
>     7. Do you need any storage or network requirements?

Not beyond ephemeralStorage
 
>     8. What partner tools do you use?

CircleCI, docker Buildkit.

**Comment by tarfeef102** [comment]
> Hi! We are currently scoping this request. To help better understand your use case, would really appreciate answers/thoughts/opinions on the following questions or other questions if you feel they are pertinent:
> 
> 1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
> 2. Do you build multi arch images today?
> 3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
> 4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?
> 5. What languages do your applications use?
> 6. What task sizes do you need on ARM?
> 7. Do you need any storage or network requirements?
> 8. What partner tools do you use?

1. CI/CD
2. No
3. No, DevOps could handle integrating multi-arch where applicable to be largely invisible
4. We would likely have some people on ARM, yes. Apple's M1 macbooks help a lot in this regard
5. NodeJS, python are probably the biggest
6. As small as the minimum to 4GB+ of RAM (and the corresponding CPU size)
7. Nothing notable
8. Large list, nothing that should really impact this

**Comment by Nexus357ZA** [comment]
> 1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
> 2. Do you build multi arch images today?
> 3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
> 4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?
> 5. What languages do your applications use?
> 6. What task sizes do you need on ARM?
> 7. Do you need any storage or network requirements?
> 8. What partner tools do you use?

1.  CI/CD
2. Yes
3. We would need to opt-in
4. This will be evaluated on a case by case basis 
5. Go and Python primarily
6. Similar to what is currently available 
7. Yes, similar to what is currently available 
8. There's an extensive list

**Comment by jonathannaguin** [comment]
> 1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
> 2. Do you build multi arch images today?
> 3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
> 4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?
> 5. What languages do your applications use?
> 6. What task sizes do you need on ARM?
> 7. Do you need any storage or network requirements?
> 8. What partner tools do you use?


1. CI/CD system (Jenkins).
2. Yes
3. We can switch transparently.
4. We can use buildx to build against ARM. Mac M1 are also helpful.
5. Java primarly and some Python.
6. Whatever is currentl available.
7.  Whatever is currentl available. 
8. Docker BuildX, Jenkins, CloudFormation.

**Comment by gilbahat** [comment]
> Hi! We are currently scoping this request. To help better understand your use case, would really appreciate answers/thoughts/opinions on the following questions or other questions if you feel they are pertinent:
> 
> 1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
> 2. Do you build multi arch images today?
> 3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
> 4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?
> 5. What languages do your applications use?
> 6. What task sizes do you need on ARM?
> 7. Do you need any storage or network requirements?
> 8. What partner tools do you use?

1. CI/CD system
2. Not yet
3. We can switch transparently
4. No need for arm workstations, developers will be opted in automatically
5. NodeJS, go, python, ruby, java, haskell, php
6. Whatever is currently available
7. Nothing in particular
8. Nothing in particular. We expect our load to migrate to arm64 cleanly and will rely on the CI/CD pipeline.

**Comment by rkujawa** [comment]
Hi. Graviton in Fargate on EKS, plz.

>     1. How do you build your containers? Do developers build them on their laptop or it is done in a CI/CD system?
1. CI/CD
>     2. Do you build multi arch images today?
2. No (no need yet)
>     3. What if you switched transparently to ARM behind the scenes? Would you need developers to opt in?
3. Yes, but this is already happening (non-Fargate EKS nodes on ARM)
>     4. If yes, how would you incentivize developers to opt in to ARM (eg. cost)? Would developers need ARM dev workstations to test?
4. Not a problem in our case, since we run full k8s-based development environment in EKS (i.e. developers have the IDE running on their workstations but the code actually gets executed in EKS on all stages of development)
>     5. What languages do your applications use?
5. PHP, C#
>     6. What task sizes do you need on ARM?
6. Same as on x86
>     7. Do you need any storage or network requirements?
7. Same as on x86
>     8. What partner tools do you use?
8. None, as far as I am aware

**Comment by SaloniSonpal** [comment]
We just launched ECS/Fargate powered by AWS Graviton2 Processors:
https://aws.amazon.com/about-aws/whats-new/2021/11/aws-fargate-amazon-ecs-aws-graviton2-processors/

**Comment by iancward** [comment]
An issue has been opened for EKS: https://github.com/aws/containers-roadmap/issues/1629
