### ISSUE TITLE
[ECS] [request]: Service auto scaling support when using the blue/green deployment type. 

### ISSUE THREAD

**Issue by arekdon** [aws/containers-roadmap#794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

I would like to see support for Service auto scaling with CodeDeploy deployment techniques. 
Accordingly to documentation:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-bluegreen.html

it is not possible right now. 

**Which service(s) is this request for?**

ECS, CodeDeploy

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

It is a common practice to use service auto-scalling in a projects I currently participate. It is one of the best method to optimize your cost and be 'elastic' accordingly to what AWS promotes. Impact is quite high as it is blocking us to use more advanced methods of deployments. It affects most of ours microservices. 

**Are you currently working around this issue?**
How are you currently solving this problem?

There is no workaround. We have to rely on rolling updates.

**Comment by dbednall** [comment]
To add, because I suspect it is for the same reasons as with CodeDeploy; a deployment controller type of `EXTERNAL` has the same limitation thus preventing ECS customers creating an alternative system where ECS/CodeDeploy falls short.

> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-external.html

It is a is a big pain point being limited to only a Rolling Update configuration when in used conjunction with Service Autoscaling. I would consider both features "essential" however Autoscaling has to win out, forcing the app deployment approach to be suboptimal.

**Comment by jg-edt** [comment]
This appears to be supported now according to https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-type-bluegreen.html, so this issue can probably be closed.

From the documentation:
>  Amazon ECS service auto scaling is supported when using the blue/green deployment type. When a new deployment is started, if there are scaling activities occurring then CodeDeploy will wait 5 minutes before starting the deployment. If the scaling activities complete within 5 minutes, the deployment will continue. If the scaling activities do not complete within 5 minutes, the deployment will fail.

**Comment by maskerade** [comment]
Is this fixed? 
The ECS documentation still states that service auto scaling is not supported for either `BLUE/GREEN` or `EXTERNAL`

**Comment by pyranja** [comment]
> This appears to be supported now according to https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-type-bluegreen.html, so this issue can probably be closed.
> 
> From the documentation:
> 
> > Amazon ECS service auto scaling is supported when using the blue/green deployment type. When a new deployment is started, if there are scaling activities occurring then CodeDeploy will wait 5 minutes before starting the deployment. If the scaling activities complete within 5 minutes, the deployment will continue. If the scaling activities do not complete within 5 minutes, the deployment will fail.

The documentation seems to have changed and now states again that auto scaling is not supported with blue/green deployments.

**Comment by c-py** [comment]
The [documentation was updated again](https://github.com/awsdocs/amazon-ecs-developer-guide/commit/b27f3fc83ebe8de97fb1eed58569439f5c8ad987) and it says service auto scaling is supported with blue/green deployments. The docs, as at 20/01/2021, read:

> Amazon ECS service auto scaling is supported when using the blue/green deployment type. The following should be considered when using service auto scaling:

> If a service is scaling and a deployment starts, the green task set is created and CodeDeploy will wait up to an hour for the green task set to reach steady state and won't shift any traffic until it does.

> If a service is in the process of a blue/green deployment and a scaling event occurs, traffic will continue to shift for 5 minutes. If the service doesn't reach steady state within 5 minutes, CodeDeploy will stop the deployment and mark it as failed.
