### ISSUE TITLE
[EKS] [request]: Privilege Escalation using aws-auth configmap

### ISSUE THREAD

**Issue by eightnoteight** [aws/containers-roadmap#795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Make a better alternative to aws-auth configmap, so that we can avoid privilege escalation in kubernetes.

If I give permissions to configmap update permissions to anyone then they can change the aws-auth configmap and give themselves admin permissions to the eks cluster by allowing an IAM role to admin permissions

**Which service(s) is this request for?**
EKS

**Comment by gothrek22** [comment]
Only if you scope permissions to all namespaces. Normal users shouldn't have access to the kube-system namespace. If you want to be security conscious, then be that all the way :)

**Comment by mikestef9** [comment]
Addressed with #185
