### ISSUE TITLE
[ECR] [image tag mutability CloudFormation Support]: Add CloudFormation Support to image tag mutability

### ISSUE THREAD

**Issue by jonjozwiak** [aws/containers-roadmap#808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Image Tag Mutability was released middle of 2019 (https://github.com/aws/containers-roadmap/issues/169), but there is no support to configure it in CloudFormation.  I could create a custom resource, but would rather have native support in AWS::ECR::Repository.  

**Which service(s) is this request for?**
ECR / CloudFormation

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
From a security perspective I want to ensure container image tags are immutable.  However, everything I deploy is as code and CloudFormation does not easily support this today.  

**Are you currently working around this issue?**
How are you currently solving this problem?
I'm using Terraform to work around the problem.  It's supported in their ecr_repository module: 
https://www.terraform.io/docs/providers/aws/r/ecr_repository.html

**Comment by njgibbon** [comment]
This feature has shipped according to aws-cloudformation/aws-cloudformation-coverage-roadmap#222.

**Comment by rpnguyen** [comment]
Shipped!
