### ISSUE TITLE
[EKS]: Support For Kubernetes 1.18

### ISSUE THREAD

**Issue by marcincuber** [aws/containers-roadmap#809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support Kubernetes 1.18

**Which service(s) is this request for?**
EKS

**Comment by gudipatiharitha** [comment]
Hi , could you please let us know the planned date for avaibility of this task in AWS,  we need to plan our deployment based on that , we have a dependancy on CSI proxy for windows added in 1.18. Thank you

**Comment by abdennour** [comment]
Also we have a dependency of startupProbe which is beta feature in 1.18 
https://github.com/aws/containers-roadmap/issues/947

**Comment by mikhailjan** [comment]
We could really use the HorizontalPodAutoscaler behaviour functionality that was added in the v1.18 v2beta2 API. https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior.

**Comment by stijndehaes** [comment]
For those who didn't see it yet, the EKS documentation now contains a release calendar with future releases in it:
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

**Comment by limewxr** [comment]
When can we know the exact release date of EKS 1.18? 😁

**Comment by lwimmer** [comment]
> When can we know the exact release date of EKS 1.18?

When it is released :grimacing:

**Comment by mikestef9** [comment]
Kubernetes version 1.18 is now available on EKS!

[Documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.18)
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-kubernetes-version-1-18/)
[eksctl support](https://github.com/weaveworks/eksctl/releases/tag/0.30.0-rc.1)

**Comment by groodt** [comment]
Upgraded our clusters to this today! Thanks! Smooth so far!

One issue we saw during the upgrade:

It is advised to use CoreDNS 1.7.0 in the [docs](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html).

When doing so, we got CrashLoopBackoff due to:
```
plugin/kubernetes: /etc/coredns/Corefile:6 - Error during parsing: unknown property 'upstream'
```

So we rolled back to 1.6.6 and everything is working. Is this a documentation issue?

**Comment by gitfool** [comment]
@groodt looks like it. (I filed #1115 after it failed for me too.)

**Comment by manojkumarbardhan** [comment]
Can anyone suggest why I am getting this error for my particular node "failed to garbage collect required amount of images. Wanted to free 7290190233 bytes, but freed 0 bytes" ? I am using eks 1.18 version , it seems the memory consumption is gradually more and the usage reaching upto 88% & more. I can see many pods are getting evicted after that. Any suggestion would be helpful for me.
