### ISSUE TITLE
[EKS] [request]: Managed Node Groups support for all AMI release versions

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#810]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Managed Node Groups should support any EKS AMI release version. Today, it only supports the most recent release version.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Having the ability to test and deploy applications against a specific AMI release version. Today, when managed node groups supports a new AMI, you can no longer create a node group with a previous release version.

**Comment by ajithreddygeth** [comment]
+1

**Comment by ajithreddygeth** [comment]
+1

**Comment by ajithreddygeth** [comment]
@rtripat  need help on this

**Comment by STollenaar** [comment]
What is the reason why this is not implemented yet? People can bypass this behaviour by not using a nodegroup and making autoscaling groups and such, which does allow the older AMI's. 
Any suggestions on how people could currently test migrating from older to newer AMI's using these node groups?

**Comment by dgarbus** [comment]
This needs to be a higher priority after the debacle in https://github.com/awslabs/amazon-eks-ami/issues/563

**Comment by STollenaar** [comment]
> 
> 
> This needs to be a higher priority after the debacle in [awslabs/amazon-eks-ami#563](https://github.com/awslabs/amazon-eks-ami/issues/563)

Agreed. Luckily I am not using the node groups directly as I am waiting for this feature, but seeing that this happened again raises my question. Why wasn't this implemented yet?

**Comment by iliastsi** [comment]
According to @rtripat, this is now work in progress (see https://github.com/awslabs/amazon-eks-ami/issues/563#issuecomment-731258805). This is awesome. It would be great if you could provide a timeline of when you could have this available.

**Comment by wedge-jarrad** [comment]
Bumped into this today.

Our use case is testing cluster upgrade automation. Without the ability to create managed node groups at old versions we must wait for updates to become available for our existing node groups.

**Comment by mikestef9** [comment]
You can now create or update a managed dode group to any AMI release version

**Comment by elementalvoid** [comment]
@mikestef9 👋

* Are there any docs that you can share with us on this feature?
* This might be a stretch (?) but do you know if `eksctl` has support for it?

**Comment by mikestef9** [comment]
The EKS API documentation is up to date, for the _releaseVersion_ param.

https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html

By default, the latest AMI release version is used if not specified. But you can now any specify version, which you can find in [docs](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html).

Eventually, we'll build an API to return available versions, tracked in #771 

This is not yet supported in eksctl. I just opened an issue there to track https://github.com/weaveworks/eksctl/issues/3506

**Comment by elementalvoid** [comment]
That's great! Thank you!

**Comment by cPu1** [comment]
> @mikestef9 
> 
> * Are there any docs that you can share with us on this feature?
> * This might be a stretch (?) but do you know if `eksctl` has support for it?


@elementalvoid This is out in https://github.com/weaveworks/eksctl/releases/tag/0.45.0-rc.1 (PR: https://github.com/weaveworks/eksctl/pull/3544)
