### ISSUE TITLE
[EKS] Cluster SLA updated to 99.95%

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#811]
The [EKS SLA](https://aws.amazon.com/eks/sla/) is now 99.95% for **all** Amazon EKS clusters.

Previously, Amazon EKS offered an SLA of 99.9%. Now, EKS has increased the SLA to 99.95%. The new SLA doubles the availability guarantee for the EKS cluster endpoint.

This new SLA is applicable for all EKS clusters in all regions where Amazon EKS is available.

See the new SLA: https://aws.amazon.com/eks/sla/

**Comment by igrowheart** [comment]
Hi @tabern ,
We know it's an incredible improvement on SLA! 
Is it possible to share more insights on the architecture level change? For example, how do you do to make this happen? By introducing more replicas of control plane nodes?
