### ISSUE TITLE
EKS Tagging

### ISSUE THREAD

**Issue by praveenchandran** [aws/containers-roadmap#82]
Hello,

Are there any plans to enable tagging for EKS clusters ? 

Thanks 
Praveen Chandran

**Comment by derBroBro** [comment]
We see the need also. Reason is that EKS is currently showing up as untagged costs.

**Comment by mikesimons** [comment]
Given the importance of tags to managing AWS resources how does this keep getting overlooked on new AWS services?

**Comment by tabern** [comment]
Yes @praveenchandran - we are working on this.

**Feature details**
Ability to tag EKS clusters. EKS will allow you to associate [AWS tags](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/tag-editor.html) to your EKS clusters for organization and cost allocation.

**Note**
This is solely tagging support for the EKS cluster object within AWS. This is not support for using EKS to propagate tags to other AWS resources. For this feature proposal see https://github.com/aws/containers-roadmap/issues/374

**Comment by AlexHornDev** [comment]
glad it's being worked on - we'll use it when it's ready. Any ETA ? 2019 ? 2020 ? thanks !

**Comment by tabern** [comment]
@AlexHornDev coming soon!

**Comment by tabern** [comment]
Amazon EKS now supports adding AWS tags to your clusters.

These tags can be used to control access to the EKS API for managing the cluster using IAM.

**Note** Tags added to an EKS cluster are specific to the AWS EKS cluster resource, they do not propagate to other AWS resources used by the cluster such as EC2 instances or load balancers. Today, cluster tagging is supported for all new and existing EKS clusters via the AWS API, Console, and SDKs. 

Support for tagging clusters using CloudFormation and the eksctl command line tool is coming soon. We are updating the AWS console to support adding tags to EKS clusters. This change takes a little while to deploy and will become available region by region over the next week.

**Links**
* [EKS tagging documentation](https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html)
* [Announcement post](https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-supports-cluster-tagging/)

**Comment by AlexHornDev** [comment]
fantastic !!! nice work !!!

**Comment by b2jrock** [comment]
@tabern Any chance this can get propagated to cloudformation? It'd be convenient for implementation in `eksctl` since that uses cloudformation under the hood. Otherwise it'll have to make separate API calls to tag after the fact. It's not listed in the docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html and indeed when I try it I get `Property validation failure: [Encountered unsupported properties in {/}: [Tags]]`.

**Comment by b2jrock** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/200 - Looks like it's tracked here if anyone else finds this thread first as I did.
