### ISSUE TITLE
[EKS] [request]: EKS Fargate in Paris

### ISSUE THREAD

**Issue by SBerda** [aws/containers-roadmap#823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

I would like to use EKS Fargate in Paris

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

I would like to use EKS Fargate in Paris

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

Using ECS

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by PatMyron** [comment]
https://github.com/aws/containers-roadmap/issues/620

**Comment by tabern** [comment]
EKS/Fargate is now available in Paris (eu-west-3)

[Documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html)
