### ISSUE TITLE
vpc-admission-webhook relies on deprecated nodeSelector

### ISSUE THREAD

**Issue by rparsonsbb** [aws/containers-roadmap#836]
Currently in order for the vpc-admission-webhook to patch a pod to provide the vpc-resource-controller with the IP for a windows pod the nodeSelector must be `beta.kubernetes.io/os: windows`.  If `kubernetes.io/os` nodeSelector is used then it is not detected as a windows pod by the service.

This tag has been deprecated in favor of `kubernetes.io/os` and the vpc-admission-webhook should either check for the current tag **and** the deprecated flag, or only the current nodeSelector.

**Comment by abhipth** [comment]
Hi @rparsonsbb, we have fixed the issue as part of v0.2.3 release of vpc-admission-webhook. I would recommend you to update to the [latest version ](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html) of vpc-resource-controller and vpc-admission-webhook to get all the fixes.

Closing the issue. Please feel free to re open in case you run into the issue with the latest release.
