### ISSUE TITLE
[EKS] [Request]: Support NLB access log annotation

### ISSUE THREAD

**Issue by GnatorX** [aws/containers-roadmap#837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please add support to enable access logs via annotations similar to ALB
`alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-access-log-bucket,access_logs.s3.prefix=my-app`

**Which service(s) is this request for?**
This could be EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

This helps centralizing all NLB related information into the yaml that deploys the NLB rather than forcing user to create a separate process to add access logs. 

**Are you currently working around this issue?**
Directly going into NLBs and adding the access log

**Comment by M00nF1sh** [comment]
@GnatorX 
Access logs is already supported: https://github.com/kubernetes/kubernetes/commit/33e6465084c9de9e21a8b796b35479567a6ecc96

We chosen to reuse the old annotation for CLB.
