### ISSUE TITLE
[ECS]: ability to remove capacity provider from ECS -service-

### ISSUE THREAD

**Issue by toredash** [aws/containers-roadmap#838]
**Tell us about your request**
Once a capacity provider is added to a ECS **service**, it is impossible to remove it unless you re-create the service (delete / create).

**Which service(s) is this request for?**
ECS and Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
One can add a capacity provider to a ECS service that does not have this present like this:
`aws ecs update-service --cluster ecs_cluster --service ecs_service --force-new-deployment --capacity-provider-strategy capacityProvider="ecsCap",weight=1`

The same command can be used to change the current assigned capacity provider.

There is no way to remove the capacity provider once it is added.

Useful if you want to migrate away from ECS capacity providers, or want to remove the capacity provder link for some services.

**Are you currently working around this issue?**
Duplicating all services in a cluster with a new name, then recreate all previously services with new capacity provider. 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by anosulchik** [comment]
+1

**Comment by briancurt** [comment]
This is critical. If you only have one Capacity Provider and you need to change it (which you can't as per [PR-663](https://github.com/aws/containers-roadmap/issues/633), so you have to delete it first) basically you have to delete an entire Service (causing downtime) because you cannot "unset" the Launch Type back to EC2.

**Comment by renanrt** [comment]
this is critical for our business too!!!

**Comment by Clasyc** [comment]
This must be resolved, now we are having an issue where we can't update our service without the downtime because cf can't update service.

**Comment by danielfariati** [comment]
The only reason for my company not to use capacity providers is this issue. This makes us afraid of enabling it.

**Comment by aakarshg** [comment]
This needs to be fixed :) Any update on this ?

**Comment by AbhishekNautiyal** [comment]
Removing Capacity Providers is now supported.  Passing an empty Capacity Provider list will remove Capacity Providers from the service and revert it to the same launch type.  This means that if you previously created (or updated) a service with an ASG Capacity Provider, passing an empty Capacity Provider list will revert the service to using the EC2 launch type. Fargate Capacity Provider can be removed similarly to revert to Fargate launch type.
