### ISSUE TITLE
[FireLens] [request]: Send nanoseconds of a log records to a log router

### ISSUE THREAD

**Issue by pjxiao** [aws/containers-roadmap#839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

* The `awsfirelens` log driver seems not to send nanoseconds of the timestamp of a log record
* Please add an option to enable nanoseconds of timestamps

**Which service(s) is this request for?**

* Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

* A log aggregation service (in my case, DataDog) shows logs sent in the same second in random order
* For instance, multiline traceback string is sent at the same moment and will be shown in random order

**Are you currently working around this issue?**

* Gathering a multiline output into a single line JSON

**Additional context**

* fluent/fluent-bit#572
* Docker's fluentd logging driver won't send nanoseconds unless `fluentd-sub-second-precision` option is enabled

**Attachments**
n/a

**Comment by MeghnaPrabhu** [comment]
Released on ECS EC2 and Fargate.
