### ISSUE TITLE
ECS Dashboard Target Group dropdown length increase: At least double the length of the 'Target group name' dropdown upon ECS Create Service 

### ISSUE THREAD

**Issue by sterichards** [aws/containers-roadmap#84]
**Tell us about your request**
A small change to increase the length of the dropdown described above

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I had 2 target groups named similar with the only difference being at the end of the name. Because of this, I couldn't identify the target groups in the dropdown unless I inspected element via my browser

**Are you currently working around this issue?**
Using inspect element from my browser

**Additional context**
Anything else we should know?

**Attachments**
[]https://imgur.com/a/gteFVqv

**Comment by abby-fuller** [comment]
all fixed!

**Comment by sterichards** [comment]
@abby-fuller Angel

**Comment by stefansundin** [comment]
@abby-fuller If you are curious about other similar usability issues, have a look at my Chrome extension which applies a bunch of CSS improvements throughout the AWS console: https://gitlab.com/stefansundin/aws-console-fixes

It would be great if some of them could be fixed upstream so I don't have to maintain them. And some of the CSS selectors change frequently, which breaks my fixes. :/

Sorry for hijacking this issue! :)
I have tried to report some of these things before but haven't quite gotten through. Thanks!

**Comment by sterichards** [comment]
@abby-fuller The issue has returned - https://ibb.co/sRMMQRS
