### ISSUE TITLE
[ECS] [request]: set LATEST Platform Version to 1.4.0

### ISSUE THREAD

**Issue by monken** [aws/containers-roadmap#840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Starting a Task with platform version `LATEST` starts the task with version 1.3.0 instead of 1.4.0

**Which service(s) is this request for?**
Fargate, ECS

**Comment by mreferre** [comment]
Hi @monken. Thanks for your interest. To give you a bit of background about the LATEST flag, this was a conscious decision we took to allow users to test platform version 1.4 before rolling it out in production. I have covered this in the `A less aggressive move to the LATEST flag` section in the [AWS Fargate platform versions primer](https://aws.amazon.com/blogs/containers/aws-fargate-platform-versions-primer/) blog post we published last week. 

Eager to hear your thoughts re this roll out approach we took.

**Comment by monken** [comment]
Got it! Thanks for the detailed explanation on the strategy.

**Comment by benschwarz** [comment]
> Eager to hear your thoughts re this roll out approach we took. 

@mreferre, I thought there was something wrong with our ECS config when it didn’t automatically get switched to 1.4. 

By choosing the LATEST tag we fully accepted the risk that it might cause a break or incompatibility—to me, that’s the point of the latest tag. To use the most edge version of the stack to explore it as it develops.

I think not updating the LATEST tag was a strange and confusing choice.

**Comment by mreferre** [comment]
Thanks @benschwarz for the feedback. I hear you. As with everything there are pros and cons and finding the right balance isn't easy. If everyone was following best practices (similar to container tags) to not deploy critical workloads (e.g. production) without the LATEST tag, this decision would have been easier to take (and we would have moved the tag to point to 1.4 more lightly). However we know a reasonable amount of customers use LATEST as a shortcut to avoid having to manage tags properly even for critical workloads. When we faced the dilemma between making life easier for customers embracing best practices (you) and move the tag Vs mitigating the risks for customers not fully embracing best practicing we opted for the latter in an effort to be conservative. 

Sorry for the inconvenience.

**Comment by benschwarz** [comment]
@mreferre I get what you're saying, but this actively causes confusion for ALL customers who are using ECS and the `LATEST` tag — not just the customers who decide to ignore your recommendations of how to use the `LATEST` tag.

At some arbitrary date (at least, arbitrary to us), the `LATEST` tag will switch to 1.4. We've no way of knowing when that'll happen and (presumably) there won't be a launch/update announcement from AWS to help us piece together when the update occurred.

I refer you to two points taken from the [AWS Fargate Platform Versions documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html): 

> Platform Version Considerations
> The following should be considered when specifying a platform version:
>   *  When specifying a platform version, you can use either the version number (for example, 1.4.0) or `LATEST`.
>    * To use a specific platform version, specify the version number when creating or updating your service. If you specify `LATEST`, your tasks use platform version 1.3.0.

Point 1 states that 1.4.0 is equivalent to `LATEST`, point 2 says 1.3.0. In actuality it's 1.3.0. 

Can you update the documentation to explain how the `LATEST` tag works and should be used?

**Comment by mreferre** [comment]
@benschwarz that piece of doc was written to mean "you can use either the version number (for example, 1.4.0) or LATEST (1.3.0)." ..... but I can totally see how the way it's written may lead to confusion. I will bring this up to fix the doc and make them more explicit. 

Thanks.

**Comment by benschwarz** [comment]
> but I can totally see how the way it's written may lead to confusion
FYI, this seems like you're saying that I misinterpreted it, not that the documentation was incorrect and requires a fix.

**Comment by mreferre** [comment]
@benschwarz Sorry, I was not suggesting you misinterpreted it. I was just saying the documentation was written with good intentions. But we took your valuable feedback and tweaked that line into: 

```
When specifying a platform version, you can use either the version number, for example 1.4.0, or LATEST (which points to the 1.3.0 platform version.
```

**Comment by abdulmohammed1** [comment]
@mreferre - ` A less aggressive move to the LATEST flag` section in the _AWS Fargate platform versions primer blog post says_ in May 2020 time frame latest flag will point to 1.4.0 version. I wanted to know when this change will be in effect?

**Comment by mreferre** [comment]
We are in the process of updating the blog post to mention that we are postponing the move of the flag to some time in Q3.

**Comment by mreferre** [comment]
FYI the blog has just been update with the above verbiage.

**Comment by mreferre** [comment]
@benschwarz @monken additional feedback is welcome: https://github.com/aws/containers-roadmap/issues/1069

**Comment by DanieleSalatti** [comment]
So it seems like the `LATEST` tag actually means stable?

Wouldn't it make more sense to have separate stable and latest tags then?

**Comment by mreferre** [comment]
> So it seems like the `LATEST` tag actually means stable?
> 
> Wouldn't it make more sense to have separate stable and latest tags then?

That's in fact what's being proposed in https://github.com/aws/containers-roadmap/issues/1069
