### ISSUE TITLE
[ECR] [request]: Disable image pull until image is scanned

### ISSUE THREAD

**Issue by realvz** [aws/containers-roadmap#843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Now that ECR supports image scanning, there should be an option to disable or prevent images from being pulled until image scan has been completed. Since images are scanned only once a day, if the image has already been scanned in the past 24 hours and a new version is pushed, it should not be prevented from being pulled. 

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Unscanned images should not be allowed to run in a secure environment. If an image has critical vulnerabilities, it should not be allowed to run in production environments. The option to disable pull until image has been scanned should be configurable. Some customers may not want to pull an image with high vulnerabilities, where as some may only prevent images with critical vulnerabilities from being run. 

**Are you currently working around this issue?**
Right now the only way to do this is by manually deploying new image once ECR scan completes successfully. The status of ECR scan can be monitored using CloudWatch events.

**Comment by zbintliff** [comment]
Would you imagine this as an ECR policy that denies pull until it passes a scan?

**Comment by rpnguyen** [comment]
Since evaluation of scanning status should happen at container deployment time, would this functionality be more suited for ECS Container Lifecycle Hooks? #952

**Comment by gtaws** [comment]
Want to re-open this as I think this is an important control against a repo to prevent problems from spreading and becoming worse within highly automated environments.

**Comment by dokuboyejo** [comment]
This is becoming increasingly important for compliance ...
