### ISSUE TITLE
[EFS] [request]: Create Access points in CloudFormation

### ISSUE THREAD

**Issue by machielg** [aws/containers-roadmap#846]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Ability to create access points in EFS CloudFormation 

**Which service(s) is this request for?**
EFS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Access point creation can be done via the UI and CLI. Would be great if it's supported in cloud formation too, otherwise the access points need to have it's own extra API call. I'm using AWS CDK for the stack, which would need this feature as well to expose it in the CDK API.

**Are you currently working around this issue?**
Using the AWS CLI

**Comment by coultn** [comment]
Thanks for the feature request!  This is not a request for any of the AWS container services (ECS, EKS, Fargate, or ECR) so it doesn't belong on this roadmap, unfortunately.  EFS doesn't yet have a public github roadmap, but we have shared this request with the EFS team.  Closing this issue.

**Comment by sopel** [comment]
There is a [CloudFormation Public Coverage Roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap) as well meanwhile, and the request at hand is already tracked via https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/395.
