### ISSUE TITLE
[EKS] New EKS Region: Cape Town

### ISSUE THREAD

**Issue by jaymccon** [aws/containers-roadmap#848]
EKS in Cape Town, South Africa(af-south-1)

**Comment by Fluffy24** [comment]
Estimate of when it could be ready ?

**Comment by ethan3run** [comment]
> Estimate of when it could be ready ?

Its already there bro. Look this article : https://www.itweb.co.za/content/lLn14MmjpAkqJ6Aa

Bingham said: “We are looking at that list, but already we can see various services such as Athena, Quicksight, EKS and service quotas.”

**Comment by Fluffy24** [comment]
hmmm thats weird

**Comment by ethan3run** [comment]
> hmmm thats weird

why ?

**Comment by DavzDaCoder** [comment]
@ethan3run howcome Cape Town doesnt have the tick yet for EKS ?

**Comment by Fluffy24** [comment]
> @ethan3run howcome Cape Town doesnt have the tick yet for EKS ?

exactly my point

**Comment by DavzDaCoder** [comment]
@Fluffy24 I hope one of the devs gets back to us soon.

**Comment by Fluffy24** [comment]
yeah cause i am really confused rn

**Comment by ethan3run** [comment]
> > @ethan3run howcome Cape Town doesnt have the tick yet for EKS ?
> 
> exactly my point

Sorry bro Im french. Can you explain what is the tick for eks ?

**Comment by Fluffy24** [comment]
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/
there has to be a tick here for eks

**Comment by DavzDaCoder** [comment]
![cpt](https://user-images.githubusercontent.com/39415181/80251231-8b9f7400-8675-11ea-8167-cb6190dd5d03.png)

**Comment by Fluffy24** [comment]
it makes us think what we should believe at this stage ?

**Comment by DavzDaCoder** [comment]
I think its gonna take around a month, I mean thats how long Bahrain took.

**Comment by Fluffy24** [comment]
Bahrain took 10 days to implement EKS

**Comment by DavzDaCoder** [comment]
Bahrain launched on the 29th of July and got EKS on the 30 of August @Fluffy24

**Comment by DavzDaCoder** [comment]
Maybe they only started working on it 10 days before it launched?

**Comment by Fluffy24** [comment]
hmmm idk anymore. I guess we just gotta wait and see bro

**Comment by ethan3run** [comment]
![Capture](https://user-images.githubusercontent.com/64282650/80254115-a11f9880-868b-11ea-9adc-0b596fb2ea87.PNG)

Why I dont see cape town :/

**Comment by DavzDaCoder** [comment]
I dont know ;(

**Comment by ethan3run** [comment]
But maybe Amazon just forgot to update the page because this guy said that EKS is already there... I hope...

**Comment by Evanrr12** [comment]
Hi any news on EKS ?

**Comment by ethan3run** [comment]
They still work on it like you can see Up ⬆️
I think in the next 7 days its gonna be ready

**Comment by Prototyp8** [comment]
Hoping these wont get delayed because of current events (covid-19)

**Comment by Brazer2** [comment]
@Prototyp8 I dont think the virus will slow things down too much. They managed to get the server finished and online during this lockdown period and most of this implementation process is correspondence based.

**Comment by DavzDaCoder** [comment]
@mikestef9 Hi Mike, do you have any estimate on when EKS for Cape Town should be ready?

**Comment by TRCEReaper** [comment]
Any update on The EKS in Cape Town

**Comment by Brazer2** [comment]
Lads we need to get hold of Mike some how.

**Comment by TRCEReaper** [comment]
Mikevany updates

**Comment by MikeOxlongKEKW** [comment]
They dont work on the weekeend. Stop bothering them

**Comment by MuggLZA** [comment]
In the Bahrain servers they had the same thing that's happening here...they opened the issue and someone put in in you're working on it then 10 days later the issue was closed and bahrain had EKS 🙌

**Comment by GlockFNBR** [comment]
Hopefully this is done soon

**Comment by WilkieZA** [comment]
@mikestef9 any idea on when EKS will be finished?

**Comment by YannikMeyer** [comment]
My goodness leave the guy alone.

**Comment by ashpro1212** [comment]
Yeah can't they just wait 3-4 more days.

**Comment by DavzDaCoder** [comment]
Remember that Mike is from Seattle and they're 9 hours behind us, so hes still asleep for a long time.

**Comment by DaemosZA** [comment]
Lets pray that some progress is reported today

**Comment by mikestef9** [comment]
Hey everyone,

Please refer to this roadmaps [FAQs](https://github.com/aws/containers-roadmap#faqs) to get more information on the meaning of different roadmap categories. We are unable to provide more specific timelines in this public forum.

EKS treats each new AWS region launch as a critical feature, so this is a high priority for the team. Keep in mind that each EKS cluster consists of a single tenant control plane that spans 3 AZs, and we have a high internal bar for security and reliability to meet before adding support for a new region. The next update on this issue will be moving the status from "We're Working On It" to "Coming Soon".

-Mike

**Comment by DaemosZA** [comment]
Much appreciated!

**Comment by TRCEReaper** [comment]
Thanks for the update much appreciated

**Comment by YannikMeyer** [comment]
Hey @mikestef9 , If I way ask, How long it took for the Bahrain Region it took until EKS was available and do game server require EKS for them to run on the AWS Clouds? 

P.S.
Really interested in these things and so on! (Coding, etc)

Yannik Meyer

**Comment by Qavy** [comment]
So will we be getting SA servers soon or is it going to take a while just want to know please

**Comment by Brazer2** [comment]
@Qavy Bro he literally said he cannot tell us more about the timeline. If you read the key it says once they update it to "coming soon" it can take a few days to 2 months.

**Comment by mikestef9** [comment]
It's here! Very happy to announce that EKS is now generally available in the AWS Africa Cape Town (af-south-1) region!

- [What's new post](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-now-available-cape-town-milan/)
- [EKS documentation & AMIs](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html)
