### ISSUE TITLE
Attach Persistent Storage to ECS + Launch Type Fargate

### ISSUE THREAD

**Issue by asadullahrao** [aws/containers-roadmap#851]
I want a shared storage under one ecs cluster which needs to be accessible to all of my services task. Like if one task of service create file on this storage, other task of the service can access it easily? Can I do that?

Cluster 1 --> Service 1 --> Task 1 --> Create file on Storage A.
Cluster 1 --> Service 2 --> Task 2 --> Can access file on Storage A.

Note: Storage A can be any storage.

**Comment by coultn** [comment]
This is exactly what the recently-launched ECS/EFS integration does:  https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/

Closing this issue as it is already available.
