### ISSUE TITLE
[ECS] [BUG]: Missing values in platform_version 1.4.0 in task metadata endpoint

### ISSUE THREAD

**Issue by J-Mx** [aws/containers-roadmap#855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Tast definition metadata should return full Docker Stats (https://docs.docker.com/engine/api/v1.30/#operation/ContainerStats)

**Which service(s) is this request for?**
Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
While trying to monitor my task with Datadog Agent, everything works fine with platform_version `1.3.0` , but when I upgrade to `1.4.0` , some metrics from task metadata endpoint disappear. When I go deeper in [datadog agent code](https://github.com/DataDog/integrations-core/blob/master/ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py#L165) , it seems that the task metadata endpoint does not return anymore these values : 
```
system_cpu_usage
online_cpus
```
You could see a sample with a task definition metadata from `1.4.0`  on the left  and a task definiton metadata `1.3.0` on the right  [here](https://gist.github.com/J-Mx/50dcfaecb9b0a96a358698558371121f/revisions?diff=split) 

(on the other side we have network informations in `1.4.0` which is a nice feature :+1: )

**Are you currently working around this issue?**
We rollback to platform_version `1.3.0`

**Additional context**
N/A

**Attachments**
https://gist.github.com/J-Mx/50dcfaecb9b0a96a358698558371121f/revisions?diff=split

**Comment by ddyzhang** [comment]
Hello @J-Mx ,

Thank you for reporting this, we have identified this as a bug in Fargate PV 1.4. We will work on addressing this and provide updates once it is resolved.

Derek

**Comment by akshayram-wolverine** [comment]
This is now fixed. Please relaunch tasks on PV1.4 to observe system_cpu_usage and online_cpus.

**Comment by hatappo** [comment]
Hello @akshayram-wolverine ,

I relaunched my task on PV1.4.0 and see task metadata. But I still could not find some values such as `precpu_stats. system_cpu_usage` (not `cpu_stats.system_cpu_usage`).

Are there any plan to fix also it?

Here is my diff between PV1.3.0 and PV1.4.0 .
https://gist.github.com/hatappo/f763613305d30636123fe68b453a6492/revisions?diff=split#diff-7f757eaf4ee2eefdfd3db69a9a0b6c28
