### ISSUE TITLE
[ECR] [request]: Support Ubuntu 20.04

### ISSUE THREAD

**Issue by dmarkey** [aws/containers-roadmap#858]
**Tell us about your request**
What do you want us to build?

Add support for scanning ubuntu 20.04 based images for security vulnerabilities.

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
None

**Additional context**
Anything else we should know?
Tried to scan yesterday and it told me ubuntu 20.04 was not supported.,

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by dsalamancaMS** [comment]
Clair already contains 20.04 in its DB, should this Issue be closed? 

 https://github.com/quay/clair/pull/987

**Comment by michaelb990** [comment]
We have deployed an update to our Clair clusters. Ubuntu 20.04 is now supported in ECR.
