### ISSUE TITLE
[ECS] [request]: Capacity Provider ability to enable Protection from scale in in ASG

### ISSUE THREAD

**Issue by dsalamancaMS** [aws/containers-roadmap#860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When you create a Capacity Provider, the Capacity Provider should be able to enable on its own the "Instance Protection - Protected from scale in" in the selected AutoScaling Group, when you select the Managed termination protection as Enabled.

The current behavior is that you have to enable it manually in the ASG before enabling Managed termination protection on the CapProv.

**Comment by AbhishekNautiyal** [comment]
This was fixed earlier in the year. 

When you enable managed termination protection, Amazon ECS first turns on the instance scale-in protection option for the EC2 instances in the Auto Scaling group. Then, Amazon ECS places the tasks on the instances. When all non-daemon tasks are stopped on an instance, Amazon ECS initiates the scale-in process and turns off scale-in protection for the EC2 instance. The Auto Scaling group can then terminate the instance.
Please refer to [documentation] for more details (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-termination-protection.html)

Let us know if you face any issues.
