### ISSUE TITLE
[EKS] [NLB]: Backport support for elastic ip from 1.16

### ISSUE THREAD

**Issue by rverma-jm** [aws/containers-roadmap#861]
**Tell us about your request**
Backport support for elastic ip from 1.16 based on annotation
   `service.beta.kubernetes.io/aws-load-balancer-eip-allocations`

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Its required for compliance.

**Are you currently working around this issue?**
No solution, have to run sensitive apps outside kubernetes.

**Comment by astrived** [comment]
@rverma-jm Given that we release 1.16 and it has fix for this https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#network do you see a need to backport it ?

**Comment by rverma-jm** [comment]
We can skip this for now.
