### ISSUE TITLE
Tag Immutability off but can't override image, which is not even present [ECR ARM] Issue

### ISSUE THREAD

**Issue by Henry-Asante** [aws/containers-roadmap#862]
Please let us know how we can improve the [EKS ARM preview program](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview). This can be a bug report, feature, or functionality request.

**Describe the issue**
I initially set a tag immutability check on, so no tags can be overwritten
I turned it off so I can have a stable latest tag to work with.
Now all is set but when am overwriting the latest tag, I get this error in my codebuild process:
...

49faa1768b47: Pushed
--
244 | [DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the number.ecr.us-east-1.amazonaws.com registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
245 | tag invalid: The image tag 'latest' already exists in the 'app_service_image' repository and cannot be overwritten because the repository is immutable.
246 |  
247 | [Container] 2020/04/26 18:07:43 Command did not exit successfully docker push $REPOSITORY_URI:latest exit status 1
248 | [Container] 2020/04/26 18:07:43 Running command echo Finished Pushing Auth_service Image into Amazon ECR

**To Reproduce**
First set tag immutability on your AWS ECR image repository and push and then off and push again. Thats how I experienced this

**Expected behavior**
That the tag is overwritten

**Screenshots**
Section of build process where problem occurs
![image](https://user-images.githubusercontent.com/30865594/80317770-971da700-87fd-11ea-902b-2f9800aa36fc.png)

ECR IMAGE REPO
![image](https://user-images.githubusercontent.com/30865594/80317933-8b7eb000-87fe-11ea-97fe-44cc0fea17b4.png)

**Cluster Information**
It's in the AWS Codebuild and AWS ECR process

**Additional context**
None

**Comment by runningman84** [comment]
From my point of view there should be some way to exclude alias tags from the tag immutability. Maybe some regex which would allow to overwrite latest, branch name ...

Right now it is all or nothing. We use specific tags based on commit id for deployments. But is is also very convenient that a developer can just fetch the latest image without knowing the last commit id. This means we are not able to use this feature...

**Comment by rpnguyen** [comment]
We haven’t been able to reproduce this issue, could you let us know if this is still happening?

**Comment by Henry-Asante** [comment]
It's been a long time since I experienced this issue, however from what I remember, after deleting the Image, and setting the tag immutability on and off again.

I could not replace it, basically as reported in my reported issue

**Comment by Mugane** [comment]
Well, that was an utter waste of time.
