### ISSUE TITLE
[EKS]: Kubernetes v1.13 End of Support (June 30, 2020)

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#871]
Kubernetes version 1.13 on Amazon EKS is now deprecated and will no longer be supported on **June 30, 2020**. On this day, you will no longer be able to create new 1.13 clusters and all EKS clusters running Kubernetes version 1.13 will be updated to the latest available platform version of Kubernetes version 1.14.

We recommend customers upgrade existing 1.13 clusters and worker nodes to at least 1.14 as soon as practical.

Learn more:
* [Updates to Amazon EKS Version Lifecycle](https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/)
* [Amazon EKS Kubernetes Versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by Marlois** [comment]
what does this mean, is it part of cape town ?
