### ISSUE TITLE
[EKS] [request]: EBS / EFS CSI driver Helm charts hosted in a public Chartmuseum

### ISSUE THREAD

**Issue by paulcrecan** [aws/containers-roadmap#872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

We’re finding ourselves in need of an official Helm chart for EBS / EFS CSI drivers. We’re using Helm as our package manager and we’d like to be able to fetch that chart using the Terraform Helm provider.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We’d like to stick as much as possible to the infrastructure as code paradigm, but we’ve hit a point where we’re having difficulties managing the storage aspect of our EKS cluster. For this issue to be resolved EBS / EFS CSI drivers hosted in a public chart museum (https://kubernetes-charts.storage.googleapis.com) would be the way to go and for us to maintain a native Kubernetes way of doing things.

**Are you currently working around this issue?**
Yes

How are you currently solving this problem?
We’re currently using ArgoCD to work around this by deploying Kustomize manifests of the EBS / EFS CSI drivers within the cluster.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sppwf** [comment]
Waiting for the same feature

**Comment by mikestef9** [comment]
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/charts/aws-ebs-csi-driver
https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/charts/aws-efs-csi-driver
