### ISSUE TITLE
[EKS] Minor typo in the description for Cluster Endpoint Access in the Networking tab

### ISSUE THREAD

**Issue by cPu1** [aws/containers-roadmap#874]
Under `EKS > Clusters > cluster-name > Networking`, clicking on the `info` link for `API server endpoint access` opens up the description for Cluster Endpoint Access. There's a minor typo there:

```diff
- You can limit, or completely disable, public access from the internet to you Kubernetes cluster endpoint.

+ You can limit, or completely disable, public access from the internet to your Kubernetes cluster endpoint. 
```

![image](https://user-images.githubusercontent.com/6298307/80982575-26077080-8e49-11ea-9c14-6d31ec727827.png)

**Comment by mikestef9** [comment]
Resolved
