### ISSUE TITLE
[ECR] [request]:  Export scan findings to AWS Security Hub

### ISSUE THREAD

**Issue by kennycoder** [aws/containers-roadmap#875]
**Tell us about your request**
Export scan findings to AWS Security Hub

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Since AWS Security Hub is a centralized hub for all the security related topics, it would be great to have this integration with ECR scanning.

**Are you currently working around this issue?**
Directly exporting to EventBridge and taking actions there. 

**Additional context**
I know Security Hub also talks with EventBridge but since it's supposed to be a centralized place, imho it makes sense to have this integration.

**Attachments**
n/a

**Comment by shahbhavik01** [comment]
Are there any updates on this? Our company would love to use this feature at scale. We need centralized view of all images with vulnerabilities in Security Hub.

**Comment by hisnakad** [comment]
> Are there any updates on this? Our company would love to use this feature at scale. We need centralized view of all images with vulnerabilities in Security Hub.

Hello, I uploaded sample package to the following repositories. This project provides sending ECR Scan results to Security Hub as ASFF format by Lambda function. Please let me know if you want to feedback about this.
https://github.com/hisnakad/AmazonECRScanSecurityHub

**Comment by dnx-seek** [comment]
This seems like quite an omission; we can integrate Inspector to Security Hub. We can also easily utilise kube-bench in EKS and ship that to security hub, and many other integrations, but as an organisation utilising ECR we have to deploy some sort of self-baked script to target all ECRs in all accounts and pull data back. Not ideal.

I'd also add to this that it'd be ideal if the results also included some metadata around the ECR settings, e.g. Lifecycle Policy & is scan on push enabled.

**Comment by mattgillard** [comment]
I just came across this. Yes - quite the omission indeed. ;-)
Look you can build it yourself!
https://aws.amazon.com/blogs/containers/automating-image-compliance-for-amazon-eks-using-amazon-elastic-container-registry-and-aws-security-hub/

Would be nice to have it fully integrated.

**Comment by uname223** [comment]
Any news regarding this one? I see that enhanced scanning done by the inspector engine has this capability already integrated. Are we going to see it also in basic scanning, or will it be reserved feature for the inspector, so this issue shall be closed?

**Comment by srrengar** [comment]
This is provided in Inspector as you mentioned @uname223, and I will close this issue
