### ISSUE TITLE
[Fargate] [bug/regression]: Modifying /etc/hosts does not work with 1.4.0 anymore

### ISSUE THREAD

**Issue by lifeofguenter** [aws/containers-roadmap#886]
It used to be possible with Fargate 1.3.0 to add entries to `/etc/hosts`. With 1.4.0 I get the following error:

```
/usr/local/bin/entrypoint.sh: line 11: /etc/hosts: Read-only file system
```

This is unfortunately crucial as `extraHosts` via task-definition is not supported with awsvpc.

**Comment by aberezin** [comment]
I need this fixed too

**Comment by SaloniSonpal** [comment]
This issue is now fixed and you should be able to modify /etc/hosts, /etc/hostname, and /etc/resolv.conf with PV 1.4
