### ISSUE TITLE
Documentation or information on "vpc-resource-controller" and "vpc-admission-webhook"

### ISSUE THREAD

**Issue by cshivashankar** [aws/containers-roadmap#889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Document usage, limitations on "vpc-resource-controller" and "vpc-admission-webhook".
Above 2 are very critical components for running windows nodes, but it's still a black hole on how this works and there is very little information on this. What is the behaviour or effects when the above pods are evicted , maybe in a spot environment etc. At present I see only one replica for them, will it be a bottleneck ?

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
At present  "vpc-resource-controller" and "vpc-admission-webhook" are total black boxes. It would be good to have a better understanding of critical components.

**Are you currently working around this issue?**
No workarounds. 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by ngortheone** [comment]
at least publish the code for vpc-resource-controller and vpc-admission-webhook

**Comment by mikestef9** [comment]
Windows IP address management is now included as part of the open source VPC resource controller project. See release v1.1.0 for details

https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0

This version of the controller now runs as part of EKS control plane, see EKS documentation for more details.

https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
