### ISSUE TITLE
[Fargate, ECS] [Tagging]: Support tagging when starting a task from CWE

### ISSUE THREAD

**Issue by iconara** [aws/containers-roadmap#89]
**Tell us about your request**
Support for tagging a task started through CloudWatch Events.

**Which service(s) is this request for?**
Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When creating an ECS CloudWatch Events rule target there is no option to set tags. This means that tasks started through CWE won't get tags in Cost and Usage Reports.

**Are you currently working around this issue?**
It's possible to work around by triggering Lambda functions on task start events and tagging that way, but it's a lot of infrastructure.

**Comment by czerasz** [comment]
Is there a workaround? Would this be possible with EventBridge?

**Comment by arnaudmm** [comment]
@czerasz a workaround is to use a scheduled lambda to run an ECS task. When using the run_task api you can choose your tag.

**Comment by yonran** [comment]
I asked this [question on stackoverflow](https://stackoverflow.com/questions/67381587/how-to-propogate-tags-to-an-ecs-task-launched-from-an-eventbridge-target) too. Yesterday the `ecsParameters.PropagateTags: "TASK_DEFINITION"` was added to EventBridge PutTargets and started being added to the SDKs so it seems that this issue has been resolved

* python [botocore 1.20.99](https://github.com/boto/botocore/commit/df7892410ef7d7f4312eb5da520ecaec5ea1ffdd)
* js [aws-sdk v2.933.0](https://github.com/aws/aws-sdk-js/commit/d420427503fcfe7854d191c055e4a034fcfa9fdd)
* [aws-sdk-go v1.38.66](https://github.com/aws/aws-sdk-go/pull/3974)

**Comment by renedacosta** [comment]
Hi there, 
I see this issue has been open for a while are there any updates and is there currently a way to have the created task inherit tags from the cloudwatch event instead of the task definition (without a lambda workaround) ?

**Comment by SaloniSonpal** [comment]
You're right @yonran , support for configuring tags among other missing configurations for scheduled and event-driven tasks was recently added.
https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-ecs-supports-additional-configurations-for-scheduled-and-event-driven-tasks/
