### ISSUE TITLE
[EKS] New EKS Region: Milan - MXP

### ISSUE THREAD

**Issue by FabioChiodini** [aws/containers-roadmap#890]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
I'd like to have EKS available in the new Italian region please

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For K8s workloads that require low latency or data sovereignty it would be useful to have EKS available in the new Italian Region

**Are you currently working around this issue?**
K8s Workloads are now hosted on premises or in other AWS region (in this case latency is sub optimal)

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by Anonymous263-Anonymous** [comment]
when will eks Africa be ready

**Comment by mikestef9** [comment]
Happy to announce that EKS is now generally available in the AWS Europe Milan (eu-south-1) region! Note that this launch also includes support for AWS Fargate.

- [What's new post](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-now-available-cape-town-milan/)
- [EKS documentation & AMIs](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html)
