### ISSUE TITLE
[EKS] [request]: Private IPs for AWS NLBs

### ISSUE THREAD

**Issue by vikram-katkar** [aws/containers-roadmap#896]
**Tell us about your request**
Ability to specify static, private IPv4 addresses when creating a service backed by an AWS NLB. This is analogous to the existing support for Elastic IP allocations, but for internal NLBs instead.

**Which service(s) is this request for?**
EKS

**Additional context**
https://github.com/kubernetes/kubernetes/pull/90407

**Comment by mikestef9** [comment]
Closing as duplicate of #894
