### ISSUE TITLE
[Fargate] [bug/regression]: Container health checks not working anymore with 1.4.0

### ISSUE THREAD

**Issue by lifeofguenter** [aws/containers-roadmap#898]
We already opened a support ticket, but just for visibility to gauge if this is a feature that has been used a lot or not.

With Fargate 1.4.0 container health checks do not work anymore.

**Comment by SaloniSonpal** [comment]
Thanks for reporting the issue @lifeofguenter. We are aware of the problem [(also on StackOverflow)](https://stackoverflow.com/questions/61222368/can-not-get-docker-healtcheck-to-work-with-ecs-fargate-v-1-4-0) and are working on fixing it.

**Comment by ddyzhang** [comment]
Hi Günter,

The Fargate team has recently identified and fixed a container health check issue where if your container health check command outputs to `stderr` at all, we would incorrectly classify it as a health check failure. This was most apparent for customers who use `curl` in their health check commands and did not specify the `-s` flag.

Can you please verify if this was the issue you were encountering and whether or not it has been resolved on your end?

Thank you!

Derek

**Comment by SaloniSonpal** [comment]
@lifeofguenter - checking back again to see if your issue has been addressed based on @ddyzhang 's comment above?

**Comment by lifeofguenter** [comment]
Thank you @SaloniSonpal and apologies for the late reply. We upgraded to 1.4.0 _without_ changing anything on our side and its working now.

So the initial bug has been resolved :)

**Comment by dekimsey** [comment]
@ddyzhang Do you know if this fix was applied in all AVs across all regions? We seem to be seeing something that looks alot like this behavior in eu-central-1. Services with 1.4.0 set will only ever successfully startup in eu-central-1c. A & B never succeed.

**Comment by ddyzhang** [comment]
Hi Daniel,

This fix should have been rolled out to all regions and availability zones where Fargate is available. Can you please email me at zhandere@amazon.com with some more details? I'd be happy to look into this for you.

**Comment by ddyzhang** [comment]
Providing a quick update on this issue from some offline discussions with @dekimsey:

> After further investigation, I think we have an idea of what's going on here. There is a known bug in Fargate PV 1.4 where the `startTimeout` for container dependencies is not being handled correctly. This bug causes premature task termination even when customer containers come online before the configured timeout. The fix for this issue is currently pending production release.
>
> As to why this issue is isolated to eu-central-1a and 1b, our best theory right now is that perhaps eu-central-1c exhibits slightly lower network latency than the other two availability zones.

In the meantime, those affected by this issue can temporarily mitigate the problem by bumping up any `startTimeout` values in the ECS task definition.

**Comment by LeslieK** [comment]
@ddyzhang : I expected this healthCheck command to work with Fargate platform version 1.4.0:
`["CMD-SHELL", "curl -s http://localhost/health || exit 1"]`
All other healthCheck attributes use the default values.
Am I correct that this command should work?

**Comment by regevbr** [comment]
@ddyzhang I'm still having issues even after adding the -s flag. Is there another workaround or a way to check why the health checks fail? According to my app logs the health checks always pass within 1 ms

**Comment by starrybleu** [comment]
Nowadays, I'm still facing the problem too with `curl with options -s, -f` and `platform version 1.4.0`

Not all tasks failed. Sometimes, suddenly one or more tasks being stopped because of container health check without any consistent pattern.

Even though I have set health check command `CMD-SHELL, echo hello`, container health check failed intermittently on several tasks.

Is there anyone like me?

**Comment by cnguyenWurl** [comment]
@starrybleu - I'm also having the same problem. Simple "echo" command still cause random intermittent health check failure after a few days on several tasks.

**Comment by starrybleu** [comment]
@cnguyenWurl I eventually have changed fargate platform version from 1.4.0 to 1.3.0, then everything's fine now.

If I should upgrade to 1.4.0 again later, I would be cautious and so tired.

**Comment by tsgoff** [comment]
redirecting stderr to /dev/null is working for 1.4.0.
But using enable_execute_command at the same time the healthcheck is failing again.

**Comment by thebpmgroup** [comment]
```json
"command": [
          "CMD-SHELL",
          "curl -f http://localhost:8080/heath > /dev/null || exit 1"
],
```

This fails, consistently.
I can ssh into the container and run the cmd successfully
I can run it as a docker container on my local machine with the --health-cmd switch and the same command.

I've tried it with and without piping to /dev/null
