### ISSUE TITLE
Fargate Log Driver Support v1

### ISSUE THREAD

**Issue by abby-fuller** [aws/containers-roadmap#9]
Log driver parity with ECS. Bring Fargate on-par with additional logging drivers that ECS supports like Splunk.

**Comment by peterdeme** [comment]
Any progress regarding this @abby-fuller ? Our company's only blocker from utilizing Fargate is the missing Splunk driver.

**Comment by adambasloe** [comment]
Also curious, can we can expect the support in days, weeks, months?

**Comment by mnewell** [comment]
Same for my company; Splunk log driver support is our blocker from using Fargate. Would love to know timeframe.

**Comment by iniinikoski** [comment]
We have solved this with the common Splunk integration: from CW Logs to Splunk using Kinesis Streams - same way as with Lambdas. Works like a charm...

**Comment by benbpyle** [comment]
Is the team looking at fully parity with ECS (EC2) log drivers as described here? https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html

**Comment by arvinep** [comment]
Is there any ETA on implementing this feature?

**Comment by abby-fuller** [comment]
shipped! https://t.co/cHTbBF1rbl

**Comment by dayer4b** [comment]
I see that this is "shipped" but, in actuality, there is _NOT_ parity with ECS on this feature.  The only log drivers I see are awslogs and splunk.  I have an interest in sumologic support.  What about others?

**Comment by akshayram-wolverine** [comment]
@dayer4b please see https://github.com/aws/containers-roadmap/issues/10. We are working a unified interface that makes it seamless to ingest logs into AWS and other partner tools, including sumologic. We will let you know when we have a preview for this.
