### ISSUE TITLE
[Fargate] [Tagging]: Inherit tags from cluster/service/task definition

### ISSUE THREAD

**Issue by iconara** [aws/containers-roadmap#90]
**Tell us about your request**
Tasks should inherit tags from cluster, service, and/or task definitions. 

It would be great if tags could be marked as inheritable, like how tags work in Auto Scaling Groups in EC2. Tasks could inherit tags from cluster, service, and/or task definitions (with some reasonable precedence if they define overlapping tags).

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
You have to provide a lot of things to start a task, and I think it would be great the less that would be required and the more that could come from other sources like the task definition and cluster, and service when there is one. One such thing is tags. Tagging resources with long life spans, and that you have relatively few of, like clusters, services, and task definitions is not a big deal, but having to tag tasks, every time you run them, even though the information is already in the other, related resources, feels like unnecessary work.

Tagging is also often an infrastructure concern, if you tag to get your costs organized, for example, it may be unnatural for the application starting the tasks to have to know about these tags. If the tags were inherited from, say, the task definition, the application would only have to know about that, and not also about tags.

**Are you currently working around this issue?**
By duplicating tagging information all over the place.

**Comment by Akramio** [comment]
Hi iconara, thank you for opening this request. You can already configure your Task tags to be inherited from either Task Definition or Service. See the "propagateTags" flag available in the RunTask, StartTask, and CreateService APIs.  [1]

Your ECS Container Instance can also inherit tags from the corresponding EC2 instance, using the "ECS_CONTAINER_INSTANCE_PROPAGATE_TAGS_FROM" config  the ecs-agent. [2]

[1]: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-propagateTags

[2]: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html

**Comment by iconara** [comment]
That's great, I didn't realise that was possible, it's not mentioned in the tagging docs (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html).

Can the same thing be achieved when starting a task in response to a CloudWatch Events rule triggering?

**Comment by Akramio** [comment]
Tags support when launching ECS Tasks as CloudWatch Events Targets is currently not yet supported. Closing this issue since the original question is answered and your follow-up request is captured in issue #89
