### ISSUE TITLE
ECS CapacityProviderReservation metrics is behaving erratically 

### ISSUE THREAD

**Issue by RajatToshniwal** [aws/containers-roadmap#900]
I tried to provision and setup the ECS capacity providers and last couple of days, I am literally struggling with the behaviour. At present I have two capacity providers configured in the ECS with a default strategy of cp1 with base=1,weight=1 and cp2 with weight=1. Target capacity for both of them is set to 100.
I am currently running only one task. My understanding is it should trigger one cp1  instance where it should run the task, whenever there is a need of second instance it should run on the cp2 instance.
 As per the below link for the first task, two servers will be triggered, this is also fine, though my requirement is of only one instance.
https://aws.amazon.com/blogs/containers/deep-dive-on-amazon-ecs-cluster-auto-scaling/

But what I am facing is my two cp1 servers are going down and coming up after every 15 to 20 minutes approximately. When the two servers are up task picks one of them to run and when they are down, tasks stays in the provisioning state.

Scaling trigger is happening due to the Cloudwatch metrics which states if the CapacityProviderReservation is less than 100 for 15 minutes, it should scale down, which is terminating both the instances and then there is another check, when the CapacityProviderReservation is more than 100 for 1 minute, ( task once again comes in the provisioning state ) it starts both the instances again.

How to overcome this behaviour?

**Comment by anoopkapoor** [comment]
@RajatToshniwal checking in if you're still seeing this issue or its now resolved?

**Comment by anoopkapoor** [comment]
@RajatToshniwal I'm going ahead and closing this. Please let us know if you're still seeing the issue.
