### ISSUE TITLE
[ECS] [request]: per-task networking for Windows containers

### ISSUE THREAD

**Issue by nonspecialist** [aws/containers-roadmap#907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Task networking for Windows Containers

**Which service(s) is this request for?**

ECS although it would also be required for Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Currently, Windows containers can only use the `default` network mode, which means NAT. This prevents allocation of security groups per-service, which makes it impossible to achieve least privilege network access where there are multiple services in a cluster with multiple backends, where there should be an N:1 relation between services and backends.

For example, in a cluster hosting X services, with Y RDS instances as back-ends, each worker node must be able to access all Y RDS instances, meaning all X services must be able to access those instances.

Workarounds include:
* multiple clusters (which can mean lower utilisation)
* multiple autoscaling groups in a cluster (again, risk of low utilisation)

**Are you currently working around this issue?**
Right now, no. Utilisation and cost control is more important at present, so all services running on all EC2 worker nodes in the cluster can connect to any RDS instance.

**Additional context**
nothing I can think of

**Attachments**
n/a

**Comment by rawahars** [comment]
Task networking for Windows containers on ECS EC2 is now live with agent version 1.54.0 and greater.
Please follow the blog post available [here](https://aws.amazon.com/blogs/containers/getting-started-with-task-networking-on-amazon-ecs-with-windows-containers/) to get started.

**Comment by eugenecg** [comment]
> Task networking for Windows containers on ECS EC2 is now live with agent version 1.54.0 and greater. Please follow the blog post available [here](https://aws.amazon.com/blogs/containers/getting-started-with-task-networking-on-amazon-ecs-with-windows-containers/) to get started.

Hi @rawahars 

Any news if ENI trunking will be made available for Windows? 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/eni-trunking-supported-instance-types.html

**Comment by rawahars** [comment]
Hello @eugenecg,

There are no plans at the moment to extend support for ENI Trunking for Windows on Amazon ECS.
Please upvote the feature here- https://github.com/aws/containers-roadmap/issues/1490 which would allow us to prioritise the same.

CC: @goyalpurvi
