### ISSUE TITLE
[EKS] [request]: Coredns manifest still has reference to extensions/v1beta1

### ISSUE THREAD

**Issue by kaykay88** [aws/containers-roadmap#910]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Coredns manifest provided in AWS docs has apiVersion extensions/v1beta1 for deployment resource, but k8s version 1.16 no longer supports this version for deployments. Please find more details below.

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

As per the AWS guide to upgrade EKS clusters [here](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html):

> DaemonSet, **Deployment**, StatefulSet, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved through the apps/v1 API. For example, to convert a Deployment that currently uses apps/v1beta1, enter the following command.

And in the guide to upgrade coredns [here](https://docs.aws.amazon.com/eks/latest/userguide/coredns.html) the manifest file provided is `https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-05-08/dns.yaml`.This file has reference  to **extensions/v1beta1** under Deployment resource:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
.
.

```
So upgrading cluster to 1.16 using this manifest would break coredns deployment. 

In my opinion the manifest should be updated as per the requisites of kubernetes version 1.16.

**Are you currently working around this issue?**

Not yet, can't take risk of breaking coredns deployment after upgrading our EKS cluster. So the upgrade is on hold at the moment.

**Additional context**
NA

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by kaykay88** [comment]
Hi @mikestef9 

Is there any update on this one ?

**Comment by mikestef9** [comment]
Hey @kaykay88 thanks for reporting, docs have been updated, see 

https://docs.aws.amazon.com/eks/latest/userguide/coredns.html
