### ISSUE TITLE
[EKS/Fargate] [request]: Support for Fargate in Sao Paulo (sa-east-1)

### ISSUE THREAD

**Issue by andreilocks** [aws/containers-roadmap#912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
 Support for Fargate in sa-east

**Which service(s) is this request for?**
EKS Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
Using eks on demand for production cluster and eks in us-east for staging cluster.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by joaomanoelaureliano** [comment]
+1

**Comment by FelipeAugustoCrici** [comment]
+1

**Comment by tabern** [comment]
EKS/Fargate is now available in Sao Paulo (sa-east-1)

[Documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html)
