### ISSUE TITLE
[Fargate] : Ephemeral volume encryption using CMK managed through AWS Key Management Service (KMS)

### ISSUE THREAD

**Issue by akshayram-wolverine** [aws/containers-roadmap#915]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
 We are working on a feature to introduce customer master keys (https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#master_keys) (CMKs) stored in AWS Key Management Service (https://aws.amazon.com/kms/) (AWS KMS) for encryption of ephemeral storage. This will allow customers to control CMK origin, ownership and audit amongst other benefits (https://aws.amazon.com/kms/features/) offered by AWS KMS to help with key management controls.

**Which service(s) is this request for?**
Fargate

**Comment by jbarz1** [comment]
Will this support cross account KMS key? That is the KMS key belongs to an account that is different from the account that owns the Fargate task? Similar to

https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html#policy-example-cmk-cross-account-access

**Comment by pspot2** [comment]
Nowadays this is absolutely basic for security departments of companies, and Fargate's ephemeral storage is a no-go without this feature. Especially if it is exposed as a bind mount of a shared host.

**Comment by OTTOxMarc** [comment]
Is there an update on this?

**Comment by fablocke** [comment]
The same applies to my company. Would appreciate feedback from AWS.

**Comment by amit2067** [comment]
Is it going to be released any soon?

**Comment by mlanner-aws** [comment]
Launched on June 10, 2024: https://aws.amazon.com/blogs/compute/securing-amazon-ecs-workloads-on-aws-fargate-with-customer-managed-keys/
