### ISSUE TITLE
[Fargate, ECS] [CloudFormation]: Support for tags in CloudFormation

### ISSUE THREAD

**Issue by iconara** [aws/containers-roadmap#93]
**Tell us about your request**
Support for tagging resources from CloudFormation

**Which service(s) is this request for?**
Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently there is no support for adding tags to things like `AWS::ECS::Cluster` and `AWS::ECS::TaskDefinition` in CloudWatch.

**Are you currently working around this issue?**
Adding the tags manually after CFN has created the stack.

**Comment by robertd** [comment]
@iconara `AWS::ECS::Service` is also on the list of resources that cannot be tagged using CloudFormation.

**Comment by pmontanari** [comment]
What about EKS?

**Comment by robertd** [comment]
Hi @abby-fuller. You've added this to `Coming Soon` section on January 10th. I understand that this is on Cloudfromation team's plate, but I was wondering if you have any inside scoop on how soon we can expect this functionality.  Thanks in advance!

**Comment by radifalco** [comment]
Can you really call this coming soon if it wasn't delivered in 4 months?

**Comment by whereisaaron** [comment]
@radifalco mere months is radically fast for CF time :smile: E.g. tags support for EIPs was [added to EC2 in 2017](https://forums.aws.amazon.com/thread.jspa?threadID=96348&start=50&tstart=0), and AFAIK we are still waiting for [CF support](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html).

**Comment by robertd** [comment]
The fact that we need to spend more money (lambdas to tag) to figure how much money our ECS clusters are spending is so sad. I just hope that “coming soon” is not in à la Duke Nukem style (coming soon... when it’s done). :)

**Comment by dsouzajude** [comment]
A suggestion to AWS:

It would be nice to release features with CloudFormation support first since your most **advanced** users use this heavily. or atleast have support for it a few weeks or at max a month after the feature is released. Or some how make CloudFormation opensource.

Thank You.

**Comment by robertd** [comment]
Every CFN team member out there...ever 🤣
![](https://memegenerator.net/img/instances/65599026/say-cloudformation-one-more-time.jpg)

**Comment by michelsalib** [comment]
Hello,
We are a big AWS customer heavily relying on tagging and ECS. Can we have an estimation when this feature will be made available ?
Thanks,

**Comment by coultn** [comment]
Hi everyone, I want to assure you that this feature is actively in development and really is "coming soon". We will update this issue once it is released.

**Comment by whereisaaron** [comment]
Thanks @coultn! Will be very handy. I like to drop `AWS::EC2::EIP` into any missing CFN Tags conversation, in the hope that it too, will [one day](https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-virtual-private-cloud-vpc-now-allows-customers-to-tag-their-elastic-ip-addresses/) be 'coming soon'. 😄

**Comment by rendicott** [comment]
+1

**Comment by DanielRedOak** [comment]
Any chance for an update on this issue?

**Comment by trav-c** [comment]
AWS::ECR::Repository is also missing CloudFormation tagging support, would that be covered by the current feature development work or should a separate issue be opened?

**Comment by coultn** [comment]
This is now fully available in all ECS regions!

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by coultn** [comment]
> AWS::ECR::Repository is also missing CloudFormation tagging support, would that be covered by the current feature development work or should a separate issue be opened?

@trav-c yes, tagging for ECR launched also:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

**Comment by trav-c** [comment]
Thanks @coultn it does appear to have been missed in the release notes though.
