### ISSUE TITLE
[EKS]: Support for IMDSv2

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#930]
For defense in depth, EKS is in the process of updating all software components running on the Kubernetes control plane to use IMDSv2 only.

We are also working on IMDSv2 compatibility on the data plane side. IMDSv2 requires a PUT request to initiate a session to the instance metadata service and retrieve a token. By default, the response to PUT requests has a response hop limit (time to live) of 1 at the IP protocol level. However, this limit is incompatible with containerized applications on Kubernetes that run in a separate network namespace from the instance.

To address this, we will update our docs with a new [self managed worker node CFN template](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html) that specifies metadata token response hop limit to 2. We will also build new AMIs with kubelet/authenticator binaries which use IMDSv2 by default. eksctl will also be updated to compatible with IMDSv2.

For managed nodes, we plan to update behavior for all new managed node groups to set a hop limit of 2 in the autoscaling groups configured by managed nodes. Additionally, for any existing node group version or configuration update, we will also update the hop limit setting to 2. We will have an AWS what's new post on the day we make this behavior change, as well as post an update to this issue.

For more info on IMDSv2 see the [launch blog](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/).

**Comment by mikestef9** [comment]
EKS now fully supports IMDSv2. See the What's New [post](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/) for details.

**Comment by Preskton** [comment]
@mikestef9 is there somewhere where those of us rolling our own AMIs can see the specific changes we need to make to support imdsv2, including the version of `kubelet/authenticator`?

**Comment by adrian-rt** [comment]
@mikestef9  what about EKS based on Fargate? I don't see any info on that.

**Comment by mikestef9** [comment]
From EKS [docs](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html#fargate-considerations)

"The Amazon EC2 instance metadata service (IMDS) isn't available to pods that are deployed to Fargate nodes. If you have pods that are deployed to Fargate that need IAM credentials, assign them to your pods using IAM roles for service accounts. If your pods need access to other information available through IMDS, then you must hard code this information into your pod spec. This includes the Region or Availability Zone that a pod is deployed to."
