### ISSUE TITLE
[service] [request]: ENI Trunking for m6g

### ISSUE THREAD

**Issue by rmdashrfslash** [aws/containers-roadmap#931]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Add m6g to the list of supported instance types for ENI Trunking

**Which service(s) is this request for?**

ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I currently run numerous containers with ECS on m5 systems and benefit from ENI Trunking to allow for a larger density of containers per EC2 instance.  I've heard great things about m6 instances, but without ENI trunking, I won't be able to migrate my workload.

**Are you currently working around this issue?**

Staying on m5

**Additional context**

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

**Comment by ellenthsu** [comment]
Thanks for reporting this request. We have updated our documentation to communicate that we support ENI Trunking for the m6g instance family. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html#eni-trunking-supported-instance-types
