### ISSUE TITLE
[Batch] [Fargate] Add ability to use Fargate for AWS Batch managed compute environments

### ISSUE THREAD

**Issue by ilyasotkov** [aws/containers-roadmap#932]
**Tell us about your request**
I'd like to have the ability to use Fargate compute resources for AWS Batch managed compute environments

**Which service(s) is this request for?**
AWS Batch and Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I can use ONDEMAND and SPOT instances for running AWS Batch jobs but not Fargate

**Are you currently working around this issue?**
- I can use SPOT or ONDEMAND instances for creating Batch compute environments
- I can also run tasks directly with ECS Fargate launch type

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kendrexs** [comment]
https://aws.amazon.com/blogs/aws/new-fully-serverless-batch-computing-with-aws-batch-support-for-aws-fargate/

**Comment by SaloniSonpal** [comment]
We're happy to introduce the ability to specify Fargate or Fargate Spot as a computing resource for AWS Batch jobs. See [blog post](https://aws.amazon.com/blogs/aws/new-fully-serverless-batch-computing-with-aws-batch-support-for-aws-fargate/) shared by @kendrexs above for details about how it works.
