### ISSUE TITLE
[EKS] [request]: Provide EKS API to query supported K8S versions and add-ons

### ISSUE THREAD

**Issue by sdonatod** [aws/containers-roadmap#933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Provide an EKS API to be able to query metadata about supported K8S versions and what version of add-ons (CNI, coredns, kube-proxy) are compatible and recommended by AWS per documentation.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have built an automation in place within our enterprise to standup a full-fledged K8S cluster with EKS as our control plane.  There are parts of this automation that we have to predetermine and maintain because there is no API for us to consume that will allow us to determine what K8S versions are supported by EKS.  With the ability to query metadata about what EKS supports from a K8S version and add-ons perspective, the lifecycle management of EKS clusters can be fully automated.

**Are you currently working around this issue?**
Manual inspection of documentation and hardcoding of metadata.

**Comment by 3oris** [comment]
```
$ aws eks describe-addon-versions
addons:
- addonName: vpc-cni
  addonVersions:
  - addonVersion: v1.7.5-eksbuild.1
    architecture:
    - amd64
    - arm64
    compatibilities:
    - clusterVersion: '1.18'
      defaultVersion: true
      platformVersions:
      - '*'
  - addonVersion: v1.6.3-eksbuild.1
    architecture:
    - amd64
    - arm64
    compatibilities:
    - clusterVersion: '1.18'
      defaultVersion: false
      platformVersions:
      - '*'
  type: networking
```

**Comment by tabern** [comment]
This is fulfilled by the EKS [describeAddonVersions](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonVersions.html) API. As we support more add-ons into this system, they will be included in this API.
