### ISSUE TITLE
[ECS] No scaleout from 0 with capacity provider autoscaling group

### ISSUE THREAD

**Issue by mattthelee** [aws/containers-roadmap#935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please have the ECS capacity provider add the AmazonECSManaged tag to the ASG it is managing when it is created. 
Also please document the importance of that tag as it's clearly used for a lot of internal logic that's invisible to the user. 

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to create a capacity provider and ASG that can scale the instances out from 0 using aws api. When you do this in the console, the act of managing an ASG with an ECS capacity provider adds the AmazonECSManaged tag to the ASG. This is not a documented requirement and is not done automatically when doing the same process using the API (documentation here only mentions not to remove it, not what it does or what adds it: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-auto-scaling.html)
 I guess therefore there are 2 issues. 
1) The api does not apply the tag to the ASG when configuring a capacity provider to manage an ASG
2) The effect of AmazonECSManaged tag is not documented anywhere, which is a problem because without it someone can create an ASG with a valid scaling policy, but ECS will fail tasks rather than put them to pending if the ASG starts with desired capacity 0. 

**Are you currently working around this issue?**
Creating this ticket so others can know to apply the tag to their autoscaling group. 
I'm adding the tag to my autoscaling group api call

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by anoopkapoor** [comment]
hi @mattthelee 
>>The api does not apply the tag to the ASG when configuring a capacity provider to manage an ASG
Can you provide the repro steps for it?

I just created a capacity provider using the CLI with the following json and I can confirm that the AmazonECSManaged tag was applied to the ASG at the time of capacity provider creation.

{
    "name": "tagtest",
    "autoScalingGroupProvider": {
        "autoScalingGroupArn": "arn:aws:autoscaling:us-east-1:XXXXXXX:autoScalingGroupName/tagtest"
    }
}

**Comment by mattthelee** [comment]
Yep. If you do the same thing with the api (not the cli). I believe you will not have the tag applied.
________________________________

**Comment by anoopkapoor** [comment]
tested using the Java SDK and that works as well. Can you share the client that you're using for calling the API?

**Comment by mattthelee** [comment]
This was done using Terraform which i believe uses the Go SDK. In this way it's possible to create an autoscaling group in AWS which is managed by ECS but does not have that tag. Would you mind checking your cloudtrail logs to see if it's the SDK or some internal AWS call that applies the tag to the ASG? I imagine it's an internal AWS call. Once I know what i looks like I can check on my side to see if the same is happening. You can see others have had this issue with the tag not being applied but i expect it is an ECS issue not a terraform issue: https://github.com/terraform-providers/terraform-provider-aws/issues/12582

**Comment by monken** [comment]
Also CloudFormation doesn't add the tag

**Comment by anoopkapoor** [comment]
> Also CloudFormation doesn't add the tag

I believe it's the instances that were launched by the ASG ahead of it being associated with the capacity provider (since ASG would be created and its instances launched ahead of the capacity provider being created) are the ones that don't have the AmazonECSManaged tag. You can specify your ASG resource in the CloudFormation template with a min/desired=0 and let the ECS cluster auto scaling scale the ASG out as and when tasks are launched and they need more capacity. This will ensure consistent AmazonECSManaged tagging of the instances.

**Comment by anoopkapoor** [comment]
This issue has now been resolved. Earlier, in some cases, if an ASG already had instances running in it before being associated with a capacity provider, the existing instances would not be correctly accounted for by the capacity provider. Hence, the metric and scale-in protection was not calculated/managed correctly. This issue has now been resolved. You can now associate an ASG that already has instances running in it with a capacity provider, and the capacity provider will correctly account for all the instances, both existing and new.
