### ISSUE TITLE
[ECR] [Authz Token Expiry]: Ability to revoke a ECR Authz Token

### ISSUE THREAD

**Issue by Kiran01bm** [aws/containers-roadmap#936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Usecase: Get ECR Authorization token --> Work with ECR (using this token) --> Revoke Token. Continue this cycle on-demand.

Reason To avoid leaving tokens (after use) for the default lifetime of 12 hours.

Have looked up AWS doco [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) and doco for get-authorization-token and available ecr commands but coudln't find a way to revoke.

For instance, Docker Trusted Registry allows you to revoke access tokens anytime as documented [here](https://docs.docker.com/ee/dtr/user/access-tokens/)

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
To avoid leaving tokens (after use) for the default lifetime of 12 hours.

**Are you currently working around this issue?**
NA

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rpnguyen** [comment]
Thanks for the suggestion. There's no way today to revoke individual ECR authorization tokens. One workaround is to use STS to generate temporary security credentials for a role and then revoke active sessions for that role. Does this work for your use case?

- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_revoke-sessions.html
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_disable-perms.html
