### ISSUE TITLE
[ECS] [request]: Allow Capacity Providers on ECS Scheduled Tasks

### ISSUE THREAD

**Issue by waiwaing** [aws/containers-roadmap#937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to configure a capacity provider for a Scheduled Task. Currently, it appears capacity providers can be configured for Services and one-off Task runs, but not for Scheduled Tasks.

**Which service(s) is this request for?**
ECS EC2 Scheduled Tasks

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We currently have a EC2 Auto Scaling Group, which provides available instances to our ECS Cluster. The cluster runs both a number of ECS Services (used as web servers), as well as frequent Scheduled Tasks (used to synchronise various databases with external third parties). 

We'd like to be able to make use of ECS Cluster Auto Scaling so that we can configure the Services and Scheduled Tasks to have different Capacity Providers. This would allows us to configure Termination Protection for the Scheduled Tasks (as otherwise they have a habit of being killed off prematurely by the Auto Scaling Group scaling in when the Services scale in). 

**Are you currently working around this issue?**
We're not currently working around this issue, but are looking at having separate EC2 instances and ECS Cluster for Scheduled Tasks. However, this is unoptimal because these Services and Scheduled Tasks are logically grouped together; in addition, this solution would result in unused EC2 capacity on the Scheduled Tasks instances. (I would also welcome better workarounds).

**Comment by Layoric** [comment]
Regarding work arounds, does anyone know if Scheduled tasks in a cluster utilize the specified `default` capacity provider for a cluster when launching the scheduled task? Eg, would it be possible to specify a sensible default capacity provider so that scheduled tasks also protected from ECS managed scale in? I'd imagine this would be good enough for a lot of scenarios but I can't find any documentation on this specific combination of features.

**Comment by evanfwelch** [comment]
I have this same issue... any suggestions for workarounds?

**Comment by tovbinm** [comment]
This is so badly needed!

**Comment by leo-viridis** [comment]
Any updates on this?

**Comment by ianneub** [comment]
I would like this added too.

Under the hood the ECS UI is using [AWS EventBridge](https://docs.aws.amazon.com/eventbridge/index.html) rules and targets.

One possible workaround would be to not use the ECS UI to create the scheduled task, but instead use Cloudwatch UI or API. Have the schedule trigger a lambda function that will create the ECS task as a one off task that has a capacity provider set.

Not optimal, but I don't see why it wouldn't work. Please correct me if I'm wrong!

**Comment by SteveRoland** [comment]
I have this same issue. Any updates?

**Comment by summera** [comment]
We'd really like to run a scheduled Fargate task on Fargate Spot but it sounds like this is not possible since it's based on the capacity provider and that can't be used with Scheduled Tasks.

**Comment by coultn** [comment]
> We'd really like to run a scheduled Fargate task on Fargate Spot but it sounds like this is not possible since it's based on the capacity provider and that can't be used with Scheduled Tasks.

You can absolutely use scheduled tasks with Capacity Providers.  Today, it does require that you set a default capacity provider strategy on the cluster, and do NOT set a launch type for the schedule task.  The scheduled task will then use the default capacity provider strategy defined by the cluster, which you can set to be Fargate Spot.

**Comment by summera** [comment]
> You can absolutely use scheduled tasks with Capacity Providers. Today, it does require that you set a default capacity provider strategy on the cluster, and do NOT set a launch type for the schedule task. The scheduled task will then use the default capacity provider strategy defined by the cluster, which you can set to be Fargate Spot.

@coultn Thanks for the response! So to be clear, it's only possible to use the default capacity provider with scheduled tasks? If we wanted to use a mixture of capacity providers for scheduled tasks within the same cluster that's not possible? I'm worried that if we set the default capacity to Fargate Spot just to run this scheduled tasked on Fargate Spot that it's a bit limiting for any other Scheduled Tasks that we may want to run in this cluster which are now (if I'm understanding correctly) forced to run in Fargate Spot in that cluster.

**Comment by belangovan** [comment]
@coultn  we can't able to create scheduled tasks without choosing the Launch type for ECS. if we have any plan to update ECS console and cloud formation support for the use of capacity providers for scheduled tasks.

**Comment by summera** [comment]
@coultn just wanted to check back with you on this one. Would you mind clarifying based on the questions in https://github.com/aws/containers-roadmap/issues/937#issuecomment-700330797?

**Comment by summera** [comment]
Thanks @coultn 👍

**Comment by gbataille** [comment]
Thanks @coultn 

I ended up with the exact same issue. EC2 would not work, saying that there was no container instances (ignoring the c capacity provider)  
FARGATE would not start (DockerTimeout) although I tried in both a NATed subnet and an internet subnets, and I even have VPC endpoints for a lot of service.

I was first thrown off by you comment to chose neither EC2 nor FARGATE as the Web console does not allow that.

But then I realized that the API (and terraform that we use) does allow it, and it ended up working.

A bit hidden and convoluted, I think it's worth having a note somewhere and maybe allowing to deselect the launch type in the Web console, but at least there is a workaround.

thanks

**Comment by maxannear** [comment]
@gbataille 

> But then I realized that the API (and terraform that we use) does allow it, and it ended up working.

Mind sharing how you got this working with Terraform? No matter what I do in Terraform it seems that the launch type of EC2 is always set which means the the capacity provider isn't used

**Comment by gbataille** [comment]
@maxannear 
I pass 

```hcl
resource aws_cloudwatch_event_target "db_dump" {
  target_id = "daily-db-dump"
  arn       = aws_ecs_cluster.backend_cpu.arn
  rule      = aws_cloudwatch_event_rule.db_dump.name
  role_arn  = aws_iam_role.ecs_events.arn

  ecs_target {
    task_count          = 1
    task_definition_arn = aws_ecs_task_definition.db_dump.arn
    # It is critical to leave this value blank so that the task uses the capacity provider
    # https://github.com/aws/containers-roadmap/issues/937#issuecomment-700299611
    launch_type         = ""

    network_configuration {
      subnets         = values(aws_subnet.backend_appserver)[*].id
      security_groups = [
        aws_security_group.backend_appserver.id
      ]
    }
  }
}
```

As per the comment, keeping the `launch_type` attribute in the config and setting it to blank seems to be key

I was in a situation in test, where because my main application is shutdown, the cluster is generally at 0 VMs. when using the above, finally I could see that when launching the task through the schedule event, it went through the PROVISIONNING stage where the capacity provider added VM to the cluster and ultimately my container was run on them

**Comment by belangovan** [comment]
@gbataille,  any idea to do this on cloud formation or any custom resources.

**Comment by gbataille** [comment]
@belangovan have not tried no. But if terraform supports it, that means that the AWS API supports it.

so custom, you should be able to explicitly pass this `launch_type` attribute set to blank.  
As for CouldFormation I would expect it to be the same.

From my test through terraform, not specifying `launch_type` does not work, you have to specify it as an empty value

**Comment by surferzskan** [comment]
+1

**Comment by vibhav-ag** [comment]
https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-ecs-supports-additional-configurations-for-scheduled-and-event-driven-tasks/
