### ISSUE TITLE
[AWS for Fluent Bit] [FireLens]: AWS for Fluent Bit supports sending logs to Amazon S3

### ISSUE THREAD

**Issue by srrengar** [aws/containers-roadmap#940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
The ability to send container logs to Amazon S3 from AWS for Fluent Bit, similar to CloudWatch logs, Kinesis, or Elasticsearch 
https://github.com/fluent/fluent-bit/issues/1004

**Which service(s) is this request for?**
Fargate, ECS, FireLens, EKS using Fluent Bit can use this too

**Comment by dnascimento** [comment]
https://github.com/fluent/fluent-bit/issues/1004

**Comment by PettitWesley** [comment]
This has been released in Fluent Bit 1.6 and AWS for Fluent 2.8.0

There's a new issue on Fluent Bit core to request enhancements: https://github.com/fluent/fluent-bit/issues/2700
