### ISSUE TITLE
[EKS] [request]: Container Insight enabling for EKS with fargate profile cluster

### ISSUE THREAD

**Issue by chandankashyap19** [aws/containers-roadmap#943]
Hello Team,

Although, EKS with Fargate profile is one of an enhanced model to move Kubernetes in serverless. Its available functionality helps alot to create infrastructure. But, Monitoring is one of the important aspects which is currently lacking on EKS with Fargate Model.

Apparently, there is not any monitoring tool available to monitor entire EKS with Fargate Cluster. Entirely means Operational monitorings(CPU, RAM utilization by each pods, No of pods running, No of nodes running) and application monitoring  (No of active request to application pods, No of active connection to DB etc). It should be in place for EKS with fargate.

Only cloudwatch agent integration would resolve most of the monitoring related queries but as its agent is daemonsets and it can't be run on EKS with Fargate profile.

Kindly bring some solutions. Customers don't trust any third party tools so AWS should must look into it.

#EKS with Fargate Profile Monitoring.

**Comment by vaibhavkhunger** [comment]
https://aws.amazon.com/about-aws/whats-new/2022/02/amazon-cloudwatch-eks-fargate-distro-opentelemetry/
