### ISSUE TITLE
[EKS] [request]: Enable StartupProbe feature gate for EKS 1.16+

### ISSUE THREAD

**Issue by blodan** [aws/containers-roadmap#947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add the StartupProbe feature gate which was released in Kubernetes 1.16

**Which service(s) is this request for?**
EKS 1.16 and later

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
StartupProbes was added to Kubernetes 1.16 to be able to "warmup" applications that took some time to boot, right now this feature gate is disabled so StartupProbes isn't usable in AWS EKS.

**Additional context**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

(See StartupProbe)

More about how StartupProbes works can be found here:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Comment by abdennour** [comment]
Oops! I though it was supported until i saw this issue. 
Any deadline to get this work ?

**Comment by abdennour** [comment]
I've upgraded to EKS 1.17 .
Still not available :(

**Comment by cleberwarmling** [comment]
It was a bad surprise knowing that it isn't available on EKS.

**Comment by muhyousri** [comment]
I think EKS doesn't support alpha features ,  StartUp Probe is in beta starting 1.18

**Comment by cleberwarmling** [comment]
@muhyousri Yeap! I saw that after posting here. So, hoping to 1.18 to be available soon.

**Comment by abdennour** [comment]
Hopefully @cleberwarmling  
😔

**Comment by abdennour** [comment]
For now, if anyone has a long boot time ( slow startup), you can check workarounds here https://github.com/kubernetes/kubernetes/issues/27114

**Comment by tabern** [comment]
closing this as EKS does not support alpha features/feature gates. This is resolved by #809
