### ISSUE TITLE
[EKS] [request]: EKS ARM Support for k8s 1.16+

### ISSUE THREAD

**Issue by akshayvvr** [aws/containers-roadmap#948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
EKS ARM Support for k8s 1.16+

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
**What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.**

Trying to have hardware virtualization on our eks cluster bare metal instances currently to acheive that. I recently saw that EKS added support for ARM based a1 instances but the eks arm preview has coredns and kubeproxy for only k8s version 1.15 and lower. It'll be great to have the eks ARM support k8s 1.16+.

**Are you currently working around this issue?**
No. I'm blocked by this issue as my k8s environment is 1.16.

**Comment by mikestef9** [comment]
This functionality is available as part EKS generally available support for Arm-based instances. See launch blog for more details.
