### ISSUE TITLE
[EKS ARM] Issue  C6g Instance types  not supported by  EKS

### ISSUE THREAD

**Issue by mmanishpandey** [aws/containers-roadmap#957]
Please let us know how we can improve the [EKS ARM preview program](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview). This can be a bug report, feature, or functionality request.

**Describe the issue**
C6g instance types are not currently supported by EKS. Customers may benefit by using these nodes for their compute heavy workloads

**To Reproduce**
1. Configure ' try to create a nodgroup  with instance type c6g ..'
2. Deploy ' use eksctl create  node group < eksctl create nodegroup --config-file <file name> ...'
3. Scale '....'
:  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."
**Expected behavior**

Node group should create with c6g instance type 

**Screenshots**

**Cluster Information**
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks01
  region: us-east-2

nodeGroups:
  - name: ng-2-workers
    labels: { role: workers }
    instanceType: c6g.medium
    desiredCapacity: 1
    volumeSize: 80

**Additional context**
Full errro logs 
 ``` [June 24, 2020, 12:07 AM] Pandey, Manish: ℹ]  eksctl version 0.22.0
[ℹ]  using region us-east-2
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
[ℹ]  2 existing nodegroup(s) (managed-ng-1,ng-1-workers) will be excluded
[ℹ]  nodegroup "ng-2-workers" will use "ami-073f227b0cd9507f9" [AmazonLinux2/1.16]
[ℹ]  1 nodegroup (ng-2-workers) was included (based on the include/exclude rules)
[ℹ]  combined exclude rules: managed-ng-1,ng-1-workers
[ℹ]  no nodegroups present in the current set were excluded by the filter
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "eks01"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "ng-2-workers" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-eks01-nodegroup-ng-2-workers"
[ℹ]  --nodes-min=1 was set automatically for nodegroup ng-2-workers
[ℹ]  --nodes-max=1 was set automatically for nodegroup ng-2-workers
[ℹ]  deploying stack "eksctl-eks01-nodegroup-ng-2-workers"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-eks01-nodegroup-ng-2-workers"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-east-2 --cluster=eks01 --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-eks01-nodegroup-ng-2-workers": ResourceNotReady: failed waiting for successful resource state
```

**Comment by mikestef9** [comment]
This functionality is available as part EKS generally available support for Arm-based instances. See launch [blog](https://aws.amazon.com/blogs/containers/eks-on-graviton-generally-available/) for more details.
