### ISSUE TITLE
[ECS] [request]: Capacity reservation limited to 200%

### ISSUE THREAD

**Issue by Hobbit44** [aws/containers-roadmap#961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Remove the maximum capacity reservation boundary. Currently its 200%.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
With the top capacity reservation set at 200% if a service is trying to scale beyond that then it ends up step scaling as the capacity provider only thinks it only needs to add one instance. where the target tracking scaling it ads should be able to calculate how many instances to add from the capacity reservation. This would greatly increase the scaling speed of smaller applications.

**Comment by anoopkapoor** [comment]
Hi @Hobbit44 can you clarify the ask please? The 200% is only for the very first scale out when scaling out from 0. Besides that there is no capacity reservation boundary.

**Comment by Hobbit44** [comment]
Hi @anoopkapoor. Sure, It seemed as though it was that even though i had reqested a 1000% increase, say, it only seemed to scale at 200% increments. So if i started at a desired service count of 1, it would scale to 2, then 4, then 8 and so on. that was even after manually setting a number of containers requiring at least 10 instances at full capacity.

**Comment by anoopkapoor** [comment]
Thanks, @Hobbit44. Do you still have a setup where you are seeing this behavior? Can you let me know the steps to reproduce the issue?

**Comment by Hobbit44** [comment]
@anoopkapoor Sorry this took a while. I've built a terraform file that should give you everything you need. 
[main.tf.txt](https://github.com/aws/containers-roadmap/files/5451591/main.tf.txt)

If you spin this up, you should start with 1 container. Then if you change the desired number to, say, 50. I would expect it to (once the scaling alarms go off) scale the number of instances straight to 50 as that would be how many instances you need to run all of the containers. 
512mb per service
983mb (reservable) per instance leaves 471mb over means 1 container per instance.

The reason I think its a capacity reservation issue is because this is what Cloudwatch shows for that capacity provider for that cluster.
![image](https://user-images.githubusercontent.com/21823930/97432429-dabfad80-1913-11eb-914d-1c948aafddfc.png)

I would expect it to jump to 5000% to handle full capacity. But even then, if it was just capped at 200% it should stay there until all the containers are running, but weirdly it drops to 150 after the first container starts.

In terms of autoscaling group, its only starting one instance at a time. This could be related, or could just be a symptom.
![image](https://user-images.githubusercontent.com/21823930/97432767-65a0a800-1914-11eb-97d1-4bea3955087a.png)

Hope that helps.

**Comment by anoopkapoor** [comment]
hi @Hobbit44 !
I went over your Terraform file and see that your ASG spans across multiple Availability Zones. The behavior in this case was that the scaling out would be limited by the minScalingStepSize specified in the capacity provider configuration (default for which is 1). And hence the behavior you were seeing.

But I have some good news, we just released this today: https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ecs-cluster-auto-scaling-now-offers-more-responsive-scaling/

If you can give the same configuration another try, you should see more responsive scaling as you expected.
