### ISSUE TITLE
[Fargate] [EKS]: Fargate EKS on Cape Town

### ISSUE THREAD

**Issue by DJ-Lakewood** [aws/containers-roadmap#962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
EKS Fargate on Cape Town.

**Which service(s) is this request for?**
Fargate EKS.

**Tell us about the problem you're trying to solve.
Since Fargate EKS, and Amazon EC2 is the only thing that can get EKS.
**Are you currently working around this?
By telling Amazon/ or by this post.

**Additional context**
Nothing.

**Attachments**
![EXFtxCuWAAAQkZ4](https://user-images.githubusercontent.com/67068793/85919757-92618780-b86e-11ea-80af-911f4ea90c11.jpeg)

**Comment by connor-cress** [comment]
Is the only instance of a suggestion related to Fargate in Cape Town? Do you know if the containers team is currently working on this in the background?

**Comment by kizz417** [comment]
This is necessary for EKS to work ?

**Comment by mikestef9** [comment]
Closing as this launched https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-now-available-cape-town-milan/
