### ISSUE TITLE
[ECR] [request]: Support for Alpine 3.12 on Vulnerability Scans

### ISSUE THREAD

**Issue by dsalamancaMS** [aws/containers-roadmap#963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Add support for Alpine 3.12 on vulnerability scans

**Which service(s) is this request for?**
ECR

**Current Behavior**
UnsupportedImageError: The operating system 'alpine' version 'v3.12' is not supported.

**Comment by jdnva** [comment]
help us!

**Comment by BWhitfield** [comment]
:+1:

**Comment by booleanbetrayal** [comment]
I just noticed that this has been implemented in ECR. Guessing this issue can be closed @rpnguyen .

**Comment by janario** [comment]
Confirmed here, my image based on alpine 3.12 is scanned without problems now

:+1:

**Comment by booleanbetrayal** [comment]
cc: @dsalamancaMS

**Comment by michaelb990** [comment]
Correct, the fix for this was deployed last week. Thanks for your patience!
