### ISSUE TITLE
[EKS] [FARGATE]: Support in Mumbai region

### ISSUE THREAD

**Issue by Paritosh-Anand** [aws/containers-roadmap#972]
Needed EKS FARGATE availability in Mumbai region, to move few of our workloads from ECS to EKS

Presently EKS with FARGATE is not there in Mumbai - https://docs.aws.amazon.com/eks/latest/userguide/fargate.html

**Comment by deepaksood619** [comment]
#620

**Comment by tabern** [comment]
solved by #829

**Comment by Paritosh-Anand** [comment]
Thanks, will be trying it out this week.
