### ISSUE TITLE
[EKS] [request]: Provide a way to get the latest kubernetes version of EKS.

### ISSUE THREAD

**Issue by yutachaos** [aws/containers-roadmap#982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I want an endpoint or cli function that can get the current available version of EKS.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

When a new EKS version becomes available, I want to run automatic tests against the cluster.

For example, the following cli.

```
aws eks available-versions 
{
   "versions":[
      "1.17.6",
      "1.16.8",
      "1.15.11"
   ]
}
```

or Provide such information endpoint.

**Are you currently working around this issue?**
Not done yet.

**Comment by berrac-hp** [comment]
It would be interesting if such api call provides not only the supported kubernetes versions but also the recommended versions of aws-cni, coredns and kube-proxy for each version...

**Comment by yuval-orca** [comment]
it will be great if this CLI command will list **all** currently available EKS versions so that we'll be able to know when a new version has launched and also **when a version has been deprecated** so that we'll create automation around it.

**Comment by evertonevaristo** [comment]
maybe this could help as a temporary solution:

`aws eks describe-addon-versions | jq -r ".addons[] | .addonVersions[] | .compatibilities[] | .clusterVersion" | sort | uniq | tail -n 1`

**Comment by mikestef9** [comment]
Moving to We're working on it. The API will look something like 

```
aws eks describe-cluster-versions 
{
  "clusterVersions": [
    {
      "clusterVersion": "string", #EKS cluster version in major.minor format, used as input when creating a cluster
      "clusterType": : "string", #Valid values are "eks" or "eks-local-outposts"
      "defaultPlatformVersion": "string", # EKS platform version. Only the latest platform version is returned
      "defaultVersion": boolean, #Flag to indicate if the cluster version is default or not when creating a new cluster for the specified cluster type
      "clusterVersionDescription": "string",
      "releaseDate": number,
      "endOfStandardSupportDate": number, 
"endOfExtendedSupportDate": number, 
      "status": "string" #unsupported, standard-support, extended-support
    },
    ...
  ]
}

```

**Comment by sriramranganathan** [comment]
Amazon Elastic Kubernetes Service (EKS) now lets you programmatically access availability of Kubernetes versions. Check out this    what's new blogpost for more details

https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-eks-access-kubernetes-version-availability/
