### ISSUE TITLE
[ECR] [request]: Anonymous pulls

### ISSUE THREAD

**Issue by rpnguyen** [aws/containers-roadmap#990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
A configuration to allow images to be pulled anonymously

**Which service(s) is this request for?**
ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want a repository where I can define strict push controls but also allow anyone to pull it, even if the caller does not have an AWS account.

**Are you currently working around this issue?**
Deploying a custom proxy like https://github.com/catalinpan/aws-ecr-proxy

**Comment by mwarkentin** [comment]
@rpnguyen looks like this is coming! 

https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/

**Comment by omieomye** [comment]
This is now available in the ECR Public extension of Amazon ECR. https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/

**Comment by mtricolici** [comment]
AWS public ECR requires you to have an aws account and invoke a docker login.. this is very ugly..

why a public ecr pull requires authentication?

```
$docker pull public.ecr.aws/amazonlinux/amazonlinux:latest
Error response from daemon: pull access denied for public.ecr.aws/amazonlinux/amazonlinux, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.
```

**Comment by mreferre** [comment]
@mtricolici I believe your issue is related to this: https://github.com/aws/containers-roadmap/issues/1296

**Comment by mtricolici** [comment]
@mreferre exactly. thanks for reply.. after invoking 'docker logout public.ecr.aws' I can now pull public images :)
