### ISSUE TITLE
[Fargate] [bug]: startTimeout is not being timed correctly, leading to premature task termination during task launch

### ISSUE THREAD

**Issue by ddyzhang** [aws/containers-roadmap#991]
The Fargate team is currently tracking a known issue in Fargate PV 1.4 where the specified `startTimeout` for container dependencies in the ECS Task Definition is not being timed correctly during task launches. Some customers who rely on the `startTimeout` field would see intermittent/consistent task launch failures, even if their containers are starting within the specified timeout.

To temporarily mitigate this issue, please raise the `startTimeout` values in the ECS Task Definition.

Additional context for this issue:

> Providing a quick update on this issue from some offline discussions with @dekimsey:

>> After further investigation, I think we have an idea of what's going on here. There is a known bug in Fargate PV 1.4 where the `startTimeout` for container dependencies is not being handled correctly. This bug causes premature task termination even when customer containers come online before the configured timeout. The fix for this issue is currently pending production release.
>>
>> As to why this issue is isolated to eu-central-1a and 1b, our best theory right now is that perhaps eu-central-1c exhibits slightly lower network latency than the other two availability zones.

> In the meantime, those affected by this issue can temporarily mitigate the problem by bumping up any `startTimeout` values in the ECS task definition.

_Originally posted by @ddyzhang in https://github.com/aws/containers-roadmap/issues/898#issuecomment-660327127_

**Comment by SaloniSonpal** [comment]
We recently deployed changes to fix this issue, so resolving this for now. Please let us know if you still notice anything off, and we'd be happy to take a look into it.
